"""PTE Listening Bank 4b: MCQ Single Answer (50 items)
Canonical type_id: 'pte-listening-mcsa'
Live type_name: 'MCQ Single Answer'

Each item: (title, recording, question, correct option, three wrong options, why).
Wrong options are contradicted by, or absent from, the recording. The correct option
rotates through A-D. Recordings are short talks and lecture extracts on economics,
psychology, sociology, media studies, education and linguistics.
"""

LMCSA_RAW = [
    ("A floor under alcohol prices",
     "Right, let's look at a policy that economists and doctors both followed very closely. In May 2018, Scotland became the first country in the world to set a minimum price for each unit of alcohol sold. The level was fifty pence a unit. Now, notice what this does and doesn't do. It isn't a tax, so the extra money goes to the shops, not to the government. And it barely changes the price of a drink in a pub, which was already well above the minimum. What it does hit is very cheap, strong drink sold in supermarkets, particularly high-strength cider, which is bought mainly by the heaviest drinkers. That was the whole point. An evaluation published in 2023 estimated that deaths caused directly by alcohol were about thirteen per cent lower than they would otherwise have been, with the biggest gains in the poorest areas.",
     "Which drinks were most affected by the policy?",
     "Cheap, strong drinks sold in supermarkets",
     ["Drinks served in pubs and bars", "Expensive wines and spirits", "Drinks bought by occasional drinkers"],
     "The speaker says the minimum price hit very cheap, strong drink sold in supermarkets, such as high-strength cider."),
    ("Goodhart's warning",
     "There's a principle named after the British economist Charles Goodhart, and it's usually summed up like this: when a measure becomes a target, it stops being a good measure. Goodhart was writing about monetary policy in the 1970s, but the idea turns up everywhere. Take hospitals. Suppose you judge them on how many patients wait more than four hours in the emergency department. Sounds sensible. But once managers know that number is being watched, some will find ways to improve the number without improving the care, for example by moving patients onto a ward just before the deadline, simply to stop the clock. The figure gets better; the patients aren't necessarily any better off. Schools face the same pressure with exam league tables. So the lesson isn't that we should stop measuring things. It's that a single number, once people are rewarded for it, tends to lose the very information that made it useful in the first place.",
     "What is the speaker's main point about targets?",
     "A figure that people are rewarded for can stop reflecting what it was meant to measure",
     ["Hospitals should no longer be judged on waiting times", "Economists introduced targets to improve public services", "Exam league tables give the most accurate picture of schools"],
     "The speaker says measuring is still worthwhile, but a single number loses its information once people are rewarded for it."),
    ("Rat tails in Hanoi",
     "Historians of economics like a good example of a reward that backfired, and one of the best documented comes from Hanoi in 1902, when the city was under French rule. The new sewers had filled up with rats, and there were fears of plague. So the authorities offered a small payment for every rat killed. To save officials from handling the bodies, people only had to hand in the tail. At first the scheme seemed to work; thousands of tails came in every day. But then officials started noticing rats running around with no tails. People were catching them, cutting the tails off and letting them go, so they could breed and produce more rats, and more income. There were even reports of people farming rats on the edge of the city. The scheme was dropped. And the lesson for anyone designing incentives is pretty simple: people respond to what you pay for, not to what you meant.",
     "Why did the scheme fail?",
     "People were paid for tails, so they had a reason to keep rats alive",
     ["Officials refused to handle the dead rats", "The payment was too small to interest anyone", "The sewers were closed before the scheme began"],
     "Because only the tail was needed, people released tailless rats to breed and earn more."),
    ("Ostrom and shared pastures",
     "For a long time, many economists accepted an argument known as the tragedy of the commons. The idea was that if a resource, say a pasture or a fishing ground, is shared by everyone, each person has a reason to take as much as they can, and the resource ends up ruined. The usual answers were either to hand it over to the state or to divide it up into private property. The political economist Elinor Ostrom questioned this. She spent years studying real communities, from Swiss mountain villages sharing grazing land to fishing communities on the coast of Turkey. And she found that many of them had managed shared resources successfully for generations, without either solution. The ones that worked tended to have clear rules about who could use the resource, ways for members to monitor each other, and penalties that increased step by step for anyone who broke the rules. In 2009 she became the first woman to win the Nobel Prize in economics.",
     "What did Ostrom's research show?",
     "Communities could manage shared resources well with their own rules",
     ["Shared resources are always ruined unless they are privatised", "State ownership is the best way to protect grazing land", "Fishing communities are unable to monitor each other"],
     "Ostrom found communities that had managed shared resources for generations without state or private ownership."),
    ("Why price tags stay put",
     "Here's a puzzle. If demand for a product changes from week to week, why don't firms change their prices from week to week? Economists have several answers, and one of them goes by the name of menu costs. The name comes from restaurants: every time a restaurant changes its prices, it has to reprint its menus. That's a small cost, but it's a real one. For a supermarket, it might mean relabelling thousands of shelves; for a mail-order firm in the past, it meant printing a whole new catalogue. But the bigger cost may be with customers. Surveys of managers suggest that many avoid raising prices because they're worried about annoying regular customers, who might take their business elsewhere. So firms tend to wait, and then change prices in bigger steps. And that matters for the whole economy, because it means prices adjust slowly, which is one reason changes in interest rates take time to have their full effect.",
     "According to the speaker, what may be the biggest reason firms avoid changing prices?",
     "Fear of upsetting regular customers",
     ["The cost of reprinting menus", "Rules set by the central bank", "Pressure from competing supermarkets"],
     "The speaker says the bigger cost may be with customers, as managers worry about annoying regulars."),
    ("Mugs in a classroom market",
     "In a well-known experiment published in 1990, students were split into two groups at random. Half were given a coffee mug with their university's logo on it; the other half got nothing. Then a small market was set up. Students with mugs could sell them, and students without mugs could buy them. Now, because the mugs had been handed out at random, you'd expect about half of them to change hands. In fact, very few trades happened at all. The reason was that owners asked for roughly twice as much as buyers were willing to pay. Simply owning the mug, even for a few minutes, seemed to make it more valuable to them. This is called the endowment effect. It helps explain why people hang on to things they'd never buy at the same price, from old clothes to shares that have lost value, and why free trial periods can be such a good way of selling things.",
     "Why were so few mugs traded?",
     "Owners valued the mugs much more highly than buyers did",
     ["Buyers did not like the university logo", "The mugs had not been given out at random", "Students were not allowed to keep the money"],
     "Owners asked for about twice what buyers would pay, so few trades took place."),
    ("Bricked-up windows",
     "Between 1696 and 1851, householders in England paid a tax based on the number of windows in their homes. It may sound strange, but from the government's point of view it was actually quite clever. Tax officials didn't need to go into anyone's house or ask about their income. They could simply stand in the street and count. And larger houses, owned by wealthier people, generally had more windows. But the tax changed the way people built and lived. Many owners bricked up windows to cut their bills, and you can still see blocked windows on old buildings today. Some new buildings were designed with fewer windows in the first place. Critics, including doctors, argued that the tax was bad for health, because poorer tenants in crowded buildings were left with very little light and fresh air. And that concern was a major reason why the tax was eventually abolished.",
     "Why did the government find the window tax attractive?",
     "Windows could be counted from outside without questioning anyone",
     ["It encouraged people to build healthier homes", "It was paid mainly by poorer tenants", "Doctors recommended it to improve ventilation"],
     "Officials could count windows from the street without entering houses or asking about income."),
    ("The quizmaster's advantage",
     "In a study at Stanford in 1977, pairs of students were given roles at random. One was the questioner and the other was the contestant. The questioner's job was to write ten difficult general knowledge questions, based on anything they happened to know about, and then ask them. Of course, the contestants struggled, and they got only a small proportion right. Afterwards, everyone was asked to rate the general knowledge of the two people. And here's the interesting part. Observers who'd watched the quiz rated the questioners as far more knowledgeable than the contestants. So did the contestants themselves. They'd all seen the roles being handed out by chance, and yet they ignored the huge advantage of choosing the questions. Psychologists call this tendency, explaining people's behaviour by their character rather than by their situation, the fundamental attribution error.",
     "What did the observers fail to take into account?",
     "The questioners' advantage of writing their own questions",
     ["The contestants' higher level of education", "The fact that the questions were too easy", "The contestants' preparation before the quiz"],
     "Everyone ignored the advantage the questioners had from choosing questions they knew the answers to."),
    ("Two treats or one",
     "In the late 1960s and early 1970s, researchers at Stanford offered young children a choice. They could eat one marshmallow straight away, or wait on their own for up to about fifteen minutes and get two. Follow-up studies years later suggested that the children who'd waited longer did better at school. The finding became famous, and it was often taken to mean that self-control in early childhood shapes success in later life. But the original sample was small, and it was mostly made up of children from a university community. In 2018, researchers repeated the study with a much larger and more varied group of children. They found that the link with later achievement was much weaker, and it shrank even further once they took account of things like family background. In other words, waiting for the second treat may partly reflect a child's circumstances, including whether they've learned that promised rewards actually turn up.",
     "What did the 2018 study find?",
     "The link with later achievement was smaller than first reported",
     ["Children today are less able to wait than in the 1970s", "Self-control has no connection with family background", "The original results were confirmed in a larger group"],
     "The larger study found a much weaker link, which shrank further after family background was considered."),
    ("Lost in a shopping centre",
     "In the 1990s, the psychologist Elizabeth Loftus wanted to find out whether people could come to remember a whole event that had never happened. Her team contacted relatives of each participant and collected three true stories from their childhood. Then they added a fourth, false story: that at about five years old, the participant had been lost in a shopping centre, had been upset, and was eventually helped by an older person and returned to the family. Participants were given all four stories and asked to write down what they remembered. Over a couple of interviews, about a quarter of them said they remembered the false event, at least in part, and some even added details of their own. Now, the study was small, but it had a major influence, particularly on how courts treat memories that only come back after repeated questioning.",
     "What was the purpose of the study?",
     "To test whether people could recall events that never took place",
     ["To find out why children get lost in shopping centres", "To compare the memories of participants and their relatives", "To train police officers in interview techniques"],
     "Loftus wanted to know whether people could come to remember an event that had never happened."),
    ("Explaining how a zip works",
     "Here's a simple test you can try on yourself. How well do you understand how a zip works? On a scale of one to seven, give yourself a score. Now try to explain, step by step, exactly how it works. In a series of studies published in 2002, psychologists at Yale asked people to do just that, with everyday objects like zips, flushing toilets and cylinder locks. After trying to write detailed explanations, most people lowered their scores, sometimes by quite a lot. They'd confused familiarity, knowing what a thing looks like and how to use it, with actually understanding how it works. The researchers called this the illusion of explanatory depth. And later work has suggested that asking people to explain how a proposed policy would work, rather than just giving reasons for supporting it, can make them less confident and less extreme in their views.",
     "What happened after people tried to explain how the objects worked?",
     "They gave their own understanding a lower rating",
     ["They became more confident in their knowledge", "They were able to repair the objects", "They preferred objects they understood"],
     "After attempting detailed explanations, most people lowered their scores."),
    ("Radishes and biscuits",
     "In the late 1990s, a series of experiments seemed to show that self-control works like a muscle that gets tired. In one well-known study, hungry participants were told to eat radishes while a plate of freshly baked chocolate biscuits sat right in front of them. Afterwards they gave up sooner on a difficult puzzle than people who'd been allowed to eat the biscuits. The idea, called ego depletion, spread quickly, and hundreds of studies appeared to support it. But in 2016, a large project involving more than twenty laboratories repeated a standard version of the experiment, using exactly the same procedure in every lab. Taken together, they found an effect close to zero. Now, that doesn't necessarily mean the idea is completely wrong, and researchers still disagree about it. But it's become one of the main examples in the debate about why some well-known findings in psychology can't be repeated.",
     "What did the 2016 project find?",
     "Almost no evidence of the original effect",
     ["Stronger results than the first studies", "That radishes improve concentration", "That the effect appears only in hungry people"],
     "More than twenty laboratories together found an effect close to zero."),
    ("Mozart and puzzle scores",
     "In 1993, a short paper reported that college students who listened to ten minutes of a Mozart sonata did slightly better on a spatial reasoning task than students who sat in silence. The improvement lasted only about fifteen minutes, and there were just thirty-six participants. But the press turned this into a much bigger claim: that listening to Mozart makes you more intelligent, and that it would even help babies. Products followed, and in 1998 the governor of the US state of Georgia proposed giving every newborn a classical music CD. Later researchers struggled to reproduce the result. When they did find a small boost, it seemed to come from being in a better mood or feeling more alert, and listening to other music people enjoyed, or even hearing an exciting story, could produce much the same thing. Learning to play an instrument is a different matter, but that's a separate area of research.",
     "According to later research, what explained any small improvement?",
     "Listeners being more alert or in a better mood",
     ["Something special about Mozart's music", "Playing an instrument for ten minutes", "Sitting in silence before the task"],
     "Later studies linked any boost to mood and alertness, which other music or a story could also produce."),
    ("The spilled cup of coffee",
     "In 1966, the social psychologist Elliot Aronson played students a recording of a man taking part in a quiz. In some versions, the man answered almost every question correctly; in others, he did rather badly. And in some versions, near the end, he clumsily knocked a cup of coffee all over himself. So which candidate did listeners like most? The answer was the highly competent man who spilled the coffee. His small accident seemed to make him more human and easier to relate to. But for the less competent man, the same accident made him seem even less appealing. This became known as the pratfall effect. The key point is that a mistake only helps if people already think you're good at what you do. Later studies have added further conditions, and it doesn't work for everyone, but it's often mentioned in advice for public speakers and managers.",
     "When did the accident make the man more likeable?",
     "When he had already shown he was highly competent",
     ["When he had answered most questions wrongly", "When listeners were told it was deliberate", "When it happened at the start of the quiz"],
     "The mistake helped only the competent man; it made the less competent man seem less appealing."),
    ("Walking through doorways",
     "You've probably walked into a room and immediately forgotten why you went in there. The psychologist Gabriel Radvansky and his colleagues at the University of Notre Dame looked into this. In one set of studies, participants moved through rooms, some in a virtual environment and some in a real laboratory, picking up objects and putting them down. Every so often they were asked what they were carrying. People forgot more after walking through a doorway than after walking the same distance within a single room. The researchers' explanation is that the mind divides experience into episodes, and a doorway marks the boundary between one episode and the next. Information from the previous episode becomes a little harder to get at. So it isn't just that time has passed or that you've been distracted; the boundary itself seems to matter. And going back to the original room often helps.",
     "What explanation do the researchers give?",
     "A doorway marks the end of one episode and the start of another",
     ["People are distracted by objects in the new room", "Walking any distance makes people forget", "Virtual rooms confuse the brain more than real ones"],
     "The researchers say the mind divides experience into episodes, with a doorway as the boundary."),
    ("Ninety seconds in cold water",
     "Daniel Kahneman and his colleagues ran an experiment in the early 1990s that seems, at first, to make no sense at all. Participants put one hand in painfully cold water for sixty seconds. On another occasion, they put the other hand in water at the same temperature for sixty seconds, but then kept it there for an extra thirty seconds while the water was warmed very slightly, by about one degree. So the second trial contained all the discomfort of the first, plus a bit more. Yet when they were asked which trial they'd rather repeat, most people chose the longer one. Kahneman's explanation was that we don't remember experiences as a total. What we remember is dominated by the most intense moment and by how the experience ends. This idea, known as the peak-end rule, has been applied to medical procedures, holidays and even the design of customer service.",
     "Why did most people choose to repeat the longer trial?",
     "It ended in a less unpleasant way",
     ["The water was warmer throughout", "It lasted for a shorter time overall", "They felt no discomfort during it"],
     "Memory is dominated by the peak and the end, and the longer trial ended with slightly warmer water."),
    ("Acquaintances and new jobs",
     "In the early 1970s, the sociologist Mark Granovetter interviewed people living in a suburb of Boston who had recently changed jobs. Many had heard about their new job through a personal contact, which wasn't surprising. What was surprising was who that contact was. More often than not, it wasn't a close friend or a member of the family. It was an acquaintance, someone they saw only now and then, like a former colleague or a friend of a friend. Granovetter called these weak ties. His explanation was that our close friends tend to know the same people and hear the same news that we do. Acquaintances move in different circles, so they're more likely to pass on information we haven't already heard. His 1973 paper became one of the most widely cited in sociology, and a large study of a professional networking site in 2022 found broadly similar results.",
     "According to Granovetter, why are acquaintances useful when looking for work?",
     "They have access to information that close friends lack",
     ["They are more willing than friends to recommend people", "They usually work for the same employer", "They are seen more often than close friends"],
     "Acquaintances move in different circles and pass on news we have not already heard."),
    ("A word meant as a warning",
     "The word meritocracy is now used almost entirely as praise. It suggests a fair society where people get ahead through ability and effort rather than family or wealth. But the word was meant as a warning. It first became widely known through a 1958 book by the British sociologist Michael Young, called The Rise of the Meritocracy. The book was a satire, written as if by a historian looking back from the year 2033. In it, society is run by people selected through intelligence tests and exams. The successful come to believe they fully deserve their position, while those at the bottom are told that their failure is entirely their own fault. Young's point was that a society like that could be even harsher than the old one. And near the end of his life, he complained that his warning had been taken as a recommendation.",
     "What was Young's attitude to meritocracy?",
     "He thought it could produce a harsh and unfair society",
     ["He believed it was the fairest possible system", "He thought exams should replace family connections", "He predicted it would never be adopted"],
     "His book was a satire warning that such a society could be harsher than the old one."),
    ("Ten-pin leagues",
     "In 2000, the American political scientist Robert Putnam published a book called Bowling Alone. Its title came from a striking observation: more Americans were going ten-pin bowling than ever before, but fewer of them were bowling in organised leagues. For Putnam, this was a symbol of something much bigger. Drawing on a huge range of data, he argued that since the 1960s Americans had been joining fewer clubs, going to fewer community meetings, and spending less time with their neighbours. He called the value of these networks social capital, and he linked its decline to lower trust between people and weaker local communities. He suggested several causes, including longer commutes and, most of all, television, which kept people at home. Critics have pointed out that people may simply have moved into new kinds of groups, including online ones, but the book shaped debates about community on both sides of the Atlantic.",
     "What did Putnam see as the most important cause of the decline?",
     "Television keeping people at home",
     ["The popularity of ten-pin bowling", "The growth of online groups", "A shortage of community meeting places"],
     "Putnam named several causes but said television, which kept people at home, mattered most."),
    ("About one hundred and fifty",
     "Why do so many human groups seem to settle at around the same size? In the 1990s, the anthropologist Robin Dunbar noticed that among monkeys and apes, species with a larger neocortex, that's the outer layer of the brain, tended to live in larger social groups. Using the size of the human brain, he predicted that people could maintain meaningful relationships with about one hundred and fifty others. He then went looking for evidence and found groups of roughly this size in many places, from traditional farming villages to hunter-gatherer communities. The figure is now known as Dunbar's number. It isn't meant to be precise, and other researchers, using different statistical methods, have produced estimates that are far lower and far higher. But it's been taken up by companies, some of which split offices or teams once they grow much beyond that size.",
     "How did Dunbar first arrive at his estimate?",
     "By relating brain size to group size in primates",
     ["By counting the members of farming villages", "By asking companies about the size of their teams", "By surveying people about their friendships"],
     "He predicted the figure from human brain size, based on the link he found in monkeys and apes; villages were later evidence."),
    ("Credit for the famous",
     "In 1968, the sociologist Robert Merton described a pattern he'd noticed in science. When a well-known scientist and an unknown one make similar contributions, perhaps as co-authors, or when they make the same discovery independently, the famous scientist tends to get most of the credit. Merton interviewed Nobel prize winners, and several of them described this happening, sometimes to their own discomfort. He called it the Matthew effect, after an old line about the rich getting richer. And it builds on itself. Recognition brings funding, good students and attention, which lead to more discoveries and more recognition. Researchers have since found similar patterns in how often papers are cited and in who receives grants. One consequence is that small early differences, even differences that are down to luck, can grow into very large gaps between careers.",
     "What is one consequence of the pattern described?",
     "Small early differences can grow into large gaps between careers",
     ["Unknown scientists usually receive more funding", "Nobel prize winners refuse to work with co-authors", "Papers by famous scientists are cited less often"],
     "Recognition builds on itself, so small or lucky early differences can become large gaps."),
    ("An anthropology of ourselves",
     "In 1937, three young men in Britain, an anthropologist, a poet and a film-maker, started a project with an unusual aim: to create what they called an anthropology of ourselves. The project was named Mass Observation. Instead of studying distant societies, they wanted to record the everyday lives of ordinary British people. They recruited hundreds of volunteers to keep diaries and to answer open questions about their habits and opinions, and they sent observers to note down what went on in pubs, dance halls and on the street. Critics at the time found it amateurish, and some people didn't like being watched. But the material turned out to be extremely valuable to historians, because it records how people actually lived and felt, in their own words, not just what official statistics said. The project was revived in 1981 at the University of Sussex, and volunteers are still writing about their lives today.",
     "Why has the material become valuable to historians?",
     "It records ordinary people's lives and feelings in their own words",
     ["It contains the official statistics of the period", "It was produced by professional researchers", "It describes societies outside Britain"],
     "The diaries and observations show how people actually lived and felt, beyond official statistics."),
    ("Letters to a Boston stockbroker",
     "In 1967, the psychologist Stanley Milgram tried to measure how closely connected people are. He gave letters to volunteers in Nebraska and Kansas and asked them to get each letter to a particular stockbroker in Boston. There was a rule, though: they couldn't post it to him directly unless they knew him personally. Instead, they had to send it on to someone they knew on first-name terms who they thought was more likely to know him, and that person would do the same. Most of the letters never arrived. But of those that did, the average number of steps was around six, which is where the phrase six degrees of separation comes from. It's worth being careful here, because so many chains broke, and the letters that got through may not have been typical. Still, much larger studies using email and social media have since found similarly short chains.",
     "Why does the speaker urge caution about the results?",
     "Most of the chains were never completed",
     ["The letters were sent by post rather than email", "The volunteers all knew the stockbroker", "Only a handful of letters were sent"],
     "The speaker warns that so many chains broke that the successful letters may not have been typical."),
    ("Rival groups at a summer camp",
     "In the summer of 1954, the psychologist Muzafer Sherif took a group of eleven-year-old boys to a summer camp in Oklahoma. The boys didn't know they were part of a study. At first they were split into two groups, which were kept apart, and each quickly developed its own name and its own habits. Then the researchers set up a series of competitions between the groups, with prizes for the winners. Hostility grew fast, with name-calling and raids on each other's cabins. Simply bringing the boys together for meals or films didn't help; in fact it often made things worse. What finally reduced the conflict was giving them problems that neither group could solve alone, such as repairing the camp's water supply. Working towards these shared goals gradually brought the groups together. The study's been criticised on ethical grounds, but its conclusion is still widely cited.",
     "What finally reduced the conflict between the groups?",
     "Problems that both groups had to solve together",
     ["Sharing meals and watching films together", "Ending all contact between the groups", "Offering prizes to the winning group"],
     "Shared goals that neither group could reach alone brought the boys together; meals and films did not help."),
    ("The Archers",
     "The Archers, a BBC radio drama about life in a farming village, has been on air since 1951, which makes it the longest-running drama series of its kind in the world. But it wasn't created purely to entertain. After the Second World War, Britain was still short of food, and farmers were being encouraged to use modern methods to produce more. The programme's creator, Godfrey Baseley, had worked on farming programmes before, and the drama was developed with help from the Ministry of Agriculture. The idea was that listeners would pick up practical advice more readily from characters they cared about than from a talk by an expert. So early episodes included storylines about new crops, animal diseases and machinery. Over time the balance shifted, and the stories became more about the characters' lives. But the programme still has an agricultural adviser, and it still deals with farming issues.",
     "Why was the programme originally created?",
     "To pass on farming advice to listeners in an appealing way",
     ["To record the history of village life", "To advertise new farm machinery", "To attract young people to work in cities"],
     "It was developed with the Ministry of Agriculture so that listeners would absorb practical advice through characters."),
    ("The six pips",
     "Listeners to BBC radio will know the six short tones, known as the pips, that are broadcast just before the news on the hour. They were first heard in 1924, and they were introduced at the suggestion of the Astronomer Royal, so that anyone could set a clock accurately. What a lot of people don't realise is how to read them. The first five pips are short, and they mark the seconds leading up to the hour. The sixth pip is longer, and it's the start of that last pip that marks the exact moment the hour begins. Originally, the signal was controlled by clocks at the Royal Observatory in Greenwich. These days it's generated by the BBC itself, using atomic time. And there's one more oddity: on the rare occasions when an extra second, a leap second, is added to the day, listeners hear seven pips instead of six.",
     "Which part of the signal marks the exact start of the hour?",
     "The start of the sixth, longer pip",
     ["The end of the first pip", "The end of the sixth pip", "The fifth short pip"],
     "The speaker says it is the start of the longer final pip that marks the hour."),
    ("A novel for a shilling a month",
     "When Charles Dickens published The Pickwick Papers in 1836 and 1837, it didn't come out as a single book. It appeared in nineteen monthly parts, each costing one shilling, and each with illustrations. That price mattered. A new novel in three volumes was far too expensive for most people to buy, but a shilling a month was within reach of many more readers, and a single copy was often read aloud to a whole household. Sales started slowly, but by the end each part was selling around forty thousand copies. Publishing in parts also shaped the writing. Dickens was often only a few instalments ahead of his readers, so he could respond to how they reacted, developing popular characters and ending each part in a way that made people want to buy the next. In that sense, it's not so different from the way television series are made today.",
     "Why did publishing in parts help Dickens reach more readers?",
     "Readers could afford a small payment each month",
     ["Each part was given away with a newspaper", "The parts were sold in bookshops across Europe", "Dickens finished the novel before the first part appeared"],
     "A shilling a month was affordable for many more people than a three-volume novel."),
    ("Subtitles or new voices",
     "If you watch a foreign film on television in the Netherlands or Sweden, you'll usually hear the original actors, with subtitles along the bottom of the screen. In Germany, Spain or Italy, on the other hand, foreign films are usually dubbed, with local actors recording new voices. Part of the reason is history, and part of it is cost. Dubbing is expensive, so it made more sense in countries with large audiences who all speak the same language. Smaller language markets tended to go for subtitles. Linguists have become interested in this because the subtitling countries also tend to score highly on tests of English. Of course, that doesn't prove subtitles are the cause; these countries differ in lots of other ways too. But studies comparing countries, and experiments in which learners watch subtitled programmes, suggest that regular exposure to original English soundtracks does help, particularly with listening.",
     "Why did smaller language markets tend to choose subtitles?",
     "Dubbing cost too much for small audiences",
     ["Viewers wanted to learn English", "Local actors refused to record new voices", "Governments banned the dubbing of films"],
     "The speaker says dubbing is expensive and made sense only for large audiences sharing one language."),
    ("Arthur Wynne's word-cross",
     "The first crossword is usually credited to Arthur Wynne, a journalist who'd moved to the United States from Liverpool. On the twenty-first of December 1913, he published a puzzle he called a word-cross in the New York World newspaper. It was diamond-shaped and had no black squares, but otherwise it worked much like a modern crossword. Within a few weeks the two halves of the name had been swapped round, and crossword stuck. For about ten years it stayed a fairly minor feature. Then, in 1924, a new publishing company brought out a book of crosswords, which sold hundreds of thousands of copies and started a craze. Some newspapers were dismissive and complained that readers were wasting hours on it. The Times in London didn't publish its first crossword until 1930, and the cryptic style of clue became something of a British speciality.",
     "What started the crossword craze of the 1920s?",
     "A best-selling book of crossword puzzles",
     ["A crossword published in The Times", "The change to a diamond shape", "A competition with large cash prizes"],
     "A 1924 book of crosswords sold hundreds of thousands of copies and started the craze."),
    ("Knowing the ending in advance",
     "Most of us go to some trouble to avoid spoilers, information that gives away the ending of a story. But is all that effort worth it? In 2011, two psychologists at the University of California, San Diego, put this to the test. They gave participants short stories by well-known writers, including mysteries and stories with an ironic twist. Some participants read a story just as it was written; others first read a short paragraph that revealed the ending, as if by accident. Surprisingly, across most of the stories, the people who'd been told the ending in advance said they enjoyed the story more. One possible explanation is that knowing where a story is going makes it easier to follow, so readers can pay more attention to the writing and the details. That said, later studies have produced mixed results, and some have found the opposite, so if you hate spoilers, you're certainly not alone.",
     "What did the 2011 study find?",
     "Readers who knew the ending often enjoyed the stories more",
     ["Readers enjoyed mysteries less than other stories", "Knowing the ending made the stories harder to follow", "Most readers guessed the ending anyway"],
     "Across most stories, people told the ending in advance reported more enjoyment."),
    ("Ceefax",
     "Before the internet, millions of British households got their news, weather and football results from a service called Ceefax. The BBC launched it in 1974. It displayed pages of simple text and blocky graphics on an ordinary television screen, and you called up a page by typing its three-digit number on the remote control. Interestingly, it grew out of work on providing subtitles for deaf viewers, when engineers realised that spare capacity in the television signal could carry other information as well. The pages were sent out one after another in a continuous cycle, which is why you sometimes had to wait several seconds for the page you wanted to appear. Commercial television had its own version. Ceefax finally closed in 2012, when the last analogue television signals in the UK were switched off, and by then most of its users had long since moved online.",
     "Why did viewers sometimes have to wait for a page to appear?",
     "Pages were broadcast one after another in a repeating cycle",
     ["Each page had to be downloaded from the internet", "The remote control had only a few buttons", "Engineers checked every page before it was shown"],
     "Pages were sent out in a continuous cycle, so viewers waited for the one they wanted to come round."),
    ("Evening dramas in Brazil",
     "Can television change how people live? One of the most interesting studies on this question comes from Brazil. For decades, the most popular programmes there have been telenovelas, evening dramas mostly made by a single network, Globo. The main female characters in these dramas typically had few or no children, and many were independent, working women. Brazil's birth rate fell sharply from the 1960s onwards. Economists noticed that Globo's signal reached different parts of the country at different times, as new transmitters were built. So they compared areas that received the network with similar areas that didn't have it yet. In areas that got the signal, birth rates fell faster, especially among poorer women. Of course, lots of other things were changing at the same time, but the gradual spread of the signal gave researchers a rare chance to separate the effect of television from other causes.",
     "How were the researchers able to study the effect of the dramas?",
     "By comparing areas that received the network at different times",
     ["By interviewing the writers of the dramas", "By counting the children of the main characters", "By asking women which programmes they watched"],
     "The signal spread gradually, so areas with and without it could be compared."),
    ("When the local paper closes",
     "Across Britain and the United States, hundreds of local newspapers have closed over the past twenty years, as advertising moved online. Researchers now use the term news desert for places with no regular source of local news. So why should anyone outside journalism care? Well, one striking study in the United States looked at what happened to local councils' finances after their newspaper closed. It found that the cost of borrowing for local government went up in the following years. The researchers' explanation was that, without reporters attending council meetings and checking spending, lenders saw a higher risk of waste or poor management, so they demanded higher interest. Other studies have found that fewer people stand in local elections where local news has disappeared. So a newspaper doesn't just inform its readers. It seems to act as a kind of watchdog, and when it goes, there are real costs.",
     "According to the study, why did borrowing costs rise?",
     "Lenders saw more risk when no reporters were checking spending",
     ["Councils had to pay for their own newspapers", "Advertising income for councils fell", "Fewer people stood in local elections"],
     "Without reporters watching council spending, lenders demanded higher interest."),
    ("The inverted pyramid",
     "Journalism students learn early on to write news in the shape of an inverted pyramid: the most important facts go at the top, and the details follow in order of decreasing importance. A common explanation is that it came from the telegraph. In the nineteenth century, reporters sending stories by telegraph couldn't be sure the whole message would arrive, so they put the essential information first. It's a neat story, but historians who've gone through newspapers from the period aren't convinced. They found that the inverted pyramid only became common towards the end of the century, decades after the telegraph came in. They link it instead to changes in journalism itself, as reporters were expected to be more objective and editors wanted stories that could be cut from the bottom to fit the page. Whatever its origin, it still suits readers who only look at the first paragraph.",
     "What do historians say about the telegraph explanation?",
     "The timing does not match when the style became common",
     ["It is supported by most newspapers of the period", "Telegraph messages always arrived complete", "Editors refused to cut stories from the bottom"],
     "The style became common decades after the telegraph was introduced."),
    ("Forgetting over the holidays",
     "For many years, one of the best-known findings in American education was the idea of summer learning loss: that during the long summer holiday, children forget a significant amount of what they've learned, and that children from poorer families lose the most. Some influential studies suggested that most of the gap in reading between rich and poor pupils built up during the summers, not during the school year. It was a powerful argument for funding summer programmes. But more recent research has raised doubts. When researchers looked again, they found that the size of the loss depended heavily on which tests were used, and some newer data showed little or no widening of the gap over the summer. So the current picture is uncertain. Some children probably do fall back, but the dramatic claims of the past now look a lot less secure.",
     "What is the speaker's view of the evidence now?",
     "Earlier claims about the size of the loss look less reliable",
     ["It clearly shows poorer pupils lose most over the summer", "It proves summer programmes close the gap", "It shows children learn more in summer than in term time"],
     "Newer research found the loss depended on the tests used, so earlier dramatic claims look less secure."),
    ("Rising intelligence scores",
     "In the 1980s, the New Zealand researcher James Flynn drew attention to a remarkable pattern. Scores on intelligence tests had been rising steadily in many countries throughout the twentieth century, by about three points every ten years. Test makers already knew this, which is why they kept revising the scoring to hold the average at one hundred. But Flynn pointed out what it implied: an average person from the 1930s, judged by today's standards, would score well below average. Nobody seriously thinks earlier generations were far less capable in daily life. So what changed? Suggested explanations include better nutrition, smaller families, more years in education, and a world that demands more abstract thinking. Interestingly, some countries, including Norway and Denmark, have seen the rise slow down or even reverse since the 1990s, which suggests the causes are environmental rather than genetic.",
     "What does the recent reversal in some countries suggest?",
     "The changes are caused by the environment rather than by genes",
     ["Tests have become more difficult since the 1990s", "Earlier generations were less capable in daily life", "Nutrition has no effect on test scores"],
     "A reversal within a few decades points to environmental causes rather than genetic ones."),
    ("Homework by age",
     "Does homework actually help pupils learn? Some of the most influential research on this comes from the American psychologist Harris Cooper, who has combined the results of many studies. His conclusion is that the answer depends heavily on age. For secondary school pupils, there's a clear positive link between homework and achievement, at least up to about two hours a night, after which the benefits seem to level off. For primary school children, though, the link is weak, and in some studies it's almost absent. Now, that doesn't mean young children should have no homework at all. Cooper argues that it can still help them build study habits and show parents what's going on in class. But he suggests keeping it short, roughly ten minutes a night for each year of school. And of course, the quality of the tasks matters as much as the time spent on them.",
     "What did Cooper find about homework for primary school children?",
     "Its link with achievement is weak",
     ["It should last about two hours a night", "It damages children's study habits", "It has a stronger effect than for older pupils"],
     "For primary pupils the link is weak and sometimes almost absent."),
    ("First-class degrees",
     "Over the past fifteen years or so, the share of students at British universities graduating with a first-class degree has risen dramatically. In 2010 to 2011, it was roughly one in six. By 2020 to 2021, it was more than a third. Why? Universities argue that teaching has improved, that students work harder because they're paying high fees, and that support for students is better. Critics suspect something else: that universities, competing for students and judged partly on their results, have become more generous in how they mark and classify degrees. The regulator has found that part of the increase can't be explained by students' earlier qualifications or backgrounds. The worry is that if too many students get the top grade, employers can no longer use it to tell candidates apart. Since 2021 the proportion has fallen slightly, as universities have agreed to tighten their practices.",
     "What has the regulator said about the increase?",
     "Part of it cannot be explained by students' earlier results or backgrounds",
     ["It is entirely due to better teaching", "It has made degrees more useful to employers", "It was caused by a fall in tuition fees"],
     "The regulator found part of the rise unexplained by prior qualifications or background."),
    ("The Children's House in Rome",
     "Maria Montessori was one of the first women in Italy to qualify as a doctor. Her interest in education began with her work with children with disabilities, and in 1907 she opened her first school, called the Casa dei Bambini, or Children's House, in a poor district of Rome. The children were aged between about three and six, and many of their parents were out at work all day. Montessori watched them closely and developed an approach that was very different from traditional classrooms. Instead of sitting in rows listening to a teacher, children chose their own activities from specially designed materials, like wooden blocks and letters they could trace with their fingers. Furniture was built to children's size. And the teacher's role was to observe and guide rather than to instruct. Her methods spread quickly, and there are now thousands of Montessori schools around the world.",
     "What was the teacher's role in Montessori's approach?",
     "To observe and guide the children",
     ["To give talks to the whole class", "To choose an activity for each child", "To build furniture for the classroom"],
     "The teacher's role was to observe and guide rather than instruct; children chose their own activities."),
    ("Turning to your neighbour",
     "In the early 1990s, the Harvard physics lecturer Eric Mazur had an unpleasant surprise. His students were getting good marks on standard problems, but when he gave them a simple test of basic concepts, many of them did poorly. They'd learned to apply formulas without really understanding the ideas behind them. So he changed how he taught. In his lectures, he started stopping every so often to ask a conceptual question. Students answered on their own, then spent a couple of minutes trying to convince the person sitting next to them, and then answered again. Very often, the proportion of correct answers rose sharply after the discussion. Mazur's explanation was that a fellow student who's only just understood something is often better at explaining it than a lecturer who learned it long ago. The method, called peer instruction, is now used in universities all over the world.",
     "Why does Mazur think discussion with a classmate helps?",
     "A student who has just understood an idea can explain it more clearly",
     ["Students prefer talking to listening", "Classmates can check each other's formulas", "Lecturers do not understand the concepts well"],
     "A fellow student who has only just understood is often better at explaining than a lecturer."),
    ("Studying solved problems",
     "When students learn a new type of maths problem, the traditional approach is to explain it briefly and then set lots of problems to solve. But research led by the Australian psychologist John Sweller in the 1980s suggested that beginners often learn more from studying worked examples, that is, problems that have already been solved step by step. The reason, according to Sweller's cognitive load theory, is that working memory can only handle a few new pieces of information at a time. A beginner trying to solve a problem uses up that limited space searching for a method, which leaves little room for actually learning how the solution works. As learners become more expert, though, this advantage disappears, and practising problems becomes more useful. Researchers call this the expertise reversal effect. So the best approach changes as students make progress.",
     "According to Sweller, why do beginners benefit from worked examples?",
     "They do not use up working memory searching for a method",
     ["They contain fewer steps than ordinary problems", "They are more interesting than practice problems", "They help experts solve problems faster"],
     "Beginners solving problems spend limited working memory on searching, leaving little for learning."),
    ("Lunch for every infant",
     "Since 2014, every child in the first three years of state primary school in England has been entitled to a free school lunch, whatever their family's income. Before that, free meals were only available to children from low-income families. So why give them to everyone? Part of the case came from a pilot scheme run a few years earlier in two areas, the London borough of Newham and County Durham, where all primary pupils were offered free meals. The evaluation found that children in these areas made more progress in reading and maths than similar children elsewhere. And one argument for offering meals to all children is this: when free meals are only for some, a significant number of eligible families don't claim them, perhaps because of embarrassment, or because applying is complicated. Making the meals universal removes that barrier completely.",
     "According to the speaker, why do some eligible families not claim free meals?",
     "Embarrassment or the difficulty of applying",
     ["The meals are of poor quality", "Their children prefer to bring food from home", "Schools do not tell them about the meals"],
     "The speaker mentions embarrassment and a complicated application process."),
    ("Born in late August",
     "In England, the school year starts on the first of September, so a child born in late August can be almost a full year younger than a classmate born in early September. At the age of five, that's a very large difference, around a fifth of the child's life. Research has consistently found that summer-born children, on average, do less well in tests at primary school. The gap narrows as children get older, but it doesn't disappear completely, and summer-born children are slightly less likely to go to the most selective universities. The same pattern turns up in sport, where children born early in the selection year are overrepresented in youth football academies, because at a young age they're often bigger and stronger. The good news is that it's about relative age, not ability, so some researchers argue that test scores should simply be adjusted for age.",
     "What do some researchers suggest doing?",
     "Adjusting test scores according to children's ages",
     ["Starting the school year in August", "Keeping summer-born children out of sport", "Grouping children by month of birth"],
     "Because the gap reflects relative age, researchers suggest adjusting scores for age."),
    ("Where OK came from",
     "OK is probably the most widely used English word in the world, but for a long time nobody knew where it came from. Theories linked it to Scottish, Greek and several other languages. The mystery was largely solved in the 1960s by the American scholar Allen Walker Read. He found that OK first appeared in print in a Boston newspaper in 1839. At that time, there was a fashion among young, educated writers for humorous abbreviations of deliberately misspelled phrases. OK stood for oll korrect, a joke spelling of all correct. Most of these abbreviations disappeared quickly. OK survived partly because it was used as a slogan during a presidential campaign the following year, which spread it widely. After that it became useful to telegraph operators, and eventually it spread well beyond English.",
     "According to the speaker, what did OK originally stand for?",
     "A deliberately misspelled form of all correct",
     ["A Greek phrase meaning everything is fine", "The name of a telegraph company", "A Scottish expression of agreement"],
     "Read showed OK began as oll korrect, a joke spelling of all correct."),
    ("Counting words for snow",
     "You've probably heard the claim that Inuit languages have dozens, or even hundreds, of words for snow. It's been repeated so often that many people treat it as a simple fact. The story goes back to the anthropologist Franz Boas, who in 1911 mentioned a handful of different words for snow, such as words for falling snow and snow lying on the ground. Over the following decades, writers repeated the claim and inflated the number. The linguist Geoffrey Pullum famously called it a hoax. Part of the problem is how you count words. Languages like Inuktitut build long words by adding parts to a root, so you can create a very large number of words about anything, including snow. On the other hand, English has plenty of snow words too, if you include slush, sleet, blizzard and so on. So the claim tells us more about how facts spread than about the Inuit.",
     "Why is it hard to count words for snow in Inuit languages?",
     "Long words can be built by adding parts to a root",
     ["The languages have no written form", "Boas recorded only words for falling snow", "English speakers cannot pronounce the words"],
     "Inuktitut builds words by adding parts to a root, so the number of possible words is huge."),
    ("Hearing with the eyes",
     "In 1976, two psychologists, Harry McGurk and John MacDonald, were studying how young children perceive speech when they noticed something odd. They'd dubbed a recording of someone saying the syllable ba onto a video of a person's lips saying ga. When they played it back, they didn't hear either sound. They heard da. The explanation is that the brain combines what we hear with what we see, and it produces a compromise when the two don't match. The remarkable thing is that knowing about the illusion doesn't stop it. If you close your eyes, you hear ba clearly; open them, and it changes again. The finding showed that speech perception isn't only about hearing. It helps explain why people find it easier to follow a conversation in a noisy place when they can see the speaker's face, and why badly synchronised video calls can be so hard work.",
     "What happens when people who know about the illusion watch the video?",
     "They still hear the combined sound",
     ["They hear the original recorded syllable", "They can no longer see the lips clearly", "They hear two sounds at the same time"],
     "The speaker says knowing about the illusion does not stop it."),
    ("Um and uh",
     "Most of us were taught that um and uh are signs of careless speaking. But the psychologists Herbert Clark and Jean Fox Tree argued in 2002 that they're not just noise. They studied large collections of recorded conversation and found that speakers seem to use them to signal that a delay is coming. Uh tends to be followed by a short pause, while um tends to come before a longer one. In other words, speakers use them, mostly without being aware of it, to manage the conversation, warning listeners that they're still thinking and don't want to be interrupted. Other studies have found that listeners pay closer attention after hearing um, perhaps because they're expecting something less predictable. So although too many fillers can make a speaker sound unprepared, taking them out completely can make speech sound unnatural.",
     "According to Clark and Fox Tree, what does um usually signal?",
     "That a longer pause is coming",
     ["That the speaker has finished", "That a short pause is coming", "That the speaker disagrees"],
     "Uh comes before short pauses and um before longer ones."),
    ("Light blue and dark blue",
     "Does the language you speak affect what you see? One well-known study looked at the colour blue. English has one basic word, blue, for a wide range of shades. Russian has two separate basic words: goluboy for lighter blues and siniy for darker blues. In 2007, a team of researchers showed Russian and English speakers three squares of blue and asked them to decide which of the bottom two matched the one on top. Russian speakers were faster when the two shades fell on different sides of their light and dark blue boundary. English speakers showed no such advantage. And when the Russian speakers had to remember a string of numbers at the same time, the advantage disappeared, which suggests their language was actively helping them. The effect was small, measured in fractions of a second, but it showed that words can influence quite basic perception.",
     "What happened when Russian speakers had to remember numbers during the task?",
     "Their advantage disappeared",
     ["They became faster than before", "They confused light and dark blue completely", "English speakers became faster as well"],
     "Remembering numbers removed the Russian speakers' advantage."),
    ("A word in every language",
     "Is there any word that exists in every language? A study published in 2013 suggested one strong candidate: huh, the word we use when we haven't quite caught what someone said. A team led by Mark Dingemanse, based in the Netherlands, recorded everyday conversations in ten very different languages from five continents, including Icelandic, Mandarin and a language spoken in Ghana. In every one of them, they found a short word with the same job and a very similar sound: a simple syllable, usually said with a questioning tone. The researchers argue this isn't a coincidence or a sign of a shared origin. Instead, they think the word has developed separately in each language because it's perfectly suited to what it does. It has to be quick and easy to produce at a moment when we're unprepared, and it has to be understood as a question.",
     "Why do the researchers think the word appears in so many languages?",
     "It is ideally suited to a common need in conversation",
     ["All the languages share a single ancient origin", "It was spread by international travel", "It was borrowed from English"],
     "They argue it developed separately in each language because it suits its job so well."),
    ("When bite sounded like beet",
     "Why does English spelling match pronunciation so badly? One major reason is a change called the Great Vowel Shift, which happened roughly between 1400 and 1700. During this period, the long vowels of English changed their pronunciation, one after another. For example, the word bite was once pronounced more like beet, and house sounded more like hoose, as it still does in some Scottish accents. But at the same time, spelling was becoming fixed, partly because of printing, which arrived in England in the 1470s. Printers and writers kept the older spellings even as the sounds moved on. So English ended up with a spelling system that, for many words, records how people spoke over five hundred years ago. And that's one reason why the same letters stand for quite different sounds in English than they do in most other European languages.",
     "Why did English spelling not change along with pronunciation?",
     "Spelling was becoming fixed, partly through printing",
     ["The long vowels changed too quickly to record", "Scottish writers resisted the new sounds", "Printers invented new spellings for every word"],
     "Spelling was being fixed by printing while the sounds continued to change."),
]

LMCSA_ITEMS = []
for idx, (title, transcript, question, correct, wrong, why) in enumerate(LMCSA_RAW, 1):
    assert len(wrong) == 3, f"LMCSA {idx}: need three wrong options"
    slot = (idx - 1) % 4
    texts = wrong[:slot] + [correct] + wrong[slot:]
    letters = "ABCD"
    LMCSA_ITEMS.append({
        "id": f"q-pl105-mcsa-{idx:02d}",
        "type_id": "pte-listening-mcsa",
        "type_name": "MCQ Single Answer",
        "title": title,
        "prompt": question,
        "audio_transcript": transcript,
        "prep_time_seconds": 5,
        "time_limit_seconds": 90,
        "options": [{"id": letters[n], "text": t} for n, t in enumerate(texts)],
        "correct_answers": [letters[slot]],
        "blanks": None,
        "model_answer": None,
        "explanation": f"Option ({letters[slot]}) is correct. {why}",
        "points": 1,
    })
