"""IELTS Listening practice, batch 2: note/form completion drills.

Original Prepyo scripts in the public IELTS Listening completion format: the
answers are heard in the same order as the notes, and each script offers a
distractor (a first answer that is then corrected) as the test does. Not
official, recalled or copied test content.

Each item: (title, script, notes, limit). `notes` is a list of (text with
____ for the gap, [answer, accepted variants...]). `limit` is 'ONE WORD ONLY'
or 'ONE WORD AND/OR A NUMBER'.
"""

from ielts_bank2.listening_lectures_v2 import DRILLS

W1 = 'ONE WORD ONLY'
WN = 'ONE WORD AND/OR A NUMBER'

FILL = [
    ('Joining a gym',
     "Receptionist: Hello, Parkside Gym. Caller: Hi, I'd like to join. What's the monthly fee? Receptionist: It's forty pounds, or thirty-five if you pay for a year in advance. Caller: I'll pay monthly for now. Do I need to bring anything on my first visit? Receptionist: Just a towel. We give everyone a locker, so you don't need a padlock. And your first session is with a trainer called Marco.",
     [('Monthly fee: £____', ['40', 'forty']), ('Bring: a ____', ['towel']), ('First session with: ____', ['Marco'])], WN),
    ('Renting a bicycle',
     "Assistant: Good morning, City Bikes. Customer: I'd like to rent a bike for the weekend. Assistant: Certainly. We have road bikes and mountain bikes, but for the city I'd suggest a hybrid. Customer: A hybrid is fine. Assistant: That's fifteen dollars a day. You'll need to leave a deposit, and we take a passport rather than cash. Customer: No problem. Assistant: Please bring the bike back before six on Sunday.",
     [('Type of bike: ____', ['hybrid']), ('Deposit: customer’s ____', ['passport']), ('Return before: ____ p.m. on Sunday', ['6', 'six'])], WN),
    ('Booking a restaurant table',
     "Waiter: Riverside Kitchen, can I help? Caller: I'd like to book a table for Friday. Waiter: For how many? Caller: Eight people. Oh, sorry, one person can't come, so seven. Waiter: Seven on Friday. Would you like to sit inside or on the terrace? Caller: The terrace, please. Waiter: And the name? Caller: Delaney. D, E, L, A, N, E, Y.",
     [('Number of people: ____', ['7', 'seven']), ('Seating area: the ____', ['terrace']), ('Name: ____', ['Delaney'])], WN),
    ('Evening language course',
     "Woman: I'm calling about the Spanish course. Adviser: Yes, the beginners' class meets on Mondays. It was on Wednesdays last term, but the teacher changed the day. Woman: Monday suits me. Where is it held? Adviser: In the library, on the second floor. The course book costs twenty-two dollars, and you can buy it at the first class.",
     [('Day: ____', ['Monday', 'Mondays']), ('Place: the ____', ['library']), ('Course book: $____', ['22', 'twenty-two'])], WN),
    ('Volunteer at an animal shelter',
     "Coordinator: Thanks for offering to volunteer. Most of our volunteers walk the dogs, but we really need help with cleaning at the moment. Man: That's fine. Coordinator: Great. Shifts start at eight in the morning. Please wear boots because the floors are often wet. And you'll need to complete a short training session on Saturday before you start.",
     [('Main job needed: ____', ['cleaning']), ('Wear: ____', ['boots']), ('Training day: ____', ['Saturday'])], W1),
    ('Lost property enquiry',
     "Officer: Lost property, how can I help? Passenger: I left my bag on the train this morning. Officer: What colour is it? Passenger: It's grey. Well, it's more of a dark green, actually. Officer: Dark green. And what was inside? Passenger: A laptop and a scarf. Officer: Which station did you get off at? Passenger: Kingsford.",
     [('Colour of bag: dark ____', ['green']), ('Contents: laptop and a ____', ['scarf']), ('Station: ____', ['Kingsford'])], W1),
    ('Guided walking tour',
     "Guide: Our walking tour of the old town takes about two hours. We'll finish at the cathedral, not the market as the leaflet says. Tickets are twelve euros for adults. And do bring an umbrella, because the forecast isn't good.",
     [('Duration: ____ hours', ['2', 'two']), ('Finish at: the ____', ['cathedral']), ('Bring: an ____', ['umbrella'])], WN),
    ('Doctor’s appointment',
     "Receptionist: Health centre. Patient: I'd like to see a doctor, please. Receptionist: Dr Patel is free on Thursday at ten. Patient: Could I have something later? Receptionist: Then Thursday at quarter past two. Patient: That's fine. Receptionist: Please arrive ten minutes early and bring your insurance card.",
     [('Doctor: Dr ____', ['Patel']), ('Time: ____ p.m. Thursday', ['2.15', '2:15']), ('Bring: insurance ____', ['card'])], WN),
    ('Community theatre auditions',
     "Director: Auditions for our new play take place in the school hall. We originally planned to use the church, but it's being repaired. You'll need to read a short poem, not a scene from the play. And please send us a photograph by email before the audition.",
     [('Venue: the school ____', ['hall']), ('Prepare to read: a ____', ['poem']), ('Send in advance: a ____', ['photograph'])], W1),
    ('Hiring a room for a party',
     "Manager: The large room holds a hundred people, but it's booked that night. The smaller room holds sixty. Customer: Sixty is enough. Manager: It costs two hundred and fifty pounds for the evening. We provide tables, but you'll have to bring your own decorations. The room must be empty by midnight.",
     [('Capacity: ____ people', ['60', 'sixty']), ('Customer must bring: ____', ['decorations']), ('Leave by: ____', ['midnight'])], WN),
    ('Swimming lessons for children',
     "Instructor: Classes for six-year-olds are on Tuesdays at half past four. Each class has a maximum of eight children. Parent: Do they need goggles? Instructor: No, but they must wear a swimming cap. The course lasts ten weeks.",
     [('Day: ____', ['Tuesday', 'Tuesdays']), ('Children must wear: a swimming ____', ['cap']), ('Length of course: ____ weeks', ['10', 'ten'])], WN),
    ('Farm visit for a school',
     "Farmer: When your class comes to the farm, they'll feed the goats and collect eggs. The visit starts at half past nine. Parking for the coach is behind the barn, not at the front gate. And children should bring a packed lunch because our café is closed on weekdays.",
     [('Children will feed the: ____', ['goats']), ('Coach parking: behind the ____', ['barn']), ('Bring: packed ____', ['lunch'])], W1),
    ('Photography workshop',
     "Organiser: The workshop is for beginners. You don't need an expensive camera; a phone is perfectly good. We'll meet at the harbour, and we'll finish with a visit to a gallery to see some prints. The fee is thirty-five dollars.",
     [('Equipment: a ____ is enough', ['phone']), ('Meeting place: the ____', ['harbour']), ('Fee: $____', ['35', 'thirty-five'])], WN),
    ('Moving house enquiry',
     "Assistant: Speedy Removals. Customer: I'm moving next month and need a van. Assistant: We have a small van, but for a two-bedroom flat you'd need the medium one. Customer: The medium, then. Assistant: Our team will also pack your kitchen items if you like, for an extra fee. And we'll need your new postcode. Customer: It's TW9 4LN.",
     [('Van size: ____', ['medium']), ('Extra service: packing ____ items', ['kitchen']), ('New postcode: ____', ['TW9 4LN'])], WN),
    ('Student accommodation',
     "Officer: The room is in Carter House. It has its own bathroom, but the kitchen is shared with five other students. Rent is paid every month, not every term. The internet is included, but you'll pay separately for electricity.",
     [('Building: ____ House', ['Carter']), ('Shared: the ____', ['kitchen']), ('Paid separately: ____', ['electricity'])], W1),
    ('Cookery class booking',
     "Chef: This week's class is Italian, next week's is Thai. Caller: I'd like the Thai one. Chef: Lovely. We provide aprons and ingredients; please bring a container to take your food home. The class is in the evening, starting at seven.",
     [('Type of food chosen: ____', ['Thai']), ('Bring: a ____', ['container']), ('Starts at: ____ p.m.', ['7', 'seven'])], WN),
    ('Library membership',
     "Librarian: To join, you'll need proof of address, such as a bank statement. You can borrow up to twelve books at a time. Visitor: What about DVDs? Librarian: Those cost a pound each. Books are free, of course.",
     [('Proof needed: bank ____', ['statement']), ('Maximum books: ____', ['12', 'twelve']), ('DVDs cost: £____ each', ['1', 'one'])], WN),
    ('Charity fun run',
     "Organiser: The fun run is five kilometres and starts at the park gates. Runners collect their numbers from the sports centre on the morning of the race. Last year we raised money for the hospital; this year it's for a children's charity. Everyone who finishes gets a medal.",
     [('Distance: ____ km', ['5', 'five']), ('Collect numbers from: the sports ____', ['centre']), ('Finishers receive: a ____', ['medal'])], WN),
    ('Car service booking',
     "Mechanic: Your car's due for its annual service. We can do it on Wednesday. Customer: Can you check the brakes as well? They're making a noise. Mechanic: Of course. It will take about three hours. You can wait in our lounge, or we can drive you to the station.",
     [('Service day: ____', ['Wednesday']), ('Also check: the ____', ['brakes']), ('Time needed: about ____ hours', ['3', 'three'])], WN),
    ('Craft market stall',
     "Organiser: A stall at the craft market costs forty dollars for the day. You'll get a table, but no chairs, so bring your own. The market opens at nine, but stallholders should arrive by eight to set up. We only accept handmade goods.",
     [('Stall fee: $____', ['40', 'forty']), ('Bring your own: ____', ['chairs']), ('Arrive by: ____ a.m.', ['8', 'eight'])], WN),
    ('Recycling collection',
     "Officer: From next month, glass will be collected every two weeks instead of every week. Food waste goes in the brown bin, and garden waste in the green one. Collections happen on Friday mornings, so put your bins out the night before.",
     [('Glass collected every: ____ weeks', ['2', 'two']), ('Food waste bin colour: ____', ['brown']), ('Collection day: ____', ['Friday'])], WN),
    ('Museum membership',
     "Assistant: Annual membership is sixty dollars. It gives you free entry to all exhibitions and a discount in the shop. You'll also receive our magazine four times a year. You can use your card at our sister museum too, which is in Hartford.",
     [('Annual cost: $____', ['60', 'sixty']), ('Discount in the: ____', ['shop']), ('Sister museum in: ____', ['Hartford'])], WN),
    ('Job enquiry at a hotel',
     "Manager: We're looking for a receptionist to work weekends. Applicant: What hours are they? Manager: Saturday and Sunday, from seven until three. You'll need to speak a second language; French would be ideal. The pay is thirteen pounds an hour.",
     [('Position: ____', ['receptionist']), ('Language preferred: ____', ['French']), ('Pay: £____ per hour', ['13', 'thirteen'])], WN),
    ('Pottery course details',
     "Tutor: In the first week you'll learn to make a bowl. In the second, a mug. We fire everything in the kiln at the end of the course. Please wear old clothes, as clay gets everywhere. The course costs ninety pounds, including materials.",
     [('First week: make a ____', ['bowl']), ('Wear: old ____', ['clothes']), ('Cost: £____', ['90', 'ninety'])], WN),
    ('Hiking club trip',
     "Leader: Saturday's walk is along the coast path. We'll meet at the lighthouse at nine. The walk is about fourteen kilometres, so bring plenty of water. There's a café halfway where we'll stop for lunch.",
     [('Meeting point: the ____', ['lighthouse']), ('Distance: about ____ km', ['14', 'fourteen']), ('Bring: plenty of ____', ['water'])], WN),
    ('Opening a bank account',
     "Adviser: For a student account, you'll need your passport and a letter from your university. The account has no monthly fee. You'll receive your card by post within five days, and your PIN in a separate letter.",
     [('Letter from: your ____', ['university']), ('Card arrives within: ____ days', ['5', 'five']), ('PIN sent in a separate: ____', ['letter'])], WN),
    ('Borrowing sports equipment',
     "Assistant: Students can borrow rackets and balls free of charge. You need to show your student card. Items must be returned the same day, by five o'clock. If something is damaged, please report it at the desk.",
     [('Show: your student ____', ['card']), ('Return by: ____ o’clock', ['5', 'five']), ('Report damage at the: ____', ['desk'])], WN),
    ('Wildlife boat trip',
     "Captain: Our boat trips run twice a day. The morning trip is best for seeing seals. Bring a warm jacket, even in summer, as it's windy on the water. Children under five travel free, and adults pay eighteen dollars.",
     [('Best trip for seals: ____', ['morning']), ('Bring: a warm ____', ['jacket']), ('Adult ticket: $____', ['18', 'eighteen'])], WN),
    ('Café job interview arrangement',
     "Owner: Can you come for an interview on Tuesday? Applicant: I have a class then. Could we do Thursday? Owner: Thursday at eleven is fine. Please bring a copy of your CV, and ask for Rosa when you arrive.",
     [('Interview day: ____', ['Thursday']), ('Bring: a copy of your ____', ['CV']), ('Ask for: ____', ['Rosa'])], W1),
    ('Garden centre delivery',
     "Assistant: We deliver within ten miles for free. Further than that, it's eight pounds. Customer: I live twelve miles away. Assistant: Then it's eight pounds. We deliver on Saturdays. Please make sure someone is at home, or tell us where to leave the plants, for example by the garage.",
     [('Free delivery within: ____ miles', ['10', 'ten']), ('Delivery day: ____', ['Saturday', 'Saturdays']), ('Plants can be left by the: ____', ['garage'])], WN),
    DRILLS['Lecture: Urban beekeeping'],
    ('Lecture: Desert plants',
     "Lecturer: Desert plants survive by storing water. Cacti store it in their stems, not their leaves, which have become spines. Many desert plants open their pores only at night, when it is cooler, to reduce water loss. Their roots are often shallow but spread very widely.",
     [('Cacti store water in their: ____', ['stems']), ('Pores open at: ____', ['night']), ('Roots are shallow but spread very ____', ['widely'])], W1),
    DRILLS['Lecture: History of the bicycle'],
    DRILLS['Lecture: Sleep and memory'],
    DRILLS['Lecture: Coral reefs'],
    DRILLS['Lecture: Salt in history'],
    ('Lecture: Noise in offices',
     "Lecturer: Open-plan offices were meant to improve communication, but studies found that people actually spoke face to face less. The main complaint was noise from phone calls. Productivity improved when companies created small quiet rooms.",
     [('Aim of open-plan offices: better ____', ['communication']), ('Main complaint: noise from phone ____', ['calls']), ('Solution: small ____ rooms', ['quiet'])], W1),
    DRILLS['Lecture: Migration of birds'],
    DRILLS['Lecture: Chocolate'],
    DRILLS['Lecture: Glass-making'],
    ('Tour of a science park',
     "Guide: Welcome to the science park. The building on your left houses the robotics lab. The glass building ahead is our new innovation centre, opened in March. Lunch will be in the canteen, which is next to the car park.",
     [('Building on the left: robotics ____', ['lab', 'laboratory']), ('Innovation centre opened in: ____', ['March']), ('Lunch in the: ____', ['canteen'])], W1),
    ('Holiday cottage rental',
     "Owner: The cottage sleeps four. There's a garden with a barbecue, and the beach is a ten-minute walk. Pets aren't allowed, I'm afraid. Check-in is after four o'clock on Saturday, and you'll find the key in a box by the door.",
     [('Garden has a: ____', ['barbecue']), ('Beach: ____-minute walk', ['10', 'ten']), ('Key is in a ____ by the door', ['box'])], WN),
    ('Music festival information',
     "Announcer: The festival runs for three days. Camping is available, but tents must be booked in advance. You can't bring glass bottles onto the site. Free buses run from the railway station every thirty minutes.",
     [('Festival length: ____ days', ['3', 'three']), ('Not allowed: glass ____', ['bottles']), ('Buses every: ____ minutes', ['30', 'thirty'])], WN),
    ('Dentist registration',
     "Receptionist: To register, fill in this form and bring your medical history. Your first check-up will be with Dr Morgan. We send reminders by text message, so please give us your mobile number.",
     [('Bring: your medical ____', ['history']), ('First check-up with: Dr ____', ['Morgan']), ('Reminders sent by: ____', ['text'])], W1),
    ('Art class for adults',
     "Teacher: This term we're doing watercolour painting. Last term was drawing. The class is for twelve people maximum. We'll paint outdoors when the weather is good, usually in the botanic gardens.",
     [('Technique this term: ____ painting', ['watercolour']), ('Maximum class size: ____', ['12', 'twelve']), ('Outdoor location: botanic ____', ['gardens'])], WN),
    ('Community garden plot',
     "Organiser: Each plot is five metres by three. The rent is twenty pounds a year. We supply water, but you'll need your own tools. There's a meeting for new members on the first Sunday of the month.",
     [('Rent: £____ a year', ['20', 'twenty']), ('Bring your own: ____', ['tools']), ('New members meeting: first ____ of the month', ['Sunday'])], WN),
    ('Train ticket enquiry',
     "Clerk: A return to Bristol is forty-two pounds, but if you travel after half past nine it's only twenty-eight. Traveller: I'll go after half nine, then. Clerk: You'll need to change trains at Swindon. The journey takes about two hours.",
     [('Off-peak return: £____', ['28', 'twenty-eight']), ('Change at: ____', ['Swindon']), ('Journey time: about ____ hours', ['2', 'two'])], WN),
    ('University open day',
     "Speaker: The open day starts with a welcome talk in the main hall. After that, you can join a campus tour, which leaves from the library every half hour. Don't miss the careers fair in the afternoon, in the sports centre.",
     [('Welcome talk in: the main ____', ['hall']), ('Tours leave from: the ____', ['library']), ('Afternoon event: careers ____', ['fair'])], W1),
    ('Youth football club',
     "Coach: Training is on Wednesday evenings and matches are on Sunday mornings. Players need shin pads and boots. The yearly fee is sixty-five pounds, which includes a team shirt.",
     [('Matches on: ____ mornings', ['Sunday']), ('Players need: shin ____ and boots', ['pads']), ('Yearly fee: £____', ['65', 'sixty-five'])], WN),
    ('Bike repair workshop',
     "Organiser: Our free bike repair workshop is on the last Saturday of each month, in the car park behind the library. Last month we were in the market square, but it was too windy. Mechanics will show you how to fix a puncture. Please bring your own bike lock, and if possible a small pump.",
     [('Location: car park behind the ____', ['library']), ('Learn how to fix a ____', ['puncture']), ('Bring: bike lock and a small ____', ['pump'])], W1),
]
