"""IELTS Listening practice, batch 2: multiple-choice drills.

Original Prepyo scripts in the public IELTS Listening multiple-choice format
(choose ONE letter, A, B or C). Each script mentions the wrong options too, as
distractors, and `evidence` is the exact words that give the answer. Not
official, recalled or copied test content.

Each item: (title, script, question, [A, B, C], key, evidence).
"""

MCQ = [
    ('Changing a flight', "Agent: Your flight to Lisbon on Monday is full, so we can't move you to that one. There's a seat on Tuesday morning, and one on Wednesday evening. Traveller: I have a meeting on Wednesday, so I'll take the Tuesday flight. Agent: Tuesday morning it is.",
     'Which day will the traveller fly?', ['Monday', 'Tuesday', 'Wednesday'], 'B', "I'll take the Tuesday flight"),
    ('Choosing a gym class', "Man: I thought about yoga, but the times don't suit me, and spinning looks too intense. So I've signed up for the swimming fitness class on Thursday evenings.",
     'Which class has the man chosen?', ['yoga', 'spinning', 'swimming fitness'], 'C', "signed up for the swimming fitness class"),
    ('Why the concert moved', "Organiser: Many people assume the concert moved because of ticket sales, but we sold out in a week. The real reason is that the park's stage failed its safety inspection, so we've moved to the town hall.",
     'Why was the concert moved?', ['Not enough tickets were sold.', 'The stage failed a safety check.', 'The weather was too bad.'], 'B', "failed its safety inspection"),
    ('Cheapest way to the airport', "Assistant: A taxi costs about fifty dollars, and the express train is twenty. But the cheapest option is the number seven bus, which is only four dollars, although it takes an hour.",
     'What is the cheapest way to the airport?', ['taxi', 'express train', 'bus'], 'C', "the cheapest option is the number seven bus"),
    ('A new library service', "Librarian: We've always lent books and DVDs, of course. What's new this year is that members can borrow tools, such as drills and ladders, for up to a week.",
     'What is new at the library this year?', ['lending DVDs', 'lending tools', 'longer loan periods'], 'B', "members can borrow tools"),
    ('Problem with a delivery', "Customer: The sofa arrived on time and the colour is right. The problem is that one of the legs is broken, so it isn't safe to sit on.",
     'What is wrong with the sofa?', ['It arrived late.', 'It is the wrong colour.', 'It is damaged.'], 'C', "one of the legs is broken"),
    ('Research method chosen', "Student: We considered interviews, but they take so long to transcribe. Observation wasn't practical in a hospital. In the end we chose an online questionnaire, which reached far more nurses.",
     'Which research method did the students choose?', ['interviews', 'observation', 'an online questionnaire'], 'C', "we chose an online questionnaire"),
    ('Most popular exhibit', "Guide: Visitors often expect the dinosaur skeleton to be our most popular exhibit, and it's certainly impressive. But according to our surveys, the one people enjoy most is the interactive weather room.",
     'Which exhibit do visitors enjoy most?', ['the dinosaur skeleton', 'the weather room', 'the space gallery'], 'B', "the one people enjoy most is the interactive weather room"),
    ('Reason for a late essay', "Student: I'm sorry my essay is late. I wasn't ill and my computer was fine. I simply couldn't get hold of two of the books I needed from the library until yesterday.",
     'Why was the essay late?', ['The student was ill.', 'The student’s computer broke.', 'Some books were unavailable.'], 'C', "couldn't get hold of two of the books"),
    ('Meeting point for the trip', "Teacher: Last time we met in the car park, and that caused traffic problems. So on Friday, please meet at the front of the school, by the main gate, not at the sports hall.",
     'Where should students meet on Friday?', ['the car park', 'the main gate', 'the sports hall'], 'B', "by the main gate"),
    ('Price of a course', "Receptionist: The full course normally costs three hundred dollars. Students get twenty per cent off, so for you it's two hundred and forty.",
     'How much will the student pay?', ['$200', '$240', '$300'], 'B', "for you it's two hundred and forty"),
    ('Why the café closed', "Owner: People think we closed because of the rent, but the landlord was very fair. Honestly, I just couldn't find enough staff to keep the café open seven days a week.",
     'Why did the café close?', ['The rent was too high.', 'There were not enough staff.', 'There were too few customers.'], 'B', "couldn't find enough staff"),
    ('Best time to visit', "Ranger: Spring is lovely, but the paths are often muddy. Summer is very crowded. If you want to see the birds, the best time to come is autumn, when thousands arrive from the north.",
     'When is the best time to see the birds?', ['spring', 'summer', 'autumn'], 'C', "the best time to come is autumn"),
    ('Main aim of the project', "Tutor: Your project will involve some statistics and a short presentation, but its main aim is to develop your skills in writing a research report.",
     'What is the main aim of the project?', ['to practise statistics', 'to improve presentation skills', 'to develop report-writing skills'], 'C', "its main aim is to develop your skills in writing a research report"),
    ('Choosing accommodation', "Woman: The hotel was too expensive, and the campsite was too far from the town. So we booked a small apartment right in the centre.",
     'Where did the woman decide to stay?', ['a hotel', 'a campsite', 'an apartment'], 'C', "we booked a small apartment"),
    ('Volunteer role', "Coordinator: We have plenty of drivers and our kitchen team is full. What we really need is someone to answer the phone in the office on Tuesday mornings.",
     'What kind of volunteer is needed?', ['a driver', 'a kitchen helper', 'an office assistant'], 'C', "someone to answer the phone in the office"),
    ('Result of an experiment', "Researcher: We expected the plants under blue light to grow tallest, but in fact those under red light grew the most. The plants with no extra light grew least, as predicted.",
     'Which plants grew the most?', ['under blue light', 'under red light', 'with no extra light'], 'B', "those under red light grew the most"),
    ('Parking at the hospital', "Receptionist: The hospital car park is often full by nine. There's no parking on the street outside. Most visitors use the park-and-ride from the shopping centre, which is free.",
     'What do most visitors do?', ['park in the hospital car park', 'park on the street', 'use the park-and-ride'], 'C', "Most visitors use the park-and-ride"),
    ('Change to the timetable', "Announcer: Please note that from Monday, the last bus from the city centre will leave at eleven thirty, not eleven as before. The first bus is unchanged.",
     'What has changed?', ['the time of the first bus', 'the time of the last bus', 'the bus route'], 'B', "the last bus from the city centre will leave at eleven thirty"),
    ('What the tutor liked', "Tutor: Your data collection was fine, though a little limited. The conclusion needs more work. But I was really impressed with your literature review; it was clear and well organised.",
     'Which part of the work did the tutor praise most?', ['the data collection', 'the literature review', 'the conclusion'], 'B', "I was really impressed with your literature review"),
    ('Why she chose the course', "Student: The course isn't the cheapest, and the campus isn't close to home. I chose it because it includes a year working in industry, which should help me find a job.",
     'Why did the student choose the course?', ['It was cheap.', 'It was close to home.', 'It includes work experience.'], 'C', "it includes a year working in industry"),
    ('Difficulty with the survey', "Student: Finding people to take part wasn't hard, and the questions were clear. The difficulty was that many people didn't complete the last section, because it was too long.",
     'What was the problem with the survey?', ['finding participants', 'unclear questions', 'incomplete answers'], 'C', "many people didn't complete the last section"),
    ('Gift for a colleague', "Man: Flowers would die too quickly, and we don't know what books she likes. Let's get her a voucher for the garden centre; she loves gardening.",
     'What will they buy for their colleague?', ['flowers', 'a book', 'a voucher'], 'C', "Let's get her a voucher"),
    ('Reason for visiting the town', "Woman: The town has a famous castle and some lovely beaches, but I went there for the food festival, which happens every September.",
     'Why did the woman visit the town?', ['to see the castle', 'to go to the beach', 'to attend a festival'], 'C', "I went there for the food festival"),
    ('Recommended equipment', "Instructor: You don't need special shoes yet, and we provide helmets. The one thing I'd really recommend buying is a good pair of gloves.",
     'What does the instructor recommend buying?', ['shoes', 'a helmet', 'gloves'], 'C', "a good pair of gloves"),
    ('Cause of the traffic', "Reporter: The traffic this morning wasn't caused by an accident, and there's no roadwork on the bridge. It's simply that the school holidays have ended.",
     'What caused the traffic?', ['an accident', 'roadworks', 'the end of school holidays'], 'C', "the school holidays have ended"),
    ('Feature of the new phone', "Salesperson: The camera is similar to the old model, and the screen size is the same. The big improvement is the battery, which now lasts two full days.",
     'What is the main improvement in the new phone?', ['the camera', 'the screen', 'the battery'], 'C', "The big improvement is the battery"),
    ('Why the bridge was built', "Historian: The bridge is often said to have been built for trade, but records show it was built so that soldiers could cross the river quickly.",
     'Why was the bridge built?', ['for trade', 'for soldiers', 'for tourists'], 'B', "so that soldiers could cross the river quickly"),
    ('How to submit the assignment', "Lecturer: Don't bring a printed copy to my office, and please don't email it to me. Upload it to the online system by Friday at noon.",
     'How should students submit the assignment?', ['in person', 'by email', 'online'], 'C', "Upload it to the online system"),
    ('Type of rooms available', "Receptionist: I'm afraid all our double rooms are taken, and the family suite is booked too. We only have single rooms left for that weekend.",
     'What rooms are available?', ['double rooms', 'a family suite', 'single rooms'], 'C', "We only have single rooms left"),
    ('The speaker’s job', "Speaker: People often think I'm a teacher because I work with children, and I did train as a nurse. But these days I design playgrounds.",
     'What is the speaker’s job now?', ['teacher', 'nurse', 'playground designer'], 'C', "these days I design playgrounds"),
    ('What students must bring', "Tutor: You won't need calculators in the exam, and dictionaries aren't allowed. But please bring a pencil for the diagram question.",
     'What must students bring to the exam?', ['a calculator', 'a dictionary', 'a pencil'], 'C', "please bring a pencil"),
    ('Plans for the weekend', "Woman: I'd planned to go hiking, but the forecast is terrible. My sister wanted to see a film, but I'd rather stay in. So I'll finally finish painting the kitchen.",
     'What will the woman do at the weekend?', ['go hiking', 'see a film', 'decorate'], 'C', "I'll finally finish painting the kitchen"),
    ('Main problem for the town', "Mayor: Crime is low and unemployment has fallen. The main problem for our town now is the lack of affordable housing for young families.",
     'What is the main problem for the town?', ['crime', 'unemployment', 'housing'], 'C', "the lack of affordable housing"),
    ('Feedback on a presentation', "Tutor: Your slides were attractive and you spoke clearly. However, you went over the time limit by five minutes, so practise with a timer.",
     'What should the student improve?', ['the slides', 'the speaking voice', 'the timing'], 'C', "you went over the time limit"),
    ('Why the species declined', "Scientist: Hunting stopped decades ago and the climate here is stable. The species declined because farmers drained the wetlands where it bred.",
     'Why did the species decline?', ['hunting', 'climate change', 'loss of habitat'], 'C', "farmers drained the wetlands"),
    ('Method of payment', "Shopkeeper: We stopped taking cheques years ago, and our card machine is broken today, so I'm afraid it's cash only.",
     'How can the customer pay today?', ['by cheque', 'by card', 'in cash'], 'C', "it's cash only"),
    ('What the club offers beginners', "Member: The club doesn't lend boats to beginners, and there's no discount on membership. But we do run free lessons every Saturday morning.",
     'What does the club offer beginners?', ['boats to borrow', 'cheaper membership', 'free lessons'], 'C', "we do run free lessons"),
    ('Reason for the new policy', "Manager: The new policy isn't about saving money or reducing complaints. It's to protect staff, who were working too many hours.",
     'What is the reason for the new policy?', ['to save money', 'to reduce complaints', 'to protect staff'], 'C', "It's to protect staff"),
    ('Location of the meeting', "Secretary: The meeting was going to be in room twelve, but that's being painted, and the library is too small. We'll use the staff room instead.",
     'Where will the meeting take place?', ['room 12', 'the library', 'the staff room'], 'C', "We'll use the staff room instead"),
    ('What the museum lacks', "Visitor: The museum has an excellent café and plenty of seating. What it doesn't have is information in other languages, which is a pity for tourists.",
     'What does the museum lack?', ['a café', 'seating', 'multilingual information'], 'C', "information in other languages"),
    ('How long the course lasts', "Adviser: The full-time course lasts one year. You can also study part-time, which takes two years. Some students take three, but that's unusual.",
     'How long does the part-time course usually take?', ['one year', 'two years', 'three years'], 'B', "which takes two years"),
    ('Why the man is calling', "Caller: I'm not calling to complain, and I don't need to change my order. I'd just like to know when it will be delivered.",
     'Why is the man calling?', ['to complain', 'to change an order', 'to ask about delivery'], 'C', "when it will be delivered"),
    ('What surprised the researchers', "Researcher: We expected older drivers to be more careful, and they were. What surprised us was that they also drove faster than we had predicted.",
     'What surprised the researchers?', ['older drivers were careful', 'older drivers drove faster than predicted', 'younger drivers were careful'], 'B', "they also drove faster than we had predicted"),
    ('The best feature of the flat', "Agent: The kitchen is small and the bedroom is quite dark. But the living room has an amazing view over the river, which is its best feature.",
     'What is the best feature of the flat?', ['the kitchen', 'the bedroom', 'the living room view'], 'C', "which is its best feature"),
    ('The topic of the next lecture', "Lecturer: Today we looked at the causes of the war. Next week we'll skip the treaties, which you can read about, and discuss how the war changed everyday life.",
     'What will the next lecture be about?', ['the causes of the war', 'the treaties', 'daily life during the war'], 'C', "discuss how the war changed everyday life"),
    ('What the woman lost', "Woman: My keys were in my pocket, luckily, and my phone was in my hand. It was my purse I left on the bus.",
     'What did the woman lose?', ['her keys', 'her phone', 'her purse'], 'C', "It was my purse I left on the bus"),
    ('When the pool is quietest', "Attendant: Early mornings are busy with swimmers before work, and after school it's full of children. The quietest time is at lunchtime on weekdays.",
     'When is the pool quietest?', ['early morning', 'after school', 'weekday lunchtime'], 'C', "The quietest time is at lunchtime"),
    ('Why he changed jobs', "Man: The salary was fine and I liked my colleagues. I left because the journey took nearly two hours each way.",
     'Why did the man change jobs?', ['the salary', 'his colleagues', 'the long journey'], 'C', "the journey took nearly two hours"),
    ('Advice about the essay', "Tutor: Your ideas are good and your grammar is accurate. My main advice is to use more examples to support your arguments.",
     'What is the tutor’s main advice?', ['develop better ideas', 'improve grammar', 'add more examples'], 'C', "use more examples"),
]
