"""IELTS Speaking practice items, batch 2: fifty new items for each part.

Original Prepyo practice material written to the public IELTS Speaking format
(Part 1 familiar topics, Part 2 long turn with a cue card, Part 3 abstract
discussion). Not official, recalled or copied test content. Topics avoid the
titles already in the live bank.
"""

# Part 1: (title, questions). Three short questions on a familiar topic.
PART1 = [
    ('Friends', ['How often do you see your friends?', 'Do you prefer having a few close friends or many friends?', 'Have you kept in touch with friends from your childhood?']),
    ('Family Time', ['How much time do you spend with your family each week?', 'What do you usually do together?', 'Who in your family are you closest to?']),
    ('Cooking', ['Do you cook for yourself?', 'Who taught you to cook, if anyone?', 'Is there a dish you would like to learn to make?']),
    ('Breakfast', ['What do you usually have for breakfast?', 'Do you think breakfast is the most important meal of the day?', 'Is breakfast in your country different from breakfast in other countries?']),
    ('Fruit and Vegetables', ['What fruit do you eat most often?', 'Did you like vegetables when you were a child?', 'Where do you usually buy fresh fruit and vegetables?']),
    ('Restaurants', ['How often do you eat in restaurants?', 'What kind of restaurant do you like best?', 'Do you prefer quiet restaurants or lively ones?']),
    ('Hats and Caps', ['Do you ever wear a hat or a cap?', 'Why do people wear hats?', 'Were hats more popular in the past than they are now?']),
    ('Bags', ['What kind of bag do you usually carry?', 'What do you keep in it?', 'Have you ever lost a bag?']),
    ('Jewellery', ['Do you wear any jewellery?', 'Is jewellery a popular gift in your country?', 'Why do some people spend a lot of money on jewellery?']),
    ('Smells and Scents', ['Is there a smell that you particularly like?', 'Does any smell remind you of your childhood?', 'Do you ever use perfume or scented products?']),
    ('Haircuts', ['How often do you get your hair cut?', 'Do you go to the same place every time?', 'Have you ever had a hairstyle you did not like?']),
    ('Furniture', ['What is your favourite piece of furniture at home?', 'Do you prefer modern or traditional furniture?', 'Have you ever bought second-hand furniture?']),
    ('Your Bedroom', ['What does your bedroom look like?', 'Do you spend much time in your bedroom apart from sleeping?', 'Would you like to change anything about it?']),
    ('Gardening', ['Do you have a garden or any outdoor space at home?', 'Have you ever grown any plants or vegetables yourself?', 'Is gardening a popular hobby where you live?']),
    ('Trees', ['Are there many trees near your home?', 'Do you have a favourite kind of tree?', 'Why do you think cities plant trees along streets?']),
    ('Parks', ['Is there a park near where you live?', 'What do people usually do there?', 'How often did you go to parks when you were younger?']),
    ('Wild Animals', ['Have you ever seen wild animals in their natural habitat?', 'Which wild animal would you most like to see?', 'Do you think children should learn about wild animals at school?']),
    ('Birds', ['Are there many birds where you live?', 'Do you like listening to birds singing?', 'Would you ever keep a bird as a pet?']),
    ('Rainy Days', ['Do you like rainy days?', 'What do you usually do when it rains?', 'Does it rain a lot in your hometown?']),
    ('Cold Weather', ['How do you keep warm in cold weather?', 'Do you prefer cold weather or hot weather?', 'Have you ever seen snow?']),
    ('Cars and Driving', ['Can you drive?', 'Do you think driving is an important skill to have?', 'Would you like to own a car in the future?']),
    ('Trains', ['How often do you travel by train?', 'What do you like or dislike about train journeys?', 'Are trains popular in your country?']),
    ('Boats', ['Have you ever travelled by boat?', 'Would you like to go on a long boat trip?', 'Are boats used for transport where you live?']),
    ('Airports and Flying', ['Do you enjoy flying?', 'What do you usually do on a long flight?', 'What do you think of the airports you have been to?']),
    ('Holidays', ['Where did you go on your last holiday?', 'Do you prefer relaxing holidays or active ones?', 'Who do you usually go on holiday with?']),
    ('Maps and Directions', ['Are you good at finding your way in a new place?', 'Do you use paper maps or maps on your phone?', 'Have you ever got lost?']),
    ('Hotels', ['Do you often stay in hotels?', 'What makes a hotel comfortable for you?', 'Would you prefer to stay in a hotel or with friends when you travel?']),
    ('Souvenirs', ['Do you buy souvenirs when you travel?', 'What is the best souvenir you have ever bought?', 'What souvenirs would you recommend to visitors to your country?']),
    ('Markets', ['Do you like shopping at markets?', 'What can people buy at markets in your area?', 'Do you think markets will still be popular in the future?']),
    ('Saving Money', ['Are you good at saving money?', 'What do you usually save money for?', 'Did your parents teach you how to manage money?']),
    ('Shopping Centres', ['How often do you go to shopping centres?', 'What do you usually do there besides shopping?', 'Do you prefer shopping centres or small local shops?']),
    ('Waiting in Queues', ['How do you feel when you have to wait in a queue?', 'Where do you most often have to queue?', 'What do you do to pass the time while you wait?']),
    ('Evenings', ['What do you usually do in the evening?', 'Do you prefer to spend evenings at home or going out?', 'Are your evenings different at the weekend?']),
    ('Staying Up Late', ['Do you usually go to bed early or late?', 'When was the last time you stayed up very late?', 'Do you find it easy to get up after a late night?']),
    ('Concentration', ['Is it easy for you to concentrate when you study or work?', 'What things distract you most?', 'What helps you to focus?']),
    ('Memory', ['Do you have a good memory?', 'What kind of things do you find easy to remember?', 'What do you do to help you remember important things?']),
    ('Teamwork', ['Do you prefer to work alone or in a team?', 'Did you do much group work at school?', 'What makes a good team member?']),
    ('Primary School', ['What do you remember about your primary school?', 'Who was your favourite teacher there?', 'How is primary school different now from when you were a child?']),
    ('Exams', ['How do you usually prepare for exams?', 'Do you feel nervous before an exam?', 'Do you think exams are a fair way to test students?']),
    ('Libraries', ['How often do you visit a library?', 'What did you use the library for when you were younger?', 'Do you think libraries are still useful today?']),
    ('Computers', ['What do you use a computer for?', 'When did you first learn to use a computer?', 'Could you live without a computer?']),
    ('The Internet', ['How much time do you spend online each day?', 'What websites do you visit most often?', 'How did you use the internet when you were younger?']),
    ('Diaries and Journals', ['Have you ever kept a diary or journal?', 'Why do some people like to write down what happens each day?', 'Do you use a planner to organise your time?']),
    ('Letters and Postcards', ['When did you last write a letter by hand?', 'Do you ever send postcards when you travel?', 'Do you think people will stop sending letters completely?']),
    ('Magazines', ['Do you read magazines?', 'What kind of magazines are popular in your country?', 'Do you prefer reading articles in print or online?']),
    ('Poetry', ['Did you learn any poems at school?', 'Do you ever read poetry now?', 'Is there a famous poet from your country?']),
    ('Jokes and Laughter', ['Do you like telling jokes?', 'What kind of things make you laugh?', 'Is it important to have a sense of humour?']),
    ('Street Art', ['Is there any street art or public art in your city?', 'Do you think street art makes a city more attractive?', 'Would you like to see more art in public places?']),
    ('Handmade Things', ['Have you ever made something by hand?', 'Do you prefer handmade or factory-made products?', 'Are traditional crafts popular in your country?']),
    ('Recycling', ['Do you recycle at home?', 'What kinds of things do people recycle where you live?', 'Is recycling taught in schools in your country?']),
]

# Part 2: (title, cue, points, explain). Three prompts plus "and explain".
PART2 = [
    ('A Kind Act by a Stranger', 'Describe a time when a stranger did something kind for you.', ['where you were', 'who the stranger was', 'what they did'], 'how you felt about it'),
    ('A Street You Know Well', 'Describe a street that you know well.', ['where it is', 'what you can find there', 'how often you go there'], 'why you know it so well'),
    ('A Piece of Good News', 'Describe a piece of good news you received.', ['what the news was', 'when you received it', 'who told you'], 'why it was good news for you'),
    ('A Useful Online Course or Video', 'Describe an online course or video that taught you something useful.', ['what it was about', 'how you found it', 'what you learned from it'], 'why it was useful to you'),
    ('A Time You Were Very Busy', 'Describe a time when you were very busy.', ['when it was', 'what you had to do', 'how you managed your time'], 'how you felt during that time'),
    ('A Person Who Is Good at Their Job', 'Describe a person you know who is very good at their job.', ['who the person is', 'what their job is', 'what they do in their work'], 'why you think they are good at it'),
    ('A Place Where You Like to Relax', 'Describe a place where you like to relax.', ['where it is', 'how often you go there', 'what you do there'], 'why it helps you relax'),
    ('A Long Walk You Took', 'Describe a long walk you once took.', ['where you walked', 'who you were with', 'what you saw on the way'], 'how you felt at the end of the walk'),
    ('A Time You Borrowed Something', 'Describe a time when you borrowed something from someone.', ['what you borrowed', 'who you borrowed it from', 'why you needed it'], 'how you felt about borrowing it'),
    ('An Important Decision Made by Your Family', 'Describe an important decision that your family made together.', ['what the decision was', 'when it was made', 'how your family reached the decision'], 'how it affected you'),
    ('A Skill You Would Like to Learn', 'Describe a skill you would like to learn in the future.', ['what the skill is', 'how you would learn it', 'how long it might take'], 'why you want to learn it'),
    ('A Time You Saw a Beautiful View', 'Describe a time when you saw a beautiful view.', ['where you were', 'what you could see', 'who you were with'], 'why the view was so memorable'),
    ('A Club or Group You Belong To', 'Describe a club or group that you belong to or used to belong to.', ['what kind of group it is', 'how you joined it', 'what the members do together'], 'why you like being part of it'),
    ('A Small Business You Know', 'Describe a small business that you know.', ['what the business is', 'where it is', 'who runs it'], 'why you think it is successful or unsuccessful'),
    ('A Time You Had to Be Patient', 'Describe a time when you had to be patient.', ['when it was', 'what you were waiting for', 'what you did while you waited'], 'how you managed to stay patient'),
    ('A Film You Would Watch Again', 'Describe a film you would like to watch again.', ['what the film is', 'when you first watched it', 'what it is about'], 'why you would like to watch it again'),
    ('A Tradition in Your Country', 'Describe a traditional custom or practice in your country.', ['what the tradition is', 'when it takes place', 'what people do'], 'why it is important to people'),
    ('A Time You Taught Yourself Something', 'Describe something you taught yourself to do.', ['what you learned', 'why you decided to learn it', 'how you taught yourself'], 'how you felt when you were able to do it'),
    ('An Outdoor Activity You Enjoyed', 'Describe an outdoor activity that you enjoyed doing.', ['what the activity was', 'where you did it', 'who you did it with'], 'why you enjoyed it'),
    ('A Time You Received Good Service', 'Describe a time when you received very good service in a shop or restaurant.', ['where you were', 'what happened', 'who served you'], 'why you think the service was so good'),
    ('A Goal You Hope to Achieve', 'Describe a goal you hope to achieve in the next few years.', ['what the goal is', 'when you set it', 'what you are doing to achieve it'], 'why this goal matters to you'),
    ('A Time You Were Surprised', 'Describe a time when something surprised you.', ['when it happened', 'where you were', 'what the surprise was'], 'how you reacted'),
    ('A Room You Remember From Childhood', 'Describe a room you remember from your childhood.', ['where the room was', 'what it looked like', 'what you did there'], 'why you remember it so well'),
    ('An Interesting Job', 'Describe a job that you think would be interesting to do.', ['what the job is', 'what people in this job do', 'what skills it needs'], 'why you think it would be interesting'),
    ('A Time You Shared Something', 'Describe a time when you shared something with other people.', ['what you shared', 'who you shared it with', 'why you decided to share it'], 'how you felt about sharing it'),
    ('A Public Event You Attended', 'Describe a public event that you attended, such as a concert, match or show.', ['what the event was', 'where and when it took place', 'who you went with'], 'what made it memorable'),
    ('A Time You Solved a Problem', 'Describe a time when you solved a difficult problem.', ['what the problem was', 'when it happened', 'how you solved it'], 'how you felt when the problem was solved'),
    ('A Healthy Habit You Have', 'Describe a healthy habit that you have.', ['what the habit is', 'when you started it', 'how often you do it'], 'how it has helped you'),
    ('A Famous Place in Your Country', 'Describe a famous place in your country that you have visited.', ['where it is', 'why it is famous', 'what you did there'], 'what you thought of it'),
    ('A Time You Apologised', 'Describe a time when you apologised to someone.', ['who you apologised to', 'what had happened', 'how you apologised'], 'how the other person reacted'),
    ('A Child You Know', 'Describe a child you know well.', ['who the child is', 'how you know them', 'what they are like'], 'how you feel about spending time with them'),
    ('Something You Bought Recently', 'Describe something you bought recently that you are pleased with.', ['what it is', 'where you bought it', 'why you chose it'], 'why you are pleased with it'),
    ('A Time You Worked With Others', 'Describe a time when you worked with other people to complete a task.', ['what the task was', 'who you worked with', 'what your role was'], 'whether you enjoyed working in this way'),
    ('A Place With Lots of Water', 'Describe a place you have visited where there was a lot of water, such as a waterfall or coast.', ['where it was', 'when you went there', 'what you did there'], 'how you felt about the place'),
    ('A Time You Tried New Food', 'Describe a time when you tried food you had never eaten before.', ['what the food was', 'where you tried it', 'who you were with'], 'whether you liked it and why'),
    ('A Useful Object in Your Home', 'Describe an object in your home that you find very useful.', ['what the object is', 'how long you have had it', 'how you use it'], 'why it is so useful'),
    ('A Time You Gave Someone Advice', 'Describe a time when you gave someone advice.', ['who you advised', 'what the situation was', 'what advice you gave'], 'whether the advice was helpful'),
    ('A Historical Period You Find Interesting', 'Describe a period in history that you find interesting.', ['what the period is', 'how you learned about it', 'what happened at that time'], 'why it interests you'),
    ('A Time You Stayed in an Unusual Place', 'Describe a time when you stayed somewhere unusual.', ['where you stayed', 'why you stayed there', 'what the place was like'], 'how you felt about staying there'),
    ('A Person Who Speaks Another Language Well', 'Describe a person you know who speaks a foreign language well.', ['who the person is', 'which language they speak', 'how they learned it'], 'what you think of their ability'),
    ('A Time You Missed an Appointment', 'Describe a time when you missed an important appointment.', ['what the appointment was', 'why you missed it', 'what happened as a result'], 'how you felt about it'),
    ('A Sport You Enjoy Watching', 'Describe a sport that you enjoy watching.', ['what the sport is', 'where you watch it', 'who you watch it with'], 'why you enjoy watching it'),
    ('A Time You Moved to a New Place', 'Describe a time when you moved to a new home or a new area.', ['where you moved to', 'why you moved', 'what the new place was like'], 'how you felt about the move'),
    ('A Piece of Clothing Someone Gave You', 'Describe a piece of clothing that someone gave you.', ['what it is', 'who gave it to you', 'when you wear it'], 'how you feel about it'),
    ('An Exciting Book You Read', 'Describe an exciting book that you have read.', ['what the book was', 'when you read it', 'what it was about'], 'why you found it exciting'),
    ('A Time You Were Very Tired', 'Describe a time when you felt very tired.', ['when it was', 'why you were so tired', 'what you did about it'], 'how you felt afterwards'),
    ('A Place You Would Like to Visit Again', 'Describe a place you have visited that you would like to visit again.', ['where it is', 'when you went there', 'what you did there'], 'why you would like to return'),
    ('A Time Technology Did Not Work', 'Describe a time when a piece of technology did not work when you needed it.', ['what the technology was', 'what you were trying to do', 'what you did when it failed'], 'how you felt about the situation'),
    ('A Good Friend From School', 'Describe a friend you made at school.', ['who the friend is', 'how you met', 'what you did together'], 'why you became good friends'),
    ('A Change That Would Improve Your Town', 'Describe a change that would improve the town or city where you live.', ['what the change is', 'how it could be made', 'who would benefit from it'], 'why you think it would be an improvement'),
]

# Part 3: (title, questions). Three abstract questions on a theme.
PART3 = [
    ('Kindness in Modern Society', ['Do you think people today are less kind to strangers than in the past?', 'Why are people sometimes unwilling to help others in public?', 'How can parents teach children to be kind?']),
    ('Streets and Public Spaces', ['What makes a street pleasant to walk along?', 'Should city centres be closed to cars?', 'Who should pay for the upkeep of public spaces?']),
    ('Good and Bad News', ['Why does the news focus so much on negative events?', 'Should news organisations report more good news?', 'How do people usually share important news in your country now?']),
    ('Online Learning', ['What are the advantages of learning online compared with learning in a classroom?', 'Which subjects are difficult to learn online?', 'Will online learning replace traditional schools in the future?']),
    ('Busy Lives', ['Why do people seem to be busier today than in the past?', 'Is being busy a sign of success?', 'How can people balance work and free time better?']),
    ('Success at Work', ['What qualities help people succeed in their jobs?', 'Is it more important to enjoy your job or to earn a high salary?', 'Should companies reward experience or results?']),
    ('Stress and Relaxation', ['Why do so many people feel stressed nowadays?', 'Do people in cities find it harder to relax than people in the countryside?', 'Should employers help their staff to manage stress?']),
    ('Walking and Health', ['Why do fewer people walk to work or school than in the past?', 'How could towns encourage people to walk more?', 'Is walking a good form of exercise for everyone?']),
    ('Sharing and Borrowing', ['Why are sharing schemes, such as bike or tool sharing, becoming popular?', 'Are people more willing to share things with friends or with strangers?', 'Could sharing reduce the amount people buy?']),
    ('Family Decision-Making', ['Who usually makes important decisions in families in your country?', 'Should children be involved in family decisions?', 'How has decision-making in families changed over the last few decades?']),
    ('Learning New Skills as an Adult', ['Why do some adults stop learning new things?', 'Is it harder to learn a new skill as an adult than as a child?', 'Should governments pay for adults to retrain?']),
    ('Natural Beauty and Tourism', ['Why do people travel to see natural scenery?', 'Can tourism damage places of natural beauty?', 'How can popular natural sites be protected?']),
    ('Clubs and Communities', ['Why do people join clubs and societies?', 'Are young people less interested in joining groups than older people?', 'How do communities benefit from local clubs?']),
    ('Small Businesses and Large Companies', ['What difficulties do small businesses face today?', 'Why do some people prefer to buy from small local shops?', 'Should governments support small businesses?']),
    ('Patience and Modern Life', ['Has technology made people less patient?', 'In what situations is patience most important?', 'Can patience be learned?']),
    ('Cinema and Streaming', ['Why do people still go to the cinema when they can stream films at home?', 'Do films influence the way people behave?', 'Should governments fund their country’s film industry?']),
    ('Cultural Traditions', ['Why are some traditions disappearing?', 'Should young people be expected to keep traditions alive?', 'How can traditions be adapted to modern life?']),
    ('Self-Teaching', ['What are the benefits of teaching yourself a skill?', 'What are the limits of learning without a teacher?', 'Has the internet made teachers less important?']),
    ('Outdoor Activities and Children', ['Do children spend less time outdoors than in the past?', 'What are the benefits of outdoor play for children?', 'Should schools organise more outdoor activities?']),
    ('Customer Service', ['What makes good customer service?', 'Has customer service improved or got worse in recent years?', 'Will robots and computers replace people in customer service?']),
    ('Personal Goals', ['Why is it important for people to set goals?', 'Do young people today have different goals from their parents’ generation?', 'What should people do if they fail to reach a goal?']),
    ('Surprises and Routine', ['Do people generally prefer routine or surprises?', 'Why do some people dislike change?', 'Is it good for children to have a strict routine?']),
    ('Homes and Childhood', ['How do the homes children grow up in affect them?', 'Should children have their own bedroom?', 'How have family homes changed in your country?']),
    ('Choosing a Career', ['What influences people’s choice of career?', 'Should young people follow their parents’ advice about careers?', 'Is it better to choose a career early or to try different jobs first?']),
    ('Generosity', ['Why are some people more generous than others?', 'Is it better to give money or time to charity?', 'Should rich people be expected to give more to society?']),
    ('Public Events', ['Why do people enjoy attending live events?', 'Should large public events be free for everyone?', 'What problems can big events cause for local residents?']),
    ('Problem-Solving', ['Is problem-solving a skill that schools should teach directly?', 'Do people solve problems better alone or in groups?', 'How has technology changed the way people solve everyday problems?']),
    ('Healthy Habits', ['Why do people find it difficult to change unhealthy habits?', 'Who is most responsible for people’s health: individuals, families or governments?', 'Should unhealthy food be taxed?']),
    ('Famous Places and Overtourism', ['Why do some tourist sites become extremely crowded?', 'Should the number of visitors to famous places be limited?', 'How do local people feel about large numbers of tourists?']),
    ('Apologies and Forgiveness', ['Why do some people find it difficult to apologise?', 'Is it important for public figures to apologise for their mistakes?', 'Are apologies viewed differently in different cultures?']),
    ('Children and Responsibility', ['At what age should children start to have responsibilities at home?', 'Are children today given too much freedom?', 'How can parents teach children to manage money?']),
    ('Consumer Choices', ['Why do people buy things they do not need?', 'Does advertising make people less satisfied with what they have?', 'Should people try to buy fewer new products?']),
    ('Cooperation at Work', ['Why do some teams work better than others?', 'Is competition between colleagues good or bad for a company?', 'What makes a good team leader?']),
    ('Water and the Environment', ['Why is access to clean water still a problem in many places?', 'How can individuals save water at home?', 'Should water be more expensive to encourage people to use less?']),
    ('Food and Culture', ['Why do people enjoy trying food from other countries?', 'Is traditional food becoming less popular with young people?', 'Should schools teach children how to cook?']),
    ('Objects and Design', ['What makes an everyday object well designed?', 'Why do people replace things that still work?', 'Should manufacturers be required to make products that last longer?']),
    ('Advice and Experience', ['Who do young people turn to for advice nowadays?', 'Is advice from older people always useful?', 'Why do people sometimes ignore good advice?']),
    ('Learning From History', ['Why is it important to study history?', 'Should history lessons focus on local or world history?', 'Can people really learn from mistakes made in the past?']),
    ('Unusual Places to Stay', ['Why are unusual places to stay becoming popular with travellers?', 'Is travelling more about the experience or the destination?', 'How has the internet changed the way people choose accommodation?']),
    ('Languages and Communication', ['Why do some people learn languages more easily than others?', 'Will translation technology make language learning unnecessary?', 'Should everyone learn at least one foreign language?']),
    ('Time Management', ['Why do people find it difficult to manage their time?', 'Is being on time more important in some jobs than others?', 'Can technology help people manage their time better?']),
    ('Watching Sport', ['Why do people enjoy watching sport?', 'Do sports stars earn too much money?', 'Can watching sport encourage people to take up exercise?']),
    ('Moving Home', ['Why do people move to different cities or countries?', 'What difficulties do people face when they move to a new area?', 'How can communities welcome new residents?']),
    ('Gifts and Clothing', ['Is clothing a good choice of gift?', 'Why do people care so much about what they wear?', 'Should schools and workplaces have dress codes?']),
    ('Reading for Pleasure', ['Why do some children love reading while others do not?', 'Is reading on a screen as good as reading a printed book?', 'How can parents encourage children to read more?']),
    ('Rest and Productivity', ['Why do many people not get enough sleep?', 'Should working hours be shorter?', 'Does rest make people more productive?']),
    ('Returning to Places', ['Why do people like to return to places they have visited before?', 'Is it better to visit many places briefly or a few places in depth?', 'How has travel changed in your country in recent years?']),
    ('Dependence on Technology', ['Do people rely too much on technology?', 'What would happen if the internet stopped working for a week?', 'Should children be taught to do things without technology?']),
    ('Friendship Over Time', ['Why do some friendships last and others do not?', 'Is it easier to make friends as a child or as an adult?', 'Has social media changed the meaning of friendship?']),
    ('Improving Towns and Cities', ['What makes a town a good place to live?', 'Should residents have a say in how their town develops?', 'Is it better to improve old areas or build new ones?']),
]
