"""IELTS Writing Task 2 (opinion) practice items, batch 2.

Original Prepyo prompts in the public IELTS Task 2 opinion format ("To what
extent do you agree or disagree?"). Not official, recalled or copied test
content. Topics avoid those already in the live bank.
"""

# (title, statement). The generator adds the standard task instructions.
TASK2 = [
    ('Cooking Lessons in Schools', 'Every school should teach students how to cook healthy meals, even if this means less time for academic subjects.'),
    ('Banning Junk Food Near Schools', 'Shops that sell unhealthy snacks should not be allowed to open near schools.'),
    ('Free Public Transport', 'Public transport in cities should be free for everyone, paid for by taxes.'),
    ('Working From Cafés and Shared Offices', 'Companies should pay for employees to work from shared offices near their homes instead of travelling to a central office.'),
    ('Paying Students to Attend School', 'Paying teenagers from low-income families to stay in school is a good way to reduce the number who leave early.'),
    ('Exams Versus Coursework', 'Students should be assessed through coursework and projects rather than final examinations.'),
    ('Learning Coding at School', 'Computer programming should be a compulsory subject for all secondary school students.'),
    ('Children and Competitive Sport', 'Competitive sports do more harm than good to young children.'),
    ('Libraries as Community Centres', 'Public libraries should become community centres offering activities and services rather than places mainly for borrowing books.'),
    ('Old People and Technology', 'Governments should provide free training to help older people use digital technology.'),
    ('Advertising on Children’s Television', 'All advertising should be banned during television programmes made for children.'),
    ('Luxury Goods', 'Spending large amounts of money on luxury goods is a waste of resources.'),
    ('Local Food', 'People should buy food that is produced locally, even if it is more expensive.'),
    ('Wild Animals in Circuses', 'Using wild animals in circuses and street entertainment should be banned everywhere.'),
    ('Planting Trees in Cities', 'Planting more trees is the most effective way to make cities healthier places to live.'),
    ('Owning a Car in the City', 'People who live in cities with good public transport do not need to own a car.'),
    ('Tourist Taxes', 'Tourists should pay an extra tax to help protect the places they visit.'),
    ('Historical Films', 'Films based on historical events should always be completely accurate.'),
    ('University Entrance Interviews', 'Universities should select students on the basis of interviews rather than exam results alone.'),
    ('Teaching Manners', 'Teaching good manners is the responsibility of parents, not schools.'),
    ('Handwriting in Schools', 'Schools no longer need to teach children to write by hand.'),
    ('Shorter School Holidays', 'Long school summer holidays should be replaced by several shorter breaks throughout the year.'),
    ('Personal Data and Companies', 'Companies should not be allowed to collect personal data about their customers without clear permission.'),
    ('Space Tourism', 'Travelling into space for pleasure should not be allowed because of its environmental cost.'),
    ('Internet Access in Rural Areas', 'Providing fast internet to rural areas should be a higher priority for governments than building new roads.'),
    ('Advertising Large Cars', 'Advertisements for large, high-polluting cars should be banned.'),
    ('Public Art Funding', 'Local councils should spend money on public art such as sculptures and murals.'),
    ('Online Reviews', 'Reviews written by ordinary customers online are more useful than advice from experts.'),
    ('Learning Through Games', 'Educational computer games are a more effective way for children to learn than traditional lessons.'),
    ('Group Work at University', 'University students learn more from working in groups than from studying alone.'),
    ('Charity Begins at Home', 'Wealthy countries should solve their own social problems before giving aid to other countries.'),
    ('Housework Equality', 'Household tasks should be shared equally between all adults living in a home.'),
    ('News on Social Media', 'Getting news from social media does more harm than good.'),
    ('Renewable Energy Costs', 'Governments should make renewable energy cheaper for households, even if this increases taxes.'),
    ('Night-Time Economy', 'Shops, restaurants and entertainment venues in cities should be allowed to open twenty-four hours a day.'),
    ('Science in Many Languages', 'Scientific research should be published in several languages, not only in English.'),
    ('Learning Instruments', 'Every child should have the opportunity to learn a musical instrument at school.'),
    ('Travel Broadens the Mind', 'Travelling to other countries is the best way to understand different cultures.'),
    ('Reducing Working Hours for Parents', 'Employers should allow parents of young children to work shorter hours without losing their jobs.'),
    ('Fines Based on Income', 'Fines for breaking the law, such as speeding, should be based on how much the offender earns.'),
    ('Nature Reserves Versus Farmland', 'Land should be used for nature reserves rather than for farming wherever possible.'),
    ('Celebrity Endorsements', 'Famous people should not be paid to advertise products they do not use themselves.'),
    ('Short Videos and Concentration', 'Short videos on social media are damaging young people’s ability to concentrate.'),
    ('Second-Hand Goods', 'Buying second-hand clothes and furniture should be encouraged as a way to protect the environment.'),
    ('Mother Tongue Education', 'Children should be educated in their first language during their early school years.'),
    ('A Shared Day of Rest', 'Shops and offices should close on the same day every week so that everyone can rest at the same time.'),
    ('Rewarding Good Behaviour in Schools', 'Schools should reward good behaviour rather than punish bad behaviour.'),
    ('Talent Versus Hard Work', 'Hard work is more important than natural talent for success in any field.'),
    ('Experiences Versus Possessions', 'Spending money on experiences, such as travel and concerts, brings more happiness than buying possessions.'),
    ('Street Food', 'Street food stalls should be encouraged in cities because they add to local culture.'),
]
