"""IELTS Writing Task 1 (Academic) practice figures, batch 2.

Original Prepyo figures in the public IELTS Academic Task 1 formats: bar
charts, line graphs, pie charts, tables, process diagrams and maps. All data
is invented for practice and describes invented places; it is not official,
recalled or copied test content, and not real statistics. `features` is the
examiner-style summary of the main features, given to the marker so it can
judge whether a response selects and reports them accurately.
"""

# kind='bar': categories on the x axis, one bar per series in each group.
# kind='line': x values (years) and one line per series.
# kind='pie': one or more pies of percentages that each total 100.
# kind='table': header row and data rows.
# kind='process': ordered stages.
# kind='map': two panels (before/after) of labelled areas on a 10x8 grid.
FIGURES = [
    # ---------------------------------------------------------------- bar charts
    dict(kind='bar', title='Weekly hours of exercise by age group',
         desc='the average number of hours of exercise per week taken by men and women in five age groups in Westbury',
         unit='hours per week', categories=['16-24', '25-34', '35-44', '45-64', '65+'],
         series={'Men': [5.5, 4.0, 3.2, 2.8, 2.5], 'Women': [4.5, 3.5, 3.0, 3.1, 2.9]},
         features='Men aged 16-24 exercised most (5.5 hours) and exercise fell with age for men, to 2.5 hours for over-65s. Women’s exercise also fell, to 3.0 hours at 35-44, but then levelled off (3.1 and 2.9 hours), so from age 45 women exercised more than men (3.1 v 2.8; 2.9 v 2.5). The gender gap was widest among the youngest group.'),
    dict(kind='bar', title='Books borrowed from three libraries',
         desc='the number of books borrowed from three branch libraries in Hollins in 2014 and 2024',
         unit='thousands of books', categories=['Central', 'Riverside', 'Hill Road'],
         series={'2014': [95, 60, 40], '2024': [70, 64, 55]},
         features='Borrowing at Central fell sharply from 95,000 to 70,000 but it remained the busiest branch. Riverside rose slightly (60,000 to 64,000) and Hill Road grew most, from 40,000 to 55,000. Total borrowing fell from 195,000 to 189,000 and the gap between branches narrowed.'),
    dict(kind='bar', title='Household spending on mobile services',
         desc='average monthly household spending on mobile phone calls, mobile data and streaming services in Carlow between 2012 and 2024',
         unit='dollars per month', categories=['2012', '2016', '2020', '2024'],
         series={'Calls': [30, 22, 15, 10], 'Data': [10, 20, 28, 34], 'Streaming': [2, 8, 16, 20]},
         features='Spending on calls fell steadily from $30 to $10, while data rose from $10 to $34, overtaking calls between 2016 and 2020. Streaming grew tenfold from $2 to $20. Total spending rose from $42 to $64.'),
    dict(kind='bar', title='Reasons for using a local park',
         desc='the main reasons given by visitors for using Greenacre Park on weekdays and at weekends',
         unit='% of visitors', categories=['Exercise', 'Dog walking', 'Picnics', 'Children’s play', 'Events'],
         series={'Weekdays': [38, 30, 7, 20, 5], 'Weekends': [22, 18, 20, 28, 12]},
         features='On weekdays exercise (38%) and dog walking (30%) were the main reasons. At weekends the pattern was more even: children’s play led (28%), picnics rose from 7% to 20% and events from 5% to 12%, while exercise and dog walking fell.'),
    dict(kind='bar', title='Graduates entering four careers',
         desc='the percentage of graduates from Marston University who entered four career areas in 2005 and 2025',
         unit='% of graduates', categories=['Teaching', 'Engineering', 'Healthcare', 'Technology'],
         series={'2005': [28, 22, 18, 12], '2025': [16, 20, 24, 30]},
         features='Teaching was the most common destination in 2005 (28%) but fell to 16%. Technology rose most, from 12% to 30%, to become the most popular. Healthcare increased from 18% to 24%, while engineering changed little (22% to 20%).'),
    dict(kind='bar', title='Electricity use by appliance in two homes',
         desc='the annual electricity used by six appliances in an older house and a new energy-efficient house in Dunmore',
         unit='kilowatt hours per year', categories=['Heating', 'Water heater', 'Fridge', 'Lighting', 'Washing machine', 'Television'],
         series={'Older house': [4200, 2100, 600, 500, 350, 250], 'New house': [1500, 1200, 300, 120, 200, 180]},
         features='The new house used much less electricity for every appliance, 3,500 kWh in total compared with 8,000 kWh. Heating was the largest use in both but fell most, from 4,200 to 1,500 kWh. Lighting showed the biggest proportional drop, from 500 to 120 kWh.'),
    dict(kind='bar', title='Visitors to four museums by season',
         desc='the number of visitors to four museums in Ashby in summer and winter last year',
         unit='thousands of visitors', categories=['Art', 'Science', 'History', 'Toy'],
         series={'Summer': [48, 62, 35, 20], 'Winter': [30, 58, 18, 26]},
         features='Summer was busier for three museums, with the science museum the most visited in both seasons (62,000 and 58,000) and most stable. History visitors halved in winter (35,000 to 18,000). The toy museum was the exception, attracting more visitors in winter (26,000) than summer (20,000).'),
    dict(kind='bar', title='How students travel to school',
         desc='how students at Fernhill Secondary School travelled to school in 2010 and 2025',
         unit='% of students', categories=['Walk', 'Bicycle', 'Bus', 'Car', 'Train'],
         series={'2010': [35, 5, 30, 25, 5], '2025': [28, 15, 25, 20, 12]},
         features='Walking remained the most common way to travel, although it fell from 35% to 28%. Cycling tripled from 5% to 15% and train use more than doubled (5% to 12%). The shares travelling by bus and car both fell by 5 percentage points.'),
    dict(kind='bar', title='Waste collected in a coastal town',
         desc='the amount of four types of waste collected from beaches in Porthallow each month from May to August',
         unit='kilograms', categories=['May', 'June', 'July', 'August'],
         series={'Plastic': [120, 180, 260, 240], 'Glass': [40, 55, 70, 65], 'Paper': [60, 75, 90, 110], 'Metal': [25, 30, 35, 30]},
         features='Plastic was by far the largest type of waste every month and more than doubled from 120 kg in May to a peak of 260 kg in July. Glass and metal also peaked in July before falling slightly, whereas paper rose every month to 110 kg in August. Metal was the smallest category throughout.'),
    dict(kind='bar', title='Time spent reading by format',
         desc='the average time adults in Kellerton spent reading printed books, e-books and audiobooks each week in three age groups',
         unit='minutes per week', categories=['18-34', '35-54', '55+'],
         series={'Printed books': [40, 65, 120], 'E-books': [55, 45, 20], 'Audiobooks': [70, 50, 25]},
         features='Older adults spent by far the most time on printed books (120 minutes), although total reading time was similar in every age group (160-165 minutes). Younger adults preferred audiobooks (70 minutes) and e-books (55 minutes), and use of both digital formats fell with age.'),
    dict(kind='bar', title='Overseas students at a college by region',
         desc='the number of overseas students at Linfield College from five world regions in 2015 and 2025',
         unit='number of students', categories=['East Asia', 'South Asia', 'Europe', 'Africa', 'Americas'],
         series={'2015': [420, 180, 260, 90, 150], '2025': [380, 450, 210, 230, 160]},
         features='The total rose from 1,100 to 1,430. South Asia showed the largest increase (180 to 450) and replaced East Asia (which fell from 420 to 380) as the largest source. Students from Africa more than doubled, European numbers fell and the Americas were almost unchanged.'),
    dict(kind='bar', title='Food wasted by households',
         desc='the average amount of five types of food thrown away each week by households of different sizes in Brookdale',
         unit='grams per week', categories=['Fruit & veg', 'Bread', 'Dairy', 'Meat & fish', 'Prepared meals'],
         series={'One person': [450, 300, 150, 100, 250], 'Family of four': [1200, 650, 400, 300, 350]},
         features='Families of four wasted more of every type, 2,900 g a week against 1,250 g for single people, but less per person. Fruit and vegetables were the most wasted food for both. Prepared meals made up a much larger share of waste for single-person households (20%) than for families (about 12%).'),
    # --------------------------------------------------------------- line graphs
    dict(kind='line', title='Cinema tickets and streaming subscriptions',
         desc='cinema tickets sold and streaming subscriptions in Ravenna between 2004 and 2024',
         unit='millions', x=[2004, 2008, 2012, 2016, 2020, 2024],
         series={'Cinema tickets': [40, 42, 38, 35, 12, 28], 'Streaming subscriptions': [0, 2, 8, 20, 36, 44]},
         features='Cinema tickets were stable at around 40 million until 2012, fell slowly to 35 million, collapsed to 12 million in 2020 and partly recovered to 28 million. Streaming subscriptions rose from nothing to 44 million, overtaking cinema tickets by 2020.'),
    dict(kind='line', title='Average commuting time in three cities',
         desc='the average one-way commuting time in three cities between 1995 and 2025',
         unit='minutes', x=[1995, 2000, 2005, 2010, 2015, 2020, 2025],
         series={'Harbourton': [25, 28, 32, 38, 42, 40, 44], 'Millbrook': [30, 30, 29, 28, 27, 25, 24], 'Stanwick': [20, 22, 25, 26, 30, 33, 35]},
         features='Commuting times rose in Harbourton (25 to 44 minutes) and Stanwick (20 to 35), with Harbourton’s the longest from 2005 onwards. Millbrook was the only city where commutes shortened, falling gradually from 30 to 24 minutes.'),
    dict(kind='line', title='Monthly rainfall and reservoir levels',
         desc='monthly rainfall and the water level of a reservoir in Tallis Valley over one year',
         unit='rainfall in mm / reservoir level as % full', x=['Jan', 'Mar', 'May', 'Jul', 'Sep', 'Nov'],
         series={'Rainfall (mm)': [120, 90, 50, 20, 60, 130], 'Reservoir (% full)': [95, 92, 80, 55, 50, 78]},
         features='Rainfall was highest in winter (120-130 mm) and lowest in July (20 mm). The reservoir followed rainfall with a delay: it stayed above 90% full until March, fell to a low of 50% in September, two months after the driest month, and recovered to 78% by November.'),
    dict(kind='line', title='Use of payment methods in shops',
         desc='the percentage of shop payments made by cash, card and mobile phone in Deverill between 2010 and 2025',
         unit='% of payments', x=[2010, 2013, 2016, 2019, 2022, 2025],
         series={'Cash': [60, 52, 42, 30, 18, 12], 'Card': [38, 44, 50, 55, 52, 45], 'Mobile phone': [2, 4, 8, 15, 30, 43]},
         features='Cash fell steadily from 60% of payments to 12%. Card payments rose to a peak of 55% in 2019 before declining to 45%. Mobile payments grew from 2% to 43% and were almost level with cards by 2025.'),
    dict(kind='line', title='Visitors to a mountain resort',
         desc='the number of visitors to Crestholm mountain resort each month in 2004 and 2024',
         unit='thousands of visitors', x=['Jan', 'Mar', 'May', 'Jul', 'Sep', 'Nov'],
         series={'2004': [30, 22, 8, 12, 6, 18], '2024': [22, 15, 14, 30, 18, 12]},
         features='In 2004 the resort was busiest in winter, peaking at 30,000 in January, with few summer visitors. By 2024 the pattern had reversed: July was the peak month (30,000) and winter numbers had fallen. Visitor numbers were more evenly spread through the year in 2024.'),
    dict(kind='line', title='Share of adults living alone',
         desc='the percentage of adults living alone in four age groups in Northmere from 1980 to 2020',
         unit='% of adults', x=[1980, 1990, 2000, 2010, 2020],
         series={'25-44': [6, 9, 12, 14, 15], '45-64': [8, 10, 13, 16, 19], '65-74': [18, 19, 20, 21, 22], '75+': [38, 40, 41, 40, 38]},
         features='Adults aged 75 and over were by far the most likely to live alone, at around 40% throughout. All three younger groups rose, most sharply among 45-64s (8% to 19%) and 25-44s (6% to 15%), while 65-74s increased only slightly.'),
    dict(kind='line', title='Production of three crops',
         desc='the production of wheat, maize and soya beans in the Kessel region between 1990 and 2025',
         unit='million tonnes', x=[1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025],
         series={'Wheat': [12, 13, 13, 14, 14, 13, 12, 12], 'Maize': [6, 8, 10, 11, 13, 15, 16, 18], 'Soya beans': [1, 1, 2, 4, 6, 9, 11, 12]},
         features='Wheat production was stable at 12-14 million tonnes throughout. Maize tripled from 6 to 18 million tonnes and overtook wheat around 2015. Soya beans grew fastest, from 1 to 12 million tonnes, reaching the level of wheat by 2025.'),
    dict(kind='line', title='Temperature in two cities',
         desc='the average monthly temperature in two cities, one coastal and one inland',
         unit='degrees Celsius', x=['Jan', 'Mar', 'May', 'Jul', 'Sep', 'Nov'],
         series={'Portwick (coastal)': [8, 10, 14, 19, 17, 11], 'Varne (inland)': [-2, 5, 16, 27, 18, 4]},
         features='Both cities were warmest in July and coldest in January. The inland city had a much wider range, from -2°C to 27°C, while the coastal city varied only between 8°C and 19°C. Varne was colder than Portwick in winter but hotter from May to September.'),
    dict(kind='line', title='Online and in-store clothing sales',
         desc='clothing sales made online and in stores in Elbury between 2015 and 2025',
         unit='millions of dollars', x=[2015, 2017, 2019, 2021, 2023, 2025],
         series={'In-store': [800, 790, 760, 520, 640, 620], 'Online': [150, 220, 300, 560, 540, 600]},
         features='In-store sales were stable at about $800 million before dropping sharply to $520 million in 2021 and only partly recovering. Online sales quadrupled from $150 million to $600 million and briefly overtook in-store sales in 2021. By 2025 the two channels were almost equal.'),
    dict(kind='line', title='Energy produced by a solar farm',
         desc='the average energy produced by a solar farm at different times of day in summer and winter',
         unit='megawatts', x=['6am', '9am', '12pm', '3pm', '6pm', '9pm'],
         series={'Summer': [5, 30, 48, 40, 15, 0], 'Winter': [0, 8, 20, 12, 0, 0]},
         features='Output peaked at midday in both seasons, but the summer peak (48 MW) was more than double the winter peak (20 MW). In summer the farm produced energy from 6am to 6pm, whereas in winter it produced only between about 9am and 3pm.'),
    dict(kind='line', title='Members of three sports clubs',
         desc='the membership of three sports clubs in Ellingham from 2016 to 2024',
         unit='number of members', x=[2016, 2018, 2020, 2022, 2024],
         series={'Tennis club': [300, 320, 280, 450, 520], 'Swimming club': [500, 480, 250, 400, 470], 'Running club': [120, 180, 300, 340, 360]},
         features='The swimming club was largest in 2016 (500) but fell by half in 2020 and did not fully recover. The tennis club dipped in 2020 and then grew strongly to 520, becoming the largest. The running club tripled from 120 to 360, growing even in 2020.'),
    dict(kind='line', title='Fish caught and fish farmed',
         desc='the amount of fish caught at sea and produced by fish farms in Aldmoor from 1985 to 2025',
         unit='thousand tonnes', x=[1985, 1995, 2005, 2015, 2025],
         series={'Caught at sea': [90, 85, 70, 60, 55], 'Farmed': [5, 15, 40, 65, 85]},
         features='The sea catch declined steadily from 90,000 to 55,000 tonnes, while farmed fish grew from 5,000 to 85,000 tonnes. Farming overtook the sea catch between 2005 and 2015, and total fish production rose from 95,000 to 140,000 tonnes.'),
    # ---------------------------------------------------------------- pie charts
    dict(kind='pie', title='How a charity spent its income',
         desc='how the charity Clearwater Trust spent its income in 2015 and 2025',
         pies={'2015': {'Clean water projects': 45, 'Education': 20, 'Fundraising': 15, 'Administration': 12, 'Emergency aid': 8},
               '2025': {'Clean water projects': 52, 'Education': 18, 'Fundraising': 10, 'Administration': 6, 'Emergency aid': 14}},
         features='Clean water projects took the largest share in both years, rising from 45% to 52%. Emergency aid almost doubled (8% to 14%). Spending on administration halved to 6% and fundraising fell from 15% to 10%, so a larger proportion went on the charity’s work.'),
    dict(kind='pie', title='Sources of a city’s drinking water',
         desc='where the drinking water for Kelvale came from in 1990 and 2025',
         pies={'1990': {'River': 55, 'Groundwater': 35, 'Reservoir': 10},
               '2025': {'River': 30, 'Groundwater': 25, 'Reservoir': 30, 'Recycled water': 10, 'Desalination': 5}},
         features='In 1990 Kelvale relied on three sources, mainly the river (55%). By 2025 the supply was more varied: the river’s share fell to 30%, equal to the reservoir, which tripled from 10%. Recycled water (10%) and desalination (5%) were new sources.'),
    dict(kind='pie', title='How teenagers spend their free time',
         desc='how teenagers in Harwood spent their free time on a typical weekday in 2005 and 2025',
         pies={'2005': {'Watching TV': 35, 'Sport': 20, 'Meeting friends': 25, 'Gaming': 10, 'Other': 10},
               '2025': {'Watching TV': 10, 'Sport': 15, 'Meeting friends': 15, 'Gaming': 25, 'Social media': 30, 'Other': 5}},
         features='Television was the main activity in 2005 (35%) but fell to 10% by 2025. Screen activities of other kinds grew: social media, not listed in 2005, took the largest share (30%) and gaming rose from 10% to 25%. Time spent meeting friends and on sport both declined.'),
    dict(kind='pie', title='Energy sources for home heating',
         desc='the energy sources used to heat homes in the region of Eastmarch in 2000 and 2025',
         pies={'2000': {'Oil': 40, 'Gas': 35, 'Coal': 15, 'Electricity': 8, 'Wood': 2},
               '2025': {'Oil': 12, 'Gas': 38, 'Coal': 2, 'Heat pumps': 30, 'Electricity': 10, 'Wood': 8}},
         features='Oil was the leading heating fuel in 2000 (40%) but fell to 12%, and coal almost disappeared (15% to 2%). Gas remained important and became the largest source (38%). Heat pumps, not used in 2000, provided 30% of heating in 2025, and wood rose from 2% to 8%.'),
    dict(kind='pie', title='Causes of delays on a railway',
         desc='the causes of train delays on the Westline railway in winter and in summer',
         pies={'Winter': {'Weather': 35, 'Signal faults': 25, 'Train faults': 20, 'Staff shortages': 10, 'Other': 10},
               'Summer': {'Weather': 10, 'Signal faults': 30, 'Train faults': 25, 'Staff shortages': 20, 'Other': 15}},
         features='Weather was the main cause of delays in winter (35%) but only 10% in summer. In summer, signal faults (30%) and train faults (25%) were the leading causes, and staff shortages doubled from 10% to 20%.'),
    dict(kind='pie', title='Occupations of a town’s workers',
         desc='the occupations of working adults in Brindle in 1975 and 2025',
         pies={'1975': {'Manufacturing': 42, 'Farming': 18, 'Retail': 15, 'Services': 15, 'Public sector': 10},
               '2025': {'Manufacturing': 12, 'Farming': 4, 'Retail': 18, 'Services': 44, 'Public sector': 22}},
         features='Brindle’s economy shifted from manufacturing, which fell from 42% of workers to 12%, to services, which nearly tripled to 44%. Farming declined from 18% to 4% while the public sector more than doubled to 22%. Retail rose slightly.'),
    dict(kind='pie', title='Where a university’s electricity is used',
         desc='how electricity was used at Halden University in 2010 and 2025',
         pies={'2010': {'Lighting': 30, 'Heating and cooling': 35, 'Computers': 15, 'Laboratories': 12, 'Other': 8},
               '2025': {'Lighting': 10, 'Heating and cooling': 30, 'Computers': 28, 'Laboratories': 22, 'Other': 10}},
         features='Heating and cooling remained the largest use (35% then 30%). Lighting fell sharply from 30% to 10%, while computers nearly doubled to 28% and laboratories rose from 12% to 22%.'),
    # -------------------------------------------------------------------- tables
    dict(kind='table', title='Facilities in four hotels',
         desc='the prices and facilities of four hotels in Saltmere',
         header=['Hotel', 'Price per night ($)', 'Rooms', 'Distance to beach (km)', 'Guest rating (out of 10)'],
         rows=[['Seaview', '180', '120', '0.2', '8.9'], ['Harbour Inn', '95', '40', '1.5', '8.2'], ['Grand Palace', '240', '300', '3.0', '7.4'], ['Budget Stay', '60', '85', '4.5', '6.1']],
         features='Seaview was closest to the beach and had the highest rating (8.9) despite a mid-to-high price. The Grand Palace was the most expensive and largest hotel but rated only 7.4. Budget Stay was cheapest, furthest from the beach and lowest rated, while Harbour Inn offered good value with a rating of 8.2 at $95.'),
    dict(kind='table', title='Smartphone use by age',
         desc='smartphone ownership and daily use among adults of different ages in Corvale',
         header=['Age group', 'Own a smartphone (%)', 'Daily hours of use', 'Main use'],
         rows=[['18-29', '98', '5.2', 'Social media'], ['30-44', '95', '3.8', 'Messaging'], ['45-59', '84', '2.6', 'News'], ['60-74', '62', '1.5', 'Calls'], ['75+', '35', '0.8', 'Calls']],
         features='Ownership and use both fell with age: 98% of 18-29s owned a smartphone and used it 5.2 hours a day, compared with 35% and 0.8 hours for those over 75. Younger adults mainly used phones for social media and messaging, while the two oldest groups used them mainly for calls.'),
    dict(kind='table', title='Commuting costs and times by transport',
         desc='the average cost and time of a 15-kilometre commute by five forms of transport in Dalebridge',
         header=['Transport', 'Cost per day ($)', 'Time (minutes)', 'CO2 per trip (kg)'],
         rows=[['Car', '14.00', '35', '3.2'], ['Bus', '4.50', '50', '1.1'], ['Train', '7.00', '25', '0.6'], ['Bicycle', '0.50', '45', '0.0'], ['E-scooter', '5.00', '40', '0.1']],
         features='The train was fastest (25 minutes) with low emissions, while the car was the most expensive ($14) and most polluting (3.2 kg). The bus was cheap but slowest (50 minutes). Cycling cost almost nothing and produced no CO2, but took 45 minutes.'),
    dict(kind='table', title='Performance of three schools',
         desc='information about three secondary schools in Kirkby in 2024',
         header=['School', 'Students', 'Students per teacher', 'Pass rate (%)', 'Went to university (%)'],
         rows=[['Kirkby High', '1,450', '19', '82', '58'], ['St Anne’s', '620', '14', '91', '71'], ['Moorside Academy', '980', '22', '74', '43']],
         features='St Anne’s was the smallest school with the fewest students per teacher (14), and it had the best results: a 91% pass rate and 71% going to university. Moorside had the largest classes and the weakest results. Kirkby High was the biggest school and fell between the other two on every measure.'),
    dict(kind='table', title='Tourism in four coastal towns',
         desc='tourism figures for four coastal towns in 2024',
         header=['Town', 'Visitors (thousands)', 'Average stay (nights)', 'Average spend per visitor ($)', 'Hotels'],
         rows=[['Beckport', '850', '2.1', '310', '45'], ['Colbay', '420', '5.8', '920', '30'], ['Dunwater', '1,200', '1.4', '180', '38'], ['Ferness', '300', '4.5', '760', '12']],
         features='Dunwater attracted the most visitors (1.2 million) but they stayed the shortest time and spent least ($180). Colbay and Ferness had far fewer visitors who stayed longer and spent much more, with Colbay’s visitors spending most ($920). Beckport had the most hotels.'),
    dict(kind='table', title='Nutrition in five breakfast foods',
         desc='the nutritional content of 100 grams of five breakfast foods',
         header=['Food', 'Calories', 'Sugar (g)', 'Protein (g)', 'Fibre (g)'],
         rows=[['Porridge oats', '370', '1', '11', '9'], ['Frosted cereal', '380', '35', '6', '2'], ['White bread', '265', '4', '9', '3'], ['Yoghurt', '95', '12', '5', '0'], ['Eggs', '145', '0', '13', '0']],
         features='Frosted cereal and oats had the most calories, but the cereal contained 35 g of sugar compared with only 1 g in oats, which also had the most fibre (9 g). Eggs provided the most protein (13 g) with no sugar. Yoghurt was the lowest in calories but relatively high in sugar.'),
    dict(kind='table', title='Internet speeds and prices',
         desc='the average internet download speed and monthly price in five towns in 2024',
         header=['Town', 'Download speed (Mbps)', 'Monthly price ($)', 'Homes connected (%)'],
         rows=[['Arden', '450', '45', '96'], ['Brisk', '120', '38', '88'], ['Calder', '60', '52', '71'], ['Dorling', '300', '30', '93'], ['Elm Cross', '25', '40', '64']],
         features='Arden had the fastest speeds (450 Mbps) and the highest connection rate (96%). Dorling offered the best value, with fast speeds at the lowest price ($30). Calder and Elm Cross had slow speeds and the fewest connected homes, and Calder was the most expensive town despite its slow service.'),
    # ----------------------------------------------------------------- processes
    dict(kind='process', title='How paper is recycled',
         desc='how used paper is recycled into new paper products',
         steps=['Used paper collected from homes and offices', 'Sorted by type and grade', 'Mixed with water to make pulp', 'Pulp screened to remove plastic and staples', 'Ink removed with air bubbles', 'Pulp spread on rollers and dried', 'Rolled into large reels', 'Cut and sent to factories'],
         features='The process has eight stages, from collection to delivery to factories. Paper is collected and sorted, turned into pulp with water, cleaned of contaminants and ink, then pressed and dried on rollers before being rolled and cut into new products.'),
    dict(kind='process', title='How honey is produced',
         desc='the stages in the production of honey',
         steps=['Bees collect nectar from flowers', 'Nectar stored in the hive’s wax cells', 'Bees fan their wings to evaporate water', 'Cells sealed with wax', 'Beekeeper removes the frames', 'Wax caps cut off', 'Honey extracted by spinning', 'Honey filtered and put into jars'],
         features='The process begins naturally in the hive, where bees collect nectar, store it, reduce its water content and seal it. The beekeeper then takes the frames, uncaps the cells, spins out the honey, and filters and bottles it. Four stages are natural and four are carried out by people.'),
    dict(kind='process', title='How a tunnel is built under a river',
         desc='the main stages in building a road tunnel under a river',
         steps=['Survey of the riverbed and rock', 'Access shafts dug on both banks', 'Tunnel boring machine lowered into shaft', 'Machine cuts through rock', 'Concrete rings fitted to line the tunnel', 'Waste rock removed by conveyor', 'Road surface and lighting installed', 'Safety tests before opening'],
         features='Construction begins with a survey and the digging of shafts on each bank. A boring machine then cuts the tunnel, with concrete rings fitted and waste rock removed as it advances. Finally the road, lighting and safety checks are completed before the tunnel opens.'),
    dict(kind='process', title='The water cycle',
         desc='the water cycle, the continuous movement of water on Earth',
         steps=['Sun heats water in oceans and lakes', 'Water evaporates as vapour', 'Plants release water vapour', 'Vapour rises and cools', 'Condensation forms clouds', 'Precipitation falls as rain or snow', 'Water runs off into rivers', 'Water soaks into the ground and returns to the sea'],
         features='The water cycle is a continuous natural process. Heat from the sun causes evaporation from water and plants; the vapour cools and condenses into clouds, and falls as rain or snow. The water then returns to the sea over land and underground, and the cycle begins again.'),
    dict(kind='process', title='How bricks are made',
         desc='the process of manufacturing bricks',
         steps=['Clay dug from the ground', 'Clay crushed and mixed with sand and water', 'Mixture pressed into moulds or cut by wire', 'Bricks dried for 24 to 48 hours', 'Fired in a kiln at 900-1,300°C', 'Cooled for 48 to 72 hours', 'Packed and delivered'],
         features='Bricks are made in seven stages, beginning with digging clay and ending with delivery. The clay is mixed and shaped, then dried and fired in a kiln at up to 1,300°C before a long cooling period. Drying and cooling together take between three and five days.'),
    dict(kind='process', title='The life cycle of a frog',
         desc='the life cycle of a frog',
         steps=['Adult frog lays eggs in water', 'Eggs hatch after about 10 days', 'Tadpole with gills lives in water', 'Back legs grow (5-6 weeks)', 'Front legs appear and tail shortens (9 weeks)', 'Young frog leaves the water', 'Adult frog (12-16 weeks)'],
         features='The frog’s life cycle has distinct stages over roughly three to four months, starting and ending with adult frogs in a continuous cycle. It begins in the water as eggs and gill-breathing tadpoles, which gradually grow legs and lose their tails before leaving the water as young frogs.'),
    dict(kind='process', title='How tea is produced',
         desc='the production of black tea from leaf to packet',
         steps=['Leaves picked by hand', 'Leaves spread out to wilt for 12-18 hours', 'Leaves rolled to break them', 'Leaves left to oxidise and turn brown', 'Leaves dried with hot air', 'Tea sorted by size', 'Tea tasted and graded', 'Tea packed and exported'],
         features='Tea production has eight stages from picking to export. After picking, the leaves are wilted, rolled and oxidised, which changes their colour, and then dried with hot air. Finally the tea is sorted, graded by tasting and packed.'),
    # ----------------------------------------------------------------------- maps
    dict(kind='map', title='A seaside village in 1990 and today',
         desc='the village of Wenby in 1990 and today',
         panels={'1990': [('Sea', 0, 0, 10, 2, 'water'), ('Beach', 0, 2, 10, 1, 'sand'), ('Fishing harbour', 7, 2, 3, 1, 'building'), ('Main street', 0, 4, 10, 1, 'road'), ('Houses', 1, 5, 3, 2, 'building'), ('Farmland', 5, 5, 5, 3, 'green'), ('Shops', 1, 3, 3, 1, 'building')],
                 'Today': [('Sea', 0, 0, 10, 2, 'water'), ('Beach', 0, 2, 7, 1, 'sand'), ('Marina', 7, 2, 3, 1, 'building'), ('Main street', 0, 4, 10, 1, 'road'), ('Houses', 1, 5, 3, 2, 'building'), ('Hotel', 5, 5, 2, 2, 'building'), ('Car park', 7, 5, 3, 1, 'road'), ('Holiday apartments', 7, 6, 3, 2, 'building'), ('Shops and cafés', 1, 3, 5, 1, 'building')]},
         features='Wenby has changed from a fishing village into a tourist resort. The fishing harbour has become a marina, and the farmland east of the houses has been replaced by a hotel, a car park and holiday apartments. The row of shops has been extended to include cafés, while the beach, main street and houses remain.'),
    dict(kind='map', title='A school site before and after expansion',
         desc='the site of Ferris Primary School in 2010 and in 2025',
         panels={'2010': [('Main building', 1, 1, 4, 2, 'building'), ('Playground', 1, 4, 4, 2, 'road'), ('Playing field', 6, 1, 3, 5, 'green'), ('Car park', 1, 7, 3, 1, 'road'), ('Entrance', 4, 7, 1, 1, 'road')],
                 '2025': [('Main building', 1, 1, 4, 2, 'building'), ('New classroom block', 6, 1, 3, 2, 'building'), ('Playground', 1, 4, 4, 2, 'road'), ('Playing field (smaller)', 6, 4, 3, 2, 'green'), ('Sports hall', 6, 6, 3, 2, 'building'), ('Car park', 1, 7, 3, 1, 'road'), ('Cycle shelter', 4, 6, 1, 1, 'building'), ('Entrance', 4, 7, 1, 1, 'road')]},
         features='The school has expanded mainly onto its playing field, which has been reduced to less than half its original size. A new classroom block has been built at the northern end of the field and a sports hall at the southern end. A cycle shelter has been added near the entrance; the main building, playground and car park are unchanged.'),
    dict(kind='map', title='An industrial area redeveloped',
         desc='an area beside the river in Callow in 2000 and in 2025',
         panels={'2000': [('River', 0, 0, 10, 2, 'water'), ('Warehouses', 0, 2, 4, 2, 'building'), ('Factory', 5, 2, 5, 3, 'building'), ('Railway', 0, 5, 10, 1, 'road'), ('Waste ground', 0, 6, 5, 2, 'sand'), ('Lorry depot', 6, 6, 4, 2, 'road')],
                 '2025': [('River', 0, 0, 10, 2, 'water'), ('Riverside walk', 0, 2, 10, 1, 'green'), ('Apartments', 0, 3, 4, 2, 'building'), ('Arts centre (old factory)', 5, 3, 5, 2, 'building'), ('Tram line', 0, 5, 10, 1, 'road'), ('Park', 0, 6, 5, 2, 'green'), ('Offices', 6, 6, 4, 2, 'building')]},
         features='The area has changed from industrial to residential and leisure use. The warehouses were replaced by apartments and the factory converted into an arts centre, while a riverside walk now runs along the river. The railway has become a tram line, the waste ground a park and the lorry depot an office block.'),
    dict(kind='map', title='A town centre road layout',
         desc='the centre of Oldham Cross in 2005 and today',
         panels={'2005': [('High Street (cars)', 0, 3, 10, 1, 'road'), ('Shops', 0, 1, 10, 2, 'building'), ('Bus station', 0, 5, 3, 2, 'building'), ('Car park', 4, 5, 6, 3, 'road'), ('Shops', 0, 4, 10, 1, 'building')],
                 'Today': [('High Street (pedestrians)', 0, 3, 10, 1, 'green'), ('Shops and cafés', 0, 1, 10, 2, 'building'), ('Bus station', 0, 5, 3, 2, 'building'), ('Library and cinema', 4, 5, 3, 3, 'building'), ('Smaller car park', 7, 5, 3, 3, 'road'), ('Shops', 0, 4, 10, 1, 'building')]},
         features='The most significant change is that the High Street has been closed to cars and pedestrianised. About half of the large car park has been replaced by a library and cinema, and some shops now include cafés. The bus station is unchanged.'),
    dict(kind='map', title='An island before and after a wind farm',
         desc='the island of Skerra before and after the building of a wind farm',
         panels={'Before': [('Sea', 0, 0, 10, 8, 'water'), ('Island', 2, 1, 6, 6, 'green'), ('Village', 3, 5, 2, 1, 'building'), ('Pier', 3, 6, 1, 1, 'road'), ('Hills', 5, 2, 2, 2, 'sand')],
                    'After': [('Sea', 0, 0, 10, 8, 'water'), ('Island', 2, 1, 6, 6, 'green'), ('Village', 3, 5, 2, 1, 'building'), ('Longer pier', 3, 6, 1, 2, 'road'), ('Wind turbines', 5, 1, 2, 3, 'building'), ('Access road', 4, 4, 1, 2, 'road'), ('Control building', 6, 4, 1, 1, 'building')]},
         features='The main change is the construction of wind turbines on the hills in the north-east of the island. An access road now links the village to the turbines, and a control building has been added beside them. The pier has been extended, while the village itself is unchanged.'),
]
