"""PTE Listening Bank 3: Listening Fill in the Blanks (50 items)
Canonical type_id: 'pte-listening-fib'
Live type_name: 'Listening Fill in the Blanks'

Each recording is written once with its three gaps in braces, e.g. "{microscope}".
The displayed passage replaces them with [[b1]]..[[b3]]; the recording keeps the words.
"""
import re

FIB_RAW = [
    ("Burrs and Velcro",
     "In 1941, the Swiss engineer George de Mestral returned from a walk and noticed burrs stuck to his dog's fur. Under a {microscope}, he saw that each burr was covered in tiny {hooks} that caught on loops of hair and fabric. It took him years to copy this design in nylon, but the fastener he patented in the 1950s became known as Velcro, a clear example of engineers learning from {nature}."),
    ("The accidental sticky note",
     "In 1968, a chemist at the company 3M was trying to create a very strong glue, but he produced one that was surprisingly {weak}. It stuck to surfaces yet could be removed without leaving a mark. For years nobody found a use for it, until a colleague used it to keep {bookmarks} in place in his choir book. The sticky notes finally went on {sale} in 1980."),
    ("Percy Spencer's magnetron",
     "During the Second World War, the engineer Percy Spencer worked on {radar} equipment. One day, while standing near a device called a magnetron, he noticed that a chocolate bar in his {pocket} had melted. He then tested the effect on popcorn kernels, which popped. His company patented the idea, and the first microwave ovens were large, expensive machines used mainly in {restaurants} and on ships."),
    ("Discovering Teflon",
     "In 1938, the chemist Roy Plunkett was working with a gas stored in metal {cylinders}. When he opened one, no gas came out. Cutting it open, he found a white, waxy {powder} that was extremely slippery and resisted heat and chemicals. The material, later called Teflon, was first used in industry, and only in the 1950s did a French engineer use it to coat frying {pans}."),
    ("Safer matches",
     "Early matches could be lit by striking them on almost any rough surface, which made them {dangerous}. Many also contained white phosphorus, a toxic substance that seriously harmed the health of factory {workers}. The safety match, developed in Sweden in the nineteenth century, solved both problems by moving the reactive chemical, red phosphorus, from the match head onto a {strip} on the side of the box."),
    ("The Gem clip",
     "The familiar paper clip, a loop of steel wire bent into a double oval, has a surprisingly unclear history. In the late nineteenth century, many inventors patented {designs} for holding sheets of paper together. The most successful shape, often called the Gem clip, was never actually patented by its original maker. In Norway, the paper clip became a symbol of {resistance} during the Second World War, when people wore them on their {clothes}."),
    ("The first barcode",
     "The idea for the barcode came from a student who drew lines in the {sand} while thinking about Morse code. The first patent was granted in 1952, but the technology only became practical once {lasers} and computers were cheaper. In 1974, a packet of chewing gum became the first product to be scanned at a supermarket {checkout} in the United States."),
    ("The ballpoint pen",
     "The Hungarian journalist László Bíró noticed that newspaper ink dried {quickly} without smudging, but it was too thick to flow through a fountain pen. Working with his brother, he designed a pen with a tiny rotating {ball} at its tip, which picked up ink and rolled it onto the paper. During the Second World War, the pens were valued by air crews because they did not {leak} at high altitude."),
    ("Appert's jars",
     "In the early nineteenth century, the French government offered a prize for a better way to feed its {armies}. A confectioner named Nicolas Appert won it by sealing food in glass jars and then {boiling} them. He did not know why the method worked; it was decades before Louis Pasteur showed that heat kills microbes. Tin cans soon replaced glass, although a practical can {opener} did not appear until much later."),
    ("Instant noodles",
     "Instant noodles were invented in Japan in 1958 by Momofuku Ando, who had seen long {queues} for noodle soup during the food shortages after the war. His key discovery was that frying cooked noodles in hot oil removed their {moisture} and left tiny holes, so they softened quickly in boiling water. In 1971 he added a waterproof {cup}, creating a product that is now eaten around the world."),
    ("The first crossword",
     "The first modern crossword was published in a New York newspaper in December 1913. Its creator, Arthur Wynne, called it a word-cross and arranged it in a {diamond} shape. The puzzle quickly became popular, and by the 1920s crosswords were a national {craze}, with books of puzzles selling in huge numbers. Some critics even complained that people were wasting too much {time} on them."),
    ("The Penny Black",
     "Before 1840, letters in Britain were usually paid for by the person who {received} them, and the cost depended on the distance travelled. The reformer Rowland Hill argued for a single low price paid in advance by the {sender}. The result was the Penny Black, the world's first adhesive postage {stamp}, which allowed a letter to be sent anywhere in the country for one penny."),
    ("Cat's eyes",
     "In 1934, the English inventor Percy Shaw patented a small device set into the middle of the {road}, containing glass lenses that reflect car headlights back towards the driver. According to a popular story, the idea came to him when his headlights were reflected in the {eyes} of a cat on a dark night. The design is clever: when a car drives over it, the rubber housing is pushed down and the lenses are wiped {clean} by rainwater collected inside."),
    ("Defining the metre",
     "Before the French Revolution, France used hundreds of different local units of {measurement}, which made trade confusing and unfair. In the 1790s, scientists proposed a new system based on nature. The metre was defined as one ten-millionth of the distance from the North Pole to the {equator}, and two astronomers spent years {surveying} the line between Dunkirk and Barcelona to calculate it."),
    ("The Terracotta Army",
     "In 1974, farmers digging a {well} near the Chinese city of Xi'an found fragments of a clay figure. They had discovered the Terracotta Army, thousands of life-sized soldiers buried with China's first emperor more than two thousand years ago. Each figure has an individual {face}. The soldiers were originally brightly painted, but much of the colour flakes away within minutes of being exposed to {air}."),
    ("The Mongol relay",
     "The Mongol Empire of the thirteenth century covered an enormous area, and it relied on a relay system called the Yam to carry {messages}. Riders travelled between stations placed along major routes, where they could collect fresh {horses}, food and shelter. Official messengers carried a metal tablet, a kind of {passport}, which guaranteed them help at every station."),
    ("The 1918 flu pandemic",
     "The influenza pandemic of 1918 killed tens of millions of people worldwide. Unusually, many of its victims were healthy young {adults} rather than the very old or very young. It became known as Spanish flu, not because it started in Spain, but because Spain was {neutral} in the First World War and its newspapers reported the outbreak freely, while other countries {censored} the news."),
    ("Harry Beck's diagram",
     "The London Underground map was redesigned in 1931 by Harry Beck, an engineering draughtsman. Instead of showing the true {distances} between stations, he used straight lines, even spacing and angles of forty-five or ninety degrees, rather like an electrical {circuit} diagram. Managers were doubtful at first, but passengers found it far easier to {read}, and the style has been copied by transport networks worldwide."),
    ("The Shinkansen",
     "Japan's high-speed railway, the Shinkansen, opened in 1964, just before the Tokyo Olympic Games. It is famous for its {punctuality}: the average delay is usually measured in seconds rather than minutes. Trains are cleaned in about seven minutes at the end of each journey, and the network has an outstanding {safety} record, partly because it runs on dedicated tracks without level {crossings}."),
    ("Kintsugi",
     "Kintsugi is a Japanese technique for repairing broken bowls and cups. Instead of hiding the {cracks}, the craftsperson joins the pieces with a natural lacquer mixed with powdered {gold}, so the repair becomes a visible part of the object. The practice reflects the idea that damage is part of an object's {history} and need not be something to disguise."),
    ("Discovering perspective",
     "In the early fifteenth century, the Florentine architect Filippo Brunelleschi carried out a famous experiment. He painted a view of a building on a wooden panel, made a small {hole} in it, and asked viewers to compare the painting with the real building using a {mirror}. His work helped establish linear perspective, in which parallel lines meet at a single vanishing {point}, making flat pictures appear three-dimensional."),
    ("The Bayeux Tapestry",
     "The Bayeux Tapestry tells the story of the Norman conquest of England in 1066. Despite its name, it is not technically a tapestry, because the images are {embroidered} onto linen rather than woven into the fabric. It is nearly seventy {metres} long and was probably made within a few years of the events it shows. Historians value it as a {source}, while remembering that it presents the story from the Norman point of view."),
    ("Songs stuck in your head",
     "An earworm is a short piece of music that repeats in your head without your control. Research suggests that songs with a fairly fast {tempo} and a simple, easily remembered {melody} are more likely to become stuck. One study even found that chewing {gum} reduced the problem, possibly because moving the jaw interferes with the silent rehearsal of music."),
    ("Perfect pitch",
     "Absolute pitch, often called perfect pitch, is the ability to identify a musical note without hearing any reference {note} first. It is rare in the general population. Studies suggest it is more common among people who began musical {training} at a very young age, and among speakers of tone languages such as Mandarin, where changes in pitch can change the {meaning} of a word."),
    ("Hangul",
     "The Korean alphabet, Hangul, was created in the fifteenth century under King Sejong, who wanted ordinary people, not only scholars, to be able to {read} and write. Before then, Korean was written mainly with Chinese characters, which took years to learn. Some consonant shapes were designed to represent the position of the {mouth} and tongue when making the sound. Today South Korea celebrates the alphabet with a national {holiday} each October."),
    ("Silbo Gomero",
     "On La Gomera, one of the Canary Islands, people developed a way of communicating across deep {valleys} by whistling. The whistled language, known as Silbo Gomero, turns the sounds of Spanish into changes in pitch and can carry over several {kilometres}. After it almost disappeared, it was added to the island's school {curriculum}, and UNESCO has recognised it as part of the world's cultural heritage."),
    ("The Voynich manuscript",
     "The Voynich manuscript is a book of about two hundred and forty pages written in an unknown {script}, illustrated with strange plants and diagrams. Radiocarbon dating has shown that its parchment was made in the early fifteenth {century}. Despite decades of effort by codebreakers and linguists, nobody has convincingly {deciphered} it, and some suspect it may be an elaborate hoax."),
    ("Writing at the speed of speech",
     "Before audio recorders, journalists and court reporters relied on shorthand to write down speech as quickly as people {talked}. One influential system, published by Isaac Pitman in 1837, recorded the {pronunciation} of words rather than their spelling, using simple strokes of different thickness. Skilled writers could take down well over a hundred words a {minute}."),
    ("Pangolins",
     "Pangolins are the only mammals covered in hard {scales}, which are made of keratin, the same material as human fingernails. When threatened, a pangolin rolls into a tight {ball}, protecting its soft belly. Sadly, this defence does not protect it from people, and pangolins are thought to be among the most {trafficked} mammals in the world, hunted for their meat and scales."),
    ("The axolotl",
     "The axolotl is a salamander from the lakes around Mexico City. Unusually, it keeps its juvenile features, such as feathery external {gills}, throughout its adult life. It can also regrow lost limbs and even parts of its spinal cord without {scarring}, which has made it important in medical research. Yet in the wild it is critically {endangered}, mainly because of pollution and urban growth."),
    ("Hippos and red sweat",
     "Hippopotamuses spend much of the day in water, but on land their skin can burn and dry out. They produce an oily {secretion}, sometimes called blood sweat, which turns red and then brown. Researchers in Japan found that it contains pigments that absorb ultraviolet {light}, acting like a natural sunscreen, and it may also help to prevent {infection} in wounds."),
    ("The Arctic fox's coat",
     "The Arctic fox changes its {coat} with the seasons. In winter it is thick and white, helping the fox blend in with the snow and survive temperatures far below zero. In summer the fox moults, and its fur becomes thinner and brown or grey, matching the rocks and plants of the {tundra}. It also has short ears and legs, which reduce heat {loss}."),
    ("Termite air conditioning",
     "Some African termites build tall mounds of soil above their underground nests. Tunnels inside the mound help air {circulate}, removing carbon dioxide and keeping conditions stable for the colony. These structures inspired the Eastgate Centre in Harare, Zimbabwe, an office building designed to stay cool using natural {ventilation} instead of conventional air {conditioning}."),
    ("Seahorse fathers",
     "Seahorses are among the very few animals in which the male becomes {pregnant}. The female transfers her eggs into a special {pouch} on the male's body, where they are fertilised. The father protects the developing young for several weeks, before giving birth to dozens or even hundreds of tiny, fully formed {babies}."),
    ("The platypus bill",
     "The platypus hunts at the bottom of rivers with its eyes, ears and nostrils {closed}. It finds food using thousands of sensors in its bill that detect the weak {electric} fields produced when shrimp and insect larvae move their muscles. Combined with the fact that it lays {eggs}, this makes the platypus one of the most unusual mammals on Earth."),
    ("The wandering albatross",
     "The wandering albatross has the largest wingspan of any living bird, reaching more than three {metres}. It can travel huge distances over the Southern Ocean while hardly flapping its wings, using a technique called dynamic {soaring}, in which it gains energy from the difference in wind speed just above the {waves}."),
    ("Monarch butterflies",
     "Every autumn, millions of monarch butterflies fly from Canada and the United States to forests in central {Mexico}, a journey of up to four thousand kilometres. Remarkably, no single butterfly makes the round trip; the return journey takes several {generations}. The insects appear to navigate using the position of the {sun}, adjusted by an internal clock."),
    ("Horseshoe crab blood",
     "Horseshoe crabs have blue blood, coloured by {copper}. Their blood contains cells that react to tiny amounts of bacterial toxins, so it is used to test whether medicines and medical {equipment} are safe. The crabs are collected, partly drained of blood and returned to the sea, but some do not {survive}, which has encouraged the development of synthetic alternatives."),
    ("Why popcorn pops",
     "A popcorn kernel contains a small amount of water inside a hard outer shell. When the kernel is heated, this water turns to {steam}, and the {pressure} inside rises until the shell suddenly breaks. The soft starch then expands into a {foam} and quickly sets, turning the kernel inside out."),
    ("Why bread goes stale",
     "Stale bread feels dry, but staling is not mainly caused by bread losing {water}. As bread cools after baking, its starch molecules slowly rearrange into a more {crystalline} structure, making the crumb firm. This process happens fastest at refrigerator temperatures, which is why bread kept in the {fridge} goes stale sooner than bread kept at room temperature."),
    ("Gritting in winter",
     "Salt is spread on icy roads because it lowers the {temperature} at which water freezes, so ice melts even when the air is below zero. However, it becomes much less effective in very severe cold. Road salt also has costs: it causes {rust} on cars and bridges, and when it washes into streams and soil it can harm plants and freshwater {wildlife}."),
    ("The vacuum flask",
     "The vacuum flask was invented in 1892 by the Scottish scientist James Dewar, who needed to keep chemicals very {cold}. It has two walls with a vacuum between them. Because there is almost no air in the gap, heat cannot easily travel by {conduction} or convection, and a {silver} coating on the walls reflects heat radiation. A German company later sold the design for everyday use."),
    ("Glow sticks",
     "A glow stick contains two chemicals kept apart by a thin glass {tube}. Bending the stick breaks the tube, and the chemicals mix, releasing energy as {light} rather than heat, a process called chemiluminescence. A dye controls the colour. Placing a glow stick in the {freezer} slows the reaction, so it shines more dimly but lasts much longer."),
    ("A siren's changing pitch",
     "When an ambulance passes you, its siren seems to drop in {pitch}. This is the Doppler effect, described by the Austrian physicist Christian Doppler in 1842. As the source moves towards you, the sound waves are squeezed closer together; as it moves away, they are {stretched}. The same principle is used in police speed guns, weather {radar} and medical ultrasound."),
    ("Golf ball dimples",
     "Early golf balls were smooth, but players noticed that old, {scuffed} balls flew further. Modern balls therefore have hundreds of small dimples. These create a thin layer of turbulent air around the ball, which helps the airflow cling to its surface and reduces the {wake} behind it. The result is less {drag}, so a dimpled ball can travel roughly twice as far as a smooth one."),
    ("Running out of glycogen",
     "Marathon runners sometimes describe hitting the wall, usually after about thirty kilometres. At that point, the body's stores of {glycogen}, a form of carbohydrate held in the muscles and liver, are running low. The body must rely more on {fat}, which releases energy more slowly, so the runner feels exhausted. Eating carbohydrates before and during the race helps {delay} this moment."),
    ("Streaks in basketball",
     "Many sports fans believe in the hot hand: the idea that a player who has scored several times in a row is more likely to score {again}. A famous study of basketball in 1985 found no {evidence} for this and called it a cognitive illusion. However, later researchers discovered a subtle {error} in the statistical method, and the debate has reopened."),
    ("Two-factor security",
     "Two-factor authentication protects an account by asking for two different kinds of evidence: something you know, such as a {password}, and something you have, such as your {phone}. Even if criminals steal the password, they cannot log in without the second factor. Security experts generally consider codes from an authentication app safer than codes sent by text {message}."),
    ("Ten thousand steps",
     "The popular goal of walking ten thousand steps a day did not come from medical research. It began as a {marketing} idea in Japan in the 1960s, when a company sold a step counter whose name meant ten-thousand-step {meter}. More recent studies suggest that health benefits increase with more steps but begin to {level} off at lower totals for many people, especially older adults."),
    ("Edmond Albius and vanilla",
     "Vanilla comes from an orchid native to Mexico, where it is pollinated by local {bees}. When the plant was grown elsewhere, it flowered but produced almost no pods. In 1841, Edmond Albius, a twelve-year-old enslaved boy on the island of Réunion, developed a quick way to pollinate each flower by {hand}. His method is still used today, and the intensive {labour} it requires helps explain why vanilla is so expensive."),
]

_BLANK = re.compile(r"\{([^{}]+)\}")

FIB_ITEMS = []
for idx, (title, marked) in enumerate(FIB_RAW, 1):
    answers = _BLANK.findall(marked)
    assert len(answers) == 3, f"FIB {idx}: expected 3 blanks, got {answers}"
    counter = iter(range(1, 4))
    passage = _BLANK.sub(lambda m: f"[[b{next(counter)}]]", marked)
    transcript = _BLANK.sub(lambda m: m.group(1), marked)
    FIB_ITEMS.append({
        "id": f"q-pl90-fib-{idx:02d}",
        "type_id": "pte-listening-fib",
        "type_name": "Listening Fill in the Blanks",
        "title": title,
        "prompt": "You will hear a recording. Type the missing words in each blank.",
        "context_passage": passage,
        "audio_transcript": transcript,
        "blanks": [{"id": f"b{n}", "correctAnswer": a} for n, a in enumerate(answers, 1)],
        "correct_answers": None,
        "options": None,
        "time_limit_seconds": 120,
        "prep_time_seconds": 7,
        "points": 3,
        "explanation": "The recording says: " + ", ".join(answers) + ".",
    })
