"""PTE Listening Bank 3: Highlight Incorrect Word (50 items)
Canonical type_id: 'pte-highlight-incorrect-word'
Live type_name: 'Highlight Incorrect Word'

Each recording is written once with its three changed words as {spoken|shown}.
The learner hears the spoken words and reads a transcription with the shown words;
each shown word differs clearly in meaning from what the speaker says.
"""
import re

HIW_RAW = [
    ("Measles and herd immunity",
     "Measles is one of the most {contagious|dangerous} diseases known. When a high proportion of a community is vaccinated, the virus struggles to find new hosts, and even people who cannot be vaccinated, such as newborn babies, are {protected|infected}. This is called herd immunity. For measles, experts estimate that about ninety-five percent of people need to be immune, one of the {highest|lowest} thresholds of any disease."),
    ("Insulin in Toronto",
     "Before 1922, a diagnosis of type one diabetes was usually {fatal|temporary} within a few years. In 1921, researchers in Toronto extracted insulin from the pancreas and showed that it lowered blood {sugar|pressure}. The following year, a fourteen-year-old boy became the first patient to receive an injection, and his condition improved {dramatically|slightly}. The discovery earned a Nobel Prize in 1923."),
    ("Allbutt's thermometer",
     "Early medical thermometers were about a {foot|metre} long and could take twenty minutes to give a reading. In 1867, the English doctor Thomas Allbutt designed a much {shorter|heavier} thermometer that took only about five minutes. This made it practical for doctors to measure temperature routinely, helping them track the progress of {fevers|injuries} in their patients."),
    ("Landsteiner's blood types",
     "Early blood transfusions were extremely {risky|popular}, because some patients reacted violently to the donated blood. In 1901, the Austrian scientist Karl Landsteiner showed that human blood falls into different {groups|colours}, and that mixing incompatible types causes the cells to clump together. His discovery made transfusions far {safer|cheaper} and led to the development of blood banks."),
    ("Lemons at sea",
     "In 1747, the Scottish naval surgeon James Lind tested several treatments for scurvy on sick {sailors|soldiers}. Those given oranges and lemons recovered far more {quickly|slowly} than the others. It was one of the first controlled trials in medicine, although the British navy did not supply citrus juice to all its ships until decades later. The cause, a lack of vitamin C, was identified only in the {twentieth|eighteenth} century."),
    ("Iodine and goitre",
     "A lack of iodine in the diet can cause goitre, a swelling of the {neck|knee}, and can harm the brain development of children. In the 1920s, Switzerland and the United States began adding small amounts of iodine to table {salt|sugar}. Because almost everyone uses salt, the measure reached whole populations at very low cost, and it is often described as one of the most {effective|expensive} public health measures ever introduced."),
    ("What a fever does",
     "A fever is not simply a sign that something has gone wrong. When the body detects an infection, a region of the brain raises its temperature {setting|limit}, and we begin to shiver to produce extra heat. Higher temperatures appear to help some immune cells work more {efficiently|slowly}, and may make conditions less comfortable for certain {microbes|patients}. Very high fevers, however, still need medical attention."),
    ("Ice-cream headaches",
     "Brain freeze is the sudden headache that can follow eating ice cream too {quickly|slowly}. It happens when something very cold touches the roof of the mouth, causing nearby blood vessels to narrow and then rapidly widen. Nerves in the area send pain signals that the brain interprets as coming from the {forehead|stomach}. Pressing the tongue against the roof of the mouth to warm it can make the pain {fade|worse}."),
    ("Motion sickness",
     "Motion sickness is thought to result from a {conflict|agreement} between the senses. In a moving car, the balance organs in the inner ear detect motion, but a passenger reading a book sees a page that appears {still|bright}. The brain receives mixed signals, which can cause nausea. Looking out at the {horizon|floor} helps because it allows the eyes to confirm the movement the body feels."),
    ("Cracking knuckles",
     "The sound of cracking knuckles comes from the joint, not the {bones|muscles}. When the joint is stretched, the pressure in the fluid around it drops and a {bubble|crystal} forms, making a popping sound. Many people believe the habit causes arthritis, but studies have found no clear link. One doctor cracked the knuckles of only one hand for sixty years and found no {difference|damage} between his hands."),
    ("Naming umami",
     "In 1908, the Japanese chemist Kikunae Ikeda wondered why a broth made from {seaweed|mushrooms} tasted so savoury. He identified the cause as glutamate and named the taste umami. For decades, many Western scientists {doubted|accepted} that it was a basic taste like sweet, sour, salty and bitter. It was only around the year 2000 that researchers found specific {receptors|vitamins} for it on the tongue."),
    ("Capsaicin",
     "The burning feeling from chilli peppers comes from a chemical called capsaicin, which activates the same nerve {receptors|muscles} that detect heat. Mammals feel this burn, but birds do not, and this may benefit the plant, because birds swallow the seeds whole and spread them {widely|slowly}. Drinking milk tends to relieve the burning better than {water|coffee}, which mostly spreads the capsaicin around the mouth."),
    ("Nightingale's diagrams",
     "Florence Nightingale is remembered as a nurse, but she was also a skilled {statistician|novelist}. During the Crimean War, she collected data showing that far more soldiers were dying from {disease|hunger} than from injuries in battle. She presented the figures in colourful circular diagrams that politicians could understand {easily|reluctantly}, and her work helped bring about major reforms in hospital hygiene."),
    ("The carrot story",
     "The belief that carrots help you see in the dark was spread partly by the British during the Second World War. Their pilots were shooting down enemy aircraft at night using new {radar|engines}, and officials encouraged stories that the pilots ate large amounts of carrots to keep the technology {secret|cheap}. Carrots do contain a substance the body turns into vitamin A, but eating extra will not improve normal {eyesight|hearing}."),
    ("Oral rehydration",
     "Diarrhoeal diseases such as cholera kill mainly by causing severe {dehydration|fever}. In the 1960s and 1970s, researchers working in South Asia showed that a simple drink of clean water, salt and {sugar|milk} could replace lost fluids, because sugar helps the intestine absorb salt and water. This cheap treatment, known as oral rehydration solution, is credited with saving {millions|hundreds} of lives."),
    ("Maria Montessori",
     "Maria Montessori was one of the first women in Italy to qualify as a {doctor|lawyer}. In 1907, she opened a school for young children in a poor district of Rome. Her classrooms had child-sized {furniture|windows}, and children chose their own activities from carefully designed materials. She believed that children learn best through independent {exploration|punishment}, an approach still used in thousands of schools."),
    ("Froebel's kindergarten",
     "The word kindergarten, meaning children's garden, was created by the German educator Friedrich Froebel in the nineteenth {century|month}. He believed young children learn through {play|work}, songs and hands-on activity rather than memorising facts. He designed sets of wooden blocks and shapes, called gifts, and the architect Frank Lloyd Wright later said that playing with them as a child influenced his {designs|diet}."),
    ("The Socratic method",
     "The Socratic method is named after the Greek philosopher Socrates, who taught by asking {questions|stories} rather than giving answers. By asking a student to explain and defend a belief, he aimed to reveal hidden assumptions and {contradictions|agreements}. We know about his conversations mainly through the writings of his student Plato, and a version of the method is still widely used in {law|cookery} schools today."),
    ("The Great Vowel Shift",
     "English spelling often seems {illogical|modern}, and one reason is the Great Vowel Shift. Between roughly 1400 and 1700, the pronunciation of long vowels in English changed {dramatically|slightly}. At the same time, printing helped to fix spellings, so many words are still written in a way that reflects how they were {pronounced|translated} centuries ago."),
    ("Johnson's dictionary",
     "Samuel Johnson's Dictionary of the English Language was published in 1755 after about nine years of {work|travel}. It defined around forty thousand words, and its most important innovation was the use of {quotations|pictures} from well-known writers to show how each word was actually used. Some definitions were famously {humorous|brief}, and the dictionary remained the leading authority for over a century."),
    ("Volunteers and the OED",
     "The Oxford English Dictionary relied on thousands of {volunteers|professors} who read books and posted slips of paper showing how words had been used. The project began in the 1850s and was expected to take about ten years, but the final volume was not published until {1928|1882}. One of the most productive contributors was a {doctor|sailor} held in a psychiatric hospital."),
    ("Where OK came from",
     "The word OK is used around the world, but its origin was debated for a long time. The linguist Allen Walker Read showed that it first appeared in a Boston {newspaper|novel} in 1839, as a joke abbreviation of oll korrect, a deliberate misspelling of all correct. Such jokey abbreviations were {fashionable|forbidden} at the time. The word survived partly thanks to the 1840 presidential {election|debate}, when supporters of Martin Van Buren, nicknamed Old Kinderhook, used it as a slogan."),
    ("The first emoji",
     "The first widely used set of emoji was designed in 1999 by Shigetaka Kurita for a Japanese mobile phone {company|museum}. Each of the 176 symbols was only twelve pixels {wide|tall} and twelve pixels high. The idea was to help people express emotion in short messages. Today the original set is held in the collection of the Museum of Modern Art in New {York|Delhi}."),
    ("Cracking Linear B",
     "Clay tablets inscribed with a script called Linear B were discovered on the island of {Crete|Cyprus} around 1900. For half a century nobody could read them. In 1952, Michael Ventris, an {architect|archaeologist} with a passion for codes, showed that the script recorded an early form of Greek. Disappointingly for some, most tablets turned out to be ordinary administrative {records|poems}, such as lists of goods and workers."),
    ("The fire of 1666",
     "The Great Fire of London began in a {bakery|church} in September 1666 and burned for four days. It destroyed more than thirteen thousand houses, many of them built of {wood|stone}. After the fire, new rules required buildings to be made of brick or stone, streets were widened, and the first fire {insurance|brigade} companies were established in the city."),
    ("Alexandria's collection",
     "The Library of Alexandria in Egypt was founded around the third century BC with the aim of collecting every {book|coin} in the known world. According to ancient accounts, ships arriving in the harbour were searched for scrolls, which were {copied|burned} for the library. Popular stories describe its destruction in a single fire, but historians now believe it declined {gradually|suddenly} over several centuries."),
    ("The first underground railway",
     "London's Metropolitan Railway, opened in {1863|1936}, was the world's first underground railway. Its trains were pulled by steam locomotives, so the tunnels were often filled with {smoke|water}, despite openings built to let it escape. Even so, the line was an immediate success, carrying tens of thousands of passengers on its first {day|night}."),
    ("Vulcanisation",
     "In the early nineteenth century, natural rubber was of limited use because it became sticky in {summer|winter} and brittle in cold weather. The American inventor Charles Goodyear spent years experimenting, and in 1839 he found that heating rubber with {sulphur|sugar} made it strong and flexible at all temperatures. The process, called vulcanisation, made modern tyres possible, yet Goodyear died heavily in {debt|luxury}."),
    ("The first lawn mower",
     "The first lawn mower was invented in 1830 by the English engineer Edwin Budding, who got the idea from a machine used to trim the surface of {cloth|paper} in textile mills. Before this, lawns were cut by workers with {scythes|scissors}, which only the wealthy could afford. Budding's mower made neat lawns possible for many more people and helped popularise sports played on {grass|ice}, such as tennis."),
    ("The South Sea Bubble",
     "In 1720, shares in Britain's South Sea Company rose to extraordinary {levels|lows} before collapsing within months. The company had promised enormous profits from trade with South America, but these profits never appeared. Many investors were {ruined|rewarded}, including, according to popular accounts, the scientist Isaac Newton, who is said to have remarked that he could calculate the motions of the heavenly bodies, but not the {madness|wisdom} of people."),
    ("Coubertin's Games",
     "The modern Olympic Games were revived by the French educator Pierre de Coubertin, who believed sport could improve {education|agriculture} and international understanding. The first Games took place in Athens in 1896, with athletes from about fourteen {nations|cities}. Only men competed; women took part for the first time four years later in {Paris|Rome}."),
    ("Pigeons at war",
     "Carrier pigeons were widely used to carry messages during the First World War, because they could fly home {quickly|silently} even when telephone lines were cut. One famous pigeon, Cher Ami, delivered a message in 1918 that helped save a group of trapped American {soldiers|farmers}, despite being badly {wounded|trained} on the way."),
    ("Chappe's semaphore",
     "In the 1790s, the French engineer Claude Chappe built a network of {towers|bridges} with movable wooden arms. Operators watched the next tower through a {telescope|window} and copied the positions of its arms, passing coded messages across the country far faster than a rider on horseback. The system was eventually replaced by the {electric|steam} telegraph in the nineteenth century."),
    ("Ada Lovelace",
     "In 1843, Ada Lovelace published detailed notes on a {mechanical|electrical} computer designed by Charles Babbage, called the Analytical Engine. The machine was never completed, but her notes included a method for calculating a sequence of numbers, often described as the first computer {program|poem}. She also suggested that such machines might one day work with symbols beyond {numbers|letters}, such as musical notes."),
    ("Codebreakers at Bletchley Park",
     "During the Second World War, codebreakers at Bletchley Park in England worked to read {encrypted|handwritten} German messages. Mathematicians including Alan Turing designed electromechanical machines called bombes to speed up the work. Around three quarters of the staff were {women|volunteers}, and their achievements remained secret for {decades|weeks} after the war ended."),
    ("Hedy Lamarr",
     "Hedy Lamarr was a famous Hollywood {actress|singer}, but she was also an inventor. In 1942, she and the composer George Antheil patented a system in which a radio signal jumped rapidly between {frequencies|countries}, making it hard to jam. The navy did not use it at the time, but the principle of frequency hopping later contributed to wireless {technologies|medicines}."),
    ("The transistor",
     "The transistor was invented at Bell Laboratories in the United States in {1947|1974}. It could amplify and switch electrical signals like the vacuum tubes used in early computers, but it was much {smaller|louder} and used far less power. Its three inventors shared a Nobel Prize, and today a single computer chip can contain {billions|dozens} of transistors."),
    ("A moth in the machine",
     "In 1947, operators of the Harvard Mark II computer found a {moth|mouse} trapped in one of its relays. They taped it into the logbook with the note that this was the first actual case of a bug being found. The joke worked because engineers had already used the word bug for {faults|ideas} in machines for decades; even Thomas Edison had used it in the {1870s|1970s}."),
    ("The first message online",
     "The first message sent over ARPANET, an early forerunner of the internet, travelled between two research {centres|hospitals} in California in October 1969. The operator intended to type the word login, but the system {crashed|restarted} after the first two letters. As a result, the very first message was simply lo. About an {hour|year} later, the full word was sent successfully."),
    ("Clever octopuses",
     "Octopuses have around five hundred million {neurons|bones}, and about two thirds of them are located in their arms rather than their brain. In aquariums, they have been seen opening screw-top {jars|doors} and escaping from their tanks. In the wild, one species carries coconut shells across the sea floor and uses them as a portable {shelter|weapon}."),
    ("Alex the parrot",
     "Parrots are famous for copying human speech, but some research suggests they can do more than {imitate|forget}. An African grey parrot named Alex, studied for thirty years, learned to name dozens of objects, {colours|countries} and shapes. He could even answer questions about which items were the same or different, although scientists still debate how much he truly {understood|remembered}."),
    ("The Arctic tern",
     "The Arctic tern makes the longest known migration of any animal. Each year it flies from its breeding grounds in the Arctic to the {Antarctic|tropics} and back again, a round trip that tracking studies have measured at around seventy thousand {kilometres|metres}. As a result, it experiences two {summers|winters} every year and sees more daylight than almost any other creature."),
    ("An unusual underground rodent",
     "Naked mole-rats are small, almost hairless rodents that live underground in East Africa. They live in colonies with a single breeding {queen|leader}, rather like bees or ants. They can live for more than thirty {years|months}, far longer than other rodents of similar size, and they very rarely develop {cancer|allergies}, which makes them of great interest to medical researchers."),
    ("Slow-moving sloths",
     "Sloths move slowly because their diet of leaves provides very little {energy|water}. Their metabolism is unusually slow, and they may come down from the trees only about once a {week|day} to go to the toilet. Their fur even hosts tiny algae that give it a greenish colour, which may help to {camouflage|feed} them among the leaves."),
    ("What koalas eat",
     "Koalas feed almost entirely on eucalyptus leaves, which are low in nutrients and contain {toxic|sweet} compounds. Special bacteria in their gut help them break the leaves down, and young koalas acquire these microbes from their {mothers|siblings}. Because their diet provides so little energy, koalas may sleep or rest for up to twenty {hours|minutes} a day."),
    ("Cleaner wrasse",
     "Cleaner wrasse are small fish that set up cleaning stations on coral reefs. Larger fish, including {predators|plants} that could easily eat them, wait in line and open their mouths to allow the wrasse to remove {parasites|sand}. Both sides benefit, but researchers have observed that cleaners sometimes cheat by biting off healthy tissue, and they behave more {honestly|aggressively} when other clients are watching."),
    ("Starling murmurations",
     "In winter, starlings sometimes gather in flocks of many thousands and perform swirling displays called murmurations. The birds appear to move as one, yet there is no {leader|nest}. Research suggests that each starling responds to about seven of its nearest {neighbours|predators}, and these local reactions spread rapidly across the flock. One likely purpose is protection: a large, constantly changing flock makes it harder for birds of prey to {target|feed} a single individual."),
    ("The peppered moth",
     "Before the Industrial Revolution, most peppered moths in England were pale, which helped them hide on light-coloured {bark|walls}. As factories blackened trees with soot, a dark form became far more {common|rare} in industrial areas, because birds could spot pale moths more easily. After clean air laws were introduced, the {pale|dark} form became common again."),
    ("Darwin's finches",
     "The finches of the Galápagos Islands have beaks of different shapes suited to different {foods|songs}. In the 1970s, researchers studying one small island recorded a severe {drought|flood}, after which mainly large, hard seeds were available. Birds with bigger, stronger beaks survived better, and their offspring inherited larger beaks, providing a rare chance to observe {evolution|migration} within a few years."),
    ("How geysers erupt",
     "A geyser forms where underground water is heated by hot {rock|air} deep below the surface. The water sits in narrow channels under high pressure, so it can become hotter than its normal boiling point without turning to {steam|ice}. When some of it finally boils, the pressure drops suddenly and the column of water erupts. Old Faithful, in Yellowstone National Park, erupts roughly every one to two {hours|days}."),
]

_SWAP = re.compile(r"\{([^{}|]+)\|([^{}|]+)\}")

HIW_ITEMS = []
for idx, (title, marked) in enumerate(HIW_RAW, 1):
    pairs = _SWAP.findall(marked)
    assert len(pairs) == 3, f"HIW {idx}: expected 3 changed words, got {pairs}"
    spoken = _SWAP.sub(lambda m: m.group(1), marked)
    shown = _SWAP.sub(lambda m: m.group(2), marked)
    words = shown.split()
    changed = [f"w{n}" for n, (s, d) in enumerate(zip(spoken.split(), words), 1) if s != d]
    HIW_ITEMS.append({
        "id": f"q-pl90-hiw-{idx:02d}",
        "type_id": "pte-highlight-incorrect-word",
        "type_name": "Highlight Incorrect Word",
        "title": title,
        "prompt": "You will hear a recording. Below is a transcription of the recording. Some words in the transcription differ from what the speaker said. Please click on the words that are different.",
        "context_passage": shown,
        "audio_transcript": spoken,
        "options": [{"id": f"w{n}", "text": w} for n, w in enumerate(words, 1)],
        "correct_answers": changed,
        "blanks": None,
        "time_limit_seconds": 120,
        "prep_time_seconds": 10,
        "points": 3,
        "explanation": "Select " + ", ".join(d for _, d in pairs) + ". The speaker says " + ", ".join(s for s, _ in pairs) + ".",
    })
