"""PTE Listening Bank 3: MCQ Multiple Answer (50 items)
Canonical type_id: 'pte-listening-mcma'
Live type_name: 'MCQ Multiple Answer'

Each item: (title, recording, question, correct options, wrong options, why).
Items have 5-7 options with 2 or 3 correct; the question says TWO or THREE.
Options are placed in a fixed pseudo-random order per item, so correct letters
spread across A-G and the output never changes between runs.
"""
import random

LMCMA_RAW = [
    ("The Dust Bowl",
     "In the 1930s, huge dust storms swept across the southern Great Plains of the United States, a period remembered as the Dust Bowl. In the decades before, farmers had ploughed up millions of hectares of native grassland to grow wheat. The deep roots of the prairie grasses had held the soil in place, even during dry spells. When a long drought arrived in the early 1930s, the exposed topsoil dried out and was carried away by strong winds. Some storms were so large that dust fell on cities on the east coast. Hundreds of thousands of people left the region, many travelling west to California in search of work. The government responded by creating a service to teach soil conservation, encouraging farmers to plough along the contours of the land, rotate crops and plant long rows of trees to break the wind.",
     "Which TWO causes of the Dust Bowl does the speaker mention?",
     ["A long period of drought", "Ploughing that removed the native grasses"],
     ["Heavy floods along major rivers", "A sudden fall in grain prices", "The planting of long rows of trees"],
     "Grassland was ploughed up, and then drought dried out the exposed soil; the tree planting was part of the response."),
    ("The Irish famine",
     "Between 1845 and 1852, Ireland suffered one of the worst famines in modern European history. The immediate cause was potato blight, a disease caused by a fungus-like organism that turned potatoes black and rotten in the ground. The disaster was so severe because a large part of the population, especially the rural poor, depended almost entirely on potatoes for food, and most farmers grew the same variety, which had little resistance. Around one million people died, and at least another million emigrated, many to Britain and North America. The famine remains a painful and controversial subject, partly because food, including grain and livestock, continued to be exported from Ireland while people starved, and many historians criticise the government's response as inadequate. Ireland's population has never returned to the level it reached before the famine.",
     "Which TWO statements about the famine are made by the speaker?",
     ["Many poor families depended heavily on a single crop", "Food continued to be exported from Ireland during the famine"],
     ["The blight was caused by an insect pest", "The population soon returned to its earlier level", "Most emigrants travelled to Australia", "The government banned the planting of potatoes"],
     "The rural poor relied almost entirely on potatoes, and food was still exported while people starved."),
    ("Moving the stones of Stonehenge",
     "Stonehenge, in southern England, was built in several stages over more than a thousand years, beginning around five thousand years ago. One of its greatest puzzles is how the stones arrived. The smaller bluestones, each weighing a few tonnes, have been traced to hills in west Wales, over two hundred kilometres away. The huge sarsen stones, some weighing more than twenty tonnes, came from a much closer source. In 2020, a chemical analysis of a core drilled from one stone identified a likely origin in an area about twenty-five kilometres to the north. Nobody knows exactly how the stones were moved, since the builders left no written records. Experiments suggest that teams of people could have pulled them on wooden sledges running over timber tracks, and some researchers believe the bluestones may have travelled part of the way by water.",
     "Which THREE statements are supported by the recording?",
     ["The smaller stones came from Wales", "The largest stones came from about twenty-five kilometres away", "Nobody knows exactly how the stones were moved"],
     ["The monument was built within a single decade", "The stones were carried on horse-drawn carts", "All of the stones came from one quarry", "The builders left detailed written records"],
     "Bluestones came from Wales, the sarsens from about 25 km away, and the method of transport is unknown."),
    ("Who built the pyramids",
     "For centuries, popular belief held that the pyramids of Egypt were built by huge numbers of slaves, an idea encouraged by ancient Greek writers and, much later, by Hollywood films. Archaeological discoveries near the pyramids at Giza have changed this picture. Since the 1990s, excavations have uncovered a settlement where workers lived, including bakeries and evidence that they ate large amounts of beef. Nearby, archaeologists found the tombs of workers, built close to the pyramids themselves, which would have been an honour unlikely to be given to slaves. Some skeletons show broken bones that had healed properly, suggesting that injured workers received medical care. Many researchers now believe the pyramids were built by a core of skilled, permanent craftsmen, supported by larger groups of labourers who worked in rotation, perhaps as a form of service owed to the state.",
     "Which TWO pieces of evidence suggest that the workers were not slaves?",
     ["They were buried in tombs close to the pyramids", "Their healed bones suggest they received medical care"],
     ["Written contracts listed their wages", "Greek historians praised their working conditions", "They were paid in gold coins", "They lived inside the pyramids during construction"],
     "Tombs near the pyramids and healed injuries point to honoured, cared-for workers."),
    ("Viking longships",
     "Viking longships were among the most advanced vessels of their time. They were built using overlapping wooden planks, a technique that made the hulls both strong and flexible, so they could bend with the waves rather than break. Crucially, the ships sat very low in the water, needing only about a metre of depth. This meant they could sail up rivers far inland and be pulled directly onto beaches, allowing raiders to arrive and leave quickly without a harbour. Longships carried a large square sail but also had oars, so crews could row when the wind dropped or when manoeuvring in narrow channels. The bow and stern were almost identical, so a ship could reverse direction without turning around. These vessels carried Norse explorers across the North Atlantic, and archaeological evidence confirms they reached North America around the year one thousand.",
     "Which TWO features allowed longships to reach places far from the coast or land without a harbour?",
     ["They needed only shallow water to sail", "They could be pulled directly onto beaches"],
     ["They were powered only by their sails", "Their heavy keels kept them stable in deep water", "They were carved from single hollow trees"],
     "Needing about a metre of water, they could go up rivers and land on beaches."),
    ("Apollo 13",
     "In April 1970, the Apollo 13 mission was on its way to the Moon when an oxygen tank in the service module exploded. The planned landing was immediately cancelled, and the priority became bringing the three astronauts home alive. The crew moved into the lunar module, the small craft intended for landing, and used it as a lifeboat, although it was designed to support only two people for about two days. A serious problem soon appeared. Carbon dioxide was building up in the cabin, and the square filters from the main spacecraft did not fit the round openings in the lunar module. Engineers on the ground designed a solution using only materials available on board, including plastic bags, cardboard and tape, and talked the crew through building it. After four tense days, the astronauts splashed down safely, and NASA later called the mission a successful failure.",
     "Which THREE statements about the mission are correct?",
     ["The planned Moon landing was cancelled", "The crew used the lunar module as a lifeboat", "An adaptor for the air filters was made from materials on board"],
     ["A rescue spacecraft was launched to meet them", "The crew returned to Earth within a few hours", "The astronauts repaired the oxygen tank on the Moon"],
     "The landing was cancelled, the lunar module became a lifeboat, and the filter adaptor was improvised."),
    ("After the Tenerife collision",
     "In 1977, two passenger jets collided on a foggy runway on the island of Tenerife, killing five hundred and eighty-three people in the deadliest accident in aviation history. Investigators found that a combination of factors was responsible. Visibility was very poor, radio messages were partly blocked and misunderstood, and one captain began his take-off without clear permission. Other members of his crew appear to have had doubts but did not challenge him forcefully. The disaster led to important changes. Standard radio phrases were tightened, so that the word take-off is now used only when a plane is actually cleared to take off. Airlines also introduced training known as crew resource management, which teaches pilots to work as a team and encourages junior crew members to speak up when they see a problem, however senior the captain. Hospitals and other high-risk workplaces have since adopted similar training.",
     "Which TWO changes followed the accident?",
     ["Stricter rules on when the word take-off may be used", "Training that encourages junior crew members to speak up"],
     ["A ban on flights in foggy weather", "The permanent closure of the airport", "Giving captains complete authority over every decision"],
     "Radio phrasing was tightened and crew resource management training was introduced."),
    ("Hubble's blurred vision",
     "When the Hubble Space Telescope was launched in 1990, astronomers expected spectacular images. Instead, the first pictures were disappointingly blurry. Investigators discovered that the telescope's main mirror had been ground to a slightly incorrect shape. The error was tiny, about one fiftieth of the width of a human hair, but for such a precise instrument it was enough to spoil the images. The mistake was traced to a faulty testing device used during manufacture. Because Hubble orbits the Earth, it could be reached by the space shuttle. In 1993, astronauts carried out a complex servicing mission and installed corrective optics that worked rather like glasses. The results were a dramatic success. Hubble went on to produce some of the most famous images in the history of astronomy and was serviced several more times over the following years.",
     "Which TWO statements about the telescope are correct?",
     ["Its main mirror had been ground to a slightly wrong shape", "Astronauts installed corrective optics in 1993"],
     ["It was brought back to Earth for repair", "The fault was caused by a collision with debris", "It was replaced by a completely new telescope", "The error in the mirror was several centimetres wide"],
     "A tiny error in the mirror's shape was fixed by corrective optics fitted in orbit."),
    ("The Harvard computers",
     "In the late nineteenth century, the director of the Harvard College Observatory hired a group of women to study thousands of photographic plates of the night sky. They were known as computers, because their job was to calculate and classify, and they were paid far less than male assistants would have been. Yet their work transformed astronomy. Annie Jump Cannon examined hundreds of thousands of stars and developed a system for classifying them by the features of their light, a system still taught today. Henrietta Swan Leavitt studied a type of star whose brightness rises and falls regularly, and found that the length of this cycle was linked to the star's true brightness. This allowed astronomers to calculate distances to faraway stars, and it later helped Edwin Hubble show that the universe extends far beyond our own galaxy.",
     "Which TWO achievements does the speaker describe?",
     ["A system for classifying stars that is still used", "A discovery that helped measure distances in space"],
     ["The invention of the photographic telescope", "The first photograph of another galaxy", "A method for predicting solar eclipses"],
     "Cannon's classification system and Leavitt's link between brightness cycles and distance."),
    ("Radar and the Battle of Britain",
     "In the 1930s, the British government asked scientists whether a beam of radio waves could be used as a death ray to destroy enemy aircraft. The physicist Robert Watson-Watt concluded that this was impossible, but he suggested something more useful: radio waves could be used to detect aircraft. By the start of the Second World War, a chain of radar stations along the coast could spot approaching planes long before they arrived. The information was passed to operations rooms, where staff plotted the positions of aircraft on large maps and decided which fighter squadrons to send. This system meant that fighters did not need to patrol the skies constantly, wasting fuel and exhausting pilots. Instead, they could be sent exactly where they were needed. Many historians regard radar as a key factor in the Battle of Britain in 1940.",
     "Which TWO advantages of the radar system are mentioned?",
     ["It detected aircraft long before they reached the coast", "It allowed fighters to be sent only where they were needed"],
     ["It used a beam of energy to destroy aircraft", "It worked only in daylight", "It removed the need for fighter pilots", "It was developed after the war had ended"],
     "Early detection meant fighters could be directed exactly where needed."),
    ("Mosquitoes and malaria",
     "The word malaria comes from the Italian for bad air, reflecting an old belief that the disease was caused by foul air rising from swamps. It was a reasonable guess, since malaria was common near marshes, but the real cause was not understood until the late nineteenth century. In 1880, a French army doctor saw tiny parasites in the blood of a patient. The next question was how the parasite passed from one person to another. In 1897 and 1898, Ronald Ross, a British doctor working in India, showed that mosquitoes carried the parasite and transmitted it through their bites, work that earned him a Nobel Prize. The discovery explained the link with swamps, where mosquitoes breed, and it led to practical measures such as draining standing water and sleeping under nets, which remain important today.",
     "Which TWO statements are supported by the recording?",
     ["The disease's name reflects an old belief about bad air", "Ross showed that mosquitoes transmit the parasite"],
     ["Malaria is caused by a virus in drinking water", "Ross carried out his research in South America", "The discovery immediately produced a vaccine"],
     "Malaria means bad air, and Ross proved mosquitoes spread the parasite."),
    ("Bacteria in the gut",
     "The human gut is home to trillions of microorganisms, mostly bacteria, together known as the gut microbiome. For a long time these organisms received little attention, but research over the past two decades has shown that they play important roles in our health. Many of them break down types of dietary fibre that our own digestive system cannot process, producing substances that nourish the cells lining the gut. Some bacteria produce vitamins, such as vitamin K. The microbiome also appears to help train the immune system. The composition of these communities varies greatly between people and is shaped by diet, environment and medicines. A course of antibiotics, for example, can temporarily reduce their diversity. Researchers are also investigating possible links between gut bacteria and mood, but many of these findings are still at an early stage and should be treated with caution.",
     "Which THREE roles of gut bacteria does the speaker mention?",
     ["Breaking down fibre we cannot digest", "Producing certain vitamins", "Helping to train the immune system"],
     ["Controlling body temperature", "Producing insulin", "Protecting the body against all infections"],
     "Fibre digestion, vitamin production and immune training are all mentioned."),
    ("How bacteria resist antibiotics",
     "When Alexander Fleming accepted the Nobel Prize for the discovery of penicillin in 1945, he warned that misuse of the drug could allow bacteria to become resistant. His warning proved accurate. Bacteria reproduce very quickly, and random changes in their genes occasionally make some of them less vulnerable to a particular antibiotic. When the drug is used, it kills the vulnerable bacteria, but the resistant ones survive and multiply. Bacteria can also pass genes for resistance directly to one another, even across different species, which allows resistance to spread rapidly. Every use of antibiotics creates pressure for resistance, so unnecessary use is particularly harmful. Antibiotics have no effect on viral infections such as colds and flu, yet they have often been prescribed for them. Large quantities have also been used in farming to help animals grow faster, a practice now restricted in many countries.",
     "Which THREE statements are made in the recording?",
     ["Bacteria can pass resistance genes to one another", "Prescribing antibiotics for viral infections adds to the problem", "Antibiotics have been used to make farm animals grow faster"],
     ["Antibiotics work well against colds and flu", "Resistance develops only in hospitals", "Fleming believed resistance could never happen"],
     "Gene sharing, unnecessary use for viral infections and use in farming are all described."),
    ("Caffeine and sleepiness",
     "Why does coffee make us feel more alert? During the hours we are awake, a chemical called adenosine gradually builds up in the brain. As it attaches to receptors on nerve cells, it creates a growing sense of sleepiness. Caffeine has a similar shape to adenosine, so it can occupy these receptors without activating them, effectively blocking the signal that tells us we are tired. Caffeine does not provide energy in the way food does; it simply masks fatigue. Its effects also last longer than many people realise. In a typical adult, it takes around five hours for the body to remove half of the caffeine consumed, so an afternoon coffee may still affect sleep at night. People who drink coffee every day also develop tolerance, meaning they need more to feel the same effect, and they may experience headaches if they suddenly stop.",
     "Which TWO statements about caffeine are correct according to the speaker?",
     ["It blocks a chemical signal that makes us feel sleepy", "It can affect sleep many hours after it is drunk"],
     ["It gives the body extra energy in the form of calories", "Regular drinkers become more sensitive to it over time", "It leaves the body within about an hour"],
     "Caffeine blocks adenosine receptors, and half of it remains after about five hours."),
    ("Sunlight and vitamin D",
     "Vitamin D is unusual among vitamins because the body can make it for itself. When ultraviolet light from the sun reaches the skin, it triggers a chemical reaction that produces vitamin D. The vitamin helps the body absorb calcium from food, which is essential for strong bones. A severe lack of it in childhood can cause rickets, a condition in which bones become soft and bend. In countries far from the equator, the winter sun is too low in the sky for its ultraviolet rays to be strong enough to produce vitamin D, even on a clear day. People with darker skin, which contains more of the pigment that protects against ultraviolet light, generally need longer in the sun to make the same amount. For these reasons, some health authorities advise people to take supplements during winter, while oily fish and eggs provide smaller amounts through diet.",
     "Which TWO statements about vitamin D are made?",
     ["It helps the body absorb calcium", "Winter sunlight far from the equator may be too weak to produce it"],
     ["It is found mainly in green vegetables", "People with darker skin need less sunlight to produce it", "It is made in the liver from sugar"],
     "It aids calcium absorption, and weak winter sun at high latitudes cannot produce it."),
    ("Walking and new ideas",
     "Many writers and thinkers have claimed that they think best while walking. In 2014, researchers at Stanford University tested this idea. Participants were asked to think of creative uses for everyday objects, such as a button or a tyre, either while sitting or while walking. Most people produced considerably more ideas when walking. Surprisingly, it did not matter whether they walked outdoors or on a treadmill facing a blank wall inside a small room; the act of walking itself seemed to be what mattered. The benefit also continued for a short time after participants sat down again. However, walking did not help with every kind of thinking. On tasks that required finding one correct answer, rather than generating many possibilities, walkers performed no better than those who were sitting. The researchers suggested that a walk might be most useful at the start of a project, when new ideas are needed.",
     "Which TWO findings are reported?",
     ["Walking on a treadmill indoors also increased the number of ideas", "Walking did not help with problems that have one correct answer"],
     ["Only walking outdoors in nature had any effect", "The benefit disappeared the moment people sat down", "Participants produced fewer ideas while walking"],
     "The treadmill worked as well as outdoors, but convergent tasks did not improve."),
    ("Why we sweat",
     "Humans are unusually good at sweating. We have millions of sweat glands spread across the skin, far more than most other mammals, and in hot conditions we can lose more than a litre of sweat an hour. Sweat itself does not cool us; the cooling comes when it evaporates, because turning liquid water into vapour takes heat from the skin. This is why humid weather can be dangerous. When the air already contains a lot of moisture, sweat evaporates slowly, and it drips off the body instead of cooling it. Many other animals rely on different methods. Dogs, for example, have few sweat glands and cool down mainly by panting. Some researchers believe our ability to sweat helped early humans hunt by running long distances in the heat, chasing animals until they were exhausted, although this idea is still debated.",
     "Which TWO statements are supported by the recording?",
     ["Sweat cools the body as it evaporates", "Humid air makes sweating less effective"],
     ["Humans have fewer sweat glands than most mammals", "Dogs cool down mainly by sweating through their fur", "Scientists agree that sweating evolved for hunting"],
     "Cooling comes from evaporation, which slows in humid air."),
    ("The eel's life cycle",
     "The European eel has one of the strangest life cycles of any fish. For centuries, nobody knew where eels came from, because no one had ever found eel eggs in European rivers. In the early twentieth century, a Danish scientist followed ever smaller eel larvae across the Atlantic and concluded that they hatch in the Sargasso Sea, a region of the western Atlantic. The tiny, leaf-shaped larvae drift on ocean currents for months or even years until they reach the coasts of Europe, where they turn into young eels and swim up rivers. There they may live for decades before making the long journey back across the ocean to breed, after which they die. Remarkably, no one has ever observed eels spawning in the wild. The species is now critically endangered, and scientists are still trying to understand all the reasons for its decline.",
     "Which TWO statements about European eels are correct?",
     ["Their larvae drift across the Atlantic to reach Europe", "Nobody has observed them spawning in the wild"],
     ["Adults return to European rivers after breeding", "They spend their whole lives in the Sargasso Sea", "Their numbers have increased in recent decades"],
     "Larvae drift to Europe, and spawning has never been observed."),
    ("The coelacanth",
     "Until 1938, the coelacanth was known only from fossils, and scientists believed it had died out around the same time as the dinosaurs. Then, in December of that year, a fishing boat off the coast of South Africa brought up a strange, large blue fish. A local museum curator, Marjorie Courtenay-Latimer, recognised that it was unusual and contacted a scientist, who identified it as a living coelacanth. The discovery caused a sensation. The fish has thick, fleshy fins that move in a pattern resembling the legs of land animals, which makes it important for understanding how vertebrates moved onto land. A second species was found in Indonesia in 1997. The coelacanth is often called a living fossil, but scientists point out that the term is misleading, because modern coelacanths are not identical to their ancient relatives.",
     "Which TWO statements about the coelacanth are made?",
     ["It was known from fossils before a living one was found", "A second species was later found in Indonesia"],
     ["It was first discovered by deep-sea divers", "It has not changed at all for millions of years", "It lives mainly in freshwater lakes"],
     "It was known only as a fossil until 1938, and a second species appeared in 1997."),
    ("Squid of the deep",
     "For centuries, sailors told stories of enormous sea monsters with long arms, and the giant squid may lie behind some of these legends. Dead specimens occasionally washed ashore, showing that the animals could grow to well over ten metres including their tentacles, but no one had seen one alive in the deep ocean. The first photographs of a living giant squid in its natural habitat were taken by Japanese researchers in 2004. In 2012, a team finally filmed one in the deep sea. Their success depended on being quiet and subtle: instead of bright lights and noisy vehicles, they used a camera with dim red light and a lure that imitated the glow of a jellyfish in distress, which may attract predators. Giant squid also have some of the largest eyes in the animal kingdom, about the size of a dinner plate.",
     "Which TWO statements about the giant squid are correct?",
     ["It was first photographed alive in its habitat in 2004", "A lure imitating a glowing jellyfish helped attract it"],
     ["It was captured and kept in an aquarium", "Its eyes are among the smallest of any squid", "It was filmed from a noisy vehicle with bright lights"],
     "Photographs came in 2004, and a quiet camera with a jellyfish-like lure filmed it later."),
    ("The narwhal's tusk",
     "The narwhal is a medium-sized whale that lives in the Arctic Ocean, and it is best known for the long spiral tusk that grows from the heads of most males. The tusk is in fact a tooth, which can grow to around three metres in length. In medieval Europe, narwhal tusks were brought back by traders and sold as the horns of unicorns, fetching extraordinary prices because they were believed to have magical powers. The true purpose of the tusk has long been debated. It contains millions of nerve endings, leading some scientists to suggest it can sense changes in the water around it. Others believe it plays a role in competition between males, who may display their tusks to attract females. In 2017, drone footage even showed narwhals using their tusks to tap and stun small fish before eating them.",
     "Which TWO statements are made about narwhal tusks?",
     ["The tusk is actually a very long tooth", "Tusks were once sold in Europe as unicorn horns"],
     ["Only female narwhals have tusks", "Scientists agree the tusk is used only for fighting", "Narwhals live mainly in tropical waters"],
     "The tusk is a tooth, and medieval traders sold tusks as unicorn horns."),
    ("Built for speed",
     "The cheetah is the fastest land animal, capable of reaching around one hundred kilometres an hour in a few seconds. Its body is built for speed: it has a light frame, long legs and an unusually flexible spine that stretches and bends with each stride, lengthening its step. Unlike most cats, it cannot fully retract its claws, which grip the ground like the spikes on a sprinter's shoes. Its long tail acts as a counterbalance, helping it change direction sharply when chasing prey. However, speed has costs. A chase usually lasts less than a minute, because the cheetah quickly becomes exhausted and overheated. After a successful hunt, it often needs to rest before eating, and during this time larger predators such as lions and hyenas may steal its kill. As a result, cheetahs lose a significant share of the food they catch.",
     "Which THREE statements about cheetahs are correct?",
     ["Its tail helps it balance during sharp turns", "Its claws grip the ground like running spikes", "It often loses its prey to larger predators"],
     ["It can keep its top speed for several kilometres", "Its claws retract fully like a house cat's", "It hunts mainly at night in dense forest"],
     "The tail balances turns, the claws grip like spikes, and lions or hyenas often steal kills."),
    ("How kangaroos hop",
     "Hopping looks like a tiring way to travel, but for large kangaroos it is remarkably efficient. When a kangaroo lands, the long tendons in its hind legs stretch and store elastic energy, rather like springs. This energy is released in the next jump, so the muscles do not have to do all the work. Studies in the 1970s found that, above a certain speed, a hopping kangaroo uses hardly any extra energy as it goes faster. This is very different from animals that run on four legs, which use more and more energy as their speed increases. At slow speeds, however, hopping is less practical. When feeding, kangaroos move in a slower way, using their powerful tail as a kind of fifth leg, supporting their weight while they swing their hind legs forward. Their body shape also makes it very difficult for them to move backwards.",
     "Which TWO statements about kangaroos are made?",
     ["Going faster costs them hardly any extra energy above a certain speed", "At slow speeds they use their tail like an extra leg"],
     ["They escape danger by walking backwards", "Their muscles do all the work without help from tendons", "Hopping uses more energy than running on four legs"],
     "Stored tendon energy makes fast hopping cheap, and the tail acts as a fifth leg when slow."),
    ("Homing pigeons",
     "Homing pigeons can return to their lofts from places hundreds of kilometres away, even if they have never visited them before. How they do this is still not fully understood. Experiments suggest that they use several different cues. On sunny days, pigeons can use the position of the sun as a compass, adjusting for the time of day with an internal clock. When the sky is overcast, they still manage to navigate, and many researchers believe they can sense the Earth's magnetic field. Some Italian studies found that pigeons with an impaired sense of smell struggled to find their way, suggesting that odours carried by the wind may form part of a map. Close to home, familiar landmarks become important. Tracking studies have even shown pigeons following motorways and turning at major junctions, much as a human driver would.",
     "Which TWO methods of navigation does the speaker mention?",
     ["Using the position of the sun", "Following roads and familiar landmarks near home"],
     ["Following the calls of other birds", "Relying only on their sense of hearing", "Waiting for clear skies before flying"],
     "The sun compass and familiar landmarks, including motorways, are both described."),
    ("Dogs that detect disease",
     "A dog's sense of smell is far more sensitive than ours, and researchers have been investigating whether dogs can detect diseases by their odour. Many illnesses change the chemical compounds our bodies release, sometimes in tiny amounts. Trained dogs have been used to alert people with diabetes when their blood sugar falls to dangerous levels, and studies have tested dogs' ability to identify certain cancers and infections from samples of breath, urine or clothing. Some results have been impressive, but there are practical challenges. Training a detection dog takes time and money, dogs can become tired or distracted, and individual dogs perform differently. For these reasons, many scientists see the dogs not as a replacement for medical tests, but as a guide. By identifying the chemicals the dogs are responding to, researchers hope to design electronic devices that can detect them in the same way.",
     "Which TWO statements are made in the recording?",
     ["Dogs have been trained to detect low blood sugar", "Researchers hope to build devices that copy dogs' abilities"],
     ["Most hospitals already use dogs to diagnose cancer", "All dogs perform equally well after training", "Training detection dogs is quick and cheap"],
     "Dogs alert people with diabetes, and scientists want electronic devices that detect the same chemicals."),
    ("Wildcats and grain stores",
     "Unlike dogs, which people may have actively tamed, cats seem to have largely domesticated themselves. Genetic studies suggest the process began around ten thousand years ago in the Near East, when people started farming and storing grain. The stores attracted mice and rats, and these in turn attracted wildcats. Cats that were less fearful of people could take advantage of this new source of food, and farmers had good reason to tolerate them. Some of the earliest evidence of a close bond comes from a grave on the island of Cyprus, around nine and a half thousand years old, where a person was buried with a cat. Ancient Egypt later played an important role in spreading tame cats and celebrating them in art. Even today, domestic cats remain genetically quite similar to their wild relatives, and many can still survive perfectly well without human help.",
     "Which TWO statements about the domestication of cats are correct?",
     ["Stored grain attracted mice, which drew wildcats to settlements", "Domestic cats remain genetically similar to wildcats"],
     ["Cats were first domesticated in ancient Egypt", "People captured wildcats to guard their homes", "The oldest evidence comes from a burial in China"],
     "Grain stores drew rodents and then wildcats, and domestic cats are still close to wild ones."),
    ("Vampire bat cooperation",
     "Vampire bats feed only on blood, and their lives are finely balanced. A bat that fails to find a meal for two or three nights in a row is at serious risk of starving. On any given night, some bats return to the roost hungry. Researchers have observed that well-fed bats often regurgitate some of their meal to feed these hungry companions. This sharing is not limited to close relatives. Long-term studies have found that bats are more likely to share with individuals that have shared with them in the past, a pattern that looks like a system of mutual help. In experiments, bats that had built up a wider network of sharing partners were better protected when one partner was unavailable. The findings make vampire bats an important example for scientists studying how cooperation develops among animals that are not related.",
     "Which TWO statements are supported by the recording?",
     ["A bat that fails to feed for a few nights may starve", "Bats are more likely to share with those that shared with them"],
     ["Vampire bats feed mainly on fruit", "Only closely related bats share food", "Sharing food weakens a bat's ability to hunt"],
     "Missing a few meals is dangerous, and sharing follows past help."),
    ("Bees and static charge",
     "As a bumblebee flies, friction with the air gives its body a small positive electric charge. Flowers, meanwhile, tend to carry a slight negative charge. When a bee lands on a flower, some of the charge is transferred, and the electric field around the flower changes for a short time. In 2013, researchers in Britain showed that bumblebees can detect these electric fields and learn to use them. In experiments with artificial flowers, bees learned to tell rewarding flowers from unrewarding ones using electric fields alone. Later work suggested that the bees sense the fields through tiny hairs on their bodies, which move in response. This could help a bee avoid wasting time on a flower whose nectar has just been taken by another insect. It is a reminder that animals may perceive the world through senses we are only beginning to understand.",
     "Which TWO statements are made about bumblebees?",
     ["They carry a different charge from flowers", "They may sense whether a flower has just been visited"],
     ["They produce electricity to attract mates", "Flowers give them electric shocks to keep them away", "They sense electric fields through their eyes"],
     "Bees are positively charged and flowers negatively, and a recent visit changes the field."),
    ("Clownfish and anemones",
     "Clownfish live among the tentacles of sea anemones, which are covered in stinging cells that can paralyse other small fish. Clownfish are protected by a layer of mucus on their skin, which appears to stop the anemone from firing its stinging cells. The relationship benefits both animals. The anemone provides the clownfish with shelter from predators, while the clownfish chases away fish that might eat the anemone, and its waste may provide the anemone with nutrients. Clownfish also have an unusual social structure. Each anemone is usually home to a group led by a single breeding female, the largest fish, and a breeding male. All clownfish are born male. If the female dies, the breeding male changes sex and becomes female, and the next largest fish takes his place. This detail of their biology would change the story of a famous animated film considerably.",
     "Which THREE statements about clownfish are correct?",
     ["A coating of mucus protects them from stings", "They chase away fish that would eat the anemone", "A breeding male can change into a female"],
     ["They feed on the anemone's tentacles", "The anemone gains nothing from the relationship", "All clownfish are born female"],
     "Mucus protects them, they defend the anemone, and the male becomes female if she dies."),
    ("Figs and their wasps",
     "A fig is not really a fruit in the usual sense. It is a hollow structure lined on the inside with hundreds of tiny flowers, hidden from view. This creates a problem: how can the flowers be pollinated? The answer is a remarkable partnership with tiny insects called fig wasps. A female wasp, carrying pollen, squeezes through a narrow opening into the fig, often losing her wings in the process. Inside, she pollinates the flowers and lays her eggs, and then she dies. Her offspring develop inside the fig, and new females leave carrying pollen to another fig. Many fig species rely on their own particular species of wasp, and neither could reproduce without the other. Because fig trees produce fruit throughout the year, they are an essential source of food for many birds, bats and monkeys in tropical forests.",
     "Which TWO statements about figs are made?",
     ["Their flowers are hidden inside them", "Many fig species depend on their own species of wasp"],
     ["Fig wasps are pests that destroy the fruit", "The wasps enter figs to hide from predators", "Figs are rarely eaten by wild animals"],
     "The flowers line the inside of the fig, and fig and wasp species depend on each other."),
    ("Orchids that deceive",
     "Most flowering plants offer pollinators a reward, such as nectar or pollen, in exchange for carrying pollen from one flower to another. A surprising number of orchids, however, offer nothing at all. Estimates suggest that around a third of orchid species attract insects through deception. Some produce bright colours and shapes that resemble nectar-rich flowers, even though they contain no nectar. Others are even more elaborate. Certain orchids produce a scent that closely imitates the chemical signals released by female insects, and their flowers may even look like the female. Male insects are attracted, try to mate with the flower, and pick up pollen, which they then carry to the next orchid that deceives them. The strategy works because the insects are deceived only occasionally, but it does mean that such orchids often depend on a single species of insect for their survival.",
     "Which TWO statements about orchids are correct?",
     ["Some offer insects no reward at all", "Some imitate the scent of female insects"],
     ["They produce more nectar than any other flowers", "They are pollinated mainly by the wind", "Deceptive orchids attract many different insect species"],
     "About a third deceive their pollinators, some by imitating female insects."),
    ("Sunflowers and the sun",
     "Young sunflowers really do follow the sun. During the day, the growing plants gradually turn from east to west, and at night they swing back to face east, ready for sunrise. Research published in 2016 showed that this movement is controlled partly by the plant's internal clock, which allows it to anticipate the sun's position rather than simply react to it. The turning is produced by the stem growing faster on one side than on the other. Once the plants mature and their flowers open, they stop moving and most end up facing east. The researchers found that this has an advantage. East-facing flowers warm up more quickly in the morning sun, and warm flowers attract more visits from bees and other pollinators than flowers that face west. So the direction a sunflower faces may have a direct effect on its success in producing seeds.",
     "Which TWO findings does the speaker report?",
     ["Young plants turn back towards the east at night", "East-facing mature flowers attract more bees"],
     ["Mature flower heads follow the sun all day", "Sunflowers turn only in response to rainfall", "West-facing plants produced the most seeds"],
     "Young plants reset overnight, and warm east-facing flowers get more pollinator visits."),
    ("The baobab tree",
     "The baobab tree, found across the dry savannahs of Africa, is famous for its enormous, swollen trunk. The trunk stores large quantities of water, which helps the tree survive long dry seasons, and it may lose its leaves for much of the year to reduce water loss. Baobabs can live for well over a thousand years, and some hollow trunks have been used by people as shelters and storage rooms. The trees are also valuable for food: the fruit contains a dry pulp that is rich in vitamin C. In 2018, researchers who had been dating the oldest baobabs reported that several of the largest and most ancient trees had died or lost their oldest parts within the previous decade. They suggested that changes in climate might be involved, but they stressed that more research was needed to be sure.",
     "Which TWO statements about baobabs are made?",
     ["Their trunks can store large amounts of water", "Several of the oldest trees have recently died"],
     ["They grow mainly in cold mountain regions", "Their fruit contains no vitamins", "Scientists know exactly why the old trees died"],
     "The trunk stores water, and many of the oldest trees died within a decade."),
    ("How dandelion seeds fly",
     "Each dandelion seed hangs beneath a tiny parachute made of around one hundred fine bristles. Surprisingly, this parachute is mostly empty space, yet it keeps the seed airborne so effectively that seeds can travel long distances on the wind. In 2018, researchers in Scotland used wind tunnels to discover how it works. They found that as air flows through the gaps between the bristles, it forms a stable ring of swirling air that sits just above the parachute without being carried away. This ring lowers the pressure above the seed and helps slow its fall. The researchers calculated that the bristle structure is several times more efficient, for its weight, than a solid disc of the same size would be. The discovery has interested engineers who design very small flying devices, which need to stay in the air using as little material and energy as possible.",
     "Which TWO statements are made about the dandelion's parachute?",
     ["It is mostly empty space", "A ring of swirling air above it helps it stay aloft"],
     ["It is lifted only by warm air rising from the ground", "A solid disc of the same size would work better", "Its bristles are joined by a thin skin"],
     "The open bristles create a stable swirling ring that slows the fall."),
    ("Rolling tumbleweeds",
     "In Western films, tumbleweeds rolling across an empty town have become a symbol of the American frontier. A tumbleweed is the dried upper part of certain plants that, once mature, breaks away from its roots and is blown along by the wind. As it tumbles, it scatters its seeds across a wide area, and a single large plant can release many thousands. Ironically, one of the best-known tumbleweeds in North America, the Russian thistle, is not native there. It is believed to have arrived in the late nineteenth century, mixed in with a shipment of crop seeds brought by farmers from Eastern Europe. It spread rapidly across the plains. Today tumbleweeds can be a real nuisance, piling up against fences and houses, blocking roads, and sometimes presenting a fire risk when they collect in large numbers.",
     "Which TWO statements about tumbleweeds are correct?",
     ["They scatter seeds as they roll", "One well-known species arrived in North America by accident"],
     ["They are the seeds of a single desert tree", "They move only when pushed by animals", "They are native to every continent"],
     "Rolling spreads the seeds, and the Russian thistle arrived mixed in with crop seeds."),
    ("Dwarf elephants",
     "When animals become isolated on islands, their body size often changes over many generations. Large animals frequently become smaller, a pattern known as island dwarfism. Fossils show that elephants living on several Mediterranean islands, including Sicily and Malta, evolved into dwarf forms, some only about a metre tall. Scientists think that limited food on small islands favoured smaller bodies, which need less energy, and that the absence of large predators removed one of the advantages of being big. The opposite can happen to small animals, which sometimes grow larger than their mainland relatives, a pattern called island gigantism. Examples include giant rats and lizards on certain islands. The discovery of fossils of a small human species on the Indonesian island of Flores has led some researchers to ask whether similar processes may even have affected our own relatives.",
     "Which TWO statements are supported by the recording?",
     ["Some island elephants became much smaller than their ancestors", "Small animals on islands sometimes become larger"],
     ["Islands usually provide more food than the mainland", "All island animals become smaller over time", "Dwarf elephants still live in the Mediterranean", "Large predators are common on small islands"],
     "Dwarf elephants and giant rats and lizards illustrate both patterns."),
    ("Tortoises of the Galápagos",
     "Giant tortoises once lived in huge numbers on the Galápagos Islands. Their ability to survive for many months without food or water proved disastrous for them. From the seventeenth century onwards, sailors and whalers collected thousands of tortoises and stored them alive in the holds of their ships, providing a supply of fresh meat on long voyages. Later, settlers and the animals they introduced added to the damage. Goats, in particular, ate much of the vegetation the tortoises relied on. Several species became extinct. One famous tortoise, known as Lonesome George, was the last known member of his species when he died in 2012. Conservation programmes have since removed goats from several islands and bred tortoises in captivity for release into the wild, and some populations have recovered significantly, although others remain at risk.",
     "Which THREE statements are made in the recording?",
     ["Sailors kept them alive on ships as fresh meat", "Introduced goats ate the vegetation they needed", "Lonesome George was the last known member of his species"],
     ["They were hunted mainly for their shells", "Every species has now fully recovered", "They cannot survive without drinking daily"],
     "Sailors took them as food, goats destroyed their food plants, and Lonesome George was the last of his kind."),
    ("The kiwi",
     "The kiwi, New Zealand's national bird, is unusual in many ways. It cannot fly, and its tiny wings are hidden beneath its feathers. It is mostly active at night, and unlike almost all other birds, it has nostrils at the tip of its long beak, which it uses to smell insects and worms in the soil. Perhaps most remarkably, the female lays an enormous egg compared with her body size, around a fifth of her own weight, one of the largest egg-to-body ratios of any bird. Before humans arrived, New Zealand had no land mammals except bats, so the kiwi had few predators on the ground. Today introduced animals, especially stoats, kill most chicks before they are old enough to defend themselves. Conservation programmes collect eggs from the wild, hatch them in safety, and return the young birds once they are large enough to survive.",
     "Which THREE statements about the kiwi are correct?",
     ["Its nostrils are at the tip of its beak", "The female's egg is very large compared with her body", "Introduced stoats kill many chicks"],
     ["It flies short distances at night", "It finds food mainly by sight", "It had many ground predators before humans arrived"],
     "Nostrils at the beak tip, a huge egg and chick losses to stoats are all described."),
    ("The passenger pigeon",
     "In the nineteenth century, the passenger pigeon may have been the most numerous bird in North America, with a population estimated in the billions. Observers described flocks so large that they darkened the sky for hours as they passed. Yet by 1914 the species was extinct; the last known individual, a female named Martha, died in a zoo in Cincinnati. Commercial hunting was a major cause. New technologies played a part: telegraph networks allowed hunters to learn quickly where flocks were nesting, and railways carried vast quantities of meat to city markets. The clearing of forests also removed the birds' habitat. Some scientists believe the species was especially vulnerable because it bred in enormous colonies, and when numbers fell, the remaining small groups may not have been able to breed successfully.",
     "Which THREE statements are supported by the recording?",
     ["The telegraph and railways helped hunters", "The birds may have needed large colonies to breed", "The last known bird died in a zoo in 1914"],
     ["A disease was the main cause of extinction", "Small numbers still survive in remote forests", "The bird was never common in North America"],
     "Technology aided hunting, small groups may not have bred, and Martha died in 1914."),
    ("Commuting and happiness",
     "When researchers ask people to describe how they felt during different activities throughout the day, commuting regularly appears among the least enjoyable. Economists have also noticed a puzzle. People who accept a long commute should, in theory, be compensated by something else, such as a higher salary or a larger home. Yet some studies have found that people with long commutes report lower satisfaction with their lives, suggesting that many underestimate the cost of travel when choosing where to live or work. Not all commutes are equal, however. People who walk or cycle to work tend to report higher satisfaction than those who drive or use crowded public transport, perhaps because of the exercise and the predictability of the journey. The growth of working from home has given researchers new opportunities to study how the time saved is actually used.",
     "Which TWO findings does the speaker report?",
     ["Commuting is among the least enjoyable parts of many people's day", "People who walk or cycle to work tend to be more satisfied"],
     ["Long commutes are fully compensated by higher pay", "People usually overestimate how tiring travel will be", "Driving is the most enjoyable way to commute"],
     "Commuting ranks low for enjoyment, and walkers and cyclists report higher satisfaction."),
    ("Blind orchestra auditions",
     "In the 1970s and 1980s, many major orchestras in the United States began holding auditions behind a screen, so that the judges could hear the musician but not see them. Some orchestras even laid carpet on the stage, so that the sound of footsteps would not reveal whether a candidate was wearing high heels. During the same period, the proportion of women in these orchestras increased considerably. A widely cited study published in 2000 concluded that the screens had helped women advance, and the case became a famous example of how removing information can reduce bias. In recent years, some researchers have argued that the statistical evidence in the study was weaker than often claimed. Even so, the idea behind blind auditions has influenced recruitment in other fields, such as removing names from job applications during the first stage of selection.",
     "Which TWO statements are made in the recording?",
     ["Screens hid the musicians' identity from the judges", "Some researchers have questioned the strength of the study's evidence"],
     ["Screens were introduced to improve the sound", "Orchestras stopped using screens after the study", "Only female musicians auditioned behind screens"],
     "Judges could hear but not see candidates, and the 2000 study has been criticised."),
    ("Better job interviews",
     "Job interviews are one of the most common ways of choosing employees, yet research suggests that traditional interviews are surprisingly poor at predicting how well someone will perform in a job. In an unstructured interview, the conversation can go in any direction, and interviewers often form a strong impression within the first few minutes, sometimes based on factors such as confidence or shared interests that have little to do with the job. Decades of studies have found that structured interviews work considerably better. In a structured interview, every candidate is asked the same questions, which are based on the skills the job requires, and answers are scored using agreed criteria. Some organisations combine this with work sample tests, in which candidates complete a task similar to the real job. These methods do not remove human judgement, but they help to make it fairer and more consistent.",
     "Which TWO statements about interviews are supported?",
     ["Asking every candidate the same questions improves predictions", "Interviewers often form opinions very quickly"],
     ["Informal conversations are the most reliable method", "Work sample tests have been shown to be useless", "Structured interviews remove human judgement completely"],
     "Structured questions predict better, and impressions form in the first minutes."),
    ("The economics of presents",
     "In 1993, the economist Joel Waldfogel published a paper with a provocative title: The Deadweight Loss of Christmas. He asked students to estimate how much the givers had paid for gifts they had received and how much they would have been willing to pay for them. On average, recipients valued their gifts at noticeably less than the price the giver had paid, and the gap was largest for gifts from more distant relatives. From a purely economic point of view, giving cash would avoid this loss, since people could buy exactly what they wanted. In practice, however, many people feel that giving money is impersonal or even rude. Gift cards offer a compromise, although a proportion of them are never spent. Critics of the study also point out that it ignores sentimental value: a gift can matter because of who chose it, not only because of what it is.",
     "Which TWO points does the speaker make?",
     ["Recipients often value gifts at less than their price", "Many people feel uncomfortable giving cash"],
     ["Gift cards are always valued above their price", "Gifts from close friends were valued least", "Economists recommend giving no gifts at all"],
     "Gifts were valued below cost, yet cash is often seen as impersonal."),
    ("Getting used to good fortune",
     "A famous study published in 1978 compared people who had won large sums in a lottery with people who had not. Some time after their win, the lottery winners were not significantly happier than the comparison group, and they reported taking less pleasure in ordinary everyday activities. The study is often used to illustrate an idea called hedonic adaptation: people tend to get used to changes in their circumstances, whether positive or negative, and their happiness gradually drifts back towards its usual level. This helps explain why a pay rise or a new car may bring only temporary satisfaction. However, later research has shown that adaptation is not complete for every kind of event. Some experiences, such as long-term unemployment or the loss of a partner, can have lasting effects on well-being.",
     "Which TWO statements are supported by the recording?",
     ["People tend to adapt to major changes over time", "Some events can have lasting effects on happiness"],
     ["Lottery winners stayed much happier for the rest of their lives", "People adapt to good events but never to bad ones", "Winners enjoyed everyday activities more than before"],
     "Happiness tends to drift back after change, but some losses have lasting effects."),
    ("Handedness",
     "Around one in ten people around the world are left-handed, a proportion that appears to have been fairly stable for thousands of years, judging by evidence from ancient tools and artwork. Handedness is influenced by genes, but no single gene determines it, and environmental factors also play a part. For much of history, left-handed children were often forced to write with their right hand, and the words for left in several languages carry negative meanings. Left-handers are, however, overrepresented at the top level of some sports. In one-on-one contests such as fencing, boxing and tennis, they may have an advantage because most opponents spend their time competing against right-handers and are less familiar with the angles a left-hander creates. Some researchers have suggested that a similar advantage in fighting may help explain why left-handedness has survived throughout human evolution.",
     "Which THREE statements are made in the recording?",
     ["About one in ten people are left-handed", "Left-handed children were often forced to use their right hand", "Left-handers are overrepresented in some one-on-one sports"],
     ["Handedness is decided by a single gene", "Left-handers have an advantage only in team sports", "Left-handedness first appeared in the last century"],
     "The proportion, the history of forced switching and the sporting advantage are all mentioned."),
    ("Childhood amnesia",
     "Most adults cannot remember anything from the first three or four years of their lives, even though young children clearly form memories at the time; a two-year-old can remember a visit to the park the week before. This loss of early memories is known as childhood amnesia. Researchers have proposed several explanations. The hippocampus, a brain region important for forming long-term memories of events, is still developing in early childhood, and the rapid growth of new brain cells may disrupt older memories. Language may also play a role: memories formed before children can describe experiences in words may be harder to retrieve later. In addition, many people report early memories that are actually based on family photographs or stories they have heard, rather than on the events themselves. Studies have shown that it is surprisingly easy to create such false memories, especially of early childhood.",
     "Which TWO explanations for childhood amnesia does the speaker mention?",
     ["A brain region for event memory is still developing", "Memories formed before language may be hard to retrieve"],
     ["Young children cannot form memories at all", "Adults deliberately suppress unhappy early experiences", "Family photographs erase real memories"],
     "The developing hippocampus and the role of language are both given as explanations."),
    ("Bacteria on dropped snacks",
     "Many people follow the so-called five-second rule, believing that food dropped on the floor is safe to eat if it is picked up quickly. In 2016, researchers in the United States tested this belief. They contaminated different surfaces, including stainless steel, tiles, wood and carpet, with bacteria, and then dropped foods such as watermelon, bread and gummy sweets onto them for different lengths of time. They found that bacteria could move onto food in less than a second, so the rule is not reliable. Longer contact did lead to more contamination, however. Moisture was the most important factor: watermelon picked up the most bacteria, while the gummy sweets picked up the least. Surprisingly, carpet transferred fewer bacteria than steel or tiles, possibly because food touches less of its surface. The researchers concluded that the five-second rule is a significant oversimplification.",
     "Which THREE findings are reported?",
     ["Bacteria can move onto food in less than a second", "Moist foods picked up the most bacteria", "Longer contact led to more contamination"],
     ["Food is safe if picked up within five seconds", "Carpet transferred more bacteria than steel", "Contact time made no difference"],
     "Transfer was almost instant, moisture mattered most, and longer contact meant more bacteria."),
    ("Recognising a reflection",
     "In 1970, the psychologist Gordon Gallup developed a simple test of whether animals recognise themselves. Chimpanzees were given time to become familiar with a mirror, and then a coloured mark was placed on their faces while they were anaesthetised, in a position they could see only in the mirror. When they woke, several chimpanzees looked in the mirror and touched the mark on their own faces, suggesting they understood that the reflection showed themselves. Since then, great apes, some elephants, dolphins and magpies have been reported to pass versions of the test. Many other animals, including dogs, do not. Critics argue that the test favours species that depend heavily on vision. Dogs rely much more on smell, and researchers have designed experiments suggesting that dogs may recognise their own scent in ways similar to a mirror test.",
     "Which TWO statements about the mirror test are made?",
     ["The mark is placed where it can be seen only in a mirror", "Critics say it favours animals that rely on sight"],
     ["Dogs pass it more easily than chimpanzees", "Only humans have ever passed it", "It measures an animal's overall intelligence"],
     "The mark is visible only in the mirror, and the test may be unfair to smell-based animals."),
    ("Darwin's earthworms",
     "Charles Darwin's final book, published in 1881, was not about evolution but about earthworms, and it sold remarkably well. Darwin had studied worms for decades. He measured how quickly objects left on the surface of fields were buried as worms brought soil up from below, and he showed that worms had helped to bury ancient buildings and stones. He argued that worms were enormously important to agriculture, because by constantly swallowing and moving soil they mix it, let air and water in, and make it more fertile. Some of his experiments were charmingly unusual. He tested whether worms could hear by having his son play the bassoon to them, and by playing notes on a piano. The worms showed no reaction to the music, but when their pots were placed on top of the piano, they responded quickly to the vibrations.",
     "Which TWO statements are made about Darwin's research?",
     ["His final book was about earthworms", "Worms ignored the music but reacted to vibrations"],
     ["He concluded that worms damage farmland", "The book sold very few copies", "He found that worms could hear the piano clearly"],
     "The 1881 book was about worms, which reacted to vibrations but not to sound."),
    ("Pisa's tilt",
     "Construction of the famous bell tower in Pisa began in 1173, and it had reached only its third floor when it began to lean. The ground beneath it was soft and uneven, and one side sank more than the other. Work stopped for almost a century because of wars, and this long pause may have saved the tower, allowing the soil to compress and become stronger. When building resumed, the engineers tried to correct the tilt by making the upper floors slightly curved. By the late twentieth century, the lean had become so great that the tower was closed to the public in 1990. Engineers then carefully removed small amounts of soil from beneath the higher side, allowing it to settle and reducing the tilt without straightening it completely. The tower reopened in 2001, and experts believe it should remain stable for centuries.",
     "Which THREE statements about the tower are correct?",
     ["It began to lean while it was still being built", "Work on it stopped for almost a century", "Removing soil from one side reduced the lean"],
     ["Engineers straightened it completely", "The lean was caused by an earthquake", "It has been closed to visitors since 1990"],
     "The lean began early, construction paused, and soil removal reduced the tilt."),
]

LMCMA_ITEMS = []
for idx, (title, transcript, question, correct, wrong, why) in enumerate(LMCMA_RAW, 1):
    want = {2: "TWO", 3: "THREE"}[len(correct)]
    assert want in question, f"LMCMA {idx}: question should ask for {want}"
    texts = correct + wrong
    order = list(range(len(texts)))
    random.Random(9000 + idx).shuffle(order)
    letters = "ABCDEFG"
    options = [{"id": letters[n], "text": texts[i]} for n, i in enumerate(order)]
    keys = sorted(letters[n] for n, i in enumerate(order) if i < len(correct))
    LMCMA_ITEMS.append({
        "id": f"q-pl90-mcma-{idx:02d}",
        "type_id": "pte-listening-mcma",
        "type_name": "MCQ Multiple Answer",
        "title": title,
        "prompt": question,
        "audio_transcript": transcript,
        "prep_time_seconds": 7,
        "time_limit_seconds": 90,
        "options": options,
        "correct_answers": keys,
        "blanks": None,
        "model_answer": None,
        "explanation": "Options (" + "), (".join(keys) + f") are correct. {why}",
        "points": len(keys),
    })
