"""PTE Listening Bank 3: MCQ Single Answer (50 items)
Canonical type_id: 'pte-listening-mcsa'
Live type_name: 'MCQ Single Answer'

Each item: (title, recording, question, correct option, three wrong options, why).
Wrong options are contradicted by, or absent from, the recording. The correct option
rotates through A-D.
"""

LMCSA_RAW = [
    ("The first kidney transplant",
     "For centuries, doctors dreamed of replacing failing organs, but early attempts at transplants almost always failed. The main obstacle was the immune system, which recognises tissue from another person as foreign and attacks it, a process called rejection. In 1954, surgeons in Boston carried out the first successful long-term kidney transplant. The patient's donor was his identical twin brother. Because identical twins have almost perfectly matching tissues, the patient's immune system did not reject the new kidney, and he lived for another eight years. Transplants between people who were not identical twins remained very risky until drugs were developed to suppress the immune system. One of the most important of these was introduced in the early 1980s and greatly improved survival. Today, kidney transplants are routine operations in many countries, and the main limit is no longer surgical skill but the shortage of donated organs.",
     "Why was the 1954 transplant successful?",
     "The donor and the patient were identical twins",
     ["The patient was given drugs to suppress his immune system", "The kidney came from an animal donor", "The surgeons had removed the patient's immune system"],
     "Matching tissue between identical twins prevented rejection; the drugs came decades later."),
    ("Heating wine and milk",
     "In the 1860s, French winemakers asked the chemist Louis Pasteur why so much of their wine was turning sour. Pasteur examined samples under a microscope and found that spoilage was caused by unwanted microorganisms. He showed that heating wine gently, to a temperature well below boiling, for a short time killed most of these microbes without ruining the taste. The process became known as pasteurisation. Although it was first developed for wine and beer, its greatest impact came later, when it was applied to milk. In the nineteenth century, milk was a common source of dangerous infections, including tuberculosis, especially in growing cities. Laws requiring milk to be pasteurised helped to reduce these diseases dramatically. Today the same principle, using carefully controlled heat to make food safer while keeping its quality, is applied to juices, eggs and many other products.",
     "According to the speaker, where did pasteurisation have its greatest impact?",
     "In making milk safer to drink",
     ["In improving the flavour of wine", "In curing patients with tuberculosis", "In extending the life of fresh eggs"],
     "The speaker says its greatest impact came when it was applied to milk."),
    ("Clarence Birdseye",
     "In the 1910s, the American naturalist Clarence Birdseye spent several winters in Labrador, in northern Canada. There he watched Inuit fishers catch fish in temperatures of around minus forty degrees. The fish froze almost instantly in the icy air, and when they were cooked months later they still tasted fresh. Birdseye realised why. When food freezes slowly, large ice crystals form and damage its cells, so it becomes soft and watery when thawed. Rapid freezing produces much smaller crystals, which cause far less damage. Back in the United States, he developed machines that froze packaged food quickly between cold metal plates. His business was sold in 1929 for a very large sum, and the brand still carries his name. However, frozen food only became common in homes decades later, once household freezers and supermarket freezer cabinets were widespread.",
     "Why did the fish Birdseye saw in Labrador still taste fresh?",
     "They froze so quickly that only small ice crystals formed",
     ["The fishers preserved them with salt before freezing", "They were stored between cold metal plates", "They were cooked immediately after being caught"],
     "Rapid freezing produced small crystals that did little damage to the cells."),
    ("The story of ketchup",
     "The word ketchup probably comes from the name of a fermented fish sauce made in southern China and parts of Southeast Asia. British sailors and traders encountered it in the seventeenth century, and English cooks tried to recreate it at home, using ingredients such as mushrooms, walnuts and oysters. Tomato ketchup appeared in the United States in the early nineteenth century, but early versions often spoiled quickly, and some manufacturers added questionable chemicals to preserve them. In the early twentieth century, the company founded by Henry Heinz developed a recipe with much more vinegar and sugar, which preserved the sauce naturally without such additives. It also sold ketchup in clear glass bottles so that customers could see the product was pure. That sweeter, thicker recipe became the model for the ketchup now eaten around the world, far removed from its salty, fishy origins.",
     "Why did the Heinz company add more vinegar and sugar?",
     "To preserve the sauce without questionable additives",
     ["To make it taste like the original fish sauce", "To reduce the cost of glass bottles", "To replace the tomatoes with mushrooms"],
     "Vinegar and sugar preserved the sauce naturally, replacing doubtful chemicals."),
    ("The price of saffron",
     "Saffron is often described as the most expensive spice in the world by weight, and the reason lies in how it is harvested. It comes from a crocus flower, and each flower produces only three thin red threads, called stigmas. These must be picked by hand, usually early in the morning, because the flowers open for only a short time in autumn. Estimates suggest that well over one hundred thousand flowers are needed to produce a single kilogram of dried saffron. Machines have so far been unable to replace skilled workers, because the threads are delicate. Iran produces the great majority of the world's supply, although saffron is also grown in Spain, India and elsewhere. Because of its high price, saffron is also a common target for fraud, with some sellers mixing in dyed plant fibres or other parts of the flower.",
     "According to the speaker, why is saffron so expensive?",
     "Its threads must be picked by hand from huge numbers of flowers",
     ["It can only be grown in one country", "Most of each harvest is lost to fraud", "Its flowers open only once every few years"],
     "Each flower gives only three threads, and all must be picked by hand."),
    ("Decaffeination",
     "Decaffeinated coffee has a surprising history. In the early twentieth century, the German merchant Ludwig Roselius is said to have received a shipment of coffee beans that had been soaked in seawater during the voyage. The beans had lost much of their caffeine but still tasted of coffee. Roselius developed a commercial process, but it used benzene, a chemical later found to be harmful, and it was eventually abandoned. Today caffeine is removed from green beans before they are roasted. Some methods use solvents that bind to caffeine; others use only water, passing it through filters that capture caffeine molecules; and some use carbon dioxide under very high pressure. None of these methods removes caffeine completely. Decaffeinated coffee usually keeps a small amount, which is why people who must avoid caffeine entirely are advised to check carefully before drinking it.",
     "Which statement about modern decaffeinated coffee is correct?",
     "It still contains a small amount of caffeine",
     ["It is made from beans after they have been roasted", "It is usually processed with benzene", "It must be soaked in seawater during transport"],
     "The speaker says no method removes caffeine completely."),
    ("Ripening bananas",
     "Many fruits, including bananas, tomatoes and avocados, continue to ripen after they are picked. The trigger is ethylene, a simple gas that the fruit produces itself. As ethylene levels rise, starches turn into sugars, the fruit softens and its colour changes. This explains the old saying that one bad apple spoils the barrel: a damaged or overripe fruit releases ethylene, which speeds up ripening in the fruit around it. Commercial growers make use of this. Bananas are usually harvested while still hard and green, shipped in cool conditions to slow them down, and then placed in ripening rooms where a controlled amount of ethylene is added. At home, you can speed up ripening by placing an unripe fruit in a paper bag with a ripe banana, which keeps the gas close to it. Other fruits, such as grapes and strawberries, do not ripen further after picking.",
     "Why are bananas shipped in cool conditions?",
     "To slow down ripening during the journey",
     ["To stop them from producing starch", "To remove ethylene from the fruit", "To make them sweeter before sale"],
     "Cool shipping slows the fruit down until ethylene is added in ripening rooms."),
    ("Sweeteners found by accident",
     "Several artificial sweeteners were discovered by accident, often because of poor laboratory hygiene. In 1879, the chemist Constantin Fahlberg was working on coal tar compounds at a university in the United States. That evening at dinner, he noticed that his bread tasted unusually sweet. He realised the sweetness came from a chemical on his hands, which he had not washed properly, and traced it back to his laboratory. The substance was saccharin, which is hundreds of times sweeter than sugar. Decades later, a sweetener called cyclamate was found when a student put his cigarette down on a laboratory bench and then noticed a sweet taste. Another sweetener was discovered in the 1970s when a researcher reportedly misheard an instruction to test a compound as an instruction to taste it. Such practices would be considered dangerous in laboratories today.",
     "What does the speaker imply about these discoveries?",
     "They resulted from practices that would now be considered unsafe",
     ["They were the result of carefully planned experiments", "They were all made by the same research team", "They produced sweeteners weaker than sugar"],
     "The speaker ends by saying such practices would now be considered dangerous."),
    ("The MSG scare",
     "In 1968, a doctor wrote a letter to a medical journal describing symptoms such as numbness and weakness after eating at Chinese restaurants. He wondered whether monosodium glutamate, or MSG, a flavour enhancer, might be responsible. The idea spread quickly, and a name for the supposed condition entered popular language. Yet when researchers later carried out controlled studies, in which neither participants nor researchers knew who had received MSG, they did not find consistent reactions at the amounts normally found in food. Glutamate is also present naturally in foods such as tomatoes, mushrooms and aged cheese, which many people eat without concern. Some researchers argue that the rapid spread of fears about MSG reflected cultural bias against foreign food as much as scientific evidence. Food safety agencies generally regard MSG as safe, although a small number of people may be sensitive to very large doses.",
     "What did controlled studies of MSG find?",
     "No consistent reactions at the amounts normally found in food",
     ["Strong reactions in most people who ate it", "That glutamate does not occur naturally in food", "That the original letter described the wrong symptoms"],
     "Blind studies found no consistent reactions at normal amounts."),
    ("Use-by and best-before dates",
     "Many shoppers throw away food as soon as the date on the packet has passed, but not all dates mean the same thing. In many countries, a use-by date is about safety. It appears on foods that can become dangerous quickly, such as fresh meat and fish, and these foods should not be eaten after that date. A best-before date, by contrast, is about quality. After it, the food may be less crisp or flavourful, but it is usually still safe to eat if it has been stored properly. Surveys suggest that many consumers confuse the two labels, and this confusion contributes to large amounts of household food waste. For this reason, several supermarkets have removed best-before dates from fresh fruit and vegetables altogether, encouraging customers to use their own judgement about whether produce is still good.",
     "What is the main difference between the two kinds of date?",
     "One concerns safety and the other concerns quality",
     ["One is for fruit and the other is for meat", "One is set by shops and the other by governments", "One shows when to buy and the other when to cook"],
     "Use-by dates are about safety; best-before dates are about quality."),
    ("Eating insects",
     "Insects are already a normal part of the diet for an estimated two billion people, particularly in parts of Asia, Africa and Latin America. Crickets, beetle larvae and caterpillars can be rich in protein, healthy fats and minerals. Supporters argue that farming insects could be far more efficient than raising cattle. Insects are cold-blooded, so they do not use energy to keep warm, and they convert feed into body weight much more efficiently. They also need less land and water. In many Western countries, however, the main obstacle is not nutrition or cost but disgust. For this reason, companies selling insect products often grind them into flour and add them to familiar foods, such as pasta, biscuits and protein bars, where the insects cannot be seen. Whether this approach will change eating habits on a large scale remains uncertain.",
     "According to the speaker, what is the main barrier to eating insects in many Western countries?",
     "People's feelings of disgust",
     ["Their poor nutritional value", "The high cost of farming them", "A shortage of land and water"],
     "The speaker says the main obstacle is disgust, not nutrition or cost."),
    ("How soap cleans",
     "Why does soap clean so much better than water alone? Many kinds of dirt, including grease and the oils from our skin, do not mix with water, so rinsing simply slides over them. Soap molecules solve this problem because they have two different ends. One end is attracted to water, while the other avoids water and is attracted to oils and fats. When you wash your hands, the oil-loving ends attach to grease and dirt, and the molecules gather around it in tiny clusters. The water-loving ends face outwards, so the whole cluster can be rinsed away. Soap can also damage certain viruses, which are surrounded by a fatty outer layer that the soap molecules break apart. This is why health authorities recommend washing hands with soap for at least twenty seconds, giving the molecules time to work.",
     "Why can water alone not remove grease?",
     "Grease does not mix with water",
     ["Water damages the skin's natural oils", "Water is attracted to the oils in dirt", "Grease is protected by a layer of viruses"],
     "Grease and oils do not mix with water, so rinsing slides over them."),
    ("Pressure cookers",
     "At sea level, water boils at one hundred degrees Celsius. But the boiling point depends on air pressure, and as you climb higher, the pressure falls. On high mountains, water boils at a noticeably lower temperature, so food cooked in boiling water takes much longer to become tender. Climbers near the summit of Everest would find their water boiling at around seventy degrees, which is not hot enough to cook rice or lentils properly. A pressure cooker solves this problem. Its lid seals tightly, so steam cannot escape, and the pressure inside rises. Under this higher pressure, water can reach well over one hundred degrees before boiling, and food cooks much faster. The principle is old: in the seventeenth century, the French scientist Denis Papin demonstrated a steam digester that could soften even bones. Today pressure cookers are especially popular in mountain regions.",
     "Why does food take longer to cook in boiling water on high mountains?",
     "Water boils at a lower temperature there",
     ["Cooking pots lose heat faster in cold air", "The air contains too little oxygen for the fire", "The pressure inside the pot is too high"],
     "Lower air pressure lowers the boiling point, so the water is not as hot."),
    ("Shocks from door handles",
     "Most people have felt a small electric shock when touching a door handle after walking across a carpet. This is static electricity. When two materials rub together, electrons can move from one to the other, leaving one surface with a negative charge and the other with a positive charge. The charge builds up on your body until you touch a conductor, such as a metal handle, and it suddenly jumps across, producing a tiny spark. Static shocks are much more common in winter. The reason is not the cold itself but the dry air. When the air is humid, a thin layer of moisture on surfaces allows charge to leak away gradually. In dry conditions, charge builds up instead. Static electricity is usually harmless, but it can be dangerous near flammable vapours, which is why fuel stations and factories take care to prevent sparks.",
     "Why are static shocks more common in winter?",
     "The air is drier, so charge cannot leak away",
     ["Cold temperatures create more electrons", "People touch more metal objects in winter", "Carpets produce more charge when cold"],
     "The speaker says the cause is dry air, not the cold itself."),
    ("Franklin's rod",
     "In the 1750s, Benjamin Franklin set out to show that lightning was a form of electricity. In his famous kite experiment, he reportedly flew a kite during a storm and collected electric charge in a special jar, although historians still debate exactly how the experiment was carried out. Whatever the details, Franklin used his ideas to design a practical invention: the lightning rod. A pointed metal rod is fixed to the highest part of a building and connected by a thick wire to the ground. If lightning strikes, the current follows this path into the earth instead of passing through the walls and roof, where it could start a fire. Some people at the time objected, believing that lightning was a divine punishment that humans should not interfere with. Nevertheless, lightning rods spread quickly, and they are still used on tall buildings today.",
     "How does a lightning rod protect a building?",
     "It gives the current a safe path to the ground",
     ["It stops lightning from forming above the building", "It stores electric charge in a special jar", "It keeps rain away from the roof"],
     "The current follows the rod and wire into the earth instead of the building."),
    ("The blue LED",
     "Light-emitting diodes, or LEDs, have existed since the 1960s, but for decades they were used mainly as small red or green indicator lights. To produce bright white light efficiently, engineers needed a blue LED as well, and this proved extraordinarily difficult. Many large companies gave up. In the late 1980s and early 1990s, three researchers working in Japan, Isamu Akasaki, Hiroshi Amano and Shuji Nakamura, finally succeeded, using a material called gallium nitride that others had considered too hard to work with. Their breakthrough made energy-saving white LED lamps possible, as well as the bright screens in modern phones and televisions. LED lamps use a fraction of the electricity of traditional bulbs and last far longer. In 2014, the three scientists were awarded the Nobel Prize in Physics, with the committee noting that the invention would benefit the whole world.",
     "Why was the blue LED so important?",
     "It made efficient white LED lighting possible",
     ["It was the first LED ever produced", "It replaced green indicator lights in phones", "It was cheaper to make than red LEDs"],
     "White LED light needed a blue LED, which the three researchers finally made."),
    ("Why bicycles stay upright",
     "Why does a moving bicycle stay upright, while a stationary one falls over? For many years, the usual explanation was that the spinning wheels act like gyroscopes, resisting any change in their direction. Another popular idea focused on the angle of the front fork. In 2011, however, a team of engineers built an unusual experimental bicycle designed to cancel out both of these effects. Surprisingly, when pushed without a rider, it still balanced itself. The researchers concluded that stability comes from a combination of factors, including how the mass of the bicycle is distributed and how the front wheel is steered. When a bicycle starts to lean, the front wheel tends to turn in the same direction, bringing the wheels back under the frame. A rider does the same thing without thinking, steering slightly into a fall.",
     "What did the 2011 experiment show?",
     "A bicycle can balance itself without the effects once thought essential",
     ["Spinning wheels are the only reason bicycles stay upright", "Riders cannot balance a bicycle without training", "A stationary bicycle is more stable than a moving one"],
     "The experimental bicycle cancelled the gyroscope and fork effects but still balanced."),
    ("Swerving free kicks",
     "Footballers who can make the ball swerve in the air are using a principle called the Magnus effect. When a player strikes the ball off-centre, it spins as it travels. The spinning surface drags the surrounding air with it, so air on one side of the ball moves faster than air on the other. This creates a difference in pressure, and the ball is pushed sideways, curving towards the side with lower pressure. One of the most famous examples came in 1997, when the Brazilian defender Roberto Carlos scored a free kick that seemed to be heading well wide before bending sharply into the goal. The same effect explains why tennis players use topspin to make the ball dip, and engineers have even applied it to ships, using tall spinning cylinders on deck to help them move with the wind.",
     "What causes a spinning ball to curve?",
     "A difference in air pressure on opposite sides",
     ["The weight of the ball shifting as it spins", "Wind blowing across the pitch", "The surface of the ball becoming smoother"],
     "Faster air on one side creates a pressure difference that pushes the ball sideways."),
    ("Banned swimsuits",
     "At the Beijing Olympics in 2008 and the world championships a year later, swimmers broke world records at an astonishing rate. Much of the credit went to a new generation of full-body swimsuits. Some were made partly or entirely from polyurethane, a material that trapped air, increased buoyancy and squeezed the body into a more streamlined shape, reducing drag in the water. Critics argued that races were becoming contests between suit manufacturers rather than athletes, and that swimmers without the latest suits were at a disadvantage. In response, the sport's governing body introduced new rules from 2010, requiring suits to be made from textile materials and limiting how much of the body they could cover. Many records set in that period stood for years afterwards, and some commentators still describe them as difficult to compare with those set before or since.",
     "Why did the governing body change the rules in 2010?",
     "To stop swimsuit technology from deciding results",
     ["Because the suits caused injuries to swimmers", "Because the suits were too expensive for most teams", "To encourage more swimmers to break records"],
     "Critics said races were becoming contests between suit makers."),
    ("Super shoes",
     "In recent years, running shoes with a stiff carbon-fibre plate inside thick, springy foam have transformed long-distance running. Laboratory studies found that some of these shoes reduced the energy runners needed at a given pace by around four percent on average, a very large improvement at elite level. Marathon times fell sharply, and athletes wearing them set a series of records. The shoes raised a difficult question: at what point does equipment give an unfair advantage? In 2020, the sport's governing body responded not by banning the technology but by setting limits. Shoes used in road races must now have soles no thicker than forty millimetres, and they must be available for the public to buy, so that athletes cannot use secret prototypes. Some experts believe the benefit varies considerably from one runner to another.",
     "How did the governing body respond to the new shoes?",
     "By limiting sole thickness and requiring the shoes to be on sale",
     ["By banning carbon plates from all races", "By removing records set in the shoes", "By giving identical shoes to every athlete"],
     "The body set limits rather than banning the technology."),
    ("Training in thin air",
     "Many endurance athletes spend weeks training at high altitude before important competitions. At altitude, each breath contains less oxygen, and over several weeks the body responds by producing more red blood cells, which carry oxygen to the muscles. When the athletes return to lower ground, they may benefit from this extra capacity for a limited time. However, training hard at altitude is difficult, because athletes cannot run as fast in the thin air. This led to an approach known as live high, train low: athletes sleep and rest at altitude but travel down to lower areas for their most intense sessions. The success of runners who grew up in the highlands of Kenya and Ethiopia has also drawn attention to altitude, though researchers stress that many other factors, including culture and opportunity, contribute to their achievements.",
     "What is the purpose of the live high, train low approach?",
     "To gain the benefits of altitude while still training at high intensity",
     ["To avoid producing extra red blood cells", "To reduce the time athletes spend travelling", "To copy the diet of runners from Kenya"],
     "Athletes live at altitude but go lower for their hardest sessions."),
    ("Goalkeepers and penalties",
     "A study of penalty kicks in top football leagues found something surprising about goalkeepers. When a penalty is taken, goalkeepers dive to the left or right almost every time, rarely staying in the centre of the goal. Yet the data suggested that staying in the centre gave them a chance of stopping the ball that was at least as good as diving. Why, then, do they dive? The researchers proposed an explanation called action bias. If a goal is conceded while the goalkeeper stays still, it looks as though he did nothing, and he is likely to feel worse and receive more criticism. If he dives and the ball goes the other way, he at least appears to have tried. In other words, the choice may be shaped less by the best chance of saving the ball than by how the outcome will look to others.",
     "According to the researchers, why do goalkeepers usually dive?",
     "Doing nothing looks worse if a goal is conceded",
     ["Most penalties are kicked towards the corners", "Staying in the centre gives the lowest chance of a save", "Coaches punish goalkeepers who do not move"],
     "The action bias explanation: standing still looks like doing nothing."),
    ("Riding in the peloton",
     "In professional cycling races, riders travel in a large, tightly packed group called the peloton. The main reason is air resistance, which accounts for most of the effort a cyclist makes at racing speeds. A rider directly behind another experiences much less drag, and computer simulations have suggested that riders in the middle of a large peloton may face only a small fraction of the air resistance of a cyclist riding alone. This has a strong influence on tactics. Teams place riders around their leader to shelter him from the wind and save his energy for the decisive moments of the race. It also explains why small groups that break away from the peloton are so often caught before the finish: a large group sharing the work at the front can travel faster for longer than a few riders on their own.",
     "Why are breakaway groups often caught before the finish?",
     "A large group can share the work of facing the wind",
     ["Breakaway riders are usually less experienced", "Race rules require riders to stay together", "Small groups face less air resistance"],
     "The larger group shares the effort at the front and goes faster for longer."),
    ("The smell of swimming pools",
     "Many people assume that a strong smell of chlorine at a swimming pool means the water is especially clean. In fact, the opposite is often true. Chlorine is added to pools to kill harmful microorganisms, but when it reacts with substances brought in by swimmers, such as sweat, skin oils and urine, it forms compounds called chloramines. It is mainly these chloramines that produce the sharp smell and can irritate the eyes and lungs. A well-managed pool, with good ventilation and the correct balance of chemicals, should have only a faint smell. Pool operators therefore encourage swimmers to shower before entering the water, which reduces the amount of material that reacts with chlorine. So the next time your eyes sting after a swim, it may be a sign that the pool needs more attention, not less.",
     "What does a strong chlorine smell usually indicate?",
     "Chlorine has reacted with substances from swimmers",
     ["The water contains more chlorine than necessary", "The pool has just been cleaned", "The ventilation is working well"],
     "The smell comes mainly from chloramines formed with sweat, oils and urine."),
    ("Head injuries in sport",
     "For many years, players who received a blow to the head were often encouraged to carry on, and being knocked out briefly was sometimes treated as part of the game. Attitudes have changed as evidence has grown that repeated head injuries can have serious long-term effects on the brain. Many sports now have formal concussion procedures. In rugby, a player with a suspected head injury may be removed for an assessment by a doctor, and a replacement can come on while this takes place. Several football competitions now allow extra substitutions specifically for concussion, so that teams are not tempted to keep an injured player on the field to avoid being a player short. At amateur level, where doctors are rarely present, the advice is simpler: if in doubt, sit them out.",
     "Why have some football competitions introduced extra substitutions for concussion?",
     "So teams are not tempted to keep injured players on the field",
     ["To give more young players a chance to play", "Because a doctor must attend every match", "To make matches last longer"],
     "Extra substitutions remove the pressure to avoid being a player short."),
    ("reCAPTCHA",
     "You have probably been asked to type distorted letters or choose pictures of traffic lights before logging in to a website. These tests, known as CAPTCHAs, are designed to tell humans apart from automated programs. The computer scientist Luis von Ahn, one of their inventors, realised that people around the world were collectively spending an enormous amount of time solving them, and he wondered whether this effort could be put to use. His answer was reCAPTCHA. Instead of random letters, users were shown words from old books and newspapers that computers had failed to read when the pages were scanned. Each time someone typed the word correctly, they were helping to digitise printed texts. Later versions, showing photographs of street scenes, have been used to help train computer systems to recognise objects.",
     "What was the main idea behind reCAPTCHA?",
     "To use people's effort to help digitise printed texts",
     ["To make logging in faster for users", "To stop people reading old newspapers online", "To measure how quickly people can type"],
     "Users typed words from scanned books that computers could not read."),
    ("Why spam pays",
     "Why do spammers keep sending millions of unwanted emails when almost nobody responds? In 2008, a group of computer scientists studied this question by quietly taking control of part of a network used by spammers. They tracked a campaign that sent around three hundred and fifty million emails advertising medicines. Only twenty-eight people went on to make a purchase, a response rate of well under one in ten million. At first glance, this seems like a failure. But sending an email costs the spammer almost nothing, especially when the messages are sent from thousands of infected computers belonging to other people. Even a tiny number of sales can therefore produce a profit. The researchers concluded that spam is sustained by extremely low costs rather than by success in persuading people, and later research suggested targeting the banks that spammers depend on.",
     "According to the study, why does spam remain profitable?",
     "Sending messages costs almost nothing",
     ["Most people who receive it make a purchase", "Spammers are paid by advertising companies", "The emails are sent only to wealthy customers"],
     "Very low costs mean even twenty-eight sales can make a profit."),
    ("New password advice",
     "For years, organisations told users to create passwords with a mixture of capital letters, numbers and symbols, and to change them every few months. In 2017, the United States National Institute of Standards and Technology revised its widely followed guidance. It concluded that these rules often made security worse. Complicated requirements led people to choose predictable patterns, such as replacing a letter with a number, and frequent changes encouraged them to make only tiny adjustments or to write passwords down. The new advice emphasised length instead. A long passphrase made of several unrelated words can be both easier to remember and harder to guess. The guidance also recommended checking new passwords against lists of passwords already exposed in data breaches, and forcing a change only if there is evidence that a password has been compromised.",
     "What did the revised guidance emphasise?",
     "Making passwords longer rather than more complicated",
     ["Changing passwords every few months", "Replacing letters with numbers", "Writing passwords down in a safe place"],
     "The new advice emphasised length, such as long passphrases."),
    ("Website cookies",
     "A cookie is a small text file that a website stores on your device. Cookies were introduced in 1994 by a programmer working on an early web browser, who needed a way for an online shop to remember what a customer had put in their basket from one page to the next. Many cookies are still used for such practical purposes, keeping you logged in or remembering your language settings. However, so-called third-party cookies, placed by companies other than the website you are visiting, allow advertisers to follow your activity across many different sites and build a detailed profile of your interests. Concerns about privacy led the European Union to require websites to ask for consent before storing most non-essential cookies, which is why so many sites now show pop-up banners. Several browsers also block third-party cookies by default.",
     "Why were cookies first introduced?",
     "To let an online shop remember a customer's basket",
     ["To let advertisers track users across websites", "To meet European privacy laws", "To block unwanted pop-up banners"],
     "The first cookies helped a shop remember the basket between pages."),
    ("Predictive text",
     "When you type a message on a phone, the keyboard often suggests the next word before you have started it. Early mobile phones used a system called T9, which guessed which word you meant from a sequence of number key presses. Modern predictive keyboards work by calculating probabilities. They are built using enormous collections of text, from which they learn which words are most likely to follow others, and they also adapt to the words you personally use most often. This makes typing faster, but it has side effects. Autocorrect sometimes replaces an unusual but correct word, such as a name, with a more common one, occasionally with embarrassing results. Some linguists also wonder whether constant suggestions might gradually encourage people to use more predictable language, although the long-term effects are not yet clear.",
     "How do modern predictive keyboards decide which word to suggest?",
     "By calculating which words are most likely to follow others",
     ["By counting number key presses", "By checking a dictionary of correct spellings", "By asking the user to choose a language"],
     "They learn word probabilities from large collections of text."),
    ("Machine translation",
     "In 1954, researchers in the United States demonstrated a computer that translated about sixty Russian sentences into English, and some predicted that machine translation would be solved within a few years. It took far longer. Early systems relied on rules written by linguists, but human language is full of ambiguity, and rules could not cover every case. A major change came when researchers began using statistics, training systems on huge collections of documents that had already been translated by humans, such as the records of international organisations. Since the mid-2010s, systems based on neural networks have produced far more fluent results. Yet quality still varies enormously between languages. Translation between widely used languages, for which vast amounts of text exist, is often very good, while languages with little available written material remain much harder for machines.",
     "According to the speaker, why do some languages remain difficult for machine translation?",
     "Little written material exists for training systems",
     ["Their grammar has too many rules", "Linguists have not written rules for them", "They were left out of the 1954 demonstration"],
     "Systems learn from existing text, so languages with little text are harder."),
    ("Drones carrying blood",
     "In 2016, Rwanda became the first country to use drones for regular deliveries of blood to hospitals. The service was run by a company called Zipline, working with the national health system. Blood is difficult to manage in rural areas. It must be stored carefully, some types expire quickly, and patients who need it after childbirth or accidents often cannot wait. Previously, a clinic might have waited hours for a delivery by road. Using small fixed-wing drones, the company could deliver within about half an hour. The drones do not land. Instead, they fly low over the hospital and drop the package, which floats down on a small paper parachute, before returning to base. The model has since been extended to vaccines and other medical supplies, and to other countries.",
     "How are the packages delivered to hospitals?",
     "They are dropped by parachute from the drone",
     ["The drones land on hospital roofs", "They are collected by motorcycle from a base", "They are carried the last part of the way by road"],
     "The drones fly low and drop packages on paper parachutes."),
    ("Metals in e-waste",
     "Old mobile phones, laptops and other electronic devices contain small amounts of valuable metals, including gold, silver and copper. In fact, a tonne of discarded phones can contain far more gold than a tonne of ore from a typical gold mine. Recovering these metals from waste is sometimes called urban mining. A striking example came from Japan, which made all the medals for the Tokyo Olympic Games from metals extracted from electronic devices donated by the public over two years. Despite such projects, only a minority of the world's electronic waste is formally collected and recycled. Much of the rest ends up in landfill or is processed informally, sometimes by burning cables and circuit boards in the open air, which exposes workers to toxic fumes. Better design, making devices easier to take apart, could make recycling safer and more profitable.",
     "What example of urban mining does the speaker give?",
     "Olympic medals made from recycled electronics",
     ["A new gold mine opened in Japan", "Phones redesigned to contain no metal", "Landfill sites turned into mines"],
     "Japan made the Tokyo medals from metals in donated devices."),
    ("Server farms",
     "The data centres that store our emails, photographs and videos contain thousands of computer servers running day and night. These machines produce a great deal of heat, and keeping them cool can use a large share of a data centre's total energy. Companies have tried several solutions. Some have built centres in cold countries, such as Finland and Sweden, where outside air can be used for cooling for much of the year. Others use nearby seawater or lakes. In one experiment, a technology company sealed servers inside a container and placed it on the seabed off Scotland for two years; the servers failed less often than similar ones on land, perhaps because of the stable temperature and the absence of people. Increasingly, data centres are also connected to local heating networks, so that their waste heat can warm homes.",
     "What happened in the underwater experiment?",
     "The servers failed less often than similar ones on land",
     ["The servers overheated in the seawater", "The container was later moved to Finland", "The servers heated homes on the coast"],
     "The sealed servers on the seabed failed less often."),
    ("Wrist heart-rate sensors",
     "Many smartwatches and fitness bands can measure your heart rate without any needles or wires. On the underside of the device, small lights, usually green, shine into the skin of your wrist. Blood absorbs green light, so the amount of light reflected back changes slightly as blood pulses through the vessels with each heartbeat. A sensor detects these changes, and software converts them into a heart rate. The method works well when the wearer is resting, but it can become less reliable during vigorous exercise, when arm movements disturb the signal, or if the watch is worn loosely. Some studies have also found that accuracy can vary with skin tone and tattoos. For this reason, many athletes who need precise measurements still use a strap worn around the chest, which detects the heart's electrical activity directly.",
     "Why do some athletes still use chest straps?",
     "They measure the heart's electrical activity more precisely",
     ["Smartwatches cannot measure heart rate at rest", "Chest straps use green light instead of electricity", "Wrist devices damage the skin during exercise"],
     "Chest straps detect the heart's electrical signals directly."),
    ("How Wikipedia works",
     "When Wikipedia was launched in 2001, many people doubted that an encyclopedia anyone could edit would ever be reliable. Yet it grew rapidly into one of the most visited websites in the world. Its model depends on large numbers of volunteers who write articles, check sources and correct errors. Key rules require information to be supported by published sources and articles to be written from a neutral point of view. Deliberate damage, known as vandalism, is common, but it is often removed within minutes, partly by automated programs. In 2005, the journal Nature compared a selection of science articles with those in another well-known encyclopedia and reported a broadly similar number of serious errors, though the other publisher strongly disputed the study. Teachers often advise students to use Wikipedia as a starting point and to follow its references, rather than citing it directly.",
     "What advice do teachers often give about Wikipedia?",
     "Use it as a starting point and follow its references",
     ["Avoid it completely because of vandalism", "Cite it directly in academic essays", "Use it only for science topics"],
     "Teachers suggest starting there and following the references."),
    ("The War of the Worlds broadcast",
     "On the evening of 30 October 1938, an American radio station broadcast a drama based on H. G. Wells's novel The War of the Worlds, presented as a series of realistic news reports about a Martian invasion. The next day, newspapers reported that the programme had caused mass panic, with frightened listeners fleeing their homes. The story became famous as an example of the power of the media. However, later researchers have argued that the panic was greatly exaggerated. Relatively few people were listening to the programme, and there is little evidence of widespread flight. Some historians suggest that newspapers had a reason to exaggerate: radio was a new and growing competitor for advertising, and reports of irresponsible broadcasting helped to portray it as dangerous. Ironically, the myth of the panic may itself show how easily media stories spread.",
     "According to later researchers, why might newspapers have exaggerated the panic?",
     "Radio was competing with them for advertising",
     ["Most journalists had listened to the programme", "The radio station paid them for publicity", "The government wanted to ban radio dramas"],
     "Radio was a new rival for advertising, so newspapers had a motive."),
    ("The rise of podcasts",
     "The word podcast was coined in 2004 by a journalist who combined the name of a popular music player with the word broadcast. At first, podcasts were a niche interest, downloaded by relatively small numbers of enthusiasts. Growth accelerated around 2014, when a true-crime series called Serial attracted millions of listeners and showed that audio storytelling could become a mass phenomenon. Since then, the number of podcasts has grown enormously. Part of their appeal is convenience: listeners can choose exactly what they want and listen while commuting, exercising or doing housework. For producers, costs are low compared with radio or television, so it is possible to serve small, specialised audiences, from fans of medieval history to people learning a particular language. The challenge now is not making a podcast but getting anyone to notice it among so many.",
     "What does the speaker identify as the main challenge for podcast producers now?",
     "Attracting attention among so many podcasts",
     ["The high cost of recording equipment", "Finding listeners who commute", "Getting permission to use the name podcast"],
     "The speaker says the challenge is getting noticed among so many."),
    ("False stories on Twitter",
     "In 2018, researchers published a large study of how true and false news stories spread on Twitter between 2006 and 2017. They examined around one hundred and twenty-six thousand stories that had been checked by independent fact-checking organisations. False stories spread further, faster and more widely than true ones, and this was especially the case for false political news. Many people assume automated accounts, or bots, are mainly responsible, but the researchers found that bots spread true and false news at similar rates. The difference was driven by human users. One possible explanation is novelty: false stories were more often surprising, and people like to share information that seems new. The false stories also tended to provoke stronger emotional reactions, such as surprise and disgust. The findings suggest that fighting misinformation requires changing human behaviour, not just removing automated accounts.",
     "What did the study find about bots?",
     "They spread true and false stories at similar rates",
     ["They were responsible for most false news", "They mainly shared political stories", "They were removed by fact-checking organisations"],
     "The difference in spread came from human users, not bots."),
    ("Altered photographs",
     "Many people think that faked photographs are a product of the digital age, but images have been altered almost since photography began. One of the best-known examples comes from the Soviet Union in the 1930s. When officials fell out of favour with Joseph Stalin, they were sometimes removed from official photographs, so that it appeared they had never been present. In one famous case, a senior police official who had been photographed walking beside Stalin simply vanished from later versions of the picture. These changes were made by hand in darkrooms, using techniques such as painting over prints and cutting negatives. Digital software has made alteration much easier, which is why many news agencies now have strict rules forbidding any change to the content of a news photograph beyond basic adjustments such as brightness.",
     "What does the speaker say about news agencies today?",
     "Many forbid changing the content of news photographs",
     ["They use darkroom techniques to check images", "They allow officials to be removed from pictures", "They no longer publish photographs of politicians"],
     "Agencies allow only basic adjustments such as brightness."),
    ("Recorded laughter on television",
     "For decades, television comedies were often accompanied by recorded laughter, known as a laugh track. In the 1950s, a sound engineer named Charles Douglass built a machine containing recordings of different kinds of laughter, from gentle chuckles to loud roars, which he could play at chosen moments. Producers used it to add laughter to shows filmed without an audience, or to boost reactions that seemed too quiet. Many viewers found laugh tracks irritating, yet there was a reason they persisted. Research suggests that laughter is contagious: people tend to laugh more, and rate jokes as funnier, when they hear others laughing. Television producers were, in effect, providing a virtual audience for people watching alone at home. In recent years, many popular comedies have abandoned laugh tracks, trusting viewers to decide for themselves what is funny.",
     "Why did laugh tracks remain in use for so long?",
     "Hearing laughter makes people find jokes funnier",
     ["Viewers asked producers to include them", "Live audiences were not allowed in studios", "They were cheaper than writing new jokes"],
     "Laughter is contagious, so the track made shows seem funnier."),
    ("Trailers",
     "The short advertisements for upcoming films are called trailers, which seems strange, because today they are shown before the main feature. The name comes from the early days of cinema, when these advertisements were shown after the film had finished, trailing behind it. Cinema owners soon noticed that many people left as soon as the main film ended, so the trailers were moved to the beginning of the programme, where the audience was certain to see them. The name, however, remained. Trailers have since become an art form of their own. Editors must attract attention in two or three minutes without revealing too much of the story, and studios often test several versions with audiences before choosing one. With the rise of online video, the release of a trailer for a major film has become a news event in itself.",
     "Why were trailers moved to the beginning of the programme?",
     "Many viewers left as soon as the film ended",
     ["Audiences complained that they revealed the ending", "Films became too long to include them afterwards", "Online video made them more popular"],
     "Audiences left when the main film finished, so trailers were moved."),
    ("Competitive gaming",
     "Competitive video gaming, known as esports, has grown from small gatherings of enthusiasts into a global industry. Major tournaments now fill large arenas, and millions more watch online. Professional players often train for many hours a day, practising strategies with their teams and studying opponents, much like athletes in traditional sports. Whether esports should count as sport remains a subject of debate. Critics argue that they lack the physical effort that defines sport, while supporters point to the fast reactions, precise hand movements and intense concentration they demand. The question gained new attention when esports were included as official medal events at the Asian Games held in China in 2023. Despite the attention, careers can be very short. Many professional players retire in their mid-twenties, partly because of the pressure of constant competition and the physical strain of long hours of practice.",
     "What does the speaker say about esports careers?",
     "They are often very short",
     ["They usually last longer than careers in traditional sports", "They depend mainly on physical strength", "They usually begin after university"],
     "Many players retire in their mid-twenties."),
    ("The Jazz Singer",
     "In 1927, the film The Jazz Singer included sequences of synchronised speech and song, and audiences were amazed to hear an actor speak on screen. Within a few years, silent films had almost disappeared. The change transformed the industry in ways that went beyond sound itself. Some famous silent stars found their careers in difficulty, because their voices or accents did not suit the roles they were known for, or because they struggled with dialogue. Early sound equipment also created technical problems: noisy cameras had to be placed inside soundproof booths, which made filming less flexible for a time. Another group lost out as well. Many cinemas had employed musicians to play live accompaniment for silent films, and thousands of these jobs vanished as recorded soundtracks took over.",
     "According to the speaker, which group lost their jobs because of sound films?",
     "Musicians who played in cinemas",
     ["Camera operators in film studios", "Writers of silent film scripts", "Engineers who built sound equipment"],
     "Live accompaniment was replaced by recorded soundtracks."),
    ("Inventing the piano",
     "Before the piano, the most common keyboard instrument in European homes and courts was the harpsichord. When a harpsichord key is pressed, a small mechanism plucks the string, and the volume is much the same however hard the key is struck. Around the year 1700, Bartolomeo Cristofori, an instrument maker in Florence, developed a new mechanism in which small hammers struck the strings and then immediately fell back, allowing them to vibrate. Crucially, the harder the player pressed the key, the louder the sound. His instrument was described as a harpsichord with soft and loud, which in Italian included the words piano and forte. The name was eventually shortened to piano. The new instrument took decades to become popular, but composers such as Mozart and Beethoven later wrote music that depended on its range of expression.",
     "What was the key advantage of Cristofori's instrument?",
     "Players could control how loud each note was",
     ["It was much cheaper than a harpsichord", "Its strings were plucked more gently", "It could easily be carried between rooms"],
     "The harder the key was pressed, the louder the sound."),
    ("Tuning an orchestra",
     "Before a concert, an orchestra tunes to a single note played by the oboe. There are practical reasons for this. The oboe has a clear, penetrating sound that can be heard across the whole orchestra, and its pitch is relatively stable. The note chosen is usually an A. For much of history, the exact pitch of this A varied considerably from place to place, so an instrument tuned in one city might sound out of tune in another. In the twentieth century, a standard was widely adopted in which the A vibrates four hundred and forty times per second. Even so, the standard is not followed everywhere. Many orchestras tune slightly higher, believing it gives a brighter sound, while groups performing music from earlier centuries often tune lower to recreate the pitch the composers would have known.",
     "Why do orchestras tune to the oboe?",
     "Its sound is clear and its pitch is stable",
     ["It is the loudest instrument in the orchestra", "It can easily change pitch to match others", "It plays the lowest note in the orchestra"],
     "The oboe's clear sound carries and its pitch is stable."),
    ("Ultramarine blue",
     "In Renaissance Europe, the most precious blue pigment was ultramarine. Its name means beyond the sea, because the stone it was made from, lapis lazuli, came from mines in what is now Afghanistan, thousands of kilometres away. Turning the stone into a pure, intense blue was a slow and difficult process: it had to be ground and repeatedly washed to separate the blue particles from impurities. The finished pigment could be more expensive than gold, and contracts for paintings sometimes specified exactly how much ultramarine an artist was to use. Painters often reserved it for the most important figures, such as the robes of the Virgin Mary. In the 1820s, a French society offered a prize for a synthetic version, and a manufacturing method was soon found. Artificial ultramarine was far cheaper, and the colour became available to everyone.",
     "Why did contracts sometimes specify how much ultramarine an artist should use?",
     "The pigment was extremely expensive",
     ["It faded quickly if too much was used", "It was reserved by law for religious paintings", "Artists preferred the cheaper synthetic blue"],
     "Ultramarine could cost more than gold."),
    ("The Vermeer forger",
     "After the Second World War, Dutch authorities discovered that a painting believed to be by Johannes Vermeer had been sold to the senior Nazi Hermann Göring. They traced the sale to a painter named Han van Meegeren and arrested him for selling a national treasure to the enemy, a serious crime. Van Meegeren's defence was astonishing. He claimed that the painting was not a Vermeer at all, but a forgery he had painted himself. To prove it, he painted another work in the style of Vermeer in front of witnesses. He was cleared of the more serious charge but convicted of forgery. Experts were embarrassed, because several of his paintings had been accepted as genuine and displayed in major museums. His case is often cited as a warning that experts can be misled when a discovery confirms what they hope to find.",
     "Why did Van Meegeren admit to forgery?",
     "To avoid a more serious charge",
     ["To earn money from museums", "Because experts had already exposed him", "To protect Vermeer's reputation"],
     "Admitting forgery cleared him of selling a national treasure to the enemy."),
    ("Cinderella around the world",
     "The story of Cinderella is often associated with a single famous version, but folklorists have recorded hundreds of related tales from around the world. One of the oldest written versions comes from China, in a collection from the ninth century, in which a young woman named Ye Xian is helped by a magical fish and loses a golden shoe. An even earlier story, recorded by a Greek writer, tells of a woman whose sandal is carried off by an eagle and dropped in front of a king. Many details that people now consider essential, such as the fairy godmother, the pumpkin and the glass slipper, come from a French version published in 1697. By comparing such variations, folklorists try to understand how stories travel between cultures and which elements survive as they are retold.",
     "What does the speaker say about the glass slipper?",
     "It comes from a French version published in 1697",
     ["It appears in the oldest Chinese version", "It was carried off by an eagle", "It is found in every version of the story"],
     "The slipper, godmother and pumpkin come from the 1697 French version."),
    ("Shakespeare's vocabulary",
     "William Shakespeare is often credited with inventing a remarkable number of English words and expressions. Dictionaries have long listed his plays as the earliest known source for many terms, and phrases such as wild-goose chase are first recorded in his work. However, recent research using large digital collections of early printed books has complicated this picture. Scholars searching these collections have found that many words once credited to Shakespeare were in fact used by other writers before him. Because his works were studied so carefully, they were simply the first place dictionary makers looked. This does not mean his influence was small. He clearly created some words and gave new life to many others, but it suggests that the language of his time was more inventive than a focus on one writer might suggest.",
     "What have digital collections of early books revealed?",
     "Many words credited to Shakespeare were used earlier by others",
     ["Shakespeare invented more words than previously thought", "Dictionary makers ignored Shakespeare's plays", "Shakespeare never used the phrase wild-goose chase"],
     "Searches found earlier uses of many supposed Shakespeare coinages."),
]

LMCSA_ITEMS = []
for idx, (title, transcript, question, correct, wrong, why) in enumerate(LMCSA_RAW, 1):
    assert len(wrong) == 3, f"LMCSA {idx}: need three wrong options"
    slot = (idx - 1) % 4
    texts = wrong[:slot] + [correct] + wrong[slot:]
    letters = "ABCD"
    LMCSA_ITEMS.append({
        "id": f"q-pl90-mcsa-{idx:02d}",
        "type_id": "pte-listening-mcsa",
        "type_name": "MCQ Single Answer",
        "title": title,
        "prompt": question,
        "audio_transcript": transcript,
        "prep_time_seconds": 5,
        "time_limit_seconds": 90,
        "options": [{"id": letters[n], "text": t} for n, t in enumerate(texts)],
        "correct_answers": [letters[slot]],
        "blanks": None,
        "model_answer": None,
        "explanation": f"Option ({letters[slot]}) is correct. {why}",
        "points": 1,
    })
