"""PTE Listening Bank 3: Select Missing Word (50 items)
Canonical type_id: 'pte-select-missing-word'
Live type_name: 'Select Missing Word'

Each item: (title, recording up to the beep, correct ending, three wrong endings, why).
Wrong endings fit the grammar of the sentence but contradict what the speaker said.
The correct option rotates through A-D.
"""

SMW_RAW = [
    ("Unfinished tasks",
     "In the 1920s, the psychologist Bluma Zeigarnik noticed that waiters could remember complicated orders until the bill was paid, and then quickly forgot them. Her experiments suggested that people remember interrupted tasks better than completed ones. In other words, an unfinished task tends to stay",
     "on our minds", ["easy to ignore", "in the past", "forgotten quickly"],
     "Interrupted tasks are remembered better, so they stay on our minds."),
    ("Liking the familiar",
     "Studies by the psychologist Robert Zajonc found that people rated unfamiliar shapes, words and faces more positively after seeing them several times, even when they could not remember seeing them before. This is known as the mere exposure effect: simple familiarity tends to increase our",
     "liking for something", ["fear of something", "boredom with it", "memory of the source"],
     "Repeated exposure made people rate things more positively."),
    ("Missing a swap",
     "In a well-known experiment, a researcher asked a stranger for directions. While they talked, two people carrying a door walked between them, and the researcher was replaced by a different person. About half of the strangers did not notice the switch. The study shows that we often fail to detect large changes when our attention is",
     "focused elsewhere", ["free to wander", "completely undivided", "on the person's face"],
     "People missed the change because their attention was on the directions."),
    ("The cost of interruptions",
     "Research on office workers has found that after being interrupted, people can take a considerable time to return fully to what they were doing. Constant notifications from email and messaging apps therefore cost more than the few seconds needed to read them. For this reason, some experts recommend checking messages only at set times of day, so that people can spend longer periods",
     "working without interruption",
     ["answering every message", "sitting in meetings", "reading notifications"],
     "Checking messages at set times protects long periods of uninterrupted work."),
    ("Halo judgements",
     "The halo effect occurs when one positive quality, such as physical attractiveness, influences our judgement of a person's other qualities. In studies, people rated as attractive were also assumed to be more intelligent and more honest, even though there was no evidence for this. Our first impression can therefore spread to",
     "unrelated characteristics", ["no other judgement", "only their appearance", "people we have never met"],
     "One positive quality colours judgements of other, unrelated qualities."),
    ("Crossing buttons",
     "In many cities, some of the buttons that pedestrians press at crossings do not actually change the timing of the lights, especially at busy times when signals are controlled by a central computer. Even so, the buttons are often left in place. Pressing one gives people a sense of control, and researchers suggest this may make them more willing to",
     "wait for the green signal",
     ["cross against the red light", "complain to the council", "walk a different way home"],
     "A sense of control makes waiting easier, not crossing early."),
    ("Pulling on a rope",
     "In the nineteenth century, the engineer Max Ringelmann found that when people pulled on a rope in a group, each person pulled less hard than when pulling alone. Later researchers called this social loafing. It is reduced when each person's contribution can be measured separately, because people work harder when their efforts are",
     "individually visible", ["shared equally", "hidden from others", "not recorded"],
     "Loafing falls when each person's effort can be measured, so visible effort is the key."),
    ("An embarrassing T-shirt",
     "In one study, students were asked to wear an embarrassing T-shirt into a room full of classmates. They guessed that about half of the people present would notice it, but in reality only around a quarter did. Psychologists call this the spotlight effect: we tend to overestimate how much other people",
     "notice about us", ["care about fashion", "remember their own clothes", "trust our judgement"],
     "Students expected far more people to notice them than actually did."),
    ("Survival or mortality",
     "Doctors and patients can make different choices depending on how information is presented. In one classic study, more people chose a surgical treatment when told it had a ninety percent survival rate than when told it had a ten percent mortality rate. The facts were identical; only the",
     "wording had changed", ["risks had increased", "patients were different", "treatment was cheaper"],
     "Both descriptions give the same facts in different words."),
    ("Knowing it all along",
     "After an event has happened, people often feel that they knew the outcome all along. Election results, sporting upsets and financial crises all seem obvious once we know how they turned out. This tendency, called hindsight bias, can make us overconfident, because it makes the past seem much more",
     "predictable than it really was", ["confusing than the present", "distant than it is", "exciting than it was"],
     "Hindsight makes outcomes feel obvious, that is, more predictable."),
    ("Workers under observation",
     "In the 1920s and 1930s, researchers at the Hawthorne factory near Chicago studied how changes in lighting affected workers' productivity. Output seemed to rise whatever the researchers changed. One popular interpretation is that the workers performed better simply because they knew they were being",
     "observed", ["paid more", "replaced", "ignored"],
     "Output rose whatever changed, which was put down to the attention of being studied."),
    ("Naming the ink colour",
     "In the Stroop test, people are shown colour words, such as red, printed in a different ink, such as blue, and asked to name the ink colour. Most people are noticeably slower when the word and the colour do not match. This happens because, for fluent readers, reading a word is so automatic that it is difficult to",
     "ignore", ["pronounce", "see", "remember"],
     "Automatic reading interferes with naming the colour, so the word is hard to ignore."),
    ("Grouping information",
     "Most people can hold only a small number of separate items in short-term memory at once. However, we can remember far more if we group information into meaningful units. For example, a long telephone number is easier to recall when it is broken into three shorter parts. Psychologists call this process",
     "chunking", ["forgetting", "rehearsing silently", "multitasking"],
     "Grouping items into units is called chunking."),
    ("Sunk costs",
     "Imagine you have paid for a concert ticket, but on the night you feel ill and would rather stay at home. Many people go anyway, because they do not want to waste the money. Economists point out that the money is already spent whatever you decide, so a rational choice should depend only on",
     "future costs and benefits", ["how much the ticket cost", "what your friends think", "the price of the next concert"],
     "Money already spent cannot be recovered, so only what lies ahead should count."),
    ("Twenty-six blacks in a row",
     "At a casino in Monte Carlo in 1913, the ball in a roulette game landed on black twenty-six times in a row. Gamblers lost huge sums betting on red, believing it was due. But a roulette wheel has no memory; each spin is independent, so the chance of red on the next spin was",
     "exactly the same as before", ["much higher than usual", "almost zero", "impossible to calculate"],
     "Independent spins mean the odds never change."),
    ("Reusing towels",
     "Hotels often ask guests to reuse their towels to protect the environment. In one experiment, a card saying that most guests who had stayed in the same room reused their towels was more effective than a card focused only on the environment. People are strongly influenced by what",
     "others like them do", ["the hotel manager says", "the law requires", "costs the least"],
     "The message about other guests worked best."),
    ("Goldfish and attention",
     "You may have heard that human attention spans are now shorter than those of goldfish, at around eight seconds. The claim spread widely through news articles, but researchers have been unable to find the original study, and experts say attention depends heavily on the task. The famous comparison is therefore",
     "not supported by evidence", ["a proven scientific fact", "true only for children", "based on goldfish research"],
     "No original study can be found, so the claim lacks evidence."),
    ("More users, more usefulness",
     "Some products become more valuable as more people use them. A telephone is useless if nobody else has one, but extremely useful when everyone does. The same is true of messaging apps and online marketplaces. Economists call these network effects, and they help explain why a few large platforms often",
     "dominate their markets", ["fail within a year", "charge nothing forever", "avoid new customers"],
     "The more users a platform has, the stronger it becomes, so large platforms dominate."),
    ("Economies of scale",
     "A factory that makes a million cars can usually produce each one more cheaply than a factory that makes a thousand. Fixed costs, such as machinery and research, are spread over many more units, and large firms can negotiate lower prices from suppliers. These advantages are known as economies of",
     "scale", ["speed", "design", "choice"],
     "Cost advantages from size are economies of scale."),
    ("The cost of a choice",
     "When you spend an evening studying, the cost is not only the price of your books. It is also the value of the best alternative you gave up, such as working a paid shift or spending time with friends. Economists call this the opportunity cost, and it reminds us that every choice involves",
     "giving something up", ["spending money", "a written contract", "a guaranteed reward"],
     "Opportunity cost is the alternative you give up."),
    ("Just-in-time factories",
     "The Japanese carmaker Toyota became famous for a system called just-in-time production. Instead of keeping large stores of parts, factories received components only when they were needed. This reduced storage costs and waste, but it also made production vulnerable, because a single delay in the supply chain could quickly bring the factory to a",
     "standstill", ["profit", "celebration", "new location"],
     "Without stored parts, a delay stops production."),
    ("Cheap bread, dear baskets",
     "Supermarkets sometimes sell popular items, such as bread or milk, at a price that barely covers their cost, or even at a loss. These products are called loss leaders. The idea is that customers who come in for the cheap item will also buy other goods, so the shop makes its profit on the",
     "rest of the shopping", ["bread and milk", "car park charges", "staff wages"],
     "The cheap items attract shoppers who then buy other goods."),
    ("Bulbs built to fail",
     "In 1924, several leading light bulb manufacturers agreed to limit the life of their bulbs to around one thousand hours, and they fined members whose bulbs lasted longer. This agreement, known as the Phoebus cartel, is often cited as an early example of planned obsolescence, the practice of designing products to",
     "wear out sooner", ["last forever", "save energy", "cost less to make"],
     "The cartel deliberately shortened the life of bulbs."),
    ("Brands on screen",
     "When a character in a film drinks a particular brand of soft drink, the company may have paid for that moment. This is product placement, and it has grown as viewers increasingly skip traditional advertisements. Because the brand appears as part of the story rather than in a separate break, audiences are less likely to",
     "notice that they are being advertised to", ["enjoy the film", "remember the characters", "buy a ticket"],
     "Placement hides the advertisement inside the story."),
    ("Milk at the back",
     "Have you noticed that everyday essentials such as milk and eggs are often placed at the back of the supermarket? To reach them, shoppers must walk past many other products, and some of these will end up in the basket. Store layouts are carefully designed to increase",
     "unplanned purchases", ["delivery times", "staff numbers", "the price of milk"],
     "Walking past other products leads shoppers to buy things they had not planned to."),
    ("Comparing currencies with a burger",
     "In 1986, The Economist magazine introduced the Big Mac index as a light-hearted way of comparing currencies. Because the burger is made to a similar recipe around the world, its price in different countries should, in theory, be the same once converted. If it is much cheaper in one country, that country's currency may be",
     "undervalued", ["overvalued", "illegal", "unchanged"],
     "A cheaper burger suggests the currency is worth more than its exchange rate shows."),
    ("Interest on interest",
     "If you invest money and leave the interest in your account, next year you earn interest not only on the original amount but also on the interest already added. Over short periods the difference is small, but over decades it becomes enormous. This is why financial advisers encourage young people to start saving",
     "as early as possible", ["only after retirement", "in cash at home", "when interest rates fall"],
     "Compound growth is largest over long periods, so starting early matters."),
    ("More tickets than seats",
     "Airlines regularly sell more tickets than there are seats on a flight. They do this because, on average, a certain number of passengers do not turn up. Using past data, they can predict how many will be missing. When their prediction is wrong, some passengers are offered compensation to",
     "take a later flight", ["upgrade their seats", "pay extra fees", "cancel their holiday"],
     "When too many passengers arrive, some are paid to travel later."),
    ("Pooling risk",
     "Insurance works by pooling risk. Thousands of people each pay a relatively small amount into a shared fund. In any given year, only a few of them will suffer an expensive event, such as a house fire, and the fund pays for their losses. In this way, a cost that would ruin one family is",
     "shared across many", ["paid by the government", "avoided completely", "doubled each year"],
     "Pooling spreads each loss across all members."),
    ("Subscriptions",
     "Many companies now sell products as subscriptions rather than one-off purchases, from software to razors and meal kits. For businesses, subscriptions provide a steady, predictable income. However, consumer groups warn that some services make cancelling deliberately difficult, relying on the fact that many customers",
     "forget they are still paying",
     ["prefer paying in cash", "cancel on the first day", "never use the internet"],
     "The warning is about customers who keep paying without noticing."),
    ("Fake goods",
     "Counterfeit goods are copies sold under a brand name without permission. While fake handbags and watches may seem harmless, fake medicines, car parts and electrical goods can be dangerous, because they are not made to the same standards. Customs officers therefore focus particularly on counterfeit products that could",
     "put people's safety at risk", ["look fashionable", "be sold online", "cost very little"],
     "The speaker contrasts harmless fakes with dangerous ones."),
    ("Printer cartridges",
     "Home printers are often sold at low prices, sometimes below the cost of making them. Manufacturers make their money later, through replacement ink cartridges, which can be extremely expensive. This approach is sometimes called the razor-and-blades model, because the main profit comes from",
     "repeat purchases", ["the first sale", "free repairs", "advertising revenue"],
     "Profit comes from buying cartridges again and again."),
    ("Points for shoppers",
     "Loyalty programmes reward customers with points or discounts for returning to the same shop. But they also give companies something valuable: detailed data about what each customer buys and when. Retailers use this information to design personalised offers, so the programme benefits the shop as much as",
     "the shopper", ["the government", "its competitors", "the manufacturer"],
     "Both the shop and the customer gain from the scheme."),
    ("Hyperinflation in 1923",
     "In Germany in 1923, prices rose so fast that workers were paid twice a day and rushed to spend their wages before they lost value. Some people burned banknotes for heat because they were cheaper than fuel. By the end of the year, the currency had become almost",
     "worthless", ["impossible to print", "valuable again", "illegal to own"],
     "Hyperinflation destroyed the value of money."),
    ("When a brand becomes a word",
     "Some brand names become so successful that people use them for every product of that type. Escalator, aspirin and thermos all began as trademarks. When this happens, a company can lose its legal protection, which is why firms sometimes remind the public that their brand name should not be used as",
     "an ordinary word", ["a company logo", "a slogan", "a product price"],
     "Protection is lost when a brand becomes a general word."),
    ("The Red Planet",
     "Mars is often called the Red Planet because its surface is covered in dust rich in iron oxide, the same compound that forms rust on Earth. Fine particles of this dust are carried high into the thin atmosphere, so even the sky on Mars often looks",
     "pinkish or orange", ["deep blue", "completely black", "bright green"],
     "Red dust in the air colours the Martian sky."),
    ("Saturn's rings",
     "Saturn's rings look solid from a distance, but they are made of countless pieces of ice and rock, ranging from tiny grains to chunks as large as houses. Although the rings are hundreds of thousands of kilometres wide, in many places they are remarkably thin, often only about ten metres",
     "thick", ["long", "wide", "away"],
     "The contrast is between the rings' great width and their thinness."),
    ("Finding distant planets",
     "Most known planets outside our solar system were discovered by the transit method. A telescope watches a star continuously, and if a planet passes in front of it, the star's brightness drops very slightly. By measuring how much light is blocked, astronomers can estimate the planet's",
     "size", ["age", "name", "orbit around the galaxy"],
     "A larger planet blocks more light, so the dip reveals its size."),
    ("Pluto reclassified",
     "When Pluto was discovered in 1930, it was counted as the ninth planet. But as astronomers found more objects of similar size in the outer solar system, they had to decide what a planet really was. In 2006, the International Astronomical Union agreed a new definition, and Pluto was reclassified as a",
     "dwarf planet", ["moon of Neptune", "comet", "star"],
     "The 2006 definition made Pluto a dwarf planet."),
    ("The hottest planet",
     "Venus is further from the Sun than Mercury, yet it is the hottest planet in the solar system, with surface temperatures high enough to melt lead. The reason is its extremely thick atmosphere of carbon dioxide, which traps heat so effectively that the surface cannot",
     "cool down", ["warm up", "absorb sunlight", "be very hot"],
     "Trapped heat stops the surface from cooling."),
    ("The far side of the Moon",
     "The Moon always shows the same face to the Earth, because it rotates once on its axis in exactly the time it takes to orbit our planet. The far side is often wrongly called the dark side, but it receives just as much sunlight. It was first photographed in 1959 by a Soviet",
     "space probe", ["telescope on Earth", "astronaut", "weather balloon"],
     "The far side cannot be seen from Earth, so a probe was needed."),
    ("Halley's prediction",
     "In 1705, the astronomer Edmond Halley argued that comets seen in 1531, 1607 and 1682 were in fact the same object, returning roughly every seventy-six years. He predicted it would appear again in 1758. He died before that date, but the comet returned as he had forecast, and it was named",
     "in his honour", ["after the year it appeared", "by a committee", "after a ship"],
     "The comet carries Halley's name because of his prediction."),
    ("The aurora",
     "The northern lights, or aurora, appear when charged particles from the Sun reach the Earth. The planet's magnetic field guides many of these particles towards the polar regions, where they collide with gases high in the atmosphere and make them glow. This is why auroras are seen most often at",
     "high latitudes", ["the equator", "midday", "sea level"],
     "The particles are guided towards the poles."),
    ("Eating in orbit",
     "On early space missions, astronauts ate food squeezed from tubes and small cubes coated to prevent crumbs. Crumbs were a real concern, because in weightless conditions they float around the cabin and could get into equipment or an astronaut's eyes. Bread, for example, is usually replaced on the International Space Station by",
     "tortillas", ["biscuits", "cakes", "crackers"],
     "Tortillas produce almost no crumbs; the other foods crumble."),
    ("Telling time by shadow",
     "A sundial tells the time using the shadow cast by a pointer, called a gnomon. For the dial to be accurate throughout the year, the gnomon must be angled to point towards the celestial pole, which means its angle depends on the",
     "latitude of the place", ["height of the owner", "colour of the dial", "season it was built"],
     "The angle to the pole changes with latitude."),
    ("El Niño",
     "Every few years, the surface waters of the central and eastern tropical Pacific Ocean become unusually warm. This event, called El Niño, shifts rainfall patterns around the world, bringing heavy rain to parts of South America and drought to parts of Australia. Its name, meaning the boy child, refers to its tendency to appear around",
     "Christmas", ["midsummer", "the new moon", "the spring harvest"],
     "The boy child refers to Christmas, when the warming often appears off South America."),
    ("How hailstones grow",
     "Hailstones form inside powerful thunderstorm clouds. Strong upward currents of air carry water droplets high into the cloud, where they freeze. The small ice pellets fall, collect more water, and are lifted again, growing layer by layer. Hailstones fall to the ground when they become too heavy for the",
     "updrafts to support", ["rain to carry", "ground to absorb", "sun to melt"],
     "Rising air holds the stones up until they are too heavy."),
    ("The truth about quicksand",
     "In films, characters caught in quicksand often sink until they disappear. In reality, quicksand is a mixture of sand and water, and it is much denser than the human body. Researchers have shown that a person would sink only to about the waist. The real danger comes from being trapped and unable to",
     "pull themselves free", ["float on the surface", "see the sky", "feel their feet"],
     "People do not sink completely; the risk is being stuck."),
    ("Naming storms",
     "Tropical storms in the Atlantic are given names from lists prepared in advance by the World Meteorological Organization. Short, familiar names are easier to remember and reduce confusion when several storms are active. When a storm is particularly deadly or destructive, its name is",
     "retired and replaced", ["used again the next year", "given to a city", "kept secret"],
     "Names of very destructive storms are not reused."),
    ("Meteor showers",
     "Meteor showers happen when the Earth passes through a trail of dust and small particles left behind by a comet. These particles strike the atmosphere at high speed and burn up, creating streaks of light. Because the Earth crosses the same trails at the same point in its orbit each year, many showers occur",
     "on the same dates every year", ["only once a century", "at random times", "during total eclipses"],
     "The Earth meets the same trails at the same time each year."),
]

SMW_ITEMS = []
for idx, (title, lead, correct, wrong, why) in enumerate(SMW_RAW, 1):
    assert len(wrong) == 3, f"SMW {idx}: need three wrong endings"
    slot = (idx - 1) % 4
    texts = wrong[:slot] + [correct] + wrong[slot:]
    letters = "ABCD"
    SMW_ITEMS.append({
        "id": f"q-pl90-smw-{idx:02d}",
        "type_id": "pte-select-missing-word",
        "type_name": "Select Missing Word",
        "title": title,
        "prompt": "You will hear a recording. At the end of the recording the last word or group of words has been replaced by a beep. Select the correct option to complete the recording.",
        "audio_transcript": f"{lead} [beep]",
        "prep_time_seconds": 7,
        "time_limit_seconds": 90,
        "options": [{"id": letters[n], "text": t} for n, t in enumerate(texts)],
        "correct_answers": [letters[slot]],
        "blanks": None,
        "model_answer": None,
        "explanation": f"Option ({letters[slot]}) is correct: the recording ends with \"{correct}\". {why}",
        "points": 1,
    })
