-- Migration: 000065_ielts_speaking_part2_expansion.up.sql
-- 50 additional questions for IELTS Speaking Part 2 (Cue Card)

-- Part 2: Cue Cards (60s prep, 120s speak)
INSERT INTO questions (
    id,
    exam_version_id,
    exam,
    skill,
    type_id,
    type_name,
    title,
    prompt,
    prep_time_seconds,
    time_limit_seconds,
    points,
    difficulty,
    tags,
    supported_exams
) VALUES
(
    'ielts-spk-part2-011',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Memorable Meal',
    'Describe a memorable meal you had with other people. You should say: where and when you had the meal; who you were with; what you ate; and explain why this meal was so memorable. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-012',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Childhood Toy',
    'Describe a toy or game you loved as a child. You should say: what it was; who gave it to you or how you got it; how you used to play with it; and explain why it was special to you. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-013',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Time You Were Late',
    'Describe an occasion when you arrived late for something important. You should say: what the event was; why you were late; what happened as a result; and explain how you felt about the situation afterwards. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-014',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Sport You Would Like to Try',
    'Describe a sport or physical activity you would like to try in the future. You should say: what the activity is; where you first saw or heard about it; what you would need to do it; and explain why it appeals to you. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-015',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Piece of Art You Admire',
    'Describe a painting, sculpture or other work of art you admire. You should say: what the artwork is; where you saw it; what it looks like; and explain why you find it impressive. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-016',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Family Tradition',
    'Describe a tradition that is important in your family. You should say: what the tradition is; how long your family has followed it; what everyone does; and explain why your family keeps this tradition alive. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-017',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Neighbour You Know Well',
    'Describe a neighbour you know well. You should say: who the neighbour is; how long you have known them; what you usually do or talk about together; and explain why you get along well with this person. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-018',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Time You Changed Your Mind',
    'Describe a time when you changed your mind about something important. You should say: what the decision or opinion was; what made you reconsider; what you decided in the end; and explain whether you think it was the right choice. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-019',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Wedding You Attended',
    'Describe a wedding or similar ceremony you attended. You should say: whose ceremony it was; where it took place; what happened during the day; and explain what you remember most about it. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-020',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Song With Special Meaning',
    'Describe a song or piece of music that has special meaning for you. You should say: what the song is; when you first heard it; what it sounds like or is about; and explain why it is meaningful to you. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-021',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Crowded Place',
    'Describe a crowded place you have been to. You should say: where it was; when you went there; why it was so crowded; and explain how you felt being there. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-022',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Photograph You Treasure',
    'Describe a photograph that you treasure. You should say: when and where the photo was taken; who or what is in it; who took it; and explain why it is valuable to you. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-023',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Time You Helped a Stranger',
    'Describe a time when you helped someone you did not know. You should say: who the person was; where it happened; what kind of help you gave; and explain how you felt after helping them. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-024',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Website or App You Use Often',
    'Describe a website or mobile app you use frequently. You should say: what it is called; what it does; how often you use it; and explain why you find it valuable. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-025',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Teacher Who Stood Out',
    'Describe a teacher from your school days whom you remember well. You should say: who the teacher was; what subject they taught; how they taught their lessons; and explain why you still remember them. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-026',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'An Item of Clothing You Like',
    'Describe an item of clothing that you enjoy wearing. You should say: what it is; where you got it; when you usually wear it; and explain why you like it so much. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-027',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Time You Felt Proud of Someone',
    'Describe a time when you felt proud of a family member or friend. You should say: who the person was; what they did; how you found out about it; and explain why you felt so proud. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-028',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A River, Lake or Sea',
    'Describe a river, lake or sea that you have visited. You should say: where it is; when you went there; what you did there; and explain how you felt about the place. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-029',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Competition You Took Part In',
    'Describe a competition or contest you took part in. You should say: what the competition was; how you prepared for it; how well you performed; and explain what you learned from taking part. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-030',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Plan You Had to Cancel',
    'Describe a plan that you had to cancel or postpone. You should say: what the plan was; why you had to cancel it; what you did instead; and explain how you felt about the change. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-031',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Garden or Park You Enjoy',
    'Describe a garden or public park that you like to visit. You should say: where it is; what it looks like; what people do there; and explain why you enjoy spending time there. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-032',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'An Interesting Conversation',
    'Describe an interesting conversation you had with someone. You should say: who you spoke with; where the conversation took place; what you talked about; and explain why you found it interesting. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-033',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Gift You Gave',
    'Describe a gift you gave to someone that they really liked. You should say: what the gift was; who you gave it to; why you chose it; and explain how the person reacted when they received it. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-034',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Foreign Country You Would Like to Live In',
    'Describe a foreign country where you would like to live for a while. You should say: which country it is; how you learned about it; what you would do there; and explain why you would like to live there. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-035',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Time You Lost Something',
    'Describe a time when you lost something valuable. You should say: what you lost; where and how you lost it; what you did to try to find it; and explain how the experience affected you. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-036',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Hobby You Started Recently',
    'Describe a hobby or interest you have taken up recently. You should say: what the hobby is; how you got started; how much time you spend on it; and explain what you enjoy about it. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-037',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Recent Change in Your Area',
    'Describe a recent change in the area where you live. You should say: what the change was; when it happened; how local people reacted to it; and explain whether you think it was a positive change. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-038',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Time You Taught Someone',
    'Describe a time when you taught someone how to do something. You should say: who you taught; what you taught them; how you explained it; and explain how successful the experience was. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-039',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Famous Person You Would Like to Meet',
    'Describe a well-known person you would like to meet. You should say: who the person is; what they are known for; what you would say or ask if you met them; and explain why you would like to meet them. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-040',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'An Unusual Building',
    'Describe a modern building with an unusual design. You should say: where it is; what it looks like; what it is used for; and explain what you think of its design. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-041',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Day Without Your Phone',
    'Describe a time when you could not use your mobile phone for a whole day. You should say: when it happened; why you could not use your phone; what you did during that day; and explain how you felt about the experience. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-042',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Party You Enjoyed',
    'Describe a party or social gathering you enjoyed. You should say: what the occasion was; where it was held; who attended; and explain why you enjoyed it. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-043',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Risk You Took',
    'Describe a time when you took a risk that turned out well. You should say: what the risk was; why you decided to take it; what the outcome was; and explain how the experience changed you. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-044',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'An Animal You Find Interesting',
    'Describe a wild animal that you find interesting. You should say: what the animal is; where it lives; how you learned about it; and explain why it interests you. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-045',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Rule You Disagree With',
    'Describe a rule at school, at work or in public that you disagree with. You should say: what the rule is; where it applies; why it was introduced; and explain why you disagree with it. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-046',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Morning Routine',
    'Describe your ideal morning routine. You should say: what time you would wake up; what activities you would do; how long it would take; and explain why this routine would suit you. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-047',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Time You Waited a Long Time',
    'Describe a time when you had to wait a long time for something. You should say: what you were waiting for; where you were; how long you had to wait; and explain how you dealt with the wait. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-048',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Letter or Message You Received',
    'Describe a letter, email or message that made you happy. You should say: who sent it; when you received it; what it said; and explain why it made you so happy. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-049',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Place in Your City for Visitors',
    'Describe a place in your town or city that you would recommend to visitors. You should say: what and where the place is; what visitors can see or do there; how they can get there; and explain why you would recommend it. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-050',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Group Project',
    'Describe a project you worked on as part of a team. You should say: what the project was; who was in the team; what your role was; and explain whether the team worked well together. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-051',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Time the Weather Affected Your Plans',
    'Describe a time when bad weather affected your plans. You should say: what you had planned; what the weather was like; what you did instead; and explain how you felt about it. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-052',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Vehicle You Would Like to Own',
    'Describe a car, motorbike or other vehicle you would like to own. You should say: what the vehicle is; what it looks like; how you would use it; and explain why you would like to own it. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-053',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'An Older Person You Respect',
    'Describe an older person you respect. You should say: who the person is; how you know them; what they are like; and explain why you respect them. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-054',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Time You Felt Nervous',
    'Describe a situation that made you feel nervous. You should say: what the situation was; when it happened; what you did to calm down; and explain how things turned out in the end. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-055',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Subject You Wish You Had Studied',
    'Describe a subject you wish you had studied at school or university. You should say: what the subject is; why you did not study it; what you would like to learn about it; and explain how it might have been useful to you. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-056',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Handmade Object',
    'Describe something you made by hand. You should say: what you made; how you made it; how long it took; and explain how you felt about the finished object. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-057',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Talkative Person',
    'Describe a person you know who is very talkative. You should say: who the person is; how you know them; what they usually talk about; and explain how you feel about spending time with them. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-058',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Good Decision You Made',
    'Describe a good decision you made recently. You should say: what the decision was; why you had to make it; how you made it; and explain why you think it was a good decision. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-059',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Place Where You Study or Work Best',
    'Describe a place where you can study or work well. You should say: where it is; what it looks like; how often you go there; and explain why it helps you concentrate. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-060',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'An Advertisement You Remember',
    'Describe an advertisement you have seen that you remember well. You should say: what product or service it advertised; where you saw it; what happened in it; and explain why it stuck in your memory. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
)
ON CONFLICT (id) DO NOTHING;
