-- Migration: 000058_ielts_speaking_parts_2_and_3.up.sql
-- 10 distinct questions for IELTS Speaking Part 2 (Cue Card)
-- 10 distinct questions for IELTS Speaking Part 3 (Discussion)

-- Part 2: Cue Cards (60s prep, 120s speak)
INSERT INTO questions (
    id,
    exam_version_id,
    exam,
    skill,
    type_id,
    type_name,
    title,
    prompt,
    prep_time_seconds,
    time_limit_seconds,
    points,
    difficulty,
    tags,
    supported_exams
) VALUES
(
    'ielts-spk-part2-001',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'An Unforgettable Journey',
    'Describe an unforgettable journey you have taken. You should say: where you went and how you travelled; who you went with; what happened during the journey; and explain why this journey was so memorable to you. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-002',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'An Inspiring Person',
    'Describe a person who has had a strong influence on your life. You should say: who this person is and how you know them; what qualities or achievements make them special; what they have taught you; and explain why you admire or look up to them. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-003',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Cultural Festival or Celebration',
    'Describe a traditional festival or celebration in your country that you enjoyed. You should say: what the festival is and when it takes place; what people do during this event; what special food or clothing is involved; and explain why this festival is meaningful to you. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-004',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Useful Electronic Device',
    'Describe an electronic device or gadget you find very useful. You should say: what the device is and when you got it; how often you use it; what tasks it helps you perform; and explain why you would find it difficult to manage without it. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-005',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Difficult Goal You Achieved',
    'Describe a difficult goal that you set for yourself and achieved. You should say: what the goal was; why you decided to pursue it; what obstacles or difficulties you faced; and explain how you felt when you successfully completed it. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-006',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'An Impactful Book or Movie',
    'Describe a book or film that made a deep impression on you. You should say: what the title is and what the story is about; when and why you read or watched it; what message or theme stood out to you; and explain why it left such a lasting impression. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-007',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Historic Building or Monument',
    'Describe an interesting historical building or monument you have visited. You should say: where it is located; what it looks like; why it was built or why it is historically significant; and explain what you found most fascinating about your visit. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-008',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'An Environmental Project or Activity',
    'Describe an environmental project or clean-up activity you participated in or learned about. You should say: what the project involved; where and when it took place; who organised or took part in it; and explain why this initiative was important for the local community. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-009',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'Valuable Advice You Received',
    'Describe a valuable piece of advice someone gave you. You should say: who gave you the advice; what the situation or problem was; what the person advised you to do; and explain how following this advice affected your life. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part2-010',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part2',
    'Speaking Part 2 (Cue Card)',
    'A Favourite Local Shop or Market',
    'Describe a local market or shop you enjoy visiting. You should say: where it is and what products it sells; how often you go there; what the atmosphere is like; and explain why you prefer this shop or market over others. You have one minute to prepare and may make notes. Speak for one to two minutes.',
    60,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 2'],
    ARRAY['IELTS']
)
ON CONFLICT (id) DO NOTHING;

-- Part 3: Discussions (0s prep, 120s speak)
INSERT INTO questions (
    id,
    exam_version_id,
    exam,
    skill,
    type_id,
    type_name,
    title,
    prompt,
    prep_time_seconds,
    time_limit_seconds,
    points,
    difficulty,
    tags,
    supported_exams
) VALUES
(
    'ielts-spk-part3-001',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Tourism and Cultural Preservation',
    'How does international tourism affect traditional customs and historic sites in developing nations? Should governments limit visitor numbers to fragile cultural locations? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-002',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Technology and Automation in the Workplace',
    'In what ways will artificial intelligence and automation change the types of jobs available to future generations? What skills should educational systems prioritize to prepare students for these changes? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-003',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Urban Growth and Quality of Life',
    'What major social problems are created by rapid urbanisation and overcrowded cities? How can city planners create environments that encourage stronger community relationships? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-004',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Consumerism and Environmental Responsibility',
    'Who holds greater responsibility for reducing environmental waste: individual consumers or large manufacturing corporations? Can consumer campaigns genuinely persuade businesses to adopt greener practices? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-005',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Education Methods and Standardized Testing',
    'Do traditional examinations accurately assess a student''s true capabilities and intellect? How can schools better support students who excel in practical or creative pursuits rather than academic exams? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-006',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Digital Communication and Personal Relationships',
    'How has online communication transformed the depth and quality of personal friendships? Are younger generations becoming more socially isolated despite being constantly connected? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-007',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Public Health and Dietary Choices',
    'Should governments impose higher taxes on unhealthy foods and sugary drinks to combat rising obesity? What role should public advertising play in encouraging active lifestyles? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-008',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'The Role of the Arts in Modern Society',
    'Why is it important for a nation to support artists, musicians, and writers? Should public tax revenues be spent on museums and galleries during economic downturns? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-009',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Globalisation and Small Businesses',
    'How do global multinational chains impact small local businesses and regional variety? What advantages do local independent shops still hold over large international corporations? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-010',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Qualities of Effective Leaders',
    'What essential qualities distinguish an inspiring and ethical leader from an ineffective one? Are natural leadership abilities born, or can effective leadership skills be taught and cultivated? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
)
ON CONFLICT (id) DO NOTHING;
