-- Migration: 000065_ielts_speaking_part3_expansion.up.sql
-- 50 more IELTS Speaking Part 3 (Discussion) questions (part3-011 to part3-060).
-- Topics do not repeat any Part 3 question from 000058.

-- Part 3: Discussions (0s prep, 120s speak)
INSERT INTO questions (
    id,
    exam_version_id,
    exam,
    skill,
    type_id,
    type_name,
    title,
    prompt,
    prep_time_seconds,
    time_limit_seconds,
    points,
    difficulty,
    tags,
    supported_exams
) VALUES
(
    'ielts-spk-part3-011',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Housing and Home Ownership',
    'Why is it becoming harder for young people to buy their own homes in many countries? Is renting a home a sensible long-term choice compared with buying one? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-012',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Neighbourhood Communities',
    'Why do people in modern cities often know very little about their neighbours? What could local councils do to build a stronger sense of community? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-013',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Changing Family Structures',
    'How have family sizes and roles changed over the last few decades? Do you think grandparents should play a larger part in raising children? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-014',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Online Shopping and Retail',
    'What effects has the rise of online shopping had on town centres and high streets? Will physical shops disappear completely in the future? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-015',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Fashion and Identity',
    'Why do some people spend large amounts of money on designer brands? Does the fashion industry place too much pressure on young people to look a certain way? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-016',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Film and Society',
    'Can films have a real influence on the way people think and behave? Should governments censor films that contain violent content? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-017',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Traditional Cooking Skills',
    'Why are fewer young people learning to cook traditional family recipes? Should cooking be a compulsory subject in schools? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-018',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Green Spaces in Cities',
    'How important are parks and green areas for people living in large cities? Should developers be required to include green space in every new building project? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-019',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Animal Welfare',
    'Is it acceptable to keep wild animals in zoos? What responsibilities do people have towards the animals they keep as pets? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-020',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Work-Life Balance',
    'Why do so many people today struggle to separate their work from their personal life? Should employers be legally prevented from contacting staff outside working hours? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-021',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Remote Working',
    'What are the long-term advantages and disadvantages of working from home? How might remote working change the way cities are designed? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-022',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Sleep and Modern Lifestyles',
    'Why are people in modern societies sleeping less than previous generations did? Whose responsibility is it to raise awareness of the importance of rest? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-023',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Museums and Heritage',
    'What role do museums play in helping a society understand its history? Should historical objects taken from other countries be returned to their places of origin? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-024',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Public Libraries',
    'Are public libraries still necessary in the age of the internet? How could libraries adapt to remain relevant to younger people? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-025',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Language Learning',
    'Why do some people find it much easier to learn a foreign language than others? Is it better to start learning a second language in early childhood? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-026',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Endangered Languages',
    'What is lost when a minority language disappears? Should governments spend money protecting languages that very few people speak? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-027',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Gift-Giving and Consumer Culture',
    'Has gift-giving on special occasions become too commercial? Are experiences better gifts than physical objects? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-028',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Noise and Light Pollution',
    'How does constant noise in cities affect people''s health and wellbeing? What measures could authorities take to reduce noise and light pollution? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-029',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Space Exploration',
    'Is spending money on space exploration justified when there are serious problems on Earth? Should private companies be allowed to lead space missions? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-030',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Climate and Extreme Weather',
    'How are changing weather patterns affecting farming and daily life around the world? Should wealthier nations pay more to help poorer countries adapt? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-031',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Food Waste',
    'Why do households and supermarkets throw away so much edible food? What practical steps could reduce food waste at a national level? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-032',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Vegetarianism and Plant-Based Diets',
    'Why are plant-based diets becoming more popular? Should governments encourage people to eat less meat for environmental reasons? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-033',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Restaurant Culture',
    'Why do people increasingly eat out or order takeaway food rather than cooking at home? What effect does this have on family life? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-034',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Leisure Time and Hobbies',
    'Do people today have more or less free time than their parents did? Why is it important for adults to have hobbies unrelated to their jobs? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-035',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Video Games',
    'Can video games have educational value for children and teenagers? Should there be strict limits on how long young people spend gaming? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-036',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Digital Privacy',
    'How much personal information should technology companies be allowed to collect about their users? Are people too willing to give away their privacy for convenience? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-037',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'The Future of Written Communication',
    'Has the widespread use of texting and email damaged people''s writing skills? Will formal letter writing become a completely lost skill? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-038',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Punctuality Across Cultures',
    'Why do attitudes to punctuality differ so much between cultures? Is being on time more important in business than in social situations? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-039',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Childhood and Play',
    'How has the way children play changed compared with previous generations? Do children today have enough freedom to play outside unsupervised? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-040',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'The Role of Teachers',
    'What qualities make someone an excellent teacher? Will technology ever be able to replace teachers in the classroom? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-041',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Water Safety and Swimming',
    'Should learning to swim be a compulsory part of every child''s education? Who should be responsible for safety at public beaches and lakes? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-042',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Coastal Protection',
    'What problems do coastal communities face as sea levels rise? Should people be discouraged from building homes close to the sea? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-043',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Rural Depopulation',
    'Why are so many young people leaving villages and moving to cities? What could be done to make rural areas more attractive places to live? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-044',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Celebrity Culture',
    'Why are people so interested in the private lives of celebrities? Do famous people have a responsibility to act as role models? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-045',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Advertising and Children',
    'Should advertising aimed at young children be banned? How does advertising influence the choices adults make about what they buy? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-046',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Personal Finance Education',
    'Should schools teach students how to manage money and budget? Why do many young adults fall into debt? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-047',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Ageing Populations',
    'What challenges do countries face when a large proportion of the population is elderly? How can societies make better use of older people''s experience? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-048',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Volunteering and Charity',
    'Why do some people choose to volunteer their time for good causes? Should community service be compulsory for secondary school students? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-049',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Sport and National Identity',
    'Why do major international sporting events generate such strong national pride? Is hosting events like the Olympics worth the enormous cost? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-050',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Professional Sport and Salaries',
    'Are top athletes paid too much compared with workers in essential jobs such as nursing? What effect do high salaries have on the spirit of sport? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-051',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Traffic and Road Safety',
    'What are the main causes of traffic accidents in your country? Should the minimum age for driving be raised? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-052',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Electric Vehicles and Transport Policy',
    'Will electric cars solve the environmental problems caused by road transport? Should petrol and diesel cars be banned in city centres? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-053',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Crime and Punishment',
    'Is prison the most effective way to deal with people who commit crimes? What can society do to prevent young people from turning to crime? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-054',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Rules and Personal Freedom',
    'Where should governments draw the line between protecting citizens and restricting their freedom? Are there too many rules in modern society? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-055',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'News and Media Trust',
    'Why do many people no longer trust traditional news outlets? How can ordinary people tell the difference between reliable news and misinformation? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-056',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Science and Public Understanding',
    'Why do some people distrust scientific experts? How could scientists communicate their research more effectively to the public? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-057',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Medical Advances and Ethics',
    'Should everyone have equal access to expensive new medical treatments? Are there limits to what medical science should be allowed to do? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-058',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Architecture and Modern Design',
    'Should new buildings in historic towns be designed to match traditional styles? How does the design of a building affect the people who use it? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-059',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Success and Happiness',
    'Is financial success the most important measure of a successful life? Why do some wealthy people still feel unhappy? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
),
(
    'ielts-spk-part3-060',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part3',
    'Speaking Part 3 (Discussion)',
    'Mentors and Role Models',
    'How important is it for young people to have a mentor outside their family? Are older generations still valued as a source of wisdom today? Discuss reasons, comparisons and examples. This is a two-minute discussion drill; a full examiner-led Part 3 lasts 4–5 minutes.',
    0,
    120,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 3'],
    ARRAY['IELTS']
)
ON CONFLICT (id) DO NOTHING;
