-- Starter EPS-TOPIK content: two questions for each of the sixteen subtasks,
-- so every link in the practice menu opens a working question and "Next
-- question" has somewhere to go.
--
-- The questions are written for Prepyo in the style of HRD Korea's published
-- tasks; none is copied from its books. Pictures are simple SVG drawings kept
-- as question assets, and listening items carry a script the browser reads in
-- a Korean voice until real recordings are uploaded. All of it can be replaced
-- from the admin question bank.

INSERT INTO question_assets (id, content_type, byte_size, data) VALUES
    ('eps_seed_hammer', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">🔨</text></svg>', 'UTF8')),
    ('eps_seed_gloves', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">🧤</text></svg>', 'UTF8')),
    ('eps_seed_umbrella', 'image/svg+xml', 316, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">☂️</text></svg>', 'UTF8')),
    ('eps_seed_cap', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">🧢</text></svg>', 'UTF8')),
    ('eps_seed_glasses', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">👓</text></svg>', 'UTF8')),
    ('eps_seed_phone', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">📞</text></svg>', 'UTF8')),
    ('eps_seed_extinguisher', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">🧯</text></svg>', 'UTF8')),
    ('eps_seed_ladder', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">🪜</text></svg>', 'UTF8')),
    ('eps_seed_milk', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">🥛</text></svg>', 'UTF8')),
    ('eps_seed_coffee', 'image/svg+xml', 313, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">☕</text></svg>', 'UTF8')),
    ('eps_seed_water', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">💧</text></svg>', 'UTF8')),
    ('eps_seed_juice', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">🧃</text></svg>', 'UTF8')),
    ('eps_seed_box', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">📦</text></svg>', 'UTF8')),
    ('eps_seed_car', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">🚗</text></svg>', 'UTF8')),
    ('eps_seed_noodles', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">🍜</text></svg>', 'UTF8')),
    ('eps_seed_book', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">📖</text></svg>', 'UTF8')),
    ('eps_seed_clock3', 'image/svg+xml', 314, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><text x="120" y="158" font-size="120" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">🕒</text></svg>', 'UTF8')),
    ('eps_seed_price_3500', 'image/svg+xml', 394, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#FFFBEB" stroke="#F59E0B" stroke-width="6"/><circle cx="46" cy="46" r="12" fill="#F59E0B"/><text x="120" y="138" font-size="40" font-weight="700" text-anchor="middle" fill="#0F172A" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">3,500원</text></svg>', 'UTF8')),
    ('eps_seed_price_5300', 'image/svg+xml', 394, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#FFFBEB" stroke="#F59E0B" stroke-width="6"/><circle cx="46" cy="46" r="12" fill="#F59E0B"/><text x="120" y="138" font-size="40" font-weight="700" text-anchor="middle" fill="#0F172A" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">5,300원</text></svg>', 'UTF8')),
    ('eps_seed_price_3050', 'image/svg+xml', 394, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#FFFBEB" stroke="#F59E0B" stroke-width="6"/><circle cx="46" cy="46" r="12" fill="#F59E0B"/><text x="120" y="138" font-size="40" font-weight="700" text-anchor="middle" fill="#0F172A" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">3,050원</text></svg>', 'UTF8')),
    ('eps_seed_price_35000', 'image/svg+xml', 395, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="4" y="4" width="232" height="232" rx="28" fill="#FFFBEB" stroke="#F59E0B" stroke-width="6"/><circle cx="46" cy="46" r="12" fill="#F59E0B"/><text x="120" y="138" font-size="40" font-weight="700" text-anchor="middle" fill="#0F172A" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">35,000원</text></svg>', 'UTF8')),
    ('eps_seed_day_5', 'image/svg+xml', 648, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="20" y="30" width="200" height="190" rx="18" fill="#FFFFFF" stroke="#DC2626" stroke-width="6"/><rect x="20" y="30" width="200" height="50" rx="18" fill="#DC2626"/><rect x="20" y="62" width="200" height="18" fill="#DC2626"/><text x="120" y="66" font-size="26" font-weight="700" text-anchor="middle" fill="#FFFFFF" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">매달</text><text x="120" y="176" font-size="72" font-weight="700" text-anchor="middle" fill="#0F172A" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">5일</text></svg>', 'UTF8')),
    ('eps_seed_day_15', 'image/svg+xml', 649, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="20" y="30" width="200" height="190" rx="18" fill="#FFFFFF" stroke="#DC2626" stroke-width="6"/><rect x="20" y="30" width="200" height="50" rx="18" fill="#DC2626"/><rect x="20" y="62" width="200" height="18" fill="#DC2626"/><text x="120" y="66" font-size="26" font-weight="700" text-anchor="middle" fill="#FFFFFF" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">매달</text><text x="120" y="176" font-size="72" font-weight="700" text-anchor="middle" fill="#0F172A" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">15일</text></svg>', 'UTF8')),
    ('eps_seed_day_25', 'image/svg+xml', 649, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="20" y="30" width="200" height="190" rx="18" fill="#FFFFFF" stroke="#DC2626" stroke-width="6"/><rect x="20" y="30" width="200" height="50" rx="18" fill="#DC2626"/><rect x="20" y="62" width="200" height="18" fill="#DC2626"/><text x="120" y="66" font-size="26" font-weight="700" text-anchor="middle" fill="#FFFFFF" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">매달</text><text x="120" y="176" font-size="72" font-weight="700" text-anchor="middle" fill="#0F172A" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">25일</text></svg>', 'UTF8')),
    ('eps_seed_day_10', 'image/svg+xml', 649, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect x="20" y="30" width="200" height="190" rx="18" fill="#FFFFFF" stroke="#DC2626" stroke-width="6"/><rect x="20" y="30" width="200" height="50" rx="18" fill="#DC2626"/><rect x="20" y="62" width="200" height="18" fill="#DC2626"/><text x="120" y="66" font-size="26" font-weight="700" text-anchor="middle" fill="#FFFFFF" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">매달</text><text x="120" y="176" font-size="72" font-weight="700" text-anchor="middle" fill="#0F172A" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">10일</text></svg>', 'UTF8')),
    ('eps_seed_pharmacy', 'image/svg+xml', 1124, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 320"><rect x="6" y="6" width="468" height="308" rx="22" fill="#FFFFFF" stroke="#16A34A" stroke-width="8"/><rect x="6" y="6" width="468" height="78" rx="22" fill="#16A34A"/><rect x="6" y="60" width="468" height="24" fill="#16A34A"/><text x="240" y="60" font-size="40" font-weight="700" text-anchor="middle" fill="#FFFFFF" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">행복 약국</text><text x="40" y="140" font-size="28" fill="#0F172A" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">영업시간: 오전 9시 ~ 오후 7시</text><text x="40" y="190" font-size="28" fill="#DC2626" font-weight="700" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">일요일은 쉽니다</text><text x="40" y="240" font-size="28" fill="#0F172A" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">전화: 031-123-4567</text><text x="40" y="285" font-size="22" fill="#475569" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">경기도 안산시 단원구</text></svg>', 'UTF8')),
    ('eps_seed_shock_sign', 'image/svg+xml', 555, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 320"><rect x="6" y="6" width="308" height="308" rx="22" fill="#FFFFFF" stroke="#CBD5E1" stroke-width="4"/><polygon points="160,30 290,250 30,250" fill="#FACC15" stroke="#0F172A" stroke-width="12" stroke-linejoin="round"/><polygon points="172,90 128,170 158,170 142,225 196,140 164,140 182,90" fill="#0F172A"/><text x="160" y="295" font-size="34" font-weight="700" text-anchor="middle" fill="#0F172A" font-family="Noto Sans KR,Malgun Gothic,Apple SD Gothic Neo,sans-serif">감전 주의</text></svg>', 'UTF8')),
    ('eps_seed_desk', 'image/svg+xml', 649, convert_to('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 320"><rect x="6" y="6" width="468" height="308" rx="22" fill="#F8FAFC" stroke="#CBD5E1" stroke-width="4"/><rect x="60" y="170" width="240" height="18" rx="4" fill="#92400E"/><rect x="75" y="188" width="14" height="100" fill="#92400E"/><rect x="271" y="188" width="14" height="100" fill="#92400E"/><text x="180" y="160" font-size="84" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">👜</text><text x="385" y="285" font-size="110" text-anchor="middle" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">🪑</text></svg>', 'UTF8'))
ON CONFLICT (id) DO NOTHING;

INSERT INTO questions
    (id, exam_version_id, exam, supported_exams, skill, type_id, type_name, title, prompt,
     context_passage, audio_transcript, image_url, time_limit_seconds, options, correct_answers,
     explanation, difficulty, tags, points, is_published)
VALUES
    ('eps-seed-r-picture-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-picture', 'Picture to Word or Sentence', '공구 이름: 망치', '다음 그림을 보고 맞는 단어나 문장을 고르십시오.', NULL, NULL, '/api/v1/questions/assets/eps_seed_hammer', 75, '[{"id": "A", "text": "망치입니다."}, {"id": "B", "text": "가위입니다."}, {"id": "C", "text": "우산입니다."}, {"id": "D", "text": "시계입니다."}]'::jsonb, '["A"]'::jsonb, '망치 means "hammer". 가위 is scissors, 우산 is umbrella and 시계 is a clock.', 'easy', ARRAY['EPS_TOPIK Reading', 'Picture to Word or Sentence', 'tools-machines']::text[], 1, TRUE),
    ('eps-seed-r-picture-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-picture', 'Picture to Word or Sentence', '보호 장비: 장갑', '다음 그림을 보고 맞는 단어나 문장을 고르십시오.', NULL, NULL, '/api/v1/questions/assets/eps_seed_gloves', 75, '[{"id": "A", "text": "양말입니다."}, {"id": "B", "text": "장갑입니다."}, {"id": "C", "text": "안경입니다."}, {"id": "D", "text": "가방입니다."}]'::jsonb, '["B"]'::jsonb, '장갑 means "gloves", worn to protect your hands at work. 양말 is socks, 안경 is glasses and 가방 is a bag.', 'easy', ARRAY['EPS_TOPIK Reading', 'Picture to Word or Sentence', 'industrial-safety']::text[], 1, TRUE),
    ('eps-seed-r-grammar-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-grammar', 'Correct Underlined Grammar', '조사 고르기', '다음 중 밑줄 친 부분이 맞는 것은 무엇입니까?', NULL, NULL, NULL, 75, '[{"id": "A", "text": "저는 사과__가__ 먹어요."}, {"id": "B", "text": "친구__를__ 만나요."}, {"id": "C", "text": "공장__에서__ 가요."}, {"id": "D", "text": "주말__에게__ 쉬어요."}]'::jsonb, '["B"]'::jsonb, '만나다 takes an object, so 친구를 만나요 is right. It should be 사과를 먹어요, 공장에 가요 and 주말에 쉬어요.', 'easy', ARRAY['EPS_TOPIK Reading', 'Correct Underlined Grammar', 'grammar']::text[], 1, TRUE),
    ('eps-seed-r-grammar-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-grammar', 'Correct Underlined Grammar', '불규칙 동사', '다음 중 밑줄 친 부분이 맞는 것은 무엇입니까?', NULL, NULL, NULL, 75, '[{"id": "A", "text": "음악을 __듣어요__."}, {"id": "B", "text": "날씨가 __덥어요__."}, {"id": "C", "text": "창문을 __닫았어요__."}, {"id": "D", "text": "라면이 __맵어요__."}]'::jsonb, '["C"]'::jsonb, '닫다 is regular, so 닫았어요 is right. 듣다, 덥다 and 맵다 are irregular: 들어요, 더워요, 매워요.', 'medium', ARRAY['EPS_TOPIK Reading', 'Correct Underlined Grammar', 'grammar']::text[], 1, TRUE),
    ('eps-seed-r-practical-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-practical', 'Signs, Notices and Charts', '약국 안내문', '이 약국이 쉬는 날은 언제입니까?', NULL, NULL, '/api/v1/questions/assets/eps_seed_pharmacy', 75, '[{"id": "A", "text": "토요일입니다."}, {"id": "B", "text": "일요일입니다."}, {"id": "C", "text": "월요일입니다."}, {"id": "D", "text": "매일 문을 엽니다."}]'::jsonb, '["B"]'::jsonb, 'The notice says 일요일은 쉽니다: the pharmacy is closed on Sundays. It is open 9 a.m. to 7 p.m. on other days.', 'easy', ARRAY['EPS_TOPIK Reading', 'Signs, Notices and Charts', 'public-services']::text[], 1, TRUE),
    ('eps-seed-r-practical-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-practical', 'Signs, Notices and Charts', '안전 표지: 감전 주의', '이 표지의 뜻으로 알맞은 것은 무엇입니까?', NULL, NULL, '/api/v1/questions/assets/eps_seed_shock_sign', 75, '[{"id": "A", "text": "전기에 감전될 수 있습니다."}, {"id": "B", "text": "바닥이 미끄럽습니다."}, {"id": "C", "text": "담배를 피울 수 없습니다."}, {"id": "D", "text": "안전모를 써야 합니다."}]'::jsonb, '["A"]'::jsonb, '감전 주의 means "danger of electric shock". A yellow triangle is a warning sign in Korean workplaces.', 'easy', ARRAY['EPS_TOPIK Reading', 'Signs, Notices and Charts', 'industrial-safety']::text[], 1, TRUE),
    ('eps-seed-r-word-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-word-relation', 'Related Word', '관계있는 말: 월급', '다음 단어와 관계있는 것은 무엇입니까?', '월급', NULL, NULL, 75, '[{"id": "A", "text": "회사에서 받는 돈이에요."}, {"id": "B", "text": "회사에서 먹는 밥이에요."}, {"id": "C", "text": "회사에서 입는 옷이에요."}, {"id": "D", "text": "회사에서 자는 방이에요."}]'::jsonb, '["A"]'::jsonb, '월급 is the salary a worker is paid each month.', 'easy', ARRAY['EPS_TOPIK Reading', 'Related Word', 'workplace-culture']::text[], 1, TRUE),
    ('eps-seed-r-word-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-word-relation', 'Related Word', '관계있는 말: 기숙사', '다음 단어와 관계있는 것은 무엇입니까?', '기숙사', NULL, NULL, 75, '[{"id": "A", "text": "근로자가 일하는 곳이에요."}, {"id": "B", "text": "근로자가 돈을 찾는 곳이에요."}, {"id": "C", "text": "근로자가 사는 곳이에요."}, {"id": "D", "text": "근로자가 밥을 사는 곳이에요."}]'::jsonb, '["C"]'::jsonb, '기숙사 is a dormitory: company housing where workers live.', 'easy', ARRAY['EPS_TOPIK Reading', 'Related Word', 'basic-life']::text[], 1, TRUE),
    ('eps-seed-r-blank-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-blank', 'Fill in the Blank', '빈칸: 옷을 입다', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '날씨가 추우니까 두꺼운 옷을 (          ).', NULL, NULL, 75, '[{"id": "A", "text": "입으세요"}, {"id": "B", "text": "먹으세요"}, {"id": "C", "text": "타세요"}, {"id": "D", "text": "읽으세요"}]'::jsonb, '["A"]'::jsonb, 'Clothes are "worn" in Korean with 입다: 두꺼운 옷을 입으세요, "wear thick clothes".', 'easy', ARRAY['EPS_TOPIK Reading', 'Fill in the Blank', 'daily-life']::text[], 1, TRUE),
    ('eps-seed-r-blank-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-blank', 'Fill in the Blank', '빈칸: 전원을 끄다', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '기계를 청소하기 전에 반드시 전원을 (          ).', NULL, NULL, 75, '[{"id": "A", "text": "켜야 합니다"}, {"id": "B", "text": "꺼야 합니다"}, {"id": "C", "text": "사야 합니다"}, {"id": "D", "text": "빌려야 합니다"}]'::jsonb, '["B"]'::jsonb, 'Before cleaning a machine you must turn the power off: 전원을 꺼야 합니다. 켜다 is to turn on.', 'medium', ARRAY['EPS_TOPIK Reading', 'Fill in the Blank', 'industrial-safety']::text[], 1, TRUE),
    ('eps-seed-r-def-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-definition', 'Word from Description', '도구 설명: 톱', '다음 설명에 알맞은 어휘를 고르십시오.', '나무나 쇠를 자를 때 쓰는 도구입니다. 날에 뾰족한 이가 많이 있습니다.', NULL, NULL, 75, '[{"id": "A", "text": "톱"}, {"id": "B", "text": "망치"}, {"id": "C", "text": "드라이버"}, {"id": "D", "text": "줄자"}]'::jsonb, '["A"]'::jsonb, '톱 is a saw: a tool with many sharp teeth for cutting wood or metal.', 'easy', ARRAY['EPS_TOPIK Reading', 'Word from Description', 'tools-machines']::text[], 1, TRUE),
    ('eps-seed-r-def-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-definition', 'Word from Description', '도구 설명: 줄자', '다음 설명에 알맞은 어휘를 고르십시오.', '길이를 잴 때 쓰는 도구입니다. 당기면 늘어나고 버튼을 누르면 다시 감깁니다.', NULL, NULL, 75, '[{"id": "A", "text": "펜치"}, {"id": "B", "text": "줄자"}, {"id": "C", "text": "삽"}, {"id": "D", "text": "붓"}]'::jsonb, '["B"]'::jsonb, '줄자 is a tape measure: you pull it out to measure length and it rolls back in.', 'medium', ARRAY['EPS_TOPIK Reading', 'Word from Description', 'tools-machines']::text[], 1, TRUE),
    ('eps-seed-r-topic-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-topic', 'Passage Topic', '글의 주제: 설날', '다음 글을 읽고 무엇에 대한 글인지 고르십시오.', '한국에서는 설날에 떡국을 먹습니다. 떡국을 먹으면 나이를 한 살 더 먹는다고 생각합니다. 그리고 가족들이 모여서 어른들께 세배를 합니다.', NULL, NULL, 75, '[{"id": "A", "text": "설날 풍습"}, {"id": "B", "text": "음식 가격"}, {"id": "C", "text": "여행 계획"}, {"id": "D", "text": "날씨 변화"}]'::jsonb, '["A"]'::jsonb, 'The text is about New Year (설날) customs: eating 떡국 and bowing to elders (세배).', 'easy', ARRAY['EPS_TOPIK Reading', 'Passage Topic', 'korean-culture']::text[], 1, TRUE),
    ('eps-seed-r-topic-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-topic', 'Passage Topic', '글의 주제: 안전 수칙', '다음 글을 읽고 무엇에 대한 글인지 고르십시오.', '작업장에서 다치지 않으려면 규칙을 잘 지켜야 합니다. 작업 전에는 보호 장비를 착용하고, 기계가 움직일 때는 손을 넣지 않습니다. 또 바닥에 물이 있으면 바로 닦습니다.', NULL, NULL, 75, '[{"id": "A", "text": "휴가 신청"}, {"id": "B", "text": "안전 수칙"}, {"id": "C", "text": "월급 계산"}, {"id": "D", "text": "회식 장소"}]'::jsonb, '["B"]'::jsonb, 'Wearing protective equipment, keeping hands out of machines and wiping wet floors are all safety rules (안전 수칙).', 'medium', ARRAY['EPS_TOPIK Reading', 'Passage Topic', 'industrial-safety']::text[], 1, TRUE),
    ('eps-seed-r-detail-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-detail', 'Matching Statement', '회사 식당 안내', '다음 글을 읽고 내용과 같은 것을 고르십시오.', '우리 회사 식당은 아침 7시부터 8시까지, 점심 12시부터 1시까지 문을 엽니다. 저녁은 제공하지 않습니다. 식당을 이용하려면 사원증을 보여 줘야 합니다.', NULL, NULL, 75, '[{"id": "A", "text": "식당에서 저녁을 먹을 수 있습니다."}, {"id": "B", "text": "점심시간은 한 시간입니다."}, {"id": "C", "text": "식당은 하루 종일 문을 엽니다."}, {"id": "D", "text": "사원증이 없어도 식당을 이용할 수 있습니다."}]'::jsonb, '["B"]'::jsonb, 'Lunch runs from 12 to 1, so it is one hour. Dinner is not served and you must show your staff card.', 'easy', ARRAY['EPS_TOPIK Reading', 'Matching Statement', 'workplace-culture']::text[], 1, TRUE),
    ('eps-seed-r-detail-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-detail', 'Matching Statement', '사업장 변경', '다음 글을 읽고 내용과 같은 것을 고르십시오.', '외국인 근로자가 회사를 옮기고 싶으면 고용센터에 신청해야 합니다. 회사를 옮길 수 있는 횟수는 정해져 있습니다. 회사를 옮긴 후에는 새 회사와 근로계약서를 다시 써야 합니다.', NULL, NULL, 75, '[{"id": "A", "text": "회사를 옮길 때는 신청하지 않아도 됩니다."}, {"id": "B", "text": "회사는 원하는 만큼 옮길 수 있습니다."}, {"id": "C", "text": "새 회사와 근로계약서를 다시 써야 합니다."}, {"id": "D", "text": "근로계약서는 한 번만 쓰면 됩니다."}]'::jsonb, '["C"]'::jsonb, 'The text says a new employment contract (근로계약서) must be signed with the new company.', 'medium', ARRAY['EPS_TOPIK Reading', 'Matching Statement', 'laws-systems']::text[], 1, TRUE),
    ('eps-seed-r-ttp-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-text-to-picture', 'Description to Picture', '설명: 우산', '다음 설명을 읽고 알맞은 그림을 고르십시오.', '비가 오는 날에 씁니다. 펴서 머리 위에 들고 다닙니다.', NULL, NULL, 75, '[{"id": "A", "text": "우산", "imageUrl": "/api/v1/questions/assets/eps_seed_umbrella"}, {"id": "B", "text": "모자", "imageUrl": "/api/v1/questions/assets/eps_seed_cap"}, {"id": "C", "text": "장갑", "imageUrl": "/api/v1/questions/assets/eps_seed_gloves"}, {"id": "D", "text": "안경", "imageUrl": "/api/v1/questions/assets/eps_seed_glasses"}]'::jsonb, '["A"]'::jsonb, 'You open an umbrella (우산) over your head on rainy days.', 'easy', ARRAY['EPS_TOPIK Reading', 'Description to Picture', 'daily-life']::text[], 1, TRUE),
    ('eps-seed-r-ttp-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'reading', 'eps-r-text-to-picture', 'Description to Picture', '설명: 소화기', '다음 설명을 읽고 알맞은 그림을 고르십시오.', '불이 났을 때 이것으로 불을 끕니다. 안전핀을 뽑고 손잡이를 누릅니다.', NULL, NULL, 75, '[{"id": "A", "text": "망치", "imageUrl": "/api/v1/questions/assets/eps_seed_hammer"}, {"id": "B", "text": "전화기", "imageUrl": "/api/v1/questions/assets/eps_seed_phone"}, {"id": "C", "text": "소화기", "imageUrl": "/api/v1/questions/assets/eps_seed_extinguisher"}, {"id": "D", "text": "사다리", "imageUrl": "/api/v1/questions/assets/eps_seed_ladder"}]'::jsonb, '["C"]'::jsonb, 'A fire extinguisher (소화기) puts out fires: pull the safety pin, then squeeze the handle.', 'easy', ARRAY['EPS_TOPIK Reading', 'Description to Picture', 'industrial-safety']::text[], 1, TRUE),
    ('eps-seed-l-sound-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-sound', 'Choose What You Heard', '소리 구별: 공장', '들은 것을 고르십시오.', NULL, '공장', NULL, 75, '[{"id": "A", "text": "공장"}, {"id": "B", "text": "광장"}, {"id": "C", "text": "고장"}, {"id": "D", "text": "공짜"}]'::jsonb, '["A"]'::jsonb, 'You heard 공장 (factory). 광장 is a square, 고장 is a breakdown and 공짜 means free.', 'easy', ARRAY['EPS_TOPIK Listening', 'Choose What You Heard', 'job-korean']::text[], 1, TRUE),
    ('eps-seed-l-sound-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-sound', 'Choose What You Heard', '소리 구별: 시장', '들은 것을 고르십시오.', NULL, '시장', NULL, 75, '[{"id": "A", "text": "사장"}, {"id": "B", "text": "시장"}, {"id": "C", "text": "시간"}, {"id": "D", "text": "지장"}]'::jsonb, '["B"]'::jsonb, 'You heard 시장 (market). 사장 is a company owner and 시간 is time.', 'easy', ARRAY['EPS_TOPIK Listening', 'Choose What You Heard', 'daily-life']::text[], 1, TRUE),
    ('eps-seed-l-picture-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-picture', 'Listen and Choose Picture', '그림 고르기: 우유', '다음을 듣고 들은 내용과 관계있는 그림을 고르십시오.', NULL, '우유를 마셔요.', NULL, 75, '[{"id": "A", "text": "우유", "imageUrl": "/api/v1/questions/assets/eps_seed_milk"}, {"id": "B", "text": "커피", "imageUrl": "/api/v1/questions/assets/eps_seed_coffee"}, {"id": "C", "text": "물", "imageUrl": "/api/v1/questions/assets/eps_seed_water"}, {"id": "D", "text": "주스", "imageUrl": "/api/v1/questions/assets/eps_seed_juice"}]'::jsonb, '["A"]'::jsonb, 'You heard 우유를 마셔요, "I drink milk".', 'easy', ARRAY['EPS_TOPIK Listening', 'Listen and Choose Picture', 'daily-life']::text[], 1, TRUE),
    ('eps-seed-l-picture-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-picture', 'Listen and Choose Picture', '그림 고르기: 상자 옮기기', '다음을 듣고 들은 내용과 관계있는 그림을 고르십시오.', NULL, '여: 지금 뭐 해요? 남: 상자를 옮기고 있어요.', NULL, 75, '[{"id": "A", "text": "상자를 옮기는 모습", "imageUrl": "/api/v1/questions/assets/eps_seed_box"}, {"id": "B", "text": "운전하는 모습", "imageUrl": "/api/v1/questions/assets/eps_seed_car"}, {"id": "C", "text": "밥을 먹는 모습", "imageUrl": "/api/v1/questions/assets/eps_seed_noodles"}, {"id": "D", "text": "책을 읽는 모습", "imageUrl": "/api/v1/questions/assets/eps_seed_book"}]'::jsonb, '["A"]'::jsonb, 'The man says 상자를 옮기고 있어요, "I am moving boxes".', 'easy', ARRAY['EPS_TOPIK Listening', 'Listen and Choose Picture', 'job-korean']::text[], 1, TRUE),
    ('eps-seed-l-response-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-response', 'Choose the Right Reply', '대답 고르기: 고향', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, '남: 고향이 어디예요?', NULL, 75, '[{"id": "A", "text": "네팔에서 왔어요."}, {"id": "B", "text": "회사에 다녀요."}, {"id": "C", "text": "스물다섯 살이에요."}, {"id": "D", "text": "김치를 좋아해요."}]'::jsonb, '["A"]'::jsonb, '고향이 어디예요? asks where you are from, so 네팔에서 왔어요 answers it.', 'easy', ARRAY['EPS_TOPIK Listening', 'Choose the Right Reply', 'basic-life']::text[], 1, TRUE),
    ('eps-seed-l-response-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-response', 'Choose the Right Reply', '대답 고르기: 퇴근 시간', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, '여: 오늘 몇 시에 퇴근해요?', NULL, 75, '[{"id": "A", "text": "버스로 가요."}, {"id": "B", "text": "여섯 시에 퇴근해요."}, {"id": "C", "text": "어제 퇴근했어요."}, {"id": "D", "text": "공장에서 일해요."}]'::jsonb, '["B"]'::jsonb, 'The question asks what time (몇 시) you finish work today.', 'easy', ARRAY['EPS_TOPIK Listening', 'Choose the Right Reply', 'workplace-culture']::text[], 1, TRUE),
    ('eps-seed-l-next-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-next', 'What Comes Next', '이어지는 말: 기계 사용', '다음을 듣고 이어지는 말을 고르십시오.', NULL, '여: 이 기계는 위험하니까 혼자 사용하지 마세요.', NULL, 75, '[{"id": "A", "text": "네, 혼자 사용할게요."}, {"id": "B", "text": "네, 조심할게요. 반장님과 같이 사용할게요."}, {"id": "C", "text": "아니요, 기계가 없어요."}, {"id": "D", "text": "어제 기계를 샀어요."}]'::jsonb, '["B"]'::jsonb, 'Told not to use a dangerous machine alone, the right reply is to be careful and use it with the team leader.', 'medium', ARRAY['EPS_TOPIK Listening', 'What Comes Next', 'industrial-safety']::text[], 1, TRUE),
    ('eps-seed-l-next-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-next', 'What Comes Next', '이어지는 말: 병원', '다음을 듣고 이어지는 말을 고르십시오.', NULL, '남: 내일 병원에 가야 해서 오전에 일을 쉬고 싶어요.', NULL, 75, '[{"id": "A", "text": "그럼 휴가 신청서를 쓰세요."}, {"id": "B", "text": "병원이 너무 멀어요."}, {"id": "C", "text": "저도 어제 쉬었어요."}, {"id": "D", "text": "내일 오전에 일찍 오세요."}]'::jsonb, '["A"]'::jsonb, 'Asking for the morning off to see a doctor, the natural reply is to fill in a leave request (휴가 신청서).', 'medium', ARRAY['EPS_TOPIK Listening', 'What Comes Next', 'workplace-culture']::text[], 1, TRUE),
    ('eps-seed-l-number-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-number', 'Numbers, Dates and Prices', '가격: 장갑', '다음을 듣고 들은 내용과 관계있는 그림을 고르십시오.', NULL, '여: 이 장갑은 얼마예요? 남: 삼천오백 원이에요.', NULL, 75, '[{"id": "A", "text": "3,500원", "imageUrl": "/api/v1/questions/assets/eps_seed_price_3500"}, {"id": "B", "text": "5,300원", "imageUrl": "/api/v1/questions/assets/eps_seed_price_5300"}, {"id": "C", "text": "3,050원", "imageUrl": "/api/v1/questions/assets/eps_seed_price_3050"}, {"id": "D", "text": "35,000원", "imageUrl": "/api/v1/questions/assets/eps_seed_price_35000"}]'::jsonb, '["A"]'::jsonb, '삼천오백 원 is 3,500 won: 삼천 (3,000) + 오백 (500).', 'medium', ARRAY['EPS_TOPIK Listening', 'Numbers, Dates and Prices', 'numbers-time']::text[], 1, TRUE),
    ('eps-seed-l-number-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-number', 'Numbers, Dates and Prices', '날짜: 월급날', '다음을 듣고 들은 내용과 관계있는 그림을 고르십시오.', NULL, '남: 월급날이 언제예요? 여: 매달 십오 일이에요.', NULL, 75, '[{"id": "A", "text": "매달 5일", "imageUrl": "/api/v1/questions/assets/eps_seed_day_5"}, {"id": "B", "text": "매달 15일", "imageUrl": "/api/v1/questions/assets/eps_seed_day_15"}, {"id": "C", "text": "매달 25일", "imageUrl": "/api/v1/questions/assets/eps_seed_day_25"}, {"id": "D", "text": "매달 10일", "imageUrl": "/api/v1/questions/assets/eps_seed_day_10"}]'::jsonb, '["B"]'::jsonb, '십오 일 is the 15th. Payday is the 15th of every month (매달).', 'easy', ARRAY['EPS_TOPIK Listening', 'Numbers, Dates and Prices', 'numbers-time']::text[], 1, TRUE),
    ('eps-seed-l-pq-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-picture-question', 'Picture Question', '위치: 가방', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, '남: 가방은 어디에 있습니까?', '/api/v1/questions/assets/eps_seed_desk', 75, '[{"id": "A", "text": "책상 위에 있습니다."}, {"id": "B", "text": "의자 밑에 있습니다."}, {"id": "C", "text": "문 옆에 있습니다."}, {"id": "D", "text": "상자 안에 있습니다."}]'::jsonb, '["A"]'::jsonb, 'In the picture the bag is on the desk: 책상 위에 있습니다.', 'easy', ARRAY['EPS_TOPIK Listening', 'Picture Question', 'basic-life']::text[], 1, TRUE),
    ('eps-seed-l-pq-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-picture-question', 'Picture Question', '시간: 세 시', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, '여: 지금 몇 시입니까?', '/api/v1/questions/assets/eps_seed_clock3', 75, '[{"id": "A", "text": "한 시입니다."}, {"id": "B", "text": "세 시입니다."}, {"id": "C", "text": "다섯 시입니다."}, {"id": "D", "text": "열 시입니다."}]'::jsonb, '["B"]'::jsonb, 'The clock shows three o''clock: 세 시. Hours use native Korean numbers (한, 두, 세, 네...).', 'easy', ARRAY['EPS_TOPIK Listening', 'Picture Question', 'numbers-time']::text[], 1, TRUE),
    ('eps-seed-l-dialogue-1', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-dialogue', 'Dialogue Comprehension', '대화: 회식', '여자가 내일 회식에 못 가는 이유는 무엇입니까?', NULL, '남: 수니타 씨, 내일 회식이 있는데 올 수 있어요? 여: 내일은 친구 결혼식이 있어서 못 가요. 남: 그래요? 그럼 다음에 같이 가요.', NULL, 75, '[{"id": "A", "text": "몸이 아파서"}, {"id": "B", "text": "친구 결혼식이 있어서"}, {"id": "C", "text": "야근을 해야 해서"}, {"id": "D", "text": "고향에 가야 해서"}]'::jsonb, '["B"]'::jsonb, 'She says 친구 결혼식이 있어서 못 가요: she can''t come because of a friend''s wedding.', 'medium', ARRAY['EPS_TOPIK Listening', 'Dialogue Comprehension', 'workplace-culture']::text[], 1, TRUE),
    ('eps-seed-l-dialogue-2', 'eps-topik-2026-01', 'EPS_TOPIK', ARRAY['EPS_TOPIK'], 'listening', 'eps-l-dialogue', 'Dialogue Comprehension', '대화: 송금', '남자는 어디에 왔습니까?', NULL, '여: 어서 오세요. 무엇을 도와 드릴까요? 남: 고향에 돈을 보내고 싶어요. 여: 여기 신청서를 쓰고 외국인 등록증을 보여 주세요.', NULL, 75, '[{"id": "A", "text": "병원"}, {"id": "B", "text": "은행"}, {"id": "C", "text": "식당"}, {"id": "D", "text": "공항"}]'::jsonb, '["B"]'::jsonb, 'He wants to send money home and is asked for a form and his alien registration card, so he is at a bank.', 'medium', ARRAY['EPS_TOPIK Listening', 'Dialogue Comprehension', 'public-services']::text[], 1, TRUE)
ON CONFLICT (id) DO NOTHING;
