-- Migration: 000057_ielts_speaking_introduction.up.sql
-- 10 distinct, non-overlapping IELTS Speaking Part 1 (Introduction) questions across varied everyday topics.

INSERT INTO questions (
    id,
    exam_version_id,
    exam,
    skill,
    type_id,
    type_name,
    title,
    prompt,
    prep_time_seconds,
    time_limit_seconds,
    points,
    difficulty,
    tags,
    supported_exams
) VALUES
(
    'ielts-spk-intro-001',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Hometown and Local Area',
    'Where is your hometown located, and what is the most interesting thing about it? Would you recommend your hometown as a good place for young people to live? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-002',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Studies and Career Ambitions',
    'Do you currently work or study? What motivated you to choose your current subject or profession, and what do you hope to achieve in the future? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-003',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Daily Routine and Morning Habits',
    'What is your favorite part of the day, and why? Do you prefer planning your daily schedule in advance or being spontaneous? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-004',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Weather and Seasons',
    'What kind of weather do you enjoy the most? How does rainy or cold weather influence your daily activities and mood? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-005',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Mobile Phones and Social Media',
    'How often do you use social media apps during the day? Do you find it easy or difficult to stay away from your phone when you need to focus? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-006',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Food and Eating Habits',
    'What types of food do you like to eat when celebrating special occasions? Do you enjoy trying unusual or unfamiliar dishes when travelling? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-007',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Music and Musical Instruments',
    'What kind of music do you like to listen to when you want to relax? Did you ever learn to play a musical instrument when you were a child? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-008',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Public Transport and Commuting',
    'What form of transport do you rely on most frequently in your daily life? How could the public transport system in your area be made more convenient? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-009',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Sports and Physical Exercise',
    'What sports or outdoor exercises do you take part in regularly? Do you prefer playing team sports with others or exercising on your own? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-010',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Books and Reading Habits',
    'Do you prefer reading printed paper books or reading digitally on a screen? What was the last memorable book or story you read, and what made it memorable? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
)
ON CONFLICT (id) DO NOTHING;
