-- Migration: 000065_ielts_speaking_introduction_expansion.up.sql
-- 50 more IELTS Speaking Part 1 (Introduction) questions. Topics and wording
-- are distinct from 000057 and the ielts-audit practice set.

INSERT INTO questions (
    id,
    exam_version_id,
    exam,
    skill,
    type_id,
    type_name,
    title,
    prompt,
    prep_time_seconds,
    time_limit_seconds,
    points,
    difficulty,
    tags,
    supported_exams
) VALUES
(
    'ielts-spk-intro-011',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Flowers and Plants',
    'Do you keep any plants or flowers in your home? Which flower is popular in your country, and why do people like it? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-012',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Birthdays',
    'How do you usually celebrate your birthday? Is the way you celebrate now different from when you were a child? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-013',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Shoes and Footwear',
    'Do you prefer comfortable shoes or fashionable ones? How many pairs of shoes do you own, and which do you wear most? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-014',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Taking Photographs',
    'Do you like taking photos with your phone or a camera? What kinds of things do you usually photograph? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-015',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Handwriting',
    'Do you still write by hand very often? Do you think handwriting will become less important in the future? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-016',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Colours',
    'What is your favourite colour, and has it changed over the years? Are there any colours you would never wear? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-017',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'The Night Sky',
    'Do you ever look up at the stars or the moon at night? Is it easy to see the night sky clearly where you live? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-018',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Napping and Rest',
    'Do you ever take a short nap during the day? How do you feel after a nap compared with a full night of sleep? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-019',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Visiting Museums',
    'When was the last time you went to a museum? What kind of museum would you most like to visit? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-020',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Making New Friends',
    'Is it easy for you to make new friends? Where do people of your age usually meet new people? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-021',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Neighbours',
    'How well do you know your neighbours? Have your neighbours ever helped you with something? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-022',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Giving Gifts',
    'Do you enjoy choosing gifts for other people? What is the best present you have ever given someone? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-023',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Clothes and Style',
    'What kind of clothes do you feel most comfortable in? Do you change your style for work, study or special events? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-024',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Shopping Online',
    'What was the last thing you bought online? Do you prefer buying clothes online or in a physical shop? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-025',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Sweets and Desserts',
    'Do you have a sweet tooth? Which dessert from your country would you recommend to a visitor? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-026',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Coffee and Tea',
    'Do you prefer coffee or tea, and at what time of day do you usually drink it? Is there a popular café culture where you live? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-027',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Pets and Animals',
    'Have you ever had a pet? Which animal do you think makes the best companion, and why? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-028',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Going for Walks',
    'How often do you go for a walk just for pleasure? Where is your favourite place to walk? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-029',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Bicycles',
    'When did you first learn to ride a bicycle? Is cycling a popular way to get around in your city? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-030',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Swimming',
    'Can you swim, and who taught you? Do you prefer swimming in a pool or in the sea? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-031',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Watching Films',
    'Do you prefer watching films at the cinema or at home? What type of film do you choose when you want to be entertained? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-032',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Television',
    'How much television do you watch these days? Which TV programmes were popular when you were a child? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-033',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Keeping Up With the News',
    'How do you usually find out what is happening in the world? Do you prefer local news or international news? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-034',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Emails and Messages',
    'Do you send more emails or text messages in a typical week? How quickly do you usually reply to messages? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-035',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Mathematics',
    'Did you enjoy maths lessons at school? How often do you use maths in your everyday life? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-036',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Learning Languages',
    'Which languages can you speak? What is the most difficult part of learning a new language for you? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-037',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'History',
    'Are you interested in history? Which period of history would you most like to learn more about? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-038',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Drawing and Painting',
    'Did you draw or paint much when you were younger? Would you like to take an art class in the future? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-039',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Dancing',
    'Do you enjoy dancing, and on what occasions do you dance? Is there a traditional dance in your culture? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-040',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Singing',
    'Do you ever sing, for example in the shower or with friends? Have you ever tried karaoke? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-041',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Noise',
    'Is the place where you live quiet or noisy? What kinds of noise annoy you the most? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-042',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Crowded Places',
    'How do you feel when you are in a very crowded place? Which places in your city are usually the busiest? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-043',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Being on Time',
    'Are you usually punctual? How do you feel when someone keeps you waiting? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-044',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Weekends',
    'What did you do last weekend? Do you prefer busy weekends or quiet, relaxing ones? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-045',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Public Holidays',
    'Which public holiday do you look forward to most? How do people in your country usually spend their holidays? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-046',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Childhood Toys',
    'What was your favourite toy when you were a child? Do you think children today play with different toys? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-047',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Your Home',
    'Do you live in a house or an apartment? Which room in your home do you spend the most time in, and why? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-048',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Rivers and Lakes',
    'Is there a river or lake near where you live? What do people do there in their free time? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-049',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'The Beach and the Sea',
    'How often do you go to the beach? What do you like to do when you are by the sea? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-050',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Mountains and Hills',
    'Have you ever climbed a mountain or a large hill? Would you prefer a holiday in the mountains or by the coast? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-051',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Science',
    'Did you like science subjects at school? Is there any scientific topic that you find fascinating? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-052',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Advertisements',
    'Do you pay attention to advertisements you see online or on the street? Have you ever bought something because of an advert? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-053',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Watches and Time',
    'Do you wear a watch, or do you check the time on your phone? Do you think watches are more of a fashion item nowadays? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-054',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Borrowing and Lending',
    'Do you ever lend things to friends? How do you feel when someone borrows something and forgets to return it? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-055',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Picnics',
    'When did you last go on a picnic? What food do you think is ideal to take on a picnic? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-056',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Relaxation',
    'What do you usually do to relax after a long day? Do you find it easy to switch off from work or study? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-057',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Your Name',
    'Does your name have a special meaning? Would you ever consider changing your name? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-058',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Puzzles and Board Games',
    'Do you enjoy puzzles or board games? Who do you usually play games with? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-059',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Collecting Things',
    'Have you ever collected anything, such as stamps, coins or stickers? Why do you think people enjoy collecting things? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
),
(
    'ielts-spk-intro-060',
    'ielts-2026-01',
    'IELTS',
    'speaking',
    'ielts-speaking-part1',
    'Introduction',
    'Housework and Chores',
    'Which household chores do you do regularly? Is there a chore you particularly dislike? Give natural answers with relevant detail. This is a short Part 1 practice drill, not a complete 4–5 minute interview.',
    0,
    90,
    15,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Speaking', 'Part 1'],
    ARRAY['IELTS']
)
ON CONFLICT (id) DO NOTHING;
