-- Migration: 000066_ielts_writing_task2_opinion_bank.up.sql
-- 100 original IELTS Writing Task 2 Opinion (Agree or Disagree) questions.
-- No statement repeats another in this set or the existing Task 2 bank.

INSERT INTO questions (
    id,
    exam_version_id,
    exam,
    skill,
    type_id,
    type_name,
    title,
    prompt,
    explanation,
    prep_time_seconds,
    time_limit_seconds,
    points,
    difficulty,
    tags,
    supported_exams
) VALUES
(
    'ielts-wrt-opinion-001',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'School Uniforms',
    'Some people believe that school uniforms should be abolished because they restrict students'' individuality. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-002',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Free University Education',
    'University education should be free of charge for all students, regardless of their family income. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-003',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Homework in Primary Schools',
    'Primary school children should not be given any homework. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-004',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Single-Sex Schools',
    'Children learn more effectively in single-sex schools than in mixed schools. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-005',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Online Degrees',
    'A degree earned entirely online is just as valuable as one earned by attending a university in person. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-006',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Arts Versus Science Subjects',
    'Schools should give more time to science and technology subjects than to art and music. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-007',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Gap Years',
    'Young people should take a year off to work or travel before starting university. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-008',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Starting School Age',
    'Children should not begin formal schooling until they are seven years old. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-009',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Teachers'' Pay',
    'Teachers should be paid according to the exam results their students achieve. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-010',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Learning History',
    'Studying history at school is a waste of time because it has little relevance to modern life. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-011',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Vocational Training',
    'Governments should invest more in vocational training than in academic university courses. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-012',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Foreign Languages at School',
    'Every child should be required to learn at least two foreign languages at school. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-013',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Competition in Schools',
    'Encouraging competition between students does more harm than good. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-014',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Parents as Teachers',
    'Parents, rather than schools, should be responsible for teaching children good manners and behaviour. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-015',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Financial Literacy',
    'Managing personal finances should be taught as a compulsory subject in secondary schools. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-016',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Physical Education',
    'Physical education lessons should be given the same importance as academic subjects. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-017',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Studying Abroad',
    'Students gain more from studying at a university abroad than from studying in their home country. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-018',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Mobile Phones in Classrooms',
    'Mobile phones should be completely banned in schools. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-019',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Graduate Unemployment',
    'Universities should be judged mainly by how many of their graduates find jobs. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-020',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Lifelong Learning',
    'Adults should be required to update their professional qualifications throughout their working lives. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-021',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Artificial Intelligence and Jobs',
    'Artificial intelligence will create more jobs than it destroys. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-022',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Children and Screen Time',
    'Children under the age of twelve should not be allowed to own a smartphone. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-023',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Social Media Age Limits',
    'Social media platforms should be legally required to verify the age of every user. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-024',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Cashless Societies',
    'A society that uses only electronic payments would be better than one that still uses cash. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-025',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Online Anonymity',
    'People should not be allowed to post comments online without revealing their real identity. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-026',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Technology and Memory',
    'Relying on technology to store information is making people less able to think for themselves. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-027',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Self-Driving Cars',
    'Self-driving cars will make roads safer and should replace human drivers as soon as possible. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-028',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Robots in Care Homes',
    'Using robots to care for elderly people is an acceptable solution to staff shortages. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-029',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Video Calls Versus Meetings',
    'Face-to-face meetings are no longer necessary in business because of video conferencing. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-030',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Big Tech Regulation',
    'Large technology companies have too much power and should be broken up into smaller firms. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-031',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Digital Detox',
    'Everyone should spend at least one day each week without using the internet. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-032',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'E-Books Replacing Print',
    'Printed newspapers and magazines will soon disappear completely, and this is not a loss. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-033',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Plastic Bag Bans',
    'Governments should ban all single-use plastic products, even if this increases costs for consumers. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-034',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Air Travel Taxes',
    'Frequent flyers should pay much higher taxes to reduce the environmental damage caused by air travel. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-035',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Nuclear Energy',
    'Nuclear power is the most realistic solution to the world''s growing demand for clean energy. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-036',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Individual Action on Climate',
    'Individual actions, such as recycling and saving energy, make little difference to climate change. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-037',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Protecting Endangered Species',
    'Money spent on protecting endangered animals would be better spent on helping people in poverty. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-038',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Car-Free City Centres',
    'Private cars should be banned from the centres of all major cities. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-039',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Meat Consumption',
    'Governments should introduce a tax on meat to encourage people to eat more environmentally friendly diets. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-040',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Fast Fashion',
    'Cheap, mass-produced clothing is harmful to society and should be discouraged. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-041',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Environmental Education',
    'Environmental protection should be taught as a separate subject in all schools. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-042',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Wealthy Nations and Climate',
    'Rich countries should bear the full cost of tackling climate change because they caused most of the problem. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-043',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Bottled Water',
    'The sale of bottled water should be banned in places where tap water is safe to drink. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-044',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Zoos',
    'Zoos are cruel and outdated and should be closed. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-045',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Sugar Tax',
    'Governments should place a heavy tax on sugary foods and drinks to improve public health. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-046',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Free Healthcare',
    'Healthcare should be completely free for everyone and paid for through taxation. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-047',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Alternative Medicine',
    'Traditional and alternative medicines should be given the same status as modern medical treatments. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-048',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Mental Health at Work',
    'Employers should be legally responsible for the mental health of their employees. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-049',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Organ Donation',
    'Everyone should automatically be an organ donor unless they choose to opt out. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-050',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Fast Food Advertising',
    'Advertising fast food to children should be banned. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-051',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Compulsory Exercise',
    'Employers should provide paid time during the working day for staff to exercise. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-052',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Individual Responsibility for Health',
    'People who damage their health through smoking or poor diet should pay more for medical care. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-053',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Longer Life Expectancy',
    'Increasing human life expectancy is creating more problems than benefits for society. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-054',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Four-Day Working Week',
    'A four-day working week would benefit both employees and employers. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-055',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Retirement Age',
    'There should be no fixed retirement age, and people should be allowed to work as long as they wish. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-056',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Job Satisfaction Versus Salary',
    'Job satisfaction is more important than a high salary. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-057',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Equal Pay for Sport',
    'Male and female professional athletes should receive equal pay and prize money. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-058',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Universal Basic Income',
    'Governments should give every adult citizen a basic income, whether or not they work. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-059',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Changing Careers',
    'It is better to stay in one career for life than to change jobs frequently. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-060',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Unpaid Internships',
    'Unpaid internships are unfair and should be made illegal. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-061',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Entrepreneurship',
    'Starting your own business is a better path to success than working for a large company. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-062',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'High Salaries for Executives',
    'The salaries of company directors should be limited by law. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-063',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Tipping Culture',
    'Tipping in restaurants should be replaced by paying service staff a higher fixed wage. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-064',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Minimum Wage',
    'Raising the minimum wage causes more harm than good because it leads to job losses. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-065',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Elderly Care',
    'Adult children should be responsible for looking after their elderly parents rather than relying on the state. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-066',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Parenting Classes',
    'All parents should be required to attend parenting courses before their first child is born. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-067',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Children and Household Chores',
    'Children should be paid for helping with household chores. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-068',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Living Alone',
    'The growing number of people living alone is having a negative effect on society. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-069',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Stay-at-Home Fathers',
    'It is just as natural for fathers as for mothers to stay at home and raise children. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-070',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Celebrity Role Models',
    'Celebrities have a duty to set a good example to young people. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-071',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Volunteering',
    'Unpaid volunteer work should be a requirement for all adults who are able to do it. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-072',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Wealth and Happiness',
    'Money is the most important factor in achieving happiness. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-073',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Youth and Politics',
    'The voting age should be lowered to sixteen. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-074',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Community Life',
    'People today are less involved in their local communities than in the past, and this is a serious problem. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-075',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Capital Punishment',
    'The death penalty is an effective way to reduce serious crime. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-076',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Prison Versus Rehabilitation',
    'Education and job training in prisons are more effective at reducing crime than longer prison sentences. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-077',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Surveillance Cameras',
    'The use of surveillance cameras in public places is an invasion of privacy. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-078',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Compulsory Voting',
    'Voting in national elections should be compulsory. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-079',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Military Service',
    'All young people should be required to complete a period of national or military service. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-080',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Spending on the Arts',
    'Governments should not spend public money on the arts when there are more urgent needs such as health and education. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-081',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Space Exploration Spending',
    'The money spent on space exploration would be better used to solve problems on Earth. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-082',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Gun Ownership',
    'Private citizens should not be allowed to own firearms. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-083',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Juvenile Crime',
    'Teenagers who commit serious crimes should be punished in the same way as adults. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-084',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Taxing the Rich',
    'People with very high incomes should pay a much larger share of their earnings in tax. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-085',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Global Language',
    'The dominance of English as a global language is a threat to local cultures. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-086',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'International Tourism',
    'The disadvantages of international tourism for local communities outweigh the benefits. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-087',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Preserving Old Buildings',
    'Old buildings should be protected by law, even if this prevents new development. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-088',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Censorship of Films',
    'Films and video games containing violence should be strictly censored. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-089',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'News Reporting',
    'The news media focus too much on negative stories. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-090',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Museum Entry Fees',
    'Museums and art galleries should be free for everyone to visit. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-091',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Global Brands',
    'The spread of international brands and fast food chains is making countries around the world too similar. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-092',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Traditional Skills',
    'Traditional crafts and skills should be supported by the government even if there is little demand for them. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-093',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Reality Television',
    'Reality television programmes have no educational or cultural value. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-094',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Watching Versus Playing Sport',
    'Watching sport on television has little value compared with taking part in it. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-095',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Public Transport Fares',
    'Public transport should be free for everyone in large cities. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-096',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'High-Rise Housing',
    'Building high-rise apartment blocks is the best solution to housing shortages in cities. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-097',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Moving to the Countryside',
    'Governments should encourage people to move from large cities to rural areas. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-098',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Cycling Infrastructure',
    'Cities should spend more on cycle lanes than on building new roads for cars. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-099',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Home Ownership',
    'Owning a home is a better choice than renting for young people. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
),
(
    'ielts-wrt-opinion-100',
    'ielts-2026-01',
    'IELTS',
    'writing',
    'ielts-writing-task2-opinion',
    'Opinion / Agree or Disagree',
    'Outdoor Advertising',
    'Outdoor advertising such as billboards should be banned from city streets. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience. Write at least 250 words. Suggested time: 40 minutes.',
    'State a clear position, develop relevant reasons and examples, address qualifications where useful, and sustain the position through the conclusion. There is no preferred opinion.',
    0,
    2400,
    25,
    'medium',
    ARRAY['Original practice', 'IELTS', 'Writing', 'Task 2'],
    ARRAY['IELTS']
)
ON CONFLICT (id) DO NOTHING;
