"""50 original Repeat Sentence items for PTE Speaking bank 4a.

Each sentence is 8 to 15 words, of the kind heard in the live task: a remark
from a lecture, a tutorial or campus announcement, or a plain statement of an
academic fact. The explanation points out the words to stress and where to
pause.
"""


def _item(title, sentence, explanation):
    return {"title": title, "sentence": sentence, "explanation": explanation}


RS_ITEMS = [
    _item("Moving a revision session", "This week's revision session has been moved to the large room on the second floor.",
          "Keep 'revision session' together and stress 'second floor'."),
    _item("Checking sources", "Always check when a website was last updated before you cite it in an essay.",
          "Stress 'last updated' and pause very slightly before 'before'."),
    _item("Handing in coursework late", "Coursework handed in after the deadline will lose five marks for each day it is late.",
          "Say 'five marks' clearly and keep 'for each day it is late' flowing."),
    _item("Borrowing laptops", "Students can borrow a laptop from the help desk for up to four hours.",
          "Stress 'laptop' and 'four hours', and link 'help desk' smoothly."),
    _item("Fresh water in ice", "Most of the fresh water on Earth is frozen in ice sheets and glaciers.",
          "Stress 'fresh water' and 'frozen'. Say 'glaciers' as 'GLASS-ee-ers' or 'GLAY-see-ers'."),
    _item("Group presentation length", "Each group will have fifteen minutes to present, followed by five minutes of questions.",
          "Contrast 'fifteen minutes' with 'five minutes', with a short pause after 'present'."),
    _item("Reading before a seminar", "Please read the first two chapters before Thursday's seminar so we can discuss them properly.",
          "Group 'the first two chapters' and stress 'Thursday's seminar'."),
    _item("Early trade routes", "Many of the world's oldest cities grew up along rivers and trade routes.",
          "Stress 'oldest cities' and link 'rivers and trade routes'."),
    _item("A survey sample", "The survey was completed by just over two thousand adults across the country.",
          "Say 'just over two thousand' as one phrase."),
    _item("Office hours change", "My office hours this term are on Tuesday and Wednesday afternoons from two until four.",
          "Stress the days and keep 'from two until four' clear at the end."),
    _item("Referencing guide", "A guide to the referencing style used in this department is available online.",
          "Keep 'referencing style' together and stress 'online' at the end."),
    _item("How bees communicate", "Honeybees use a kind of dance to tell each other where to find food.",
          "Stress 'dance' and 'where to find food'."),
    _item("Library quiet floor", "Mobile phones should be switched to silent on the third floor of the library.",
          "Stress 'silent' and 'third floor', linking 'switched to' smoothly."),
    _item("Interest rates and borrowing", "When interest rates rise, businesses usually become more cautious about borrowing money.",
          "Pause briefly after 'rise' and stress 'more cautious'."),
    _item("Field trip meeting point", "The coach for the field trip will leave from outside the main entrance at eight.",
          "Keep 'the coach for the field trip' as one unit and stress 'eight'."),
    _item("Primary and secondary data", "Primary data is information that researchers collect themselves rather than taking it from others.",
          "Stress 'Primary data' and 'themselves', pausing slightly before 'rather'."),
    _item("Sleep and exam performance", "Students who sleep well before an exam tend to remember more of what they studied.",
          "Stress 'sleep well' and 'remember more'."),
    _item("Registration for modules", "Optional modules for next year must be chosen by the end of this month.",
          "Stress 'Optional modules' and 'end of this month'."),
    _item("Photosynthesis and light", "Plants use the energy in sunlight to turn water and carbon dioxide into sugar.",
          "Link 'carbon dioxide' smoothly and stress 'sugar' at the end."),
    _item("Draft feedback", "If you send me a draft by Friday, I will give you some written feedback.",
          "Pause after 'Friday' and stress 'written feedback'."),
    _item("Population growth in cities", "Most of the growth in world population this century is expected to happen in cities.",
          "Stress 'this century' and 'cities'."),
    _item("Laboratory safety glasses", "Safety glasses must be worn at all times while you are working in the laboratory.",
          "Stress 'at all times' and say 'laboratory' as 'la-BOR-a-tree'."),
    _item("The history of writing", "Writing appears to have been invented independently in several different parts of the world.",
          "Stress 'independently' and 'several different parts'."),
    _item("Careers fair", "More than sixty employers are expected to attend the careers fair in the sports hall.",
          "Say 'more than sixty employers' as one phrase and stress 'sports hall'."),
    _item("Measuring unemployment", "Unemployment figures only include people who are actively looking for work.",
          "Stress 'only' and 'actively looking'."),
    _item("Word limits in essays", "Essays that go more than ten per cent over the word limit may be penalised.",
          "Keep 'ten per cent over the word limit' together and stress 'penalised'."),
    _item("Volcanic soils", "The soil around many volcanoes is extremely fertile, which is why farmers settle there.",
          "Pause after 'fertile' and stress 'farmers settle there'."),
    _item("Printing credits", "Every student receives some free printing credit at the start of each term.",
          "Stress 'free printing credit' and 'each term'."),
    _item("Interviews in research", "Interviews allow researchers to explore people's opinions in much greater depth than questionnaires.",
          "Contrast 'Interviews' with 'questionnaires' and stress 'much greater depth'."),
    _item("The speed of light", "Light from the Sun takes a little over eight minutes to reach the Earth.",
          "Say 'a little over eight minutes' as one phrase."),
    _item("Booking study rooms", "Group study rooms can be booked up to a week in advance through the library website.",
          "Stress 'up to a week in advance' and link 'library website'."),
    _item("Supply and demand", "When supply falls and demand stays the same, prices will normally go up.",
          "Contrast 'supply falls' with 'demand stays the same' and stress 'go up'."),
    _item("Guest lecture on architecture", "Tonight's guest lecture will look at how architects design buildings for hot climates.",
          "Stress 'guest lecture' and 'hot climates'."),
    _item("Bilingual children", "Children who grow up with two languages rarely confuse them for very long.",
          "Stress 'two languages' and 'rarely'."),
    _item("Returning books", "Books that have been reserved by another reader must be returned within three days.",
          "Stress 'reserved' and 'three days'."),
    _item("Ancient roads", "The Romans built more than eighty thousand kilometres of paved roads across their empire.",
          "Say 'eighty thousand kilometres' clearly and stress 'paved roads'."),
    _item("Plagiarism software", "All essays are checked by software that compares them with published work and other submissions.",
          "Pause after 'software' and keep the last phrase flowing."),
    _item("A change of lecturer", "Dr Evans will be teaching this module for the rest of the term.",
          "Say 'Dr' as 'Doctor' and stress 'the rest of the term'."),
    _item("Migrating birds", "Some small birds fly thousands of kilometres every autumn to spend the winter in Africa.",
          "Stress 'thousands of kilometres' and 'Africa'."),
    _item("Student accommodation", "Applications for university accommodation for next year open on the first of March.",
          "Stress 'university accommodation' and 'first of March'."),
    _item("Marketing and brands", "A strong brand allows a company to charge more than its competitors for similar products.",
          "Stress 'strong brand' and 'charge more'."),
    _item("Tides and the Moon", "Tides are caused mainly by the pull of the Moon on the oceans.",
          "Stress 'mainly' and 'the Moon'."),
    _item("Attendance requirement", "You need to attend at least eighty per cent of the tutorials to pass this course.",
          "Say 'at least eighty per cent' as one phrase."),
    _item("Handwriting and memory", "Some studies suggest that taking notes by hand helps students remember lectures better.",
          "Stress 'by hand' and 'remember'."),
    _item("Statistics support", "Free drop-in sessions on statistics are held in the maths centre every Monday.",
          "Link 'drop-in sessions' and stress 'every Monday'."),
    _item("Coral and water temperature", "Coral reefs are very sensitive to even small increases in sea temperature.",
          "Stress 'very sensitive' and 'small increases'."),
    _item("Final-year projects", "Final-year students should agree a project topic with their supervisor before the winter break.",
          "Keep 'agree a project topic' together and stress 'winter break'."),
    _item("Oral history", "Oral history records the memories of ordinary people in their own words.",
          "Stress 'ordinary people' and 'their own words'."),
    _item("Sports centre membership", "Students can join the university sports centre at a reduced rate for the whole year.",
          "Stress 'reduced rate' and 'whole year'."),
    _item("Wind speed and height", "Wind speeds are generally higher and steadier at greater heights above the ground.",
          "Stress 'higher and steadier' and 'greater heights'."),
]
