"""Generator script to produce polished 50 SWT items with passages 150-250 words,
single-sentence summaries (5-75 words), and clear plain English titles.
"""

from pathlib import Path
import re

# We will write out the complete, rich 50 SWT items directly into swt.py
ROOT = Path(__file__).resolve().parent

# Let's inspect existing SWT_ITEMS and enrich each passage to 160-220 words
from swt import SWT_ITEMS

enriched = []
for item in SWT_ITEMS:
    title = item['title']
    p = item['passage']
    ans = item['model_answer']
    exp = item['explanation']
    
    # Check current word count
    words = p.split()
    if len(words) < 155:
        # Add an informative, fact-based supplementary sentence expanding on the real-world application or technical nuance
        supplementary = {
            "Acoustic Seafloor Thermometry": "Continuous long-baseline acoustic thermometry also filters out short-term internal wave noise, yielding stable decade-long climatological trend lines across entire ocean basins. These empirical acoustic measurements provide physical oceanographers with essential benchmark constraints to validate and refine global coupled climate models.",
            "Urban Bioswale Stormwater Retention": "Over time, accumulated organic matter within the bioswale matrix enhances soil cation exchange capacity, allowing root microbes to immobilize toxic trace metals permanently. Civil engineers increasingly integrate these natural drainage networks into metropolitan street designs to replace deteriorating concrete pipes with adaptive green infrastructure.",
            "Anaerobic Digestion of Municipal Waste": "Methane yields from municipal digestion reactors are further optimized by co-digesting food waste with residential sewage sludge, which balances the carbon-to-nitrogen ratio within the bacterial broth. State-of-the-art closed-loop facilities recirculate process heat to maintain thermophilic temperatures, ensuring complete pathogen destruction during continuous operation.",
            "Precision Drip Irrigation Systems": "Automated moisture probes embedded across the field monitor root-zone matric potential in real time, triggering automated irrigation cycles only when soil moisture falls below threshold levels. This closed-loop precision management prevents nutrient leaching below the root zone, safeguarding regional groundwater aquifers from nitrate contamination.",
            "Cross-Laminated Timber in Construction": "Precision computer-controlled milling machines cut conduit channels and window openings into structural panels with sub-millimeter precision before panels leave the factory. This high degree of prefabrication drastically cuts on-site construction timelines while virtually eliminating raw material waste on commercial building sites.",
            "Satellite Synthetic Aperture Radar": "By employing multiple microwave polarization modes, polarimetric radar distinguishes between various surface textures, separating smooth open water from rough pack ice and bare soil. Orbiting constellations of small radar satellites now provide rapid revisit times, ensuring disaster response agencies receive near-real-time flood extent maps during torrential monsoon downpours.",
            "Marine Seagrass Carbon Sequestration": "In addition to accumulating autochthonous organic carbon from their own leaves, seagrass canopies act as physical sediment traps, capturing allochthonous particulate carbon transported from terrestrial river mouths. Restoring degraded seagrass meadows therefore yields dual benefits, reviving productive coastal nurseries while expanding long-term oceanic blue carbon reservoirs.",
            "District Heating from Geothermal Fluid": "Multi-stage heat pumps installed at central distribution substations extract residual thermal energy from return lines before the brine is reinjected, maximizing overall system thermodynamic efficiency. Decades of operational experience in volcanic districts demonstrate that maintaining balanced injection and withdrawal rates preserves geothermal reservoir pressure for generations.",
            "Seed Dormancy and Agricultural Resilience": "Molecular biologists have identified specific transcription factors that regulate dormancy release, enabling the precise genetic editing of sensitivity to ambient moisture and temperature. Applying these insights to commercial grain cultivars prevents catastrophic field losses from premature grain sprouting during prolonged periods of damp pre-harvest weather.",
            "Atmospheric River Water Transport": "High-altitude reconnaissance aircraft deploy dropsondes directly into approaching atmospheric rivers to measure humidity, wind velocity, and temperature profiles across the vapor plume. Feeding these real-time atmospheric transects into numerical weather models significantly improves landfall forecasts, allowing flood control operators to manage reservoir storage proactively.",
            "Seismic Base Isolation for Architecture": "To prevent excessive lateral swaying during prolonged ground resonance, civil engineers install viscous fluid dampers alongside base isolation bearings to dissipate vibrational energy smoothly. Post-earthquake structural inspections across seismically active nations confirm that base-isolated facilities sustain negligible non-structural damage, protecting delicate medical machinery and laboratory equipment.",
            "Constructed Wetlands for Wastewater Remediation": "In colder climates, subsurface flow wetlands prevent ice formation by routing wastewater entirely beneath a dry gravel mulch layer, maintaining active microbial biofilm communities throughout winter. These natural treatment systems also create valuable peri-urban wildlife habitats, supporting diverse populations of migratory waterfowl and beneficial pollinating insects.",
            "Cryogenic Air Separation for Pure Nitrogen": "Modern cryogenic plants incorporate internal compression cycles and vacuum-insulated cold boxes to minimize thermal heat leaks from ambient air. The immense economies of scale achieved by cryogenic distillation make it the primary technology supporting the global production of synthetic ammonia fertilizers and ultra-pure electronics chemicals.",
            "Cover Cropping in Regenerative Agriculture": "Terminating cover crops with roller-crimpers leaves an unbroken layer of organic mulch across the soil surface, retaining soil moisture and cooling soil temperatures during hot summer months. Agronomists observe that fields managed with continuous cover cropping exhibit higher earthworm populations and superior aggregate stability compared to conventionally tilled ground.",
            "Urban Tree Canopies and Microclimate Modulation": "Selecting climate-resilient tree species with high drought tolerance ensures that urban canopies continue to provide cooling benefits during prolonged heatwaves without depleting municipal water reserves. Municipal urban planners increasingly deploy thermal satellite imaging to identify canopy-deficient neighborhoods, directing tree-planting investments toward areas facing the highest heat vulnerability.",
            "Deep Sea Siliceous Sponge Reef Growth": "Benthic landers deployed on sponge mounds record strong diurnal tidal currents that sweep away fine silt, keeping hexactinellid filter tissues clean and delivering fresh supplies of suspended bacteria. Protecting these fragile deep-sea formations from bottom-trawl fishing gear is essential, as the slow-growing silica skeletons require centuries to recover from mechanical disturbance.",
            "Biochar for Soil Remediation and Carbon Storage": "The high surface area and chemical functional groups of biochar particles allow them to bind toxic heavy metal cations in contaminated soils, preventing plant uptake of industrial pollutants. Blending biochar with mature compost before field application inoculates the porous charcoal with beneficial bacteria, accelerating soil structural improvements and crop root establishment.",
            "Pedestrian Street Orientation and Urban Livability": "Transitioning urban streets into pedestrian-focused corridors also facilitates low-carbon micromobility options like cycling and cargo-bike deliveries, which can operate safely away from heavy automotive traffic. Long-term municipal studies indicate that vibrant walkable streets foster greater civic engagement and physical activity, yielding measurable public health improvements across urban populations.",
            "Dendrochronological Analysis in Paleoclimatology": "Isotopic analysis of carbon and oxygen ratios within individual growth rings provides complementary data on historical cloud cover, stomatal conductance, and atmospheric vapor pressure deficits. Combining ring-width chronologies with isotopic fingerprints allows paleoclimatologists to disentangle temperature influences from drought stress in ancient forest ecosystems.",
            "Molten Salt Thermal Storage in Solar Energy": "Corrosion-resistant nickel alloy piping and specialized pump seals ensure that molten nitrate salts circulate safely through heat exchangers without degrading system components over decades of thermal cycling. Developing commercial molten-salt storage represents a major milestone in transitioning electricity grids away from fossil fuel peaker plants toward continuous renewable power.",
            "Biological Control in Greenhouse Horticulture": "Specialized banker plant systems provide alternative pollen and nectar sources within the greenhouse, allowing populations of beneficial predatory insects to persist even when pest numbers drop to low levels. This continuous biological presence prevents secondary pest flare-ups, creating a resilient, self-sustaining ecological equilibrium within commercial glasshouses.",
            "Subterranean Cable Networks for Urban Grids": "Advanced partial discharge monitoring instruments detect microscopic insulation degradation inside underground cables long before electrical flashovers occur, enabling scheduled preventive maintenance. Modern trenchless horizontal directional drilling techniques also allow utilities to install underground conduits beneath existing roads and rivers without disrupting surface vehicular traffic.",
            "Acoustic Wildlife Monitoring in Conservation": "Combining passive acoustic monitoring with edge-computing microprocessors allows acoustic sensors to recognize target endangered bird calls locally and transmit real-time alerts via satellite networks. Wildlife rangers utilize these automated acoustic alerts to detect illegal poaching gunshots or unauthorized chainsaws in remote national parks immediately.",
            "Industrial Waste Heat Recovery Systems": "Thermally activated absorption chillers can also convert low-temperature industrial waste heat into chilled water for facility air conditioning or industrial refrigeration, displacing electricity-driven cooling compressors. Maximizing industrial waste heat capture represents one of the most cost-effective strategies for heavy manufacturing plants to achieve net-zero operational targets.",
            "Microbial Fuel Cells for Wastewater Energy": "Synthesizing three-dimensional graphene foam and carbon nanotube anodes drastically increases the available surface area for bacterial colonization, boosting power density in pilot-scale microbial fuel cells. In addition to treating municipal sewage, microbial fuel cells can remediate toxic wastewater from food processing and brewery facilities while generating on-site electricity.",
            "River Meander Floodplain Reconnection": "Restored riparian wetlands act as natural sediment sinks, capturing upstream agricultural runoff and preventing phosphorus accumulation in downstream lakes and coastal estuaries. Reconnected floodplains also restore natural hydrological connectivity, allowing juvenile salmon and riverine amphibians to access productive seasonal nursery habitats safely.",
            "Satellite Laser Altimetry in Glaciology": "Advanced photon-counting detector technology enables modern spaceborne laser instruments to measure surface elevations across steep, crevassed alpine terrain where older radar altimeters suffered signal distortion. These comprehensive laser surveys reveal that accelerating ice mass discharge from peripheral mountain glaciers contributes significantly to near-term global sea level rise.",
            "Microalgae Cultivation for Biodiesel Production": "Residual lipid-extracted algal biomass is rich in proteins and carbohydrates, serving as an exceptional high-protein livestock feed or as an anaerobic digestion feedstock to generate supplementary biogas. This integrated biorefinery model monetizes every fraction of the harvested microalgae, significantly improving the overall economic viability of industrial algal biofuel production.",
            "Seismic Dam Safety and Early Warning Systems": "High-precision satellite radar interferometry complements internal dam sensors by detecting subtle millimeter-scale crest deflections and foundation settlements across entire reservoir rims. Geotechnical engineering teams combine real-time sensor data with dynamic finite-element models to simulate dam behavior under various earthquake scenarios, ensuring structural safety protocols remain up to date.",
            "Soil Bioengineering for Slope Stabilization": "Establishing deep-rooted native shrub matrices along railway corridors and highway embankments also intercepts surface runoff, preventing roadside mudslides and reducing municipal ditch clearance costs. As root networks deepen over successive growing seasons, they anchor permeable soil layers to underlying bedrock, creating long-lasting, self-repairing geotechnical stabilization.",
            "Autonomous Underwater Gliders for Ocean Profiling": "Modern ocean gliders are equipped with acoustic Doppler profilers and chemical sensors, measuring ocean current velocities and oceanic carbon chemistry across remote frontal boundaries. Long-endurance glider surveys provide oceanographers with high-resolution physical datasets that bridge the observational scale gap between point-source research moorings and broad-scale satellite overpasses.",
            "Geopolymer Cement from Coal Fly Ash": "Because geopolymer synthesis relies on low-energy chemical polymerization rather than high-temperature kiln firing, manufacturing geopolymer concrete consumes significantly less embodied energy than traditional Portland formulations. Developing standardized international engineering testing protocols has accelerated the commercial adoption of geopolymer concrete for precast structural beams and railway sleepers.",
            "Pollinator Corridors in Agricultural Landscapes": "Establishing perennial wildflower strips between cultivated fields also creates microclimates that buffer beneficial insects against agricultural pesticide drift and extreme weather events. Long-term agronomic trials indicate that field-scale pollinator corridors improve soybean and canola crop yields while significantly enhancing landscape-level wild bee biodiversity.",
            "Clay Extraction of Lithium Hydroxide": "Selective acid leaching and membrane electrodialysis extract high-purity lithium hydroxide from continental hectorite clay deposits without extensive evaporating ponds. Developing commercial clay-based refining processes transforms mineral supply chains, converting domestic sedimentary deposits into battery-grade precursor chemicals while shortening transportation distances.",
            "Thermal Mass in Earth-Sheltered Architecture": "Earth-sheltered structures also exhibit extraordinary aerodynamic resistance to severe windstorms and hurricanes, as submerged wall profiles deflect destructive wind shear over the structure without catching eaves. Integrating south-facing clerestory glazing and reflective light tubes brings natural daylight deep into subterranean living spaces, ensuring bright, well-ventilated interior architecture.",
            "Meromictic Lake Stratification Dynamics": "Because oxygen is completely absent in the deep monimolimnion, benthic organisms cannot survive to disturb bottom sediments, allowing microscopic fossil pollen, diatom frustules, and charcoal flecks to settle in pristine chronological sequence. Paleolimnologists extract continuous sediment cores from meromictic lakes to reconstruct past wildfire regimes and regional vegetation shifts across tens of thousands of years.",
            "Recyclable Thermoplastic Wind Turbine Blades": "At the end of their operational lifespan, thermoplastic composite blades can be shredded and dissolved in mild organic solvents, separating intact fiberglass reinforcements from dissolved polymer resins. This gentle chemical recycling process preserves the tensile strength of the recovered structural glass fibers, allowing them to be remanufactured into automotive panels or new wind energy infrastructure.",
            "Riparian Buffers for Agricultural Watersheds": "Vegetated riparian zones also stabilize fragile riverbank soils against hydraulic scour during seasonal high-flow events, preventing large-scale bank collapse and agricultural land loss. Establishing continuous wooded riparian corridors across rural catchments provides shaded migration corridors for terrestrial wildlife while protecting downstream drinking water reservoirs from agricultural contamination.",
            "Acoustic Sensors for Precision Livestock Welfare": "Directional microphone arrays mounted in barns isolate individual animal sounds, allowing automated algorithms to pinpoint the exact location of distressed animals in high-density housing units. Implementing early acoustic detection protocols substantially reduces the volume of therapeutic antibiotics required during disease outbreaks by enabling targeted, localized treatment of infected animals.",
            "Geothermal Energy in Greenhouse Horticulture": "Directing low-temperature geothermal fluids through automated soil-warming loops accelerates the germination and root development of high-value horticultural seedlings during cold winter months. Operating geothermal greenhouse facilities independent of commercial fossil fuel distribution networks shields growers from unexpected heating fuel price spikes during extreme winter freezes.",
            "Moisture Management in Massive Timber Buildings": "Applying temporary hydrophobic sealants to end-grain surfaces and taping structural panel joints protects exposed cross-laminated timber decks from rain ponding during floor-by-floor building erection. Incorporating moisture-monitoring telemetry systems within completed structural wall cavities provides facility managers with ongoing assurance that building envelopes remain completely dry throughout decades of service.",
            "Biomimetic Sharkskin Marine Antifouling Coatings": "Unlike soft silicone foul-release coatings that can tear when oceanic vessels navigate shallow waterways or rub against harbor pilings, textured biomimetic fluoropolymer surfaces exhibit high mechanical abrasion resistance. Applying non-toxic textured coatings to commercial shipping fleets cuts global maritime fuel consumption by millions of tons annually without releasing copper contaminants into marine food webs.",
            "Hyperspectral Remote Sensing of Forest Canopy Health": "Integrating airborne hyperspectral imagery with LiDAR canopy height models provides forest managers with three-dimensional structural and biochemical profiles of entire forest watersheds. These high-resolution remote-sensing maps guide targeted forestry sanitation cuts that remove infested timber before bark beetle outbreaks can spread across regional forest reserves.",
            "Biogeochemical Cycles in Coastal Estuarine Sediments": "Active bioturbation by burrowing marine polychaetes and bivalves introduces oxygen pulses into shallow sediment layers, creating complex micro-scale mosaics of oxic and anoxic sediment zones. These fluctuating redox interfaces accelerate coupled nitrification-denitrification processes, permanently converting terrestrial agricultural fertilizer runoff into harmless atmospheric nitrogen gas before it reaches the open ocean.",
            "Permeable Concrete Pavement in Urban Hydrology": "Installing permeable interlocking concrete pavers along pedestrian sidewalks and public parking lots also reduces the formation of dangerous winter black ice, as surface meltwater drains immediately before refreezing. Periodic vacuum sweeping clears accumulated fine dust from joint voids, maintaining high hydrological infiltration rates and ensuring decades of reliable flood protection.",
            "Ancient Agricultural Terracing and Soil Conservation": "The dry-stacked stone retaining walls of traditional agricultural terraces allow excess soil water to drain freely through wall crevices, preventing destructive hydrostatic pressure buildup behind walls during torrential mountain storms. Restoring abandoned mountain terraces revives sustainable traditional agroforestry systems, enhances slope stability, and protects downstream mountain valleys from catastrophic debris flows.",
            "Recycling Silicon Waste in Photovoltaic Manufacturing": "Recovering high-purity silicon powders from sawing slurry using advanced centrifugal hydrocyclones and chemical etching eliminates the need to process virgin quartz ore through energy-intensive carbothermic reduction furnaces. Implementing circular kerf recycling loops within solar wafer manufacturing facilities slashes industrial carbon footprints while significantly lowering the levelized cost of solar electricity generation.",
            "Managed Aquifer Recharge for Groundwater Security": "Equipping artificial infiltration basins with vegetated soil biofilters removes residual trace organic contaminants and heavy metals from stormwater before water enters deep regional aquifer systems. Operating managed aquifer recharge programs provides agricultural basins with large-scale seasonal water storage capacity, ensuring stable agricultural irrigation supplies throughout multi-year drought cycles.",
            "Biofilm Growth in Potable Water Networks": "Municipal water utilities deploy online optical sensors and real-time ATP bioluminescence assays to detect the early stages of biofilm formation across potable water pipe networks. Combining optimized chloramine disinfection residuals with regular unidirectional flushing regimes successfully suppresses microbial regrowth, ensuring consistent tap water quality and safeguarding public health.",
            "Aerodynamic Noise Mitigation on High-Speed Trains": "Wind tunnel testing confirms that installing porous sound-absorbing panels within wheel bogie cavities and smoothing pantograph support linkages significantly dampens aerodynamic vortex noise at extreme operating speeds. Reducing aerodynamic wayside noise enables high-speed rail lines to expand train operating frequencies through densely populated residential transit corridors without exceeding municipal noise ordinances.",
        }
        extra_sentence = supplementary.get(title, "")
        if extra_sentence:
            p = p.rstrip() + " " + extra_sentence
            
    enriched.append({
        "title": title,
        "passage": p,
        "model_answer": ans,
        "explanation": exp,
    })

output_lines = [
    '"""50 Original Summarize Written Text (SWT) items for PTE Writing Batch 3 (Migration 000088).',
    '',
    'Constraints:',
    '  - context_passage: 150-300 words, informative academic / general interest, established facts.',
    '  - model_answer: exactly ONE sentence (5-75 words, 1 terminal period, no semicolon tricks).',
    '  - explanation: key ideas that an effective summary must capture.',
    '  - No clash with live SWT, live reading topics, or previous batches.',
    '"""',
    '',
    'SWT_ITEMS = ['
]

for item in enriched:
    output_lines.append('    {')
    output_lines.append(f'        "title": {repr(item["title"])},')
    output_lines.append(f'        "passage": {repr(item["passage"])},')
    output_lines.append(f'        "model_answer": {repr(item["model_answer"])},')
    output_lines.append(f'        "explanation": {repr(item["explanation"])},')
    output_lines.append('    },')

output_lines.append(']')
output_lines.append('')
output_lines.append('assert len(SWT_ITEMS) == 50, f"Expected 50 SWT items, got {len(SWT_ITEMS)}"')
output_lines.append('')

(ROOT / 'swt.py').write_text('\n'.join(output_lines), encoding='utf-8')
print("Successfully generated enriched swt.py!")
