"""Dialogue Comprehension, part two. Same format as dialogue_a."""

DIALOGUES_B = [
    ("남: 실례합니다. 화장실이 어디에 있어요? 여: 이 복도 끝에서 오른쪽으로 가세요. 남: 엘리베이터 옆이에요? 여: 네, 엘리베이터 바로 옆이에요.",
     "Man: Excuse me. Where is the toilet? Woman: Go to the end of this corridor and turn right. Man: Is it next to the lift? Woman: Yes, right next to the lift.",
     "화장실은 어디에 있습니까?", "Where is the toilet?",
     [("복도 끝 오른쪽, 엘리베이터 옆", "At the end of the corridor on the right, next to the lift"), ("복도 끝 왼쪽", "At the end of the corridor on the left"), ("계단 아래", "Under the stairs"), ("이 층 사무실 안", "Inside the office on the second floor")],
     "복도 끝에서 오른쪽 … 엘리베이터 바로 옆: end of the corridor, right, beside the lift.", "basic-life", "easy"),
    ("여: 이번 휴가 때 고향에 가요? 남: 아니요, 비행기표가 너무 비싸서 못 가요. 여: 그럼 뭐 할 거예요? 남: 부산에 사는 친구 집에 놀러 가려고요.",
     "Woman: Are you going home for this holiday? Man: No, the plane tickets are too expensive, so I can't. Woman: Then what will you do? Man: I'm going to visit a friend who lives in Busan.",
     "남자가 고향에 가지 않는 이유는 무엇입니까?", "Why isn't the man going home?",
     [("비행기표가 비싸서", "Plane tickets are too expensive."), ("휴가가 짧아서", "The holiday is too short."), ("일이 많아서", "He has too much work."), ("친구가 한국에 와서", "A friend is coming to Korea.")],
     "비행기표가 너무 비싸서 못 가요: the tickets cost too much.", "basic-life", "easy"),
    ("남: 이 옷을 세탁기에 빨아도 돼요? 여: 아니요, 이건 손으로 빨아야 해요. 남: 뜨거운 물로요? 여: 아니요, 찬물로 빠세요.",
     "Man: Can I wash this in the washing machine? Woman: No, this has to be washed by hand. Man: In hot water? Woman: No, wash it in cold water.",
     "이 옷은 어떻게 빨아야 합니까?", "How should this item be washed?",
     [("찬물에 손으로", "By hand in cold water"), ("세탁기에 뜨거운 물로", "In the machine with hot water"), ("손으로 뜨거운 물에", "By hand in hot water"), ("세탁소에 맡긴다", "Take it to the dry cleaner")],
     "손으로 빨아야 해요 … 찬물로 빠세요: by hand, in cold water.", "basic-life", "medium"),
    ("여: 오늘 작업 끝나고 같이 한국어 공부할래요? 남: 좋아요. 어디에서 해요? 여: 기숙사 휴게실에서 해요. 남: 그럼 일곱 시에 휴게실에서 만나요.",
     "Woman: Shall we study Korean together after work today? Man: Sure. Where? Woman: In the dormitory lounge. Man: Then let's meet in the lounge at seven.",
     "두 사람은 어디에서 만납니까?", "Where will the two of them meet?",
     [("기숙사 휴게실", "In the dormitory lounge"), ("회사 식당", "In the company canteen"), ("도서관", "At the library"), ("한국어 학원", "At a Korean school")],
     "기숙사 휴게실에서 … 휴게실에서 만나요: the dorm lounge.", "daily-life", "easy"),
    ("남: 이번 달 월급 명세서 받았어요? 여: 네, 그런데 야근 수당이 빠진 것 같아요. 남: 그럼 경리과에 가서 물어보세요. 여: 네, 점심 먹고 가 볼게요.",
     "Man: Did you get this month's payslip? Woman: Yes, but I think the overtime pay is missing. Man: Then go and ask the accounts office. Woman: OK, I'll go after lunch.",
     "여자는 점심 후에 무엇을 할 겁니까?", "What will the woman do after lunch?",
     [("경리과에 가서 수당을 물어본다", "Ask the accounts office about the overtime pay"), ("은행에 간다", "Go to the bank"), ("야근을 한다", "Work overtime"), ("명세서를 버린다", "Throw away the payslip")],
     "Overtime pay is missing, so she will ask the accounts office.", "job-korean", "medium"),
    ("여: 여기에서 시청까지 어떻게 가요? 남: 지하철 이 호선을 타고 시청역에서 내리세요. 여: 몇 정거장 가야 해요? 남: 다섯 정거장이에요.",
     "Woman: How do I get to City Hall from here? Man: Take Line 2 and get off at City Hall station. Woman: How many stops is it? Man: Five stops.",
     "여자는 몇 정거장을 가야 합니까?", "How many stops must the woman travel?",
     [("다섯 정거장", "Five stops"), ("두 정거장", "Two stops"), ("세 정거장", "Three stops"), ("열 정거장", "Ten stops")],
     "다섯 정거장이에요: five stops. 이 호선 is the line number.", "public-services", "medium"),
    ("남: 작업장 바닥에 기름이 있어요. 여: 위험하니까 빨리 닦아야 해요. 남: 걸레가 어디 있어요? 여: 청소 도구함에 있어요. 제가 가져올게요.",
     "Man: There's oil on the workshop floor. Woman: It's dangerous, so we need to wipe it up quickly. Man: Where are the cloths? Woman: In the cleaning cupboard. I'll fetch one.",
     "여자는 이제 무엇을 할 겁니까?", "What will the woman do now?",
     [("걸레를 가져온다", "Fetch a cloth"), ("기름을 산다", "Buy oil"), ("기계를 고친다", "Repair the machine"), ("반장님에게 전화한다", "Phone the team leader")],
     "제가 가져올게요: she will fetch the cloth.", "industrial-safety", "easy"),
    ("여: 무슨 운동을 좋아해요? 남: 저는 축구를 좋아해요. 주말마다 공원에서 해요. 여: 저도 같이 해도 돼요? 남: 그럼요. 이번 주 일요일 아침에 오세요.",
     "Woman: What sport do you like? Man: I like football. I play in the park every weekend. Woman: Can I join in? Man: Of course. Come on Sunday morning this week.",
     "남자는 언제 축구를 합니까?", "When does the man play football?",
     [("주말마다", "Every weekend"), ("매일 저녁", "Every evening"), ("퇴근 후", "After work"), ("한 달에 한 번", "Once a month")],
     "주말마다 공원에서 해요: every weekend.", "daily-life", "easy"),
    ("남: 이 방은 한 달에 얼마예요? 여: 보증금 백만 원에 월세 이십오만 원이에요. 남: 관리비도 있어요? 여: 네, 관리비는 한 달에 오만 원이에요.",
     "Man: How much is this room a month? Woman: A deposit of one million won and rent of 250,000 won. Man: Is there a maintenance fee too? Woman: Yes, it's 50,000 won a month.",
     "한 달 월세는 얼마입니까?", "How much is the monthly rent?",
     [("250,000원", "250,000 won"), ("1,000,000원", "1,000,000 won"), ("50,000원", "50,000 won"), ("25,000원", "25,000 won")],
     "월세 이십오만 원: 250,000 won. 백만 원 is the deposit.", "numbers-time", "hard"),
    ("여: 내일 건강 검진이 있어요. 남: 아침을 먹으면 안 돼요? 여: 네, 오늘 밤 아홉 시부터 아무것도 먹지 마세요. 물은 조금 마셔도 돼요.",
     "Woman: There's a health check tomorrow. Man: Can't I eat breakfast? Woman: That's right. Don't eat anything from nine tonight. You can drink a little water.",
     "대화의 내용과 같은 것을 고르십시오.", "Which statement matches the conversation?",
     [("오늘 밤 아홉 시부터 먹으면 안 된다.", "No food from nine tonight."), ("아침을 먹어도 된다.", "Breakfast is allowed."), ("물을 마시면 안 된다.", "No water is allowed."), ("건강 검진은 오늘이다.", "The check is today.")],
     "아홉 시부터 아무것도 먹지 마세요; a little water is fine.", "public-services", "medium"),
    ("남: 오늘 몇 시에 퇴근해요? 여: 원래 여섯 시인데 오늘은 물건이 많이 들어와서 여덟 시까지 일해야 해요. 남: 힘들겠네요.",
     "Man: What time are you finishing today? Woman: Usually six, but a lot of goods have come in today, so I have to work until eight. Man: That'll be tiring.",
     "여자는 오늘 몇 시에 퇴근합니까?", "What time is the woman finishing today?",
     [("여덟 시", "Eight o'clock"), ("여섯 시", "Six o'clock"), ("일곱 시", "Seven o'clock"), ("아홉 시", "Nine o'clock")],
     "원래 여섯 시인데 … 여덟 시까지: usually six, but eight today.", "workplace-culture", "medium"),
    ("여: 비닐하우스 안이 너무 더워요. 남: 창문을 열고 환풍기를 켜세요. 여: 물도 줘야 해요? 남: 네, 오후 다섯 시쯤에 주세요.",
     "Woman: It's too hot inside the greenhouse. Man: Open the windows and turn on the fan. Woman: Should I water the plants too? Man: Yes, do it around five in the afternoon.",
     "두 사람은 어디에서 일합니까?", "Where do the two people work?",
     [("농장", "On a farm"), ("식당", "In a restaurant"), ("공사장", "On a building site"), ("배", "On a boat")],
     "A greenhouse (비닐하우스) and watering plants mean farm work.", "job-korean", "medium"),
    ("남: 그물을 정리하고 나서 뭐 해요? 여: 잡은 생선을 상자에 담아야 해요. 남: 얼음도 넣어요? 여: 네, 생선 위에 얼음을 많이 넣으세요.",
     "Man: What do I do after sorting the nets? Woman: We have to pack the fish we caught into boxes. Man: Do we add ice too? Woman: Yes, put lots of ice on top of the fish.",
     "남자가 그물을 정리한 후에 할 일은 무엇입니까?", "What will the man do after sorting the nets?",
     [("생선을 상자에 담는다", "Pack the fish into boxes"), ("생선을 판다", "Sell the fish"), ("그물을 산다", "Buy nets"), ("얼음을 만든다", "Make ice")],
     "잡은 생선을 상자에 담아야 해요: pack the catch into boxes, with ice.", "job-korean", "medium"),
    ("여: 시멘트를 몇 포대 더 가져올까요? 남: 열 포대 더 가져오세요. 여: 혼자서 옮기기 무거운데요. 남: 그럼 수레를 쓰세요.",
     "Woman: How many more bags of cement shall I bring? Man: Bring ten more. Woman: They're heavy to carry on my own. Man: Then use the cart.",
     "여자는 시멘트를 어떻게 옮길 겁니까?", "How will the woman move the cement?",
     [("수레로 옮긴다", "With a cart"), ("혼자 들고 옮긴다", "Carry it alone"), ("트럭으로 옮긴다", "By lorry"), ("옮기지 않는다", "She won't move it.")],
     "수레를 쓰세요: use the cart.", "job-korean", "medium"),
    ("남: 이 돼지들은 하루에 몇 번 밥을 줘요? 여: 아침하고 저녁, 두 번 줘요. 남: 물은요? 여: 물은 항상 가득 채워 두세요.",
     "Man: How many times a day do these pigs get fed? Woman: Twice, morning and evening. Man: And water? Woman: Always keep the water full.",
     "돼지에게 밥은 하루에 몇 번 줍니까?", "How many times a day are the pigs fed?",
     [("두 번", "Twice"), ("한 번", "Once"), ("세 번", "Three times"), ("항상", "All the time")],
     "아침하고 저녁, 두 번: twice a day. It is the water that is always kept full.", "job-korean", "easy"),
    ("여: 다음 주부터 새로운 기계가 들어와요. 남: 사용법은 누가 가르쳐 줘요? 여: 기계 회사 직원이 와서 교육을 해 줄 거예요. 남: 언제요? 여: 월요일 오전에요.",
     "Woman: A new machine arrives next week. Man: Who will teach us how to use it? Woman: Someone from the machine company will come and train us. Man: When? Woman: Monday morning.",
     "기계 사용 교육은 누가 합니까?", "Who will give the training on the machine?",
     [("기계 회사 직원", "Staff from the machine company"), ("반장님", "The team leader"), ("사장님", "The boss"), ("여자", "The woman")],
     "기계 회사 직원이 와서 교육을 해 줄 거예요.", "tools-machines", "medium"),
    ("남: 우산 있어요? 여: 아니요, 안 가져왔어요. 남: 비가 많이 오는데 같이 써요. 여: 고마워요. 버스 정류장까지만 같이 가요.",
     "Man: Have you got an umbrella? Woman: No, I didn't bring one. Man: It's raining hard, so let's share. Woman: Thanks. Let's go together as far as the bus stop.",
     "두 사람은 어디까지 같이 갑니까?", "How far will they go together?",
     [("버스 정류장", "To the bus stop"), ("집", "Home"), ("회사", "To the company"), ("지하철역", "To the underground station")],
     "버스 정류장까지만 같이 가요: as far as the bus stop.", "daily-life", "easy"),
    ("여: 사장님, 이번 달에 고향에 다녀와도 될까요? 어머니가 편찮으세요. 남: 많이 아프세요? 여: 네, 수술을 하셔야 해요. 남: 알겠어요. 일주일 휴가를 쓰세요.",
     "Woman: Boss, may I go home this month? My mother is ill. Man: Is she very ill? Woman: Yes, she has to have an operation. Man: All right. Take a week's leave.",
     "여자가 고향에 가려는 이유는 무엇입니까?", "Why does the woman want to go home?",
     [("어머니가 아프셔서", "Her mother is ill."), ("결혼을 해서", "She is getting married."), ("휴가가 남아서", "She has leave left."), ("비자가 끝나서", "Her visa is ending.")],
     "어머니가 편찮으세요: her mother is ill and needs an operation.", "workplace-culture", "medium"),
    ("남: 외국인 등록증을 잃어버렸어요. 여: 그럼 출입국 사무소에 가서 다시 신청해야 해요. 남: 뭘 가져가야 해요? 여: 여권하고 사진 한 장을 가져가세요.",
     "Man: I've lost my alien registration card. Woman: Then you have to go to the immigration office and apply again. Man: What should I take? Woman: Take your passport and one photo.",
     "남자가 가져가야 하는 것은 무엇입니까?", "What must the man take?",
     [("여권과 사진 한 장", "His passport and one photo"), ("통장과 도장", "His bankbook and seal"), ("근로계약서", "His employment contract"), ("휴대폰", "His mobile")],
     "여권하고 사진 한 장: a passport and a photo.", "laws-systems", "medium"),
    ("여: 이 김치 직접 만들었어요? 남: 네, 회사 아주머니께 배웠어요. 여: 정말 맛있어요. 저도 배우고 싶어요. 남: 그럼 다음 주말에 같이 만들어요.",
     "Woman: Did you make this kimchi yourself? Man: Yes, a lady at the company taught me. Woman: It's really tasty. I'd like to learn too. Man: Then let's make some together next weekend.",
     "두 사람은 다음 주말에 무엇을 합니까?", "What will they do next weekend?",
     [("같이 김치를 만든다", "Make kimchi together"), ("김치를 산다", "Buy kimchi"), ("식당에 간다", "Go to a restaurant"), ("회사에서 일한다", "Work at the company")],
     "다음 주말에 같이 만들어요: they will make kimchi together.", "korean-culture", "easy"),
    ("남: 엘리베이터가 고장 났어요. 여: 그럼 계단으로 올라가야겠네요. 남: 사무실이 칠 층인데 괜찮아요? 여: 운동한다고 생각하죠, 뭐.",
     "Man: The lift is broken. Woman: Then we'll have to take the stairs. Man: The office is on the seventh floor. Is that OK? Woman: Let's think of it as exercise.",
     "두 사람은 어떻게 올라갑니까?", "How will they go up?",
     [("계단으로", "By the stairs"), ("엘리베이터로", "By lift"), ("에스컬레이터로", "By escalator"), ("올라가지 않는다", "They won't go up.")],
     "엘리베이터가 고장 났어요, so 계단으로 올라가야겠네요.", "basic-life", "easy"),
    ("여: 오늘 왜 이렇게 일찍 왔어요? 남: 출근 버스를 놓칠까 봐 일찍 나왔어요. 여: 버스 시간이 바뀐 거 몰랐어요? 남: 몰랐어요. 언제 바뀌었어요? 여: 어제부터요.",
     "Woman: Why are you so early today? Man: I left early in case I missed the work bus. Woman: Didn't you know the bus times changed? Man: No. When did they change? Woman: From yesterday.",
     "대화의 내용과 같은 것을 고르십시오.", "Which statement matches the conversation?",
     [("남자는 버스 시간이 바뀐 것을 몰랐다.", "He didn't know the bus times had changed."), ("남자는 오늘 늦게 왔다.", "He came late today."), ("버스 시간은 내일 바뀐다.", "The times change tomorrow."), ("여자는 버스를 놓쳤다.", "She missed the bus.")],
     "몰랐어요: he didn't know. The change began yesterday.", "workplace-culture", "hard"),
    ("남: 휴대폰 요금이 너무 많이 나왔어요. 여: 해외 전화를 많이 했어요? 남: 네, 고향에 자주 전화했어요. 여: 그럼 인터넷 전화를 써 보세요. 훨씬 싸요.",
     "Man: My phone bill is far too high. Woman: Did you make a lot of international calls? Man: Yes, I called home often. Woman: Then try internet calls. They're much cheaper.",
     "여자는 남자에게 무엇을 하라고 했습니까?", "What does the woman tell the man to do?",
     [("인터넷 전화를 쓰라고", "Use internet calls"), ("전화를 하지 말라고", "Stop calling"), ("휴대폰을 바꾸라고", "Get a new phone"), ("고향에 가라고", "Go home")],
     "인터넷 전화를 써 보세요: try internet calls, which are cheaper.", "daily-life", "medium"),
    ("여: 저 사람은 누구예요? 남: 이번에 새로 온 안전 관리자예요. 여: 무슨 일을 해요? 남: 작업장이 안전한지 매일 점검해요.",
     "Woman: Who's that? Man: He's the new safety manager. Woman: What does he do? Man: He checks every day that the workplace is safe.",
     "새로 온 사람은 무슨 일을 합니까?", "What does the new person do?",
     [("작업장 안전을 점검한다", "Checks that the workplace is safe"), ("기계를 판다", "Sells machines"), ("월급을 계산한다", "Works out pay"), ("식당에서 요리한다", "Cooks in the canteen")],
     "안전 관리자 checks the workplace is safe every day (매일 점검해요).", "industrial-safety", "medium"),
]

assert len(DIALOGUES_B) == 24, len(DIALOGUES_B)
