"""Dialogue Comprehension, part one: short conversations at work and in
daily life, each with one question about where, why, what or what next.

Each entry: (Korean script with 남/여 labels, English with Man/Woman labels,
question in Korean, question in English, [(right answer, English), then
three wrong], note in English, topic tag, difficulty).
"""

DIALOGUES_A = [
    ("남: 오늘 왜 이렇게 피곤해 보여요? 여: 어제 밤늦게까지 야근을 해서 잠을 못 잤어요. 남: 그럼 점심시간에 좀 쉬세요.",
     "Man: Why do you look so tired today? Woman: I worked overtime until late last night, so I couldn't sleep. Man: Then take a rest at lunchtime.",
     "여자가 피곤한 이유는 무엇입니까?", "Why is the woman tired?",
     [("야근을 해서", "She worked overtime."), ("감기에 걸려서", "She has a cold."), ("이사를 해서", "She moved house."), ("운동을 많이 해서", "She exercised a lot.")],
     "She says 야근을 해서 잠을 못 잤어요: she worked late and couldn't sleep.", "workplace-culture", "easy"),
    ("여: 어서 오세요. 어디가 불편하세요? 남: 어제부터 목이 아프고 기침이 나요. 여: 열도 있는지 한번 재 볼게요.",
     "Woman: Come in. What seems to be the trouble? Man: My throat has been sore since yesterday and I'm coughing. Woman: Let me check whether you have a temperature too.",
     "남자는 어디에 왔습니까?", "Where has the man come?",
     [("병원", "A clinic"), ("은행", "A bank"), ("식당", "A restaurant"), ("우체국", "A post office")],
     "He describes a sore throat and a cough and has his temperature taken: he is at a clinic.", "public-services", "easy"),
    ("남: 이 소포를 베트남에 보내고 싶어요. 여: 안에 뭐가 들어 있어요? 남: 옷하고 과자예요. 여: 저울 위에 올려 주세요.",
     "Man: I'd like to send this parcel to Vietnam. Woman: What's inside? Man: Clothes and snacks. Woman: Please put it on the scales.",
     "두 사람은 어디에 있습니까?", "Where are the two people?",
     [("우체국", "At a post office"), ("시장", "At a market"), ("공항", "At an airport"), ("옷 가게", "At a clothes shop")],
     "Sending a parcel abroad and weighing it happens at a post office.", "public-services", "easy"),
    ("여: 반장님, 내일 오후에 반차를 써도 될까요? 남: 무슨 일 있어요? 여: 외국인 등록증을 새로 받으러 출입국 사무소에 가야 해요. 남: 알겠어요. 신청서를 내세요.",
     "Woman: Team leader, may I take tomorrow afternoon off? Man: Is something up? Woman: I have to go to the immigration office to get a new alien registration card. Man: All right. Hand in a request form.",
     "여자가 내일 오후에 하려는 일은 무엇입니까?", "What is the woman going to do tomorrow afternoon?",
     [("출입국 사무소에 간다", "Go to the immigration office"), ("병원에 간다", "Go to the hospital"), ("고향에 간다", "Go home to her country"), ("야근을 한다", "Work overtime")],
     "She needs the afternoon off to get a new registration card at the immigration office.", "laws-systems", "medium"),
    ("남: 이 셔츠 좀 큰 걸로 바꿀 수 있어요? 여: 영수증 있으세요? 남: 네, 여기 있어요. 여: 그럼 엘 사이즈로 바꿔 드릴게요.",
     "Man: Can I change this shirt for a bigger one? Woman: Do you have the receipt? Man: Yes, here it is. Woman: Then I'll change it for a large.",
     "남자는 왜 가게에 왔습니까?", "Why has the man come to the shop?",
     [("셔츠를 큰 것으로 바꾸려고", "To change the shirt for a bigger one"), ("셔츠를 새로 사려고", "To buy a new shirt"), ("영수증을 받으려고", "To get a receipt"), ("돈을 돌려받으려고", "To get his money back")],
     "He asks to swap the shirt for a bigger size, not for a refund.", "daily-life", "medium"),
    ("여: 기숙사 세탁기가 고장 났어요. 남: 그래요? 관리실에 말했어요? 여: 네, 내일 고쳐 준대요. 남: 그럼 오늘은 제 방 세탁기를 쓰세요.",
     "Woman: The dormitory washing machine is broken. Man: Is it? Did you tell the management office? Woman: Yes, they say they'll fix it tomorrow. Man: Then use the washing machine in my room today.",
     "대화의 내용과 같은 것을 고르십시오.", "Which statement matches the conversation?",
     [("세탁기는 내일 고칠 것이다.", "The washing machine will be fixed tomorrow."), ("여자는 관리실에 말하지 않았다.", "The woman did not tell the office."), ("남자의 세탁기도 고장 났다.", "The man's machine is broken too."), ("세탁기는 오늘 고쳤다.", "The machine was fixed today.")],
     "The office says it will fix the machine tomorrow (내일 고쳐 준대요).", "basic-life", "medium"),
    ("남: 지게차를 운전할 수 있어요? 여: 네, 고향에서 면허를 땄어요. 남: 한국 면허도 있어요? 여: 아니요, 한국 면허는 아직 없어요.",
     "Man: Can you drive a forklift? Woman: Yes, I got a licence back home. Man: Do you have a Korean licence too? Woman: No, I don't have a Korean licence yet.",
     "여자에 대한 내용으로 맞는 것을 고르십시오.", "Which is true of the woman?",
     [("한국 지게차 면허가 없다.", "She has no Korean forklift licence."), ("지게차를 운전할 수 없다.", "She can't drive a forklift."), ("한국에서 면허를 땄다.", "She got her licence in Korea."), ("면허가 두 개 있다.", "She has two licences.")],
     "She has a licence from home but no Korean one yet.", "tools-machines", "medium"),
    ("여: 이번 주 토요일에 같이 등산 갈래요? 남: 미안해요. 토요일에는 특근이 있어요. 여: 그럼 일요일은 어때요? 남: 일요일은 좋아요.",
     "Woman: Would you like to go hiking together this Saturday? Man: Sorry, I have extra shifts on Saturday. Woman: Then how about Sunday? Man: Sunday's good.",
     "두 사람은 언제 등산을 갑니까?", "When will they go hiking?",
     [("일요일", "Sunday"), ("토요일", "Saturday"), ("금요일", "Friday"), ("가지 않는다", "They won't go.")],
     "He works on Saturday, so they agree on Sunday.", "daily-life", "easy"),
    ("남: 이 기계는 어떻게 켜요? 여: 먼저 빨간 버튼을 누르고, 초록색 불이 켜지면 시작 버튼을 누르세요. 남: 끌 때는요? 여: 빨간 버튼을 다시 누르면 돼요.",
     "Man: How do I turn this machine on? Woman: First press the red button, and when the green light comes on, press the start button. Man: And to turn it off? Woman: Just press the red button again.",
     "기계를 켤 때 처음에 해야 하는 것은 무엇입니까?", "What must you do first to turn the machine on?",
     [("빨간 버튼을 누른다", "Press the red button"), ("시작 버튼을 누른다", "Press the start button"), ("초록색 버튼을 누른다", "Press the green button"), ("전원을 뽑는다", "Unplug it")],
     "먼저 빨간 버튼을 누르고: the red button comes first.", "tools-machines", "medium"),
    ("여: 고향에 돈을 보내려면 어떻게 해야 해요? 남: 은행에 가서 해외 송금을 신청하면 돼요. 여: 수수료가 비싸요? 남: 은행마다 달라요. 외국인 근로자 전용 창구에 물어보세요.",
     "Woman: How do I send money home? Man: Go to a bank and ask for an overseas transfer. Woman: Are the fees expensive? Man: They differ from bank to bank. Ask at the counter for foreign workers.",
     "남자가 여자에게 알려 준 것은 무엇입니까?", "What does the man tell the woman?",
     [("돈을 보내는 방법", "How to send money"), ("은행 위치", "Where the bank is"), ("월급날", "When payday is"), ("환율", "The exchange rate")],
     "She asks how to send money home and he explains the steps.", "public-services", "medium"),
    ("남: 다음 주 화요일이 공휴일이에요. 여: 그래요? 그럼 회사도 쉬어요? 남: 네, 우리 회사는 쉬어요. 여: 잘됐네요. 친구를 만나러 서울에 가야겠어요.",
     "Man: Next Tuesday is a public holiday. Woman: Is it? Does the company close too? Man: Yes, our company is closed. Woman: Great. I'll go to Seoul to see a friend.",
     "여자는 공휴일에 무엇을 할 겁니까?", "What will the woman do on the holiday?",
     [("서울에서 친구를 만난다", "Meet a friend in Seoul"), ("회사에서 일한다", "Work at the company"), ("집에서 쉰다", "Rest at home"), ("고향에 간다", "Go home to her country")],
     "She says she will go to Seoul to see a friend.", "korean-culture", "easy"),
    ("여: 작업할 때 왜 장갑을 안 꼈어요? 남: 장갑이 찢어져서요. 여: 창고에 새 장갑이 있으니까 가져가세요. 남: 네, 지금 가져올게요.",
     "Woman: Why weren't you wearing gloves while you worked? Man: They were torn. Woman: There are new gloves in the storeroom, so take some. Man: OK, I'll go and get them now.",
     "남자가 장갑을 끼지 않은 이유는 무엇입니까?", "Why wasn't the man wearing gloves?",
     [("장갑이 찢어져서", "His gloves were torn."), ("장갑이 없어서", "He had no gloves."), ("날씨가 더워서", "It was hot."), ("장갑이 커서", "The gloves were too big.")],
     "장갑이 찢어져서요: his gloves were torn.", "industrial-safety", "easy"),
    ("남: 이 버스가 시청 앞에 서요? 여: 아니요, 이 버스는 안 가요. 길 건너서 백이십 번 버스를 타세요. 남: 감사합니다.",
     "Man: Does this bus stop outside City Hall? Woman: No, this bus doesn't go there. Cross the road and take the number 120 bus. Man: Thank you.",
     "남자는 무엇을 타야 합니까?", "What should the man take?",
     [("길 건너에서 120번 버스", "The number 120 bus across the road"), ("이 버스", "This bus"), ("지하철", "The underground"), ("택시", "A taxi")],
     "She tells him to cross the road and take bus 120.", "public-services", "easy"),
    ("여: 무슨 일을 하세요? 남: 자동차 부품 공장에서 일해요. 여: 일이 힘들지 않아요? 남: 처음에는 힘들었는데 지금은 괜찮아요.",
     "Woman: What do you do? Man: I work in a car parts factory. Woman: Isn't the work hard? Man: It was hard at first, but it's fine now.",
     "남자에 대한 내용으로 맞는 것을 고르십시오.", "Which is true of the man?",
     [("지금은 일이 괜찮다.", "The work is fine for him now."), ("자동차를 판다.", "He sells cars."), ("지금도 일이 힘들다.", "The work is still hard."), ("공장에서 일한 적이 없다.", "He has never worked in a factory.")],
     "처음에는 힘들었는데 지금은 괜찮아요: hard at first, fine now.", "job-korean", "medium"),
    ("남: 사과 한 상자에 얼마예요? 여: 삼만 원이에요. 남: 좀 비싸네요. 반 상자도 팔아요? 여: 네, 반 상자는 만 육천 원이에요.",
     "Man: How much is a box of apples? Woman: Thirty thousand won. Man: That's a bit expensive. Do you sell half boxes? Woman: Yes, a half box is sixteen thousand won.",
     "반 상자는 얼마입니까?", "How much is a half box?",
     [("16,000원", "16,000 won"), ("15,000원", "15,000 won"), ("30,000원", "30,000 won"), ("6,000원", "6,000 won")],
     "만 육천 원 is 16,000 won: 만 (10,000) + 육천 (6,000).", "numbers-time", "medium"),
    ("여: 이번 달부터 통근 버스 시간이 바뀌었어요. 남: 몇 시로 바뀌었어요? 여: 아침 일곱 시 사십 분에 기숙사 앞에서 출발해요. 남: 십 분 빨라졌네요.",
     "Woman: The shuttle bus times changed this month. Man: To what time? Woman: It leaves from outside the dormitory at seven forty in the morning. Man: So it's ten minutes earlier.",
     "통근 버스는 몇 시에 출발합니까?", "What time does the shuttle bus leave?",
     [("7시 40분", "7:40"), ("7시 50분", "7:50"), ("7시 30분", "7:30"), ("8시", "8:00")],
     "일곱 시 사십 분 is 7:40, ten minutes earlier than before.", "numbers-time", "medium"),
    ("남: 어제 왜 전화를 안 받았어요? 여: 휴대폰 배터리가 다 돼서 꺼졌어요. 남: 무슨 일이 있는 줄 알고 걱정했어요. 여: 미안해요. 충전기를 회사에 두고 왔거든요.",
     "Man: Why didn't you answer the phone yesterday? Woman: My mobile battery ran out and it turned off. Man: I was worried something had happened. Woman: Sorry. I'd left my charger at work.",
     "여자가 전화를 받지 못한 이유는 무엇입니까?", "Why couldn't the woman answer the phone?",
     [("배터리가 다 돼서", "Her battery had run out."), ("휴대폰을 잃어버려서", "She had lost her phone."), ("일을 하고 있어서", "She was working."), ("잠을 자고 있어서", "She was asleep.")],
     "배터리가 다 돼서 꺼졌어요: the battery died.", "daily-life", "easy"),
    ("여: 이 서류는 어디에 내야 해요? 남: 일 층 인사과에 내면 돼요. 여: 오늘까지 내야 해요? 남: 아니요, 금요일까지 내면 돼요.",
     "Woman: Where do I hand in this form? Man: At the personnel office on the first floor. Woman: Does it have to be in by today? Man: No, Friday is fine.",
     "서류는 언제까지 내야 합니까?", "By when must the form be handed in?",
     [("금요일까지", "By Friday"), ("오늘까지", "By today"), ("내일까지", "By tomorrow"), ("다음 주까지", "By next week")],
     "금요일까지 내면 돼요: by Friday.", "laws-systems", "easy"),
    ("남: 주말에 뭐 했어요? 여: 친구들하고 한강 공원에서 자전거를 탔어요. 남: 재미있었겠네요. 여: 네, 날씨도 좋아서 정말 즐거웠어요.",
     "Man: What did you do at the weekend? Woman: I rode bikes with friends in Hangang Park. Man: That must have been fun. Woman: Yes, the weather was nice too, so it was really enjoyable.",
     "여자는 주말에 무엇을 했습니까?", "What did the woman do at the weekend?",
     [("공원에서 자전거를 탔다", "Rode a bike in the park"), ("집에서 쉬었다", "Rested at home"), ("회사에서 일했다", "Worked at the company"), ("수영을 했다", "Went swimming")],
     "한강 공원에서 자전거를 탔어요: she cycled in the park.", "daily-life", "easy"),
    ("여: 오늘 회식은 어디에서 해요? 남: 회사 앞 삼겹살집에서 해요. 여: 몇 시에 시작해요? 남: 일 끝나고 바로, 여섯 시 반쯤이요.",
     "Woman: Where's the staff dinner today? Man: At the pork belly restaurant in front of the company. Woman: What time does it start? Man: Straight after work, around half past six.",
     "회식은 어디에서 합니까?", "Where is the staff dinner?",
     [("회사 앞 식당", "At a restaurant in front of the company"), ("회사 식당", "In the company canteen"), ("기숙사", "In the dormitory"), ("사장님 집", "At the boss's house")],
     "회사 앞 삼겹살집: a restaurant in front of the company.", "workplace-culture", "easy"),
    ("남: 손가락을 왜 그래요? 여: 상자를 옮기다가 문에 끼었어요. 남: 많이 아프겠네요. 병원에 가 봤어요? 여: 아직이요. 이따가 갈 거예요.",
     "Man: What happened to your finger? Woman: I caught it in a door while I was moving boxes. Man: That must hurt a lot. Have you been to the hospital? Woman: Not yet. I'll go later.",
     "여자는 어떻게 다쳤습니까?", "How did the woman get hurt?",
     [("문에 손가락이 끼었다", "She caught her finger in a door."), ("칼에 베였다", "She cut it on a knife."), ("넘어졌다", "She fell over."), ("상자가 발에 떨어졌다", "A box fell on her foot.")],
     "상자를 옮기다가 문에 끼었어요: she caught it in a door.", "industrial-safety", "medium"),
    ("여: 다음 달에 기숙사에서 이사 나가요. 남: 어디로 가요? 여: 회사 근처 원룸으로 가요. 남: 월세는 얼마예요? 여: 삼십만 원이에요.",
     "Woman: I'm moving out of the dormitory next month. Man: Where to? Woman: To a studio flat near the company. Man: How much is the rent? Woman: Three hundred thousand won.",
     "대화의 내용과 같은 것을 고르십시오.", "Which statement matches the conversation?",
     [("여자는 원룸으로 이사한다.", "The woman is moving into a studio flat."), ("여자는 기숙사로 이사 온다.", "The woman is moving into the dorm."), ("월세는 삼만 원이다.", "The rent is 30,000 won."), ("원룸은 회사에서 멀다.", "The flat is far from work.")],
     "She is moving to a studio flat near work; the rent is 300,000 won.", "basic-life", "medium"),
    ("남: 이 약은 하루에 몇 번 먹어요? 여: 하루에 두 번, 아침하고 저녁 식사 후에 드세요. 남: 술을 마셔도 돼요? 여: 아니요, 약을 드시는 동안에는 안 돼요.",
     "Man: How many times a day do I take this medicine? Woman: Twice a day, after breakfast and dinner. Man: Can I drink alcohol? Woman: No, not while you're taking the medicine.",
     "약은 언제 먹습니까?", "When should the medicine be taken?",
     [("아침과 저녁 식사 후", "After breakfast and dinner"), ("하루에 세 번", "Three times a day"), ("자기 전에", "Before bed"), ("식사 전에", "Before meals")],
     "하루에 두 번, 아침하고 저녁 식사 후에: twice, after breakfast and dinner.", "public-services", "medium"),
    ("여: 반장님, 이 부품 불량인 것 같아요. 남: 어디가 문제예요? 여: 여기 금이 가 있어요. 남: 그럼 따로 빼 두고, 몇 개인지 세어서 알려 주세요.",
     "Woman: Team leader, I think this part is faulty. Man: What's the problem? Woman: There's a crack here. Man: Then set it aside, count how many there are and let me know.",
     "여자가 이제 할 일은 무엇입니까?", "What will the woman do now?",
     [("불량 부품을 빼고 개수를 센다", "Set aside the faulty parts and count them"), ("부품을 고친다", "Repair the part"), ("새 부품을 산다", "Buy new parts"), ("기계를 끈다", "Turn off the machine")],
     "He tells her to set the faulty parts aside and count them.", "job-korean", "medium"),
]

assert len(DIALOGUES_A) == 24, len(DIALOGUES_A)
