"""Choose the Right Reply and What Comes Next.

RESPONSE: one speaker asks something; the learner picks the answer that fits.
NEXT: one speaker says something (a warning, a request, news); the learner
picks what the other person would naturally say back.

Each entry: (speaker 남/여, Korean, English, [(right reply, English), then
three wrong ones], note in English on why, topic tag). The wrong replies
reuse a word from the line or answer a different question, the trap the exam
sets.
"""

RESPONSE = [
    ("남", "이름이 뭐예요?", "What's your name?",
     [("저는 라주예요.", "I'm Raju."), ("네, 이름이에요.", "Yes, it's a name."), ("한국에서 일해요.", "I work in Korea."), ("스물여덟 살이에요.", "I'm twenty-eight.")],
     "이름이 뭐예요? asks for your name, so the reply gives one.", "basic-life"),
    ("여", "몇 살이에요?", "How old are you?",
     [("스물다섯 살이에요.", "I'm twenty-five."), ("다섯 시예요.", "It's five o'clock."), ("이 층이에요.", "It's the second floor."), ("다섯 명이에요.", "There are five people.")],
     "몇 살 asks your age; 살 is the counter for years of age.", "numbers-time"),
    ("남", "한국에 언제 왔어요?", "When did you come to Korea?",
     [("작년 삼월에 왔어요.", "I came in March last year."), ("비행기로 왔어요.", "I came by plane."), ("친구와 같이 왔어요.", "I came with a friend."), ("네팔에서 왔어요.", "I came from Nepal.")],
     "언제 asks when, so the answer is a time: 작년 삼월.", "basic-life"),
    ("여", "주말에 보통 뭐 해요?", "What do you usually do at weekends?",
     [("친구를 만나거나 쉬어요.", "I meet friends or rest."), ("주말이 아니에요.", "It isn't the weekend."), ("토요일이에요.", "It's Saturday."), ("회사가 멀어요.", "The company is far away.")],
     "뭐 해요 asks what you do; meeting friends or resting answers it.", "daily-life"),
    ("남", "점심 먹었어요?", "Have you had lunch?",
     [("네, 방금 먹었어요.", "Yes, I've just eaten."), ("점심은 열두 시예요.", "Lunch is at twelve."), ("식당이 커요.", "The canteen is big."), ("네, 맛있게 드세요.", "Yes, enjoy your meal.")],
     "A yes-or-no question about eating: 네, 방금 먹었어요.", "daily-life"),
    ("여", "이 일은 처음 해 봐요?", "Is this your first time doing this work?",
     [("네, 처음이라서 잘 몰라요.", "Yes, it's my first time, so I don't know it well."), ("네, 첫 번째 층이에요.", "Yes, it's the first floor."), ("처음 뵙겠습니다.", "Nice to meet you."), ("일이 끝났어요.", "The work is finished.")],
     "처음 해 봐요? asks whether you have done it before.", "job-korean"),
    ("남", "집이 회사에서 멀어요?", "Is your home far from the company?",
     [("아니요, 걸어서 십 분쯤 걸려요.", "No, it takes about ten minutes on foot."), ("네, 집이 커요.", "Yes, my home is big."), ("회사가 좋아요.", "The company is good."), ("집에 가요.", "I'm going home.")],
     "멀어요? asks about distance; ten minutes on foot answers it.", "basic-life"),
    ("여", "무슨 음식을 좋아해요?", "What food do you like?",
     [("불고기를 좋아해요.", "I like bulgogi."), ("음식이 많아요.", "There's a lot of food."), ("식당에 가요.", "I'm going to a restaurant."), ("네, 좋아해요.", "Yes, I like it.")],
     "무슨 asks which one, so a yes is not enough: name a food.", "daily-life"),
    ("남", "어디가 아파요?", "Where does it hurt?",
     [("머리가 아파요.", "I have a headache."), ("병원에 있어요.", "I'm at the hospital."), ("어제 아팠어요.", "I was ill yesterday."), ("약을 먹었어요.", "I took some medicine.")],
     "어디가 asks which part of the body hurts.", "public-services"),
    ("여", "이 상자를 어디에 둘까요?", "Where shall I put this box?",
     [("저쪽 선반 위에 두세요.", "Put it on the shelf over there."), ("상자가 무거워요.", "The box is heavy."), ("네, 두 개 있어요.", "Yes, there are two."), ("상자를 샀어요.", "I bought a box.")],
     "어디에 둘까요? asks where to put it, so the reply names a place.", "job-korean"),
    ("남", "내일 몇 시까지 출근해야 해요?", "What time do I have to be at work tomorrow?",
     [("여덟 시까지 오세요.", "Come by eight."), ("버스를 타고 오세요.", "Come by bus."), ("내일은 화요일이에요.", "Tomorrow is Tuesday."), ("공장으로 오세요.", "Come to the factory.")],
     "몇 시까지 asks by what time.", "workplace-culture"),
    ("여", "고향에 가족이 몇 명 있어요?", "How many family members do you have back home?",
     [("부모님하고 동생, 세 명이 있어요.", "Three: my parents and my younger sibling."), ("고향은 베트남이에요.", "My hometown is in Vietnam."), ("가족을 사랑해요.", "I love my family."), ("세 시에 전화해요.", "I call at three.")],
     "몇 명 asks how many people.", "basic-life"),
    ("남", "이 근처에 은행이 있어요?", "Is there a bank near here?",
     [("네, 우체국 옆에 있어요.", "Yes, it's next to the post office."), ("네, 돈이 있어요.", "Yes, I have money."), ("은행에서 일해요.", "I work at a bank."), ("돈을 찾았어요.", "I took out some money.")],
     "The question is whether a bank is nearby; the reply says where it is.", "public-services"),
    ("여", "휴가 때 뭐 할 거예요?", "What will you do on your holiday?",
     [("고향에 다녀올 거예요.", "I'll go home for a visit."), ("휴가가 삼 일이에요.", "The holiday is three days."), ("휴가 신청서예요.", "It's a leave form."), ("어제 쉬었어요.", "I rested yesterday.")],
     "뭐 할 거예요 asks about a plan.", "workplace-culture"),
    ("남", "한국 생활이 어때요?", "How is life in Korea?",
     [("조금 힘들지만 재미있어요.", "It's a bit hard, but it's fun."), ("한국에 살아요.", "I live in Korea."), ("한국 사람이에요.", "I'm Korean."), ("생활비를 보냈어요.", "I sent living expenses.")],
     "어때요? asks how something is, so the reply describes it.", "basic-life"),
    ("여", "이 옷 얼마예요?", "How much is this?",
     [("이만 원이에요.", "It's twenty thousand won."), ("옷이 예뻐요.", "The clothes are pretty."), ("두 벌 있어요.", "There are two."), ("시장에서 샀어요.", "I bought it at the market.")],
     "얼마예요? asks the price.", "daily-life"),
    ("남", "무엇을 도와 드릴까요?", "What can I help you with?",
     [("통장을 만들고 싶어요.", "I'd like to open a bank account."), ("네, 도와 드릴게요.", "Yes, I'll help you."), ("저는 은행원이에요.", "I'm a bank clerk."), ("도움이 많아요.", "There's a lot of help.")],
     "Staff ask this when you come in; the reply says what you need.", "public-services"),
    ("여", "작업복은 어디에서 갈아입어요?", "Where do I change into my work clothes?",
     [("이 층 탈의실에서 갈아입으세요.", "Change in the changing room on the second floor."), ("작업복이 커요.", "The work clothes are big."), ("아침에 입어요.", "I put them on in the morning."), ("파란색이에요.", "They're blue.")],
     "어디에서 asks where.", "job-korean"),
    ("남", "오늘 야근할 수 있어요?", "Can you work overtime tonight?",
     [("네, 할 수 있어요.", "Yes, I can."), ("야근이 많아요.", "There's a lot of overtime."), ("밤이에요.", "It's night."), ("야근 수당이에요.", "It's overtime pay.")],
     "할 수 있어요? asks whether you can; 네, 할 수 있어요 answers it.", "workplace-culture"),
    ("여", "기숙사 방은 몇 명이 같이 써요?", "How many people share a dormitory room?",
     [("두 명이 같이 써요.", "Two people share it."), ("방이 깨끗해요.", "The room is clean."), ("이 층에 있어요.", "It's on the second floor."), ("두 시에 써요.", "I use it at two.")],
     "몇 명 asks how many people.", "basic-life"),
    ("남", "이 기계 사용법을 알아요?", "Do you know how to use this machine?",
     [("아니요, 한 번 가르쳐 주세요.", "No, please show me once."), ("기계가 비싸요.", "The machine is expensive."), ("네, 기계예요.", "Yes, it's a machine."), ("기계를 샀어요.", "I bought a machine.")],
     "사용법을 알아요? asks whether you know how to use it.", "tools-machines"),
    ("여", "무슨 일을 해요?", "What work do you do?",
     [("공장에서 부품을 만들어요.", "I make parts in a factory."), ("일이 많아요.", "There's a lot of work."), ("아홉 시에 일해요.", "I work at nine."), ("일요일에 쉬어요.", "I rest on Sundays.")],
     "무슨 일 asks what job you do.", "job-korean"),
    ("남", "왜 늦었어요?", "Why are you late?",
     [("버스가 늦게 와서 늦었어요.", "The bus came late, so I was late."), ("아홉 시에 왔어요.", "I came at nine."), ("늦게 자요.", "I go to bed late."), ("내일 올게요.", "I'll come tomorrow.")],
     "왜 asks for a reason; -아서/어서 gives one.", "workplace-culture"),
    ("여", "전화번호가 몇 번이에요?", "What's your phone number?",
     [("공일공 일이삼사 오육칠팔이에요.", "It's 010-1234-5678."), ("휴대폰이 있어요.", "I have a mobile phone."), ("세 번 전화했어요.", "I called three times."), ("전화를 받으세요.", "Please answer the phone.")],
     "Phone numbers are read digit by digit in Sino-Korean numbers.", "numbers-time"),
    ("남", "생일이 언제예요?", "When is your birthday?",
     [("시월 이십 일이에요.", "It's the twentieth of October."), ("스물다섯 살이에요.", "I'm twenty-five."), ("케이크를 먹어요.", "I eat cake."), ("생일 축하해요.", "Happy birthday.")],
     "언제 asks for a date: 시월 이십 일.", "numbers-time"),
    ("여", "커피 마실래요?", "Would you like some coffee?",
     [("네, 좋아요. 고마워요.", "Yes, please. Thank you."), ("커피숍이에요.", "It's a coffee shop."), ("커피를 샀어요.", "I bought coffee."), ("커피가 검은색이에요.", "Coffee is black.")],
     "An offer: accept or decline it.", "daily-life"),
    ("남", "한국어를 어디에서 배웠어요?", "Where did you learn Korean?",
     [("고향에 있는 학원에서 배웠어요.", "At a language school back home."), ("한국어가 어려워요.", "Korean is difficult."), ("일 년 배웠어요.", "I learned it for a year."), ("한국어 책이에요.", "It's a Korean book.")],
     "어디에서 asks where, not how long.", "daily-life"),
    ("여", "이번 달 월급 받았어요?", "Have you been paid this month?",
     [("네, 어제 받았어요.", "Yes, I got it yesterday."), ("월급이 많아요.", "The pay is good."), ("은행에 가요.", "I'm going to the bank."), ("월급날이에요?", "Is it payday?")],
     "A yes-or-no question about getting paid.", "job-korean"),
    ("남", "어떤 운동을 좋아해요?", "Which sport do you like?",
     [("축구를 좋아해요.", "I like football."), ("운동장에 가요.", "I'm going to the sports ground."), ("매일 해요.", "I do it every day."), ("운동화를 샀어요.", "I bought trainers.")],
     "어떤 asks which one, so name a sport.", "daily-life"),
    ("여", "이 버스 시청에 가요?", "Does this bus go to City Hall?",
     [("아니요, 십오 번 버스를 타세요.", "No, take the number 15 bus."), ("버스가 커요.", "The bus is big."), ("시청에서 일해요.", "I work at City Hall."), ("버스비가 천오백 원이에요.", "The fare is 1,500 won.")],
     "The question is whether this bus goes there.", "public-services"),
    ("남", "손을 다쳤어요?", "Have you hurt your hand?",
     [("네, 칼에 조금 베였어요.", "Yes, I cut it a little on a knife."), ("손이 커요.", "My hands are big."), ("장갑을 샀어요.", "I bought gloves."), ("손을 씻어요.", "I wash my hands.")],
     "A yes-or-no question about an injury.", "industrial-safety"),
    ("여", "여기에서 사진을 찍어도 돼요?", "May I take photos here?",
     [("아니요, 여기에서는 찍으면 안 돼요.", "No, you can't take photos here."), ("사진이 예뻐요.", "The photo is pretty."), ("카메라가 있어요.", "I have a camera."), ("어제 찍었어요.", "I took them yesterday.")],
     "-아도/어도 돼요? asks permission; -으면 안 돼요 refuses it.", "public-services"),
    ("남", "밖에 날씨가 어때요?", "What's the weather like outside?",
     [("비가 오고 추워요.", "It's raining and cold."), ("날씨가 있어요.", "There is weather."), ("우산이에요.", "It's an umbrella."), ("내일이에요.", "It's tomorrow.")],
     "어때요? asks what it is like.", "daily-life"),
    ("여", "뭘 드릴까요?", "What can I get you?",
     [("김치찌개 하나 주세요.", "One kimchi stew, please."), ("맛있게 드세요.", "Enjoy your meal."), ("식당이 멀어요.", "The restaurant is far."), ("저는 손님이에요.", "I'm a customer.")],
     "Staff at a restaurant ask what you want; order something.", "daily-life"),
    ("남", "회의는 몇 층에서 해요?", "Which floor is the meeting on?",
     [("삼 층 회의실에서 해요.", "In the meeting room on the third floor."), ("세 시에 해요.", "At three."), ("회의가 길어요.", "The meeting is long."), ("계단으로 가요.", "I take the stairs.")],
     "몇 층 asks which floor; floors use Sino-Korean numbers.", "workplace-culture"),
    ("여", "어제 왜 결근했어요?", "Why were you absent yesterday?",
     [("열이 많이 나서 못 왔어요.", "I had a high fever, so I couldn't come."), ("어제는 월요일이었어요.", "Yesterday was Monday."), ("오늘 왔어요.", "I came today."), ("결근하지 마세요.", "Don't be absent.")],
     "왜 asks for the reason.", "workplace-culture"),
    ("남", "이 서류 어디에 사인해요?", "Where on this form do I sign?",
     [("맨 아래에 사인하세요.", "Sign at the very bottom."), ("볼펜으로 해요.", "With a pen."), ("서류가 많아요.", "There are a lot of forms."), ("내일 주세요.", "Give it to me tomorrow.")],
     "어디에 asks where, not with what.", "laws-systems"),
    ("여", "같이 저녁 먹을까요?", "Shall we have dinner together?",
     [("좋아요. 몇 시에 만날까요?", "Sure. What time shall we meet?"), ("저녁이 맛있어요.", "Dinner is tasty."), ("저는 식당이에요.", "I am a restaurant."), ("아침을 먹었어요.", "I had breakfast.")],
     "-을까요? suggests doing something together; accept and plan.", "daily-life"),
    ("남", "이 약은 언제 먹어요?", "When do I take this medicine?",
     [("하루에 세 번 식후에 드세요.", "Take it three times a day after meals."), ("약국에서 샀어요.", "I bought it at the pharmacy."), ("약이 써요.", "The medicine is bitter."), ("감기약이에요.", "It's cold medicine.")],
     "언제 asks when: three times a day, after meals.", "public-services"),
    ("여", "고향 음식이 그립지 않아요?", "Don't you miss the food back home?",
     [("네, 가끔 많이 생각나요.", "Yes, I often think of it."), ("고향이 멀어요.", "My hometown is far away."), ("음식을 만들어요.", "I make food."), ("한국 음식이에요.", "It's Korean food.")],
     "The question asks how you feel about home food.", "korean-culture"),
    ("남", "짐이 많네요. 도와 드릴까요?", "You've got a lot of bags. Shall I help you?",
     [("네, 고맙습니다.", "Yes, thank you."), ("짐을 쌌어요.", "I packed my bags."), ("네, 도와 드릴게요.", "Yes, I'll help you."), ("짐이 세 개 있어요.", "There are three bags.")],
     "Someone offers help; thank them. 도와 드릴게요 is what the helper says.", "daily-life"),
    ("여", "퇴근 후에 보통 뭐 해요?", "What do you usually do after work?",
     [("기숙사에서 한국어를 공부해요.", "I study Korean in the dormitory."), ("여섯 시에 퇴근해요.", "I finish work at six."), ("퇴근이 늦어요.", "I finish late."), ("회사에서 일해요.", "I work at the company.")],
     "후에 means after: what you do once work is over.", "daily-life"),
    ("남", "이 장갑 누구 거예요?", "Whose gloves are these?",
     [("제 거예요. 고마워요.", "They're mine. Thanks."), ("장갑이 두 개예요.", "There are two gloves."), ("장갑을 끼세요.", "Put your gloves on."), ("하얀색이에요.", "They're white.")],
     "누구 거 asks whose.", "industrial-safety"),
    ("여", "비자가 언제까지예요?", "Until when is your visa valid?",
     [("내년 오월까지예요.", "Until May next year."), ("비자를 받았어요.", "I got my visa."), ("출입국 사무소예요.", "It's the immigration office."), ("삼 년 일했어요.", "I worked for three years.")],
     "언제까지 asks for the end date.", "laws-systems"),
    ("남", "지금 시간 있어요?", "Have you got a moment now?",
     [("네, 무슨 일이에요?", "Yes, what is it?"), ("지금 세 시예요.", "It's three o'clock now."), ("시계가 있어요.", "I have a watch."), ("시간이 빨라요.", "Time is fast.")],
     "시간 있어요? asks if you are free, not what time it is.", "daily-life"),
    ("여", "기숙사 와이파이 비밀번호 알아요?", "Do you know the dormitory Wi-Fi password?",
     [("네, 문 옆에 붙어 있어요.", "Yes, it's stuck up by the door."), ("와이파이가 빨라요.", "The Wi-Fi is fast."), ("휴대폰이 없어요.", "I don't have a mobile."), ("비밀이에요.", "It's a secret.")],
     "The question asks whether you know the password.", "basic-life"),
    ("남", "누구하고 같이 살아요?", "Who do you live with?",
     [("동료 두 명하고 같이 살아요.", "I live with two co-workers."), ("기숙사에 살아요.", "I live in the dormitory."), ("삼 년 살았어요.", "I've lived here three years."), ("혼자 왔어요?", "Did you come alone?")],
     "누구하고 asks who with, so name the people.", "basic-life"),
    ("여", "오늘 기분이 어때요?", "How are you feeling today?",
     [("월급날이라서 기분이 좋아요.", "It's payday, so I'm in a good mood."), ("오늘은 금요일이에요.", "Today is Friday."), ("기분이 있어요.", "There is a mood."), ("날씨예요.", "It's the weather.")],
     "기분이 어때요? asks how you feel.", "daily-life"),
]

NEXT = [
    ("남", "바닥이 미끄러우니까 뛰지 마세요.", "The floor is slippery, so don't run.",
     [("네, 천천히 걸을게요.", "OK, I'll walk slowly."), ("네, 빨리 뛸게요.", "OK, I'll run fast."), ("바닥을 샀어요.", "I bought a floor."), ("미끄럼틀이 좋아요.", "I like slides.")],
     "A warning not to run; the reply agrees to walk slowly.", "industrial-safety"),
    ("여", "내일은 공장 청소가 있어서 일찍 와야 해요.", "We're cleaning the factory tomorrow, so you need to come early.",
     [("알겠습니다. 일찍 올게요.", "Understood. I'll come early."), ("오늘 청소했어요.", "I cleaned today."), ("늦게 올게요.", "I'll come late."), ("공장이 커요.", "The factory is big.")],
     "Asked to come early, the reply agrees: 일찍 올게요.", "workplace-culture"),
    ("남", "이 상자는 무거우니까 두 사람이 같이 드세요.", "This box is heavy, so lift it with two people.",
     [("네, 동료를 불러서 같이 들게요.", "OK, I'll get a co-worker and lift it together."), ("혼자 들게요.", "I'll lift it on my own."), ("상자가 작아요.", "The box is small."), ("상자를 열었어요.", "I opened the box.")],
     "The instruction is to lift it together, so call a co-worker.", "industrial-safety"),
    ("여", "감기에 걸렸으면 오늘은 일찍 들어가서 쉬세요.", "If you've got a cold, go home early today and rest.",
     [("감사합니다. 약 먹고 푹 쉴게요.", "Thank you. I'll take some medicine and get a good rest."), ("감기가 좋아요.", "I like colds."), ("오늘은 야근할게요.", "I'll do overtime today."), ("일찍 일어났어요.", "I got up early.")],
     "Told to rest, thank them and say you will.", "workplace-culture"),
    ("남", "다음 주 월요일부터 작업 시간이 바뀝니다.", "From next Monday, working hours are changing.",
     [("몇 시부터 몇 시까지로 바뀌어요?", "What will the new hours be?"), ("월요일이 좋아요.", "I like Mondays."), ("지난주에 일했어요.", "I worked last week."), ("시간이 없어요.", "I have no time.")],
     "News of a change: ask what the new hours are.", "workplace-culture"),
    ("여", "기계에서 이상한 소리가 나요.", "The machine is making a strange noise.",
     [("그럼 기계를 끄고 반장님께 말씀드리세요.", "Then switch it off and tell the team leader."), ("소리가 좋아요.", "It sounds nice."), ("노래를 불러요.", "I'm singing."), ("기계를 샀어요.", "I bought a machine.")],
     "A strange noise means a fault: stop the machine and report it.", "tools-machines"),
    ("남", "이번 주말에 회사 체육 대회가 있어요.", "There's a company sports day this weekend.",
     [("그래요? 저도 축구 경기에 나가고 싶어요.", "Really? I'd like to play in the football match."), ("주말에 일했어요.", "I worked at the weekend."), ("체육관이 멀어요.", "The gym is far."), ("회사가 커요.", "The company is big.")],
     "News of an event: show interest in taking part.", "workplace-culture"),
    ("여", "이 서류는 내일까지 꼭 내야 해요.", "This form must be handed in by tomorrow.",
     [("네, 오늘 써서 내일 아침에 드릴게요.", "OK, I'll fill it in today and give it to you tomorrow morning."), ("서류가 하얗네요.", "The form is white."), ("다음 달에 낼게요.", "I'll hand it in next month."), ("서류를 읽어요.", "I'm reading a form.")],
     "A deadline: promise to meet it.", "laws-systems"),
    ("남", "길이 막혀서 조금 늦을 것 같아요.", "The traffic's bad, so I think I'll be a little late.",
     [("괜찮아요. 천천히 조심해서 오세요.", "That's fine. Take your time and come safely."), ("길이 넓어요.", "The road is wide."), ("일찍 왔어요.", "I came early."), ("막혀서 좋아요.", "I'm glad it's jammed.")],
     "Someone will be late; reassure them.", "daily-life"),
    ("여", "오늘 저녁에 회식이 있는데 같이 가요.", "There's a staff dinner tonight. Let's go together.",
     [("좋아요. 어디에서 해요?", "Sure. Where is it?"), ("저녁을 만들어요.", "I'm making dinner."), ("어제 갔어요.", "I went yesterday."), ("회사에 가요.", "I'm going to the company.")],
     "An invitation: accept and ask where.", "workplace-culture"),
    ("남", "냉장고에 있는 우유는 제 거예요.", "The milk in the fridge is mine.",
     [("아, 그래요? 몰랐어요. 미안해요.", "Oh, is it? I didn't know. Sorry."), ("냉장고가 커요.", "The fridge is big."), ("우유가 하얘요.", "Milk is white."), ("우유를 샀어요?", "Did you buy milk?")],
     "He is pointing out the milk is his; apologise for taking it.", "basic-life"),
    ("여", "오늘 오후에 비가 많이 온대요.", "They say it'll rain heavily this afternoon.",
     [("그럼 우산을 가지고 가야겠어요.", "Then I'd better take an umbrella."), ("날씨가 맑아요.", "The weather is clear."), ("우산을 팔아요.", "I sell umbrellas."), ("비가 안 와요.", "It isn't raining.")],
     "Rain is forecast, so take an umbrella.", "daily-life"),
    ("남", "새로 온 직원이에요. 잘 부탁드립니다.", "I'm the new member of staff. I look forward to working with you.",
     [("반가워요. 모르는 것이 있으면 물어보세요.", "Nice to meet you. Ask if there's anything you don't know."), ("새 옷이에요.", "They're new clothes."), ("직원이 많아요.", "There are lots of staff."), ("잘 먹겠습니다.", "Thank you for the meal.")],
     "Welcome a new co-worker and offer help.", "workplace-culture"),
    ("여", "작업할 때는 꼭 안전모를 쓰세요.", "Always wear a safety helmet when you're working.",
     [("네, 지금 바로 쓸게요.", "OK, I'll put it on right now."), ("모자가 예뻐요.", "The hat is pretty."), ("안전모를 벗을게요.", "I'll take my helmet off."), ("작업이 끝났어요.", "The work is done.")],
     "A safety instruction: put the helmet on.", "industrial-safety"),
    ("남", "손을 다쳤으니까 병원에 가 보세요.", "You've hurt your hand, so go and see a doctor.",
     [("네, 지금 다녀오겠습니다.", "OK, I'll go now and come back."), ("손을 씻었어요.", "I washed my hands."), ("병원이 커요.", "The hospital is big."), ("손이 두 개예요.", "I have two hands.")],
     "Told to see a doctor, agree to go.", "industrial-safety"),
    ("여", "다음 달부터 기숙사비가 조금 올라요.", "The dormitory fee goes up a little from next month.",
     [("얼마나 올라요?", "By how much?"), ("기숙사가 깨끗해요.", "The dormitory is clean."), ("다음 달이 좋아요.", "Next month is good."), ("이 층으로 올라가요.", "I'm going up to the second floor.")],
     "News of a rise: ask how much.", "basic-life"),
    ("남", "이 물건은 깨지기 쉬우니까 조심하세요.", "This item breaks easily, so be careful.",
     [("네, 천천히 옮길게요.", "OK, I'll move it slowly."), ("쉬운 물건이에요.", "It's an easy item."), ("물건이 싸요.", "It's cheap."), ("던질게요.", "I'll throw it.")],
     "Fragile goods: handle them slowly.", "job-korean"),
    ("여", "여기는 금연 구역이에요.", "This is a no-smoking area.",
     [("죄송합니다. 밖에 나가서 피울게요.", "Sorry. I'll go outside to smoke."), ("담배를 사요.", "I'm buying cigarettes."), ("금요일이에요.", "It's Friday."), ("구역이 넓어요.", "The area is wide.")],
     "Told not to smoke here, apologise and go outside.", "industrial-safety"),
    ("남", "오늘은 일이 많으니까 점심을 빨리 먹읍시다.", "We've got a lot of work today, so let's eat lunch quickly.",
     [("네, 김밥을 사 와서 먹을까요?", "OK, shall I get some gimbap for us?"), ("점심은 맛있어요.", "Lunch is tasty."), ("일이 없어요.", "There's no work."), ("천천히 먹어요.", "Let's eat slowly.")],
     "A suggestion to eat quickly; suggest something quick.", "workplace-culture"),
    ("여", "지난번에 빌린 책 다 읽었어요?", "Have you finished the book you borrowed last time?",
     [("네, 내일 돌려 드릴게요.", "Yes, I'll give it back tomorrow."), ("책을 샀어요.", "I bought a book."), ("도서관이에요.", "It's a library."), ("책이 두꺼워요.", "The book is thick.")],
     "Asked about a borrowed book, offer to return it.", "daily-life"),
    ("남", "전기를 아끼려면 나갈 때 불을 끄세요.", "To save electricity, turn off the lights when you leave.",
     [("네, 나갈 때 꼭 끌게요.", "OK, I'll be sure to turn them off when I leave."), ("불을 켤게요.", "I'll turn them on."), ("전기가 비싸요.", "Electricity is expensive."), ("밖이 어두워요.", "It's dark outside.")],
     "A request to turn lights off: agree.", "basic-life"),
    ("여", "휴대폰을 잃어버렸어요.", "I've lost my mobile phone.",
     [("마지막으로 어디에서 썼어요?", "Where did you last use it?"), ("휴대폰이 비싸요.", "Mobiles are expensive."), ("새 휴대폰이에요.", "It's a new mobile."), ("휴대폰을 샀어요.", "I bought a mobile.")],
     "Help look for it: ask where it was last used.", "daily-life"),
    ("남", "다음 주에 건강 검진이 있어요.", "There's a health check next week.",
     [("무슨 요일에 해요?", "What day is it?"), ("건강해요.", "I'm healthy."), ("지난주에 아팠어요.", "I was ill last week."), ("병원이 멀어요.", "The hospital is far.")],
     "News of a check-up: ask what day.", "public-services"),
    ("여", "이 일이 끝나면 저쪽 창고도 정리해 주세요.", "When you've finished this, please tidy the storeroom over there too.",
     [("네, 끝나고 바로 정리할게요.", "OK, I'll tidy it as soon as I've finished."), ("창고가 커요.", "The storeroom is big."), ("일이 끝났어요.", "The work is done."), ("저쪽이에요.", "It's over there.")],
     "A request: agree to do it.", "job-korean"),
    ("남", "설날에는 공장이 사흘 동안 쉽니다.", "The factory closes for three days over New Year.",
     [("그럼 그때 친구들하고 여행을 가야겠어요.", "Then I'll go on a trip with friends."), ("설날은 겨울이에요.", "New Year is in winter."), ("사흘 동안 일할게요.", "I'll work for three days."), ("공장이 바빠요.", "The factory is busy.")],
     "Days off are coming: make a plan for them.", "korean-culture"),
    ("여", "기숙사 근처에 새 마트가 생겼어요.", "A new supermarket has opened near the dorm.",
     [("그래요? 이따가 같이 가 봐요.", "Really? Let's go and have a look later."), ("마트에서 일해요.", "I work at a supermarket."), ("기숙사가 멀어요.", "The dorm is far."), ("새 옷을 샀어요.", "I bought new clothes.")],
     "News of a new shop: suggest visiting it.", "basic-life"),
    ("남", "이 기계는 아직 고치는 중이에요.", "This machine is still being repaired.",
     [("그럼 다른 기계를 사용할게요.", "Then I'll use another machine."), ("기계를 고쳤어요.", "I fixed the machine."), ("고치는 사람이에요.", "I'm the repairer."), ("기계가 새것이에요.", "The machine is new.")],
     "The machine can't be used; use another one.", "tools-machines"),
    ("여", "오늘이 제 생일이에요.", "Today's my birthday.",
     [("생일 축하해요! 오늘 저녁은 제가 살게요.", "Happy birthday! Dinner's on me tonight."), ("오늘은 금요일이에요.", "Today is Friday."), ("생일이 언제예요?", "When's your birthday?"), ("축하해 주세요.", "Please congratulate me.")],
     "She has just said it is her birthday: congratulate her.", "daily-life"),
    ("남", "제가 길을 잘 몰라서요.", "I don't really know the way.",
     [("제가 같이 가 드릴게요.", "I'll go with you."), ("길이 넓어요.", "The road is wide."), ("저도 길이에요.", "I'm a road too."), ("지도를 팔아요.", "I sell maps.")],
     "He is lost; offer to show him.", "daily-life"),
    ("여", "오늘 처음으로 지게차를 운전해요.", "Today I'm driving the forklift for the first time.",
     [("처음이니까 천천히 조심해서 하세요.", "It's your first time, so go slowly and carefully."), ("지게차가 노래요.", "The forklift is yellow."), ("차를 샀어요.", "I bought a car."), ("빨리 운전하세요.", "Drive fast.")],
     "A first time on a forklift: advise care.", "industrial-safety"),
    ("남", "화장실 물이 안 내려가요.", "The toilet won't flush.",
     [("관리실에 전화해서 고쳐 달라고 할게요.", "I'll call the management office and ask them to fix it."), ("물을 마셔요.", "I'm drinking water."), ("화장실이 깨끗해요.", "The toilet is clean."), ("물이 차가워요.", "The water is cold.")],
     "Something is broken: call someone to fix it.", "basic-life"),
    ("여", "내일 아침에 비행기 타고 고향에 가요.", "I'm flying home tomorrow morning.",
     [("잘 다녀오세요. 가족들에게 안부 전해 주세요.", "Have a good trip. Say hello to your family."), ("비행기가 커요.", "The plane is big."), ("어제 고향에 갔어요.", "I went home yesterday."), ("아침을 먹어요.", "I'm eating breakfast.")],
     "Someone is leaving on a trip: wish them well.", "basic-life"),
    ("남", "이 방은 너무 더워요.", "This room is too hot.",
     [("에어컨을 켤까요?", "Shall I turn on the air conditioning?"), ("방이 커요.", "The room is big."), ("겨울이에요.", "It's winter."), ("난방을 켤게요.", "I'll turn on the heating.")],
     "The room is hot, so offer to cool it. Heating would make it worse.", "basic-life"),
    ("여", "계약 기간이 다음 달에 끝나요.", "My contract ends next month.",
     [("계약을 연장할 거예요?", "Are you going to extend it?"), ("계약서가 하얘요.", "The contract is white."), ("지난달에 끝났어요.", "It ended last month."), ("다음 달이 좋아요.", "Next month is good.")],
     "A contract ending: ask about renewing it.", "laws-systems"),
    ("남", "공구는 쓰고 나서 제자리에 놓으세요.", "Put the tools back in their place after use.",
     [("네, 다 쓰고 정리하겠습니다.", "OK, I'll tidy up when I've finished."), ("공구가 많아요.", "There are many tools."), ("제자리에 앉을게요.", "I'll sit in my seat."), ("공구를 샀어요.", "I bought tools.")],
     "An instruction to put tools away: agree.", "tools-machines"),
    ("여", "버스 카드를 집에 놓고 왔어요.", "I've left my bus card at home.",
     [("제가 버스비를 빌려 드릴게요.", "I'll lend you the fare."), ("버스가 왔어요.", "The bus has come."), ("카드가 예뻐요.", "The card is pretty."), ("집이 커요.", "The house is big.")],
     "She can't pay the fare; offer to lend it.", "public-services"),
    ("남", "다음 주부터 한국어 수업이 시작돼요.", "Korean classes start next week.",
     [("저도 신청하고 싶어요. 어디에서 해요?", "I'd like to sign up too. Where is it?"), ("한국어가 쉬워요.", "Korean is easy."), ("수업이 끝났어요.", "The class is over."), ("지난주에 시작했어요.", "It started last week.")],
     "News of a class: ask to join.", "daily-life"),
    ("여", "이 음식 너무 매워요.", "This food is too spicy.",
     [("물 좀 드릴까요?", "Shall I get you some water?"), ("음식이 차가워요.", "The food is cold."), ("저는 매워요.", "I am spicy."), ("음식을 만들어요.", "I'm making food.")],
     "Too spicy: offer water.", "daily-life"),
    ("남", "작업장에 불이 났어요!", "There's a fire in the workshop!",
     [("빨리 밖으로 나가서 일일구에 전화하세요!", "Get outside quickly and call 119!"), ("불을 켜세요.", "Turn on the light."), ("작업이 끝났어요.", "The work is done."), ("불고기를 먹어요.", "I'm eating bulgogi.")],
     "In a fire, get out and call 119, Korea's fire and ambulance number.", "industrial-safety"),
    ("여", "은행이 네 시에 문을 닫아요.", "The bank closes at four.",
     [("그럼 지금 빨리 가야겠어요.", "Then I'd better go now."), ("은행이 열어요.", "The bank opens."), ("네 시에 일어나요.", "I get up at four."), ("돈이 많아요.", "I have a lot of money.")],
     "The bank closes soon, so hurry.", "public-services"),
    ("남", "오늘 작업은 여기까지 합시다.", "Let's stop work here for today.",
     [("수고하셨습니다. 내일 뵙겠습니다.", "Thanks for your hard work. See you tomorrow."), ("작업을 시작할게요.", "I'll start work."), ("여기는 공장이에요.", "This is a factory."), ("오늘은 월요일이에요.", "Today is Monday.")],
     "End of the working day: 수고하셨습니다 is the usual reply.", "workplace-culture"),
    ("여", "이번 달 월급이 조금 늦게 나온대요.", "They say this month's pay will be a bit late.",
     [("언제쯤 나온대요?", "When will it come, did they say?"), ("월급을 받았어요.", "I've been paid."), ("늦게 일어났어요.", "I got up late."), ("은행이에요.", "It's a bank.")],
     "Pay will be late: ask when it will come.", "job-korean"),
    ("남", "제 자리에 누가 가방을 놓았어요.", "Someone has put a bag on my seat.",
     [("아, 죄송해요. 제 가방이에요. 치울게요.", "Oh, sorry. It's my bag. I'll move it."), ("가방을 샀어요.", "I bought a bag."), ("자리가 넓어요.", "The seat is wide."), ("가방이 무거워요.", "The bag is heavy.")],
     "The owner of the bag apologises and moves it.", "daily-life"),
    ("여", "이 약을 먹으면 졸릴 수 있어요.", "This medicine may make you sleepy.",
     [("그럼 먹고 나서 운전하지 않을게요.", "Then I won't drive after taking it."), ("약이 달아요.", "The medicine is sweet."), ("잠을 잘 잤어요.", "I slept well."), ("약국에 가요.", "I'm going to the pharmacy.")],
     "A warning about drowsiness: avoid driving.", "public-services"),
    ("남", "오늘 오후에 사장님이 공장에 오세요.", "The boss is coming to the factory this afternoon.",
     [("그럼 작업장을 깨끗하게 청소해야겠어요.", "Then we'd better clean the workshop."), ("사장님이 가요.", "The boss is going."), ("오전에 왔어요.", "I came in the morning."), ("공장이 멀어요.", "The factory is far.")],
     "A visit is coming: get ready for it.", "workplace-culture"),
    ("여", "우리 팀이 이번 달 생산 목표를 달성했어요.", "Our team has hit this month's production target.",
     [("정말요? 모두 수고 많았어요.", "Really? Well done, everyone."), ("목표가 없어요.", "There's no target."), ("다음 달에 해요.", "We'll do it next month."), ("생산이 뭐예요?", "What's production?")],
     "Good news: congratulate the team.", "job-korean"),
    ("남", "문이 잠겨서 들어갈 수 없어요.", "The door's locked and I can't get in.",
     [("관리실에 열쇠가 있으니까 가 보세요.", "The management office has a key, so go there."), ("문을 잠갔어요.", "I locked the door."), ("들어오세요.", "Come in."), ("문이 커요.", "The door is big.")],
     "He can't get in: tell him where the key is.", "basic-life"),
    ("여", "이 컵은 일회용이 아니에요.", "This cup isn't disposable.",
     [("아, 그럼 씻어서 다시 쓸게요.", "Oh, then I'll wash it and use it again."), ("컵을 버릴게요.", "I'll throw the cup away."), ("컵이 예뻐요.", "The cup is pretty."), ("일회용 컵이에요.", "It's a disposable cup.")],
     "A reusable cup should be washed, not thrown away.", "basic-life"),
]

assert len(RESPONSE) == 48, len(RESPONSE)
assert len(NEXT) == 48, len(NEXT)
