"""Fill in the Blank: one or two sentences with a gap; four words or endings
of the same kind, one of which fits the meaning.

Each entry: (Korean text with the gap, English with ____ for the gap,
[(right word, English), then three wrong], note in English, topic tag,
difficulty).
"""

G = "(          )"

BLANKS = [
    (f"배가 고파서 식당에서 밥을 {G}.", "I was hungry, so I ____ at a restaurant.",
     [("먹었어요", "ate"), ("마셨어요", "drank"), ("입었어요", "wore"), ("씻었어요", "washed")],
     "You eat (먹다) rice; 마시다 is for drinks.", "daily-life", "easy"),
    (f"목이 말라요. 물을 {G}.", "I'm thirsty. I ____ water.",
     [("마시고 싶어요", "want to drink"), ("먹고 싶어요", "want to eat"), ("읽고 싶어요", "want to read"), ("타고 싶어요", "want to ride")],
     "Water is drunk: 마시다.", "daily-life", "easy"),
    (f"비가 오니까 {G}을 가지고 가세요.", "It's raining, so take an ____ with you.",
     [("우산", "umbrella"), ("안경", "glasses"), ("가방", "bag"), ("지갑", "wallet")],
     "Rain calls for an umbrella (우산).", "daily-life", "easy"),
    (f"내일은 일요일이라서 회사에 {G}.", "Tomorrow is Sunday, so I ____ to work.",
     [("안 가요", "don't go"), ("가요", "go"), ("일해요", "work"), ("출근해요", "go in")],
     "Sunday is a day off, so 안 가요.", "workplace-culture", "easy"),
    (f"방이 너무 어두워요. 불을 {G}.", "The room is too dark. ____ the light.",
     [("켜 주세요", "Please turn on"), ("꺼 주세요", "Please turn off"), ("닫아 주세요", "Please close"), ("버려 주세요", "Please throw away")],
     "A dark room needs the light on: 켜다.", "basic-life", "easy"),
    (f"햇빛이 강하니까 밖에서 일할 때는 {G}를 쓰세요.", "The sun is strong, so wear a ____ when you work outside.",
     [("모자", "hat"), ("장화", "pair of rubber boots"), ("앞치마", "apron"), ("넥타이", "tie")],
     "You wear (쓰다) a hat on your head against the sun.", "industrial-safety", "easy"),
    (f"먼지가 많은 곳에서는 {G}를 써야 합니다.", "Where there is a lot of dust you must wear a ____.",
     [("마스크", "face mask"), ("모자", "cap"), ("넥타이", "tie"), ("목도리", "scarf")],
     "A mask (마스크) keeps dust out of your nose and mouth.", "industrial-safety", "easy"),
    (f"한국에 온 지 일 년이 {G}.", "It ____ a year since I came to Korea.",
     [("되었어요", "has been"), ("왔어요", "came"), ("갔어요", "went"), ("살았어요", "lived")],
     "-ㄴ 지 … 되다 says how long it has been.", "grammar", "medium"),
    (f"저는 매일 아침 일곱 시에 {G}.", "I ____ at seven every morning.",
     [("일어나요", "get up"), ("자요", "sleep"), ("퇴근해요", "leave work"), ("저녁을 먹어요", "have dinner")],
     "Seven in the morning is when you get up.", "daily-life", "easy"),
    (f"이 옷은 너무 작아요. 더 {G} 옷 있어요?", "This is too small. Do you have a ____ one?",
     [("큰", "bigger"), ("작은", "smaller"), ("짧은", "shorter"), ("싼", "cheaper")],
     "Too small, so ask for a bigger one: 큰.", "daily-life", "easy"),
    (f"길을 몰라서 지나가는 사람에게 {G}.", "I didn't know the way, so I ____ a passer-by.",
     [("물어봤어요", "asked"), ("가르쳤어요", "taught"), ("팔았어요", "sold to"), ("때렸어요", "hit")],
     "Lost, you ask (물어보다) someone the way.", "daily-life", "easy"),
    (f"기계가 고장 나서 {G}를 불렀어요.", "The machine broke down, so I called a ____.",
     [("수리 기사", "repair engineer"), ("요리사", "cook"), ("의사", "doctor"), ("가수", "singer")],
     "A broken machine needs a repair engineer (수리 기사).", "tools-machines", "easy"),
    (f"작업이 끝나면 공구를 {G}에 넣어 두세요.", "When the work is done, put the tools away in the ____.",
     [("공구함", "toolbox"), ("냉장고", "fridge"), ("세탁기", "washing machine"), ("쓰레기통", "bin")],
     "Tools go in a toolbox (공구함).", "tools-machines", "easy"),
    (f"감기에 걸려서 {G}에 갔어요.", "I caught a cold, so I went to the ____.",
     [("병원", "doctor's"), ("은행", "bank"), ("우체국", "post office"), ("시장", "market")],
     "When you are ill you go to a clinic (병원).", "public-services", "easy"),
    (f"머리가 너무 길어서 {G}에 갔어요.", "My hair was too long, so I went to the ____.",
     [("미용실", "hairdresser's"), ("병원", "hospital"), ("도서관", "library"), ("우체국", "post office")],
     "You get your hair cut at a hairdresser's (미용실).", "daily-life", "easy"),
    (f"오늘은 일이 많아서 밤 아홉 시까지 {G}을 해야 해요.", "There's a lot of work today, so I have to do ____ until nine at night.",
     [("야근", "overtime"), ("휴식", "a rest"), ("출장", "a business trip"), ("면접", "an interview")],
     "Working late is 야근, overtime at night.", "workplace-culture", "medium"),
    (f"기름이 묻은 걸레는 불이 날 수 있으니까 {G}에 따로 버리세요.", "Oily rags can catch fire, so throw them away separately in a ____.",
     [("뚜껑이 있는 통", "bin with a lid"), ("냉장고", "fridge"), ("서랍", "drawer"), ("가방", "bag")],
     "Oily rags go in a closed bin (뚜껑이 있는 통) because they can catch fire.", "industrial-safety", "hard"),
    (f"월급은 매달 이십오 일에 {G}으로 들어와요.", "My pay goes into my ____ on the 25th of every month.",
     [("통장", "bank account"), ("가방", "bag"), ("지갑", "wallet"), ("서랍", "drawer")],
     "Pay is paid into a bank account (통장).", "job-korean", "medium"),
    (f"주말에 친구를 {G} 영화를 봤어요.", "At the weekend I ____ a friend and watched a film.",
     [("만나서", "met … and"), ("만들어서", "made … and"), ("팔아서", "sold … and"), ("보내서", "sent … and")],
     "-아서/어서 links two actions in order: met, then watched.", "grammar", "medium"),
    (f"이 상자는 {G} 혼자 들 수 없어요.", "This box is ____, so I can't lift it on my own.",
     [("무거워서", "heavy"), ("가벼워서", "light"), ("작아서", "small"), ("싸서", "cheap")],
     "A box you cannot lift alone is heavy: 무겁다 → 무거워서.", "grammar", "medium"),
    (f"날씨가 {G} 에어컨을 켰어요.", "It was ____, so I turned on the air conditioning.",
     [("더워서", "hot"), ("추워서", "cold"), ("시원해서", "cool"), ("흐려서", "cloudy")],
     "You turn on air conditioning when it is hot: 덥다 → 더워서.", "daily-life", "easy"),
    (f"버스를 놓쳐서 회사에 {G}.", "I missed the bus, so I was ____ for work.",
     [("늦었어요", "late"), ("일찍 왔어요", "early"), ("쉬었어요", "resting"), ("이사했어요", "moving house")],
     "Missing the bus makes you late: 늦다.", "workplace-culture", "easy"),
    (f"한국어를 잘하고 싶어서 매일 {G}.", "I want to be good at Korean, so I ____ every day.",
     [("공부해요", "study"), ("잊어버려요", "forget it"), ("쉬어요", "rest"), ("놀아요", "play")],
     "To get good at it, you study (공부하다).", "daily-life", "easy"),
    (f"위험하니까 기계가 움직일 때 손을 {G}.", "It's dangerous, so ____ your hand in while the machine is moving.",
     [("넣지 마세요", "don't put"), ("넣으세요", "put"), ("씻으세요", "wash"), ("드세요", "raise")],
     "-지 마세요 forbids it: keep hands out of moving machines.", "industrial-safety", "medium"),
    (f"화가 난 손님에게 \"{G}\"라고 말했어요.", "I said \"____\" to the angry customer.",
     [("죄송합니다", "I'm sorry"), ("축하합니다", "Congratulations"), ("잘 먹겠습니다", "Thank you for the meal"), ("안녕히 주무세요", "Good night")],
     "To an upset customer you apologise: 죄송합니다.", "workplace-culture", "easy"),
    (f"친구가 생일 선물을 줘서 \"{G}\"라고 했어요.", "My friend gave me a birthday present, so I said \"____\".",
     [("고맙습니다", "Thank you"), ("미안합니다", "I'm sorry"), ("괜찮습니다", "It's fine"), ("실례합니다", "Excuse me")],
     "You thank someone for a present: 고맙습니다.", "daily-life", "easy"),
    (f"사과를 다섯 {G} 샀어요.", "I bought five ____ of apples.",
     [("개", "(counter for things)"), ("명", "(counter for people)"), ("마리", "(counter for animals)"), ("권", "(counter for books)")],
     "Fruit and objects are counted with 개.", "numbers-time", "easy"),
    (f"우리 팀에는 직원이 열 {G} 있어요.", "There are ten ____ of staff in our team.",
     [("명", "(counter for people)"), ("개", "(counter for things)"), ("장", "(counter for sheets)"), ("대", "(counter for machines)")],
     "People are counted with 명.", "numbers-time", "easy"),
    (f"공장에 기계가 세 {G} 있어요.", "There are three ____ in the factory.",
     [("대", "machines (counter)"), ("명", "people (counter)"), ("마리", "animals (counter)"), ("병", "bottles (counter)")],
     "Machines and vehicles are counted with 대.", "numbers-time", "medium"),
    (f"농장에서 소를 스무 {G} 키워요.", "We raise twenty ____ on the farm.",
     [("마리", "head of cattle (counter)"), ("명", "people (counter)"), ("대", "machines (counter)"), ("권", "books (counter)")],
     "Animals are counted with 마리.", "numbers-time", "medium"),
    (f"서류에 이름을 쓰고 {G}을 하세요.", "Write your name on the form and add your ____.",
     [("서명", "signature"), ("계산", "a calculation"), ("운동", "exercise"), ("산책", "a walk")],
     "Forms are signed: 서명을 하다.", "laws-systems", "medium"),
    (f"외국인 근로자는 한국에 온 후 구십 일 안에 {G}을 해야 합니다.", "Foreign workers must complete ____ within ninety days of arriving in Korea.",
     [("외국인 등록", "alien registration"), ("결혼 신고", "marriage registration"), ("건강 검진", "a health check"), ("대학 입학", "university entry")],
     "Registering as a foreign resident (외국인 등록) is required within 90 days of entry.", "laws-systems", "hard"),
    (f"계약 기간이 끝나기 전에 회사를 옮기려면 {G}에 신청해야 해요.", "To change company before your contract ends you must apply to the ____.",
     [("고용센터", "job centre"), ("우체국", "post office"), ("편의점", "convenience store"), ("경찰서", "police station")],
     "Changes of workplace are handled by the job centre (고용센터).", "laws-systems", "hard"),
    (f"쓰레기는 종이, 플라스틱, 캔으로 {G} 버려야 합니다.", "Rubbish must be ____ into paper, plastic and cans before it is thrown away.",
     [("나눠서", "sorted"), ("모아서", "gathered"), ("태워서", "burned"), ("숨겨서", "hidden")],
     "In Korea rubbish is sorted (분리수거): 나눠서 버리다.", "basic-life", "medium"),
    (f"이 약은 식사 후 삼십 분 {G} 드세요.", "Take this medicine thirty minutes ____ meals.",
     [("뒤에", "after"), ("전부터", "from before"), ("동안", "during"), ("만에", "in")],
     "식후 삼십 분 뒤에: thirty minutes after eating.", "public-services", "medium"),
    (f"저는 매운 음식을 잘 {G}.", "I can't ____ spicy food well.",
     [("못 먹어요", "eat"), ("못 마셔요", "drink"), ("못 입어요", "wear"), ("못 들어요", "hear")],
     "Food goes with 먹다; 못 says you cannot.", "daily-life", "easy"),
    (f"오늘은 바람이 많이 불고 {G}.", "Today it's very windy and ____.",
     [("추워요", "cold"), ("맛있어요", "tasty"), ("비싸요", "expensive"), ("친절해요", "kind")],
     "Weather words: wind and cold go together.", "daily-life", "easy"),
    (f"안전모는 머리를 {G} 위해 씁니다.", "A safety helmet is worn to ____ your head.",
     [("보호하기", "protect"), ("자르기", "cut"), ("씻기", "wash"), ("말리기", "dry")],
     "-기 위해 gives the purpose: to protect (보호하다) the head.", "industrial-safety", "medium"),
    (f"지하철에서 내릴 때 문이 {G} 조심하세요.", "Be careful as the doors ____ when you get off the train.",
     [("닫히니까", "close"), ("먹으니까", "eat"), ("자니까", "sleep"), ("웃으니까", "laugh")],
     "Doors close: 닫히다.", "public-services", "medium"),
    (f"주문한 물건이 아직 {G}.", "The goods I ordered ____ yet.",
     [("안 왔어요", "haven't arrived"), ("왔어요", "arrived"), ("팔았어요", "sold"), ("먹었어요", "ate")],
     "아직 (not yet) goes with a negative: 안 왔어요.", "grammar", "medium"),
    (f"내일 아침 일찍 출발하니까 오늘은 일찍 {G}.", "We leave early tomorrow morning, so ____ early tonight.",
     [("주무세요", "go to bed"), ("일어나세요", "get up"), ("드세요", "eat"), ("오세요", "come")],
     "To leave early, sleep early: 주무세요 is the polite form of 자다.", "daily-life", "medium"),
    (f"이 일은 혼자 하기 어려우니까 동료에게 {G}을 요청하세요.", "This job is hard to do alone, so ask a co-worker for ____.",
     [("도움", "help"), ("돈", "money"), ("선물", "a present"), ("칭찬", "praise")],
     "Ask for help: 도움을 요청하다.", "workplace-culture", "medium"),
    (f"작업장에서 사고가 나면 바로 {G}에게 알려야 합니다.", "If there's an accident at work, you must tell the ____ immediately.",
     [("관리자", "manager"), ("손님", "customer"), ("친구", "friend"), ("가족", "family")],
     "Accidents at work are reported to the manager (관리자) at once.", "industrial-safety", "medium"),
    (f"계단을 내려갈 때는 {G}를 잡으세요.", "Hold the ____ when going down the stairs.",
     [("손잡이", "handrail"), ("의자", "chair"), ("바구니", "basket"), ("휴지", "tissue")],
     "Hold the handrail (손잡이) on stairs.", "industrial-safety", "easy"),
    (f"은행에서 돈을 찾으려면 {G}이 필요해요.", "You need a ____ to take money out at a bank.",
     [("신분증", "form of ID"), ("우산", "umbrella"), ("장갑", "gloves"), ("공책", "notebook")],
     "Banks ask for ID (신분증).", "public-services", "medium"),
    (f"일을 시작하기 전에 {G}을 꼭 입으세요.", "Be sure to put on your ____ before you start work.",
     [("작업복", "work clothes"), ("잠옷", "pyjamas"), ("수영복", "swimsuit"), ("한복", "hanbok")],
     "Work clothes (작업복) are worn at work.", "industrial-safety", "easy"),
    (f"시간이 없으니까 {G} 오세요.", "There's no time, so come ____.",
     [("빨리", "quickly"), ("천천히", "slowly"), ("늦게", "late"), ("내일", "tomorrow")],
     "No time, so hurry: 빨리.", "daily-life", "easy"),
    (f"오늘 처음 만난 사람에게 \"{G}\"라고 인사했어요.", "I greeted someone I met for the first time today with \"____\".",
     [("처음 뵙겠습니다", "How do you do"), ("잘 먹었습니다", "Thanks for the meal"), ("수고하셨습니다", "Good work today"), ("다녀오겠습니다", "I'm off")],
     "처음 뵙겠습니다 is said on first meeting.", "korean-culture", "medium"),
]

assert len(BLANKS) == 48, len(BLANKS)
