"""Correct Underlined Grammar: four sentences, each with one underlined part
(__x__); only one is correct. The wrong three are the slips learners make:
the wrong particle, a regular ending on an irregular verb, the wrong tense
or connector.

Each entry: ([(sentence, English meaning)] right one first, then three
wrong, note in English with the corrections, title, difficulty).
"""

GRAMMAR = [
    ([("저는 커피__를__ 마셔요.", "I drink coffee."), ("버스__을__ 타요.", "I take the bus."), ("도서관__에서__ 가요.", "I go to the library."), ("동생__에게서__ 선물을 줬어요.", "I gave my sibling a present.")],
     "커피를 마셔요 is right. It should be 버스를, 도서관에 가요 and 동생에게 줬어요.", "조사", "easy"),
    ([("친구__와__ 같이 일해요.", "I work with a friend."), ("의자__을__ 앉아요.", "I sit on the chair."), ("공원__를__ 걸어요.", "I walk in the park."), ("아침__에서__ 일어나요.", "I get up in the morning.")],
     "친구와 같이 is right. It should be 의자에 앉아요, 공원에서 걸어요 and 아침에 일어나요.", "조사", "easy"),
    ([("회사__에서__ 일해요.", "I work at the company."), ("회사__에__ 일해요.", "—"), ("회사__을__ 일해요.", "—"), ("회사__가__ 일해요.", "—")],
     "An action happens 에서: 회사에서 일해요. 에 marks where you go or where something is.", "조사", "easy"),
    ([("기숙사__에__ 살아요.", "I live in the dormitory."), ("기숙사__을__ 살아요.", "—"), ("기숙사__와__ 살아요.", "—"), ("기숙사__의__ 살아요.", "—")],
     "살다 takes 에 or 에서 for where you live: 기숙사에 살아요.", "조사", "easy"),
    ([("트럭에 짐을 __실어요__.", "I load the goods onto the lorry."), ("트럭에 짐을 __싣어요__.", "—"), ("트럭에 짐을 __싯어요__.", "—"), ("트럭에 짐을 __실으요__.", "—")],
     "싣다 is ㄷ-irregular: ㄷ becomes ㄹ before a vowel, so 실어요.", "불규칙 동사", "medium"),
    ([("날씨가 __추워요__.", "The weather is cold."), ("날씨가 __춥어요__.", "—"), ("날씨가 __추어요__.", "—"), ("날씨가 __춥워요__.", "—")],
     "춥다 is ㅂ-irregular: ㅂ becomes 우, so 추워요.", "불규칙 동사", "medium"),
    ([("이 상자가 __무거워요__.", "This box is heavy."), ("이 상자가 __무겁어요__.", "—"), ("이 상자가 __무거어요__.", "—"), ("이 상자가 __무겁워요__.", "—")],
     "무겁다 is ㅂ-irregular: 무거워요.", "불규칙 동사", "medium"),
    ([("길을 __걸어서__ 왔어요.", "I came on foot."), ("길을 __걷어서__ 왔어요.", "—"), ("길을 __걸서__ 왔어요.", "—"), ("길을 __겄어서__ 왔어요.", "—")],
     "걷다 is ㄷ-irregular: 걸어서.", "불규칙 동사", "medium"),
    ([("김치를 __만들어요__.", "I make kimchi."), ("김치를 __만드어요__.", "—"), ("김치를 __만들으요__.", "—"), ("김치를 __만드러요__.", "—")],
     "만들다 + 어요 = 만들어요; the ㄹ stays before 어.", "불규칙 동사", "medium"),
    ([("이 가방이 __예뻐요__.", "This bag is pretty."), ("이 가방이 __예쁘어요__.", "—"), ("이 가방이 __예뻐어요__.", "—"), ("이 가방이 __예쁘요__.", "—")],
     "예쁘다 drops ㅡ before 어: 예뻐요.", "불규칙 동사", "medium"),
    ([("배가 __고파요__.", "I'm hungry."), ("배가 __고프어요__.", "—"), ("배가 __고퍼요__.", "—"), ("배가 __고프요__.", "—")],
     "고프다 drops ㅡ and takes 아 after 오: 고파요.", "불규칙 동사", "medium"),
    ([("한국어를 __몰라요__.", "I don't know Korean."), ("한국어를 __모라요__.", "—"), ("한국어를 __모르아요__.", "—"), ("한국어를 __모르요__.", "—")],
     "모르다 is 르-irregular: 몰라요.", "불규칙 동사", "hard"),
    ([("어제 친구를 __만났어요__.", "I met a friend yesterday."), ("어제 친구를 __만나요__.", "—"), ("어제 친구를 __만날 거예요__.", "—"), ("어제 친구를 __만나겠어요__.", "—")],
     "어제 (yesterday) needs the past tense: 만났어요.", "시제", "easy"),
    ([("내일 고향에 __갈 거예요__.", "I'll go home tomorrow."), ("내일 고향에 __갔어요__.", "—"), ("내일 고향에 __갔었어요__.", "—"), ("내일 고향에 __가었어요__.", "—")],
     "내일 (tomorrow) needs the future: 갈 거예요.", "시제", "easy"),
    ([("지난주에 영화를 __봤어요__.", "I saw a film last week."), ("다음 주에 영화를 __봤어요__.", "I ... a film next week."), ("지금 영화를 __볼 거였어요__.", "I ... a film now."), ("내일 영화를 __봤었어요__.", "I ... a film tomorrow.")],
     "Only 지난주 (last week) fits a past tense.", "시제", "medium"),
    ([("지금 밥을 __먹고 있어요__.", "I'm eating now."), ("어제 밥을 __먹고 있어요__.", "—"), ("내일 밥을 __먹었어요__.", "—"), ("지금 밥을 __먹었을 거예요__.", "—")],
     "-고 있어요 is for something going on now: 지금 먹고 있어요.", "시제", "medium"),
    ([("비가 __와서__ 우산을 샀어요.", "It rained, so I bought an umbrella."), ("비가 __오지만__ 우산을 샀어요.", "—"), ("비가 __오고__ 우산을 샀어요.", "—"), ("비가 __오면__ 우산을 샀어요.", "—")],
     "-아서/어서 gives a reason: rain, so an umbrella.", "연결 어미", "medium"),
    ([("한국어는 어렵__지만__ 재미있어요.", "Korean is hard but fun."), ("한국어는 어렵__어서__ 재미있어요.", "—"), ("한국어는 어렵__고서__ 재미있어요.", "—"), ("한국어는 어렵__으면__ 재미있어요.", "—")],
     "Hard and fun are a contrast: -지만 (but).", "연결 어미", "medium"),
    ([("시간이 __있으면__ 같이 가요.", "If you have time, let's go together."), ("시간이 __있지만__ 같이 가요.", "—"), ("시간이 __있어서__ 같이 가요.", "—"), ("시간이 __있고__ 같이 가요.", "—")],
     "-으면 means if: 시간이 있으면.", "연결 어미", "medium"),
    ([("밥을 먹__고__ 커피를 마셨어요.", "I ate and then drank coffee."), ("밥을 먹__지만__ 커피를 마셨어요.", "—"), ("밥을 먹__으면__ 커피를 마셨어요.", "—"), ("밥을 먹__으러__ 커피를 마셨어요.", "—")],
     "-고 joins two actions in order: ate, then coffee.", "연결 어미", "easy"),
    ([("돈을 찾__으러__ 은행에 가요.", "I'm going to the bank to take out money."), ("돈을 찾__지만__ 은행에 가요.", "—"), ("돈을 찾__아서__ 은행에 가요.", "—"), ("돈을 찾__으면서__ 은행에 가요.", "—")],
     "-으러 + 가다 gives the purpose of going: to take out money.", "연결 어미", "medium"),
    ([("음악을 들__으면서__ 운동해요.", "I exercise while listening to music."), ("음악을 들__어서__ 운동해요.", "—"), ("음악을 들__지만__ 운동해요.", "—"), ("음악을 들__으러__ 운동해요.", "—")],
     "-으면서 means while, two actions at once.", "연결 어미", "medium"),
    ([("저는 술을 __안__ 마셔요.", "I don't drink alcohol."), ("저는 술을 __없__ 마셔요.", "—"), ("저는 술을 __아니__ 마셔요.", "—"), ("저는 술을 __말__ 마셔요.", "—")],
     "안 before a verb makes it negative: 안 마셔요.", "부정", "easy"),
    ([("기계 안에 손을 넣__지 마세요__.", "Don't put your hand inside the machine."), ("기계 안에 손을 넣__지 않으세요__.", "—"), ("기계 안에 손을 넣__지 못하세요__.", "—"), ("기계 안에 손을 넣__지 없어요__.", "—")],
     "-지 마세요 tells someone not to do something.", "부정", "medium"),
    ([("다리가 아파서 __못__ 걸어요.", "My leg hurts, so I can't walk."), ("다리가 아파서 __못하__ 걸어요.", "—"), ("다리가 아파서 __없__ 걸어요.", "—"), ("다리가 아파서 __아니__ 걸어요.", "—")],
     "못 says you cannot: 못 걸어요.", "부정", "medium"),
    ([("저는 한국 사람이 __아니에요__.", "I'm not Korean."), ("저는 한국 사람이 __안이에요__.", "—"), ("저는 한국 사람이 __없어요__.", "—"), ("저는 한국 사람이 __못해요__.", "—")],
     "The negative of 이에요 is 이/가 아니에요.", "부정", "easy"),
    ([("사장님께서 __오셨어요__.", "The boss has arrived."), ("사장님께서 __왔어__.", "—"), ("사장님께서 __와__.", "—"), ("사장님께서 __와라__.", "—")],
     "께서 calls for the honorific -시-: 오셨어요.", "높임말", "medium"),
    ([("할머니께서 __주무세요__.", "Grandmother is sleeping."), ("할머니께서 __자요__.", "—"), ("할머니께서 __자라__.", "—"), ("할머니께서 __잤어__.", "—")],
     "The honorific of 자다 is 주무시다: 주무세요.", "높임말", "medium"),
    ([("사장님, 커피 __드세요__.", "Boss, please have some coffee."), ("사장님, 커피 __먹어__.", "—"), ("사장님, 커피 __마셔라__.", "—"), ("사장님, 커피 __먹자__.", "—")],
     "Offer food or drink politely with 드세요.", "높임말", "medium"),
    ([("반장님__께__ 서류를 드렸어요.", "I gave the team leader the documents."), ("반장님__에__ 서류를 드렸어요.", "—"), ("반장님__께서__ 서류를 드렸어요.", "—"), ("반장님__을__ 서류를 드렸어요.", "—")],
     "To give to someone senior: 께 + 드리다.", "높임말", "hard"),
    ([("사과 __세 개__ 주세요.", "Three apples, please."), ("사과 __삼 개__ 주세요.", "—"), ("사과 __셋 개__ 주세요.", "—"), ("사과 __세 명__ 주세요.", "—")],
     "Counters take native numbers, and 셋 shortens to 세: 세 개.", "수 표현", "medium"),
    ([("직원이 __다섯 명__ 있어요.", "There are five staff."), ("직원이 __오 명__ 있어요.", "—"), ("직원이 __다섯 개__ 있어요.", "—"), ("직원이 __다섯 마리__ 있어요.", "—")],
     "People take 명 with native numbers: 다섯 명.", "수 표현", "medium"),
    ([("지금 __두 시__예요.", "It's two o'clock."), ("지금 __이 시__예요.", "—"), ("지금 __둘 시__예요.", "—"), ("지금 __두 분__예요.", "—")],
     "Hours use native numbers: 두 시.", "수 표현", "medium"),
    ([("이 옷은 __삼만 원__이에요.", "This costs 30,000 won."), ("이 옷은 __셋만 원__이에요.", "—"), ("이 옷은 __세만 원__이에요.", "—"), ("이 옷은 __삼만 개__예요.", "—")],
     "Money uses Sino-Korean numbers: 삼만 원.", "수 표현", "medium"),
    ([("제 방은 __삼 층__에 있어요.", "My room is on the third floor."), ("제 방은 __세 층__에 있어요.", "—"), ("제 방은 __셋 층__에 있어요.", "—"), ("제 방은 __삼 개__에 있어요.", "—")],
     "Floors use Sino-Korean numbers: 삼 층.", "수 표현", "medium"),
    ([("저는 축구를 __좋아해요__.", "I like football."), ("저는 축구가 __좋아해요__.", "—"), ("저는 축구를 __좋아요__.", "—"), ("저는 축구를 __좋았요__.", "—")],
     "좋아하다 takes an object (를); 좋다 takes 이/가.", "조사", "hard"),
    ([("저는 한국 음식이 __좋아요__.", "I like Korean food."), ("저는 한국 음식을 __좋아요__.", "—"), ("저는 한국 음식이 __좋아하요__.", "—"), ("저는 한국 음식이 __좋하요__.", "—")],
     "좋다 takes 이/가: 음식이 좋아요.", "조사", "hard"),
    ([("한국어를 __할 수 있어요__.", "I can speak Korean."), ("한국어를 __할 수 해요__.", "—"), ("한국어를 __하는 수 있어요__.", "—"), ("한국어를 __할 수가 해요__.", "—")],
     "-ㄹ 수 있다 says you can: 할 수 있어요.", "능력", "medium"),
    ([("여기에서 사진을 __찍어도 돼요__?", "May I take photos here?"), ("여기에서 사진을 __찍어도 해요__?", "—"), ("여기에서 사진을 __찍어서 돼요__?", "—"), ("여기에서 사진을 __찍도 돼요__?", "—")],
     "-아도/어도 돼요? asks permission: 찍어도 돼요?", "허락", "medium"),
    ([("작업 전에 안전모를 __써야 해요__.", "You have to wear a helmet before work."), ("작업 전에 안전모를 __쓰야 해요__.", "—"), ("작업 전에 안전모를 __써도 해요__.", "—"), ("작업 전에 안전모를 __씨야 해요__.", "—")],
     "쓰다 drops ㅡ: 써야 해요 (must wear).", "의무", "medium"),
    ([("저는 의사__가__ 되고 싶어요.", "I want to become a doctor."), ("저는 의사__를__ 되고 싶어요.", "—"), ("저는 의사__와__ 되고 싶어요.", "—"), ("저는 의사__에__ 되고 싶어요.", "—")],
     "되다 takes 이/가: 의사가 되고 싶어요.", "조사", "hard"),
    ([("저는 동생__보다__ 키가 커요.", "I'm taller than my younger sibling."), ("저는 동생__처럼__ 키가 커요.", "—"), ("저는 동생__부터__ 키가 커요.", "—"), ("저는 동생__까지__ 키가 커요.", "—")],
     "보다 compares: taller than my sibling.", "조사", "medium"),
    ([("아홉 시__부터__ 여섯 시까지 일해요.", "I work from nine until six."), ("아홉 시__에서__ 여섯 시부터 일해요.", "—"), ("아홉 시__까지__ 여섯 시부터 일해요.", "—"), ("아홉 시__보다__ 여섯 시까지 일해요.", "—")],
     "Time ranges use 부터 … 까지.", "조사", "medium"),
    ([("버스__로__ 회사에 가요.", "I go to work by bus."), ("버스__를__ 회사에 가요.", "—"), ("버스__에서__ 회사에 가요.", "—"), ("버스__와__ 회사에 가요.", "—")],
     "(으)로 marks the means of transport: 버스로.", "조사", "easy"),
    ([("볼펜__으로__ 이름을 쓰세요.", "Write your name with a pen."), ("볼펜__로__ 이름을 쓰세요.", "—"), ("볼펜__에__ 이름을 쓰세요.", "—"), ("볼펜__과__ 이름을 쓰세요.", "—")],
     "After a final consonant other than ㄹ, (으)로 is 으로: 볼펜으로.", "조사", "medium"),
    ([("주말에 같이 영화를 __볼까요__?", "Shall we see a film together at the weekend?"), ("주말에 같이 영화를 __봤을까요__?", "—"), ("주말에 같이 영화를 __보을까요__?", "—"), ("주말에 같이 영화를 __보겠을까요__?", "—")],
     "-ㄹ까요? suggests doing something together: 볼까요?", "제안", "medium"),
    ([("제가 창문을 __닫을게요__.", "I'll close the window."), ("제가 창문을 __닫으세요__.", "—"), ("제가 창문을 __닫겠을게요__.", "—"), ("제가 창문을 __닫게요__.", "—")],
     "-을게요 is a promise to do something: 닫을게요.", "의지", "medium"),
    ([("한국에 온 __지__ 이 년이 됐어요.", "It's been two years since I came to Korea."), ("한국에 온 __때__ 이 년이 됐어요.", "—"), ("한국에 온 __후에서__ 이 년이 됐어요.", "—"), ("한국에 온 __것__ 이 년이 됐어요.", "—")],
     "-ㄴ 지 + time + 되다 says how long since.", "시간 표현", "hard"),
]

assert len(GRAMMAR) == 48, len(GRAMMAR)
for options, *_ in GRAMMAR:
    assert all(text.count("__") == 2 for text, _ in options), options
