"""Signs, Notices and Charts: a drawn sign or notice and one question about
it. Safety signs follow the colours used on Korean worksites (red for
prohibition, yellow for warning, blue for things you must do, green for
information); the notices are the kind a worker meets at work and around town.

Each entry: (kind, header, lines, emoji or None, header and lines in English,
question in Korean, question in English, [(right answer, English), then three
wrong], note in English, topic tag, difficulty).
"""

SIGN_Q = ("이 표지의 뜻으로 알맞은 것은 무엇입니까?", "What does this sign mean?")

PRACTICAL = [
    # ---- prohibition (red)
    ("prohibition", "금연", ["이곳에서는", "담배를 피울 수", "없습니다."], "🚭", "No smoking. You may not smoke here.", *SIGN_Q,
     [("담배를 피우면 안 됩니다.", "You must not smoke."), ("담배를 팝니다.", "Cigarettes are sold here."), ("불이 났습니다.", "There is a fire."), ("담배를 피우는 곳입니다.", "This is a smoking area.")],
     "금연 means no smoking.", "industrial-safety", "easy"),
    ("prohibition", "출입 금지", ["관계자 외", "들어갈 수", "없습니다."], "⛔", "No entry. Authorised staff only.", *SIGN_Q,
     [("아무나 들어가면 안 됩니다.", "Not just anyone may go in."), ("누구나 들어갈 수 있습니다.", "Anyone may go in."), ("입구가 저쪽에 있습니다.", "The entrance is over there."), ("문을 닫지 마세요.", "Don't close the door.")],
     "출입 금지: no entry except for authorised people (관계자).", "industrial-safety", "easy"),
    ("prohibition", "사진 촬영 금지", ["이 구역에서는", "사진을 찍을", "수 없습니다."], "📵", "No photography. You may not take photos in this area.", *SIGN_Q,
     [("사진을 찍으면 안 됩니다.", "You must not take photos."), ("사진을 찍는 곳입니다.", "This is a photo spot."), ("휴대폰을 팝니다.", "Phones are sold here."), ("사진을 찍어 줍니다.", "Photos are taken for you.")],
     "촬영 금지: photography is forbidden.", "industrial-safety", "easy"),
    ("prohibition", "음식물 반입 금지", ["작업장 안으로", "음식을 가지고", "들어오지 마세요."], "🚫", "No food allowed. Do not bring food into the workplace.", *SIGN_Q,
     [("작업장에 음식을 가지고 오면 안 됩니다.", "Don't bring food into the workplace."), ("작업장에서 밥을 먹습니다.", "Meals are eaten in the workplace."), ("음식을 팝니다.", "Food is sold here."), ("음식을 버리는 곳입니다.", "This is where food is thrown away.")],
     "반입 금지: bringing it in is forbidden.", "industrial-safety", "medium"),
    ("prohibition", "화기 엄금", ["불을 사용하면", "안 됩니다.", "※ 폭발 위험"], "🔥", "No naked flames. Do not use fire. Danger of explosion.", *SIGN_Q,
     [("불을 사용하면 안 됩니다.", "You must not use fire."), ("불을 피워도 됩니다.", "You may light a fire."), ("요리하는 곳입니다.", "This is a cooking area."), ("소화기가 있습니다.", "There is an extinguisher here.")],
     "화기 엄금: fire is strictly forbidden.", "industrial-safety", "medium"),
    ("prohibition", "주차 금지", ["이곳에 차를", "세우지 마세요."], "🚗", "No parking. Do not park your car here.", *SIGN_Q,
     [("여기에 차를 세우면 안 됩니다.", "You must not park here."), ("차를 세우는 곳입니다.", "This is a car park."), ("차를 고치는 곳입니다.", "This is a garage."), ("차를 팝니다.", "Cars are sold here.")],
     "주차 금지: no parking.", "public-services", "easy"),
    ("prohibition", "탑승 금지", ["지게차에", "사람이 타면", "안 됩니다."], "🚜", "No riding. People must not ride on the forklift.", *SIGN_Q,
     [("지게차에 사람이 타면 안 됩니다.", "People must not ride on the forklift."), ("지게차를 타고 가세요.", "Ride on the forklift."), ("지게차를 고치세요.", "Repair the forklift."), ("지게차를 빌려줍니다.", "Forklifts are lent here.")],
     "탑승 금지: no riding on it.", "industrial-safety", "medium"),
    # ---- warning (yellow)
    ("warning", "미끄럼 주의", ["바닥이", "미끄럽습니다.", "천천히 걸으세요."], "⚠️", "Caution: slippery. The floor is slippery. Walk slowly.", *SIGN_Q,
     [("바닥이 미끄러우니까 조심하세요.", "Be careful, the floor is slippery."), ("뛰어도 됩니다.", "You may run."), ("바닥을 청소하세요.", "Clean the floor."), ("물을 마시세요.", "Drink water.")],
     "미끄럼 주의: watch out, slippery.", "industrial-safety", "easy"),
    ("warning", "낙하물 주의", ["위에서 물건이", "떨어질 수", "있습니다."], "⚠️", "Caution: falling objects. Things may fall from above.", *SIGN_Q,
     [("위에서 물건이 떨어질 수 있습니다.", "Things may fall from above."), ("물건을 버리세요.", "Throw things away."), ("물건을 위로 올리세요.", "Lift things up."), ("물건을 팝니다.", "Goods are sold here.")],
     "낙하물 is a falling object.", "industrial-safety", "medium"),
    ("warning", "지게차 주의", ["지게차가", "다니는 길입니다.", "좌우를 살피세요."], "⚠️", "Caution: forklifts. Forklifts use this route. Look both ways.", *SIGN_Q,
     [("지게차가 다니니까 조심하세요.", "Watch out for forklifts."), ("지게차를 세우는 곳입니다.", "This is forklift parking."), ("지게차를 타세요.", "Get on the forklift."), ("사람만 다니는 길입니다.", "This path is for people only.")],
     "Forklifts pass here; look left and right.", "industrial-safety", "easy"),
    ("warning", "고온 주의", ["뜨거우니까", "손대지 마세요."], "⚠️", "Caution: hot. It's hot, so don't touch.", *SIGN_Q,
     [("뜨거우니까 만지면 안 됩니다.", "It's hot, so don't touch it."), ("차가우니까 조심하세요.", "It's cold, so be careful."), ("손을 씻으세요.", "Wash your hands."), ("불을 켜세요.", "Turn on the light.")],
     "고온 means high temperature.", "industrial-safety", "easy"),
    ("warning", "끼임 주의", ["기계에 손이", "끼일 수 있습니다."], "⚠️", "Caution: trapping hazard. Your hand may get caught in the machine.", *SIGN_Q,
     [("기계에 손이 끼일 수 있으니까 조심하세요.", "Careful, your hand could get caught."), ("기계를 끄세요.", "Turn off the machine."), ("기계가 고장 났습니다.", "The machine is broken."), ("손을 넣으세요.", "Put your hand in.")],
     "끼임: getting caught or trapped.", "industrial-safety", "medium"),
    ("warning", "추락 주의", ["높은 곳에서", "떨어질 수", "있습니다."], "⚠️", "Caution: risk of falling. You could fall from height.", *SIGN_Q,
     [("높은 곳에서 떨어질 수 있습니다.", "You could fall from a height."), ("물건이 떨어집니다.", "Things are falling."), ("높은 곳에 올라가세요.", "Climb up high."), ("계단이 없습니다.", "There are no stairs.")],
     "추락: a person falling from height.", "industrial-safety", "medium"),
    ("warning", "독극물 주의", ["몸에 닿거나", "마시면", "위험합니다."], "☠️", "Caution: poison. Dangerous if it touches you or is swallowed.", *SIGN_Q,
     [("독이 있어서 위험합니다.", "It is poisonous and dangerous."), ("마셔도 되는 물입니다.", "This water is safe to drink."), ("약을 파는 곳입니다.", "Medicine is sold here."), ("손을 씻는 곳입니다.", "This is for washing hands.")],
     "독극물 means poison.", "industrial-safety", "medium"),
    # ---- mandatory (blue)
    ("mandatory", "안전모 착용", ["작업할 때는", "안전모를 꼭", "쓰세요."], "⛑️", "Wear a safety helmet. Always wear a helmet when working.", *SIGN_Q,
     [("안전모를 써야 합니다.", "You must wear a helmet."), ("모자를 벗으세요.", "Take off your hat."), ("안전모를 팝니다.", "Helmets are sold here."), ("머리를 감으세요.", "Wash your hair.")],
     "착용 means wearing.", "industrial-safety", "easy"),
    ("mandatory", "보안경 착용", ["눈 보호를 위해", "보안경을", "쓰세요."], "🥽", "Wear safety goggles to protect your eyes.", *SIGN_Q,
     [("보안경을 써야 합니다.", "You must wear goggles."), ("안경을 벗으세요.", "Take off your glasses."), ("눈을 감으세요.", "Close your eyes."), ("안경을 고칩니다.", "Glasses are repaired here.")],
     "보안경 착용: wear goggles.", "industrial-safety", "easy"),
    ("mandatory", "안전화 착용", ["이 구역에서는", "안전화를", "신으세요."], "🥾", "Wear safety shoes in this area.", *SIGN_Q,
     [("안전화를 신어야 합니다.", "You must wear safety shoes."), ("신발을 벗으세요.", "Take off your shoes."), ("신발을 팝니다.", "Shoes are sold here."), ("맨발로 다니세요.", "Go barefoot.")],
     "안전화 착용: wear safety shoes.", "industrial-safety", "easy"),
    ("mandatory", "마스크 착용", ["먼지가 많으니까", "마스크를", "쓰세요."], "😷", "Wear a mask. It's dusty, so wear a mask.", *SIGN_Q,
     [("마스크를 써야 합니다.", "You must wear a mask."), ("마스크를 버리세요.", "Throw your mask away."), ("창문을 닫으세요.", "Close the window."), ("청소를 하지 마세요.", "Don't clean.")],
     "마스크 착용: wear a mask.", "industrial-safety", "easy"),
    ("mandatory", "보호 장갑 착용", ["손을 보호하기", "위해 장갑을", "끼세요."], "🧤", "Wear protective gloves to protect your hands.", *SIGN_Q,
     [("장갑을 껴야 합니다.", "You must wear gloves."), ("장갑을 벗으세요.", "Take off your gloves."), ("손을 씻으세요.", "Wash your hands."), ("장갑을 빌려줍니다.", "Gloves are lent here.")],
     "장갑을 끼다: to put on gloves.", "industrial-safety", "easy"),
    ("mandatory", "귀마개 착용", ["소음이 심한", "곳입니다.", "귀마개를 하세요."], "🔊", "Wear earplugs. This is a very noisy place.", *SIGN_Q,
     [("시끄러우니까 귀마개를 해야 합니다.", "It's noisy, so you must wear earplugs."), ("조용히 하세요.", "Be quiet."), ("음악을 들으세요.", "Listen to music."), ("소리를 크게 하세요.", "Turn the volume up.")],
     "소음 means noise.", "industrial-safety", "medium"),
    # ---- information (green)
    ("info", "비상구", ["불이 나면", "이쪽으로", "나가세요."], "🏃", "Emergency exit. In a fire, go out this way.", *SIGN_Q,
     [("위험할 때 나가는 문입니다.", "This is the way out in an emergency."), ("들어가는 문입니다.", "This is the way in."), ("화장실입니다.", "This is the toilet."), ("불을 끄는 곳입니다.", "This is where fires are put out.")],
     "비상구 is an emergency exit.", "industrial-safety", "easy"),
    ("info", "응급 처치함", ["다쳤을 때", "쓰는 약과", "붕대가 있습니다."], "🩹", "First aid box. Medicine and bandages for injuries.", *SIGN_Q,
     [("다쳤을 때 쓰는 물건이 있습니다.", "There are things for injuries here."), ("공구를 넣는 곳입니다.", "Tools are kept here."), ("약을 파는 곳입니다.", "Medicine is sold here."), ("병원 입구입니다.", "This is a hospital entrance.")],
     "응급 처치 is first aid.", "industrial-safety", "medium"),
    ("info", "대피 장소", ["지진이나 화재 때", "이곳으로", "모이세요."], "📍", "Assembly point. Gather here in an earthquake or fire.", *SIGN_Q,
     [("위험할 때 모이는 곳입니다.", "This is where to gather in an emergency."), ("주차장입니다.", "This is a car park."), ("운동하는 곳입니다.", "This is for exercise."), ("쉬는 곳입니다.", "This is a rest area.")],
     "대피 장소: where you evacuate to.", "industrial-safety", "medium"),
    # ---- notices (blue header)
    ("notice", "회사 식당 이용 안내", ["아침  07:00~08:00", "점심  12:00~13:00", "저녁  18:00~19:00", "※ 주말에는 쉽니다."], None,
     "Company canteen hours. Breakfast 7–8, lunch 12–1, dinner 6–7. Closed at weekends.",
     "이 식당에 대한 설명으로 맞는 것은 무엇입니까?", "Which is true of this canteen?",
     [("주말에는 식당을 이용할 수 없습니다.", "The canteen can't be used at weekends."), ("저녁은 일곱 시에 시작합니다.", "Dinner starts at seven."), ("점심시간은 두 시간입니다.", "Lunch is two hours."), ("아침은 주지 않습니다.", "No breakfast is served.")],
     "※ 주말에는 쉽니다: closed at weekends.", "workplace-culture", "easy"),
    ("notice", "미용실 영업 시간", ["평일  10:00~20:00", "토요일  10:00~15:00", "※ 화요일 휴무"], None,
     "Hair salon hours. Weekdays 10 a.m.–8 p.m. Saturday 10 a.m.–3 p.m. Closed Tuesdays.",
     "토요일에 이 미용실은 몇 시에 문을 닫습니까?", "What time does the salon close on Saturday?",
     [("오후 세 시", "3 p.m."), ("오후 여덟 시", "8 p.m."), ("오전 열 시", "10 a.m."), ("문을 열지 않습니다", "It doesn't open.")],
     "토요일 10:00~15:00: it closes at 3 p.m.", "daily-life", "easy"),
    ("notice", "분리수거 안내", ["월·수·금: 플라스틱, 캔", "화·목: 종이", "음식물: 매일", "※ 일요일은 버리지 마세요."], None,
     "Recycling. Mon/Wed/Fri: plastic and cans. Tue/Thu: paper. Food waste: every day. Do not put rubbish out on Sundays.",
     "종이는 언제 버립니까?", "When does paper go out?",
     [("화요일과 목요일", "Tuesday and Thursday"), ("월요일과 수요일", "Monday and Wednesday"), ("매일", "Every day"), ("일요일", "Sunday")],
     "화·목: 종이: paper on Tuesdays and Thursdays.", "basic-life", "medium"),
    ("notice", "기숙사 생활 규칙", ["밤 11시 이후 조용히", "방에서 요리 금지", "흡연은 밖에서만", "※ 외박할 때는 미리 알리기"], None,
     "Dormitory rules. Quiet after 11 p.m. No cooking in rooms. Smoking outside only. Tell staff in advance if you stay out overnight.",
     "이 규칙에 맞는 것은 무엇입니까?", "Which follows these rules?",
     [("외박하기 전에 미리 알립니다.", "Telling staff before staying out overnight."), ("방에서 라면을 끓입니다.", "Cooking noodles in your room."), ("밤 열두 시에 노래를 부릅니다.", "Singing at midnight."), ("방에서 담배를 피웁니다.", "Smoking in your room.")],
     "외박할 때는 미리 알리기: tell staff before an overnight stay.", "basic-life", "medium"),
    ("notice", "통근 버스 시간표", ["기숙사 출발  07:20", "공장 도착  07:50", "공장 출발  18:10", "기숙사 도착  18:40"], None,
     "Shuttle bus timetable. Leaves dorm 7:20, arrives factory 7:50. Leaves factory 18:10, arrives dorm 18:40.",
     "기숙사에서 공장까지 얼마나 걸립니까?", "How long does it take from the dormitory to the factory?",
     [("삼십 분", "Thirty minutes"), ("이십 분", "Twenty minutes"), ("한 시간", "An hour"), ("십 분", "Ten minutes")],
     "7:20 to 7:50 is thirty minutes.", "numbers-time", "medium"),
    ("notice", "건강 검진 안내", ["날짜: 5월 20일(수)", "시간: 오전 9시~12시", "장소: 2층 회의실", "※ 전날 밤부터 금식"], None,
     "Health check. Date: Wednesday 20 May. Time: 9 a.m.–12 noon. Place: 2nd floor meeting room. No food from the night before.",
     "건강 검진에 대한 설명으로 맞는 것은 무엇입니까?", "Which is true of the health check?",
     [("검진 전날 밤부터 음식을 먹으면 안 됩니다.", "No eating from the night before."), ("검진은 오후에 합니다.", "It's in the afternoon."), ("검진은 병원에서 합니다.", "It's at a hospital."), ("검진은 목요일에 합니다.", "It's on Thursday.")],
     "※ 전날 밤부터 금식: fast from the night before.", "public-services", "medium"),
    ("notice", "휴가 신청 방법", ["① 신청서 쓰기", "② 반장님 사인 받기", "③ 사무실에 내기", "※ 1주일 전까지"], None,
     "How to apply for leave. 1. Fill in the form. 2. Get the team leader's signature. 3. Hand it in at the office. At least one week before.",
     "휴가를 신청할 때 두 번째로 하는 일은 무엇입니까?", "What is the second step in applying for leave?",
     [("반장님 사인을 받습니다.", "Get the team leader's signature."), ("신청서를 씁니다.", "Fill in the form."), ("사무실에 냅니다.", "Hand it to the office."), ("사장님께 전화합니다.", "Phone the boss.")],
     "② 반장님 사인 받기 is step two.", "workplace-culture", "medium"),
    ("notice", "한국어 교실", ["매주 일요일 14:00~16:00", "시민 센터 3층", "외국인 근로자 무료", "※ 교재 무료 제공"], None,
     "Korean class. Every Sunday 2–4 p.m. Civic Centre, 3rd floor. Free for foreign workers. Textbooks provided free.",
     "이 수업에 대한 설명으로 맞는 것은 무엇입니까?", "Which is true of this class?",
     [("교재를 사지 않아도 됩니다.", "You don't need to buy the textbook."), ("수업은 토요일에 합니다.", "Classes are on Saturdays."), ("수업료를 내야 합니다.", "There's a fee."), ("수업은 세 시간입니다.", "Classes last three hours.")],
     "교재 무료 제공: textbooks are free.", "daily-life", "easy"),
    ("notice", "엘리베이터 점검", ["오늘 14:00~16:00", "엘리베이터 사용 불가", "계단을 이용해 주세요."], None,
     "Lift inspection. Today 2–4 p.m. The lift cannot be used. Please use the stairs.",
     "오후 세 시에 이 건물에서 어떻게 올라갑니까?", "How do you go up in this building at 3 p.m.?",
     [("계단으로 올라갑니다.", "By the stairs."), ("엘리베이터를 탑니다.", "By lift."), ("올라갈 수 없습니다.", "You can't go up."), ("에스컬레이터를 탑니다.", "By escalator.")],
     "3 p.m. falls in the 2–4 p.m. inspection, so take the stairs.", "basic-life", "medium"),
    ("notice", "택배 보관 안내", ["택배는 경비실에서 보관", "찾는 시간: 18:00~22:00", "※ 이름, 방 번호 확인"], None,
     "Parcel storage. Parcels are kept at the security office. Collection: 6–10 p.m. Name and room number checked.",
     "택배를 찾을 수 있는 시간은 언제입니까?", "When can parcels be collected?",
     [("저녁 여섯 시부터 열 시까지", "6 to 10 p.m."), ("아침 여섯 시부터", "From 6 a.m."), ("하루 종일", "All day"), ("밤 열 시 이후", "After 10 p.m.")],
     "찾는 시간: 18:00~22:00.", "basic-life", "easy"),
    ("notice", "버스 요금", ["교통카드  1,500원", "현금  1,600원", "어린이  800원", "※ 환승 할인 (카드만)"], None,
     "Bus fares. Transport card 1,500 won. Cash 1,600 won. Children 800 won. Transfer discount with card only.",
     "어른이 교통카드로 내면 얼마입니까?", "How much does an adult pay by transport card?",
     [("1,500원", "1,500 won"), ("1,600원", "1,600 won"), ("800원", "800 won"), ("무료", "Free")],
     "교통카드 1,500원.", "numbers-time", "easy"),
    ("notice", "도서관 이용 안내", ["화~일 09:00~18:00", "※ 월요일 휴관", "대출: 5권 / 2주"], None,
     "Library. Tuesday–Sunday 9 a.m.–6 p.m. Closed Mondays. Loans: 5 books for 2 weeks.",
     "이 도서관에 대한 설명으로 맞는 것은 무엇입니까?", "Which is true of this library?",
     [("월요일에는 문을 열지 않습니다.", "It's closed on Mondays."), ("일요일에는 쉽니다.", "It's closed on Sundays."), ("책을 열 권 빌릴 수 있습니다.", "You can borrow ten books."), ("밤 아홉 시에 문을 닫습니다.", "It closes at 9 p.m.")],
     "※ 월요일 휴관: closed Mondays.", "public-services", "easy"),
    ("notice", "세탁실 이용 요금", ["세탁기  3,000원 (50분)", "건조기  2,000원 (40분)", "※ 동전만 사용"], None,
     "Laundry room. Washer 3,000 won (50 min). Dryer 2,000 won (40 min). Coins only.",
     "세탁기와 건조기를 모두 쓰면 얼마입니까?", "How much to use both the washer and the dryer?",
     [("5,000원", "5,000 won"), ("3,000원", "3,000 won"), ("2,000원", "2,000 won"), ("6,000원", "6,000 won")],
     "3,000 + 2,000 = 5,000 won.", "numbers-time", "medium"),
    ("notice", "공장 견학 안내", ["견학 시간: 10:00, 14:00", "소요 시간: 1시간", "※ 안전모 착용 필수", "※ 사진 촬영 금지"], None,
     "Factory tours. Times: 10:00 and 14:00. Length: 1 hour. Safety helmet required. No photography.",
     "견학할 때 해야 하는 것은 무엇입니까?", "What must you do on the tour?",
     [("안전모를 씁니다.", "Wear a helmet."), ("사진을 찍습니다.", "Take photos."), ("두 시간 동안 봅니다.", "Watch for two hours."), ("저녁에 갑니다.", "Go in the evening.")],
     "※ 안전모 착용 필수: a helmet is required.", "industrial-safety", "medium"),
    ("notice", "고용센터 상담 안내", ["평일 09:00~18:00", "토요일 10:00~13:00", "통역: 베트남어, 네팔어", "※ 상담 무료"], None,
     "Job centre advice. Weekdays 9 a.m.–6 p.m. Saturday 10 a.m.–1 p.m. Interpreting: Vietnamese, Nepali. Advice is free.",
     "이 안내문의 내용과 같은 것을 고르십시오.", "Which matches the notice?",
     [("토요일 오전에도 상담할 수 있습니다.", "Advice is available on Saturday morning."), ("일요일에도 상담합니다.", "Advice is given on Sundays."), ("상담료를 내야 합니다.", "You must pay for advice."), ("영어 통역만 있습니다.", "Only English interpreting.")],
     "토요일 10:00~13:00: open Saturday morning.", "laws-systems", "medium"),
    ("notice", "단수 안내", ["5월 3일(화) 09:00~15:00", "물이 나오지 않습니다.", "※ 미리 물을 받아 두세요."], None,
     "Water cut. Tuesday 3 May, 9 a.m.–3 p.m. There will be no water. Please store some water in advance.",
     "이 안내문을 보고 미리 해야 할 일은 무엇입니까?", "What should you do in advance?",
     [("물을 받아 둡니다.", "Store some water."), ("전기를 끕니다.", "Turn off the electricity."), ("창문을 닫습니다.", "Close the windows."), ("가스를 잠급니다.", "Turn off the gas.")],
     "※ 미리 물을 받아 두세요: store water beforehand.", "basic-life", "medium"),
    ("notice", "회사 체육 대회", ["일시: 10월 12일(토)", "장소: 시민 운동장", "종목: 축구, 줄다리기", "※ 점심 제공"], None,
     "Company sports day. Saturday 12 October. Place: Civic Stadium. Events: football, tug of war. Lunch provided.",
     "체육 대회에 대한 설명으로 맞는 것은 무엇입니까?", "Which is true of the sports day?",
     [("점심을 줍니다.", "Lunch is provided."), ("회사 안에서 합니다.", "It's held at the company."), ("일요일에 합니다.", "It's on Sunday."), ("농구를 합니다.", "There's basketball.")],
     "※ 점심 제공: lunch is provided.", "workplace-culture", "easy"),
    ("notice", "월급 명세서", ["기본급  2,100,000원", "연장 수당  300,000원", "공제  -200,000원", "실수령액  2,200,000원"], None,
     "Payslip. Basic pay 2,100,000 won. Overtime 300,000 won. Deductions −200,000 won. Take-home pay 2,200,000 won.",
     "이 사람이 통장으로 받는 돈은 얼마입니까?", "How much does this person receive in their account?",
     [("2,200,000원", "2,200,000 won"), ("2,100,000원", "2,100,000 won"), ("2,400,000원", "2,400,000 won"), ("300,000원", "300,000 won")],
     "실수령액 (take-home pay) is 2,200,000 won.", "job-korean", "hard"),
    ("notice", "마트 할인 행사", ["과일·채소 20% 할인", "매주 수요일", "※ 3만 원 이상 무료 배달"], None,
     "Supermarket offer. 20% off fruit and vegetables every Wednesday. Free delivery on orders over 30,000 won.",
     "할인은 언제 합니까?", "When is the discount?",
     [("매주 수요일", "Every Wednesday"), ("매일", "Every day"), ("주말", "At weekends"), ("한 달에 한 번", "Once a month")],
     "매주 수요일: every Wednesday.", "daily-life", "easy"),
    ("notice", "작업 순서", ["① 전원 끄기", "② 기계 청소하기", "③ 공구 정리하기", "④ 퇴근 기록하기"], None,
     "End-of-shift order. 1. Turn off the power. 2. Clean the machine. 3. Put tools away. 4. Clock out.",
     "공구를 정리한 다음에 하는 일은 무엇입니까?", "What comes after putting the tools away?",
     [("퇴근 기록을 합니다.", "Clock out."), ("전원을 끕니다.", "Turn off the power."), ("기계를 청소합니다.", "Clean the machine."), ("기계를 켭니다.", "Turn the machine on.")],
     "③ 공구 정리하기 is followed by ④ 퇴근 기록하기, clocking out.", "industrial-safety", "medium"),
    ("notice", "병원 진료 시간", ["평일 09:00~18:00", "점심 13:00~14:00", "토요일 09:00~13:00", "※ 일요일 휴진"], None,
     "Clinic hours. Weekdays 9 a.m.–6 p.m. Lunch 1–2 p.m. Saturday 9 a.m.–1 p.m. Closed Sundays.",
     "평일 오후 한 시 반에 병원에 가면 어떻게 됩니까?", "What happens if you go at 1:30 p.m. on a weekday?",
     [("점심시간이라서 기다려야 합니다.", "It's lunch break, so you must wait."), ("바로 진료를 받습니다.", "You're seen right away."), ("병원이 문을 닫았습니다.", "The clinic has closed for the day."), ("토요일에만 진료합니다.", "It only opens on Saturdays.")],
     "13:00–14:00 is lunch, so you wait until two.", "public-services", "hard"),
    ("notice", "지하철 2호선", ["시청 → 을지로 → 동대문", "첫차 05:30  막차 24:00", "※ 5분마다 운행"], None,
     "Underground Line 2. City Hall → Euljiro → Dongdaemun. First train 5:30, last train midnight. Every 5 minutes.",
     "이 지하철은 얼마나 자주 옵니까?", "How often does this train come?",
     [("오 분마다", "Every five minutes"), ("십 분마다", "Every ten minutes"), ("삼십 분마다", "Every thirty minutes"), ("한 시간마다", "Every hour")],
     "※ 5분마다 운행: every five minutes.", "public-services", "easy"),
    ("notice", "추석 연휴 안내", ["연휴: 9월 28일~30일", "10월 1일부터 정상 근무", "※ 연휴 중 통근 버스 없음"], None,
     "Chuseok holiday. Holiday: 28–30 September. Normal work from 1 October. No shuttle bus during the holiday.",
     "이 안내문의 내용과 같은 것을 고르십시오.", "Which matches the notice?",
     [("연휴 동안 통근 버스가 다니지 않습니다.", "No shuttle bus runs during the holiday."), ("연휴는 10월 1일에 시작합니다.", "The holiday starts on 1 October."), ("연휴는 일주일입니다.", "The holiday lasts a week."), ("9월 30일에 출근합니다.", "Work on 30 September.")],
     "※ 연휴 중 통근 버스 없음.", "korean-culture", "medium"),
    ("notice", "분실물 보관", ["검은색 지갑 (식당)", "파란색 우산 (휴게실)", "찾는 곳: 경비실"], None,
     "Lost property. Black wallet (canteen). Blue umbrella (break room). Collect from the security office.",
     "우산은 어디에서 찾았습니까?", "Where was the umbrella found?",
     [("휴게실", "In the break room"), ("식당", "In the canteen"), ("경비실", "At the security office"), ("화장실", "In the toilet")],
     "파란색 우산 (휴게실): found in the break room.", "daily-life", "medium"),
    ("notice", "출입 시간 안내", ["기숙사 출입: 06:00~24:00", "※ 밤 12시 이후 출입 금지", "※ 늦을 때는 관리실에 연락"], None,
     "Dormitory hours. Entry 6 a.m.–midnight. No entry after midnight. If you'll be late, call the management office.",
     "늦게 들어올 때 해야 하는 일은 무엇입니까?", "What should you do if you'll be back late?",
     [("관리실에 연락합니다.", "Contact the management office."), ("창문으로 들어옵니다.", "Come in through a window."), ("친구 방에서 잡니다.", "Sleep in a friend's room."), ("아침 여섯 시에 연락합니다.", "Call at 6 a.m.")],
     "※ 늦을 때는 관리실에 연락.", "basic-life", "easy"),
]

assert len(PRACTICAL) == 48, len(PRACTICAL)
