"""Matching Statement: a short notice, message or passage; the learner picks
the statement that agrees with it. The wrong three change one fact: a time,
a day, a number, who does what.

Each entry: (Korean passage, English passage, [(right statement, English),
then three wrong], note in English, topic tag, difficulty).
"""

DETAILS = [
    ("저는 네팔에서 온 비노드입니다. 한국에 온 지 이 년이 되었습니다. 지금 김해에 있는 가구 공장에서 일합니다. 주말에는 친구들과 축구를 합니다.",
     "I'm Binod from Nepal. It's been two years since I came to Korea. I now work at a furniture factory in Gimhae. At weekends I play football with friends.",
     [("가구 공장에서 일합니다.", "He works at a furniture factory."), ("한국에 온 지 일 년이 되었습니다.", "He came to Korea a year ago."), ("주말에도 일을 합니다.", "He works at weekends too."), ("베트남에서 왔습니다.", "He is from Vietnam.")],
     "He works at a furniture factory; he came two years ago, from Nepal.", "basic-life", "easy"),
    ("이번 주 금요일에 회사 회식이 있습니다. 장소는 회사 앞 고깃집이고 저녁 일곱 시에 시작합니다. 참석할 수 있는 사람은 목요일까지 반장님께 말씀해 주세요.",
     "There's a staff dinner this Friday. It's at the barbecue restaurant in front of the company and starts at 7 p.m. If you can come, tell the team leader by Thursday.",
     [("참석하려면 목요일까지 말해야 합니다.", "To attend you must say so by Thursday."), ("회식은 목요일에 합니다.", "The dinner is on Thursday."), ("회식은 회사 식당에서 합니다.", "It's in the company canteen."), ("회식은 여섯 시에 시작합니다.", "It starts at six.")],
     "Tell the team leader by Thursday; the dinner itself is Friday at seven.", "workplace-culture", "easy"),
    ("우리 기숙사는 방 하나에 두 명이 삽니다. 방마다 화장실이 있고 부엌은 일 층에 같이 씁니다. 세탁기는 지하에 있습니다.",
     "Two people live in each room of our dormitory. Every room has its own bathroom, and the kitchen on the ground floor is shared. The washing machines are in the basement.",
     [("부엌은 같이 씁니다.", "The kitchen is shared."), ("방마다 부엌이 있습니다.", "Each room has a kitchen."), ("한 방에 세 명이 삽니다.", "Three people share a room."), ("세탁기는 일 층에 있습니다.", "The washing machines are on the ground floor.")],
     "The kitchen on the first floor is shared (같이 씁니다).", "basic-life", "easy"),
    ("[안내] 다음 주 월요일부터 수요일까지 공장 기계 점검이 있습니다. 이 기간에는 일 라인만 작업합니다. 이 라인 근무자는 사흘 동안 쉽니다.",
     "[Notice] From next Monday to Wednesday the factory machines will be inspected. During this time only Line 1 will run. Line 2 workers will have three days off.",
     [("이 라인 근무자는 사흘 동안 쉽니다.", "Line 2 workers get three days off."), ("기계 점검은 일주일 동안 합니다.", "The inspection lasts a week."), ("일 라인은 쉽니다.", "Line 1 stops."), ("점검은 목요일에 끝납니다.", "The inspection ends on Thursday.")],
     "Monday to Wednesday is three days; Line 2 rests, Line 1 works.", "workplace-culture", "medium"),
    ("저는 매일 아침 여섯 시에 일어나서 회사 버스를 탑니다. 회사까지 삼십 분쯤 걸립니다. 일은 여덟 시에 시작해서 다섯 시에 끝납니다.",
     "I get up at six every morning and take the company bus. It takes about thirty minutes to get to work. Work starts at eight and ends at five.",
     [("일은 여덟 시에 시작합니다.", "Work starts at eight."), ("회사까지 한 시간 걸립니다.", "It takes an hour to get to work."), ("지하철을 타고 출근합니다.", "He goes to work by underground."), ("일곱 시에 일어납니다.", "He gets up at seven.")],
     "여덟 시에 시작해서: work starts at eight.", "workplace-culture", "easy"),
    ("김 반장님께. 오늘 아침에 열이 많이 나서 병원에 왔습니다. 의사 선생님이 오늘은 쉬라고 하셨습니다. 내일은 출근하겠습니다. 죄송합니다. 아마르 드림.",
     "Dear Team Leader Kim, I had a high fever this morning, so I've come to the hospital. The doctor told me to rest today. I'll come to work tomorrow. I'm sorry. From Amar.",
     [("아마르 씨는 내일 출근할 겁니다.", "Amar will come to work tomorrow."), ("아마르 씨는 오늘 출근했습니다.", "Amar came to work today."), ("반장님이 아픕니다.", "The team leader is ill."), ("아마르 씨는 일주일 쉽니다.", "Amar is off for a week.")],
     "내일은 출근하겠습니다: he'll be at work tomorrow.", "workplace-culture", "easy"),
    ("이 식당은 아침 열한 시에 문을 열고 밤 열 시에 닫습니다. 매주 월요일은 쉽니다. 점심시간에는 손님이 많아서 예약하는 것이 좋습니다.",
     "This restaurant opens at 11 a.m. and closes at 10 p.m. It's closed every Monday. It's busy at lunchtime, so booking is a good idea.",
     [("월요일에는 문을 열지 않습니다.", "It doesn't open on Mondays."), ("아침 아홉 시에 문을 엽니다.", "It opens at 9 a.m."), ("점심에는 손님이 적습니다.", "Few customers come at lunch."), ("예약을 할 수 없습니다.", "You can't book.")],
     "매주 월요일은 쉽니다: closed on Mondays.", "daily-life", "easy"),
    ("오늘 우리 팀은 상자 오백 개를 포장해야 합니다. 오전에 삼백 개를 했으니까 오후에는 이백 개만 하면 됩니다. 다 끝나면 창고로 옮깁니다.",
     "Today our team has to pack 500 boxes. We did 300 in the morning, so we only need to do 200 in the afternoon. When we're done, we move them to the warehouse.",
     [("오후에 상자 이백 개를 포장합니다.", "200 boxes will be packed in the afternoon."), ("오전에 이백 개를 포장했습니다.", "200 were packed in the morning."), ("오늘 상자 삼백 개만 포장합니다.", "Only 300 boxes are packed today."), ("상자는 트럭으로 바로 보냅니다.", "The boxes go straight onto lorries.")],
     "500 − 300 = 200 left for the afternoon.", "job-korean", "medium"),
    ("[모집] 한국어 교실 학생을 모집합니다. 대상: 외국인 근로자. 시간: 매주 일요일 오후 두 시~네 시. 장소: 시민 센터 삼 층. 수업료: 무료.",
     "[Recruiting] Students wanted for a Korean class. For: foreign workers. Time: every Sunday 2–4 p.m. Place: Civic Centre, 3rd floor. Fee: free.",
     [("수업료를 내지 않아도 됩니다.", "There's no fee to pay."), ("수업은 토요일에 합니다.", "Classes are on Saturdays."), ("수업은 세 시간 동안 합니다.", "Classes last three hours."), ("수업은 시민 센터 이 층에서 합니다.", "Classes are on the 2nd floor.")],
     "수업료: 무료. Classes are Sundays, two hours, on the third floor.", "daily-life", "easy"),
    ("이 약은 하루에 세 번, 식사하고 삼십 분 후에 드세요. 이 약을 먹으면 졸릴 수 있으니까 운전은 하지 마세요. 사흘 동안 드시고 다시 오세요.",
     "Take this medicine three times a day, thirty minutes after meals. It may make you sleepy, so don't drive. Take it for three days and then come back.",
     [("약을 먹고 운전하면 안 됩니다.", "You shouldn't drive after taking it."), ("약은 식사 전에 먹습니다.", "It's taken before meals."), ("약은 하루에 두 번 먹습니다.", "It's taken twice a day."), ("일주일 후에 다시 옵니다.", "Come back after a week.")],
     "졸릴 수 있으니까 운전은 하지 마세요: don't drive.", "public-services", "medium"),
    ("저는 지난달에 기숙사에서 나와서 원룸으로 이사했습니다. 방은 작지만 회사에서 가깝습니다. 월세는 이십오만 원이고 관리비는 따로 냅니다.",
     "Last month I moved out of the dormitory into a studio flat. The room is small but close to work. The rent is 250,000 won and I pay maintenance separately.",
     [("지금 사는 곳은 회사에서 가깝습니다.", "Where he lives now is close to work."), ("지금도 기숙사에 삽니다.", "He still lives in the dormitory."), ("방이 아주 넓습니다.", "The room is very big."), ("월세에 관리비가 들어 있습니다.", "Maintenance is included in the rent.")],
     "방은 작지만 회사에서 가깝습니다: small but close to work.", "basic-life", "medium"),
    ("공장 안에서는 반드시 안전화를 신어야 합니다. 안전화가 없는 사람은 사무실에서 받을 수 있습니다. 안전화는 무료로 줍니다.",
     "Safety shoes must be worn inside the factory. Anyone without them can get a pair from the office. They are given out free.",
     [("안전화는 돈을 내지 않고 받습니다.", "Safety shoes are free."), ("안전화는 직접 사야 합니다.", "You have to buy your own."), ("공장 밖에서만 안전화를 신습니다.", "They're only worn outside the factory."), ("안전화는 창고에서 받습니다.", "You collect them from the warehouse.")],
     "안전화는 무료로 줍니다: given free, from the office.", "industrial-safety", "easy"),
    ("지수 씨, 내일 비가 와서 등산은 다음 주로 미뤘어요. 대신 내일은 영화를 볼까요? 오후 세 시에 시청역 이 번 출구에서 만나요.",
     "Jisu, because it's going to rain tomorrow, I've put the hike off until next week. Shall we see a film tomorrow instead? Let's meet at exit 2 of City Hall station at 3 p.m.",
     [("내일 영화를 보려고 합니다.", "They plan to see a film tomorrow."), ("내일 등산을 갑니다.", "They're hiking tomorrow."), ("오전 세 시에 만납니다.", "They meet at 3 a.m."), ("시청역 일 번 출구에서 만납니다.", "They meet at exit 1.")],
     "Hiking is postponed; tomorrow is a film at 3 p.m., exit 2.", "daily-life", "medium"),
    ("이 버스는 십 분마다 옵니다. 첫차는 아침 다섯 시 반이고 막차는 밤 열한 시 반입니다. 주말에는 이십 분마다 옵니다.",
     "This bus comes every ten minutes. The first bus is at 5:30 a.m. and the last is at 11:30 p.m. At weekends it comes every twenty minutes.",
     [("주말에는 버스가 더 가끔 옵니다.", "At weekends the bus comes less often."), ("버스는 매일 이십 분마다 옵니다.", "It comes every 20 minutes every day."), ("첫차는 여섯 시입니다.", "The first bus is at six."), ("막차는 열 시 반입니다.", "The last bus is at 10:30.")],
     "Ten minutes on weekdays, twenty at weekends: less often at weekends.", "public-services", "medium"),
    ("[분실물] 어제 식당에서 검은색 지갑을 주웠습니다. 지갑 안에 외국인 등록증이 있습니다. 주인은 경비실로 오세요.",
     "[Lost property] A black wallet was found in the canteen yesterday. There is an alien registration card inside. Would the owner please come to the security office.",
     [("지갑은 경비실에 있습니다.", "The wallet is at the security office."), ("지갑을 오늘 주웠습니다.", "The wallet was found today."), ("지갑은 빨간색입니다.", "The wallet is red."), ("지갑 안에 돈만 있습니다.", "There's only money in it.")],
     "주인은 경비실로 오세요: collect it from the security office.", "daily-life", "easy"),
    ("우리 농장에서는 딸기를 키웁니다. 딸기는 겨울부터 봄까지 땁니다. 딸기를 딸 때는 장갑을 끼고 조심해서 따야 합니다.",
     "We grow strawberries on our farm. Strawberries are picked from winter to spring. When picking them, wear gloves and pick carefully.",
     [("딸기는 겨울부터 봄까지 땁니다.", "Strawberries are picked from winter to spring."), ("이 농장에서는 사과를 키웁니다.", "This farm grows apples."), ("딸기는 여름에 땁니다.", "Strawberries are picked in summer."), ("딸기를 딸 때 장갑을 벗습니다.", "Gloves come off for picking.")],
     "딸기는 겨울부터 봄까지 땁니다.", "job-korean", "easy"),
    ("이번 달 월급은 이백오십만 원입니다. 이 중에서 기숙사비 이십만 원과 식비 십만 원을 뺍니다. 그래서 통장에는 이백이십만 원이 들어옵니다.",
     "This month's pay is 2.5 million won. From it, 200,000 won for the dormitory and 100,000 won for meals are deducted. So 2.2 million won goes into the bank account.",
     [("통장에 이백이십만 원이 들어옵니다.", "2.2 million won goes into the account."), ("월급은 이백만 원입니다.", "The pay is 2 million won."), ("식비는 이십만 원입니다.", "Meals cost 200,000 won."), ("기숙사비는 내지 않습니다.", "There's no dormitory fee.")],
     "2,500,000 − 200,000 − 100,000 = 2,200,000 won.", "numbers-time", "hard"),
    ("오늘 오후 두 시부터 네 시까지 전기 공사가 있습니다. 이 시간에는 엘리베이터를 사용할 수 없습니다. 계단을 이용해 주십시오.",
     "There will be electrical work from 2 to 4 p.m. today. The lifts cannot be used during this time. Please use the stairs.",
     [("공사 중에는 엘리베이터를 탈 수 없습니다.", "The lifts can't be used during the work."), ("공사는 오전에 합니다.", "The work is in the morning."), ("공사는 세 시간 동안 합니다.", "The work lasts three hours."), ("계단을 사용할 수 없습니다.", "The stairs can't be used.")],
     "엘리베이터를 사용할 수 없습니다; two hours, in the afternoon.", "basic-life", "easy"),
    ("저는 베트남에서 온 흐엉입니다. 한국에서 일한 지 삼 년이 되었습니다. 처음에는 공장에서 일했는데 지금은 농장에서 일합니다. 농장 일이 더 힘들지만 공기가 좋아서 좋습니다.",
     "I'm Huong from Vietnam. I've worked in Korea for three years. At first I worked in a factory, but now I work on a farm. Farm work is harder, but I like it because the air is good.",
     [("지금은 농장에서 일합니다.", "She works on a farm now."), ("지금도 공장에서 일합니다.", "She still works in a factory."), ("농장 일이 더 쉽습니다.", "Farm work is easier."), ("한국에서 일한 지 일 년 되었습니다.", "She's worked in Korea for a year.")],
     "지금은 농장에서 일합니다; farm work is harder.", "job-korean", "medium"),
    ("[공지] 추석 연휴는 구월 이십팔 일부터 삼십 일까지입니다. 회사 버스는 연휴 동안 다니지 않습니다. 시월 일 일부터 다시 일을 시작합니다.",
     "[Notice] The Chuseok holiday runs from 28 to 30 September. The company bus does not run during the holiday. Work starts again on 1 October.",
     [("시월 일 일에 다시 일을 시작합니다.", "Work restarts on 1 October."), ("연휴는 일주일입니다.", "The holiday lasts a week."), ("연휴에도 회사 버스가 다닙니다.", "The bus runs during the holiday."), ("연휴는 시월에 시작합니다.", "The holiday starts in October.")],
     "28–30 September off; back on 1 October; no bus during the holiday.", "korean-culture", "medium"),
    ("배에서 잡은 생선은 바로 얼음에 넣어야 합니다. 그래야 신선합니다. 생선 상자는 하나에 이십 킬로그램이 넘지 않게 담습니다.",
     "Fish caught on the boat must be put on ice straight away so that it stays fresh. Each box of fish must not weigh more than 20 kilograms.",
     [("생선 상자는 이십 킬로그램을 넘으면 안 됩니다.", "A box must not be over 20 kg."), ("생선은 집에 가서 얼음에 넣습니다.", "Fish go on ice at home."), ("상자 하나에 삼십 킬로그램을 담습니다.", "Each box holds 30 kg."), ("생선은 얼음에 넣지 않습니다.", "Fish aren't put on ice.")],
     "이십 킬로그램이 넘지 않게: no more than 20 kg.", "job-korean", "medium"),
    ("다음 주 수요일에 건강 검진이 있습니다. 검진은 회사 회의실에서 오전 아홉 시부터 합니다. 검진 전날 밤 열 시부터는 아무것도 먹지 마세요.",
     "There's a health check next Wednesday. It's in the company meeting room from 9 a.m. Don't eat anything from 10 p.m. the night before.",
     [("검진 전날 밤 열 시부터 굶어야 합니다.", "No food from 10 p.m. the night before."), ("검진은 병원에서 합니다.", "The check is at a hospital."), ("검진은 오후에 합니다.", "The check is in the afternoon."), ("검진 날 아침을 먹어도 됩니다.", "Breakfast is allowed that day.")],
     "전날 밤 열 시부터는 아무것도 먹지 마세요.", "public-services", "medium"),
    ("저희 가게는 휴대폰 수리 전문점입니다. 액정 수리는 한 시간이면 됩니다. 배터리 교체는 삼십 분 걸립니다. 일요일은 쉽니다.",
     "Our shop specialises in phone repairs. A screen repair takes an hour. A battery replacement takes thirty minutes. We're closed on Sundays.",
     [("배터리 교체는 삼십 분 걸립니다.", "A battery takes thirty minutes."), ("액정 수리는 하루 걸립니다.", "A screen repair takes a day."), ("일요일에도 문을 엽니다.", "It's open on Sundays."), ("휴대폰을 팝니다.", "The shop sells phones.")],
     "배터리 교체는 삼십 분.", "daily-life", "easy"),
    ("우리 회사 점심시간은 열두 시부터 한 시까지입니다. 식당이 좁아서 일 팀은 열두 시에, 이 팀은 열두 시 반에 먹습니다.",
     "Our company's lunch break is from 12 to 1. The canteen is small, so Team 1 eats at 12 and Team 2 at 12:30.",
     [("이 팀은 열두 시 반에 점심을 먹습니다.", "Team 2 eats at 12:30."), ("모든 팀이 열두 시에 먹습니다.", "All teams eat at 12."), ("점심시간은 두 시간입니다.", "The lunch break is two hours."), ("식당이 아주 넓습니다.", "The canteen is very big.")],
     "이 팀은 열두 시 반에 먹습니다.", "workplace-culture", "easy"),
    ("라흐만 씨에게. 어제 빌려준 우산 고마웠어요. 오늘 휴게실 책상 위에 우산을 두었어요. 그리고 작은 선물도 같이 두었어요. 민수 씀.",
     "To Rahman. Thanks for lending me your umbrella yesterday. I've left it on the desk in the break room today, with a small present. From Minsu.",
     [("민수 씨가 우산을 돌려주었습니다.", "Minsu has returned the umbrella."), ("라흐만 씨가 우산을 빌렸습니다.", "Rahman borrowed the umbrella."), ("우산은 사무실에 있습니다.", "The umbrella is in the office."), ("민수 씨는 선물을 받았습니다.", "Minsu received a present.")],
     "Minsu borrowed it and left it, with a present, on the break room desk.", "daily-life", "medium"),
    ("[주차 안내] 직원 주차장은 공장 뒤쪽에 있습니다. 공장 앞은 손님 주차장이니까 직원은 주차하지 마세요. 오토바이는 자전거 보관소 옆에 세우세요.",
     "[Parking] The staff car park is behind the factory. The front is for visitors, so staff must not park there. Motorbikes go next to the bike shelter.",
     [("직원은 공장 뒤쪽에 주차합니다.", "Staff park behind the factory."), ("직원은 공장 앞에 주차합니다.", "Staff park in front."), ("손님은 공장 뒤쪽에 주차합니다.", "Visitors park behind."), ("오토바이는 공장 안에 세웁니다.", "Motorbikes go inside.")],
     "직원 주차장은 공장 뒤쪽.", "workplace-culture", "easy"),
    ("이 세탁기는 동전 세탁기입니다. 한 번 빨래하는 데 삼천 원이고 오십 분 걸립니다. 건조기는 이천 원이고 사십 분 걸립니다.",
     "This is a coin-operated washing machine. A wash costs 3,000 won and takes fifty minutes. The dryer costs 2,000 won and takes forty minutes.",
     [("건조기는 이천 원입니다.", "The dryer costs 2,000 won."), ("세탁은 이천 원입니다.", "A wash costs 2,000 won."), ("세탁은 사십 분 걸립니다.", "A wash takes forty minutes."), ("건조기는 무료입니다.", "The dryer is free.")],
     "건조기는 이천 원, 사십 분.", "basic-life", "medium"),
    ("저는 지난주에 일을 하다가 손목을 다쳤습니다. 병원에서 이 주 동안 무거운 물건을 들지 말라고 했습니다. 그래서 지금은 포장 대신 검사 일을 하고 있습니다.",
     "Last week I hurt my wrist at work. The hospital told me not to lift anything heavy for two weeks. So now I'm doing inspection work instead of packing.",
     [("지금은 검사 일을 하고 있습니다.", "He is doing inspection work now."), ("다리를 다쳤습니다.", "He hurt his leg."), ("일주일 동안 쉽니다.", "He's off for a week."), ("지금도 무거운 상자를 포장합니다.", "He's still packing heavy boxes.")],
     "포장 대신 검사 일을 하고 있습니다.", "industrial-safety", "medium"),
    ("[회의 안내] 안전 교육이 이번 주 목요일 오후 네 시에 있습니다. 장소는 이 층 교육실입니다. 모든 직원은 꼭 참석해야 합니다. 교육 시간은 한 시간입니다.",
     "[Meeting] Safety training is this Thursday at 4 p.m., in the training room on the 2nd floor. All staff must attend. It lasts one hour.",
     [("모든 직원이 참석해야 합니다.", "All staff must attend."), ("교육은 오전에 있습니다.", "The training is in the morning."), ("교육은 두 시간입니다.", "It lasts two hours."), ("원하는 사람만 참석합니다.", "Only those who want to attend.")],
     "모든 직원은 꼭 참석해야 합니다.", "industrial-safety", "easy"),
    ("우리 동네 도서관은 화요일부터 일요일까지 문을 엽니다. 책은 한 사람이 다섯 권까지 이 주 동안 빌릴 수 있습니다. 외국인 등록증이 있으면 회원 카드를 만들 수 있습니다.",
     "Our local library opens Tuesday to Sunday. Each person can borrow up to five books for two weeks. With an alien registration card you can get a membership card.",
     [("책을 다섯 권까지 빌릴 수 있습니다.", "You can borrow up to five books."), ("월요일에도 문을 엽니다.", "It's open on Mondays."), ("책은 한 달 동안 빌립니다.", "Books are lent for a month."), ("외국인은 회원이 될 수 없습니다.", "Foreigners can't join.")],
     "다섯 권까지 이 주 동안.", "public-services", "medium"),
    ("오늘 저녁 메뉴는 비빔밥과 된장국입니다. 매운 음식을 못 먹는 사람은 고추장을 빼고 드세요. 후식으로 수박이 있습니다.",
     "Tonight's menu is bibimbap and soybean paste soup. If you can't eat spicy food, leave out the chilli paste. There's watermelon for dessert.",
     [("후식으로 수박을 줍니다.", "Watermelon is served for dessert."), ("저녁 메뉴는 김치찌개입니다.", "Dinner is kimchi stew."), ("고추장을 꼭 넣어야 합니다.", "You must add chilli paste."), ("후식이 없습니다.", "There's no dessert.")],
     "후식으로 수박이 있습니다.", "daily-life", "easy"),
    ("고용센터에서 외국인 근로자를 위한 무료 상담을 합니다. 월급, 회사 문제, 생활 문제 등을 상담할 수 있습니다. 상담은 평일 오전 아홉 시부터 오후 여섯 시까지입니다.",
     "The job centre offers free advice for foreign workers on pay, problems at work, daily life and more. Advice is available on weekdays from 9 a.m. to 6 p.m.",
     [("상담은 돈을 내지 않습니다.", "The advice is free."), ("상담은 주말에만 합니다.", "Advice is only at weekends."), ("월급 문제는 상담할 수 없습니다.", "Pay problems can't be discussed."), ("상담은 밤에도 합니다.", "Advice is also given at night.")],
     "무료 상담: free; weekdays, 9 to 6.", "laws-systems", "medium"),
    ("외국인 근로자는 허가 없이 다른 회사에서 일하면 안 됩니다. 그래서 저는 주말에 아르바이트를 하지 않고 한국어를 공부합니다. 한국어를 잘하면 회사에서 일하기도 쉬워집니다.",
     "Foreign workers may not work for another company without permission. So at weekends I don't take part-time work; I study Korean. Being good at Korean also makes work easier.",
     [("이 사람은 주말에 한국어를 공부합니다.", "This person studies Korean at weekends."), ("이 사람은 주말에 아르바이트를 합니다.", "This person works part-time at weekends."), ("외국인 근로자는 다른 곳에서 자유롭게 일할 수 있습니다.", "Foreign workers can work elsewhere freely."), ("한국어는 회사 일에 도움이 안 됩니다.", "Korean doesn't help at work.")],
     "주말에 … 한국어를 공부합니다; working elsewhere needs permission.", "laws-systems", "hard"),
    ("이번 겨울에는 기숙사 난방비를 회사에서 냅니다. 하지만 방을 비울 때는 난방을 꼭 꺼야 합니다. 창문을 열고 난방을 켜면 안 됩니다.",
     "This winter the company pays for dormitory heating. But you must turn the heating off when you leave your room, and you must not have the heating on with the window open.",
     [("난방비는 회사가 냅니다.", "The company pays for heating."), ("난방비는 직원이 냅니다.", "Staff pay for heating."), ("방에 없을 때도 난방을 켜 둡니다.", "Heating stays on when you're out."), ("창문을 열고 난방을 켜도 됩니다.", "Heating with the window open is fine.")],
     "난방비를 회사에서 냅니다.", "basic-life", "medium"),
    ("[택배 안내] 기숙사로 온 택배는 경비실에서 보관합니다. 택배는 오후 여섯 시부터 밤 열 시까지 찾을 수 있습니다. 찾을 때는 이름과 방 번호를 말해 주세요.",
     "[Parcels] Parcels delivered to the dormitory are kept at the security office. They can be collected from 6 to 10 p.m. Give your name and room number when you collect.",
     [("택배를 찾을 때 방 번호를 말해야 합니다.", "You must give your room number."), ("택배는 방 앞에 둡니다.", "Parcels are left outside rooms."), ("택배는 아침에 찾을 수 있습니다.", "Parcels can be collected in the morning."), ("택배는 사무실에서 보관합니다.", "Parcels are kept at the office.")],
     "이름과 방 번호를 말해 주세요.", "basic-life", "easy"),
    ("우리 공장은 삼 교대로 일합니다. 아침 조는 여섯 시부터 두 시까지, 오후 조는 두 시부터 열 시까지, 밤 조는 열 시부터 아침 여섯 시까지 일합니다.",
     "Our factory works three shifts. The morning shift is 6 a.m. to 2 p.m., the afternoon shift 2 to 10 p.m., and the night shift 10 p.m. to 6 a.m.",
     [("오후 조는 밤 열 시에 끝납니다.", "The afternoon shift ends at 10 p.m."), ("아침 조는 여덟 시에 시작합니다.", "The morning shift starts at 8."), ("밤 조는 열두 시에 시작합니다.", "The night shift starts at midnight."), ("공장은 두 교대로 일합니다.", "The factory runs two shifts.")],
     "오후 조는 두 시부터 열 시까지.", "workplace-culture", "hard"),
    ("저는 한국 운전면허를 따려고 운전 학원에 다닙니다. 필기 시험은 지난주에 합격했습니다. 다음 달에 도로 주행 시험을 봅니다.",
     "I'm going to driving school to get a Korean licence. I passed the written test last week. I take the road test next month.",
     [("필기 시험은 이미 합격했습니다.", "He has already passed the written test."), ("벌써 운전면허를 땄습니다.", "He already has his licence."), ("도로 주행 시험은 지난주였습니다.", "The road test was last week."), ("필기 시험은 다음 달입니다.", "The written test is next month.")],
     "필기 시험은 지난주에 합격했습니다.", "daily-life", "medium"),
    ("이 화분은 일주일에 한 번 물을 주면 됩니다. 햇빛이 잘 드는 창가에 두세요. 겨울에는 추우니까 방 안으로 옮기세요.",
     "This pot plant only needs watering once a week. Keep it on a sunny windowsill. In winter it's cold, so move it inside the room.",
     [("물은 일주일에 한 번 줍니다.", "Water it once a week."), ("물은 매일 줍니다.", "Water it every day."), ("어두운 곳에 둡니다.", "Keep it somewhere dark."), ("겨울에는 밖에 둡니다.", "Put it outside in winter.")],
     "일주일에 한 번 물을 주면 됩니다.", "daily-life", "easy"),
    ("돼지우리를 청소할 때는 장화와 마스크를 꼭 착용하세요. 청소는 하루에 두 번, 아침과 저녁에 합니다. 청소가 끝나면 소독약을 뿌립니다.",
     "When cleaning the pigsty, always wear rubber boots and a mask. It's cleaned twice a day, morning and evening. After cleaning, spray disinfectant.",
     [("청소가 끝나면 소독약을 뿌립니다.", "Disinfectant is sprayed after cleaning."), ("청소는 하루에 한 번 합니다.", "It's cleaned once a day."), ("장화를 신지 않아도 됩니다.", "Boots aren't needed."), ("소독은 청소 전에 합니다.", "Disinfecting comes before cleaning.")],
     "청소가 끝나면 소독약을 뿌립니다.", "job-korean", "medium"),
    ("[휴가 신청] 휴가를 쓰려면 일주일 전까지 휴가 신청서를 내야 합니다. 신청서는 반장님께 내고, 반장님이 사인한 후 사무실에 냅니다. 급한 일이 있으면 전화로 먼저 알리세요.",
     "[Leave] To take leave, hand in a leave form at least a week before. Give it to the team leader, and after they sign it, it goes to the office. In an emergency, phone first.",
     [("신청서는 반장님이 먼저 사인합니다.", "The team leader signs the form first."), ("신청서는 하루 전에 내도 됩니다.", "The form can go in the day before."), ("신청서는 바로 사무실에 냅니다.", "The form goes straight to the office."), ("급한 일은 알리지 않아도 됩니다.", "Emergencies don't need reporting.")],
     "반장님께 내고, 반장님이 사인한 후 사무실에 냅니다.", "workplace-culture", "hard"),
    ("저는 고향에 있는 딸과 매일 밤 영상 통화를 합니다. 한국과 고향은 두 시간 시차가 있습니다. 그래서 제가 밤 열 시에 전화하면 고향은 여덟 시입니다.",
     "I video call my daughter back home every night. There's a two-hour time difference between Korea and home, so when I call at 10 p.m., it's 8 o'clock there.",
     [("한국이 고향보다 두 시간 빠릅니다.", "Korea is two hours ahead of home."), ("일주일에 한 번 전화합니다.", "He calls once a week."), ("아들과 통화합니다.", "He talks to his son."), ("고향이 한국보다 두 시간 빠릅니다.", "Home is two hours ahead of Korea.")],
     "10 p.m. in Korea is 8 p.m. at home, so Korea is two hours ahead.", "numbers-time", "hard"),
    ("이 우유는 유통 기한이 시월 십오 일까지입니다. 문을 연 후에는 냉장고에 넣고 사흘 안에 드세요.",
     "This milk is good until 15 October. Once opened, keep it in the fridge and drink it within three days.",
     [("열고 나서 사흘 안에 마셔야 합니다.", "Drink it within three days of opening."), ("유통 기한은 시월 오 일입니다.", "It's good until 5 October."), ("열고 나서 밖에 둡니다.", "Keep it out of the fridge once opened."), ("열고 나서 일주일 동안 마십니다.", "Drink it over a week once opened.")],
     "문을 연 후에는 … 사흘 안에 드세요.", "daily-life", "medium"),
    ("[공사장 안내] 내일은 비가 많이 온다고 합니다. 비가 오면 높은 곳 작업은 하지 않습니다. 대신 실내에서 자재 정리를 합니다.",
     "[Site notice] Heavy rain is forecast for tomorrow. If it rains, there will be no work at height. Instead, materials will be sorted indoors.",
     [("비가 오면 실내에서 일합니다.", "If it rains, work moves indoors."), ("비가 와도 높은 곳에서 일합니다.", "Work at height goes on in rain."), ("내일은 모두 쉽니다.", "Everyone has tomorrow off."), ("자재 정리는 밖에서 합니다.", "Materials are sorted outside.")],
     "대신 실내에서 자재 정리를 합니다.", "industrial-safety", "medium"),
    ("이번 토요일에 시민 센터에서 외국인 노래자랑 대회가 있습니다. 참가하고 싶은 사람은 금요일까지 전화로 신청하세요. 일등은 상금 오십만 원을 받습니다.",
     "This Saturday there's a singing contest for foreigners at the Civic Centre. If you want to take part, apply by phone by Friday. First prize is 500,000 won.",
     [("일등은 오십만 원을 받습니다.", "First prize is 500,000 won."), ("대회는 일요일에 합니다.", "The contest is on Sunday."), ("신청은 시민 센터에 가서 합니다.", "You apply in person."), ("한국 사람만 참가할 수 있습니다.", "Only Koreans can enter.")],
     "일등은 상금 오십만 원.", "korean-culture", "medium"),
    ("새로 산 냉장고가 고장 났습니다. 산 지 한 달밖에 안 되어서 무료로 고칠 수 있습니다. 서비스 센터에 전화했더니 내일 오전에 기사가 온다고 합니다.",
     "The fridge I've just bought has broken. It's only a month old, so it can be repaired for free. I called the service centre and they said an engineer will come tomorrow morning.",
     [("수리비를 내지 않습니다.", "There's no repair charge."), ("냉장고를 산 지 일 년 되었습니다.", "The fridge is a year old."), ("기사가 오늘 옵니다.", "The engineer comes today."), ("냉장고를 직접 고칩니다.", "She'll fix it herself.")],
     "무료로 고칠 수 있습니다; the engineer comes tomorrow.", "daily-life", "medium"),
    ("저는 퇴근 후에 동료들과 배드민턴을 칩니다. 회사 체육관은 저녁 일곱 시부터 아홉 시까지 쓸 수 있습니다. 라켓은 체육관에서 빌릴 수 있습니다.",
     "After work I play badminton with co-workers. The company gym can be used from 7 to 9 p.m. Rackets can be borrowed at the gym.",
     [("라켓은 빌릴 수 있습니다.", "Rackets can be borrowed."), ("체육관은 밤 열한 시까지 씁니다.", "The gym is open until 11 p.m."), ("라켓은 직접 사야 합니다.", "You must buy your own racket."), ("출근 전에 배드민턴을 칩니다.", "They play before work.")],
     "라켓은 체육관에서 빌릴 수 있습니다.", "daily-life", "easy"),
    ("[작업 안내] 다음 주부터 포장 라인에 새 직원 두 명이 옵니다. 첫 주에는 아룬 씨가 새 직원들에게 일을 가르쳐 줄 겁니다. 새 직원들은 오전에만 일합니다.",
     "[Work notice] Two new staff join the packing line next week. In the first week Arun will teach them the job. The new staff will work mornings only.",
     [("아룬 씨가 새 직원들을 가르칩니다.", "Arun will train the new staff."), ("새 직원은 세 명입니다.", "There are three new staff."), ("새 직원들은 오후에만 일합니다.", "The new staff work afternoons only."), ("새 직원들은 검사 라인에서 일합니다.", "They work on the inspection line.")],
     "아룬 씨가 … 가르쳐 줄 겁니다; two new staff, mornings, packing line.", "workplace-culture", "medium"),
    ("우리 동네 마트는 밤 열두 시까지 문을 엽니다. 매주 수요일에는 과일과 채소를 싸게 팝니다. 삼만 원 이상 사면 기숙사까지 무료로 배달해 줍니다.",
     "Our local supermarket is open until midnight. Every Wednesday fruit and vegetables are cheap. Spend 30,000 won or more and they deliver free to the dormitory.",
     [("삼만 원 이상 사면 배달비가 없습니다.", "Delivery is free if you spend 30,000 won or more."), ("마트는 밤 열 시에 닫습니다.", "It closes at 10 p.m."), ("과일은 금요일에 쌉니다.", "Fruit is cheap on Fridays."), ("배달은 하지 않습니다.", "There's no delivery.")],
     "삼만 원 이상 사면 … 무료로 배달해 줍니다.", "daily-life", "medium"),
]

assert len(DETAILS) == 48, len(DETAILS)
