"""Passage Topic: a short passage; the learner picks what it is about.

Each entry: (Korean passage, English passage, [(right topic, English), then
three wrong], note in English, topic tag, difficulty).
"""

TOPICS = [
    ("저는 아침마다 공원에서 달리기를 합니다. 주말에는 친구들과 축구를 합니다. 운동을 하면 몸도 건강해지고 기분도 좋아집니다.",
     "I go running in the park every morning. At weekends I play football with friends. Exercise makes my body healthier and puts me in a good mood.",
     [("운동", "Exercise"), ("음식", "Food"), ("쇼핑", "Shopping"), ("여행", "Travel")], "Running and football: the passage is about exercise.", "daily-life", "easy"),
    ("우리 가족은 모두 다섯 명입니다. 아버지는 농부이시고 어머니는 시장에서 과일을 파십니다. 형은 회사원이고 여동생은 학생입니다.",
     "There are five people in my family. My father is a farmer and my mother sells fruit at the market. My older brother is an office worker and my younger sister is a student.",
     [("가족 소개", "Introducing a family"), ("시장 위치", "Where the market is"), ("과일 가격", "Fruit prices"), ("회사 생활", "Office life")], "It introduces each family member.", "basic-life", "easy"),
    ("오늘은 아침부터 하늘이 흐렸습니다. 오후에는 비가 많이 오고 바람도 강하게 불었습니다. 내일은 맑고 따뜻하겠습니다.",
     "The sky was cloudy from the morning today. In the afternoon it rained heavily and a strong wind blew. Tomorrow will be clear and warm.",
     [("날씨", "The weather"), ("계절", "The seasons"), ("교통", "Traffic"), ("건강", "Health")], "Cloud, rain, wind and tomorrow's sun: the weather.", "daily-life", "easy"),
    ("저는 김치찌개를 좋아합니다. 먼저 냄비에 김치와 고기를 넣고 볶습니다. 그다음에 물을 넣고 끓입니다. 마지막으로 두부와 파를 넣습니다.",
     "I like kimchi stew. First, put kimchi and meat in a pot and stir-fry them. Next, add water and bring it to the boil. Finally, add tofu and spring onion.",
     [("요리 방법", "How to cook"), ("식당 소개", "A restaurant"), ("시장 보기", "Food shopping"), ("음식 가격", "Food prices")], "Step-by-step instructions for a stew: a recipe.", "daily-life", "easy"),
    ("한국의 여름은 덥고 비가 많이 옵니다. 특히 칠월에는 장마가 있어서 거의 매일 비가 옵니다. 그래서 여름에는 우산을 꼭 가지고 다녀야 합니다.",
     "Korean summers are hot and rainy. In July especially there is a monsoon season, so it rains almost every day. So in summer you should always carry an umbrella.",
     [("한국의 여름 날씨", "Summer weather in Korea"), ("우산 가게", "An umbrella shop"), ("여름 휴가", "Summer holidays"), ("칠월의 행사", "Events in July")], "Heat, monsoon rain and umbrellas: Korean summer weather.", "korean-culture", "medium"),
    ("지게차를 운전하려면 면허가 있어야 합니다. 운전할 때는 안전벨트를 매고 천천히 움직여야 합니다. 짐을 너무 높이 쌓으면 앞이 안 보여서 위험합니다.",
     "You need a licence to drive a forklift. When driving you must wear a seat belt and move slowly. Stacking loads too high is dangerous because you can't see ahead.",
     [("지게차 안전 운전", "Driving a forklift safely"), ("자동차 면허 시험", "The car driving test"), ("짐 싸는 방법", "How to pack"), ("공장 위치", "Where the factory is")], "Licence, seat belt, speed and load height: forklift safety.", "industrial-safety", "medium"),
    ("한국에서는 쓰레기를 버릴 때 종류별로 나눠야 합니다. 음식물 쓰레기는 따로 모으고, 종이와 플라스틱, 캔은 분리해서 버립니다. 일반 쓰레기는 종량제 봉투에 넣습니다.",
     "In Korea, rubbish must be sorted by type. Food waste is collected separately, and paper, plastic and cans are sorted before being thrown away. General rubbish goes in pay-as-you-throw bags.",
     [("쓰레기 분리수거", "Sorting rubbish"), ("음식 만들기", "Cooking"), ("봉투 가격", "The price of bags"), ("청소 시간", "Cleaning times")], "Sorting waste by type is 분리수거.", "basic-life", "medium"),
    ("시월 구 일은 한글날입니다. 한글은 세종대왕이 만든 한국의 글자입니다. 한글은 배우기 쉬워서 외국인도 며칠 만에 읽을 수 있습니다.",
     "The ninth of October is Hangul Day. Hangul is the Korean alphabet, created by King Sejong. It is easy to learn, so even foreigners can read it within a few days.",
     [("한글과 한글날", "Hangul and Hangul Day"), ("세종대왕의 가족", "King Sejong's family"), ("외국어 공부", "Studying foreign languages"), ("시월의 날씨", "October weather")], "The passage is about Hangul and the day that celebrates it.", "korean-culture", "easy"),
    ("작업장에서 화재가 나면 먼저 \"불이야!\" 하고 크게 소리칩니다. 그리고 비상벨을 누르고 비상구로 빨리 나갑니다. 엘리베이터는 타면 안 됩니다.",
     "If a fire breaks out at the workplace, first shout \"Fire!\" loudly. Then press the alarm and get out quickly through the emergency exit. Do not use the lift.",
     [("화재가 났을 때 할 일", "What to do in a fire"), ("엘리베이터 사용법", "How to use a lift"), ("비상벨 고치기", "Repairing the alarm"), ("작업장 청소", "Cleaning the workplace")], "Shout, press the alarm, use the exit: fire procedure.", "industrial-safety", "easy"),
    ("저는 한국에 온 지 일 년이 되었습니다. 처음에는 한국말을 잘 몰라서 힘들었습니다. 하지만 지금은 동료들과 이야기도 하고 혼자 시장에도 갑니다.",
     "It has been a year since I came to Korea. At first it was hard because I didn't know much Korean. But now I chat with co-workers and go to the market on my own.",
     [("한국 생활에 적응한 이야기", "Getting used to life in Korea"), ("시장에서 물건 사기", "Shopping at the market"), ("동료 소개", "Introducing a co-worker"), ("고향 생각", "Thinking of home")], "From struggling to managing alone: adapting to life in Korea.", "basic-life", "medium"),
    ("근로자는 일주일에 한 번 이상 쉬는 날이 있어야 합니다. 또 일 년 동안 열심히 일하면 유급 휴가를 받을 수 있습니다. 휴가를 쓰려면 미리 회사에 신청해야 합니다.",
     "Workers must have at least one day off a week. Also, after working hard for a year you can receive paid leave. To take leave you must apply to the company in advance.",
     [("근로자의 휴일과 휴가", "Workers' days off and leave"), ("회사의 월급날", "The company payday"), ("여행 계획", "Travel plans"), ("회사 규칙 위반", "Breaking company rules")], "Weekly days off and paid annual leave.", "laws-systems", "medium"),
    ("병원에 처음 가면 먼저 접수를 해야 합니다. 접수할 때 외국인 등록증과 건강 보험증을 보여 줍니다. 그다음에 이름을 부를 때까지 기다립니다.",
     "On your first visit to a hospital you must register first. When registering, show your alien registration card and health insurance card. Then wait until your name is called.",
     [("병원 이용 방법", "How to use a hospital"), ("건강 보험의 종류", "Types of health insurance"), ("의사가 되는 방법", "How to become a doctor"), ("약 먹는 시간", "When to take medicine")], "Register, show cards, wait: using a hospital.", "public-services", "medium"),
    ("고향에 돈을 보낼 때는 은행이나 송금 회사를 이용합니다. 은행은 안전하지만 수수료가 조금 비쌉니다. 송금 회사는 수수료가 싸지만 믿을 수 있는 곳인지 확인해야 합니다.",
     "To send money home, people use a bank or a money transfer company. Banks are safe but the fees are a little high. Transfer companies have lower fees, but you must check they can be trusted.",
     [("해외 송금 방법", "Ways to send money abroad"), ("은행 직원의 일", "A bank clerk's job"), ("돈을 아끼는 방법", "How to save money"), ("환전하는 곳", "Where to change money")], "Comparing banks and transfer companies for sending money home.", "public-services", "medium"),
    ("한국 사람들은 처음 만나면 고개를 숙여서 인사합니다. 나이가 많은 사람에게는 두 손으로 물건을 드립니다. 식사할 때는 어른이 먼저 수저를 드신 후에 먹습니다.",
     "Koreans bow their heads when they first meet. They hand things to older people with both hands. At meals, they eat after the eldest has picked up their spoon and chopsticks.",
     [("한국의 예절", "Korean etiquette"), ("한국 음식", "Korean food"), ("나이 계산", "Working out age"), ("수저 사용법", "Using a spoon and chopsticks")], "Bowing, giving with two hands, letting elders eat first: manners.", "korean-culture", "medium"),
    ("이 공장에서는 휴대폰 부품을 만듭니다. 기계가 부품을 만들면 직원들이 하나씩 검사합니다. 검사를 통과한 부품만 상자에 넣어서 다른 회사로 보냅니다.",
     "This factory makes mobile phone parts. After the machines make the parts, staff check them one by one. Only the parts that pass inspection are boxed and sent to another company.",
     [("공장에서 하는 일", "What the factory does"), ("휴대폰 사용법", "How to use a mobile"), ("직원 모집", "Recruiting staff"), ("상자 만드는 법", "How to make boxes")], "Making, checking and shipping parts: the factory's work.", "job-korean", "medium"),
    ("요즘 건강을 위해서 걷는 사람이 많습니다. 하루에 삼십 분만 걸어도 몸에 좋습니다. 엘리베이터 대신 계단을 이용하는 것도 좋은 방법입니다.",
     "These days many people walk for their health. Walking just thirty minutes a day is good for you. Taking the stairs instead of the lift is another good way.",
     [("건강을 위한 걷기", "Walking for health"), ("엘리베이터 고장", "A broken lift"), ("계단 청소", "Cleaning the stairs"), ("하루 일정", "A daily schedule")], "Walking and stairs for health.", "daily-life", "easy"),
    ("내일은 저의 생일입니다. 동료들이 회사 근처 식당에서 생일 파티를 해 준다고 했습니다. 고향 음식을 먹을 수 있는 곳이라서 정말 기대가 됩니다.",
     "Tomorrow is my birthday. My co-workers said they will throw me a birthday party at a restaurant near the company. It's a place where I can eat food from home, so I'm really looking forward to it.",
     [("생일 파티", "A birthday party"), ("고향 음식 만들기", "Cooking food from home"), ("식당 아르바이트", "A restaurant job"), ("회사 회의", "A company meeting")], "Co-workers are holding his birthday party.", "daily-life", "easy"),
    ("밤에 잠을 잘 자려면 자기 전에 휴대폰을 보지 않는 것이 좋습니다. 또 커피는 오후에 마시지 않는 것이 좋습니다. 매일 같은 시간에 자고 일어나는 것도 중요합니다.",
     "To sleep well at night, it's best not to look at your phone before bed. It's also best not to drink coffee in the afternoon. Going to bed and getting up at the same time every day matters too.",
     [("잠을 잘 자는 방법", "How to sleep well"), ("커피의 종류", "Kinds of coffee"), ("휴대폰 고르기", "Choosing a mobile"), ("아침 운동", "Morning exercise")], "Tips for a good night's sleep.", "daily-life", "medium"),
    ("농장에서 일할 때는 햇빛이 강해서 모자를 꼭 써야 합니다. 또 물을 자주 마셔야 합니다. 너무 더운 낮 시간에는 쉬고 아침이나 저녁에 일하는 것이 좋습니다.",
     "When working on a farm you must wear a hat because the sun is strong. You must also drink water often. It's best to rest in the hottest part of the day and work in the morning or evening.",
     [("더운 날 농장에서 일할 때 주의할 점", "Staying safe on a farm in hot weather"), ("모자 파는 곳", "Where to buy hats"), ("농장 위치", "Where the farm is"), ("저녁 식사", "Dinner")], "Hat, water and avoiding midday heat: working safely in heat.", "industrial-safety", "medium"),
    ("배에서 일할 때는 구명조끼를 항상 입어야 합니다. 바다에 빠지면 위험하기 때문입니다. 또 바닥이 젖어서 미끄러우니까 미끄럼 방지 신발을 신어야 합니다.",
     "When working on a boat you must always wear a life jacket, because falling into the sea is dangerous. Also, the deck is wet and slippery, so you must wear non-slip shoes.",
     [("배에서의 안전", "Safety on a boat"), ("바다 여행", "A sea trip"), ("수영 배우기", "Learning to swim"), ("신발 가게", "A shoe shop")], "Life jackets and non-slip shoes: safety at sea.", "industrial-safety", "medium"),
    ("공사장에서는 위에서 물건이 떨어질 수 있습니다. 그래서 안전모를 꼭 써야 합니다. 높은 곳에서 일할 때는 안전벨트도 매야 합니다.",
     "On a building site things may fall from above, so you must wear a safety helmet. When working at height you must also wear a safety harness.",
     [("공사장 안전 수칙", "Building site safety rules"), ("건물 짓는 방법", "How to build a building"), ("모자 고르기", "Choosing a hat"), ("높은 건물 구경", "Sightseeing tall buildings")], "Helmet and harness on a building site.", "industrial-safety", "easy"),
    ("우리 회사에는 외국인 근로자를 위한 한국어 교실이 있습니다. 매주 수요일 저녁 일곱 시에 수업을 합니다. 수업료는 무료이고 교재도 회사에서 줍니다.",
     "Our company runs a Korean class for foreign workers. Lessons are every Wednesday at seven in the evening. The class is free, and the company provides the textbook.",
     [("회사의 한국어 교실", "The company's Korean class"), ("외국인 근로자 모집", "Recruiting foreign workers"), ("교재 판매", "Selling textbooks"), ("수요일 회의", "The Wednesday meeting")], "Time, cost and books of a Korean class.", "workplace-culture", "easy"),
    ("추석은 음력 팔월 십오일입니다. 이때 사람들은 송편을 만들어 먹고 조상에게 차례를 지냅니다. 밤에는 가족과 함께 보름달을 보면서 소원을 빕니다.",
     "Chuseok falls on the fifteenth day of the eighth lunar month. People make and eat songpyeon and hold memorial rites for their ancestors. At night they look at the full moon with their families and make wishes.",
     [("추석", "Chuseok"), ("달의 모양", "The shape of the moon"), ("떡 가게", "A rice cake shop"), ("가을 날씨", "Autumn weather")], "Songpyeon, ancestral rites and the full moon: Chuseok.", "korean-culture", "easy"),
    ("기계를 사용하기 전에는 기계에 이상이 없는지 확인해야 합니다. 작업 중에 기계에서 이상한 소리가 나면 바로 기계를 멈춥니다. 그리고 관리자에게 알립니다.",
     "Before using a machine you must check there is nothing wrong with it. If the machine makes a strange noise during work, stop it immediately and tell the manager.",
     [("기계를 안전하게 사용하는 방법", "Using machines safely"), ("기계 사는 방법", "Buying a machine"), ("관리자의 하루", "A manager's day"), ("소리 듣기 연습", "Listening practice")], "Check, stop if odd, report: safe machine use.", "tools-machines", "medium"),
    ("저는 주말마다 시장에 갑니다. 시장은 마트보다 물건 값이 싸고 사람들도 친절합니다. 가끔 주인 아주머니가 과일을 더 주시기도 합니다.",
     "I go to the market every weekend. Things are cheaper at the market than at the supermarket, and the people are friendly. Sometimes the stallholder gives me extra fruit.",
     [("시장을 좋아하는 이유", "Why the writer likes the market"), ("마트 가는 길", "The way to the supermarket"), ("과일 농장", "A fruit farm"), ("주말 근무", "Working at weekends")], "Cheaper prices and friendly people: why the writer likes markets.", "daily-life", "medium"),
    ("한국에서는 대중교통을 이용할 때 교통카드를 많이 씁니다. 교통카드는 편의점에서 사고 돈을 충전할 수 있습니다. 버스에서 지하철로 갈아타면 요금이 할인됩니다.",
     "In Korea people use transport cards for public transport. You can buy a card at a convenience store and top it up with money. Changing from bus to underground gives you a discount.",
     [("교통카드 사용", "Using a transport card"), ("편의점 아르바이트", "A convenience store job"), ("버스 운전", "Driving a bus"), ("지하철 노선", "Underground lines")], "Buying, topping up and transfer discounts: transport cards.", "public-services", "medium"),
    ("감기에 걸리지 않으려면 손을 자주 씻어야 합니다. 그리고 따뜻한 물을 많이 마시고 잠을 충분히 자야 합니다. 사람이 많은 곳에서는 마스크를 쓰는 것이 좋습니다.",
     "To avoid catching a cold, wash your hands often. Drink plenty of warm water and get enough sleep. Wearing a mask in crowded places is a good idea.",
     [("감기 예방", "Preventing colds"), ("마스크 만드는 법", "Making masks"), ("물의 종류", "Kinds of water"), ("병원 위치", "Where the hospital is")], "Washing hands, rest and masks: preventing a cold.", "public-services", "easy"),
    ("우리 기숙사에는 몇 가지 규칙이 있습니다. 밤 열한 시 이후에는 조용히 해야 합니다. 방에서 요리를 하면 안 되고 담배는 밖에서만 피울 수 있습니다.",
     "Our dormitory has a few rules. You must be quiet after eleven at night. Cooking in your room is not allowed, and you may smoke only outside.",
     [("기숙사 규칙", "Dormitory rules"), ("요리 수업", "A cooking class"), ("담배 가격", "The price of cigarettes"), ("밤 운동", "Exercise at night")], "Quiet hours, no cooking, smoking outside: dorm rules.", "basic-life", "easy"),
    ("근로계약서에는 일하는 시간, 월급, 쉬는 날 등이 쓰여 있습니다. 계약서에 사인하기 전에 내용을 꼭 확인해야 합니다. 모르는 내용이 있으면 물어보고 사인해야 합니다.",
     "An employment contract sets out working hours, pay, days off and so on. You must check its contents before signing. If there is anything you don't understand, ask before you sign.",
     [("근로계약서 확인", "Checking an employment contract"), ("사인 연습", "Practising a signature"), ("월급 올리기", "Getting a pay rise"), ("회사 옮기기", "Changing company")], "Read and ask before signing a contract.", "laws-systems", "medium"),
    ("저는 지난 주말에 동료들과 바다에 갔습니다. 바다에서 수영도 하고 맛있는 생선회도 먹었습니다. 오랜만에 일을 잊고 즐거운 시간을 보냈습니다.",
     "Last weekend I went to the seaside with co-workers. We swam in the sea and ate delicious raw fish. For the first time in ages I forgot about work and had a great time.",
     [("주말 여행", "A weekend trip"), ("수영 대회", "A swimming race"), ("생선 요리법", "A fish recipe"), ("회사 일", "Work at the company")], "A trip to the sea with co-workers.", "daily-life", "easy"),
    ("물건을 들 때는 허리를 굽히지 말고 무릎을 굽혀서 들어야 합니다. 물건을 몸 가까이에 붙여서 들면 허리가 덜 아픕니다. 너무 무거운 물건은 다른 사람과 함께 듭니다.",
     "When lifting things, bend your knees, not your back. Holding the load close to your body is easier on your back. Very heavy things should be lifted with someone else.",
     [("물건을 안전하게 드는 방법", "How to lift safely"), ("허리 운동", "Back exercises"), ("무거운 물건 사기", "Buying heavy goods"), ("배달하는 방법", "How to deliver")], "Knees bent, load close, share heavy loads: safe lifting.", "industrial-safety", "medium"),
    ("한국에서 일하는 외국인 근로자도 다치면 산재 보험의 도움을 받을 수 있습니다. 일하다가 다치면 먼저 치료를 받고 회사에 알립니다. 치료비는 산재 보험에서 냅니다.",
     "Foreign workers in Korea can also get help from industrial accident insurance if they are injured. If you are hurt at work, first get treatment and then tell the company. The insurance pays for the treatment.",
     [("산재 보험", "Industrial accident insurance"), ("병원 예약", "Booking a hospital"), ("보험 회사 취직", "Getting a job at an insurer"), ("회사 휴가", "Company leave")], "Injury at work and the insurance that pays: 산재 보험.", "laws-systems", "hard"),
    ("저는 퇴근 후에 기숙사에서 한국 드라마를 봅니다. 드라마를 보면 한국어 듣기 공부도 되고 한국 문화도 알 수 있습니다. 요즘은 자막 없이도 조금 이해할 수 있습니다.",
     "After work I watch Korean dramas in the dormitory. Watching dramas helps my Korean listening and teaches me about Korean culture. These days I can understand a little even without subtitles.",
     [("드라마로 한국어 공부하기", "Learning Korean through dramas"), ("드라마 배우", "Drama actors"), ("텔레비전 사기", "Buying a TV"), ("기숙사 생활비", "Dormitory costs")], "Watching dramas to learn Korean.", "daily-life", "medium"),
    ("이 버스는 시청, 시장, 병원을 지나서 기차역까지 갑니다. 아침 여섯 시부터 밤 열한 시까지 십오 분마다 옵니다. 요금은 교통카드로 내면 천오백 원입니다.",
     "This bus passes City Hall, the market and the hospital on its way to the railway station. It comes every fifteen minutes from six in the morning until eleven at night. The fare is 1,500 won with a transport card.",
     [("버스 안내", "Information about a bus"), ("기차 시간표", "A train timetable"), ("병원 위치", "Where the hospital is"), ("시장 물건 값", "Market prices")], "Route, times and fare of a bus.", "public-services", "medium"),
    ("요즘 회사 식당 음식이 맛있다는 사람이 많습니다. 새로 온 요리사가 여러 나라 음식을 만들어 주기 때문입니다. 지난주에는 베트남 쌀국수가 나와서 인기가 많았습니다.",
     "Many people say the company canteen food has been tasty lately. That's because the new cook makes food from many countries. Last week Vietnamese rice noodles were served and were very popular.",
     [("회사 식당의 음식", "The company canteen food"), ("베트남 여행", "A trip to Vietnam"), ("요리사 모집", "Hiring a cook"), ("식당 청소", "Cleaning the canteen")], "Why the canteen food has improved.", "workplace-culture", "medium"),
    ("한국에는 사계절이 있습니다. 봄에는 꽃이 피고 여름에는 덥습니다. 가을에는 나뭇잎이 빨갛게 변하고 겨울에는 눈이 옵니다.",
     "Korea has four seasons. Flowers bloom in spring and summer is hot. In autumn the leaves turn red, and in winter it snows.",
     [("한국의 사계절", "Korea's four seasons"), ("꽃 이름", "Names of flowers"), ("겨울 운동", "Winter sports"), ("나무 심기", "Planting trees")], "Spring, summer, autumn, winter: the seasons.", "korean-culture", "easy"),
    ("이번 달부터 출근 시간에 지문으로 출근을 확인합니다. 출근하면 입구에 있는 기계에 손가락을 대세요. 퇴근할 때도 똑같이 하면 됩니다.",
     "From this month, arrival at work is recorded by fingerprint. When you arrive, put your finger on the machine at the entrance. Do the same when you leave.",
     [("출퇴근 확인 방법", "How arrival and departure are recorded"), ("손가락 다쳤을 때", "When you hurt a finger"), ("기계 고치기", "Repairing a machine"), ("입구 청소", "Cleaning the entrance")], "Fingerprint clocking-in and clocking-out.", "workplace-culture", "medium"),
    ("저는 돈을 아끼려고 가계부를 씁니다. 매일 쓴 돈을 적고 한 달이 끝나면 계산합니다. 가계부를 쓰니까 필요 없는 물건을 덜 사게 되었습니다.",
     "I keep a household budget book to save money. Every day I write down what I spent, and at the end of the month I add it up. Since I started, I buy fewer things I don't need.",
     [("돈을 아끼는 방법", "A way to save money"), ("공책 사기", "Buying a notebook"), ("계산기 사용법", "Using a calculator"), ("월급날", "Payday")], "Recording spending to save money.", "daily-life", "medium"),
    ("작업장에서는 정리 정돈이 중요합니다. 바닥에 물건이 있으면 걸려서 넘어질 수 있습니다. 사용한 공구는 바로 제자리에 놓아야 합니다.",
     "Keeping things tidy matters at work. Things left on the floor can trip people up. Tools should be put back in their place as soon as they've been used.",
     [("작업장 정리 정돈", "Keeping the workplace tidy"), ("공구 사는 곳", "Where to buy tools"), ("넘어졌을 때 치료", "First aid after a fall"), ("바닥 공사", "Laying a floor")], "Tidiness prevents trips; put tools away.", "industrial-safety", "easy"),
    ("고용허가제로 한국에 온 외국인 근로자는 처음에 삼 년 동안 일할 수 있습니다. 회사가 다시 고용을 원하면 일 년 십 개월을 더 일할 수 있습니다.",
     "Foreign workers who come to Korea under the Employment Permit System can work for three years at first. If the company wants to re-hire them, they can work for another one year and ten months.",
     [("외국인 근로자의 취업 기간", "How long foreign workers may work"), ("회사 옮기는 방법", "How to change company"), ("비자 신청 서류", "Visa application papers"), ("퇴직금 계산", "Working out severance pay")], "Three years plus an extension: the length of employment.", "laws-systems", "hard"),
    ("오늘 처음으로 한국 친구 집에 초대를 받았습니다. 친구 어머니께서 불고기와 잡채를 만들어 주셨습니다. 저는 과일을 사 가지고 갔는데 모두 좋아하셨습니다.",
     "Today I was invited to a Korean friend's home for the first time. My friend's mother made bulgogi and japchae. I took some fruit, and everyone liked it.",
     [("친구 집 방문", "Visiting a friend's home"), ("과일 가게", "A fruit shop"), ("잡채 만드는 법", "How to make japchae"), ("어머니의 직업", "Mother's job")], "A first visit to a Korean friend's home.", "korean-culture", "easy"),
    ("우리 회사는 매년 봄에 체육 대회를 합니다. 직원들이 팀을 나눠서 축구, 줄다리기, 달리기를 합니다. 이긴 팀은 상품을 받고 모두 같이 저녁을 먹습니다.",
     "Our company holds a sports day every spring. Staff split into teams for football, tug of war and running. The winning team gets prizes, and everyone has dinner together.",
     [("회사 체육 대회", "The company sports day"), ("축구 규칙", "Football rules"), ("상품 가격", "The price of prizes"), ("봄 날씨", "Spring weather")], "Teams, games and prizes: a company sports day.", "workplace-culture", "easy"),
    ("휴대폰을 새로 사려면 외국인 등록증이 필요합니다. 요금제는 한 달에 쓰는 데이터와 통화 시간을 생각해서 고르면 됩니다. 해외 전화를 자주 하면 국제 전화 요금도 확인하세요.",
     "To get a new mobile you need your alien registration card. Choose a plan based on how much data and call time you use each month. If you call abroad often, check the international call rates too.",
     [("휴대폰 개통하기", "Getting a mobile phone"), ("외국인 등록증 만들기", "Getting an alien registration card"), ("데이터 아끼기", "Saving data"), ("고향에 전화하기", "Calling home")], "ID, choosing a plan and call rates: getting a phone.", "public-services", "medium"),
    ("소화기를 쓸 때는 먼저 안전핀을 뽑습니다. 그다음에 호스를 불 쪽으로 향하게 합니다. 마지막으로 손잡이를 꽉 누르면 됩니다.",
     "To use a fire extinguisher, first pull out the safety pin. Then point the hose towards the fire. Finally, squeeze the handle firmly.",
     [("소화기 사용 방법", "How to use a fire extinguisher"), ("불을 피우는 방법", "How to light a fire"), ("호스 고치기", "Repairing a hose"), ("안전핀 사기", "Buying safety pins")], "Pin, aim, squeeze: using an extinguisher.", "industrial-safety", "easy"),
    ("저는 매달 월급의 반을 고향에 보냅니다. 그 돈으로 동생이 학교에 다니고 부모님이 생활하십니다. 힘들 때도 있지만 가족을 생각하면 힘이 납니다.",
     "Every month I send half my pay home. With that money my younger sibling goes to school and my parents live. It's hard sometimes, but thinking of my family keeps me going.",
     [("가족을 위해 일하는 마음", "Working for one's family"), ("학교 생활", "School life"), ("은행 이용 방법", "How to use a bank"), ("월급 계산", "Working out pay")], "Sending money home for the family.", "basic-life", "medium"),
    ("비닐하우스 안은 바깥보다 훨씬 덥습니다. 그래서 여름에는 창문을 열어서 바람이 통하게 해야 합니다. 겨울에는 반대로 따뜻하게 하기 위해 문을 잘 닫아야 합니다.",
     "It is much hotter inside a greenhouse than outside. So in summer you must open the windows to let air through. In winter, on the other hand, you must keep the doors shut to keep it warm.",
     [("비닐하우스 온도 관리", "Managing greenhouse temperature"), ("창문 고치기", "Fixing windows"), ("겨울 옷", "Winter clothes"), ("채소 팔기", "Selling vegetables")], "Opening and closing to control greenhouse heat.", "job-korean", "hard"),
    ("한국에서는 식당에 들어가면 물과 반찬을 무료로 줍니다. 반찬이 모자라면 더 달라고 할 수 있습니다. 그리고 계산은 보통 나갈 때 카운터에서 합니다.",
     "In Korea, when you go into a restaurant you get water and side dishes for free. If you run out of side dishes you can ask for more. And you usually pay at the counter on the way out.",
     [("한국 식당 이용 문화", "How Korean restaurants work"), ("반찬 만드는 법", "How to make side dishes"), ("식당 아르바이트", "A restaurant job"), ("물 마시는 습관", "Drinking habits")], "Free water and side dishes, paying at the counter.", "korean-culture", "medium"),
    ("지난주에 회사 근처에 새 공원이 생겼습니다. 공원에는 산책길과 운동 기구가 있습니다. 점심을 먹고 나서 동료들과 공원을 걸으면 오후에 덜 피곤합니다.",
     "Last week a new park opened near the company. It has walking paths and exercise equipment. Walking in the park with co-workers after lunch makes the afternoon less tiring.",
     [("회사 근처의 새 공원", "The new park near the company"), ("운동 기구 사는 방법", "How to buy exercise equipment"), ("점심 메뉴", "The lunch menu"), ("오후 작업 시간", "Afternoon working hours")], "A new park and walking there after lunch.", "daily-life", "easy"),
]

assert len(TOPICS) == 48, len(TOPICS)
