"""English versions for the 18 starter reading questions (migration 000097),
which shipped without one, and neutral titles for the starter questions whose
title gave the answer away ("공구 이름: 망치" on a picture of a hammer).
The listening starters already have their English (migration 000099).
"""

SEED_ENGLISH = {
    "eps-seed-r-picture-1": (None, "Look at the picture and choose the matching word or sentence.",
                             ["It's a hammer.", "They're scissors.", "It's an umbrella.", "It's a clock."]),
    "eps-seed-r-picture-2": (None, "Look at the picture and choose the matching word or sentence.",
                             ["They're socks.", "They're gloves.", "They're glasses.", "It's a bag."]),
    "eps-seed-r-grammar-1": (None, "Which underlined part is correct?",
                             ["I eat an apple.", "I meet a friend.", "I go to the factory.", "I rest at the weekend."]),
    "eps-seed-r-grammar-2": (None, "Which underlined part is correct?",
                             ["I listen to music.", "The weather is hot.", "I closed the window.", "The noodles are spicy."]),
    "eps-seed-r-practical-1": ("Happy Pharmacy. Opening hours 9 a.m. to 7 p.m. Closed on Sundays. Phone 031-123-4567. Danwon-gu, Ansan, Gyeonggi-do.",
                               "When is this pharmacy closed?",
                               ["Saturday.", "Sunday.", "Monday.", "It opens every day."]),
    "eps-seed-r-practical-2": ("Caution: electric shock.", "What does this sign mean?",
                               ["You could get an electric shock.", "The floor is slippery.", "You may not smoke.", "You must wear a safety helmet."]),
    "eps-seed-r-word-1": ("Monthly salary.", "Which is related to this word?",
                          ["Money you are paid by the company.", "Food you eat at the company.", "Clothes you wear at the company.", "A room you sleep in at the company."]),
    "eps-seed-r-word-2": ("Dormitory.", "Which is related to this word?",
                          ["The place where workers work.", "The place where workers take out money.", "The place where workers live.", "The place where workers buy food."]),
    "eps-seed-r-blank-1": ("It's cold, so ____ thick clothes.", "Choose the best answer for the blank.",
                           ["wear", "eat", "ride", "read"]),
    "eps-seed-r-blank-2": ("Before cleaning the machine, you must ____ the power.", "Choose the best answer for the blank.",
                           ["turn on", "turn off", "buy", "borrow"]),
    "eps-seed-r-def-1": ("A tool used to cut wood or metal. Its blade has many sharp teeth.", "Choose the word that fits the description.",
                         ["saw", "hammer", "screwdriver", "tape measure"]),
    "eps-seed-r-def-2": ("A tool for measuring length. It stretches when you pull it and winds back in when you press the button.",
                         "Choose the word that fits the description.",
                         ["pliers", "tape measure", "shovel", "brush"]),
    "eps-seed-r-topic-1": ("In Korea people eat rice cake soup at New Year. People believe eating it makes you a year older. Families also gather and bow to their elders.",
                           "Read the text and choose what it is about.",
                           ["New Year customs", "Food prices", "Travel plans", "Changes in the weather"]),
    "eps-seed-r-topic-2": ("To avoid getting hurt at work you must follow the rules. Wear protective equipment before work, and keep your hands out of a moving machine. Also wipe up any water on the floor straight away.",
                           "Read the text and choose what it is about.",
                           ["Applying for leave", "Safety rules", "Working out pay", "Where the staff dinner is"]),
    "eps-seed-r-detail-1": ("Our company canteen is open from 7 to 8 in the morning and from 12 to 1 at lunchtime. Dinner is not served. To use the canteen you must show your staff card.",
                            "Read the text and choose the statement that matches it.",
                            ["You can eat dinner in the canteen.", "The lunch break is one hour.", "The canteen is open all day.", "You can use the canteen without a staff card."]),
    "eps-seed-r-detail-2": ("A foreign worker who wants to change company must apply to the job centre. The number of times you can change company is limited. After changing, you must sign a new employment contract with the new company.",
                            "Read the text and choose the statement that matches it.",
                            ["You don't need to apply when changing company.", "You can change company as often as you like.", "You must sign a new contract with the new company.", "You only ever sign one contract."]),
    "eps-seed-r-ttp-1": ("You use it on rainy days. You open it and hold it over your head.", "Read the description and choose the matching picture.",
                         ["umbrella", "cap", "gloves", "glasses"]),
    "eps-seed-r-ttp-2": ("When there is a fire, you put it out with this. Pull out the safety pin and squeeze the handle.",
                         "Read the description and choose the matching picture.",
                         ["hammer", "telephone", "fire extinguisher", "ladder"]),
}

# Starter titles that named the answer, and what replaces them.
SEED_TITLES = {
    "eps-seed-r-picture-1": ("공구 이름: 망치", "그림 보고 고르기 1"),
    "eps-seed-r-picture-2": ("보호 장비: 장갑", "그림 보고 고르기 2"),
    "eps-seed-r-blank-1": ("빈칸: 옷을 입다", "빈칸 채우기 1"),
    "eps-seed-r-blank-2": ("빈칸: 전원을 끄다", "빈칸 채우기 2"),
    "eps-seed-r-def-1": ("도구 설명: 톱", "설명에 맞는 어휘 1"),
    "eps-seed-r-def-2": ("도구 설명: 줄자", "설명에 맞는 어휘 2"),
    "eps-seed-r-topic-1": ("글의 주제: 설날", "글의 주제 1"),
    "eps-seed-r-topic-2": ("글의 주제: 안전 수칙", "글의 주제 2"),
    "eps-seed-r-ttp-1": ("설명: 우산", "설명 보고 그림 고르기 1"),
    "eps-seed-r-ttp-2": ("설명: 소화기", "설명 보고 그림 고르기 2"),
    "eps-seed-l-sound-1": ("소리 구별: 공장", "소리 구별 1"),
    "eps-seed-l-sound-2": ("소리 구별: 시장", "소리 구별 2"),
    "eps-seed-l-picture-1": ("그림 고르기: 우유", "듣고 그림 고르기 1"),
    "eps-seed-l-picture-2": ("그림 고르기: 상자 옮기기", "듣고 그림 고르기 2"),
    "eps-seed-l-pq-1": ("위치: 가방", "그림 보고 대답하기 1"),
    "eps-seed-l-pq-2": ("시간: 세 시", "그림 보고 대답하기 2"),
}
