"""IELTS Speaking practice items, batch 4: fifty new items for each part.

Original Prepyo practice material written to the public IELTS Speaking format
(Part 1 familiar topics, Part 2 long turn with a cue card, Part 3 abstract
discussion). Not official, recalled or copied test content. Every item is
checked against the whole bank by scripts/bank_check.py.
"""

# Part 1: (title, questions). Three short questions on a familiar topic.
PART1 = [
    ('Baking', ['Have you ever baked a cake or a loaf of bread?', 'Did anyone in your family bake when you were a child?', 'Why do you think so many people enjoy baking?']),
    ('Umbrellas', ['Do you usually carry an umbrella with you?', 'Would you ever buy an umbrella as a present for someone?', 'Have you ever lost or broken an umbrella?']),
    ('Sunshine', ['Do you like sunny weather?', 'What do you like to do on a sunny day?', 'Are there times when you prefer to stay out of the sun?']),
    ('Fast Food', ['How often do you eat fast food?', 'What kind of fast food is popular where you live?', 'Did you eat fast food when you were a child?']),
    ('Snacks', ['Do you often eat snacks between meals?', 'What was your favourite snack when you were younger?', 'Do you think snacks are bad for your health?']),
    ('Spicy Food', ['Do you enjoy spicy food?', 'Is spicy food common in your country?', 'Have you ever eaten a dish that was far too spicy?']),
    ('Drinking Water', ['How much water do you drink every day?', 'Do you prefer tap water or bottled water?', 'Do you take a water bottle with you when you go out?']),
    ('Taxis', ['How often do you take a taxi?', 'Do you prefer to book a taxi on an app or stop one in the street?', 'Would you like to work as a taxi driver?']),
    ('Motorbikes', ['Are motorbikes common where you live?', 'Have you ever ridden on a motorbike?', 'Why do some people prefer motorbikes to cars?']),
    ('Traffic Jams', ['Is traffic a problem in the place where you live?', 'What do you usually do when you are stuck in traffic?', 'At what times of day are the roads busiest in your town?']),
    ('Part-time Jobs', ['Have you ever had a part-time job?', 'Is it common for students in your country to work part-time?', 'What kind of part-time job would you like to do?']),
    ('Lunch Breaks', ['What do you usually do in your lunch break?', 'Do you prefer to eat lunch alone or with other people?', 'When you were at school, how long was the lunch break?']),
    ('Homework', ['Did you get a lot of homework at school?', 'Where did you usually do your homework?', 'Do you think children should be given homework every day?']),
    ('Teachers', ['Did you have a favourite teacher at school?', 'What do you think makes a good teacher?', 'Would you like to be a teacher yourself?']),
    ('Classmates', ['Do you still keep in touch with your old classmates?', 'What did you and your classmates do together at break time?', 'Did you prefer sitting at the front or the back of the class?']),
    ('Pens and Pencils', ['Do you prefer writing with a pen or a pencil?', 'Do you still carry a pen with you every day?', 'Has anyone ever given you a pen as a present?']),
    ('Mirrors', ['How many mirrors are there in your home?', 'How often do you look in a mirror during the day?', 'Would you ever buy a mirror just to decorate a room?']),
    ('The View From Your Window', ['What can you see from your window at home?', 'Do you like the view from your window?', 'Would you prefer a view of a city or of the countryside?']),
    ('Boredom', ['Do you often feel bored?', 'What do you do when you are bored?', 'Did you get bored more often when you were a child?']),
    ('Robots', ['Have you ever seen a robot in real life?', 'Would you like to have a robot to help you at home?', 'What kinds of jobs would you like to see done by robots?']),
    ('Phone Calls', ['Who do you phone most often?', 'Do you prefer phoning people or sending them messages?', 'Is there a phone call that you remember well?']),
    ('Computer Games', ['Do you play computer games?', 'What games did you play when you were younger?', 'Do you think children spend too much time on computer games?']),
    ('Running', ['Do you ever go running?', 'Is running a popular form of exercise in your country?', 'Would you ever enter a running race?']),
    ('Concerts', ['Have you ever been to a concert?', 'What kind of concert would you like to go to?', 'Do you prefer listening to live music or recorded music?']),
    ('The Theatre', ['Have you ever been to the theatre?', 'Did you take part in any plays at school?', 'How much does it cost to go to the theatre?']),
    ('Cartoons', ['Did you watch cartoons when you were a child?', 'Do you still watch cartoons now?', 'Why do you think some adults enjoy cartoons?']),
    ('Famous People', ['Is there a famous person you particularly like?', 'What kinds of people become famous in your country?', 'Would you like to be famous?']),
    ('Glasses and Sunglasses', ['Do you wear glasses or sunglasses?', 'Where do people usually buy glasses in your country?', 'Why do some people wear sunglasses even when it is not sunny?']),
    ('Losing Things', ['Do you often lose things?', 'What was the last thing you lost?', 'What do you do to avoid losing your keys or your phone?']),
    ('Your Kitchen', ['What is your kitchen like?', 'How much time do you spend in the kitchen?', 'Is there anything you would change about your kitchen?']),
    ('The Countryside', ['How often do you go to the countryside?', 'What do you like to do there?', 'Would you like to live on a farm?']),
    ('Tall Buildings', ['Are there many tall buildings in your city?', 'Would you like to live or work on a high floor?', 'Have you ever been to the top of a very tall building?']),
    ('Bridges', ['Are there any well-known bridges in your town or city?', 'Do you enjoy walking across bridges?', 'Have you ever crossed a very long bridge?']),
    ('Local Festivals', ['Are there any festivals held in your town?', 'What happens at them?', 'Would you like to go to a festival in another country?']),
    ('Brothers and Sisters', ['Do you have any brothers or sisters?', 'Did you get on well with them when you were younger?', 'Do you think it is better to be an only child or to have brothers and sisters?']),
    ('Grandparents', ['How often do you see your grandparents?', 'What did you do with them when you were a child?', 'Have your grandparents taught you anything useful?']),
    ('Volunteering', ['Have you ever done any voluntary work?', 'What kind of voluntary work is common in your area?', 'Would you like to volunteer in the future?']),
    ('Good Manners', ['What are considered good manners in your country?', 'Who taught you good manners?', 'Do you think young people are less polite than they used to be?']),
    ('Smiling', ['Do you smile a lot?', 'What kinds of things make you smile?', 'Do you smile at people you do not know?']),
    ('Numbers', ['Do you have a favourite number?', 'Are you good at remembering numbers, such as phone numbers?', 'Do people in your country think some numbers are lucky?']),
    ('Insects', ['Are there many insects where you live?', 'Are you afraid of any insects?', 'Did you ever catch insects when you were a child?']),
    ('Zoos', ['When did you last visit a zoo?', 'Which animals do you most like to see there?', 'Do you think children enjoy going to the zoo?']),
    ('Islands', ['Have you ever been to an island?', 'Is there a famous island in your country?', 'Would you like to live on an island?']),
    ('Forests', ['Is there a forest near your home?', 'What do people do when they visit forests?', 'Did you spend time in forests as a child?']),
    ('Camping', ['Have you ever been camping?', 'Is camping popular in your country?', 'Would you rather sleep in a tent or stay in a hotel?']),
    ('Hobbies', ['What hobbies do you have?', 'Did you have the same hobbies when you were a child?', 'Is there a hobby you would like to take up?']),
    ('Radio and Podcasts', ['Do you listen to the radio?', 'Do you ever listen to podcasts?', 'At what times of day do you usually listen to them?']),
    ('Paying for Things', ['Do you usually pay by card or in cash?', 'Do you ever pay with your phone?', 'Do you think people will stop using cash?']),
    ('Having Guests', ['Do you often have guests at your home?', 'What do you usually do when friends come to visit?', "Do you prefer going to other people's homes or having guests?"]),
    ('Tidiness', ['Are you a tidy person?', 'Is your room usually tidy?', 'Do you find it hard to keep your things tidy?']),
]

# Part 2: (title, cue, points, explain). Three prompts plus "and explain".
PART2 = [
    ('A Relative You Enjoy Spending Time With', 'Describe a relative you enjoy spending time with.', ['who this relative is', 'how often you see each other', 'what you do together'], 'why you enjoy spending time with this relative'),
    ('A Person Who Is Good at Cooking', 'Describe a person you know who is good at cooking.', ['how you know this person', 'what dishes they cook', 'how they learned to cook'], 'what you think of their cooking'),
    ('A Creative Person You Know', 'Describe a creative person you know.', ['who this creative person is', 'what creative things they do', 'how long they have been doing them'], 'why you think this person is so creative'),
    ('A Sportsperson You Admire', 'Describe a sportsperson you admire.', ['who this sportsperson is', 'which sport they play', 'how you first heard about them'], 'why you admire this sportsperson'),
    ('A Successful Person You Know', 'Describe someone you know personally who has been successful.', ['what your connection with this person is', 'what they have achieved', 'how they achieved it'], 'what you have learned from their success'),
    ('A Person Who Makes You Laugh', 'Describe a person who often makes you laugh.', ['who this funny person is', 'how often you see them', 'what they do or say that makes you laugh'], 'why you enjoy their sense of humour'),
    ('A Musician or Singer You Like', 'Describe a musician or singer you like.', ['who the musician or singer is', 'what kind of music they perform', 'how you first heard their music'], 'why you like their music'),
    ('A Café You Often Go To', 'Describe a café that you often go to.', ['where the café is', 'what food and drink it serves', 'what you usually do there'], 'why you like this café'),
    ('A Library or Bookshop You Like', 'Describe a library or bookshop that you like.', ['where the library or bookshop is', 'what it looks like inside', 'how often you visit it'], 'why you like going there to read or browse'),
    ('A Place Where You Do Exercise', 'Describe a place where you go to do sport or exercise.', ['where it is', 'what facilities it has', 'who you usually go with'], 'why you like exercising there'),
    ('A Hotel You Stayed In', 'Describe a hotel you have stayed in.', ['where the hotel was', 'why you stayed there', 'what the rooms and service were like'], 'whether you would recommend the hotel'),
    ('A Small Town or Village You Visited', 'Describe a small town or village you have visited.', ['where the town or village is', 'why you went there', 'what you saw and did'], 'what you liked or disliked about this town or village'),
    ('A Museum or Gallery You Visited', 'Describe a museum or art gallery you went to.', ['where the museum or gallery is', 'what kind of things are on display', 'who you went with'], 'what you found most interesting in the museum or gallery'),
    ('A Traditional Dish From Your Country', 'Describe a traditional dish from your country.', ['what the dish is', 'how it is made', 'when people usually eat it'], 'why people in your country like this dish'),
    ('A City You Enjoyed Visiting', 'Describe a city you enjoyed visiting.', ['which city it was', 'who you went with', 'which places you visited in the city'], 'why you enjoyed your time in this city'),
    ('A Piece of Furniture You Like', 'Describe a piece of furniture that you like.', ['what it is', 'where it is', 'how long you have had it'], 'why you like this piece of furniture'),
    ('An Old Object Your Family Has Kept', 'Describe an old object that your family has kept for many years.', ['what the object is', 'where it came from', 'where it is kept now'], 'why your family has kept it'),
    ('An Invention You Think Is Important', 'Describe an invention that you think is important.', ['what the invention is', 'when it was invented', 'how people use it'], 'why you think this invention is important'),
    ('Something You Carry Every Day', 'Describe an item that you carry with you every day.', ['what the item is', 'how long you have had it', 'what you use it for'], 'why you always take it with you'),
    ('A Musical Instrument You Would Like to Play', 'Describe a musical instrument you would like to be able to play.', ['what the instrument is', 'where you have heard it played', 'how you could learn'], 'why you would like to play this instrument'),
    ('Something You Are Saving Up For', 'Describe something you are saving money to buy.', ['what it is', 'how much it costs', 'how you are saving for it'], 'why you want to buy it'),
    ('A Tree or Plant You Like', 'Describe a tree or plant that you like.', ['what the tree or plant is', 'where you have seen it', 'what it looks like in different seasons'], 'why you like this tree or plant'),
    ('A Night You Spent Outdoors', 'Describe a time when you spent a night outdoors, for example on a camping trip.', ['where you were', 'who you were with', 'what you did'], 'how you felt about sleeping outside'),
    ('A Birthday Celebration You Remember', 'Describe a birthday celebration you remember well.', ['whose birthday it was', 'where the celebration took place', 'what people did'], 'why you remember this birthday'),
    ('A Live Performance You Enjoyed', 'Describe a live performance you enjoyed, such as a concert, a play or a dance show.', ['what the performance was', 'where and when you saw it', 'who you went with'], 'why you enjoyed the performance'),
    ('A Time You Got Lost', 'Describe a time when you got lost.', ['where you were', 'how you got lost', 'how you found your way'], 'how you felt while you were lost'),
    ('A Mistake You Learned From', 'Describe a mistake you made that taught you something.', ['what the mistake was', 'when you made it', 'what effect it had'], 'what you learned from this mistake'),
    ('A Time Someone Praised You', 'Describe a time when someone praised you for something you had done.', ['who praised you', 'what you had done', 'what they said'], 'how you reacted to the praise'),
    ('Something You Did for the First Time', 'Describe something you did for the first time recently.', ['what you did', 'when and where you did it', 'why you decided to do it'], 'how you felt about doing it'),
    ('A Disagreement You Had With Someone', 'Describe a time when you disagreed with someone.', ['who the other person was', 'what you disagreed about', 'how the disagreement ended'], 'how you felt once it was over'),
    ('A Time You Had to Decide Quickly', 'Describe a time when you had to make a decision very quickly.', ['what the situation was', 'what you decided', 'what happened next'], 'whether you think your quick decision was correct'),
    ('A Holiday You Would Like to Take', 'Describe a holiday you would like to take in the future.', ['where you would go', 'who you would take with you', 'what you would like to see and do'], 'why you would choose this holiday'),
    ('A Meal You Cooked for Other People', 'Describe a meal you cooked for other people.', ['what you cooked', 'who you cooked it for', 'why you cooked it'], 'how the meal went'),
    ("A Visit to Someone's Home", "Describe a visit you made to a friend's or relative's home.", ['whose home it was', 'why you went there', 'what you did during the visit'], 'what you enjoyed most about being a guest'),
    ('A Day You Spent Alone', 'Describe a day when you spent most of the time on your own.', ['which day it was', 'why you were alone', 'how you spent your time'], 'how you felt about being on your own'),
    ('A Talk or Presentation You Gave', 'Describe a talk or presentation you gave.', ['what the talk was about', 'who the audience was', 'how you prepared for it'], 'how nervous you felt before and during the talk'),
    ('Something You Looked Forward To', 'Describe something you looked forward to for a long time.', ['what it was', 'why you were looking forward to it', 'what happened when it finally came'], 'whether it was as good as you had expected'),
    ('A School Trip You Remember', 'Describe a school trip you remember.', ['where you went', 'how old you were', 'what you did during the trip'], 'why you remember this trip'),
    ('A TV Programme You Often Watch', 'Describe a television programme you often watch.', ['what the programme is called', 'what it is about', 'when it is on'], 'why you like this programme'),
    ('An Article You Read', 'Describe an interesting article you read in a newspaper, a magazine or online.', ['what the article was about', 'where you read it', 'what new information it gave you'], 'why the article caught your attention'),
    ('A Game You Played as a Child', 'Describe a game you played when you were a child.', ['what the game was', 'who you played it with', 'how you played it'], 'why you enjoyed playing this game'),
    ('A Subject You Enjoyed at School', 'Describe a subject you enjoyed studying at school.', ['which subject it was', 'who taught it', 'what you did in the lessons'], 'why you enjoyed this subject'),
    ('A Time You Were Stuck in Traffic', 'Describe a time when you were stuck in traffic.', ['where you were going', 'why the traffic was so bad', 'what you did while you were waiting'], 'how you felt about the delay'),
    ('A Company You Would Like to Work For', 'Describe a company you would like to work for.', ['what the company is', 'what it does', 'how you found out about the company'], 'why you would like to work there'),
    ('A Pet You Remember', 'Describe a pet that you or someone you know had.', ['what kind of animal it was', 'who it belonged to', 'what it was like'], 'why you remember this pet'),
    ('An Invitation You Accepted', 'Describe an invitation you received and accepted.', ['who invited you', 'what the invitation was for', 'how you were invited'], 'why you accepted it'),
    ('A Well-Designed Everyday Object', 'Describe an everyday object that you think is well designed.', ['what the object is', 'what people use it for', 'where you can buy one'], 'what makes it so well designed'),
    ('Something You Found That Belonged to Someone Else', 'Describe a time when you found something that belonged to someone else.', ['what you found', 'where you found it', 'how you returned it to its owner'], 'how you felt about what happened'),
    ('A Bicycle Ride You Remember', 'Describe a bicycle ride you remember.', ['where you rode', 'who you were with', 'what you saw along the route'], 'why you remember this ride'),
    ('An Early Childhood Memory', 'Describe one of your earliest memories.', ['how old you were', 'where you were', 'what happened'], 'why you think this memory has stayed so clear'),
]

# Part 3: (title, questions). Three abstract questions on a theme.
PART3 = [
    ('Grandparents and Grandchildren', ['What can grandparents teach their grandchildren?', 'Do grandparents play a bigger or smaller part in family life than they did in the past?', 'Should grandparents be expected to look after children while the parents are at work?']),
    ('Fast Food and Convenience', ['Why has fast food become so popular?', 'Should fast food restaurants be allowed near schools?', 'Will people cook less at home as ready meals become cheaper?']),
    ('Creativity in Schools', ['Can creativity be taught, or are some people simply born creative?', 'Do schools give enough time to subjects such as art and music?', 'Which jobs need creative people most?']),
    ('Sports Stars and Young People', ['Why do young people admire sports stars?', 'Should famous athletes be expected to set a good example?', 'Does watching top athletes encourage children to be more active?']),
    ('Humour and Comedy', ['Why do people from different countries find different things funny?', 'Is humour useful in the workplace?', 'Are there subjects that people should not joke about?']),
    ('Music and Young People', ['Why is music so important to many teenagers?', 'Should every child learn to play a musical instrument at school?', 'How has the way people listen to music changed?']),
    ('Cafés and Meeting Places', ['Why have cafés become such popular places to meet?', 'Do people need public places where they can meet without spending money?', 'How are the places where young people meet different from those older people prefer?']),
    ('The Future of Bookshops', ['Why do some people still prefer to buy books in a shop?', 'Can small bookshops compete with large online sellers?', 'Do you think printed books will ever disappear?']),
    ('Public Sports Facilities', ['Should sports centres and swimming pools be free to use?', 'What sports facilities does a town need?', 'Why do some people stop exercising as they get older?']),
    ('Working in Tourism', ['What are the advantages and disadvantages of working in the tourist industry?', 'Why do some hotels offer better service than others?', 'How does tourism create jobs in a local area?']),
    ('Village Life', ['What are the advantages of growing up in a small village?', 'Is life in a village less stressful than life in a city?', 'How could villages be made more attractive places for families?']),
    ('Buying Second-Hand Goods', ['Why do some people prefer to buy second-hand things?', 'Are there any products that people should always buy new?', 'Has the internet made it easier to buy and sell used items?']),
    ('Keeping Old Things', ['Why do families keep old objects that they no longer use?', 'Should old objects be kept even when they are no longer useful?', 'Do young people value old things as much as their grandparents?']),
    ('Inventions and Progress', ["Which invention of the last hundred years has changed people's lives the most?", 'Do all new inventions make life better?', 'Should governments pay for scientific research or leave it to private companies?']),
    ('Skilled Manual Work', ['Why do fewer young people train as plumbers, electricians or builders?', 'Should manual jobs be paid as well as office jobs?', 'Is it more useful to learn a trade than to go to university?']),
    ('Saving and Spending', ['Why do some people find it hard to save money?', 'Should children be given pocket money?', 'Is it more sensible to save money or to spend it on experiences?']),
    ('Camping and Outdoor Holidays', ['Why do some families choose camping holidays?', 'Is camping becoming more or less popular in your country?', 'What effects do large numbers of visitors have on the countryside?']),
    ('Celebrating Birthdays', ['Why do people celebrate birthdays?', "Do parents spend too much money on children's birthday parties?", 'Are some birthdays more important than others in your culture?']),
    ('Live Music and Theatre', ['Why do people pay to see live performances when recordings are available?', 'Should theatres and concert halls receive government money?', 'How can young people be encouraged to go to the theatre?']),
    ('Maps and Navigation Technology', ['How has satellite navigation changed the way people travel?', 'Is it still important to be able to read a paper map?', 'Do people depend too much on their phones for directions?']),
    ('Learning From Mistakes', ['Why are some people afraid of making mistakes?', 'Should teachers let students make mistakes?', 'Is it easier for children or adults to admit that they were wrong?']),
    ('Praise and Motivation', ['Is it important for parents to praise their children?', 'Can too much praise be harmful?', 'Apart from money, what makes people want to work hard?']),
    ('Trying New Experiences', ['Why do some people enjoy trying new things more than others?', 'Are young people more willing to take risks than older people?', 'Should schools encourage shy students to try new hobbies?']),
    ('Arguments and Disagreements', ['What do people in families most often argue about?', 'Is it sometimes good for people to disagree?', 'How can people settle a disagreement without getting angry?']),
    ('Quick Decisions', ['What important decisions do young people have to make?', 'Is it better to make decisions quickly or to take time to think?', 'Should people ask others for advice before making big decisions?']),
    ('Types of Holiday', ['Why do some people prefer package holidays to organising their own trip?', 'Is it better to go on holiday in your own country or abroad?', "How have people's holidays changed since your parents were young?"]),
    ('Hospitality and Guests', ['How do people in your country usually welcome guests?', 'Is it more common now to meet friends in cafés than to invite them home?', "Is it acceptable to arrive at someone's home without an invitation?"]),
    ('Spending Time Alone', ['Why do some people enjoy being alone?', 'Is it good for children to spend some time on their own?', 'Do people who live alone feel lonely more often than others?']),
    ('Public Speaking', ['Why are many people nervous about speaking in public?', 'Should schools teach students how to give presentations?', 'Which jobs require good speaking skills?']),
    ('Learning Outside the Classroom', ['What can students learn on school trips that they cannot learn in class?', 'Should school trips be paid for by parents or by the school?', 'Are museums and galleries good places for children to learn?']),
    ('The Future of Television', ['Do people watch less television than they did in the past?', 'Is television a good way for children to learn?', 'Will people still sit down together to watch the same television channel?']),
    ('Newspapers and Magazines', ['Why are fewer people buying newspapers?', 'Is news on the internet as reliable as news in print?', 'What kinds of magazines are still popular?']),
    ('Traditional Games', ["Why are some traditional children's games disappearing?", 'Do children today play differently from children in the past?', 'Should parents limit the time children spend on screens?']),
    ('The School Curriculum', ['Which subjects should all children study at school?', 'Should students be allowed to choose their subjects at a young age?', 'Should practical skills such as cooking and managing money be part of every curriculum?']),
    ('Long Commutes', ['Why do some people accept a long journey to work?', "How does commuting affect people's quality of life?", 'Should employers let staff start and finish work at different times to avoid the rush hour?']),
    ('Choosing an Employer', ['What makes a company a good employer?', 'Do most people prefer to work for large companies or small ones?', 'Should companies be judged on how they treat the environment?']),
    ('Keeping Pets', ['Why do people keep pets?', 'Is having a pet good for children?', 'Should there be rules about keeping pets in flats?']),
    ('Social Occasions', ['Why do people sometimes turn down invitations?', 'Are formal social occasions less common than they used to be?', 'How has technology changed the way people invite others to events?']),
    ('Honesty', ['Is it always wrong to tell a lie?', 'Do you think most people would hand in something valuable they had found?', 'How can parents teach children to be honest?']),
    ('Cycling in Cities', ['Why do more people cycle in some cities than in others?', 'Should cities build more cycle lanes, even if it means less space for cars?', 'Is cycling safe for children in your town?']),
    ('Memory and Remembering', ['Why do people remember some events clearly and forget others?', 'Do people today need to remember as much as people did in the past?', 'What can older people do to keep their memory good?']),
    ('Free Public Transport', ['Should public transport be free for everyone?', 'Who benefits most from cheap buses and trains?', 'Why do many people still prefer to drive?']),
    ('Robots in the Home', ['What household jobs could robots do in the future?', 'Would you trust a robot to look after an elderly relative?', 'Could robots in the home make people lazy?']),
    ('High-Rise Living', ['What are the advantages of living in a tall block of flats?', 'Are high-rise buildings a good solution to housing shortages?', 'Should every new block of flats have a playground and a garden?']),
    ('Zoos and Wildlife Parks', ['Should zoos still exist?', 'Do zoos help to protect endangered animals?', 'Is it better for children to see animals in zoos or in documentaries?']),
    ('Politeness and Manners', ['Are good manners less important than they used to be?', 'Do manners differ from country to country?', 'Should schools teach manners, or is that the job of parents?']),
    ('Packaging and Waste', ['Why do many products have so much packaging?', 'Should shops be made to reduce plastic packaging?', 'Are people in your country willing to change their shopping habits to reduce waste?']),
    ('A Cashless Society', ['Why are people using cash less than before?', 'Who might find it difficult if cash disappeared completely?', 'Do people spend more when they pay by card?']),
    ('Siblings and Family Size', ['How does having brothers and sisters affect a child?', 'Why are families smaller today than they were in the past?', 'Do the oldest children in a family usually have more responsibility?']),
    ('Forests and Woodland', ['Why are forests important?', 'Should trees be cut down to make space for new homes?', 'How can children learn to value the natural world?']),
]
