"""IELTS Writing Task 2 bank 4: fifty new questions for each of the six essay types.

Original Prepyo practice content written to the public IELTS Task 2 formats.
None of it is official, recalled or copied test material. The topics are new:
none repeats a question already in the bank (checked by
scripts/generate_ielts_task2_b4.py with scripts/bank_check.py).

Opinion entries are (title, statement); the generator adds "To what extent do
you agree or disagree?" as migration 000066 does. Discussion entries are
(title, statement) and take DISCUSS. The other types are
(title, statement, question), using the question wordings of
scripts/ielts_task2_types.py (migration 000091).
"""
from ielts_task2_types import (                                        # noqa: F401
    BENEFITS, BOTH_SIDES, CAUSE_SOLVE, CAUSES_EFFECTS, DISCUSS, MEASURES, OUTWEIGH, REASONS_EFFECTS,
    WHY_EFFECTS, WHY_SOLVE,
)

AGREE = 'To what extent do you agree or disagree?'

# Opinion: a clear, arguable statement, then AGREE.
OPINION = [
    ('Driving Tests for Older Drivers',
     'People over the age of 70 should have to take a driving test every few years if they want to keep their driving licence.'),
    ('Major Sporting Events on Free Television',
     'Major sporting events, such as the Olympic Games and the football World Cup, should always be shown on free television channels rather than only on paid services.'),
    ('First Aid Lessons',
     'Every secondary school student should be taught basic first aid as a compulsory part of the curriculum.'),
    ('Fines for Not Recycling',
     'In many countries, households are asked to separate their rubbish for recycling. Those who do not should have to pay a fine.'),
    ('Returning Objects to Their Countries of Origin',
     'Museums should return valuable historical objects to the countries they were originally taken from.'),
    ('Students Assessing Their Teachers',
     'Students should be asked to assess their teachers, and the results should be used when deciding teachers\' pay.'),
    ('Contacting Staff After Work',
     'Employers should not be allowed to contact their staff by phone or email outside working hours.'),
    ('Publishing Salaries',
     'Some people think that companies should make the salaries of all their employees public, so that everyone knows what their colleagues earn.'),
    ('Experience or Qualifications',
     'When choosing new staff, employers should pay more attention to a candidate\'s work experience than to their academic qualifications.'),
    ('Holidays During Term Time',
     'Parents should never take their children out of school during term time for a family holiday.'),
    ('Reading Paper Maps',
     'Now that most people use satellite navigation, there is no longer any need for children to learn how to read a paper map.'),
    ('Banning Short Flights',
     'Some people believe that flights within a country should be banned when the same journey can be made by train in less than four hours.'),
    ('Subtitles or Dubbing',
     'Foreign films and television programmes should be shown with subtitles rather than dubbed into the local language, because this helps viewers learn other languages.'),
    ('Graffiti as Art',
     'Graffiti should be regarded as a form of art rather than as damage to property.'),
    ('Street Performers',
     'It is often argued that street performers, such as musicians and jugglers, make town centres more pleasant places and should be encouraged by local councils.'),
    ('Video Replays in Sport',
     'The use of video technology to help referees make decisions has spoilt the enjoyment of watching sport.'),
    ('Chess as a Sport',
     'Mind games such as chess should be recognised as sports and receive the same public funding as physical sports.'),
    ('Public Service Broadcasting',
     'Governments should continue to fund public television and radio channels, even though there are now many commercial channels to choose from.'),
    ('Prevention Before Treatment',
     'It is often argued that governments should spend more of their health budget on preventing illness than on treating people who are already ill.'),
    ('Cycle Helmets',
     'Wearing a helmet should be compulsory for everyone who rides a bicycle.'),
    ('Lower Speed Limits in Towns',
     'The speed limit on residential streets should be reduced to 20 miles per hour in all towns and cities.'),
    ('Judges or Juries',
     'Serious criminal cases should be decided by professional judges rather than by juries made up of ordinary members of the public.'),
    ('Parents and Damage Caused by Children',
     'Parents should be made to pay for any damage their children cause to other people\'s property.'),
    ('Eating Insects',
     'Some people argue that insects should become a normal part of people\'s diet, as they are a more sustainable source of protein than meat.'),
    ('Free School Meals',
     'Some people think that all schoolchildren should receive a free lunch every day, whatever their parents\' income.'),
    ('Teaching Public Speaking',
     'Schools should teach students how to speak confidently in public, as this skill is just as important as reading and writing.'),
    ('Lessons Outdoors',
     'Primary school children should spend at least one day a week having their lessons outdoors.'),
    ('Computers Marking Written Work',
     'Teachers should use computers to mark students\' essays and other written work, as this would save time and be fairer.'),
    ('Philosophy at School',
     'All secondary school students should have to study philosophy so that they learn how to think critically.'),
    ('Going to the Nearest School',
     'All children should go to their nearest local school, rather than parents being free to choose a school further away.'),
    ('Building Around Cities',
     'The countryside around cities should be protected from new building, even if this means that homes become more expensive.'),
    ('Fireworks for Private Use',
     'The sale of fireworks to the public should be banned, and only organised public displays should be allowed.'),
    ('Buildings That Produce Energy',
     'Every new home and office building should be required to produce some of its own energy, for example from solar panels.'),
    ('Climate Labels on Food',
     'Food packaging should show clearly how much each product contributes to climate change.'),
    ('Too Many Toys',
     'Nowadays, children are given too many toys, and this does them more harm than good.'),
    ('Dropping Subjects at 14',
     'Students should be allowed to stop studying subjects they dislike from the age of 14.'),
    ('Local Newspapers',
     'Local newspapers matter more to a community than national ones, and they deserve financial support from local councils.'),
    ('Learning From Local People',
     'Travellers learn far more about a place by talking to local people than by reading guidebooks or websites.'),
    ('Learning Phrases Before Travelling',
     'Anyone who visits a foreign country should learn at least a few basic phrases in the local language before they go.'),
    ('Members of the Public in Science',
     'Ordinary members of the public, with no scientific training, can make a valuable contribution to scientific research.'),
    ('Scientists Explaining Their Work',
     'Scientists have a duty to explain their work to the general public in language that everyone can understand.'),
    ('Public Money for Stadiums',
     'Some people say that public money should never be used to build stadiums for professional sports clubs.'),
    ('Free Entry to National Parks',
     'Entry to national parks should always be free, even if this means there is less money to protect them.'),
    ('Children in Advertisements',
     'Children should not be allowed to appear in advertisements on television or online.'),
    ('Promotion and Length of Service',
     'Employees should be promoted because of the results they achieve, not because of the number of years they have worked for a company.'),
    ('Naming People Accused of Crimes',
     'Newspapers and websites should not be allowed to publish the names of people accused of a crime unless they are found guilty.'),
    ('Banning Boxing',
     'Sports in which the main aim is to hit an opponent, such as boxing, should be banned.'),
    ('Making Polluters Pay',
     'Companies that pollute the environment should pay the full cost of cleaning up the damage they cause.'),
    ('Music and Programmes Made at Home',
     'Radio and television stations should be required to broadcast a minimum amount of music and programmes produced in their own country.'),
    ('Learning a Language Abroad',
     'In many countries, people say that the only effective way to learn a foreign language is to live in a country where it is spoken.'),
]

# Discuss both views: two opposing views in the statement, then DISCUSS.
DISCUSSION = [
    ('Large or Small Science Projects',
     'Some people think governments should put their science budget into a few large projects, such as space telescopes, while others believe it is better to spread the money across many smaller projects.'),
    ('Experiments or Theory in Science Lessons',
     'Some people believe that science is best taught in schools through practical experiments, while others think students first need a solid understanding of theory.'),
    ('Teachers as Friends',
     'Some people think teachers should try to be friends with their students, while others believe they should keep a more formal relationship.'),
    ('Memorising Facts',
     'Some people believe students should learn important facts, such as dates and formulas, by heart. Others think it is more important for students to understand ideas and know where to find information.'),
    ('Local or International News',
     'Some people think it is more important to follow the news in their local area, while others believe international news matters more.'),
    ('Large Companies or Small Businesses',
     'Some people prefer to work for a large company, while others believe a small business offers a better working life.'),
    ('Building Upwards or Outwards',
     'Some people think cities should grow by putting up taller buildings in the centre, while others believe new homes should be built on land around the edge of the city.'),
    ('Tourism and Local Traditions',
     'Some people believe that tourism helps to keep local traditions alive, while others think it turns them into shows put on for visitors.'),
    ('Competition or Cooperation at Work',
     'Some people think competition between colleagues makes everyone work harder, while others believe that cooperation produces better results.'),
    ('Saving or Spending When Young',
     'Some people think young adults should save as much of their income as they can, while others believe they should spend it on enjoying themselves while they are young.'),
    ('Novels or Films',
     'Some people believe that reading a novel is more rewarding than watching a film of the same story, while others think films can be just as valuable.'),
    ('Traditional or Modern Ways of Life',
     'Some people think countries should try to protect their traditional ways of life, while others believe it is better to accept modern ways of living.'),
    ('Technology and Everyday Life',
     'Many people believe that modern technology has made everyday life simpler. Others, however, think it has made life more complicated and stressful.'),
    ('Relaxing or Active Holidays',
     'Some people like to spend their holidays relaxing, while others prefer holidays that are full of new activities and experiences.'),
    ('Electric Cars and Pollution',
     'Some people think electric cars will solve the problem of pollution from traffic, while others believe the only answer is for people to use cars much less.'),
    ('Difficult Subjects in Children\'s Books',
     'Some people think stories for young children should present only a happy and safe world, while others believe they should also deal with difficult subjects.'),
    ('Modern Art',
     'Some people think modern art, such as abstract painting, is as valuable as traditional art, while others believe it requires little skill.'),
    ('Beauty or Function in Buildings',
     'Some people believe that new buildings should be designed to look attractive, while others think it only matters that they are practical and comfortable.'),
    ('Television as Education',
     'Television is seen by some people as a useful way to learn about the world. Others believe it mainly wastes people\'s time.'),
    ('Preventing or Adapting to Climate Change',
     'Some people think governments should concentrate on preventing climate change, while others believe it is more important to prepare for the changes that are already happening.'),
    ('Gyms or the Outdoors',
     'Some people think exercising in a gym is the best way to keep fit, while others believe outdoor activities such as walking and cycling are better.'),
    ('The School Leaving Age',
     'Some people believe all young people should stay in full-time education until the age of 18, while others think those who want to start work at 16 should be free to do so.'),
    ('Who Chooses What Students Learn',
     'Some people think teachers should decide what students learn in class, while others believe students should be allowed to choose topics that interest them.'),
    ('Interviews or Practical Tests',
     'Some people believe that job interviews are the best way to choose new employees, while others think practical tests of skills are more reliable.'),
    ('Promoting From Within',
     'Some people think companies should fill senior positions by promoting their own staff, while others believe it is better to bring in managers from outside.'),
    ('Living Near Parents',
     'Some people think adult children should live close to their parents, while others believe they should move wherever they can find the best opportunities.'),
    ('International Films and Music',
     'Some people think the spread of international films and music is making cultures around the world more alike, while others believe it helps people from different countries understand each other.'),
    ('Rural Bus Services',
     'Some people think governments should pay for bus services in rural areas even when few people use them, while others see this as a waste of public money.'),
    ('Public Money for Festivals',
     'Many towns spend public money on festivals and celebrations. Some people think this is wasteful, while others believe such events bring communities together.'),
    ('Parks or Housing',
     'Some people believe empty land in cities should be used for parks and other green spaces, while others think it should be used to build much-needed homes.'),
    ('Watching Sport Live',
     'Some people think watching a match at the stadium is a far better experience than watching it on television, while others prefer to watch sport at home.'),
    ('Local Players or Stars From Abroad',
     'Some people think professional sports teams should be made up mainly of local players, while others believe clubs should be free to sign the best players from anywhere in the world.'),
    ('Recycling or Buying Less',
     'Some people think recycling is the best way to reduce the amount of waste we produce, while others believe people simply need to buy fewer things.'),
    ('The Price of Food',
     'Some people think food should be as cheap as possible so that everyone can afford it, while others believe consumers should pay more so that farmers earn a fair income.'),
    ('Separate Schools for Gifted Children',
     'Some people think very able children should be taught in special schools, while others believe they should stay in ordinary schools with children of their own age.'),
    ('Using Free Time',
     'Some people think free time should be spent on activities that develop useful skills, while others believe it should be used simply to relax.'),
    ('Obeying or Questioning Adults',
     'Some people think children should be taught to obey their parents and teachers, while others believe they should be encouraged to question what adults tell them.'),
    ('Low-Cost Airlines',
     'Cheap flights have made air travel possible for millions of people. Some think this has given ordinary people valuable opportunities, while others believe the damage to the environment is too great.'),
    ('Mental Arithmetic',
     'Some people believe children should still learn to do calculations in their heads, while others think this is unnecessary now that calculators and phones can do the work.'),
    ('Punishing Minor Offences',
     'Some people believe that punishing minor offences such as dropping litter strictly helps to prevent more serious crime, while others think police time should be spent on serious crime only.'),
    ('Journalists and Their Opinions',
     'Some people think journalists should report the news without giving their own opinions, while others believe it is acceptable for them to express their views.'),
    ('Learning Through Play',
     'Some people think children should start learning to read and write at the age of four, while others believe that until the age of six or seven they should learn mainly through play.'),
    ('The Environment or Jobs',
     'Some people think protecting the natural environment should come before creating jobs, while others believe economic growth must come first.'),
    ('Live or Recorded Music',
     'Some people believe that listening to music played live is a completely different experience from listening to recordings, while others think recordings are just as enjoyable.'),
    ('Planning the Future',
     'Some people like to plan every part of their future carefully, while others prefer to take opportunities as they come.'),
    ('Honesty and Small Lies',
     'Some people think it is always best to tell the truth, while others believe small lies are sometimes necessary to avoid hurting people\'s feelings.'),
    ('First Impressions',
     'Some people believe that our first impressions of a person are usually accurate, while others think they are often misleading.'),
    ('Starting a Career in a Big City',
     'Some people think young adults should move to a big city to start their careers, while others believe there are more advantages in staying in their home town.'),
    ('Tour Groups or Independent Travel',
     'Some people prefer to travel abroad with an organised tour group, while others believe travelling independently is the only way to get to know a country.'),
    ('Quality or Cheap Goods',
     'Some people think it is better to pay more for high-quality goods that last a long time, while others prefer to buy cheaper goods and replace them more often.'),
]

# Advantages / disadvantages: a trend, then a weighing question.
ADVANTAGES = [
    ('Automated Customer Service',
     'Many companies now use automated online chat, rather than human staff, to answer customers\' questions.', OUTWEIGH),
    ('University Courses Taught in English',
     'In many countries where English is not the main language, universities are teaching more of their courses in English.', OUTWEIGH),
    ('High-Speed Railways',
     'Many countries are building high-speed railway lines to connect their major cities.', BENEFITS),
    ('Taking Exams at Home',
     'Some universities now allow students to take their exams online at home rather than in an exam hall.', OUTWEIGH),
    ('Car-Sharing Schemes',
     'In many cities, people are joining car-sharing schemes, which let them hire a car by the hour, instead of owning one.', BOTH_SIDES),
    ('Joining the Family Business',
     'Some young people choose to work in their parents\' business rather than look for a job elsewhere.', BOTH_SIDES),
    ('Hiring Rather Than Buying',
     'Instead of buying items they rarely use, such as tools or clothes for special occasions, more people are now renting or borrowing them.', OUTWEIGH),
    ('International Schools',
     'More parents are sending their children to international schools that teach a foreign curriculum, often in a foreign language.', BOTH_SIDES),
    ('Digital Identity Documents',
     'Some countries are replacing paper identity cards and other official documents with digital versions stored on mobile phones.', OUTWEIGH),
    ('Lessons Matched to Each Student',
     'Some schools now use software that adjusts lessons to each student\'s level, instead of teaching the whole class the same material.', BENEFITS),
    ('Foreign Owners of Sports Clubs',
     'Many professional football clubs are now owned by wealthy investors from other countries.', OUTWEIGH),
    ('Specialising in One Sport Early',
     'Some children now train in a single sport from a very young age in the hope of becoming professional athletes.', BOTH_SIDES),
    ('Film Location Tourism',
     'Places where popular films and television series were made are now attracting large numbers of tourists.', OUTWEIGH),
    ('All-Inclusive Holidays',
     'All-inclusive holidays, where meals, drinks and activities are included in the price of the hotel, are becoming more popular.', OUTWEIGH),
    ('Paperless Offices',
     'Many offices are giving up paper and keeping all their documents in electronic form.', BOTH_SIDES),
    ('Houses Built in Factories',
     'In some countries, more new houses are being built in sections in factories and then put together on site.', BENEFITS),
    ('Charging Drivers to Enter City Centres',
     'Some cities charge drivers a daily fee to enter the city centre by car.', OUTWEIGH),
    ('Public Transport All Night',
     'Some large cities now run buses and trains throughout the night.', OUTWEIGH),
    ('Nurses and Pharmacists Taking On Doctors\' Work',
     'In some countries, nurses and pharmacists are now doing work that used to be done only by doctors, such as prescribing medicines.', OUTWEIGH),
    ('Mixed-Age Classes',
     'Some primary schools teach children of different ages together in the same class.', BOTH_SIDES),
    ('Recorded Lectures',
     'Many universities now record their lectures and put them online, so that students can watch them whenever they like.', OUTWEIGH),
    ('Monitoring Staff Computers',
     'Many employers now use software to check what their staff are doing on their computers during working hours.', OUTWEIGH),
    ('Job Sharing',
     'Some employers allow two people to share one full-time job, each working part of the week.', BOTH_SIDES),
    ('Pay Linked to Performance',
     'More companies now pay their staff partly according to how well they perform, rather than a fixed salary.', OUTWEIGH),
    ('Face Recognition Technology',
     'Face recognition technology is increasingly used to open mobile phones, pay for goods and pass through airport security.', BENEFITS),
    ('Virtual Visits',
     'Virtual reality now allows people to visit museums and famous places around the world without leaving home.', OUTWEIGH),
    ('Free Newspapers',
     'In many cities, newspapers are given away free and are paid for entirely by advertising.', BOTH_SIDES),
    ('Ordinary People Reporting the News',
     'Ordinary people with mobile phones are now often the first to report news events, before professional journalists arrive.', OUTWEIGH),
    ('Long Journeys by Train',
     'Some travellers are choosing to make long international journeys by train instead of flying.', OUTWEIGH),
    ('Booking Holidays Online',
     'Most people now book their holidays online instead of using a travel agent.', BOTH_SIDES),
    ('Loyalty Cards',
     'Many shops offer loyalty cards that give customers discounts in return for information about what they buy.', OUTWEIGH),
    ('Retirement Villages',
     'In some countries, more older people are choosing to live in retirement villages, among other people of their own age.', OUTWEIGH),
    ('Public Services Only Online',
     'Many governments now provide services such as tax returns and licence applications only online.', OUTWEIGH),
    ('Childcare at the Workplace',
     'Some large companies now provide childcare for their employees\' children at the workplace.', OUTWEIGH),
    ('Exercise Classes Online',
     'Instead of going to a gym, many people now follow exercise classes online at home.', BOTH_SIDES),
    ('Working Holidays Abroad',
     'Some countries offer young people visas that allow them to live and work there for a year or two.', OUTWEIGH),
    ('Tourists on Farms',
     'Many farmers now earn extra money by opening their farms to tourists.', BENEFITS),
    ('Moving Government Jobs Out of the Capital',
     'Some governments are moving public offices and jobs out of the capital city to smaller towns.', OUTWEIGH),
    ('Advertisements Chosen for Each User',
     'Advertisements on the internet are increasingly chosen to match each user\'s interests, based on what they search for and buy.', OUTWEIGH),
    ('Short-Term Contracts',
     'Many companies now employ staff on short-term contracts rather than offering them permanent jobs.', OUTWEIGH),
    ('Turning Offices Into Homes',
     'In many cities, old office buildings and factories are being turned into flats.', BENEFITS),
    ('Large Dams',
     'Many countries are building large dams across rivers to produce electricity and store water.', BOTH_SIDES),
    ('Regional Hospitals',
     'In many countries, small local hospitals are being closed and replaced by large hospitals that serve a whole region.', OUTWEIGH),
    ('Closing Village Schools',
     'In many rural areas, small village schools are closing and their pupils are being sent to larger schools in nearby towns.', OUTWEIGH),
    ('Bank Cards for Children',
     'Many banks now offer bank cards to children as young as eight, which their parents can control through an app.', OUTWEIGH),
    ('Learning Holidays',
     'Some people now spend their holidays on courses, learning skills such as cooking, painting or a new language.', BOTH_SIDES),
    ('School Buses',
     'In some countries, almost all children travel to school on buses provided by the school or the local council.', OUTWEIGH),
    ('Summer Camps',
     'Many parents send their children to residential summer camps during the school holidays.', BOTH_SIDES),
    ('Online Encyclopaedias',
     'Many people now use free online encyclopaedias written by volunteers instead of printed reference books.', OUTWEIGH),
    ('Paid Time Off for Volunteering',
     'Some companies give their staff paid time off to do voluntary work in the local community.', BENEFITS),
]

# Problem / solution: a situation, then problems (or why it is a problem) and solutions.
PROBLEM_SOLUTION = [
    ('Light Pollution',
     'In many towns and cities, bright artificial lighting at night means that people can no longer see the stars.', CAUSE_SOLVE),
    ('Keeping Experienced Nurses',
     'Many hospitals find it hard to keep experienced nurses, who leave for better-paid work or other careers.', WHY_SOLVE),
    ('Bullying at Work',
     'In many workplaces, some employees are bullied or treated unfairly by their managers or colleagues.', MEASURES),
    ('False Information Online',
     'False information spreads quickly on social media and is often believed by large numbers of people.', CAUSE_SOLVE),
    ('Constantly Checking Phones',
     'Many people find it hard to stop checking their mobile phones, even at work or while they are with friends and family.', CAUSE_SOLVE),
    ('Overfishing',
     'In many parts of the world, fish are being caught faster than they can breed, and some species are becoming rare.', MEASURES),
    ('Villages Losing Services',
     'Many villages have lost their shops, post offices and regular bus services.', CAUSE_SOLVE),
    ('Older Jobseekers',
     'In many countries, people over the age of 50 find it very difficult to get a new job after losing their previous one.', MEASURES),
    ('Lack of Parking',
     'Many town centres do not have enough parking spaces, and drivers spend a long time looking for somewhere to leave their cars.', CAUSE_SOLVE),
    ('Too Much Packaging',
     'Many products sold in shops are wrapped in far more packaging than they need.', WHY_SOLVE),
    ('Polluted Rivers',
     'Many rivers are polluted by waste from farms, factories and homes.', MEASURES),
    ('Children Missing School',
     'In many countries, a growing number of children are regularly absent from school.', CAUSE_SOLVE),
    ('Poor Behaviour in Class',
     'Teachers in many schools say that poor behaviour in class makes it difficult for them to teach.', MEASURES),
    ('Badly Behaved Tourists',
     'Some tourists behave badly in the places they visit, for example by making too much noise, leaving litter or ignoring local customs.', CAUSE_SOLVE),
    ('Historic Buildings in Poor Condition',
     'Many historic buildings are falling into disrepair because there is not enough money to look after them.', WHY_SOLVE),
    ('Stolen Personal Data',
     'Personal information held by companies and public organisations is often stolen by criminals who break into their computer systems.', MEASURES),
    ('Children\'s Teeth',
     'In many countries, large numbers of children have serious problems with their teeth.', CAUSE_SOLVE),
    ('Caring for an Ageing Population',
     'In many countries, the number of older people who need care is growing faster than the number of people available to look after them.', MEASURES),
    ('Hearing Damage From Headphones',
     'Many young people are damaging their hearing by listening to loud music through headphones.', WHY_SOLVE),
    ('Crowded Rush-Hour Trains',
     'In many cities, trains and buses are extremely crowded at the busiest times of the day.', CAUSE_SOLVE),
    ('Not Knowing Where Food Comes From',
     'Many children who grow up in cities do not know how the food they eat is grown or produced.', WHY_SOLVE),
    ('Teenage Girls Giving Up Sport',
     'In many countries, girls stop taking part in sport during their teenage years at a much higher rate than boys.', MEASURES),
    ('Expensive Tickets for Sport',
     'The price of tickets for professional sports matches has risen so much that many fans can no longer afford to go.', CAUSE_SOLVE),
    ('Young Employees Leaving Quickly',
     'Many companies find that young employees leave after only a short time in the job.', MEASURES),
    ('Coastal Erosion',
     'In some coastal areas, the sea is washing away the land, putting homes and roads at risk.', MEASURES),
    ('Starting School With Poor Speaking Skills',
     'Many children start primary school without the speaking and listening skills they need in order to learn.', CAUSE_SOLVE),
    ('Education in Remote Areas',
     'Children who live in remote rural areas often have fewer educational opportunities than those who live in cities.', MEASURES),
    ('Using Phones While Driving',
     'Many drivers use their mobile phones while they are driving, even though this is against the law.', WHY_SOLVE),
    ('Unwanted Calls and Messages',
     'Many people receive large numbers of unwanted phone calls and messages from companies trying to sell them something.', CAUSE_SOLVE),
    ('Spending Money in Online Games',
     'Many children spend large amounts of their parents\' money on extra items inside online games.', MEASURES),
    ('Small Theatres and Music Venues Closing',
     'Many small theatres and music venues are closing because they cannot cover their costs.', CAUSE_SOLVE),
    ('Poor-Quality Rented Homes',
     'Many people who rent their homes live in poor conditions, for example in flats that are damp or difficult to heat.', MEASURES),
    ('Too Many Meetings',
     'Many office workers say they spend so much time in meetings that they cannot get their real work done.', CAUSE_SOLVE),
    ('Weak Foreign Language Skills',
     'Many school leavers cannot hold a simple conversation in a foreign language, even after years of lessons.', WHY_SOLVE),
    ('Roads in Poor Repair',
     'In many areas, roads and bridges are in poor condition because there is not enough money to repair them.', CAUSE_SOLVE),
    ('Nowhere for Teenagers to Go',
     'In many towns, there are very few places where teenagers can meet and spend their free time.', CAUSE_SOLVE),
    ('Graduates Lacking Practical Skills',
     'Employers often complain that university graduates do not have the practical skills needed in the workplace.', MEASURES),
    ('Unhappiness at Work',
     'Surveys in many countries show that a large number of people are unhappy in their jobs.', CAUSE_SOLVE),
    ('Closing Sports Centres and Pools',
     'Many public swimming pools and sports centres are closing because local councils cannot afford to keep them open.', MEASURES),
    ('The Cost of Healthy Food',
     'In many countries, fresh fruit and vegetables cost more than unhealthy processed food.', WHY_SOLVE),
    ('Avoiding the Doctor',
     'Many people avoid going to the doctor until a health problem has become serious.', CAUSE_SOLVE),
    ('Young Adults Lacking Life Skills',
     'Many young adults leave home without knowing how to do basic household tasks such as cooking, cleaning or simple repairs.', MEASURES),
    ('Delivery Vans in City Streets',
     'The growth of online shopping has filled city streets with delivery vans.', CAUSE_SOLVE),
    ('Musicians and Streaming Income',
     'Most musicians earn very little money when their songs are played on streaming services.', WHY_SOLVE),
    ('Heat Lost From Homes',
     'Many homes are poorly insulated, so much of the energy used to heat them is wasted.', MEASURES),
    ('Rudeness to Service Staff',
     'Staff in shops, restaurants and call centres say that customers are increasingly rude to them.', CAUSE_SOLVE),
    ('Going to Work When Ill',
     'Many employees continue to go to work when they are ill because they are worried about losing pay or falling behind.', MEASURES),
    ('University Dropouts',
     'Many undergraduate students decide to abandon their degree programmes during their first year of study.', MEASURES),
    ('Shortage of Blood Donors',
     'Hospitals in many countries regularly run short of blood because too few people donate.', MEASURES),
    ('Shortage of Public Toilets',
     'Many towns and cities do not have enough public toilets, and some of those that existed have been closed.', CAUSE_SOLVE),
]

# Cause / effect: a trend, then its causes (or reasons) and its effects.
CAUSE_EFFECT = [
    ('Talent Shows on Television',
     'Television talent competitions, in which members of the public sing or dance to win a prize, attract huge audiences in many countries.', WHY_EFFECTS),
    ('Giving Up Meat and Dairy',
     'The number of people who choose not to eat meat or any other animal products has risen sharply in recent years.', REASONS_EFFECTS),
    ('Amateur Marathon Runners',
     'Far more ordinary people now take part in marathons and other long-distance races than in the past.', REASONS_EFFECTS),
    ('Women in Paid Work',
     'In many countries, a much larger proportion of women work outside the home than fifty years ago.', CAUSES_EFFECTS),
    ('Snacking Instead of Meals',
     'Many people now eat snacks throughout the day instead of sitting down to regular meals.', CAUSES_EFFECTS),
    ('The Spread of Coffee Shops',
     'The number of coffee shops in town centres has grown rapidly in many countries.', REASONS_EFFECTS),
    ('Fewer Cinema Visits',
     'In many countries, fewer people go to the cinema than they did twenty years ago.', CAUSES_EFFECTS),
    ('Young Gardeners',
     'Gardening, once seen mainly as a hobby for older people, has become popular with young adults.', REASONS_EFFECTS),
    ('Camping Holidays',
     'Camping and other outdoor holidays have become more popular in many countries.', REASONS_EFFECTS),
    ('Business Studies at University',
     'Business studies has become one of the most popular university subjects in many countries.', CAUSES_EFFECTS),
    ('Grandparents as Childcarers',
     'In many families, grandparents now look after their grandchildren regularly while the parents are at work.', CAUSES_EFFECTS),
    ('The Growth of Air Travel',
     'The number of people travelling by air has grown enormously over the past thirty years.', CAUSES_EFFECTS),
    ('Taking Vitamin Supplements',
     'More and more people take vitamin pills and other supplements every day.', WHY_EFFECTS),
    ('From Factories to Services',
     'In many developed countries, far fewer people work in factories than in the past, and most now work in services such as retail, finance and tourism.', CAUSES_EFFECTS),
    ('Crowds at Women\'s Football',
     'Women\'s football has attracted much larger crowds and television audiences in recent years.', REASONS_EFFECTS),
    ('Walking for Pleasure',
     'Walking in the countryside has become one of the most popular leisure activities in many countries.', WHY_EFFECTS),
    ('Discount Supermarkets',
     'Discount supermarkets, which sell a limited range of goods at low prices, have become much more popular.', REASONS_EFFECTS),
    ('Few Male Primary Teachers',
     'In many countries, very few primary school teachers are men.', CAUSES_EFFECTS),
    ('Listening to Audiobooks',
     'More people are listening to audiobooks instead of reading printed books.', REASONS_EFFECTS),
    ('Music and Television From Asia',
     'Music and television programmes from Asian countries such as South Korea have become popular around the world.', WHY_EFFECTS),
    ('Working at Weekends',
     'More people now work at weekends than in the past.', CAUSES_EFFECTS),
    ('Adults Sleeping Less',
     'Adults in many countries sleep fewer hours each night than previous generations did.', CAUSES_EFFECTS),
    ('Buying a First Home Later',
     'People in many countries are buying their first home at a much later age than their parents did.', CAUSES_EFFECTS),
    ('The Growth of Part-Time Jobs',
     'Part-time jobs make up a growing share of employment in many countries.', REASONS_EFFECTS),
    ('Interest in Healthy Eating',
     'Many people are paying more attention than ever to what they eat and how healthy it is.', REASONS_EFFECTS),
    ('Fewer Smokers',
     'The number of people who smoke has fallen sharply in many countries.', CAUSES_EFFECTS),
    ('Starting Nursery Early',
     'More children than ever now attend a nursery or day care centre before they start school.', CAUSES_EFFECTS),
    ('Older People Taking Up Sport',
     'More and more older people are taking up sports and joining exercise classes.', REASONS_EFFECTS),
    ('Air Conditioning',
     'The use of air conditioning in homes and offices has increased greatly in many countries.', CAUSES_EFFECTS),
    ('Buying Directly From Abroad',
     'More and more people buy goods online directly from sellers in other countries.', REASONS_EFFECTS),
    ('Doing Your Own Home Improvements',
     'More homeowners are doing their own building and decorating work instead of paying professionals.', WHY_EFFECTS),
    ('Photo Filters',
     'Many people now use apps to change their appearance in photographs before sharing them online.', WHY_EFFECTS),
    ('Sales of Electric Cars',
     'Sales of electric cars have risen rapidly in many countries.', CAUSES_EFFECTS),
    ('Cooking Programmes',
     'Cooking programmes are now among the most popular shows on television.', WHY_EFFECTS),
    ('Book Clubs',
     'Book clubs, where people meet to discuss a book they have all read, have become popular in many places.', REASONS_EFFECTS),
    ('Wildlife Holidays',
     'More and more tourists travel long distances to see wild animals such as whales, gorillas and bears in their natural surroundings.', REASONS_EFFECTS),
    ('Young People and the Environment',
     'Young people today appear to be much more concerned about the environment than their parents were at the same age.', CAUSES_EFFECTS),
    ('Keeping Devices for Longer',
     'People are keeping their mobile phones and computers for longer before replacing them.', REASONS_EFFECTS),
    ('Owning Fewer Possessions',
     'Some people are choosing to own as few possessions as possible.', WHY_EFFECTS),
    ('Travelling for Medical Treatment',
     'Growing numbers of people travel to other countries for medical or dental treatment.', CAUSES_EFFECTS),
    ('Living in City Centres',
     'More people are choosing to live in city centres rather than in the suburbs.', REASONS_EFFECTS),
    ('Sportswear as Everyday Clothing',
     'Sports clothing such as trainers and tracksuits is now worn by many people as everyday clothing.', WHY_EFFECTS),
    ('Sports Fans Travelling Abroad',
     'More sports fans now travel abroad to watch their teams play.', REASONS_EFFECTS),
    ('Watching Others Play Video Games',
     'Millions of people now spend their free time watching other people play video games online.', WHY_EFFECTS),
    ('Starting Work Later',
     'Young people today tend to start full-time work several years later than their parents did.', CAUSES_EFFECTS),
    ('People Growing Taller',
     'People in many countries are taller on average than they were a hundred years ago.', CAUSES_EFFECTS),
    ('Adult Dance Classes',
     'Dance classes for adults, from ballroom to salsa, have become increasingly popular.', REASONS_EFFECTS),
    ('Television Series Over Films',
     'Many viewers now prefer long television series to feature films.', REASONS_EFFECTS),
    ('Choosing Work That Helps Society',
     'More young people say they want to work for organisations that do something useful for society, even if the pay is lower.', CAUSES_EFFECTS),
    ('Older People Travelling Abroad',
     'Older people are travelling abroad on holiday far more than previous generations did.', CAUSES_EFFECTS),
]

# Two-part (direct) questions: a situation, then two questions answered in turn.
TWO_PART = [
    ('Paying for Famous Brands',
     'Many teenagers are willing to pay high prices for clothes made by famous brands.',
     'Why do they do this? Is this a positive or negative development?'),
    ('Parents Choosing Careers',
     'Many parents have a clear idea of the career they want their children to follow.',
     'Why do parents feel this way? Should children be free to choose their own careers?'),
    ('Skills Passed Down in Families',
     'In the past, older family members taught younger ones practical skills such as cooking, sewing and making repairs, but this happens much less often today.',
     'Why has this changed? Should schools teach these skills instead?'),
    ('First Names at Work',
     'In many workplaces, employees now call their managers by their first names.',
     'Why has this change happened? Is it a positive or negative development?'),
    ('Celebrities Giving Their Views',
     'Famous actors, singers and sports stars often give their opinions on subjects such as health and the environment.',
     'Why do people listen to them? Should celebrities use their fame in this way?'),
    ('The Most Important Invention',
     'Many inventions of the last hundred years have changed the way people live.',
     'Which invention do you think has had the greatest effect on everyday life? Has its effect been entirely positive?'),
    ('Measuring a Country\'s Success',
     'Governments often judge a country\'s success by how fast its economy is growing.',
     'Is this the best way to measure success? What other measures could be used?'),
    ('Salaries of Top Sports Players',
     'Top professional sports players earn far more money than people in most other jobs.',
     'Why are they paid so much? Is this fair?'),
    ('Spending on Gifts',
     'In many cultures, people spend large amounts of money on gifts for festivals and birthdays.',
     'Why do people spend so much? Has giving gifts lost its meaning?'),
    ('Pets for Children',
     'Many parents buy a pet for their children.',
     'Why do they do this? What can children learn from looking after an animal?'),
    ('A Talent for Languages',
     'Some people find it easy to learn foreign languages, while others find it very difficult.',
     'Why is this? What can help people who find languages difficult?'),
    ('Remembering Childhood',
     'Many adults remember their childhood as the happiest time of their lives.',
     'Why is this? Is childhood today happier than it was in the past?'),
    ('Asking the Internet for Advice',
     'In the past, young people usually asked older family members for advice, but today many search for it on the internet.',
     'Why has this changed? Is this a positive or negative development?'),
    ('Buildings by Famous Architects',
     'Some cities spend large amounts of money on unusual buildings designed by famous architects.',
     'Why do they do this? Is it a good use of public money?'),
    ('Statues in Public Places',
     'Many towns and cities have statues of well-known people from their history.',
     'Are such statues still important today? Whose achievements should be remembered in this way?'),
    ('Buying Souvenirs',
     'Most tourists buy souvenirs to take home from the places they visit.',
     'Why do they buy them? Does the trade in souvenirs benefit local people?'),
    ('Superstitions',
     'In many cultures, people still follow superstitions, such as believing that certain numbers bring good or bad luck.',
     'Why do these beliefs continue? Do they do any harm?'),
    ('Science Fiction Becoming Reality',
     'Many things that first appeared in science fiction stories, such as video calls and robots, are now part of everyday life.',
     'Why do you think writers were able to imagine these things? What changes do you expect to see in the next fifty years?'),
    ('Celebrating Sporting Success',
     'When a national team wins an international competition, people all over the country celebrate.',
     'Why do people feel so strongly about their national team? Does sporting success bring real benefits to a country?'),
    ('Living Far From Home',
     'Many people now live hundreds of kilometres away from the town where they grew up.',
     'Why is this? How does it affect family life?'),
    ('Qualities of a Good Teacher',
     'Most people can remember at least one teacher who had a strong influence on them.',
     'What qualities make a good teacher? Can these qualities be learned?'),
    ('The Value of Boredom',
     'Many children today are rarely bored, because they always have a screen to entertain them.',
     'Is it useful for children to experience boredom? How should parents respond when their children say they are bored?'),
    ('Nature Documentaries',
     'Television documentaries about nature and wildlife attract very large audiences.',
     'Why are they so popular? Do they help to protect the natural world?'),
    ('Food and National Culture',
     'Food is often described as an important part of a country\'s culture.',
     'Why is food so closely connected to culture? Is the traditional food of your country changing?'),
    ('Cities in Fifty Years',
     'Cities are likely to change a great deal over the next fifty years.',
     'What changes do you expect to see? Will cities be better places to live?'),
    ('Being on Time',
     'In some cultures, arriving late for a meeting or a social event is considered very rude, while in others it is quite normal.',
     'Why do attitudes to time differ? How important is punctuality at work?'),
    ('Borrowing From Friends and Family',
     'Many people borrow money from friends or relatives rather than from a bank.',
     'Why do people prefer to do this? What problems can it cause?'),
    ('Friends at Work',
     'Many people say that some of their closest friends are people they work with.',
     'Why is this? Is it wise to become close friends with colleagues?'),
    ('Why Students Work Hard',
     'Some students work hard because they enjoy learning, while others do so mainly to get good marks.',
     'Which kind of motivation is more effective? How can teachers help students to enjoy learning?'),
    ('Speaking to Strangers',
     'In many cities, people rarely speak to strangers, even when they sit next to them on public transport.',
     'Why is this? Is it a problem?'),
    ('The Generation Gap',
     'People often say that there is a large gap between the attitudes of young people and those of older people.',
     'Why does this gap exist? How can the two generations understand each other better?'),
    ('Respect for Older People',
     'In some societies, older people are highly respected, while in others they are often ignored.',
     'Why is there this difference? How can societies make better use of older people\'s experience?'),
    ('Unvisited Local Attractions',
     'Many people have never visited the famous tourist attractions in their own city or region.',
     'Why is this? Should they be encouraged to visit them?'),
    ('Using School Maths',
     'Many adults say they rarely use the mathematics they learned at school.',
     'Why is this? Should maths lessons concentrate more on the skills people need in everyday life?'),
    ('Printed Photographs',
     'Most people now keep their photographs on phones and computers rather than printing them.',
     'Why is this? Is anything lost as a result?'),
    ('Parents Helping With Homework',
     'Some parents help their children a great deal with their homework, or even do it for them.',
     'Why do they do this? How much should parents help?'),
    ('The Return of Old Technology',
     'Some older technologies, such as vinyl records and film cameras, have become popular again.',
     'Why is this happening? Will these technologies remain popular?'),
    ('Children in Family Decisions',
     'In some families, children take part in important decisions, such as where to go on holiday or whether to move house.',
     'Should children be involved in family decisions? Which decisions should parents make alone?'),
    ('Losing Touch With School Friends',
     'Many people lose touch with their school friends after they leave school.',
     'Why does this happen? Is it important to keep old friendships?'),
    ('Unusual Pets',
     'Some people keep unusual animals such as snakes, spiders or lizards as pets.',
     'Why do people choose these animals? Should keeping them be allowed?'),
    ('Extended Family Gatherings',
     'In many countries, members of extended families no longer meet regularly, except at weddings and major festivals.',
     'Why is this? Does it matter?'),
    ('Complaining About Poor Service',
     'Some people complain whenever they receive poor service, while others prefer to say nothing.',
     'Why do some people not complain? Is it important to complain when service is poor?'),
    ('Street Markets',
     'Outdoor markets remain popular in many towns, even though supermarkets sell many of the same goods.',
     'Why do people still shop at them? Should local councils do more to support them?'),
    ('Regional Accents',
     'In many countries, regional accents are becoming less noticeable, especially among young people.',
     'Why is this happening? Is it a loss?'),
    ('Comics and Graphic Novels',
     'Many children prefer reading comics and graphic novels to reading traditional books.',
     'Why is this? Should parents encourage it?'),
    ('Respected Professions',
     'In most countries, some jobs, such as doctor or lawyer, are more highly respected than others.',
     'Why is this? Should all jobs be respected equally?'),
    ('Doing Several Things at Once',
     'Many people try to do several things at the same time, such as checking messages during meetings or working with the television on.',
     'Why do people do this? Is it an effective way to work?'),
    ('Good Neighbours',
     'Some people get on very well with their neighbours, while others hardly know them.',
     'What makes a good neighbour? How important is it to have a good relationship with the people who live nearby?'),
    ('Watching Films Again',
     'Many people enjoy watching the same films or reading the same books many times.',
     'Why do people do this? Is it better to try new things?'),
    ('The Age for Leaving Home',
     'In some countries, young people usually leave their parents\' home at around 18, while in others they stay until they marry.',
     'Why is there this difference? What is the best age to leave home?'),
]
