"""IELTS Writing Task 2 questions for the five essay types beyond Opinion.

Original Prepyo practice content written to the public IELTS Task 2 formats.
None of it is official, recalled or copied test material. Each entry is
(title, statement, question); generate_ielts_task2_types.py appends the shared
instruction line and checks counts and uniqueness before writing SQL.

The question wording follows the forms IELTS itself uses for each type:
  Discuss both views  "Discuss both these views and give your own opinion."
  Advantages          "Do the advantages of this outweigh the disadvantages?"
                      or "What are the advantages and disadvantages of this?"
  Problem / Solution  "What problems does this cause? What solutions can you suggest?"
  Cause / Effect      "What are the causes of this? What effects does it have?"
  Two-part            two direct questions, answered in turn
"""

DISCUSS = 'Discuss both these views and give your own opinion.'

# Discuss both views: two opposing views in the statement, then DISCUSS.
DISCUSSION = [
    ('Classroom or Online Lessons',
     'Some people believe that secondary school students learn best in a physical classroom, while others think that online lessons taken at home can be just as effective.'),
    ('Elite Athletes or Public Sport',
     'Some people think governments should spend money training elite athletes for international competitions, while others believe the money would be better spent on sports facilities for ordinary people.'),
    ('Earning Pocket Money',
     'Some parents give their children pocket money every week to teach them how to manage money, while others believe children should earn money by helping with jobs around the house.'),
    ('Hosting International Sporting Events',
     'Some people argue that hosting a major international sporting event brings long-term benefits to a country, while others believe the costs are far greater than the benefits.'),
    ('Specialising at University',
     'Some people believe it is better for university students to specialise in one subject, while others think they should study a wide range of subjects.'),
    ('The Future of Printed Newspapers',
     'Some people think printed newspapers will soon disappear completely, while others believe they will continue to play an important role in society.'),
    ('Growing Up in the City or Countryside',
     'Some people think children should grow up in the countryside, while others believe a large city offers them a better start in life.'),
    ('Letting Children Fail',
     'Some people believe children should be allowed to make their own mistakes, while others think parents should protect them from failure as much as possible.'),
    ('Genes or Upbringing',
     'Some people believe that a person\'s character is mainly determined by the genes they inherit, while others think it is shaped mostly by upbringing and experience.'),
    ('Improving Road Safety',
     'Some people think the best way to reduce road accidents is to raise the minimum age for driving, while others believe better driver training would be more effective.'),
    ('The Role of Advertising',
     'Some people think advertising helps consumers make informed choices, while others believe its main effect is to persuade people to buy things they do not need.'),
    ('Computers Replacing Teachers',
     'Some people believe that computers will one day replace teachers in the classroom, while others think teachers will always be essential.'),
    ('What Museums Are For',
     'Some people think museums should focus on entertaining their visitors, while others believe their main purpose should be to educate.'),
    ('Saving for Retirement',
     'Some people think individuals should be responsible for saving money for their own old age, while others believe the state should provide a pension for everyone.'),
    ('Aid to Poorer Countries',
     'Some people believe wealthy countries should give financial aid to poorer countries, while others think such aid often does more harm than good.'),
    ('Team or Individual Sports',
     'Some people believe children benefit most from playing team sports, while others think individual activities such as swimming or running are more valuable.'),
    ('Privacy for Famous People',
     'Some people think famous people have the same right to privacy as anyone else, while others believe the public has a right to know about their private lives.'),
    ('Staying With One Employer',
     'Some people prefer to work for the same organisation for their whole career, while others think it is better to change employers every few years.'),
    ('Online Shopping or Local Shops',
     'Some people think online shopping is better for consumers in every way, while others believe local shops offer important benefits that should be protected.'),
    ('The Meaning of Festivals',
     'Some people think traditional festivals are losing their meaning because they have become too commercial, while others believe they are as important as ever.'),
    ('Grades for Young Children',
     'Some people believe primary school children should receive grades for their work, while others think teachers should give them only written comments.'),
    ('The Purpose of University',
     'Some people believe the main purpose of a university education is to prepare students for employment, while others think it should be to develop knowledge for its own sake.'),
    ('Why People Commit Crime',
     'Some people think crime is mainly the result of poverty and social problems, while others believe it is simply a matter of personal choice.'),
    ('Who Should Provide Housing',
     'Some people think the government should build homes for families on low incomes, while others believe housing is best left to private developers.'),
    ('Home or Office Working',
     'Some people think employees are more productive when they work from home, while others believe offices are essential for teamwork and creativity.'),
    ('Translation Technology',
     'Some people believe that translation apps mean there is no longer any need to learn a foreign language, while others think learning languages is as important as ever.'),
    ('Animals in Medical Research',
     'Some people believe that testing medicines on animals is necessary for medical progress, while others think it is cruel and should be banned.'),
    ('Tourism in Remote Wilderness',
     'Some people believe tourists should be allowed to visit remote natural areas such as the polar regions, while others think these places should be closed to tourism.'),
    ('Born or Made Leaders',
     'Some people believe that good leaders are born with special qualities, while others think leadership is a skill that anyone can learn.'),
    ('Stories for Young Children',
     'Some people believe young children should be read stories from printed books, while others think educational apps and videos are just as valuable.'),
    ('Rules for Teenagers',
     'Some parents set strict rules for their teenage children, while others prefer to give them the freedom to make their own decisions.'),
    ('Following Fashion',
     'Some people think it is important to follow the latest fashions, while others believe clothes should be chosen only for comfort and practicality.'),
    ('Older or Younger Employees',
     'Some people believe companies benefit most from hiring experienced older workers, while others think younger employees bring greater advantages.'),
    ('Friendship on Social Media',
     'Some people believe social media has made it easier to keep friendships alive, while others think it has made relationships more superficial.'),
    ('Paying for Water',
     'Some people believe clean water is a basic right and should be free, while others think people should pay for the amount they use in order to prevent waste.'),
    ('Class Size or Teacher Quality',
     'Some people think the number of students in a class has a large effect on how well they learn, while others believe the quality of the teacher matters far more.'),
    ('Eating Together as a Family',
     'Some people think families should eat their main meal together every day, while others believe this is no longer realistic in modern life.'),
    ('Genetically Modified Crops',
     'Some people believe genetically modified crops are the answer to future food shortages, while others think the risks of growing them are too great.'),
    ('Discipline in Schools',
     'Some people believe strict discipline is essential in schools, while others think students learn better in a relaxed and informal environment.'),
    ('Roads or Public Transport',
     'Some people think governments should build more roads to reduce traffic problems, while others believe the money should be spent on public transport instead.'),
    ('Cosmetic Surgery',
     'Some people think cosmetic surgery is a personal choice that others should not judge, while others believe it should be discouraged.'),
    ('Charity or Government Support',
     'Some people think charities should be responsible for helping people in need, while others believe this is the duty of the government.'),
    ('Keeping Pets in Cities',
     'Some people believe keeping pets in city flats is unfair to the animals, while others think pets benefit both their owners and the animals themselves.'),
    ('Private Schools',
     'Some people think private schools benefit society by giving parents more choice, while others believe they increase inequality.'),
    ('Ambition or Contentment',
     'Some people think it is important to be ambitious and always aim higher, while others believe that being content with what you have leads to a happier life.'),
    ('Moderating Online Content',
     'Some people think social media companies should remove offensive posts from their platforms, while others believe this threatens freedom of speech.'),
    ('More Public Holidays',
     'Some people believe a country should have more public holidays, while others think additional holidays would harm the economy.'),
    ('Growing Your Own Food',
     'Some people think every household should grow some of its own food, while others believe this is impractical in the modern world.'),
    ('Friends or Family as Influences',
     'Some people believe friends have the greatest influence on young people, while others think the family is far more influential.'),
    ('Pure or Applied Research',
     'Some people think governments should fund only scientific research that has clear practical uses, while others believe research with no immediate application is equally important.'),
]

OUTWEIGH = 'Do the advantages of this outweigh the disadvantages?'
BENEFITS = 'Do the benefits of this development outweigh the drawbacks?'
BOTH_SIDES = 'What are the advantages and disadvantages of this?'

# Advantages / disadvantages: a trend, then a weighing question. OUTWEIGH and
# BENEFITS ask for a judgement; BOTH_SIDES asks only for both sides.
ADVANTAGES = [
    ('Living With Flatmates',
     'In many cities, young adults are choosing to share a house with flatmates rather than live alone or with their family.', OUTWEIGH),
    ('Online-Only Banking',
     'Many banks are closing their local branches and offering their services only online.', OUTWEIGH),
    ('Buy Now, Pay Later',
     'More and more shoppers are using services that allow them to buy goods now and pay for them in instalments later.', OUTWEIGH),
    ('Imported Food All Year Round',
     'Supermarkets now sell fruit and vegetables imported from all over the world, whatever the season.', BENEFITS),
    ('Smartphones for Young Children',
     'In many countries, children now own a smartphone before they are ten years old.', OUTWEIGH),
    ('Cruise Holidays',
     'Holidays on large cruise ships are becoming increasingly popular.', BOTH_SIDES),
    ('Working as a Freelancer',
     'More people are working as freelancers for several clients instead of being employed full-time by one company.', OUTWEIGH),
    ('Self-Service Checkouts',
     'Many shops and supermarkets are replacing cashiers with self-service checkout machines.', OUTWEIGH),
    ('Adult Children Living at Home',
     'In many countries, young adults are living with their parents for longer than in the past.', BOTH_SIDES),
    ('Moving Abroad for Work',
     'More and more people are moving to another country to find work.', OUTWEIGH),
    ('Smart Home Devices',
     'Many homes now use voice-controlled devices to manage lighting, heating and even grocery shopping.', OUTWEIGH),
    ('Only Children',
     'Many couples today are choosing to have only one child.', BOTH_SIDES),
    ('Streaming Films at Home',
     'People increasingly watch new films at home on streaming services rather than going to the cinema.', OUTWEIGH),
    ('Rental Electric Scooters',
     'Electric scooters that can be rented by the minute have appeared on the streets of many cities.', BENEFITS),
    ('Open-Plan Offices',
     'Many companies have replaced private offices with large open-plan workspaces.', OUTWEIGH),
    ('Online Medical Appointments',
     'Many doctors now see patients through video calls instead of face-to-face appointments.', OUTWEIGH),
    ('Home Schooling',
     'A growing number of parents are choosing to educate their children at home rather than send them to school.', BOTH_SIDES),
    ('Out-of-Town Shopping Centres',
     'In many places, large shopping centres are being built on the edges of towns rather than in the town centre.', OUTWEIGH),
    ('Wearable Fitness Trackers',
     'Many people now wear devices that record their steps, heart rate and sleep throughout the day.', OUTWEIGH),
    ('Choosing Smaller Homes',
     'Some people are choosing to live in very small homes in order to reduce their living costs.', BOTH_SIDES),
    ('Gated Communities',
     'In some cities, more families are choosing to live in gated communities with private security.', OUTWEIGH),
    ('Home DNA Tests',
     'Many people now buy home DNA test kits to learn about their ancestry and health risks.', OUTWEIGH),
    ('Renting Instead of Owning',
     'Instead of buying items such as tools, cars and clothes, more people are choosing to rent or share them.', BENEFITS),
    ('Software That Screens Job Applicants',
     'Many companies now use computer software to select which job applicants are invited to an interview.', OUTWEIGH),
    ('Foreign Companies in Developing Countries',
     'Large international companies are opening factories and offices in many developing countries.', OUTWEIGH),
    ('Boarding Schools',
     'Some parents send their children to boarding schools, where they live away from home during term time.', BOTH_SIDES),
    ('Learning Skills From Online Videos',
     'Many people now learn practical skills such as cooking and home repairs from online videos instead of taking a course.', OUTWEIGH),
    ('Becoming Parents Later in Life',
     'In many countries, people are waiting until they are older before having children.', OUTWEIGH),
    ('Parcel Delivery by Drone',
     'Some companies have started delivering small parcels to customers by drone.', BENEFITS),
    ('Short-Term Holiday Lets',
     'In many cities, homeowners are renting out their flats to tourists for short stays through online platforms.', OUTWEIGH),
    ('Food Delivery Apps',
     'Ordering restaurant meals through delivery apps has become part of daily life for many people.', OUTWEIGH),
    ('Ride-Hailing Apps',
     'Many people now use smartphone apps to book rides with private drivers instead of using traditional taxis.', BOTH_SIDES),
    ('International Students',
     'Universities in many countries are recruiting large numbers of students from overseas.', OUTWEIGH),
    ('Meeting a Partner Online',
     'Many people today meet their husband, wife or partner through online dating services.', OUTWEIGH),
    ('Company Sponsorship of Schools',
     'Some schools receive money and equipment from businesses in return for displaying the company\'s name.', OUTWEIGH),
    ('Retiring Abroad',
     'A growing number of people are moving to another country when they retire.', BOTH_SIDES),
    ('Shops Open 24 Hours',
     'In many cities, supermarkets and other shops now stay open 24 hours a day.', OUTWEIGH),
    ('Urban Farming',
     'Some cities are growing fruit and vegetables on rooftops and in indoor farms.', BENEFITS),
    ('Artificial Intelligence in Medicine',
     'Hospitals are beginning to use artificial intelligence to help diagnose illnesses.', OUTWEIGH),
    ('Grandparents Living With the Family',
     'In some countries, it is becoming more common for grandparents, parents and children to live together in one home.', BOTH_SIDES),
    ('Organised After-School Activities',
     'Many children now spend most of their free time in organised clubs and classes rather than playing freely.', OUTWEIGH),
    ('Longer School Days',
     'Some schools have extended the school day by an hour or more.', OUTWEIGH),
    ('Taking a Career Break',
     'More employees are taking a break of several months from work to travel, study or care for their family.', BOTH_SIDES),
    ('Video Games as Professional Sport',
     'Competitive video gaming has become a professional sport with large audiences and prize money.', OUTWEIGH),
    ('Workplace Dress Codes',
     'Many employers require their staff to follow a strict dress code at work.', OUTWEIGH),
    ('Wind Farms in the Countryside',
     'Large wind farms are being built in many rural areas to generate electricity.', BENEFITS),
    ('Holiday Homes in Villages',
     'Many people from cities are buying second homes in villages that they use only during holidays.', OUTWEIGH),
    ('Studying Part-Time While Working',
     'Many students are choosing to study part-time while working, rather than studying full-time.', BOTH_SIDES),
    ('Meat Grown in Laboratories',
     'Scientists have developed ways of growing meat in laboratories without raising animals.', OUTWEIGH),
    ('Airport Expansion',
     'Many cities are building new airports or expanding existing ones to handle more flights.', OUTWEIGH),
]

CAUSE_SOLVE = 'What problems does this cause? What solutions can you suggest?'
MEASURES = 'What problems are associated with this, and what measures could be taken to solve them?'
WHY_SOLVE = 'Why is this a problem, and what can be done to address it?'

# Problem / solution: a situation, then a question asking for problems (or why
# it is a problem) and for solutions.
PROBLEM_SOLUTION = [
    ('Traffic Congestion',
     'In many cities, roads are becoming more and more congested with traffic.', CAUSE_SOLVE),
    ('Food Waste',
     'Households and supermarkets throw away large quantities of food that could still be eaten.', WHY_SOLVE),
    ('Plastic in the Oceans',
     'Huge amounts of plastic waste end up in the world\'s oceans every year.', MEASURES),
    ('Loneliness in Old Age',
     'In many countries, a growing number of older people live alone and feel lonely.', CAUSE_SOLVE),
    ('Skilled Workers Leaving Home',
     'Many doctors, engineers and other skilled professionals leave developing countries to work abroad.', MEASURES),
    ('Unaffordable City Housing',
     'In many large cities, young people can no longer afford to buy or even rent a home.', CAUSE_SOLVE),
    ('Childhood Obesity',
     'The number of overweight children is increasing in many parts of the world.', MEASURES),
    ('Noise in Cities',
     'People living in cities are exposed to high levels of noise both day and night.', CAUSE_SOLVE),
    ('Young People Leaving Villages',
     'In many countries, young people are leaving rural villages to live and work in cities.', MEASURES),
    ('Teacher Shortages',
     'Many countries do not have enough qualified teachers for their schools.', WHY_SOLVE),
    ('Cyberbullying',
     'An increasing number of young people are being bullied online.', CAUSE_SOLVE),
    ('Water Shortages',
     'Many parts of the world are facing serious shortages of fresh water.', MEASURES),
    ('Air Pollution in Cities',
     'Air quality in many cities has become so poor that it is damaging people\'s health.', MEASURES),
    ('Overcrowded Tourist Destinations',
     'Some popular tourist destinations are now receiving far more visitors than they can cope with.', CAUSE_SOLVE),
    ('Online Scams',
     'Criminals are increasingly using the internet and phone messages to cheat people out of their money.', MEASURES),
    ('Electronic Waste',
     'People replace their phones, computers and other electronic devices more often than ever before.', CAUSE_SOLVE),
    ('Exam Stress',
     'Many school students suffer from high levels of stress because of exams.', WHY_SOLVE),
    ('Teenagers Lacking Sleep',
     'Many teenagers today do not get enough sleep.', CAUSE_SOLVE),
    ('Litter in Public Places',
     'Streets, parks and beaches in many places are spoiled by litter.', MEASURES),
    ('Disappearing Languages',
     'Many of the world\'s minority languages are disappearing because fewer young people speak them.', WHY_SOLVE),
    ('The Decline of Insects',
     'Scientists report that the number of insects, including bees, has fallen sharply in many regions.', WHY_SOLVE),
    ('Adults Who Cannot Read',
     'In many countries, a significant number of adults are unable to read and write well.', CAUSE_SOLVE),
    ('Homelessness',
     'The number of people sleeping on the streets is rising in many cities.', MEASURES),
    ('Overuse of Antibiotics',
     'Antibiotics are being used so widely that many of them are becoming less effective.', WHY_SOLVE),
    ('Deforestation',
     'Large areas of forest are being cut down every year.', CAUSE_SOLVE),
    ('Young People and Online Gambling',
     'More and more young people are gambling online, often using their mobile phones.', MEASURES),
    ('Doctor Shortages in Rural Areas',
     'In many countries, people living in the countryside find it difficult to see a doctor.', CAUSE_SOLVE),
    ('Children Indoors',
     'Children today spend much less time playing outdoors than children did in the past.', CAUSE_SOLVE),
    ('Road Accidents',
     'Road accidents cause many deaths and serious injuries every year.', MEASURES),
    ('Counterfeit Goods',
     'Fake versions of branded products, from clothes to medicines, are widely sold.', CAUSE_SOLVE),
    ('Leaving School Early',
     'In some countries, a large number of students leave school without finishing their education.', MEASURES),
    ('Household Debt',
     'Many families are borrowing more money than they are able to pay back.', CAUSE_SOLVE),
    ('Flooding in Cities',
     'Flooding is becoming a more frequent problem in many towns and cities.', MEASURES),
    ('Inactive Lifestyles',
     'Many adults now spend most of the day sitting down, both at work and at home.', CAUSE_SOLVE),
    ('Abandoned Pets',
     'Many pets are abandoned by their owners every year.', WHY_SOLVE),
    ('Vandalism',
     'Public property such as bus shelters, parks and trains is often damaged by vandals.', MEASURES),
    ('Cheating With AI Tools',
     'Some students are using artificial intelligence tools to write their assignments for them.', CAUSE_SOLVE),
    ('Hospital Waiting Times',
     'In many countries, patients have to wait a long time for hospital treatment.', MEASURES),
    ('Wildlife Poaching',
     'Rare animals are still being illegally hunted for their skins, horns and other body parts.', MEASURES),
    ('Few Women in Engineering',
     'In many countries, far fewer women than men work as engineers.', WHY_SOLVE),
    ('Space Debris',
     'Thousands of pieces of broken satellites and old rockets are now orbiting the Earth.', WHY_SOLVE),
    ('Long Commutes',
     'Many workers spend two or more hours travelling to and from work every day.', CAUSE_SOLVE),
    ('Children Reading Less',
     'Children are reading fewer books for pleasure than they did in the past.', CAUSE_SOLVE),
    ('Rising Energy Bills',
     'Many households are struggling to pay the rising cost of heating and electricity.', MEASURES),
    ('Lack of Affordable Childcare',
     'In many countries, working parents find it difficult to find childcare that they can afford.', CAUSE_SOLVE),
    ('Damaged Farmland',
     'Intensive farming methods are reducing the quality of soil in many agricultural areas.', MEASURES),
    ('Extreme Heat in Cities',
     'Summer heatwaves are becoming more common and more dangerous in many cities.', MEASURES),
    ('Newcomers and the Local Language',
     'Many people who move to a new country struggle because they cannot speak the local language.', CAUSE_SOLVE),
    ('Shortage of Skilled Tradespeople',
     'Many countries do not have enough plumbers, electricians and builders.', WHY_SOLVE),
    ('Empty High Streets',
     'Many shops in town centres have closed, leaving streets full of empty buildings.', CAUSE_SOLVE),
]

CAUSES_EFFECTS = 'What are the causes of this? What effects does it have on individuals and society?'
REASONS_EFFECTS = 'What are the reasons for this trend, and what effects is it having?'
WHY_EFFECTS = 'Why is this happening? What impact does this have on society?'

# Cause / effect: a trend, then a question asking for its causes (or reasons)
# and its effects.
CAUSE_EFFECT = [
    ('Falling Birth Rates',
     'In many countries, the number of babies being born each year is falling.', CAUSES_EFFECTS),
    ('Rising Divorce Rates',
     'The number of marriages ending in divorce has increased in many parts of the world.', CAUSES_EFFECTS),
    ('Adult Obesity',
     'The proportion of adults who are seriously overweight is rising in many countries.', CAUSES_EFFECTS),
    ('Fewer People Cooking',
     'Fewer people cook meals at home from fresh ingredients than in the past.', REASONS_EFFECTS),
    ('Longer Working Hours',
     'In many professions, people are working longer hours than ever before.', WHY_EFFECTS),
    ('The Decline of Letter Writing',
     'Very few people now write personal letters by hand.', REASONS_EFFECTS),
    ('Extreme Sports',
     'Dangerous activities such as base jumping and free climbing are becoming more popular.', REASONS_EFFECTS),
    ('Pressure on Working Parents',
     'Many working parents say they feel under constant pressure to balance their jobs and family life.', CAUSES_EFFECTS),
    ('Young People Avoiding Farming',
     'In many countries, very few young people want to work in farming.', WHY_EFFECTS),
    ('The Gap Between Rich and Poor',
     'In many countries, the gap between the richest and poorest people is growing wider.', CAUSES_EFFECTS),
    ('The Popularity of Tattoos',
     'Tattoos have become far more common and socially accepted than they were a generation ago.', REASONS_EFFECTS),
    ('Fast Food Around the World',
     'International fast food chains can now be found in almost every country in the world.', REASONS_EFFECTS),
    ('Music Festivals',
     'Large outdoor music festivals attract hundreds of thousands of people every summer.', REASONS_EFFECTS),
    ('Travelling Alone',
     'More and more people are choosing to go on holiday alone.', WHY_EFFECTS),
    ('Children Growing Up Faster',
     'Many people feel that children today are growing up much faster than in the past.', CAUSES_EFFECTS),
    ('Demand for Organic Food',
     'Sales of organic food have risen considerably in recent years.', REASONS_EFFECTS),
    ('Private Tutoring',
     'Many parents now pay for private tutors to give their children extra lessons outside school.', CAUSES_EFFECTS),
    ('The Rising Cost of Living',
     'The prices of everyday items such as food, fuel and rent have risen sharply in many countries.', CAUSES_EFFECTS),
    ('Car Ownership in Developing Countries',
     'The number of privately owned cars is growing rapidly in many developing countries.', REASONS_EFFECTS),
    ('Rising Energy Consumption',
     'The amount of energy used by households around the world continues to increase.', CAUSES_EFFECTS),
    ('Interest in Family History',
     'Many people are becoming interested in researching the history of their own family.', REASONS_EFFECTS),
    ('Working at Night',
     'A growing number of people work night shifts in jobs such as healthcare, transport and online services.', WHY_EFFECTS),
    ('Rising Pet Ownership',
     'The number of households that keep pets has increased in many countries.', REASONS_EFFECTS),
    ('Short-Sightedness in Children',
     'Many more children need glasses because they are short-sighted than in previous generations.', CAUSES_EFFECTS),
    ('Fewer Students Choosing Science',
     'In some countries, fewer university students are choosing to study science subjects.', CAUSES_EFFECTS),
    ('The Revival of Old Hobbies',
     'Traditional hobbies such as knitting, board games and vinyl records are becoming popular again.', REASONS_EFFECTS),
    ('Declining Trust in Experts',
     'Many people say they trust experts such as scientists and economists less than they used to.', CAUSES_EFFECTS),
    ('People With More Than One Job',
     'An increasing number of people have two or more jobs at the same time.', WHY_EFFECTS),
    ('Throwaway Culture',
     'People today often throw away items rather than repair or reuse them.', CAUSES_EFFECTS),
    ('Student Debt',
     'Many young people now finish university with large debts.', CAUSES_EFFECTS),
    ('Declining Interest in Classical Music',
     'Audiences for classical music concerts are getting smaller and older.', REASONS_EFFECTS),
    ('Marrying Later',
     'In many countries, people are getting married at a later age than in the past.', REASONS_EFFECTS),
    ('Rising Water Consumption',
     'Many cities are using far more water than they did twenty years ago.', WHY_EFFECTS),
    ('Loneliness Among Young Adults',
     'Surveys show that many young adults feel lonely, even though they are constantly connected online.', CAUSES_EFFECTS),
    ('More People Going to University',
     'A much higher proportion of young people now go to university than in the past.', REASONS_EFFECTS),
    ('The Decline of Small Farms',
     'Small family farms are being replaced by large agricultural companies.', CAUSES_EFFECTS),
    ('Gym Membership',
     'Gyms and fitness centres have become extremely popular in recent years.', REASONS_EFFECTS),
    ('Children Driven to School',
     'Far fewer children walk or cycle to school than in the past; most are now driven by their parents.', CAUSES_EFFECTS),
    ('Weaker Writing Skills',
     'Teachers report that many students\' writing skills are weaker than those of students in the past.', CAUSES_EFFECTS),
    ('Early Retirement',
     'Some people are choosing to stop working in their forties or fifties.', REASONS_EFFECTS),
    ('Less Face-to-Face Conversation',
     'People spend less time talking to each other face to face than they used to.', CAUSES_EFFECTS),
    ('Back and Neck Problems',
     'Back and neck pain have become very common among office workers and students.', CAUSES_EFFECTS),
    ('Adults Learning Languages',
     'More adults are learning a new language in their free time.', REASONS_EFFECTS),
    ('Invasive Species',
     'Plants and animals introduced from other parts of the world are spreading and damaging local wildlife.', CAUSES_EFFECTS),
    ('Cycling to Work',
     'The number of people who cycle to work has increased in many cities.', REASONS_EFFECTS),
    ('Mindfulness and Meditation',
     'Practices such as meditation and mindfulness have become popular around the world.', WHY_EFFECTS),
    ('Declining Bird Populations',
     'The number of common birds such as sparrows and swallows has fallen in many countries.', CAUSES_EFFECTS),
    ('Rising Rates of Allergies',
     'Allergies to food, pollen and dust are becoming more common, especially among children.', CAUSES_EFFECTS),
    ('Fewer People Learning to Swim',
     'In some countries, a growing number of children leave primary school unable to swim.', CAUSES_EFFECTS),
    ('The Growth of Megacities',
     'The number of cities with more than ten million inhabitants has increased rapidly.', CAUSES_EFFECTS),
]

# Two-part (direct) questions: a situation, then two questions answered in turn.
TWO_PART = [
    ('Eating Alone',
     'In many countries, more and more people eat their meals alone.',
     'Why is this happening? Is this a positive or negative development?'),
    ('Wanting to Be an Influencer',
     'Many young people today say they would like to become social media influencers.',
     'Why is this career so attractive to them? Is this a positive or negative trend?'),
    ('Short Breaks',
     'Many people now take several short breaks during the year instead of one long holiday.',
     'Why do people prefer this? Is it a positive or negative development?'),
    ('Shopping as a Leisure Activity',
     'For many people, shopping has become a leisure activity rather than something done only out of necessity.',
     'Why has this happened? Is this a positive or negative development?'),
    ('Photographing Everyday Life',
     'Many people now take photographs of their meals, clothes and daily activities and share them online.',
     'Why do people do this? Is it a positive or negative development?'),
    ('Expensive Weddings',
     'Weddings in many countries are becoming more and more expensive.',
     'Why is this happening? Is this a positive or negative trend?'),
    ('Young People Not Learning to Drive',
     'In some countries, fewer young people are learning to drive than in the past.',
     'What are the reasons for this? Is this a positive or negative development?'),
    ('Choosing a Degree for Salary',
     'Many students choose their university subject according to the salary it may lead to rather than their own interests.',
     'Why do students make this choice? Is this a positive or negative development?'),
    ('Collecting Things',
     'Many people enjoy collecting objects such as stamps, coins or toys.',
     'Why do people collect things? Is collecting a worthwhile hobby?'),
    ('Foreign Festivals',
     'Festivals that originated in other countries are now celebrated in many parts of the world.',
     'Why has this happened? Is this a positive or negative development?'),
    ('Moving House Often',
     'People today move house much more often than their parents and grandparents did.',
     'Why is this? Is this a positive or negative development?'),
    ('Visiting Sites of Tragedy',
     'Some tourists choose to visit places associated with wars, disasters or crimes.',
     'Why do people visit such places? Should this kind of tourism be encouraged?'),
    ('Working After Retirement Age',
     'More people are continuing to work after they reach the official retirement age.',
     'Why are they doing this? Is it a positive or negative development?'),
    ('Adults Playing Video Games',
     'Video games are now played by as many adults as children.',
     'Why are video games so popular with adults? Is this a positive or negative development?'),
    ('Handmade Products',
     'Some people are willing to pay much more for handmade products than for similar factory-made ones.',
     'Why do people do this? Is this a positive trend?'),
    ('Choosing to Stay Single',
     'More people are choosing to remain single rather than marry or live with a partner.',
     'What are the reasons for this? Is this a positive or negative development for society?'),
    ('The Rise of Podcasts',
     'Podcasts have become very popular in recent years.',
     'Why are they so popular? Will they replace traditional radio in the future?'),
    ('Traditional Dress',
     'In many countries, fewer people wear traditional clothing in their daily lives.',
     'Why has this happened? Is it a positive or negative development?'),
    ('School Trips Abroad',
     'Many schools now organise trips abroad for their students.',
     'Why do schools organise these trips? Are the benefits worth the cost?'),
    ('Messages Instead of Calls',
     'Many people now prefer to send text or voice messages rather than make phone calls.',
     'Why is this? Is this a positive or negative development?'),
    ('Paying Others for Household Tasks',
     'More people are paying others to do tasks such as cleaning, cooking and gardening for them.',
     'Why is this happening? Is it a positive or negative trend?'),
    ('Turning a Hobby Into a Business',
     'Many people try to turn a hobby into a way of earning money.',
     'Why do people do this? Is it a good idea?'),
    ('Cooking Food From Other Countries',
     'People increasingly cook and eat dishes from other countries at home.',
     'Why has this become so common? Is this a positive or negative development?'),
    ('Queuing for New Products',
     'Some people queue for hours or even days to buy a new product on the day it is released.',
     'Why do people do this? What does it show about modern society?'),
    ('Looking Up Symptoms Online',
     'Many people search the internet for information about their health before, or instead of, seeing a doctor.',
     'Why do people do this? Is it a positive or negative development?'),
    ('Sharing Private Life Online',
     'Many people share details of their private lives on social media.',
     'Why do they do this? What are the dangers of sharing so much information?'),
    ('Cities Looking the Same',
     'Many cities around the world are starting to look more and more alike.',
     'Why is this happening? Is this a positive or negative development?'),
    ('Paying for Mountain Rescue',
     'Some people who go climbing or trekking in remote areas have to be rescued at great expense.',
     'Why do people take these risks? Should they pay the cost of their own rescue?'),
    ('Fundraising Challenges',
     'Many people raise money for charity by completing physical challenges such as marathons.',
     'Why do people choose to raise money in this way? Is it the best way to support a charity?'),
    ('Volunteering Abroad',
     'Many young people spend a few weeks doing volunteer work in developing countries.',
     'Why do they do this? Does this kind of volunteering really help local communities?'),
    ('Reading Only the Headlines',
     'Many people now read only the headlines of news stories rather than the full articles.',
     'Why do people do this? Is this a positive or negative development?'),
    ('Less Free Time',
     'Many people say they have less free time than before, even though technology saves them time.',
     'Why is this? What can people do to achieve a better balance in their lives?'),
    ('True Crime Stories',
     'Books, podcasts and programmes about real crimes have become extremely popular.',
     'Why are people so interested in these stories? Is this a positive or negative trend?'),
    ('Empty Homes as Investments',
     'In some cities, many flats are bought as investments and left empty.',
     'Why do people buy homes they do not live in? What should governments do about this?'),
    ('Borrowed Words',
     'Many languages are borrowing more and more words from English.',
     'Why is this happening? Is it a threat to those languages?'),
    ('Wealthy People and Charity',
     'Some very wealthy people give large sums of money to charity.',
     'Why do they do this? Should the rich be required to give more of their wealth to others?'),
    ('Adults Leaving Sports Clubs',
     'Fewer adults are joining local sports clubs than in the past.',
     'Why is this happening? What can be done to encourage more adults to take part?'),
    ('Emojis Instead of Words',
     'People increasingly use emojis and other symbols instead of words when they write messages.',
     'Why is this? Is it having a negative effect on language?'),
    ('Holidays at Home',
     'Instead of travelling, many people now spend their holidays at home or close to where they live.',
     'Why are people doing this? Is it a positive or negative development?'),
    ('Forgotten Playground Games',
     'Many traditional games that children used to play together are no longer played.',
     'Why is this happening? Does it matter?'),
    ('Diets From the Internet',
     'Many people follow diets that they have found on the internet.',
     'Why do people do this? What are the risks?'),
    ('Women in Senior Positions',
     'The number of women in senior positions in business and government is increasing.',
     'Why is this happening? What further changes are needed?'),
    ('Electronic Toys',
     'Many children\'s toys are now electronic rather than simple objects such as dolls and wooden blocks.',
     'Why has this change happened? Is it a positive or negative development?'),
    ('Art Made With AI',
     'Some artists now use artificial intelligence to help them create their work.',
     'Why do they use it? Can work produced in this way be called art?'),
    ('Remote Workers in Small Towns',
     'People who can work remotely are moving from large cities to small towns.',
     'Why are they moving? How does this affect the towns they move to?'),
    ('Teenagers With Part-Time Jobs',
     'Many teenagers have a part-time job while they are still at school.',
     'Why do teenagers work? Is this a positive or negative development?'),
    ('Celebrities Entering Politics',
     'A number of celebrities from sport and entertainment have become politicians.',
     'Why do voters support them? Is this a positive or negative development?'),
    ('Loyal Sports Fans',
     'Many people support the same sports team passionately throughout their lives.',
     'Why are people so loyal to their teams? Is this kind of loyalty a good thing?'),
    ('Paying for Online Content',
     'More people are paying subscriptions for online news, music and films.',
     'Why are people willing to pay? Will free online content disappear in the future?'),
    ('Buying Lottery Tickets',
     'Millions of people buy lottery tickets every week, even though their chances of winning are very small.',
     'Why do people buy them? Should governments run national lotteries?'),
]
