"""IELTS Writing Task 1 (Academic) practice figures, bank 4.

Original Prepyo figures in the public IELTS Academic Task 1 formats: bar
charts, line graphs, pie charts, tables, combined charts, maps and process
diagrams. Places are real countries and cities or plain descriptions; the
figures are invented for practice (plausible, not official statistics) and are
not official, recalled or copied test content. `features` is the examiner-style
summary of the main features, given to the marker so it can judge whether a
response selects and reports them accurately.

The fields follow scripts/ielts_bank2/writing_task1.py:
  kind='bar'     categories on the x axis, one bar per series in each group
  kind='line'    x values and one line per series
  kind='pie'     one to three pies of percentages that each total 100
  kind='table'   header row and data rows
  kind='process' ordered stages
  kind='map'     two panels (before/after) of labelled areas on a 10x8 grid
  kind='mixed'   two of the chart kinds above, each with its own title
`lead` (optional) replaces the standard opening of the prompt.
"""

FIGURES = [
    # ---------------------------------------------------------------- bar charts
    dict(kind='bar', title='Household recycling rates in five European countries',
         desc='the percentage of household waste that was recycled in five European countries in 2005 and 2022',
         unit='% of household waste', categories=['Germany', 'Italy', 'Poland', 'Spain', 'UK'],
         series={'2005': [56, 22, 6, 18, 27], '2022': [67, 51, 40, 36, 44]},
         features='Recycling rates rose in all five countries. Germany recycled the highest proportion in both years (56% and then 67%) but showed the smallest increase. Poland improved most, from only 6% to 40%, and Italy more than doubled its rate from 22% to 51%, moving ahead of the UK (44%). Spain had the lowest rate in 2022, at 36%.'),
    dict(kind='bar', title='Daily viewing of broadcast TV and online video',
         desc='the average number of minutes per day that people in five age groups in the UK spent watching broadcast television and online video in 2023',
         unit='minutes per day', categories=['16-24', '25-34', '35-54', '55-64', '65+'],
         series={'Broadcast TV': [35, 70, 140, 210, 290], 'Online video': [190, 150, 95, 60, 35]},
         features='The two types of viewing moved in opposite directions with age. Broadcast TV viewing rose steadily from 35 minutes a day among 16-24s to 290 minutes among the over-65s, while online video fell from 190 to 35 minutes. The two youngest groups watched more online video than broadcast TV; from 35-54 onwards the reverse was true. Total viewing was highest for the over-65s (325 minutes) and lowest for 25-34s (220 minutes).'),
    dict(kind='bar', title='Rail journeys per person in four countries',
         desc='the average number of rail journeys made per person in four European countries in 2000, 2010 and 2019',
         unit='journeys per person per year', categories=['France', 'Netherlands', 'Switzerland', 'UK'],
         series={'2000': [17, 20, 36, 13], '2010': [18, 25, 43, 20], '2019': [19, 27, 55, 26]},
         features='Rail use increased in all four countries. The Swiss travelled by train far more than people elsewhere, and their figure rose from 36 to 55 journeys a year. The UK figure doubled from 13 to 26, overtaking France by 2010, while France changed very little (17 to 19). The Netherlands rose steadily from 20 to 27.'),
    dict(kind='bar', title='Why overseas visitors came to the UK',
         desc='the main reasons given by overseas visitors for coming to the UK in 2012 and 2022',
         unit='% of visitors', categories=['Holiday', 'Seeing friends and family', 'Business', 'Study', 'Other'],
         series={'2012': [38, 29, 23, 3, 7], '2022': [37, 36, 15, 4, 8]},
         features='Holidays were the most common reason for visiting in both years, at 38% and 37%. Seeing friends and family rose from 29% to 36% and was almost as common as holidays by 2022. Business trips fell sharply from 23% to 15% of visits. Study and other reasons accounted for small and fairly stable shares.'),
    dict(kind='bar', title='Rents for one-bedroom flats in four UK cities',
         desc='the average weekly rent for a one-bedroom flat in four UK cities in 2015 and 2024',
         unit='£ per week', categories=['London', 'Manchester', 'Bristol', 'Glasgow'],
         series={'2015': [300, 140, 175, 125], '2024': [410, 210, 250, 190]},
         features='Rents rose in all four cities. London was by far the most expensive in both years and saw the largest rise in pounds, from £300 to £410 a week. In percentage terms, however, Manchester (£140 to £210) and Glasgow (£125 to £190) rose most, by about half. Bristol remained the second most expensive city and Glasgow the cheapest.'),
    dict(kind='bar', title='Sport and exercise among Australian men and women',
         desc='the percentage of men and women in Australia who took part in five sports or activities at least once a month in 2023',
         unit='% of adults', categories=['Walking', 'Swimming', 'Cycling', 'Running', 'Yoga'],
         series={'Men': [38, 16, 14, 17, 3], 'Women': [52, 18, 7, 14, 16]},
         features='Walking was the most popular activity for both sexes, but especially for women (52% compared with 38% of men). The largest differences were in yoga, done by 16% of women but only 3% of men, and cycling, where men were twice as likely to take part (14% and 7%). Swimming and running were similarly popular with men and women.'),
    dict(kind='bar', title='Share of electricity from renewable sources',
         desc='the proportion of electricity generated from renewable sources in five countries in 2010 and 2022',
         unit='% of electricity generated', categories=['Norway', 'Denmark', 'Spain', 'Japan', 'Canada'],
         series={'2010': [95, 33, 33, 10, 62], '2022': [98, 81, 47, 22, 68]},
         features='Every country increased its share of renewable electricity. Norway produced almost all of its electricity from renewables in both years. Denmark showed by far the greatest change, from a third (33%) to 81%. Spain and Canada grew more modestly, and Japan had the lowest share throughout, although it more than doubled from 10% to 22%.'),
    dict(kind='bar', title='Daily water use per person in six countries',
         desc='the average amount of water used at home per person each day in six countries in 2000 and 2020',
         unit='litres per person per day', categories=['US', 'Australia', 'Italy', 'UK', 'Germany', 'India'],
         series={'2000': [380, 340, 250, 150, 128, 90], '2020': [310, 260, 220, 142, 122, 110]},
         features='People in the US used the most water in both years, although use fell by 70 litres to 310. Australia had the largest proportional fall, of about a quarter (340 to 260 litres). Italy fell slightly, while use in the UK and Germany hardly changed. India had the lowest figures and was the only country where use rose (90 to 110 litres).'),
    dict(kind='bar', title='A-level entries in five modern languages',
         desc='the number of students in England who took A-level exams in five modern languages in 2010 and 2023',
         unit='thousands of students', categories=['French', 'Spanish', 'German', 'Chinese', 'Other languages'],
         series={'2010': [13.0, 7.5, 5.5, 2.6, 6.0], '2023': [8.0, 8.5, 2.8, 3.8, 5.2]},
         features='Overall entries fell from 34,600 to 28,300. French was the most popular language in 2010 (13,000) but lost almost 40% of its students and was overtaken by Spanish, which rose to 8,500. German entries roughly halved to 2,800, and Chinese grew from 2,600 to 3,800, moving ahead of German.'),
    dict(kind='bar', title='Unpaid work done by men and women in Canada',
         desc='the average time per day that men and women in Canada spent on five types of unpaid work at home in 2022',
         unit='minutes per day', categories=['Cooking', 'Cleaning', 'Childcare', 'Shopping', 'DIY and repairs'],
         series={'Men': [40, 25, 30, 20, 20], 'Women': [65, 55, 60, 30, 5]},
         features='Women spent more time than men on every task except DIY and repairs (5 minutes compared with 20). The largest gaps were in cleaning and childcare, where women spent 30 minutes a day more than men, and cooking took the most time for both. In total women did 215 minutes of unpaid work a day, compared with 135 for men.'),
    # --------------------------------------------------------------- line graphs
    dict(kind='line', title='Car ownership in three countries',
         desc='the number of cars per 1,000 people in China, Poland and the UK between 1990 and 2020',
         unit='cars per 1,000 people', x=[1990, 1995, 2000, 2005, 2010, 2015, 2020],
         series={'China': [2, 4, 7, 20, 60, 120, 190], 'Poland': [140, 200, 260, 320, 450, 580, 680], 'UK': [360, 390, 420, 450, 460, 470, 470]},
         features='Car ownership rose in all three countries. The UK had the highest level at first, but growth there slowed and levelled off at about 470 cars per 1,000 people. Poland rose fastest, from 140 to 680, overtaking the UK between 2010 and 2015. China started from almost nothing and remained far below the other two, but its growth sped up after 2005, reaching 190 by 2020.'),
    dict(kind='line', title='Average house prices in three English regions',
         desc='average house prices in London, the South West and the North East of England between 1999 and 2023',
         unit='£ thousands', x=[1999, 2003, 2007, 2011, 2015, 2019, 2023],
         series={'London': [180, 250, 300, 330, 470, 500, 520], 'South West': [110, 170, 200, 195, 240, 270, 310], 'North East': [70, 100, 130, 125, 130, 135, 160]},
         features='Prices rose in all three regions, and London was by far the most expensive throughout, almost tripling from £180,000 to £520,000, with the steepest rise between 2011 and 2015. Prices in the South West and North East dipped slightly after 2007. The North East remained the cheapest region and grew most slowly, although prices still more than doubled to £160,000.'),
    dict(kind='line', title='Passengers at three UK airports',
         desc='the number of passengers using Heathrow, Manchester and Edinburgh airports between 2004 and 2019',
         unit='millions of passengers', x=[2004, 2007, 2010, 2013, 2016, 2019],
         series={'Heathrow': [67, 68, 66, 72, 76, 81], 'Manchester': [21, 22, 17, 21, 26, 29], 'Edinburgh': [8, 9, 9, 10, 12, 15]},
         features='Heathrow was much the busiest airport, with passenger numbers rising from 67 to 81 million. All three airports saw little growth or a fall around 2010, most noticeably Manchester, which dropped to 17 million before recovering strongly to 29 million. Edinburgh was the smallest airport but grew fastest in relative terms, almost doubling from 8 to 15 million.'),
    dict(kind='line', title='New cars sold in Norway by fuel type',
         desc='the percentage of new cars sold in Norway that ran on petrol, diesel or electricity between 2012 and 2024',
         unit='% of new cars sold', x=[2012, 2014, 2016, 2018, 2020, 2022, 2024],
         series={'Petrol': [55, 40, 30, 25, 15, 6, 2], 'Diesel': [40, 45, 40, 30, 15, 5, 1], 'Electric': [3, 12, 25, 40, 65, 86, 95]},
         features='Electric cars went from a tiny share of sales (3%) to almost all new cars (95%), becoming the most popular type in 2018. Diesel sales peaked at 45% in 2014 and then fell rapidly, while petrol declined steadily from 55%. By 2024 petrol and diesel together made up only 3% of new cars sold.'),
    dict(kind='line', title='Average working week in four countries',
         desc='the average number of hours worked per week by employees in four countries between 1970 and 2020',
         unit='hours per week', x=[1970, 1980, 1990, 2000, 2010, 2020],
         series={'Japan': [44, 42, 41, 38, 36, 34], 'US': [38, 37, 37, 36, 35, 35], 'Germany': [39, 36, 34, 31, 29, 27], 'South Korea': [52, 53, 50, 48, 43, 38]},
         features='Working hours fell in all four countries. South Korea had the longest working week throughout, although hours fell sharply after 2000, from 48 to 38. Germany had the shortest week from 1980 and saw a steady fall to 27 hours. The US changed least (38 to 35 hours), so that by 2020 Americans worked slightly longer than the Japanese.'),
    dict(kind='line', title='Electricity demand in Britain across a day',
         desc='electricity demand in Britain over 24 hours on a typical winter day and a typical summer day',
         unit='gigawatts', x=['midnight', '3 am', '6 am', '9 am', 'noon', '3 pm', '6 pm', '9 pm'],
         series={'Winter day': [28, 24, 30, 38, 37, 39, 45, 38], 'Summer day': [20, 17, 20, 27, 28, 27, 28, 25]},
         features='Demand was higher in winter at every time of day. Both days had their lowest point at 3 am (24 and 17 gigawatts) and rose sharply in the morning. In winter demand peaked at 45 gigawatts at 6 pm, but in summer it stayed fairly flat at 27-28 gigawatts from 9 am to 6 pm, so the difference between the seasons was greatest in the early evening (17 gigawatts).'),
    dict(kind='line', title='UK recorded music sales by format',
         desc='the value of recorded music sold in the UK in four formats between 2000 and 2024',
         unit='£ millions', x=[2000, 2004, 2008, 2012, 2016, 2020, 2024],
         series={'CDs': [1800, 1600, 1000, 600, 350, 150, 120], 'Downloads': [0, 60, 250, 380, 200, 60, 30], 'Streaming': [0, 0, 10, 80, 500, 1000, 1400], 'Vinyl': [20, 10, 10, 15, 60, 90, 130]},
         features='CDs dominated in 2000 (£1.8 billion) but declined steadily to £120 million. Downloads rose to a peak of £380 million in 2012 and then fell away. Streaming grew from nothing after 2008 to £1.4 billion, overtaking CDs by 2016 and becoming the main format. Vinyl remained small but recovered after 2012 and by 2024 earned slightly more than CDs.'),
    dict(kind='line', title='International tourist arrivals in three countries',
         desc='the number of international tourists who arrived in France, Spain and Thailand between 2000 and 2019',
         unit='millions of arrivals', x=[2000, 2005, 2010, 2015, 2019],
         series={'France': [77, 75, 77, 85, 90], 'Spain': [47, 56, 53, 68, 84], 'Thailand': [10, 12, 16, 30, 40]},
         features='France received the most tourists throughout, but its numbers were fairly stable until 2010 before rising to 90 million. Spain grew strongly after 2010, from 53 to 84 million, and had almost caught up with France by 2019. Thailand had far fewer arrivals but grew fastest, quadrupling from 10 to 40 million, with the sharpest rise between 2010 and 2015.'),
    dict(kind='line', title='Monthly sunshine in two British cities',
         desc='the average number of hours of sunshine each month in Brighton and Glasgow',
         unit='hours of sunshine per month', x=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
         series={'Brighton': [65, 85, 125, 180, 225, 230, 240, 220, 165, 115, 75, 55], 'Glasgow': [40, 65, 100, 145, 190, 170, 160, 150, 115, 80, 50, 35]},
         features='Both cities followed the same seasonal pattern, with the least sunshine in December and the most in early summer. Brighton was sunnier in every month and reached its peak of 240 hours in July. Glasgow peaked earlier, at 190 hours in May, and became duller through the summer, so the gap between the cities was widest in July (80 hours).'),
    dict(kind='line', title='Online share of retail sales in three countries',
         desc='the percentage of retail sales made online in the UK, China and Germany between 2008 and 2023',
         unit='% of retail sales', x=[2008, 2011, 2014, 2017, 2020, 2023],
         series={'UK': [5, 9, 12, 16, 24, 23], 'China': [1, 4, 11, 19, 25, 28], 'Germany': [4, 6, 8, 11, 15, 14]},
         features='The online share of sales grew in every country. At first the UK had the highest share, but China, starting from only 1%, grew fastest and overtook the UK in 2017, reaching 28% by 2023. Germany had the lowest share from 2014 onwards. Both the UK and Germany peaked in 2020 and fell back slightly by 2023.'),
    # ---------------------------------------------------------------- pie charts
    dict(kind='pie', title='How UK households divided their spending',
         desc='how the average weekly spending of UK households was divided in 1980 and 2020',
         pies={'1980': {'Food': 22, 'Housing': 16, 'Transport': 15, 'Recreation': 11, 'Clothing': 9, 'Other goods and services': 27},
               '2020': {'Food': 11, 'Housing': 25, 'Transport': 15, 'Recreation': 14, 'Clothing': 5, 'Other goods and services': 30}},
         features='The share of spending on housing rose most, from 16% to 25%, making it the largest category in 2020 apart from other goods and services. By contrast, the proportion spent on food halved from 22% to 11% and clothing fell from 9% to 5%. Transport stayed at 15%, recreation rose slightly to 14%, and other goods and services grew from 27% to 30%.'),
    dict(kind='pie', title='Electricity generation in Germany by source',
         desc='the sources used to generate electricity in Germany in 2000 and 2023',
         pies={'2000': {'Coal': 52, 'Nuclear': 29, 'Gas': 9, 'Renewables': 7, 'Other': 3},
               '2023': {'Coal': 26, 'Nuclear': 1, 'Gas': 15, 'Renewables': 53, 'Other': 5}},
         features='In 2000 coal was the main source of electricity (52%), followed by nuclear power (29%), and renewables provided only 7%. By 2023 renewables supplied more than half of all electricity (53%), coal’s share had halved to 26%, and nuclear power had almost disappeared (1%). The share from gas rose from 9% to 15%.'),
    dict(kind='pie', title='Main source of news by age group',
         desc='the main source of news for adults in three age groups in the UK in 2023',
         pies={'16-24': {'Television': 15, 'Social media': 55, 'News websites': 18, 'Radio': 5, 'Newspapers': 2, 'Other': 5},
               '35-54': {'Television': 38, 'Social media': 20, 'News websites': 25, 'Radio': 10, 'Newspapers': 5, 'Other': 2},
               '65+': {'Television': 58, 'Social media': 5, 'News websites': 10, 'Radio': 14, 'Newspapers': 12, 'Other': 1}},
         features='Social media was the main news source for more than half of 16-24s (55%), while television was the main source for most people over 65 (58%). The middle group used a wider mix, with television (38%), news websites (25%) and social media (20%) all important. Radio and newspapers were more important with age, and newspapers were the main source for 12% of the oldest group but only 2% of the youngest.'),
    dict(kind='pie', title='Household rubbish collected in Leeds',
         desc='the make-up of household rubbish collected in Leeds in 2005 and 2023',
         pies={'2005': {'Food': 25, 'Paper and card': 28, 'Plastics': 10, 'Glass': 10, 'Garden waste': 15, 'Other': 12},
               '2023': {'Food': 32, 'Paper and card': 18, 'Plastics': 17, 'Glass': 6, 'Garden waste': 12, 'Other': 15}},
         features='Paper and card made up the largest share of rubbish in 2005 (28%) but fell to 18%, and food waste became the largest category, rising from 25% to 32%. Plastics also increased, from 10% to 17%. The shares of glass and garden waste both fell, while other waste rose slightly.'),
    dict(kind='pie', title='Age structure of Italy and Nigeria',
         desc='the proportion of the population in three age groups in Italy in 1970 and 2020, and in Nigeria in 2020',
         pies={'Italy 1970': {'Under 15': 25, '15-64': 64, '65 and over': 11},
               'Italy 2020': {'Under 15': 13, '15-64': 64, '65 and over': 23},
               'Nigeria 2020': {'Under 15': 43, '15-64': 54, '65 and over': 3}},
         features='People aged 15-64 made up the majority in every case. Italy’s population aged markedly between 1970 and 2020: the share of children almost halved from 25% to 13%, while the share aged 65 and over doubled to 23%. Nigeria in 2020 had a very young population, with 43% under 15 and only 3% aged 65 and over, and a smaller working-age share (54%) than Italy (64%).'),
    dict(kind='pie', title='Income of a regional theatre',
         desc='the sources of income for a regional theatre in England in 2010 and 2024',
         pies={'2010': {'Ticket sales': 55, 'Government grants': 25, 'Donations': 8, 'Café and shop': 7, 'Other': 5},
               '2024': {'Ticket sales': 60, 'Government grants': 10, 'Donations': 12, 'Café and shop': 13, 'Other': 5}},
         features='Ticket sales were the main source of income in both years and rose from 55% to 60%. The most significant change was the fall in government grants, from a quarter of income to only 10%. The theatre made up for this with more donations (8% to 12%) and almost doubled the share from its café and shop (7% to 13%).'),
    dict(kind='pie', title='How undergraduates divide their study time',
         desc='how undergraduate students at a British university divided their study time in their first year and in their final year',
         pies={'First year': {'Lectures': 40, 'Seminars': 15, 'Independent study': 30, 'Group projects': 10, 'Other': 5},
               'Final year': {'Lectures': 20, 'Seminars': 12, 'Independent study': 40, 'Group projects': 5, 'Dissertation research': 20, 'Other': 3}},
         features='First-year students spent the largest share of their study time in lectures (40%), whereas final-year students spent most time on independent study (40%). The share for lectures halved to 20% and group projects also halved, to 5%. Dissertation research, not part of the first year, took a fifth of final-year study time.'),
    # -------------------------------------------------------------------- tables
    dict(kind='table', title='Growth of five large cities',
         desc='the population of five large cities in 1950, 1990 and 2020',
         header=['City', '1950 (millions)', '1990 (millions)', '2020 (millions)'],
         rows=[['Tokyo', '11.3', '32.5', '37.4'], ['Lagos', '0.3', '4.8', '14.4'], ['Mumbai', '3.1', '12.4', '20.4'], ['London', '8.4', '6.8', '9.3'], ['Mexico City', '3.4', '15.6', '21.8']],
         features='Tokyo was the largest city at every date and more than tripled to 37.4 million. Lagos grew fastest, from only 0.3 million in 1950, the smallest figure in the table, to 14.4 million. Mumbai and Mexico City both grew roughly six-fold. London was the only city whose population fell, from 8.4 to 6.8 million by 1990, and although it recovered to 9.3 million it was the smallest of the five by 2020.'),
    dict(kind='table', title='Costs of four kinds of light bulb',
         desc='information about the power, lifespan and costs of four types of light bulb',
         header=['Bulb type', 'Power (watts)', 'Lifespan (hours)', 'Price (£)', 'Running cost per year (£)'],
         rows=[['Traditional', '60', '1,000', '0.80', '16.00'], ['Halogen', '42', '2,000', '1.50', '11.20'], ['Compact fluorescent', '12', '8,000', '3.50', '3.20'], ['LED', '8', '25,000', '4.00', '2.10']],
         features='The traditional bulb was the cheapest to buy (80p) but used the most power, cost the most to run (£16 a year) and had the shortest life. The LED bulb was the most expensive to buy (£4) but used the least power, cost only £2.10 a year to run and lasted 25 times longer. Running costs rose in line with power.'),
    dict(kind='table', title='Train services from London to four cities',
         desc='information about train services between London and four other British cities',
         header=['Route from London', 'Distance (km)', 'Fastest journey (minutes)', 'Standard return fare (£)', 'Trains per day'],
         rows=[['Birmingham', '190', '80', '95', '70'], ['Manchester', '300', '125', '190', '48'], ['Cardiff', '245', '110', '130', '34'], ['Edinburgh', '630', '260', '160', '36']],
         features='Birmingham was the nearest city, with the shortest journey, the cheapest fare (£95) and by far the most trains (70 a day). Edinburgh was the furthest and took the longest (260 minutes), yet its fare (£160) was lower than the Manchester fare, which was the highest at £190. Cardiff had the fewest trains per day (34).'),
    dict(kind='table', title='Pay and hours in five occupations',
         desc='the average weekly pay and working hours in five occupations in the UK, and the percentage of workers in each who were women',
         header=['Occupation', 'Average weekly pay (£)', 'Average weekly hours', 'Women in the job (%)'],
         rows=[['Nurse', '760', '37.5', '89'], ['Software developer', '1,050', '38', '20'], ['Bus driver', '620', '44', '8'], ['Hairdresser', '390', '33', '86'], ['Solicitor', '1,150', '42', '55']],
         features='Solicitors and software developers earned most (£1,150 and £1,050 a week), while hairdressers earned least (£390) and worked the fewest hours (33). Bus drivers worked the longest week (44 hours) for relatively low pay. Women made up the great majority of nurses (89%) and hairdressers (86%) but only a small minority of software developers (20%) and bus drivers (8%).'),
    dict(kind='table', title='Screen time, sleep and phones among children',
         desc='information about the screen time, sleep and mobile phone ownership of children in four age groups in the UK in 2023',
         header=['Age', 'Screen time per day (hours)', 'Sleep per night (hours)', 'Own a mobile phone (%)'],
         rows=[['5-7', '1.8', '10.9', '4'], ['8-10', '2.6', '10.1', '25'], ['11-13', '4.1', '9.2', '79'], ['14-16', '5.3', '8.4', '97']],
         features='Screen time rose steadily with age, almost tripling from 1.8 hours a day for 5-7-year-olds to 5.3 hours for 14-16-year-olds, while sleep fell from 10.9 to 8.4 hours a night. Phone ownership was rare among the youngest children (4%) but jumped from 25% at 8-10 to 79% at 11-13, and almost all 14-16-year-olds had a phone (97%).'),
    dict(kind='table', title='Green space, air quality and cycling in five cities',
         desc='information about green space, air quality and cycling in five European capital cities',
         header=['City', 'Green space (% of area)', 'Days of poor air quality per year', 'Residents who cycle to work (%)'],
         rows=[['Copenhagen', '25', '8', '45'], ['Amsterdam', '20', '12', '38'], ['London', '33', '35', '5'], ['Paris', '10', '42', '6'], ['Madrid', '15', '30', '2']],
         features='Copenhagen and Amsterdam had by far the most cyclists (45% and 38%) and the fewest days of poor air (8 and 12). London had the most green space (33%) but a high number of poor-air days (35). Paris had the least green space (10%) and the most days of poor air (42), and Madrid had the fewest people cycling to work (2%).'),
    dict(kind='table', title='Climate of four UK capital cities',
         desc='information about the climate of London, Cardiff, Edinburgh and Belfast',
         header=['City', 'Average July maximum (°C)', 'Average January minimum (°C)', 'Annual rainfall (mm)', 'Days of rain per year'],
         rows=[['London', '23.5', '2.4', '620', '110'], ['Cardiff', '21.0', '2.5', '1,150', '150'], ['Edinburgh', '19.2', '1.2', '700', '130'], ['Belfast', '18.8', '2.3', '950', '160']],
         features='London had the warmest summers (23.5°C) and was the driest city, with the least rain (620 mm) and the fewest rainy days (110). Cardiff received the most rain in total (1,150 mm), but Belfast had the most days of rain (160) and the coolest summers. Winter minimums were similar except in Edinburgh, which was coldest at 1.2°C.'),
    # ----------------------------------------------------------- combined charts
    dict(kind='mixed', title='Visitors to the Lake District National Park',
         lead='The bar chart below shows',
         desc='the number of day visitors and staying visitors to the Lake District National Park in each season of 2023, and the pie chart shows the main activity of visitors',
         parts=[dict(kind='bar', title='Visitors by season, 2023', unit='millions of visitors',
                     categories=['Spring', 'Summer', 'Autumn', 'Winter'],
                     series={'Day visitors': [3.2, 5.6, 2.8, 1.4], 'Staying visitors': [0.9, 1.8, 0.8, 0.3]}),
                dict(kind='pie', title='Main activity of visitors',
                     pies={'All visitors': {'Walking': 45, 'Sightseeing by car': 20, 'Visiting towns and villages': 15, 'Water sports': 10, 'Other': 10}})],
         features='Summer was by far the busiest season, with 7.4 million visitors, and winter the quietest, with 1.7 million. In every season day visitors greatly outnumbered those who stayed overnight, by roughly three to five times. Walking was the main activity for almost half of all visitors (45%), followed by sightseeing by car (20%) and visiting towns and villages (15%).'),
    dict(kind='mixed', title='Coffee shops in the UK',
         lead='The graph below shows',
         desc='the number of chain and independent coffee shops in the UK between 2000 and 2020, and the table shows the average price and share of sales of five drinks in 2020',
         parts=[dict(kind='line', title='Number of coffee shops', unit='thousands of shops', x=[2000, 2005, 2010, 2015, 2020],
                     series={'Chain shops': [1.5, 3.5, 6.0, 8.5, 10.0], 'Independent shops': [3.0, 4.5, 5.5, 7.5, 8.0]}),
                dict(kind='table', title='Drinks sold in coffee shops, 2020',
                     header=['Drink', 'Average price (£)', 'Share of sales (%)'],
                     rows=[['Latte', '3.20', '32'], ['Cappuccino', '3.10', '24'], ['Americano', '2.70', '17'], ['Flat white', '3.30', '15'], ['Tea', '2.20', '12']])],
         features='Both kinds of coffee shop increased in number. Independent shops were more common in 2000 (3,000 compared with 1,500), but chains grew faster, overtook them between 2005 and 2010 and reached 10,000 by 2020, against 8,000 independents. Lattes were the most popular drink (32% of sales), followed by cappuccinos (24%). Flat whites were the most expensive (£3.30) and tea the cheapest (£2.20) and least popular (12%).'),
    dict(kind='mixed', title='Plastic packaging thrown away and recycled',
         lead='The pie chart below shows',
         desc='the types of plastic packaging thrown away by households in the UK in 2022, and the bar chart shows the percentage of each type that was recycled',
         parts=[dict(kind='pie', title='Plastic packaging thrown away, by type',
                     pies={'2022': {'Bottles': 25, 'Pots, tubs and trays': 20, 'Film and bags': 35, 'Other': 20}}),
                dict(kind='bar', title='Percentage of each type recycled, 2022', unit='% recycled',
                     categories=['Bottles', 'Pots, tubs and trays', 'Film and bags', 'Other'],
                     series={'Recycled': [74, 45, 8, 20]})],
         features='Film and bags made up the largest share of plastic packaging waste (35%) but had by far the lowest recycling rate, at only 8%. Bottles, a quarter of the waste, were recycled most successfully (74%), and pots, tubs and trays came second (45%). Taken together, only about a third of all plastic packaging was recycled.'),
    dict(kind='mixed', title='Bus and car journeys in Brighton and Hove',
         lead='The graph below shows',
         desc='the number of bus journeys and car journeys into the city centre in Brighton and Hove between 2005 and 2019, and the pie chart shows the purposes of bus journeys in 2019',
         parts=[dict(kind='line', title='Journeys per year', unit='millions of journeys', x=[2005, 2008, 2011, 2014, 2017, 2019],
                     series={'Bus journeys': [38, 42, 45, 47, 48, 49], 'Car journeys into the centre': [60, 58, 55, 52, 50, 48]}),
                dict(kind='pie', title='Purpose of bus journeys, 2019',
                     pies={'2019': {'Work': 30, 'Shopping': 25, 'Leisure': 20, 'Education': 15, 'Health appointments': 5, 'Other': 5}})],
         features='Bus use rose steadily from 38 to 49 million journeys, while car journeys into the centre fell from 60 to 48 million, so that by 2019 buses carried slightly more people than cars. Travelling to work was the most common purpose of bus journeys (30%), followed by shopping (25%) and leisure (20%), with education accounting for 15%.'),
    # ----------------------------------------------------------------------- maps
    dict(kind='map', title='A village in south-west England',
         desc='a village in the south-west of England in 2000 and today',
         panels={'2000': [('Main road', 0, 3, 10, 1, 'road'), ('Houses', 0, 0, 3, 3, 'building'), ('Village shop', 3, 1, 2, 2, 'building'), ('Post office', 5, 1, 2, 2, 'building'), ('Pub', 7, 1, 2, 2, 'building'), ('Primary school', 0, 4, 3, 2, 'building'), ('Playing field', 0, 6, 3, 2, 'green'), ('Farmland', 4, 4, 6, 4, 'green')],
                  'Today': [('Main road', 0, 3, 10, 1, 'road'), ('Houses', 0, 0, 3, 3, 'building'), ('Shop and café', 3, 1, 2, 2, 'building'), ('Houses', 5, 1, 2, 2, 'building'), ('Pub', 7, 1, 2, 2, 'building'), ('Primary school (extended)', 0, 4, 3, 3, 'building'), ('Playing field', 0, 7, 3, 1, 'green'), ('Housing estate', 4, 4, 4, 4, 'building'), ('Doctors’ surgery', 8, 4, 2, 2, 'building'), ('Car park', 8, 6, 2, 2, 'road')]},
         features='The village has grown considerably, mainly to the south of the main road, where the farmland has been replaced by a housing estate, a doctors’ surgery and a car park. North of the road, the post office has been turned into houses and the village shop now includes a café, while the pub and older houses remain. The primary school has been extended onto part of its playing field.'),
    dict(kind='map', title='A university campus in 2010 and 2025',
         desc='the campus of a university in the Midlands in 2010 and 2025',
         panels={'2010': [('Library', 0, 0, 3, 2, 'building'), ('Lecture halls', 3, 0, 4, 2, 'building'), ('Science labs', 7, 0, 3, 2, 'building'), ('Student halls', 0, 2, 3, 3, 'building'), ('Lawn', 3, 3, 4, 3, 'green'), ('Sports field', 7, 3, 3, 4, 'green'), ('Car park', 0, 5, 3, 2, 'road'), ('Main road', 0, 7, 10, 1, 'road')],
                  '2025': [('Library', 0, 0, 3, 2, 'building'), ('Lecture halls', 3, 0, 4, 2, 'building'), ('Science labs', 7, 0, 3, 2, 'building'), ('Student halls', 0, 2, 3, 3, 'building'), ('Student centre', 3, 3, 2, 3, 'building'), ('Lawn', 5, 3, 2, 3, 'green'), ('New student halls', 7, 3, 3, 4, 'building'), ('Multi-storey car park', 0, 5, 3, 1, 'building'), ('Cycle store', 0, 6, 3, 1, 'building'), ('Bus stop', 4, 6, 3, 1, 'road'), ('Main road', 0, 7, 10, 1, 'road')]},
         features='The campus has become more built-up and less green. The sports field in the east has been replaced by new student halls, and half of the central lawn is now a student centre. The surface car park has become a smaller multi-storey car park with a cycle store beside it, and a bus stop has been added by the main road. The library, lecture halls, science labs and original halls are unchanged.'),
    dict(kind='map', title='Changes to a city park in Scotland',
         desc='a public park in a Scottish city in 1995 and today',
         panels={'1995': [('Open grass', 0, 0, 10, 2, 'green'), ('Tennis courts', 0, 2, 3, 2, 'road'), ('Lake', 3, 2, 4, 3, 'water'), ('Bandstand', 7, 2, 3, 2, 'building'), ('Flower gardens', 0, 4, 3, 3, 'green'), ('Toilets', 3, 5, 2, 2, 'building'), ('Car park', 5, 5, 2, 2, 'road'), ('Woodland', 7, 4, 3, 3, 'green'), ('Main path', 0, 7, 10, 1, 'road')],
                  'Today': [('Open grass', 0, 0, 10, 2, 'green'), ('Children’s play area', 0, 2, 3, 2, 'sand'), ('Lake', 3, 2, 3, 3, 'water'), ('Café', 6, 2, 1, 3, 'building'), ('Outdoor gym', 7, 2, 3, 2, 'sand'), ('Flower gardens', 0, 4, 3, 3, 'green'), ('Toilets', 3, 5, 2, 2, 'building'), ('Car park', 5, 5, 2, 2, 'road'), ('Woodland', 7, 4, 3, 3, 'green'), ('Path and cycle track', 0, 7, 10, 1, 'road')]},
         features='The park has been changed to offer more activities. The tennis courts have been replaced by a children’s play area and the bandstand by an outdoor gym. The lake has been made smaller so that a café could be built on its eastern side, and the main path now includes a cycle track. The open grass, flower gardens, toilets, car park and woodland remain as before.'),
    dict(kind='map', title='The area around a town railway station',
         desc='the area around the railway station in a town in the north of England in 2005 and today',
         panels={'2005': [('Railway line', 0, 0, 10, 1, 'road'), ('Platform', 2, 1, 6, 1, 'building'), ('Car park', 0, 2, 3, 3, 'road'), ('Station building', 3, 2, 4, 2, 'building'), ('Taxi rank', 7, 2, 3, 1, 'road'), ('Station Road', 0, 5, 10, 1, 'road'), ('Empty warehouse', 0, 6, 4, 2, 'building'), ('Shops', 5, 6, 5, 2, 'building')],
                  'Today': [('Railway line', 0, 0, 10, 1, 'road'), ('Longer platform', 0, 1, 10, 1, 'building'), ('Multi-storey car park', 0, 2, 3, 3, 'building'), ('Station building', 3, 2, 4, 2, 'building'), ('Cycle hub', 3, 4, 2, 1, 'building'), ('Bus and taxi interchange', 7, 2, 3, 3, 'road'), ('Station Road', 0, 5, 10, 1, 'road'), ('Flats', 0, 6, 4, 2, 'building'), ('Shops', 5, 6, 5, 2, 'building')]},
         features='The station area has been redeveloped to improve transport links. The platform has been extended along the whole length of the site, the car park has been replaced by a multi-storey car park, and the taxi rank has been enlarged into a bus and taxi interchange. A cycle hub has been added in front of the station building, and the empty warehouse has been replaced by flats. The station building and shops are unchanged.'),
    dict(kind='map', title='Farmland turned into a nature reserve',
         desc='an area of farmland beside a river in eastern England in 1990 and after it became a nature reserve',
         panels={'1990': [('River', 0, 0, 10, 2, 'water'), ('Flood bank', 0, 2, 10, 1, 'sand'), ('Wheat fields', 0, 3, 6, 3, 'green'), ('Farmhouse', 7, 3, 2, 2, 'building'), ('Cattle grazing', 6, 5, 4, 1, 'green'), ('Farm track', 0, 6, 10, 1, 'road'), ('Road', 0, 7, 10, 1, 'road')],
                  'Today': [('River', 0, 0, 10, 2, 'water'), ('Reed beds', 0, 2, 5, 1, 'green'), ('Flood bank', 5, 2, 5, 1, 'sand'), ('Lakes and marsh', 0, 3, 5, 3, 'water'), ('Bird hides', 5, 3, 2, 2, 'building'), ('Visitor centre', 7, 3, 2, 2, 'building'), ('Cattle grazing', 6, 5, 4, 1, 'green'), ('Footpath', 0, 6, 8, 1, 'road'), ('Car park', 8, 6, 2, 1, 'road'), ('Road', 0, 7, 10, 1, 'road')]},
         features='The farmland has been turned into a wetland for wildlife. The wheat fields have been flooded to create lakes and marsh, and the western half of the flood bank has been removed and replaced by reed beds. The farmhouse is now a visitor centre, with bird hides beside it, the farm track has become a footpath, and a small car park has been added. Cattle still graze in the south-east of the site.'),
    dict(kind='map', title='The ground floor of a town library',
         desc='the ground floor of a public library in a town in Wales in 2000 and today',
         panels={'2000': [('Adult fiction', 0, 0, 4, 3, 'building'), ('Reading tables', 4, 0, 2, 3, 'green'), ('Non-fiction', 6, 0, 4, 3, 'building'), ('Reference books', 0, 3, 3, 4, 'building'), ('Newspapers', 3, 3, 4, 2, 'sand'), ('Children’s books', 7, 3, 3, 4, 'building'), ('Reception desk', 3, 5, 4, 1, 'building'), ('Entrance', 4, 7, 2, 1, 'road')],
                  'Today': [('Adult fiction', 0, 0, 4, 3, 'building'), ('Café', 4, 0, 2, 3, 'sand'), ('Non-fiction', 6, 0, 4, 2, 'building'), ('Meeting room', 6, 2, 4, 1, 'building'), ('Computers', 0, 3, 3, 4, 'building'), ('Newspapers and magazines', 3, 3, 4, 2, 'sand'), ('Children’s books', 7, 3, 3, 4, 'building'), ('Self-service machines', 3, 5, 4, 1, 'building'), ('Help desk', 2, 7, 2, 1, 'building'), ('Entrance', 4, 7, 2, 1, 'road')]},
         features='The library has been reorganised to offer more technology and social space. The reference section has been replaced by computers, the reading tables by a café, and the reception desk by self-service machines, with a small help desk now beside the entrance. The non-fiction area has been reduced to make room for a meeting room, and magazines have been added to the newspaper area. Adult fiction and children’s books are unchanged.'),
    # ----------------------------------------------------------------- processes
    dict(kind='process', title='How hard cheese is made',
         desc='the stages in making hard cheese from milk',
         steps=['Milk collected from dairy farms', 'Milk heated to 72°C to kill bacteria', 'Cooled, and starter culture and rennet added', 'Milk sets into a soft curd', 'Curd cut and liquid whey drained off', 'Curd salted and pressed into moulds', 'Cheese left to mature for 3 to 18 months', 'Cut, packed and sent to shops'],
         features='Making hard cheese involves eight stages, from collecting milk to delivering the finished cheese. The milk is first heated and cooled, then set into curd with the help of added cultures and rennet. The curd is cut, drained, salted and pressed, and the longest stage is maturing, which takes between three and eighteen months.'),
    dict(kind='process', title='How a book is published',
         desc='the process of publishing a new book',
         steps=['Author sends a draft to a literary agent', 'Agent offers the book to publishers', 'Publisher agrees a contract with the author', 'Editor and author revise the text', 'Cover designed and pages laid out', 'Books printed and bound', 'Books stored in a warehouse', 'Sent to bookshops and online sellers'],
         features='Publishing a book has eight stages. The first three involve finding a publisher through an agent and agreeing a contract. The book is then prepared: the text is revised and the cover and pages are designed. Finally the books are printed, stored and distributed to shops and online sellers.'),
    dict(kind='process', title='Turning used cooking oil into fuel',
         desc='how used cooking oil is turned into biodiesel',
         steps=['Used oil collected from restaurants', 'Filtered to remove bits of food', 'Heated to remove water', 'Mixed with methanol and a catalyst', 'Left to separate into two layers', 'Glycerine layer removed and sold for soap', 'Biodiesel washed and dried', 'Blended with diesel and sold at petrol stations'],
         features='There are eight stages in turning waste cooking oil into fuel. After collection, the oil is cleaned by filtering and heating, then mixed with methanol and a catalyst. The mixture separates into glycerine, which is sold to make soap, and biodiesel, which is washed, dried and mixed with ordinary diesel before sale.'),
    dict(kind='process', title='From plastic bottles to fleece jackets',
         desc='how used plastic drinks bottles are made into fleece jackets',
         steps=['Bottles collected for recycling', 'Sorted, and caps and labels removed', 'Washed in hot water', 'Shredded into small flakes', 'Flakes melted and pushed through fine holes', 'Fibres stretched and spun into yarn', 'Yarn knitted into fleece fabric', 'Fabric cut and sewn into jackets'],
         features='The process has eight stages and falls into two parts. First the bottles are collected, sorted, cleaned and shredded into flakes. The flakes are then melted and made into fibres, which are spun into yarn, knitted into fleece fabric and finally made into jackets.'),
    dict(kind='process', title='Generating electricity from household waste',
         desc='how electricity is generated from household waste at an energy-from-waste plant',
         steps=['Lorries deliver household waste', 'Waste stored in a large bunker', 'Crane lifts waste into the furnace', 'Waste burned at 850°C', 'Heat turns water into steam', 'Steam drives a turbine to make electricity', 'Ash removed and used in road building', 'Gases cleaned before leaving the chimney'],
         features='The plant turns rubbish into electricity in a series of stages. Waste is delivered, stored and lifted into a furnace, where it is burned at 850°C. The heat produces steam, which drives a turbine to generate electricity. The process also has two by-products: ash, which is reused in road building, and gases, which are cleaned before release.'),
    dict(kind='process', title='How sea arches and stacks form',
         desc='how waves wear away a headland to form caves, arches and stacks',
         steps=['Waves hit a rocky headland', 'Water attacks cracks in the rock', 'Cracks widen into a cave', 'Cave cut right through to form an arch', 'Arch roof weakens and falls into the sea', 'Stack left standing apart from the cliff', 'Stack worn down into a low stump'],
         features='This natural process has seven stages and takes place over a very long time. Waves attack weaknesses in a headland, widening cracks into a cave, which is eventually cut through to make an arch. When the roof of the arch collapses, a separate stack is left, and this is slowly worn down until only a stump remains.'),
]
