"""IELTS General Training Writing Task 1 letters, bank 4.

Original Prepyo situations in the public General Training Task 1 format, in
the shape of the letters in scripts/generate_ielts_general_training.py
(migration 000071): (tone, title, situation, recipient, three bullet points,
opening). Not official, recalled or copied test content.
"""

FORMAL = 'Dear Sir or Madam,'
NAMED = 'Dear ..........,'

LETTERS = [
    # ------------------------------------------------------------------ formal
    ('formal', 'A long delay at the airport',
     'Your flight home from a holiday in Spain was delayed by nine hours, and the airline gave passengers very little information while they waited.',
     'the airline',
     ['give details of your flight', 'describe what happened at the airport', 'say what you would like the airline to do about it'],
     FORMAL),
    ('formal', 'A cancelled train',
     'Your train was cancelled at very short notice last week, and as a result you missed an important appointment.',
     'the train company',
     ['give details of the journey you had booked', 'explain what happened because of the cancellation', 'say what you expect the company to offer you'],
     FORMAL),
    ('formal', 'Volunteering at a music festival',
     'A music festival near your town is looking for volunteers to help over a weekend in July.',
     'the festival organiser',
     ['say which kind of work you are interested in', 'describe any relevant experience you have', 'explain why you would like to volunteer'],
     FORMAL),
    ('formal', 'Overcharged on a mobile phone contract',
     'For the last three months you have been charged more for your mobile phone contract than the amount you agreed when you signed it.',
     'the phone company',
     ['give details of your contract', 'explain the problem with your bills', 'tell the company what action you would like it to take'],
     FORMAL),
    ('formal', 'Early morning roadworks',
     'For the past month, roadworks outside your home have started very early in the morning and have often blocked the entrance to your drive.',
     'the highways department of your local council',
     ['describe the roadworks and when they take place', 'explain how they are affecting you and your family', 'suggest how the problem could be reduced'],
     FORMAL),
    ('formal', 'A bus route that may close',
     'The local council is planning to stop a bus service that many people in your area use every day.',
     'the transport department of your local council',
     ['explain who uses the bus service and why', 'describe what the effects of stopping it would be', 'suggest an alternative to closing the route'],
     FORMAL),
    ('formal', 'Poor service at a birthday meal',
     'You recently went to a restaurant to celebrate a family birthday, but you were very unhappy with the service you received.',
     'the restaurant manager',
     ['give details of your visit', 'explain what went wrong during the meal', 'say how you think the restaurant should respond'],
     FORMAL),
    ('formal', 'A hotel with no record of a booking',
     'You booked a double room at a hotel for two nights, but when you arrived the hotel had no record of your booking.',
     'the hotel manager',
     ['explain what happened when you arrived', 'describe the problems this caused you', 'say what you want the hotel to do now'],
     FORMAL),
    ('formal', 'A full photography course',
     'You would like to join a part-time evening course in photography at a local college, but the college website says that the course is full.',
     'the college admissions office',
     ['say which course you want to join and why', 'describe your experience of photography so far', 'ask whether any other options are available'],
     FORMAL),
    ('formal', 'Ending a gym membership early',
     'You have a twelve-month contract with a gym, but you need to end it early because you are moving to another city for work.',
     'the gym manager',
     ['explain why you need to cancel your membership', 'say when you are moving', 'ask what you need to do to end the contract'],
     FORMAL),
    ('formal', 'Ideas for a public library',
     'Your local library has asked the people who use it for ideas on how to improve its services.',
     'the library manager',
     ['describe how you use the library at the moment', 'explain what you think could be improved', 'suggest a new service the library could offer'],
     FORMAL),
    ('formal', 'A supermarket on a playing field',
     'Your local newspaper has reported that a large supermarket may be built on a playing field near your home.',
     'the editor of the newspaper',
     ['explain how the playing field is used at present', 'give your opinion of the plan', 'suggest where the supermarket could be built instead'],
     FORMAL),
    ('formal', 'Asking for work experience',
     'You are interested in a career in architecture and would like to gain some work experience before you apply to university.',
     'an architecture firm in your area',
     ['explain who you are and why you are writing', 'describe your studies and interests', 'say when you are available and for how long'],
     FORMAL),
    ('formal', 'A package holiday that disappointed',
     'You recently went on a package holiday, but the accommodation was very different from the description in the travel company’s brochure.',
     'the travel company',
     ['give details of the holiday you booked', 'explain how the accommodation was different from the description', 'say what compensation you think is fair'],
     FORMAL),
    ('formal', 'Nominating someone for a community award',
     'A national organisation gives an award each year to people who have done valuable work in their local community. You would like to nominate someone you know.',
     'the organisation',
     ['describe the person you are nominating', 'explain what they have done for the community', 'say why you think they deserve the award'],
     FORMAL),
    ('formal', 'A present that could not be exchanged',
     'You were given a jumper as a present, but it was the wrong size. When you took it back to the shop, the assistant refused to exchange it.',
     'the manager of the shop',
     ['explain why you went to the shop', 'describe what happened when you asked for an exchange', 'say what you would like the shop to do'],
     FORMAL),
    ('formal', 'Hiring a room for a club event',
     'You are organising an event for a local club and would like to hire a room at a community centre.',
     'the manager of the community centre',
     ['explain what the event is and when it will take place', 'say what you will need on the day', 'ask about the cost and any rules you should know about'],
     FORMAL),
    # ------------------------------------------------------------- semi-formal
    ('semi-formal', 'Damp and mould in a bedroom',
     'You rent a flat, and over the winter there has been a problem with damp and mould in the main bedroom.',
     'your landlord',
     ['describe the problem and when it started', 'explain how it is affecting you and your belongings', 'say what you would like your landlord to arrange'],
     NAMED),
    ('semi-formal', 'Time off to prepare for exams',
     'You work full-time and are also studying for a part-time qualification. You need some time off work to prepare for your final exams.',
     'your line manager',
     ['give details of the qualification you are taking', 'explain how much time off you need and when', 'suggest how your work could be covered while you are away'],
     NAMED),
    ('semi-formal', 'Rubbish bins left on the pavement',
     'The people who live next door to you often leave their rubbish bins on the pavement for several days after they have been emptied.',
     'your neighbours',
     ['explain why you are writing', 'describe the problems this causes', 'suggest a solution that would suit everyone'],
     NAMED),
    ('semi-formal', 'Asking a former teacher for a reference',
     'You are applying for a new job and would like one of your former teachers to write a reference for you.',
     'your former teacher',
     ['remind the teacher who you are and when they taught you', 'give details of the job you are applying for', 'explain why you have asked them for a reference'],
     NAMED),
    ('semi-formal', 'A leaving party for a colleague',
     'A colleague who has worked in your department for many years is leaving the company next month.',
     'the head of your department',
     ['explain why you are writing', 'describe what you would like to organise for your colleague', 'ask for permission and any help the department could give'],
     NAMED),
    ('semi-formal', 'Missing a week of classes',
     'You are taking a course at a language school, and you will have to miss a week of classes next month.',
     'your course tutor',
     ['explain why you will miss the classes', 'ask what you should do to catch up', 'say how you will keep up with your studies while you are away'],
     NAMED),
    ('semi-formal', 'A deposit that has not been returned',
     'You moved out of a rented flat two months ago, but the owner has still not returned your deposit.',
     'your former landlord',
     ['remind them when you left the flat and what condition it was in', 'explain why you need the money now', 'ask them to return the deposit by a certain date'],
     NAMED),
    ('semi-formal', 'A place on a training course',
     'Your company is offering some staff the chance to attend a training course, and you would like to be chosen.',
     'your supervisor',
     ['say which course you would like to attend', 'explain how it would help you in your job', 'describe how you would share what you learn with colleagues'],
     NAMED),
    ('semi-formal', 'A school trip and a food allergy',
     'Your son’s class is going on a three-day school trip next month, and he has a food allergy.',
     'your son’s class teacher',
     ['explain why you are writing', 'describe the allergy and what should be done if there is a problem', 'ask about the meals that will be provided on the trip'],
     NAMED),
    ('semi-formal', 'A tree blocking the light',
     'A large tree in the garden next to yours is blocking the light to your kitchen, and its leaves are filling your gutters.',
     'the owner of the house next door',
     ['describe the problem', 'explain what effect it is having on your home', 'suggest what could be done and offer to share the cost'],
     NAMED),
    ('semi-formal', 'Moving to a different team',
     'You would like to move to a different team within the company you work for.',
     'the human resources manager',
     ['say which team you would like to join', 'explain why you want to move', 'describe the skills you would bring to the team'],
     NAMED),
    ('semi-formal', 'Thanking a host family',
     'Last summer you spent a month living with a family in the UK while you were studying English.',
     'the family you stayed with',
     ['thank them for having you in their home', 'describe what you enjoyed most about your stay', 'tell them what you have been doing since you returned home'],
     NAMED),
    ('semi-formal', 'Too much homework',
     'Your daughter has recently been given much more homework than usual, and it is affecting her sleep and her other activities.',
     'the headteacher of your daughter’s school',
     ['explain why you are writing', 'describe how the homework is affecting your daughter', 'suggest what the school could do'],
     NAMED),
    ('semi-formal', 'Damaging a tutor’s book',
     'Your college tutor lent you a valuable book several months ago, and you have accidentally damaged it.',
     'your tutor',
     ['apologise for keeping the book for so long', 'explain how the book was damaged', 'offer to put the situation right'],
     NAMED),
    ('semi-formal', 'A lift that keeps breaking down',
     'You live in a block of flats where the lift has broken down several times in the past month.',
     'the manager of your building',
     ['describe the problem with the lift', 'explain how it affects the people who live there', 'ask for the problem to be dealt with quickly'],
     NAMED),
    ('semi-formal', 'Losing a parking space at work',
     'The car park at your workplace is being made smaller, and you have been told you will no longer have a parking space.',
     'the facilities manager at your workplace',
     ['explain why you need a parking space', 'describe the difficulties this change will cause you', 'propose a solution'],
     NAMED),
    ('semi-formal', 'Helping at a summer fair',
     'Your local residents’ association is holding a summer fair and is looking for people to help.',
     'the chair of the residents’ association',
     ['say how you would like to help', 'describe any relevant skills or experience', 'ask for more information about the fair'],
     NAMED),
    # ---------------------------------------------------------------- informal
    ('informal', 'Where to go on holiday',
     'A friend is planning a holiday in your country and has asked you where to go.',
     'your friend',
     ['recommend a place to visit and say why', 'describe what your friend can do there', 'give some advice about travelling around'],
     NAMED),
    ('informal', 'A cousin’s new job',
     'Your cousin has just got a new job in another city.',
     'your cousin',
     ['congratulate your cousin on the new job', 'ask some questions about the job', 'offer to help with the move'],
     NAMED),
    ('informal', 'A borrowed camera',
     'You borrowed a friend’s camera for a trip, and it was damaged while you were away.',
     'your friend',
     ['explain what happened to the camera', 'tell your friend how you feel about it', 'say what you will do to replace or repair it'],
     NAMED),
    ('informal', 'A birthday present',
     'A friend sent you a present for your birthday.',
     'your friend',
     ['tell your friend how much you like the present', 'explain how you will use it', 'describe how you celebrated your birthday'],
     NAMED),
    ('informal', 'A school reunion',
     'You and some old friends from school have decided to meet up again after ten years.',
     'an old school friend',
     ['explain the plans for the reunion', 'ask your friend to help with part of the organisation', 'tell your friend what you have been doing since you left school'],
     NAMED),
    ('informal', 'A new flat',
     'You have recently moved to a new flat in a different part of the city.',
     'a friend who lives abroad',
     ['describe your new flat', 'explain why you decided to move', 'invite your friend to come and stay'],
     NAMED),
    ('informal', 'Cancelling a weekend visit',
     'You had arranged to visit a friend for the weekend, but now you are unable to go.',
     'your friend',
     ['apologise and explain why you cannot come', 'suggest another date for the visit', 'tell your friend about something you are looking forward to doing together'],
     NAMED),
    ('informal', 'Learning to drive',
     'Your younger brother is about to start driving lessons and has asked for your advice.',
     'your brother',
     ['tell him about your own experience of learning to drive', 'give him some advice about lessons and the test', 'offer to help him practise'],
     NAMED),
    ('informal', 'A new hobby',
     'You have recently taken up a new hobby.',
     'a friend',
     ['describe the hobby', 'explain how you got started', 'encourage your friend to try it too'],
     NAMED),
    ('informal', 'Looking after a cat',
     'You are going away for two weeks and would like a friend to look after your cat.',
     'your friend',
     ['ask your friend if they could look after the cat', 'explain what they would need to do each day', 'tell them how you will thank them'],
     NAMED),
    ('informal', 'A concert your friend missed',
     'You recently went to a concert by a band that you and a friend both like, but your friend could not come.',
     'your friend',
     ['describe the concert', 'tell your friend about the best moment', 'suggest another event you could go to together'],
     NAMED),
    ('informal', 'Comments on a friend’s CV',
     'A friend has asked you to look at their CV before they apply for a job.',
     'your friend',
     ['give your opinion of the CV', 'suggest some changes', 'wish your friend luck and offer further help'],
     NAMED),
    ('informal', 'A cycling race in your town',
     'Your town is hosting a big cycling race next month.',
     'a friend who likes cycling',
     ['invite your friend to come and watch the race', 'describe the event', 'explain the arrangements for staying with you'],
     NAMED),
    ('informal', 'An invitation to a barbecue',
     'You are having a barbecue at your home to celebrate finishing your exams.',
     'a friend from your course',
     ['invite your friend to the barbecue', 'give details of the day', 'ask your friend to bring something'],
     NAMED),
    ('informal', 'Starting university in your town',
     'A friend is about to start university in the town where you live.',
     'your friend',
     ['offer to help your friend settle in', 'describe the best parts of the town for students', 'tell your friend about some things to avoid'],
     NAMED),
    ('informal', 'Getting back in touch',
     'You have not been in touch with a friend for over a year.',
     'a friend you have not seen for some time',
     ['apologise for not writing sooner', 'tell your friend your main news', 'suggest meeting up soon'],
     NAMED),
]
