"""Passages 6-10 for IELTS Academic Reading Bank Batch 3."""

PASSAGES_6_10 = [
    {
        "id_slug": "glaciers",
        "title": "The Anatomy of Glaciers: Sentinels of Global Climate",
        "subtitle": "The formation, dynamics, and hydrological significance of mountain ice",
        "topic": "Glaciology and physical geography",
        "paragraphs": [
            {
                "label": "A",
                "text": "Occupying roughly ten percent of the planet's total land area, glaciers represent some of the most dynamic physical structures on Earth. While they appear from a distance to be static masses of frozen snow, glaciers are in truth colossal rivers of ice that deform, flow, and remodel terrestrial topography over geological epochs. The metamorphosis from fragile winter snowflake to dense glacial ice is a protracted physical process spanning decades or centuries. In high-altitude alpine regions and polar ice sheets, perennial snow accumulates in sheltered hollows where summer temperatures fail to induce complete melting. As successive seasonal snowfalls pile up, the weight of overlying layers exerts intense pressure on the bottom strata, expelling trapped atmospheric air. The loose crystals gradually recrystallize into a granular intermediate state known as firn, which eventually coalesces under extreme lithostatic compression into solid, blue glacial ice characterized by interlocking crystal lattices."
            },
            {
                "label": "B",
                "text": "Once a mass of ice reaches a critical thickness of approximately thirty metres, its sheer mass overcomes internal friction, initiating downhill movement under the influence of gravity. This displacement occurs through two distinct mechanical regimes: internal plastic deformation and basal sliding. In the colder, deeper zones of the glacier, the ice behaves as a high-viscosity plastic fluid; under sustained differential pressure, individual microscopic ice crystals slip along internal cleavage planes, allowing the entire mass to creep slowly forward without fracturing. Conversely, the brittle upper fifty metres of the glacier cannot deform plastically, leading to the formation of gaping crevasses as the ice stretches over uneven bedrock. At the glacier's base, meltwater generated by geothermal heat and frictional pressure acts as a pressurized hydraulic lubricant, facilitating basal sliding wherein the entire frozen monolith glides smoothly across the underlying bedrock."
            },
            {
                "label": "C",
                "text": "A glacier functions as an open thermodynamic system governed by an annual mass balance—the algebraic difference between accumulation and ablation. The upper, high-elevation sector where snowfall exceeds annual melting is designated the accumulation zone. Downslope, separated by an equilibrium line where annual mass gain exactly equals mass loss, lies the ablation zone. Here, the glacier sheds mass through sublimation, evaporation, meltwater runoff, and, where ice margins meet open water, the dramatic calving of icebergs. The position of the terminus (the glacier's front snout) serves as a sensitive visual barometer of regional climate trends: when accumulation outpaces ablation over a multi-year cycle, the snout advances down the valley; conversely, when ablation dominates, the terminus recedes upslope."
            },
            {
                "label": "D",
                "text": "The ecological and hydrological significance of alpine glaciers is immense, earning them the moniker 'natural water towers' of the planet. Throughout the arid summer months, when seasonal rainfall is negligible and lowland river tributaries run dry, glacial meltwater provides a dependable baseline discharge for major river basins across the Andes, the Alps, and the Himalayas. Billions of people living downstream depend directly upon this regulated alpine meltwater for drinking reserves, agricultural irrigation, and hydroelectric power generation. Furthermore, glaciers act as natural temperature regulators in mountainous regions, reflecting vast quantities of incoming solar radiation back into space through their high surface albedo."
            },
            {
                "label": "E",
                "text": "In the modern era of glaciology, field scientists rely extensively on spaceborne remote sensing technologies to monitor ice dynamics across remote mountain ranges. Satellite radar altimetry and optical stereoscopy measure millimeter-scale changes in glacier elevation, while orbital gravimetry missions, such as NASA's GRACE satellites, calculate mass fluctuations by detecting minute variations in Earth's gravitational field over ice sheets. These orbital observations reveal that the overwhelming majority of alpine glaciers worldwide are currently experiencing rapid, unprecedented mass deficits, with thinning rates accelerating over recent decades in response to atmospheric and oceanic warming."
            },
            {
                "label": "F",
                "text": "The accelerating retreat of mountain glaciers carries profound risks for surrounding mountain communities. As glaciers recede rapidly, meltwater often collects behind unstable dams of loose glacial debris and morainic boulders, creating perilous proglacial lakes. If an avalanche, rockfall, or earthquake breaches these fragile natural dams, it triggers a catastrophic glacial lake outburst flood (GLOF), unleashing millions of cubic metres of water and boulders on downstream villages with virtually no advance warning. Beyond these acute disasters, the long-term depletion of glacier reserves threatens chronic water insecurity across major agricultural belts once peak water is passed. Preserving mountain ecosystems and constructing early-warning flood infrastructure represents one of the most pressing civil engineering challenges of the twenty-first century."
            }
        ],
        "mcq_single": [
            {
                "prompt": "According to paragraph A, what intermediate stage occurs before snow becomes dense glacial ice?",
                "options": [
                    {"id": "A", "text": "It turns into crystalline permafrost"},
                    {"id": "B", "text": "It compresses into a granular material called firn"},
                    {"id": "C", "text": "It dissolves into high-pressure mineral slush"},
                    {"id": "D", "text": "It evaporates into airborne vapor crystals"}
                ],
                "key": "B",
                "explanation": "Paragraph A states that loose crystals recrystallize into a granular intermediate state known as firn before coalescing into solid ice."
            },
            {
                "prompt": "What role does water play at the bottom of a glacier, according to paragraph B?",
                "options": [
                    {"id": "A", "text": "It freezes instantly to lock the glacier against bedrock"},
                    {"id": "B", "text": "It erodes subterranean caverns that vent volcanic gases"},
                    {"id": "C", "text": "It acts as a pressurized lubricant that helps the glacier slide"},
                    {"id": "D", "text": "It cools the bedrock to prevent geothermal melting"}
                ],
                "key": "C",
                "explanation": "Paragraph B states that meltwater acts as a pressurized hydraulic lubricant facilitating basal sliding across bedrock."
            },
            {
                "prompt": "According to paragraph F, what causes a glacial lake outburst flood (GLOF)?",
                "options": [
                    {"id": "A", "text": "The failure of a loose moraine dam holding back meltwater"},
                    {"id": "B", "text": "The sudden collapse of an artificial hydroelectric reservoir"},
                    {"id": "C", "text": "Heavy snowfall blocking mountain drainage pipes"},
                    {"id": "D", "text": "Underground volcanic eruptions boiling glacial ice"}
                ],
                "key": "A",
                "explanation": "Paragraph F explains that meltwater collects behind unstable dams of morainic debris, and a breach triggers a catastrophic GLOF."
            }
        ],
        "mcq_multiple": [
            {
                "prompt": "Which TWO downstream benefits of glacial meltwater are mentioned in paragraph D?",
                "options": [
                    {"id": "A", "text": "Providing reliable water for crop irrigation during dry months"},
                    {"id": "B", "text": "Powering hydroelectric generation plants"},
                    {"id": "C", "text": "Allowing commercial cargo ships to travel upstream"},
                    {"id": "D", "text": "Extracting geothermal energy for central heating"},
                    {"id": "E", "text": "Preventing saltwater from entering mountain springs"}
                ],
                "keys": ["A", "B"],
                "explanation": "Paragraph D specifically cites agricultural irrigation (A) and hydroelectric power generation (B)."
            },
            {
                "prompt": "Which TWO satellite technologies are used to monitor glacier mass and thickness in paragraph E?",
                "options": [
                    {"id": "A", "text": "Satellite radar altimetry measuring elevation changes"},
                    {"id": "B", "text": "Infrared cameras photographing nocturnal animal migration"},
                    {"id": "C", "text": "Orbital gravimetry detecting gravitational variations over ice"},
                    {"id": "D", "text": "Underwater sonar beams mapping sunken moraines"},
                    {"id": "E", "text": "Radio telescopes tracking celestial cosmic radiation"}
                ],
                "keys": ["A", "C"],
                "explanation": "Paragraph E names satellite radar altimetry measuring elevation changes (A) and orbital gravimetry missions detecting gravitational field variations (C)."
            }
        ],
        "tfng": [
            {
                "statement": "Glaciers cover approximately twenty-five percent of the Earth's total land area.",
                "key": "FALSE",
                "explanation": "Paragraph A states that glaciers occupy roughly ten percent of the planet's total land area."
            },
            {
                "statement": "Crevasses form in the upper layers of a glacier because brittle surface ice cannot deform plastically.",
                "key": "TRUE",
                "explanation": "Paragraph B states that the brittle upper fifty metres cannot deform plastically, leading to gaping crevasses."
            },
            {
                "statement": "Calving occurs exclusively in freshwater alpine lakes.",
                "key": "FALSE",
                "explanation": "Paragraph C describes calving occurring where ice margins meet open water generally, without limiting it to freshwater alpine lakes."
            },
            {
                "statement": "The GRACE satellites were designed by a joint consortium of private mining corporations.",
                "key": "NOT_GIVEN",
                "explanation": "Paragraph E mentions NASA's GRACE satellites, but gives no information regarding mining corporations."
            },
            {
                "statement": "Unstable natural moraine dams can hold back millions of cubic metres of meltwater.",
                "key": "TRUE",
                "explanation": "Paragraph F notes that breaching fragile natural dams unleashes millions of cubic metres of water."
            }
        ],
        "ynng": [
            {
                "statement": "Viewing glaciers as completely motionless structures fails to recognize their dynamic physical nature.",
                "key": "YES",
                "explanation": "Paragraph A argues that while they appear static from a distance, they are in truth colossal moving rivers of ice."
            },
            {
                "statement": "The equilibrium line on a glacier remains permanently at the exact same elevation each year.",
                "key": "NO",
                "explanation": "Paragraph C explains that the mass balance varies annually with climate, directly altering accumulation and ablation boundaries."
            },
            {
                "statement": "Glacial ice provides useful regional climate cooling by reflecting solar rays back towards space.",
                "key": "YES",
                "explanation": "Paragraph D states that glaciers act as natural temperature regulators, reflecting incoming solar radiation through high albedo."
            },
            {
                "statement": "Satellite observations provide sufficient data to accurately predict the exact date of future avalanches.",
                "key": "NOT_GIVEN",
                "explanation": "Paragraph E describes satellite monitoring of elevation and mass, but does not claim it can predict the exact date of avalanches."
            },
            {
                "statement": "Vulnerable downstream populations need engineered early-warning mechanisms to safeguard against outburst floods.",
                "key": "YES",
                "explanation": "Paragraph F concludes that constructing early-warning flood infrastructure represents one of the most pressing challenges."
            }
        ],
        "matching": [
            {
                "prompt": "the step in glacier creation where snow crystals form an intermediate granular substance",
                "key": "A",
                "evidence": "loose crystals gradually recrystallize into a granular intermediate state known as firn",
                "explanation": "Paragraph A describes the formation of firn."
            },
            {
                "prompt": "an explanation of how basal meltwater assists the movement of a glacier",
                "key": "B",
                "evidence": "meltwater generated by geothermal heat and frictional pressure acts as a pressurized hydraulic lubricant, facilitating basal sliding",
                "explanation": "Paragraph B outlines how meltwater lubricates basal sliding."
            },
            {
                "prompt": "the boundary dividing the zone of net mass gain from the zone of net mass loss",
                "key": "C",
                "evidence": "separated by an equilibrium line where annual mass gain exactly equals mass loss",
                "explanation": "Paragraph C defines the equilibrium line."
            },
            {
                "prompt": "a term highlighting the essential water storage role performed by alpine ice",
                "key": "D",
                "evidence": "earning them the moniker 'natural water towers' of the planet",
                "explanation": "Paragraph D introduces the 'natural water towers' phrase."
            },
            {
                "prompt": "the catastrophic flood unleashed when a natural moraine barrier breaks",
                "key": "F",
                "evidence": "triggers a catastrophic glacial lake outburst flood (GLOF), unleashing millions of cubic metres of water and boulders",
                "explanation": "Paragraph F discusses glacial lake outburst floods."
            }
        ],
        "completion": [
            {
                "prompt": "Over decades, layers of snow compress into a granular substance termed ________.",
                "answer": "firn",
                "explanation": "Paragraph A names this intermediate state firn."
            },
            {
                "prompt": "Stretching of brittle ice over uneven ground creates deep cracks called ________.",
                "answer": "crevasses",
                "explanation": "Paragraph B states stretching causes the formation of gaping crevasses."
            },
            {
                "prompt": "The lower section of a glacier where melting and evaporation take place is the ________ zone.",
                "answer": "ablation",
                "explanation": "Paragraph C designates this lower area the ablation zone."
            },
            {
                "prompt": "Glaciers reflect large amounts of solar heat due to their high surface ________.",
                "answer": "albedo",
                "explanation": "Paragraph D attributes solar reflection to high surface albedo."
            },
            {
                "prompt": "Orbital satellites measure ice mass variations by detecting subtle differences in the planet's ________ field.",
                "answer": "gravitational",
                "explanation": "Paragraph E notes satellites detect minute variations in Earth's gravitational field."
            }
        ]
    },
    {
        "id_slug": "biomimicry",
        "title": "Borrowed from Biology: The Rise of Biomimetic Architecture",
        "subtitle": "How structural and climatic adaptations in nature inspire human building design",
        "topic": "Architecture and engineering",
        "paragraphs": [
            {
                "label": "A",
                "text": "For millennia, human builders derived architectural inspiration from nature primarily through ornamental imitation: carving lotus petals into stone columns, sculpting acanthus leaves upon classical capitals, or painting floral motifs along palace ceilings. While visually striking, these artistic tributes were superficial, borrowing the decorative forms of the natural world without engaging with its functional mechanics. Over the past three decades, however, a profound philosophical shift has taken root across the architectural discipline. Popularized by naturalists and sustainable designers like Janine Benyus, biomimetic architecture treats nature not as an aesthetic catalogue, but as an exhaustive database of proven engineering solutions. Having undergone 3.8 billion years of evolutionary refinement, biological organisms have developed exquisite mechanisms to regulate temperature, maximize structural strength, and conserve vital resources while consuming minimal energy."
            },
            {
                "label": "B",
                "text": "One of the most celebrated real-world demonstrations of biomimetic engineering is the Eastgate Centre, an expansive commercial and retail complex constructed in Harare, Zimbabwe. Designed by architect Mick Pearce in collaboration with engineers from Arup, the building operates without any conventional mechanical air conditioning systems, despite experiencing severe equatorial temperature swings. Pearce drew inspiration from the towering earthen mounds built by macrotermes termites. These social insects maintain a constant internal nursery temperature of thirty degrees Celsius while ambient exterior temperatures fluctuate from freezing at night to over forty degrees during the day. The termites achieve this homeostatic feat through a network of vertical flues and convective air channels. Mimicking this principle, the Eastgate Centre utilizes concrete thermal mass to absorb heat during the day, which is systematically vented out through high chimneys at night by natural convective currents, consuming thirty-five percent less energy than conventional office blocks in Harare."
            },
            {
                "label": "C",
                "text": "In addition to thermal regulation, evolutionary biology provides remarkable templates for structural optimization that conserve costly building materials. Conventional structural engineering typically relies on uniform geometric beams and monolithic concrete pillars, resulting in substantial material redundancy. In contrast, natural structures such as mammalian bones and old-growth trees exhibit adaptive growth: they deposit structural tissue strictly along lines of mechanical stress while eliminating material from unstressed voids, following what biomechanists call the axiom of uniform stress. Modern structural software now replicates this biological efficiency through topological optimization algorithms. By iteratively trimming redundant material from digital structural models, engineers can design complex, bone-like steel joints and floor slabs that reduce overall building weight by up to forty percent without sacrificing load-bearing safety."
            },
            {
                "label": "D",
                "text": "Biomimetic principles are equally revolutionizing the external envelopes and facades of contemporary buildings. The micro-textured surface of the sacred lotus leaf provides a quintessential model for building maintenance: despite thriving in muddy tropical ponds, the leaf remains immaculately clean because microscopic wax papillations minimize the contact area between water droplets and the surface. Raindrops ball up and roll effortlessly across the foliage, washing away adhered dirt particles. Paint and glass manufacturers have synthesized facade coatings that recreate this hydrophobic 'lotus effect'. Exterior building envelopes treated with these nano-textured coatings shed grime automatically during ordinary rainstorms, dramatically curtailing municipal water consumption and eliminating the need for caustic chemical detergents on high-rise facades."
            },
            {
                "label": "E",
                "text": "In hyper-arid regions grappling with acute water scarcity, architects are looking to desert fauna for passive moisture harvesting systems. The fog-basking beetle of the Namib Desert survives in one of the driest habitats on Earth by condensing atmospheric fog on its specialized carapace. The beetle's shell features an alternating array of microscopic hydrophilic peaks that attract suspended water droplets and waxy hydrophobic troughs that funnel accumulated moisture into the beetle's mouth. Environmental engineers have translated this dual-texture architecture into large-scale fog-harvesting mesh netting and facade panels. Deployed in coastal desert communities in Chile and Morocco, these biomimetic collectors harvest hundreds of litres of clean potable water daily directly from coastal sea fog without using electrical pumps, supplying smallholder farms and domestic reserves."
            },
            {
                "label": "F",
                "text": "Despite these compelling case studies, integrating biomimicry into mainstream construction remains challenging. Biological systems solve multi-variable physical problems holistically, whereas human construction industries are fragmented across specialized subcontractors and rigid municipal building codes. Furthermore, replicating fine biological microstructures—such as nano-scale hydrophobic textures or organic cellular lattices—demands advanced digital fabrication tools, including large-scale three-dimensional printing, which remain capital-intensive. The ultimate promise of biomimetic architecture lies in bridging this gap: moving beyond isolated demonstration projects toward systemic industrial design that respects natural ecological boundaries and minimizes humanity's planetary footprint in an era of rapid climate change."
            }
        ],
        "mcq_single": [
            {
                "prompt": "According to paragraph A, how does modern biomimetic architecture differ from historic nature-inspired architecture?",
                "options": [
                    {"id": "A", "text": "It constructs buildings using exclusively wood and stone"},
                    {"id": "B", "text": "It replicates functional engineering principles rather than decorative shapes"},
                    {"id": "C", "text": "It focuses solely on building in wilderness locations"},
                    {"id": "D", "text": "It requires structures to be hidden underground"}
                ],
                "key": "B",
                "explanation": "Paragraph A contrasts ornamental imitation with treating nature as a database of proven functional engineering solutions."
            },
            {
                "prompt": "What natural structure served as the design model for Harare's Eastgate Centre (paragraph B)?",
                "options": [
                    {"id": "A", "text": "Hollow bird bones"},
                    {"id": "B", "text": "Termite mounds with convective channels"},
                    {"id": "C", "text": "Subterranean beaver dams"},
                    {"id": "D", "text": "Honeycomb bee structures"}
                ],
                "key": "B",
                "explanation": "Paragraph B states Pearce drew inspiration from mounds built by termites containing vertical convective channels."
            },
            {
                "prompt": "According to paragraph D, what happens when rain lands on a surface exhibiting the 'lotus effect'?",
                "options": [
                    {"id": "A", "text": "Water is immediately absorbed into deep structural pores"},
                    {"id": "B", "text": "Droplets ball up and roll off, carrying dirt away with them"},
                    {"id": "C", "text": "Water evaporates instantly due to stored chemical heat"},
                    {"id": "D", "text": "Droplets trigger a chemical reaction that seals surface fractures"}
                ],
                "key": "B",
                "explanation": "Paragraph D states raindrops ball up and roll effortlessly across the surface, washing away adhered dirt particles."
            }
        ],
        "mcq_multiple": [
            {
                "prompt": "Which TWO benefits of topological optimization in building construction are highlighted in paragraph C?",
                "options": [
                    {"id": "A", "text": "Eliminating redundant material from low-stress zones"},
                    {"id": "B", "text": "Significantly reducing the total physical weight of building components"},
                    {"id": "C", "text": "Allowing buildings to heal cracks automatically without human labor"},
                    {"id": "D", "text": "Increasing the electrical conductivity of steel structures"},
                    {"id": "E", "text": "Eliminating the need for architectural construction permits"}
                ],
                "keys": ["A", "B"],
                "explanation": "Paragraph C notes eliminating material from unstressed voids (A) and reducing overall building weight by up to forty percent (B)."
            },
            {
                "prompt": "Which TWO characteristics of the Namib Desert beetle's shell enable fog harvesting (paragraph E)?",
                "options": [
                    {"id": "A", "text": "Hydrophilic peaks that capture airborne moisture droplets"},
                    {"id": "B", "text": "Electric sensors that detect approaching fog banks"},
                    {"id": "C", "text": "Hydrophobic troughs that direct collected water towards the mouth"},
                    {"id": "D", "text": "Pores that emit warm vapor to condense clouds"},
                    {"id": "E", "text": "Reflective wings that prevent all evaporation"}
                ],
                "keys": ["A", "C"],
                "explanation": "Paragraph E describes microscopic hydrophilic peaks that attract water droplets (A) and waxy hydrophobic troughs that funnel moisture (C)."
            }
        ],
        "tfng": [
            {
                "statement": "Ancient Greek columns decorated with acanthus leaf motifs were functional thermal regulators.",
                "key": "FALSE",
                "explanation": "Paragraph A states early tributes were superficial ornamental imitations that did not engage with functional mechanics."
            },
            {
                "statement": "The Eastgate Centre in Harare has no conventional mechanical air conditioning system.",
                "key": "TRUE",
                "explanation": "Paragraph B states the building operates without any conventional mechanical air conditioning systems."
            },
            {
                "statement": "Topological optimization algorithms were originally designed by naval submarine constructors.",
                "key": "NOT_GIVEN",
                "explanation": "Paragraph C explains how modern structural software replicates biological efficiency, but says nothing about submarine constructors."
            },
            {
                "statement": "Lotus leaves remain clean because their surface is entirely smooth under a microscope.",
                "key": "FALSE",
                "explanation": "Paragraph D states the surface is not smooth, but possesses microscopic wax papillations that minimize water contact."
            },
            {
                "statement": "Fog-harvesting mesh collectors in Morocco require diesel generators to operate pumps.",
                "key": "FALSE",
                "explanation": "Paragraph E states collectors harvest hundreds of litres of clean potable water without using electrical pumps."
            }
        ],
        "ynng": [
            {
                "statement": "Nature's evolutionary history offers proven answers to many complex engineering dilemmas.",
                "key": "YES",
                "explanation": "Paragraph A argues that nature is an exhaustive database of proven engineering solutions refined over 3.8 billion years."
            },
            {
                "statement": "The writer regards uniform steel beams as the most economical use of building material.",
                "key": "NO",
                "explanation": "Paragraph C contrasts the material redundancy of uniform beams with nature's economical, stress-aligned growth."
            },
            {
                "statement": "Self-cleaning building coatings eliminate the necessity for hazardous washing chemicals.",
                "key": "YES",
                "explanation": "Paragraph D states coatings shed grime automatically, eliminating the need for caustic chemical detergents."
            },
            {
                "statement": "Biomimetic mesh systems can harvest enough water to supply entire industrialized mega-cities.",
                "key": "NOT_GIVEN",
                "explanation": "Paragraph E mentions supplying hundreds of litres daily to desert communities, without claiming it can supply entire mega-cities."
            },
            {
                "statement": "Conventional construction regulations currently make it harder to adopt biological design solutions.",
                "key": "YES",
                "explanation": "Paragraph F notes that human construction industries are fragmented across specialized subcontractors and rigid municipal building codes."
            }
        ],
        "matching": [
            {
                "prompt": "a comparison contrasting superficial decorative imitation with functional biological design",
                "key": "A",
                "evidence": "these artistic tributes were superficial, borrowing the decorative forms of the natural world without engaging with its functional mechanics",
                "explanation": "Paragraph A contrasts ornamental motifs with functional mechanics."
            },
            {
                "prompt": "a commercial building that vents daytime heat through high chimneys using convection",
                "key": "B",
                "evidence": "utilizes concrete thermal mass to absorb heat during the day, which is systematically vented out through high chimneys at night by natural convective currents",
                "explanation": "Paragraph B explains Harare's Eastgate Centre."
            },
            {
                "prompt": "how modern software trims redundant materials from structural joints like bone growth",
                "key": "C",
                "evidence": "Modern structural software now replicates this biological efficiency through topological optimization algorithms. By iteratively trimming redundant material",
                "explanation": "Paragraph C details topological optimization."
            },
            {
                "prompt": "the microscopic plant adaptation that repels water and removes surface grime",
                "key": "D",
                "evidence": "microscopic wax papillations minimize the contact area between water droplets and the surface. Raindrops ball up and roll effortlessly across the foliage, washing away adhered dirt",
                "explanation": "Paragraph D describes the lotus leaf effect."
            },
            {
                "prompt": "the manufacturing hurdles associated with reproducing biological microstructures at scale",
                "key": "F",
                "evidence": "replicating fine biological microstructures—such as nano-scale hydrophobic textures or organic cellular lattices—demands advanced digital fabrication tools, including large-scale three-dimensional printing, which remain capital-intensive",
                "explanation": "Paragraph F outlines advanced manufacturing hurdles."
            }
        ],
        "completion": [
            {
                "prompt": "The natural world possesses engineering solutions refined over billions of years of biological ________.",
                "answer": "evolutionary",
                "explanation": "Paragraph A mentions 3.8 billion years of evolutionary refinement."
            },
            {
                "prompt": "Termites circulate cool air through mounds using a system of vertical ________.",
                "answer": "flues",
                "explanation": "Paragraph B states termites use a network of vertical flues and convective air channels."
            },
            {
                "prompt": "Architectural software uses algorithms for topological ________ to cut structural weight.",
                "answer": "optimization",
                "explanation": "Paragraph C mentions topological optimization algorithms."
            },
            {
                "prompt": "Lotus leaves shed dirt effortlessly because of their water-repelling ________ surfaces.",
                "answer": "hydrophobic",
                "explanation": "Paragraph D refers to this hydrophobic lotus effect."
            },
            {
                "prompt": "Namib beetles capture airborne moisture on small shell bumps described as ________ peaks.",
                "answer": "hydrophilic",
                "explanation": "Paragraph E describes microscopic hydrophilic peaks that attract water droplets."
            }
        ]
    },
    {
        "id_slug": "peatlands",
        "title": "Sinks and Silt: The Global Importance of Peatlands",
        "subtitle": "Why waterlogged bogs hold more carbon than all the world's forests combined",
        "topic": "Environmental science and climatology",
        "paragraphs": [
            {
                "label": "A",
                "text": "Covering barely three percent of the Earth's terrestrial land surface, peatlands are easily overlooked wetland environments, often dismissed in popular folklore as bleak, treacherous bogs and dismal swamps. Yet beneath their unassuming mossy surfaces lies the planet's most efficient terrestrial carbon sequestration mechanism. Peatlands—which encompass upland blanket bogs, lowland raised bogs, mineral-rich fens, and vast tropical swamp forests across the Congo Basin and Southeast Asia—store more than six hundred gigatonnes of carbon in their subterranean layers. To place this astronomical figure in perspective, this specialized ecosystem harbors twice as much carbon as the total biomass of all global forests combined. Understanding how peat forms, functions, and degrades has consequently emerged as a primary focus in global climate mitigation research and wetland conservation biology."
            },
            {
                "label": "B",
                "text": "The secret to peat's extraordinary capacity for carbon retention lies in a single geochemical condition: permanent waterlogging. In standard terrestrial environments, when plants die, soil organisms such as aerobic bacteria, fungi, and earthworms rapidly decompose the dead organic matter, consuming oxygen and returning carbon dioxide to the atmosphere. In peatlands, however, a high water table submerges plant residues beneath an anoxic aquatic layer where atmospheric oxygen cannot penetrate. Microbial activity slows to an infinitesimal pace in these oxygen-depleted, acidic waters. Over millenia, genera such as Sphagnum moss act as ecological architects: living moss releases organic acids that suppress rival vegetation and resist microbial breakdown. As successive generations of dead moss and sedges accumulate without rotting, they compress into a dense, carbon-dense organic stratum known as peat, accumulating at a sluggish rate of barely one millimetre per year, preserving ancient organic matter so thoroughly that prehistoric wooden artifacts and bog bodies remain intact."
            },
            {
                "label": "C",
                "text": "Beyond their paramount role as planetary carbon vaults, intact peatlands perform irreplaceable ecological and hydrological services. Acting as natural sponge landscapes, pristine bogs absorb torrential precipitation during heavy storm events, buffering downstream valleys against flash flooding while sustaining baseline streamflow during summer droughts. As water filters slowly through peat's spongy fibrous matrix, sediments, dissolved heavy metals, and particulate pollutants are trapped, discharging crystal-clear drinking water into municipal catchment reservoirs across mountainous regions. Peatlands also constitute unique biological sanctuaries: the harsh, acidic, nutrient-deficient conditions support specialized evolutionary oddities, including insectivorous plants like sundews and pitcher plants that capture insects to obtain nitrogen unavailable in the waterlogged soil."
            },
            {
                "label": "D",
                "text": "Despite their immense ecological worth, peatlands have endured centuries of widespread human destruction. Historically viewed as unproductive wastelands, vast expanses of peat across northern Europe, North America, and Southeast Asia were deliberately excavated with deep drainage ditches to lower the water table for commercial agriculture and pine plantations. In countries such as Ireland and Finland, peat was also strip-mined on an industrial scale using heavy machinery, dried into fuel briquettes, and burned in thermal power stations to generate electricity for national grids. In tropical regions, particularly throughout Indonesia and Malaysia, extensive logging and drainage of peat swamp forests have made way for massive commercial oil palm and acacia monocultures, destroying vital habitats for endangered primates."
            },
            {
                "label": "E",
                "text": "The environmental consequences of draining peatlands are swift and catastrophic. When the insulating water table drops, atmospheric oxygen immediately permeates the previously anoxic peat matrix. Latent aerobic bacteria revive, consuming centuries of accumulated organic matter in a rapid combustion-like oxidation process that releases immense plumes of carbon dioxide directly into the atmosphere. Drained peat also contracts and subsides physically, dropping land levels by several centimetres each year and increasing vulnerability to coastal seawater intrusion and foundation cracking. Most alarming are subterranean peat fires: dried peat becomes intensely flammable, sparking smouldering underground blazes that can burn undetected for months, resisting surface firefighting efforts and choking entire metropolitan regions in hazardous toxic haze."
            },
            {
                "label": "F",
                "text": "Confronted by these mounting crises, an international ecological movement has emerged to rehabilitate degraded bogs through a process known as rewetting. Hydrologists block historic drainage canals with peat dams, timber bunds, and plastic piling to raise the groundwater table back to surface level. Once saturated conditions are re-established, indigenous vegetation like Sphagnum moss quickly recolonizes the landscape, halting aerobic oxidation and reviving active carbon accumulation. In areas where local economies rely on peatland farming, agronomists are pioneering paludiculture—the productive commercial cultivation of wetland crops, such as reed canary grass for biomass fuel and cattails for sustainable thermal building insulation. By harmonizing ecological restoration with commercial utility, rewetting offers a viable blueprint for securing humanity's greatest subterranean carbon store under international climate conventions."
            }
        ],
        "mcq_single": [
            {
                "prompt": "According to paragraph A, how does the amount of carbon stored in peatlands compare to that in forests?",
                "options": [
                    {"id": "A", "text": "It equals the carbon found in a single tropical rainforest"},
                    {"id": "B", "text": "It is roughly half the carbon stored in northern boreal forests"},
                    {"id": "C", "text": "It is twice as much as the biomass of all global forests combined"},
                    {"id": "D", "text": "It represents less than one percent of total terrestrial carbon"}
                ],
                "key": "C",
                "explanation": "Paragraph A states this ecosystem harbors twice as much carbon as the total biomass of all global forests combined."
            },
            {
                "prompt": "Why does dead plant material fail to decompose normally in peatlands (paragraph B)?",
                "options": [
                    {"id": "A", "text": "High salt levels sterilize the surrounding groundwater"},
                    {"id": "B", "text": "Intense cold causes plant matter to turn into stone"},
                    {"id": "C", "text": "Waterlogging creates oxygen-free, acidic conditions that inhibit microbes"},
                    {"id": "D", "text": "Subterranean heat continuously dries out fallen foliage"}
                ],
                "key": "C",
                "explanation": "Paragraph B explains that high water tables submerge residues in an anoxic aquatic layer where microbial activity slows in acidic, oxygen-depleted waters."
            },
            {
                "prompt": "According to paragraph E, what happens when atmospheric oxygen enters drained peat?",
                "options": [
                    {"id": "A", "text": "It produces synthetic diamonds through mineral pressure"},
                    {"id": "B", "text": "Aerobic bacteria oxidize organic matter and release huge volumes of carbon dioxide"},
                    {"id": "C", "text": "It cools the ground and freezes underlying aquifers"},
                    {"id": "D", "text": "It neutralizes all toxic air pollutants instantly"}
                ],
                "key": "B",
                "explanation": "Paragraph E states aerobic bacteria revive, consuming accumulated organic matter in rapid oxidation that releases immense plumes of carbon dioxide."
            }
        ],
        "mcq_multiple": [
            {
                "prompt": "Which TWO hydrological or ecological benefits of intact bogs are described in paragraph C?",
                "options": [
                    {"id": "A", "text": "Absorbing heavy rainfall to protect downstream valleys from flash floods"},
                    {"id": "B", "text": "Filtering sediments and pollutants to yield clean drinking water"},
                    {"id": "C", "text": "Providing warm geothermal pools for migratory waterfowl"},
                    {"id": "D", "text": "Generating natural electrical currents that sterilize lakes"},
                    {"id": "E", "text": "Preventing all forest fires in adjacent mountain ranges"}
                ],
                "keys": ["A", "B"],
                "explanation": "Paragraph C notes pristine bogs absorb torrential precipitation buffering against flash flooding (A) and filter sediments and pollutants to discharge crystal-clear drinking water (B)."
            },
            {
                "prompt": "Which TWO methods used in rewetting degraded peatlands are mentioned in paragraph F?",
                "options": [
                    {"id": "A", "text": "Blocking historic drainage ditches with dams and piling"},
                    {"id": "B", "text": "Pumping deep sea water across inland bogs"},
                    {"id": "C", "text": "Re-establishing indigenous vegetation such as Sphagnum moss"},
                    {"id": "D", "text": "Spraying synthetic chemical foams across dry peat"},
                    {"id": "E", "text": "Installing underground electric heaters to stimulate roots"}
                ],
                "keys": ["A", "C"],
                "explanation": "Paragraph F describes blocking drainage canals with dams and plastic piling (A) and allowing indigenous vegetation like Sphagnum moss to recolonize (C)."
            }
        ],
        "tfng": [
            {
                "statement": "Peatlands cover over twenty percent of the Earth's total land area.",
                "key": "FALSE",
                "explanation": "Paragraph A states that peatlands cover barely three percent of the terrestrial land surface."
            },
            {
                "statement": "Sphagnum moss releases organic acids that help suppress competing plant species.",
                "key": "TRUE",
                "explanation": "Paragraph B states living moss releases organic acids that suppress rival vegetation."
            },
            {
                "statement": "Sundews are the most common insectivorous plant found in peat bogs.",
                "key": "NOT_GIVEN",
                "explanation": "Paragraph C names sundews and pitcher plants but says nothing about which is more common."
            },
            {
                "statement": "In Finland, burning dried peat fuel in power stations was outlawed in the eighteenth century.",
                "key": "FALSE",
                "explanation": "Paragraph D states peat was strip-mined on an industrial scale and burned in modern thermal power stations to generate electricity."
            },
            {
                "statement": "Rewetting degraded peatlands can stop the process of aerobic carbon oxidation.",
                "key": "TRUE",
                "explanation": "Paragraph F confirms saturated conditions halt aerobic oxidation and revive active carbon accumulation."
            }
        ],
        "ynng": [
            {
                "statement": "Dismissing peatlands as useless swamps ignores their critical role in regulating global climate.",
                "key": "YES",
                "explanation": "Paragraph A contrasts popular folklore dismissing bogs with their status as the planet's most efficient carbon sink."
            },
            {
                "statement": "Peat accumulates at a rapid pace that can replenish deep bogs within a few decades.",
                "key": "NO",
                "explanation": "Paragraph B states peat accumulates at a sluggish rate of barely one millimetre per year over millenia."
            },
            {
                "statement": "Commercial palm oil plantations in Southeast Asia have contributed to the destruction of peat swamp forests.",
                "key": "YES",
                "explanation": "Paragraph D notes extensive logging and drainage of peat swamp forests made way for commercial oil palm monocultures."
            },
            {
                "statement": "Most peat fires are started deliberately by farmers clearing land.",
                "key": "NOT_GIVEN",
                "explanation": "Paragraph E explains that dried peat becomes flammable and fires smoulder for months, but does not say how the fires start."
            },
            {
                "statement": "Agricultural production and peatland restoration are fundamentally incompatible under all circumstances.",
                "key": "NO",
                "explanation": "Paragraph F introduces paludiculture (wetland farming) as a viable way to harmonize ecological restoration with commercial utility."
            }
        ],
        "matching": [
            {
                "prompt": "a statistical comparison between the carbon content of peatlands and global forests",
                "key": "A",
                "evidence": "harbors twice as much carbon as the total biomass of all global forests combined",
                "explanation": "Paragraph A gives the comparative carbon statistic."
            },
            {
                "prompt": "the microscopic biological conditions that impede plant decomposition underwater",
                "key": "B",
                "evidence": "an anoxic aquatic layer where atmospheric oxygen cannot penetrate. Microbial activity slows to an infinitesimal pace in these oxygen-depleted, acidic waters",
                "explanation": "Paragraph B explains anoxic conditions inhibiting decay."
            },
            {
                "prompt": "examples of carnivorous flora adapted to nutrient-poor wetland soils",
                "key": "C",
                "evidence": "specialized evolutionary oddities, including insectivorous plants like sundews and pitcher plants that capture insects",
                "explanation": "Paragraph C describes sundews and pitcher plants."
            },
            {
                "prompt": "an account of historical excavation and industrial mining for electricity generation",
                "key": "D",
                "evidence": "strip-mined on an industrial scale using heavy machinery, dried into fuel briquettes, and burned in thermal power stations",
                "explanation": "Paragraph D discusses commercial harvesting for fuel."
            },
            {
                "prompt": "the practice of farming commercial crops on wet restored bogs",
                "key": "F",
                "evidence": "pioneering paludiculture—the productive commercial cultivation of wetland crops, such as reed canary grass",
                "explanation": "Paragraph F introduces paludiculture."
            }
        ],
        "completion": [
            {
                "prompt": "Peat accumulates very slowly at an approximate speed of one ________ each year.",
                "answer": "millimetre",
                "explanation": "Paragraph B specifies the accumulation rate of barely one millimetre per year."
            },
            {
                "prompt": "Carnivorous plants like sundews trap bugs to obtain the nutrient ________.",
                "answer": "nitrogen",
                "explanation": "Paragraph C notes insectivorous plants capture insects to obtain nitrogen."
            },
            {
                "prompt": "Extensive drainage of tropical peat swamps has occurred to establish large ________ plantations.",
                "answer": "oil",
                "explanation": "Paragraph D mentions drainage making way for massive commercial oil palm monocultures."
            },
            {
                "prompt": "Underground peat fires produce a suffocating and hazardous blanket of ________.",
                "answer": "haze",
                "explanation": "Paragraph E states blazes choke entire metropolitan regions in hazardous toxic haze."
            },
            {
                "prompt": "Farmers in rewetted bogs can cultivate wetland plants like ________ for building insulation.",
                "answer": "cattails",
                "explanation": "Paragraph F mentions cattails for sustainable thermal building insulation."
            }
        ]
    },
    {
        "id_slug": "deepsea",
        "title": "Oases of the Abyss: The Ecosystems of Hydrothermal Vents",
        "subtitle": "Life flourishing in total darkness powered by geothermal chemistry",
        "topic": "Marine biology and oceanography",
        "paragraphs": [
            {
                "label": "A",
                "text": "Until the final decades of the twentieth century, biological dogma held that virtually all complex multicellular life on Earth was ultimately powered by solar radiation through the photosynthetic machinery of plants and phytoplankton. The abyssal ocean floor, shrouded in perpetual darkness thousands of metres beneath the surface, was presumed to be a biological wasteland, sustaining only sparse scavenger populations that subsisted on the meagre organic debris—known as marine snow—drifting down from the sunlit epipelagic zone. This long-standing paradigm was shattered in 1977 during an exploratory dive by the three-person research submersible Alvin along the Galápagos Rift. Deep on the volcanic seafloor, oceanographers were astonished to discover dense, thriving biological communities clustered around towering mineral chimneys spewing billowing black plumes of superheated fluid into the icy bottom water, completely upending prevailing ecological assumptions."
            },
            {
                "label": "B",
                "text": "These volcanic structures, colloquially dubbed 'black smokers', are hydrothermal vents formed along mid-ocean tectonic spreading ridges where Earth's tectonic plates pull apart. Seawater percolates deep into cracks in the oceanic crust, where it is superheated by underlying magma chambers to temperatures exceeding four hundred degrees Celsius. Under extreme hydrostatic pressure—often exceeding two hundred atmospheres—the trapped water cannot boil into steam; instead, it becomes a chemically reactive supercritical fluid that leaches sulfur, iron, copper, and zinc from the surrounding basalt. Buoyant and superheated, this mineral broth rushes back up through the seabed. As it erupts into the near-freezing deep oceanic water, dissolved metal sulfides instantly precipitate out of solution, constructing hollow mineral chimneys that can soar several storeys high, composed of minerals like pyrite and chalcopyrite."
            },
            {
                "label": "C",
                "text": "The foundation of the entire hydrothermal vent food web rests upon an alternative metabolic process: chemosynthesis. In the absolute absence of sunlight, specialized autotrophic bacteria and archaea oxidize reduced inorganic compounds—primarily toxic hydrogen sulfide and dissolved methane—to synthesize glucose and organic molecules from carbon dioxide. These chemolithoautotrophic microbes form dense microbial mats coating rock surfaces and billow in the thermal plumes, creating an abundant nutritional foundation. Vent animals graze directly upon these bacterial mats or filter them from the water, while predatory decapod crustaceans, zoarcid fish, and cephalopods hunt the primary consumers, forming an intricate trophic hierarchy independent of solar energy, thriving in waters where temperatures drop from boiling to freezing across mere centimetres."
            },
            {
                "label": "D",
                "text": "The most striking evolutionary marvel of the vent ecosystem is the giant tube worm (Riftia pachyptila), which can grow to lengths exceeding two metres within flexible white chitinous tubes anchored to the volcanic rock. Anatomically bizarre, adult Riftia possess neither a mouth, nor a gut, nor an anus, and are completely incapable of ingesting food. Instead, the worm's interior cavity is packed with a vascularized organ called a trophosome, which houses billions of endosymbiotic sulfur-oxidizing bacteria. The worm's bright red, feathery plume absorbs hydrogen sulfide, oxygen, and carbon dioxide from the surrounding hydrothermal plume, utilizing specialized hemoglobin molecules that bind both oxygen and sulfide simultaneously without being poisoned. The bacteria process these raw chemical building blocks to manufacture organic nutrients, feeding the worm entirely from within."
            },
            {
                "label": "E",
                "text": "Despite their remarkable local biomass, hydrothermal vent communities are geologically ephemeral oases separated by vast, hostile abyssal plains. Because mid-ocean volcanic systems are dynamic and unstable, individual vent chimneys frequently clog with mineral deposits or are extinguished abruptly when subterranean magma shifts, starving the local ecosystem within years. Consequently, vent species have evolved extraordinary reproductive strategies to colonize newly opening fissures kilometres away. Organisms release vast quantities of planktonic larvae that enter deep oceanic currents; capable of surviving for months in near-freezing temperatures by slowing their metabolic rates, these larvae navigate by detecting minute thermal anomalies, acoustic vibrations, and chemical plumes drifting from distant active chimneys, occasionally using intermediate whale falls as biological stepping stones."
            },
            {
                "label": "F",
                "text": "In the twenty-first century, these pristine abyssal ecosystems face unprecedented commercial threats from the emerging deep-seabed mining industry. The mineral chimneys and seafloor deposits surrounding inactive hydrothermal vents consist of seafloor massive sulfides, which contain extraordinarily high concentrations of valuable industrial metals, including copper, gold, silver, and cobalt, essential for electric vehicles and renewable energy storage. Mining consortia are currently testing robotic seafloor crawlers designed to crush chimneys and vacuum mineral slurry to surface support ships. Marine scientists warn that stripping the seabed could devastate unique endemic species before science has even catalogued them. Developing rigorous environmental regulations under the International Seabed Authority represents an urgent diplomatic challenge to protect these fragile evolutionary marvels from industrial exploitation."
            }
        ],
        "mcq_single": [
            {
                "prompt": "According to paragraph A, what discovery did the submersible Alvin make in 1977?",
                "options": [
                    {"id": "A", "text": "Sunken military vessels from the First World War"},
                    {"id": "B", "text": "A thriving ecosystem clustered around superheated mineral vents"},
                    {"id": "C", "text": "Deep ocean currents that reversed their direction seasonally"},
                    {"id": "D", "text": "Extensive underwater forests of giant kelp"}
                ],
                "key": "B",
                "explanation": "Paragraph A states oceanographers were astonished to discover dense communities clustered around mineral chimneys spewing superheated fluid."
            },
            {
                "prompt": "How does the giant tube worm Riftia pachyptila obtain food, according to paragraph D?",
                "options": [
                    {"id": "A", "text": "By catching small crabs in its feathery red plume"},
                    {"id": "B", "text": "By receiving nutrition from bacteria living inside its trophosome organ"},
                    {"id": "C", "text": "By filtering falling marine snow drifting from the surface"},
                    {"id": "D", "text": "By sucking mineral mud directly through its mouth"}
                ],
                "key": "B",
                "explanation": "Paragraph D explains that the worm has no mouth or gut; endosymbiotic bacteria inside its trophosome synthesize organic nutrients to feed it."
            },
            {
                "prompt": "According to paragraph F, why is the mining industry interested in seafloor vent deposits?",
                "options": [
                    {"id": "A", "text": "They want to build underwater tourism hotels"},
                    {"id": "B", "text": "The deposits contain high concentrations of valuable metals like copper and cobalt"},
                    {"id": "C", "text": "The mineral chimneys can be converted into synthetic fertilizer"},
                    {"id": "D", "text": "The vents can supply geothermal steam directly to surface cities"}
                ],
                "key": "B",
                "explanation": "Paragraph F notes seafloor massive sulfides contain high concentrations of valuable industrial metals like copper, gold, silver, and cobalt."
            }
        ],
        "mcq_multiple": [
            {
                "prompt": "Which TWO chemical energy sources power vent chemosynthesis according to paragraph C?",
                "options": [
                    {"id": "A", "text": "Dissolved hydrogen sulfide"},
                    {"id": "B", "text": "Nuclear radioactive runoff"},
                    {"id": "C", "text": "Dissolved methane gas"},
                    {"id": "D", "text": "Sunlight penetrating through ice cracks"},
                    {"id": "E", "text": "Atmospheric chlorofluorocarbons"}
                ],
                "keys": ["A", "C"],
                "explanation": "Paragraph C notes autotrophic bacteria oxidize inorganic compounds, primarily toxic hydrogen sulfide (A) and dissolved methane (C)."
            },
            {
                "prompt": "Which TWO navigational cues or adaptations help vent larvae colonize new chimneys (paragraph E)?",
                "options": [
                    {"id": "A", "text": "Detecting chemical plumes and temperature changes in deep currents"},
                    {"id": "B", "text": "Entering metabolic dormancy to survive for months in freezing water"},
                    {"id": "C", "text": "Swimming directly to the ocean surface to navigate by starlight"},
                    {"id": "D", "text": "Attaching to migrating whales for long-distance transport"},
                    {"id": "E", "text": "Using magnetic compass needles grown inside their shells"}
                ],
                "keys": ["A", "B"],
                "explanation": "Paragraph E highlights surviving months by slowing metabolic rates (B) and detecting minute thermal anomalies, acoustic vibrations, and chemical plumes (A)."
            }
        ],
        "tfng": [
            {
                "statement": "Before 1977, scientists assumed the deep ocean floor was almost devoid of complex life.",
                "key": "TRUE",
                "explanation": "Paragraph A states the abyssal floor was presumed to be a biological wasteland sustaining only sparse scavengers."
            },
            {
                "statement": "Under 200 atmospheres of pressure, 400-degree water turns instantly into dry steam.",
                "key": "FALSE",
                "explanation": "Paragraph B states that under extreme hydrostatic pressure, the trapped water cannot boil into steam, becoming a supercritical fluid instead."
            },
            {
                "statement": "Adult Riftia tube worms possess a functional digestive system with teeth.",
                "key": "FALSE",
                "explanation": "Paragraph D states adult Riftia possess neither a mouth, nor a gut, nor an anus."
            },
            {
                "statement": "Planktonic vent larvae navigate between chimneys using internal magnetic compass minerals.",
                "key": "NOT_GIVEN",
                "explanation": "Paragraph E describes larvae detecting thermal anomalies, acoustic vibrations, and chemical plumes, but mentions nothing about magnetic compass minerals."
            },
            {
                "statement": "Robotic seafloor machines are being tested to extract mineral deposits from the seabed.",
                "key": "TRUE",
                "explanation": "Paragraph F notes mining consortia are currently testing robotic seafloor crawlers to crush chimneys."
            }
        ],
        "ynng": [
            {
                "statement": "The discovery of hydrothermal vent life transformed human understanding of biological requirements.",
                "key": "YES",
                "explanation": "Paragraph A states this shattered the biological dogma that all complex life depended on solar radiation and photosynthesis."
            },
            {
                "statement": "Chemosynthesis-based food webs are entirely reliant on seasonal agricultural runoff from land.",
                "key": "NO",
                "explanation": "Paragraph C explains that chemosynthesis forms an intricate trophic hierarchy completely independent of solar energy."
            },
            {
                "statement": "Vent chimneys remain geologically active for millions of uninterrupted years.",
                "key": "NO",
                "explanation": "Paragraph E states vent chimneys are dynamic and ephemeral, frequently clogging or being extinguished within years."
            },
            {
                "statement": "Deep-seabed mining should proceed immediately without any international conservation agreements.",
                "key": "NO",
                "explanation": "Paragraph F argues scientists warn of severe ecological devastation and stresses the urgency of rigorous regulations."
            },
            {
                "statement": "The International Seabed Authority has resolved every mining dispute between member states.",
                "key": "NOT_GIVEN",
                "explanation": "Paragraph F mentions developing regulations under the Authority as an urgent challenge, without claiming all disputes are resolved."
            }
        ],
        "matching": [
            {
                "prompt": "an early scientific assumption that deep-sea animals lived exclusively on descending debris",
                "key": "A",
                "evidence": "sustaining only sparse scavenger populations that subsisted on the meagre organic debris—known as marine snow—drifting down from the sunlit epipelagic zone",
                "explanation": "Paragraph A mentions marine snow and the scavenger assumption."
            },
            {
                "prompt": "how superheated mineral fluids form towering hollow chimneys on the seabed",
                "key": "B",
                "evidence": "metal sulfides instantly precipitate out of solution, constructing hollow mineral chimneys that can soar several storeys high",
                "explanation": "Paragraph B explains how chimneys are constructed."
            },
            {
                "prompt": "the chemical process by which bacteria create organic compounds without solar illumination",
                "key": "C",
                "evidence": "chemosynthesis. In the absolute absence of sunlight, specialized autotrophic bacteria and archaea oxidize reduced inorganic compounds",
                "explanation": "Paragraph C details chemosynthesis."
            },
            {
                "prompt": "an explanation of how the giant tube worm absorbs gases through a colourful plume",
                "key": "D",
                "evidence": "The worm's bright red, feathery plume absorbs hydrogen sulfide, oxygen, and carbon dioxide from the surrounding hydrothermal plume",
                "explanation": "Paragraph D describes Riftia's plume."
            },
            {
                "prompt": "the threat posed by industrial underwater crawlers gathering valuable metals",
                "key": "F",
                "evidence": "testing robotic seafloor crawlers designed to crush chimneys and vacuum mineral slurry to surface support ships. Marine scientists warn that stripping the seabed could devastate unique endemic species",
                "explanation": "Paragraph F highlights deep-seabed mining."
            }
        ],
        "completion": [
            {
                "prompt": "The three-person research submersible that discovered vents in 1977 was called ________.",
                "answer": "Alvin",
                "explanation": "Paragraph A names the research submersible Alvin."
            },
            {
                "prompt": "Vents are formed along mid-ocean tectonic ________ ridges where plates pull apart.",
                "answer": "spreading",
                "explanation": "Paragraph B states vents form along mid-ocean tectonic spreading ridges."
            },
            {
                "prompt": "Autotrophic vent bacteria synthesize nutrients through the process of ________.",
                "answer": "chemosynthesis",
                "explanation": "Paragraph C introduces chemosynthesis."
            },
            {
                "prompt": "Giant tube worms house symbiotic bacteria in an internal organ called a ________.",
                "answer": "trophosome",
                "explanation": "Paragraph D names the vascularized organ the trophosome."
            },
            {
                "prompt": "Commercial companies want to extract minerals to acquire metals like ________ for electric vehicle batteries.",
                "answer": "cobalt",
                "explanation": "Paragraph F mentions copper, gold, silver, and cobalt essential for electric vehicles."
            }
        ]
    }
]
