"""Two IELTS Academic passages for batch 3 that replace 'urbanheat' and
'language', whose topics were already live ("Cooling the urban heat island",
"Urban heat islands", "When a language dies", "When languages die").
Original practice content in the shape of the other batch 3 passages.
"""

LICHENS = {
    "id_slug": "lichens",
    "title": "Partners in Survival: The Hidden Lives of Lichens",
    "subtitle": "How a fungus and its partners colonise some of the harshest places on Earth",
    "topic": "Biology and ecology",
    "paragraphs": [
        {"label": "A", "text": "Crusty orange patches on a garden wall, grey-green tufts hanging from a branch, pale rosettes spreading across a gravestone: lichens are among the most familiar sights in the natural world, yet they are widely misunderstood. Many people assume that they are a kind of moss, or a simple plant without roots. In fact, a lichen is not a single organism at all but a partnership. The main body is formed by a fungus, which provides structure and protection and absorbs water and minerals. Living among its threads is a photosynthetic partner, either a green alga or a cyanobacterium, which uses sunlight to make sugars that feed the whole association. Scientists have so far described around 20,000 species of lichen, and new ones are identified every year."},
        {"label": "B", "text": "This partnership allows lichens to survive in conditions that few other living things can tolerate. They grow on bare rock in Antarctica, on the bark of rainforest trees and on the surface of hot deserts. Their secret is an unusual approach to water. Unlike most plants, lichens make no attempt to keep a constant water content. When their surroundings dry out, they simply dry out too and become dormant, sometimes for months or even years, without suffering serious harm. Once rain or dew returns, many species absorb water within minutes and resume photosynthesis almost immediately. This tolerance is so extreme that, in experiments on the International Space Station, some lichens survived long periods of exposure to the vacuum and radiation of space."},
        {"label": "C", "text": "Lichens also play a quiet but essential part in the formation of soil. Because they need no soil themselves, they are often the first organisms to colonise newly exposed rock, which is why ecologists describe them as pioneer species. As they grow, lichens release weak acids that slowly break down the rock surface, while their bodies trap windblown dust. When they die, their remains add organic matter to this thin layer of weathered material, gradually creating conditions in which mosses, and later larger plants, can establish themselves. Such processes are extremely slow: some lichens expand by as little as a millimetre a year. Their steady growth has even been used to estimate the age of exposed rock surfaces, a technique known as lichenometry."},
        {"label": "D", "text": "The same features that make lichens so hardy also make them unusually vulnerable to air pollution. Having no roots and no protective outer layer, they absorb water and nutrients directly from rain and the surrounding air, and with them any pollutants the air contains. During the nineteenth and twentieth centuries, many species vanished from industrial cities, where sulphur dioxide from burning coal made the air too acidic for them to survive. As clean-air laws reduced this pollution, lichens gradually returned, and their recovery is one of the clearest signs that such laws have worked. Today scientists use them to monitor a different problem, nitrogen pollution from traffic and farming, because some species thrive where nitrogen is abundant while others disappear."},
        {"label": "E", "text": "People have found many uses for lichens over the centuries. In parts of Scotland and Scandinavia, they were traditionally boiled to produce dyes for wool, giving the cloth warm browns, oranges and purples. Litmus, the substance that turns red in acid and blue in alkali, was originally extracted from lichens and is still used to teach chemistry to schoolchildren. In the far north, lichens are a vital source of food in winter for reindeer and caribou, which dig through the snow to reach them. Some species contain compounds, such as usnic acid, that can kill certain bacteria, and they have been used in traditional medicine. However, it would be premature to expect lichen-based medicines to replace conventional antibiotics."},
        {"label": "F", "text": "Despite their resilience, lichens face growing threats. Because they grow so slowly, communities damaged by trampling, construction or the collection of lichens for decoration can take decades to recover. Nitrogen pollution and a changing climate are altering which species can survive in many regions. At the same time, lichens continue to surprise the scientists who study them. In 2016, researchers reported that many common lichens contain a third partner, a type of yeast living in the outer layer of the lichen body, which had gone unnoticed for well over a century of study. The discovery suggests that these familiar organisms are more complex partnerships than anyone had imagined, and that much about them remains to be learned."},
    ],
    "mcq_single": [
        {"prompt": "According to paragraph A, what is a lichen?",
         "options": [{"id": "A", "text": "A primitive type of moss"},
                     {"id": "B", "text": "A partnership between a fungus and a photosynthetic organism"},
                     {"id": "C", "text": "A plant that grows without roots"},
                     {"id": "D", "text": "A fungus that feeds on dead wood"}],
         "key": "B", "explanation": "Paragraph A says a lichen is a partnership between a fungus and a green alga or cyanobacterium, not a moss or a plant."},
        {"prompt": "Why are lichens described as pioneer species in paragraph C?",
         "options": [{"id": "A", "text": "They are often the first organisms to colonise bare rock."},
                     {"id": "B", "text": "They grow faster than mosses."},
                     {"id": "C", "text": "They were the first living things on Earth."},
                     {"id": "D", "text": "They can move from one rock to another."}],
         "key": "A", "explanation": "Paragraph C says lichens are often the first organisms to colonise newly exposed rock, which is why they are called pioneer species."},
        {"prompt": "What does paragraph E say about litmus?",
         "options": [{"id": "A", "text": "It was originally extracted from lichens."},
                     {"id": "B", "text": "It is a dye used for wool in Scotland."},
                     {"id": "C", "text": "It is harmful to reindeer."},
                     {"id": "D", "text": "It was invented to replace lichen dyes."}],
         "key": "A", "explanation": "Paragraph E states that litmus was originally extracted from lichens."},
    ],
    "mcq_multiple": [
        {"prompt": "Which TWO features help lichens survive extreme conditions, according to paragraph B?",
         "options": [{"id": "A", "text": "They can dry out completely and become dormant."},
                     {"id": "B", "text": "They store water in deep roots."},
                     {"id": "C", "text": "They absorb water and recover quickly once it returns."},
                     {"id": "D", "text": "They move to sheltered places in dry weather."},
                     {"id": "E", "text": "They produce heat to protect themselves from frost."}],
         "keys": ["A", "C"], "explanation": "Paragraph B says lichens dry out and become dormant (A), and absorb water within minutes and resume photosynthesis when it returns (C)."},
        {"prompt": "Which TWO uses of lichens by people are mentioned in paragraph E?",
         "options": [{"id": "A", "text": "colouring wool"},
                     {"id": "B", "text": "making paper"},
                     {"id": "C", "text": "producing a chemical indicator used in teaching"},
                     {"id": "D", "text": "insulating houses"},
                     {"id": "E", "text": "fuel for fires"}],
         "keys": ["A", "C"], "explanation": "Paragraph E mentions boiling lichens to dye wool (A) and litmus, originally extracted from lichens, which is used to teach chemistry (C)."},
    ],
    "tfng": [
        {"statement": "Scientists have described around 20,000 species of lichen.", "key": "TRUE",
         "explanation": "Paragraph A says around 20,000 species have been described so far."},
        {"statement": "Lichens are killed if they dry out completely.", "key": "FALSE",
         "explanation": "Paragraph B says lichens dry out and become dormant without suffering serious harm."},
        {"statement": "Some lichens grow by as little as a millimetre a year.", "key": "TRUE",
         "explanation": "Paragraph C says some lichens expand by as little as a millimetre a year."},
        {"statement": "Lichens were first used to monitor air pollution in London.", "key": "NOT_GIVEN",
         "explanation": "Paragraph D discusses lichens in industrial cities and pollution monitoring but names no city where monitoring began."},
        {"statement": "The third partner in many lichens was identified in the nineteenth century.", "key": "FALSE",
         "explanation": "Paragraph F says the third partner was reported in 2016, after going unnoticed for over a century."},
    ],
    "ynng": [
        {"statement": "It is a mistake to think of lichens as a kind of plant.", "key": "YES",
         "explanation": "Paragraph A says lichens are widely misunderstood and are in fact a partnership, not a moss or a plant."},
        {"statement": "Lichens contribute less to soil formation than mosses do.", "key": "NOT_GIVEN",
         "explanation": "Paragraph C describes lichens preparing the ground for mosses but does not compare how much each contributes."},
        {"statement": "The return of lichens to cities shows that clean-air laws have been effective.", "key": "YES",
         "explanation": "Paragraph D calls their recovery one of the clearest signs that such laws have worked."},
        {"statement": "Lichen-based medicines are likely to replace conventional antibiotics soon.", "key": "NO",
         "explanation": "Paragraph E says it would be premature to expect lichen-based medicines to replace conventional antibiotics."},
        {"statement": "Lichen communities damaged by trampling recover quickly.", "key": "NO",
         "explanation": "Paragraph F says damaged communities can take decades to recover."},
    ],
    "matching": [
        {"prompt": "an experiment carried out beyond the Earth's atmosphere", "key": "B",
         "evidence": "International Space Station", "explanation": "Paragraph B describes lichens surviving exposure to space on the International Space Station."},
        {"prompt": "the use of lichens to estimate the age of a surface", "key": "C",
         "evidence": "lichenometry", "explanation": "Paragraph C names the technique of lichenometry."},
        {"prompt": "the reason lichens are especially sensitive to polluted air", "key": "D",
         "evidence": "absorb water and nutrients directly from rain and the surrounding air", "explanation": "Paragraph D explains that lichens absorb water and nutrients, and pollutants, directly from the air."},
        {"prompt": "a traditional craft that relied on lichens", "key": "E",
         "evidence": "produce dyes for wool", "explanation": "Paragraph E describes lichens being boiled to produce dyes for wool."},
        {"prompt": "a recent discovery about the make-up of lichens", "key": "F",
         "evidence": "a third partner", "explanation": "Paragraph F reports the 2016 discovery of a third partner in many lichens."},
    ],
    "completion": [
        {"prompt": "In a lichen, the photosynthetic partner is either a green alga or a ________.", "answer": "cyanobacterium",
         "explanation": "Paragraph A says the partner is either a green alga or a cyanobacterium."},
        {"prompt": "When their surroundings dry out, lichens can remain ________ for months or years.", "answer": "dormant",
         "explanation": "Paragraph B says lichens dry out and become dormant."},
        {"prompt": "Lichens release weak ________ that slowly break down the surface of rock.", "answer": "acids",
         "explanation": "Paragraph C says lichens release weak acids that break down the rock surface."},
        {"prompt": "Many lichens vanished from industrial cities because of sulphur ________.", "answer": "dioxide",
         "explanation": "Paragraph D says sulphur dioxide from burning coal made the air too acidic."},
        {"prompt": "In winter, reindeer and caribou depend on lichens as a source of ________.", "answer": "food",
         "explanation": "Paragraph E says lichens are a vital source of food in winter for reindeer and caribou."},
    ],
}

FORECASTING = {
    "id_slug": "forecasting",
    "title": "Reading the Sky: How Weather Forecasting Became a Science",
    "subtitle": "From storm warnings to supercomputers",
    "topic": "Meteorology and the history of science",
    "paragraphs": [
        {"label": "A", "text": "For most of human history, predicting the weather depended on local observation and inherited wisdom. Farmers and sailors watched the colour of the sky, the behaviour of animals and the shape of clouds, and passed their knowledge on in sayings such as 'red sky at night, shepherd's delight'. Some of these sayings contain a grain of truth, since they reflect patterns that genuinely tend to precede changes in the weather. From the seventeenth century, the barometer allowed people to measure air pressure, and a falling reading came to be understood as a warning of unsettled conditions. Yet a single observer could see only the sky above them. The real obstacle to forecasting was that information about approaching weather could not travel faster than the weather itself. That changed in the 1840s, when the electric telegraph made it possible to collect observations from distant places within hours."},
        {"label": "B", "text": "One of the first people to exploit this opportunity was Robert FitzRoy, who had earlier commanded HMS Beagle on the voyage that carried Charles Darwin around the world. In 1854 FitzRoy was appointed to lead a new government department collecting weather data at sea. Five years later, a violent storm wrecked the ship Royal Charter off the coast of Wales with the loss of hundreds of lives, and FitzRoy became convinced that such disasters could be prevented by warning ports in advance. He organised a network of coastal stations linked by telegraph, introduced public storm warnings, and began publishing daily forecasts in The Times newspaper in 1861. He is also credited with introducing the word 'forecast' itself. His predictions were often wrong, however, and he faced harsh criticism from scientists and the press. Few people today remember his name, yet FitzRoy surely deserves far more credit than he received in his lifetime."},
        {"label": "C", "text": "At the beginning of the twentieth century, the Norwegian scientist Vilhelm Bjerknes argued that forecasting should be treated as a problem of physics. If the present state of the atmosphere could be measured accurately, he reasoned, the laws governing the movement of air, heat and moisture could be used to calculate its future state. The British mathematician Lewis Fry Richardson attempted exactly this during the First World War, working out a forecast for a single region entirely by hand. The calculation took him about six weeks to complete for a forecast covering just six hours, and the result was wildly inaccurate. Later analysis showed that the problem lay mainly in his starting data rather than in his method. Undeterred, Richardson imagined a vast 'forecast factory' in which tens of thousands of people would perform the calculations together, fast enough to keep ahead of the weather."},
        {"label": "D", "text": "Richardson's dream became practical only with the arrival of electronic computers. In 1950, a team of meteorologists and mathematicians in the United States used one of the earliest computers, ENIAC, to produce the first successful numerical forecast. It was a modest achievement by modern standards: the machine took roughly twenty-four hours to calculate a forecast covering the following twenty-four hours. Nevertheless, it proved that Bjerknes and Richardson had been right in principle. A decade later, a second revolution began from above. In 1960 the satellite TIROS-1 sent back the first television pictures of clouds taken from space, allowing forecasters to watch storms developing over oceans where there were few or no observations."},
        {"label": "E", "text": "As computers grew more powerful, forecasters discovered a fundamental limit. In the 1960s the American meteorologist Edward Lorenz found that his computer model of the atmosphere was extremely sensitive to its starting conditions: rounding a single number slightly produced a completely different forecast a few weeks later. This property, later popularly known as the butterfly effect, means that small errors in measurement inevitably grow over time. Modern forecasting centres respond to this uncertainty by running their models many times with slightly different starting conditions. The resulting collection of forecasts, called an ensemble, shows how confident forecasters can be, and allows them to express predictions as probabilities, such as a seventy per cent chance of rain, which the writer considers a more honest way of communicating uncertainty than a single definite prediction."},
        {"label": "F", "text": "The progress of the past half-century has nonetheless been remarkable. Studies of forecast accuracy suggest that skill has improved by about one day per decade, so that a forecast for several days ahead today is roughly as reliable as a forecast for one day fewer was ten years earlier. Better observations, faster computers and improved models have all contributed. Recently, machine-learning systems trained on decades of past weather data have begun to be tested alongside traditional models, and some have produced impressive results. Chaos, however, still sets a limit: beyond about two weeks, detailed day-to-day forecasts lose almost all their skill. Forecasters may yet predict the general character of a coming season, but the writer is doubtful that the weather will ever be predicted in full detail weeks in advance."},
    ],
    "mcq_single": [
        {"prompt": "According to paragraph A, what first made it possible to forecast weather over a wide area?",
         "options": [{"id": "A", "text": "the invention of the barometer"},
                     {"id": "B", "text": "the electric telegraph"},
                     {"id": "C", "text": "traditional weather sayings"},
                     {"id": "D", "text": "photographs of clouds"}],
         "key": "B", "explanation": "Paragraph A says the telegraph made it possible to collect observations from distant places within hours."},
        {"prompt": "What happened when Richardson calculated a forecast by hand?",
         "options": [{"id": "A", "text": "His forecast was accurate but took too long to be useful."},
                     {"id": "B", "text": "The calculation took weeks and the result was badly wrong."},
                     {"id": "C", "text": "He abandoned the calculation before it was finished."},
                     {"id": "D", "text": "He was helped by thousands of other people."}],
         "key": "B", "explanation": "Paragraph C says the calculation took about six weeks and the result was wildly inaccurate."},
        {"prompt": "Why do forecasting centres run their models many times, according to paragraph E?",
         "options": [{"id": "A", "text": "to show how uncertain a forecast is"},
                     {"id": "B", "text": "to correct mistakes made by the computer"},
                     {"id": "C", "text": "to make the forecast arrive sooner"},
                     {"id": "D", "text": "to test new kinds of computer"}],
         "key": "A", "explanation": "Paragraph E says the ensemble shows how confident forecasters can be and allows predictions to be given as probabilities."},
    ],
    "mcq_multiple": [
        {"prompt": "Which TWO achievements are credited to FitzRoy in paragraph B?",
         "options": [{"id": "A", "text": "introducing the word 'forecast'"},
                     {"id": "B", "text": "inventing the barometer"},
                     {"id": "C", "text": "publishing daily forecasts in a newspaper"},
                     {"id": "D", "text": "building the first computer weather model"},
                     {"id": "E", "text": "leading an expedition to Antarctica"}],
         "keys": ["A", "C"], "explanation": "Paragraph B credits FitzRoy with introducing the word 'forecast' (A) and publishing daily forecasts in The Times (C)."},
        {"prompt": "Which TWO developments are described in paragraph D?",
         "options": [{"id": "A", "text": "the first successful forecast produced by computer"},
                     {"id": "B", "text": "a factory employing thousands of human calculators"},
                     {"id": "C", "text": "the first pictures of clouds taken from space"},
                     {"id": "D", "text": "a network of coastal telegraph stations"},
                     {"id": "E", "text": "the discovery of the butterfly effect"}],
         "keys": ["A", "C"], "explanation": "Paragraph D describes the first successful numerical forecast on ENIAC (A) and the first pictures of clouds from TIROS-1 (C)."},
    ],
    "tfng": [
        {"statement": "Before the telegraph, forecasters could not quickly learn about the weather in distant places.", "key": "TRUE",
         "explanation": "Paragraph A says information could not travel faster than the weather until the telegraph arrived."},
        {"statement": "FitzRoy's forecasts were widely praised by scientists of his time.", "key": "FALSE",
         "explanation": "Paragraph B says he faced harsh criticism from scientists and the press."},
        {"statement": "Bjerknes believed the future state of the atmosphere could be calculated using the laws of physics.", "key": "TRUE",
         "explanation": "Paragraph C says Bjerknes argued forecasting should be treated as a problem of physics."},
        {"statement": "The team that produced the first computer forecast also designed the first weather satellite.", "key": "NOT_GIVEN",
         "explanation": "Paragraph D mentions both developments but does not say who designed the satellite."},
        {"statement": "Detailed day-to-day forecasts remain reliable for more than a month ahead.", "key": "FALSE",
         "explanation": "Paragraph F says detailed forecasts lose almost all their skill beyond about two weeks."},
    ],
    "ynng": [
        {"statement": "Traditional weather sayings were entirely without value.", "key": "NO",
         "explanation": "Paragraph A says some of these sayings contain a grain of truth."},
        {"statement": "FitzRoy deserves more recognition than he was given during his lifetime.", "key": "YES",
         "explanation": "Paragraph B says FitzRoy surely deserves far more credit than he received in his lifetime."},
        {"statement": "Richardson's forecast factory would have been cheaper to run than a modern computer.", "key": "NOT_GIVEN",
         "explanation": "Paragraph C describes the forecast factory but says nothing about its cost."},
        {"statement": "Presenting forecasts as probabilities is more honest than giving a single definite prediction.", "key": "YES",
         "explanation": "Paragraph E says the writer considers probabilities a more honest way of communicating uncertainty."},
        {"statement": "The weather will one day be predictable in full detail weeks in advance.", "key": "NO",
         "explanation": "Paragraph F says the writer is doubtful that this will ever be possible."},
    ],
    "matching": [
        {"prompt": "a disaster at sea that led to a new public service", "key": "B",
         "evidence": "Royal Charter", "explanation": "Paragraph B describes the wreck of the Royal Charter, after which FitzRoy introduced storm warnings."},
        {"prompt": "an imagined workplace full of people doing calculations", "key": "C",
         "evidence": "forecast factory", "explanation": "Paragraph C describes Richardson's imagined 'forecast factory'."},
        {"prompt": "the first images of weather taken from above the Earth", "key": "D",
         "evidence": "TIROS-1", "explanation": "Paragraph D says TIROS-1 sent back the first television pictures of clouds from space."},
        {"prompt": "the reason small measurement errors grow over time", "key": "E",
         "evidence": "extremely sensitive to its starting conditions", "explanation": "Paragraph E explains that the atmosphere is extremely sensitive to its starting conditions."},
        {"prompt": "the rate at which forecast accuracy has improved", "key": "F",
         "evidence": "one day per decade", "explanation": "Paragraph F says skill has improved by about one day per decade."},
    ],
    "completion": [
        {"prompt": "From the seventeenth century, people could measure air pressure with a ________.", "answer": "barometer",
         "explanation": "Paragraph A says the barometer allowed people to measure air pressure."},
        {"prompt": "FitzRoy had earlier commanded the ship that carried Charles ________ around the world.", "answer": "Darwin",
         "explanation": "Paragraph B says FitzRoy commanded HMS Beagle on the voyage that carried Charles Darwin."},
        {"prompt": "Richardson needed about six ________ to calculate a six-hour forecast.", "answer": "weeks",
         "explanation": "Paragraph C says the calculation took about six weeks."},
        {"prompt": "Lorenz's discovery later became popularly known as the ________ effect.", "answer": "butterfly",
         "explanation": "Paragraph E says the property became popularly known as the butterfly effect."},
        {"prompt": "A collection of forecasts run from slightly different starting conditions is called an ________.", "answer": "ensemble",
         "explanation": "Paragraph E says the resulting collection of forecasts is called an ensemble."},
    ],
}
